### ISSUE TITLE
Supporting x86/x86_64

### ISSUE THREAD

**Issue by hmtheboy154** [tiann/KernelSU#1]
Hi, I just read about the project and I really like it. I am maintaining BlissOS and currently looking for a better root solution than the old [Superuser made by koush](https://git.osdn.net/view?p=android-x86/external-koush-Superuser.git;a=summary). But looking at the codes, it seems like the project [only support arm64 so far](https://github.com/tiann/KernelSU/blob/main/kernel/ksu.c#L224), are there any plan for x86/x86_64 ? I can help you test with x86_64 if you want.

**Comment by tiann** [comment]
x86_64 is feasible and I will try it, but 32bit arch such as   x86 and arm is unsupported

**Comment by hmtheboy154** [comment]
thanks

**Comment by tiann** [comment]
x86_64 support is added in https://github.com/tiann/KernelSU/commit/0d8785ec789ee71392af4bc35aceaeac91c24956, could you test it with the latest commit?

**Comment by hmtheboy154** [comment]
ok, by the way I can only test SELinux in permissive because this is Android-x86

**Comment by hmtheboy154** [comment]
if you make that hack then it might be, iirc we can't even get SurfaceFlinger running with enforcing

**Comment by tiann** [comment]
https://github.com/tiann/KernelSU/commit/280660125faec888b9703eb8fdaa8565c90554fa keeps permissive if it is

**Comment by hmtheboy154** [comment]
![Screenshot_20221213-212222_KernelSU](https://user-images.githubusercontent.com/39849246/207359777-7f8e56c3-4a44-4f12-a21a-a23f43e5265d.png)
![image](https://user-images.githubusercontent.com/39849246/207360128-a8b1acff-afa9-4a94-a701-c0819b46e500.png)

I compiled the kernel module and the app, but the app said not detected......... does that mean I have to compile the `userspace` su too ?

**Comment by tiann** [comment]
If you build the manager app yourself, you should also change this to the apk's signature: https://github.com/tiann/KernelSU/blob/main/kernel/apk_sign.c#L115

**Comment by tiann** [comment]
The signature ensure only the manager can allow/disallow root request, you can try my build(it's the builtin
[app-release.apk.zip](https://github.com/tiann/KernelSU/files/10219127/app-release.apk.zip)
 signature)

**Comment by tiann** [comment]
You can modify this line https://github.com/tiann/KernelSU/blob/main/kernel/apk_sign.c#L79 and read the dmesg to get your EXPECTED_SIZE and EXPECTED_HASH.

**Comment by hmtheboy154** [comment]
> You can modify this line https://github.com/tiann/KernelSU/blob/main/kernel/apk_sign.c#L79 and read the dmesg to get your EXPECTED_SIZE and EXPECTED_HASH.

Thanks

**Comment by hmtheboy154** [comment]
It does but it got mounted in this stage

https://git.osdn.net/view?p=android-x86/bootable-newinstaller.git;a=blob;f=initrd/init;h=f8b5378151f2816afabb622c0b1f4698504f932c;hb=refs/heads/r-x86#l208
https://git.osdn.net/view?p=android-x86/bootable-newinstaller.git;a=blob;f=initrd/scripts/2-mount;h=9cce018c1b672e820720d0ee282946b10ff8b122;hb=refs/heads/r-x86#l10

**Comment by tiann** [comment]
show some `load_allow_list open "/data/adb" failed -2` is OK, when `/data/` is mounted, it wouldn't show

**Comment by tiann** [comment]
> by the way, a small request can you limit the manager app to only compile `x86_64` and `arm64` lib ? to avoid in case the system use x86/arm libs instead

Sure, please try this build: https://github.com/tiann/KernelSU/actions/runs/3709915866

**Comment by hmtheboy154** [comment]
![PXL_20221217_072017482 MP](https://user-images.githubusercontent.com/39849246/208233464-bd7505d4-c4a9-4bcb-8d1e-9f964eb5b079.jpg)
The app does run but su still not working, here is what I got on dmesg.

**Comment by hmtheboy154** [comment]
https://github.com/hmtheboy154/Darkmatter-kernel/tree/umbral
This is how I integrate it into my kernel

**Comment by tiann** [comment]
Does the kernel have `CONFIG_KPROBES` enabled?

**Comment by hmtheboy154** [comment]
> Does the kernel have `CONFIG_KPROBES` enabled?

it haven't, and when compile it show this

```
ld.lld: error: undefined symbol: task_stack_page
>>> referenced by ld-temp.o
>>>               vmlinux.o:(sh_user_path)
```

**Comment by hmtheboy154** [comment]
I'm including linux/sched/task_stack.h right now, I'll see if that help

**Comment by tiann** [comment]
Maybe you should enable `CONFIG_THREAD_INFO_IN_TASK`?

**Comment by hmtheboy154** [comment]
I turn that on already

**Comment by hmtheboy154** [comment]
![Screenshot_20221219-121508_KernelSU](https://user-images.githubusercontent.com/39849246/208425746-2e2698f7-30fe-40e6-a713-bb33360ef219.png)
![Screenshot_20221219-121615_Termux](https://user-images.githubusercontent.com/39849246/208425753-479ee448-385d-4a80-ab78-f8c2c1e04f97.png)

It compiled and works perfectly

I also made a PR, can you check it, I don't know if older kernel have `task_types.h` like this

**Comment by hmtheboy154** [comment]
guess we should close this issue, x86_64 is working now

**Comment by hmtheboy154** [comment]
> Hello, I see that your Android x86 is using Linux kernel 5.15. Do you have any available source code? The 5.15 kernel compiled by myself does not work, and the system graphical interface does not refresh
> 
> [logcat.log](https://github.com/tiann/KernelSU/files/10420796/logcat.log) [dmesg.log](https://github.com/tiann/KernelSU/files/10420797/dmesg.log)

Which Android version are you trying to build ?

**Comment by zsmweb** [comment]
Hello, @tiann @hmtheboy154  
I made a  self-compiled blissos  (Bliss-v16.9.7-x86_64-UNOFFICIAL-gapps-20241013.iso), and install it to virtualbox.
Why the manager app only has the home tab, but no SuperUser and Module tabs?
![image](https://github.com/user-attachments/assets/c1eb4f04-2e0f-469d-ab27-4b24e0f15be1)
[logcat.txt](https://github.com/user-attachments/files/17363764/logcat.txt)
[dmesg.txt](https://github.com/user-attachments/files/17363766/dmesg.txt)
Wish for your help, thks!!!

**Comment by hmtheboy154** [comment]
> Hello, @tiann @hmtheboy154 I made a self-compiled blissos (Bliss-v16.9.7-x86_64-UNOFFICIAL-gapps-20241013.iso), and install it to virtualbox. Why the manager app only has the home tab, but no SuperUser and Module tabs? ![image](https://private-user-images.githubusercontent.com/5425084/376232186-c1eb4f04-2e0f-469d-ab27-4b24e0f15be1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5MDg3ODQsIm5iZiI6MTcyODkwODQ4NCwicGF0aCI6Ii81NDI1MDg0LzM3NjIzMjE4Ni1jMWViNGYwNC0yZTBmLTQ2OWQtYWIyNy00YjI0ZTBmMTViZTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTRUMTIyMTI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTU0OTExY2MxN2U5MTAyN2Q3NjM5YzRiYjY4ZjU4Mzg2OTk4ZjNjNTI0NWM3ZWI0M2Y3MTM1OTdiNDI2YWFjMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.JGdsgOxeTjIlOIOnrcGBQUBu0tqBBRHYy5fYUh0TpAw) [logcat.txt](https://github.com/user-attachments/files/17363764/logcat.txt) [dmesg.txt](https://github.com/user-attachments/files/17363766/dmesg.txt) Wish for your help, thks!!!

test https://github.com/tiann/KernelSU/pull/2102

**Comment by zsmweb** [comment]
@hmtheboy154  working! thks!!!
But i have another question.
Do you have a note for how to porting KernelSU to Blissos that includes all commit?
I build my own aosp with the same kernel with BlissOS (umbral-20230826) . 
but enter boot loop!
[    1.090298] KernelSU: ksu_lsm_hook_init
[    1.091956] KernelSU: sucompat: execve_kp: 0
[    1.093310] KernelSU: sucompat: newfstatat_kp: 0
[    1.094753] KernelSU: sucompat: faccessat_kp: 0
[    1.095666] KernelSU: ksud: execve_kp: 0
[    1.097137] KernelSU: ksud: vfs_read_kp: 0
[    1.100009] KernelSU: ksud: input_handle_event_kp: 0
[    1.111492] xt_time: kernel timezone is -0000
[    1.111817] ipip: IPv4 and MPLS over IPv4 tunneling driver
[    1.112266] gre: GRE over IPv4 demultiplexor driver
[    1.112749] ip_gre: GRE over IPv4 tunneling driver
[    1.113457] Initializing XFRM netlink socket
[    1.113793] NET: Registered PF_INET6 protocol family
[    1.115040] Segment Routing with IPv6
[    1.115419] In-situ OAM (IOAM) with IPv6
[    1.115699] mip6: Mobile IPv6
[    1.115955] sit: IPv6, IPv4 and MPLS over IPv4 tunneling driver
[    1.116726] NET: Registered PF_PACKET protocol family
[    1.117246] NET: Registered PF_KEY protocol family
[    1.117733] l2tp_core: L2TP core driver, V2.0
[    1.118133] l2tp_ppp: PPPoL2TP kernel driver, V2.0
[    1.118580] l2tp_ip: L2TP IP encapsulation support (L2TPv3)
[    1.119171] l2tp_netlink: L2TP netlink interface
[    1.119696] l2tp_eth: L2TP ethernet pseudowire support (L2TPv3)
[    1.120298] l2tp_ip6: L2TP IP encapsulation support for IPv6 (L2TPv3)
[    1.120963] NET: Registered PF_PHONET protocol family
[    1.121483] Key type dns_resolver registered
[    1.122223] IPI shorthand broadcast: enabled
[    1.122516] AVX2 version of gcm_enc/dec engaged.
[    1.122886] AES CTR mode by8 optimization enabled
[    1.123361] sched_clock: Marking stable (1010647010, 111510919)->(1605382623, -483224694)
[    1.124116] registered taskstats version 1
[    1.124390] Loading compiled-in X.509 certificates
[    1.126261] zswap: loaded using pool zstd/zbud
[    1.126808] Key type .fscrypt registered
[    1.127068] Key type fscrypt-provisioning registered
[    1.127707] Btrfs loaded, crc32c=crc32c-intel, zoned=no, fsverity=no
[    1.128670] PM:   Magic number: 12:499:464
[    1.131221] Freeing unused kernel image (initmem) memory: 3652K
[    1.164199] Write protecting the kernel read-only data: 30720k
[    1.173085] Freeing unused kernel image (text/rodata gap) memory: 2036K
[    1.173640] Freeing unused kernel image (rodata/data gap) memory: 636K
[    1.174143] rodata_test: all tests were successful
[    1.174632] Run /init as init process
[    1.189647] random: env: uninitialized urandom read (4 bytes read)
[    1.190687] random: setsid: uninitialized urandom read (4 bytes read)
[    1.191644] random: cttyhack: uninitialized urandom read (4 bytes read)
Detecting Androi[    1.194807] EXT4-fs (sda3): mounted filesystem without journal. Opts: (null). Quota mode: none.
d-x86...try_mount ro /dev/sda3 /mnt
13 blocks
try_mount ro /dev/block/sda6 /mnt
[    1.210823] EXT4-fs (sda6): mounted filesystem without journal. Opts: (null). Quota mode: none.
try_mount rw /dev/sda7 apex
[    1.216019] EXT4-fs (sda7): mounted filesystem without journal. Opts: (null). Quota mode: none.
try_mount ro /dev/sda8 vendor
[    1.218187] EXT4-fs (sda8): mounted filesystem without journal. Opts: (null). Quota mode: none.
Setting up swapspace version 1, size = 8589930496 bytes
[    1.221898] Adding 8388604k swap on /dev/sdb2.  Priority:-2 extents:1 across:8388604k SSFS
try_mount rw /dev/sdb1 ota
[    1.225372] EXT4-fs (sdc3): warning: mounting fs with errors, running e2fsck is recommended
mount: mounting /dev/sdb1 on ota failed: No such file or directory
try_mount rw /dev/sdc3 data
[    1.236971] EXT4-fs (sdc3): recovery complete
[    1.237256] EXT4-fs (sdc3): mounted filesystem with ordered data mode. Opts: (null). Quota mode: none.
try_mount ro /dev/sdd1 pcgame
mount: mounting /dev/sdd1 on pcgame failed: No such file or directory

 Use Alt-F1-F2 or Alt-F7 to switch to debug console.
[    1.240773] EXT4-fs (sdc1): recovery complete
[    1.241058] EXT4-fs (sdc1): mounted filesystem with ordered data mode. Opts: (null). Quota mode: none.
[    1.241986] ext4 filesystem being mounted at /android/oem supports timestamps until 2038 (0x7fffffff)
[    1.258171] init: init first stage started!
[    1.269944] init: Unable to open /lib/modules, skipping module loading.
[    1.270766] init: [libfs_mgr]ReadFstabFromDt(): failed to read fstab from dt
[    1.271504] init: [libfs_mgr]ReadDefaultFstab(): failed to find device default fstab
[    1.272823] init: Failed to create FirstStageMount failed to read default fstab for first stage mount
[    1.273867] init: Failed to mount required partitions early ...
[    1.274444] init: Skipped setting INIT_AVB_VERSION (not in recovery mode)
[    1.275057] KernelSU: /system/bin/init argc: 3
[    1.275444] KernelSU: first arg: second_stage
[    1.275841] KernelSU: /system/bin/init second_stage executed
[    1.276692] KernelSU: SELinux permissive or disabled, apply rules!
[    1.276694] BUG: kernel NULL pointer dereference, address: 0000000000000068
[    1.277937] #PF: supervisor read access in kernel mode
[    1.278738] #PF: error_code(0x0000) - not-present page
[    1.279220] PGD 0 P4D 0
[    1.279440] Oops: 0000 [#1] PREEMPT SMP
[    1.279800] CPU: 5 PID: 1 Comm: init Not tainted 5.15.125-GoogleLTS-xanmod1-umbral #13
[    1.280767] Hardware name: innotek GmbH VirtualBox/VirtualBox, BIOS VirtualBox 12/01/2006
[    1.281636] RIP: 0010:symtab_search+0x10/0x100
[    1.282030] Code: eb 05 b8 ef ff ff ff 48 83 c4 10 5b 41 5c 41 5d 41 5e 41 5f 5d c3 00 00 cc cc 0f 1f 44 00 00 55 48 89 e5 41 57 41 56 41 54 53 <44> 8b 67 08 31 db 45 85 e4 0f 84 d1 00 00 00 49 89 f6 49 89 ff 48
[    1.284687] RSP: 0018:ffffb21b4009bcd8 EFLAGS: 00010202
[    1.285165] RAX: 0000000000000036 RBX: ffffb21b4009bd40 RCX: 7536a2d1ab07f900
[    1.285780] RDX: c0000000ffffefff RSI: ffffffff8b4fac69 RDI: 0000000000000060
[    1.300896] RBP: ffffb21b4009bcf8 R08: 0000000000000000 R09: ffffffff8b86cdc0
[    1.301543] R10: 00000000ffffefff R11: 0000000000000000 R12: 0000000000000060
[    1.302797] R13: 0000000000000008 R14: ffff9313402aa040 R15: 0000000000000000
[    1.303433] FS:  00007eff3cfd5000(0000) GS:ffff931557b40000(0000) knlGS:0000000000000000
[    1.304671] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[    1.305454] CR2: 0000000000000068 CR3: 000000010228b000 CR4: 00000000000506e0
[    1.306208] Call Trace:
[    1.306861]  <TASK>
[    1.307086]  ? __die_body+0x80/0x160
[    1.307426]  ? page_fault_oops+0x2c2/0x3e0
[    1.307848]  ? vsnprintf+0x3ba/0x790
[    1.308195]  ? symtab_search+0x10/0x100
[    1.308765]  ? search_exception_tables+0x113/0x130
[    1.309184]  ? kernelmode_fixup_or_oops+0x124/0x1a0
[    1.309610]  ? __bad_area_nosemaphore+0x72/0x2d0
[    1.310148]  ? console_unlock+0x702/0x880
[    1.310809]  ? bad_area_nosemaphore+0x16/0x20
[    1.311194]  ? do_user_addr_fault+0x455/0x690
[    1.311589]  ? exc_page_fault+0x78/0xf0
[    1.311930]  ? asm_exc_page_fault+0x24/0x30
[    1.312547]  ? symtab_search+0x10/0x100
[    1.312983]  apply_kernelsu_rules+0x5a/0xa80
[    1.313361]  ksu_handle_execveat_ksud+0x145/0x1a0
[    1.313798]  execve_handler_pre.76049+0x38/0x60
[    1.314297]  aggr_pre_handler+0x6d/0x90
[    1.314910]  kprobe_ftrace_handler+0x177/0x220
[    1.315292]  ? do_execveat_common+0x5/0x3c0
[    1.315656]  0xffffffffc01a90e3
[    1.315989] RIP: 0010:do_execveat_common+0x1/0x3c0
[    1.327958] Code: 6d 00 00 44 89 e7 48 89 c6 31 d2 4c 89 f1 45 31 c0 4d 89 f9 53 e8 0f 00 00 00 48 83 c4 08 48 98 5b 41 5c 41 5e 41 5f 5d c3 e8 <ab> fd 32 36 55 48 89 e5 41 57 41 56 41 55 41 54 53 48 83 ec 28 89
[    1.329982] RSP: 0018:ffffb21b4009bf00 EFLAGS: 00000246 ORIG_RAX: 0000000000000000
[    1.331070] RAX: ffff931340b2c000 RBX: 00007efccb3c3250 RCX: 00007efccb3c3250
[    1.331717] RDX: 0000000000000000 RSI: ffff931340b2c000 RDI: 00000000ffffff9c
[    1.332696] RBP: ffffb21b4009bf20 R08: 0000000000000000 R09: 00007efccb3c3400
[    1.333375] R10: 0000000000000fe0 R11: 0000000000000020 R12: 0000000000000000
[    1.334367] R13: 0000000000000000 R14: 00007efccb3c3400 R15: 0000000000000000
[    1.335555]  ? do_execveat_common+0x5/0x3c0
[    1.335937]  ? __x64_sys_execve+0x3e/0x50
[    1.336535]  ? do_execveat_common+0x5/0x3c0
[    1.336899]  ? __x64_sys_execve+0x3e/0x50
[    1.337277]  do_syscall_64+0x4a/0xa0
[    1.337612]  entry_SYSCALL_64_after_hwframe+0x61/0xcb
[    1.338113] RIP: 0033:0x7eff3b6b7207
[    1.338712] Code: cc cc cc 53 89 fb e8 c8 d9 01 00 89 18 48 c7 c0 ff ff ff ff 5b c3 cc cc cc cc cc cc cc cc cc cc cc cc cc b8 3b 00 00 00 0f 05 <48> 3d 01 f0 ff ff 72 09 f7 d8 89 c7 e8 c8 ff ff ff c3 0f 1f 80 00
[    1.340719] RSP: 002b:00007ffdaecc9618 EFLAGS: 00000202 ORIG_RAX: 000000000000003b
[    1.341462] RAX: ffffffffffffffda RBX: 0000000000000005 RCX: 00007eff3b6b7207
[    1.342472] RDX: 00007efccb3c3400 RSI: 00007efccb3c3250 RDI: 0000557d8fcedcef
[    1.343366] RBP: 0000000000000002 R08: 0000000000000010 R09: 0000000000000001
[    1.344221] R10: 0000000000000000 R11: 0000000000000202 R12: 00007efcdb3cbd00
[    1.345485] R13: 00007efe0b3ce010 R14: 00007ffdaecc9720 R15: 00007ffdaecc9680
[    1.346623]  </TASK>
[    1.346822] Modules linked in:
[    1.347108] CR2: 0000000000000068
[    1.347533] ---[ end trace cda66bc331bb30c8 ]---
[    1.359023] RIP: 0010:symtab_search+0x10/0x100
[    1.359525] Code: eb 05 b8 ef ff ff ff 48 83 c4 10 5b 41 5c 41 5d 41 5e 41 5f 5d c3 00 00 cc cc 0f 1f 44 00 00 55 48 89 e5 41 57 41 56 41 54 53 <44> 8b 67 08 31 db 45 85 e4 0f 84 d1 00 00 00 49 89 f6 49 89 ff 48
[    1.361595] RSP: 0018:ffffb21b4009bcd8 EFLAGS: 00010202
[    1.362043] RAX: 0000000000000036 RBX: ffffb21b4009bd40 RCX: 7536a2d1ab07f900
[    1.363076] RDX: c0000000ffffefff RSI: ffffffff8b4fac69 RDI: 0000000000000060
[    1.363738] RBP: ffffb21b4009bcf8 R08: 0000000000000000 R09: ffffffff8b86cdc0
[    1.364936] R10: 00000000ffffefff R11: 0000000000000000 R12: 0000000000000060
[    1.365805] R13: 0000000000000008 R14: ffff9313402aa040 R15: 0000000000000000
[    1.366841] FS:  00007eff3cfd5000(0000) GS:ffff931557b40000(0000) knlGS:0000000000000000
[    1.367675] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[    1.368195] CR2: 0000000000000068 CR3: 000000010228b000 CR4: 00000000000506e0
[    1.369128] note: init[1] exited with preempt_count 1
[    1.369576] Kernel panic - not syncing: Attempted to kill init! exitcode=0x00000009
[    1.370623] Kernel Offset: 0x8a00000 from 0xffffffff81000000 (relocation range: 0xffffffff80000000-0xffffffffbfffffff)
[    1.371659] Rebooting in 5 seconds..

**Comment by hmtheboy154** [comment]
> @hmtheboy154 working! thks!!! But i have another question. Do you have a note for how to porting KernelSU to Blissos that includes all commit? I build my own aosp with the same kernel with BlissOS (umbral-20230826) . but enter boot loop! 

I don't build 5.15 anymore so idk, you have to switch to newer ver

**Comment by 2chiefk** [comment]
There's nothing to do with Superuser it has to do with bootloader unlocked
everybody don't even need to be rooted to do that just need to put a loader
unlocked on your device and all of it's unlocked cuz when you're turning on
your Android you'll say you're unlocked every time you turn on your device
this is how you know you're bootloaders actually unlocked cuz it tells you
every time you turn on your device if it doesn't then it's not really
unlocked that's your issue everybody I'm pretty sure and if you don't
believe me I will make a video and post it right here so you all can see
this every time I turn on my phone it says bootloader unlocked so why are
you almost seeing that if you're not seeing that this software won't work
that's correct has nothing to do with super use or anything like that

**Comment by Mercafed** [comment]
deberian colocar una .img precompilada no de android x86 con el kernel con soporte para kernelSu ¿no?
