### ISSUE TITLE
Configs are not going into effect for KernelSU

### ISSUE THREAD

**Issue by akash07k** [tiann/KernelSU#100]
I'm trying to build my kernel with KernelSU and have defined the config in the device_defconfig file as per the documentation.
But still, when I'm trying to build it, I'm getting the error: #error("`CONFIG_KPROBES` must be enabled for KernelSU!")
Any pointers on this please?
Below are the flags which I'm putting in my defconfig file:
```
CONFIG_KPROBES=y
CONFIG_HAVE_KPROBES=y
CONFIG_KPROBE_EVENTS=y

```

**Comment by hmtheboy154** [comment]
your kernel doesn't have kprobes ?

**Comment by akash07k** [comment]
Oh, so what can be done in this case?
I followed the second way too about patching the files manually, but after that too I get the same error.
> your kernel doesn't have kprobes ?

**Comment by hmtheboy154** [comment]
check Kconfig and remove depends on Kprobes

**Comment by akash07k** [comment]
You mean KernelSU configs?
> check Kconfig and remove depends on Kprobes

**Comment by akash07k** [comment]
> You mean KernelSU configs?
> 
> > check Kconfig and remove depends on Kprobes

I removed that. Still the same error regarding Kprobes. 
```
config KSU
	tristate "KernelSU module"
	default y
		depends on OVERLAY_FS
	help
	This is the KSU privilege driver for android system.

config KSU_DEBUG
	tristate "KernelSU module debug mode"
	default n
	depends on KSU
	help
	This enables debug mode for KSU
```

**Comment by Ylarod** [comment]
If you append this to your defconfig, you should `make xxx_defconfig`
Kconfig is for `make menuconfig`.
If you patch your kernel, comment this `#error` in code

**Comment by akash07k** [comment]
Ok, I'm trying.
actually my device's defconfig file name is `munch_defconfig` so I was adding these configs to that file.
Should I create another defconfig file with these values if I don't want to comment the error in the code?

> If you append this to your defconfig, you should `make xxx_defconfig` Kconfig is for `make menuconfig`. If you patch your kernel, comment this `#error` in code

**Comment by natsumerinchan** [comment]
Have you enabled `CONFIG_MODULES`? It is required for KPROBE.

**Comment by akash07k** [comment]
Ah, no, I will try that. for now I manually patched the source.
