### ISSUE TITLE
自己编译的内核启动后驱动全部失效

### ISSUE THREAD

**Issue by yejunjie10311031** [tiann/KernelSU#1001]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
已经把deconfig文件里与CONFIG_MODULE_SIG有关的全部注释了,且在module.c里加入了flags |= MODULE_INIT_IGNORE_MODVERSIONS;
        flags |= MODULE_INIT_IGNORE_VERMAGIC;
但启动后依然全部驱动失效

**Smartphone (please complete the following information):**
 - Device: Motorola edge s
 - OS: android 12.1 pixel experience
 - kernel:https://github.com/PixelExperience-Devices/kernel_motorola_sm8250/tree/twelve

**Comment by tiann** [comment]
与 KernelSU 无关。
