### ISSUE TITLE
KernelSU 模块更新对话框高度异常

### ISSUE THREAD

**Issue by setcurl** [tiann/KernelSU#1006]
ksu v0.6.8 对话框没限制高度，md过长就会导致看不见下载按钮
![Screenshot_2023-10-05-18-40-05-430_me weishu kernelsu](https://github.com/tiann/KernelSU/assets/78637344/0965c422-eb72-41ef-a9d9-5a85da491aa4)

**Comment by meiser79** [comment]
duplicate of #1005
