### ISSUE TITLE
希望能完善App Profile

### ISSUE THREAD

**Issue by purplewinexd** [tiann/KernelSU#1007]
### Describe your problem.

希望kernelSU做一个类似：lsposed的推荐应用的，推荐权限功能
若是可以将App Profile的功能也作用于KSU模块上
那就会非常的好
以及希望能汉化一下App Profile的权能（？）界面

**Comment by Lingxiiii** [comment]
希望能多做一个在线规则仓库，或许可以让用户自定义规则仓库地址（？）

**Comment by tiann** [comment]
https://github.com/tiann/KernelSU/commit/9b294682b0ede778dcb00b73525c995d40fd9010
