### ISSUE TITLE
Dumping/splitting image failed. Aborting...

### ISSUE THREAD

**Issue by ethical-haquer** [tiann/KernelSU#1010]
### Describe your problem.

I am trying to get KernelSU working with @KonstaT's [Android TV Lineage OS build for the Raspberry Pi 4](https://xdaforums.com/t/dev-rom-unofficial-lineageos-20-android-13-for-raspberry-pi-4-b.4516545/).

However, when I try to flash the AnyKernel3-android13-5.15.94_2023-05.zip in TWRP it fails with:
```
Updating partition details...
...done
Full SELinux support is present.
Installing zip file '/sdcard/Documents/AnyKernel13-android13-5.15.94_2023-05.zip'
Unmounting System...

KernelSU by KernelSU Developers

AnyKernel3 by osmOsis @ xda-developers


Installing...
/dev/block/by-name/boot

  -> ksu_supported: true
  
Dumping/splitting image failed. Aborting...
Updater process ended with ERROR: 1
Error installing zip file '/sdcard/Documents/AnyKernel13-android13-5.15.94_2023-05.zip'
Updating partition details...
...done
```

The kernel version of the build I'm using is: '5.15.94-v8-g0487e900bf08'

The KernelSU Manager app also says my device is supported.

For all I know it may not even be an issue with KernelSU itself.

If you need any more details I will try my best to provide it for you! TIA.

**Comment by ethical-haquer** [comment]
Hmm, line 138 of [this file](https://github.com/osm0sis/AnyKernel3/blob/master/tools/ak3-core.sh) could be what's causing this error, so maybe it's actually AnyKernel3 detecting an issue. (I can't figure out what that elif statement is for :blush: )

**Comment by osm0sis** [comment]
You need to post your log.

**Comment by ethical-haquer** [comment]
> You need to post your log.

[anykernel3-1969-12-31_190034-debug.zip](https://github.com/tiann/KernelSU/files/12842417/anykernel3-1969-12-31_190034-debug.zip)

[anykernel3-1969-12-31_190034-debug.002.zip](https://github.com/tiann/KernelSU/files/12842419/anykernel3-1969-12-31_190034-debug.002.zip)

[anykernel3-1969-12-31_190034-debug.003.zip](https://github.com/tiann/KernelSU/files/12842420/anykernel3-1969-12-31_190034-debug.003.zip)

Here is the debug.tgz, extracted and then zipped into three files. Did I already provide the log you need, or is that something else?

**Comment by KonstaT** [comment]
While having no idea about KernelSU or what you're trying to achieve, my Raspberry Pi builds don't have boot image to split. There's a boot partition instead. Kernel is /boot/Image and ramdisk is /boot/ramdisk.img.

If you want to put something into the kernel, compile the kernel.
https://github.com/lineage-rpi/android_kernel_manifest/tree/lineage-20.0

**Comment by osm0sis** [comment]
That would explain it.

**Comment by osm0sis** [comment]
Examining the boot.img dumped in your ak3 debug zip, whatever that is is also not even Android format, hence the error. So, long story short, Raspberry Pi 4 is not a typical Android device, hence not supported by AK3.

**Comment by ethical-haquer** [comment]
> While having no idea about KernelSU or what you're trying to achieve, my Raspberry Pi builds don't have boot image to split. There's a boot partition instead. Kernel is /boot/Image and ramdisk is /boot/ramdisk.img.
> 
> If you want to put something into the kernel, compile the kernel. https://github.com/lineage-rpi/android_kernel_manifest/tree/lineage-20.0

Thanks for explaining this to me, @KonstaT and @osm0sis. I was wondering if I would need to compile it myself. I'm attempting to use KernelSU to root the Pi instead of Magisk, as part of trying to get Prime Video Android TV to play things on your builds.

**Comment by osm0sis** [comment]
I don't see how Magisk would flash on it either, probably would need to manually patch the ramdisk.img or something.

**Comment by osm0sis** [comment]
Makes sense. So you should close this issue, it's not really anybody here's problem. 😛
