### ISSUE TITLE
[Suggestion] Consider only keep latest SubLevel version in GitHub release

### ISSUE THREAD

**Issue by sky96111** [tiann/KernelSU#1016]
### Is your feature request related to a problem? Please describe.

The GitHub release contains more than 100 asset files, which can be difficult to find what you need amongst such many files.
And the number of files keeps growing.

Since SubLevel doesn't affect the KMI version, I think keep old SubLevel version is meaningless.

### Describe the solution you'd like.

Only upload latest SubLevel version in next release.

### Describe alternatives you've considered.

none

**Comment by tiann** [comment]
We used to do this, but some machines had to have an exact version match and later revert.
