### ISSUE TITLE
When I run setup.sh I get: fatal: empty string is not a valid pathspec. please use . instead if you meant to match all paths

### ISSUE THREAD

**Issue by wshamroukh** [tiann/KernelSU#1030]
**Describe the bug**
When I run the command `curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -`  on my kernel folder, I get the following error:
`fatal: empty string is not a valid pathspec. please use . instead if you meant to match all paths`

It specifically fails in this piece of code:
```
if [ -z "${1-}" ]; then
    git checkout "$(git describe --abbrev=0 --tags)"
else
    git checkout "$1"
fi
```

**Screenshots**
![image](https://github.com/tiann/KernelSU/assets/91495448/874c032b-3ba1-4acd-886c-c5be1e4bcb20)

**Comment by tiann** [comment]
rm -rf KernelSU and try it again.

**Comment by wshamroukh** [comment]
> rm -rf KernelSU and try it again.

Oh ok. It worked.
Just a question. After the mentioned script to upgrade KSU, the only thing that is updated/added is the KernelSU folder. Is that it? 
Afterwards, I do update the KSU_GIT_VERSION under drivers/kernelsu/Makefile
Am I doing this right?

**Comment by tiann** [comment]
The only thing you need to do is update KernelSU folder, not need to update KSU_GIT_VERSION manually.
