### ISSUE TITLE
[Feature] KernelSU flashable injector for unsupported stock kernel

### ISSUE THREAD

**Issue by Nixsuki** [tiann/KernelSU#1031]
### Is your feature request related to a problem? Please describe.

Hi, I wanted to know if possible to add a flashable injector to stock kernel on unsupported kernels?

### Describe the solution you'd like.

Solution is to be universally use KernelSU for all stock kernels and CustomROMs seamlessly.

### Describe alternatives you've considered.

Consider that all Open Source enthusiasts are using KernelSU as root solution for Custom ROMs now.

**Comment by tiann** [comment]
For non GKI kernel, no plan. For GKI kernel, #928
