### ISSUE TITLE
undefined reference to '...'

### ISSUE THREAD

**Issue by Vaz15k** [tiann/KernelSU#1033]
Hello!!
Since version 0.6.8 was released, I'm having problems at the end of the kernel compilation...
I'm using manual compilation, not kprobes, (I already tried to implement the ksu code from the beginning).
In defconfig, everything from krpobes is disabled, (I also tried to compile using krpobes, but when I flash it on the device, ksu shows it as not supported).
I'm using the latest version of ksu, and I've already tried the dev branch...

Device: Samsung a70
Kernel: 4.14.190

My kernel repo:
https://github.com/Vaz15k/kernelSU-A70q

Below is the full error

aarch64-linux-gnu-ld: fs/open.o: in function `SYSC_faccessat':
/root/ksu/kernelSU-A70q/out/../fs/open.c:375: undefined reference to `ksu_handle_faccessat'
aarch64-linux-gnu-ld: fs/read_write.o: in function `vfs_read':
/root/ksu/kernelSU-A70q/out/../fs/read_write.c:444: undefined reference to `ksu_vfs_read_hook'
aarch64-linux-gnu-ld: fs/read_write.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `ksu_vfs_read_hook' which may bind externally can not be used when making a shared object; recompile with -fPIC
/root/ksu/kernelSU-A70q/out/../fs/read_write.c:444:(.text+0x800): dangerous relocation: unsupported relocation
aarch64-linux-gnu-ld: /root/ksu/kernelSU-A70q/out/../fs/read_write.c:444: undefined reference to `ksu_vfs_read_hook'
aarch64-linux-gnu-ld: /root/ksu/kernelSU-A70q/out/../fs/read_write.c:445: undefined reference to `ksu_handle_vfs_read'
aarch64-linux-gnu-ld: fs/stat.o: in function `vfs_statx':
/root/ksu/kernelSU-A70q/out/../fs/stat.c:175: undefined reference to `ksu_handle_stat'
aarch64-linux-gnu-ld: fs/exec.o: in function `do_execveat_common':
/root/ksu/kernelSU-A70q/out/../fs/exec.c:1863: undefined reference to `ksu_execveat_hook'
aarch64-linux-gnu-ld: fs/exec.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `ksu_execveat_hook' which may bind externally can not be used when making a shared object; recompile with -fPIC
/root/ksu/kernelSU-A70q/out/../fs/exec.c:1863:(.text+0x1eb8): dangerous relocation: unsupported relocation
aarch64-linux-gnu-ld: /root/ksu/kernelSU-A70q/out/../fs/exec.c:1863: undefined reference to `ksu_execveat_hook'
aarch64-linux-gnu-ld: /root/ksu/kernelSU-A70q/out/../fs/exec.c:1866: undefined reference to `ksu_handle_execveat_sucompat'
aarch64-linux-gnu-ld: /root/ksu/kernelSU-A70q/out/../fs/exec.c:1864: undefined reference to `ksu_handle_execveat'
aarch64-linux-gnu-ld: drivers/input/input.o: in function `input_handle_event':
/root/ksu/kernelSU-A70q/out/../drivers/input/input.c:379: undefined reference to `ksu_input_hook'
aarch64-linux-gnu-ld: drivers/input/input.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `ksu_input_hook' which may bind externally can not be used when making a shared object; recompile with -fPIC
/root/ksu/kernelSU-A70q/out/../drivers/input/input.c:379:(.text+0x861c): dangerous relocation: unsupported relocation
aarch64-linux-gnu-ld: /root/ksu/kernelSU-A70q/out/../drivers/input/input.c:379: undefined reference to `ksu_input_hook'
aarch64-linux-gnu-ld: /root/ksu/kernelSU-A70q/out/../drivers/input/input.c:380: undefined reference to `ksu_handle_input_handle_event'
make[1]: *** [/root/ksu/kernelSU-A70q/Makefile:1207: vmlinux] Error 1
make[1]: Leaving directory '/root/ksu/kernelSU-A70q/out'
make: *** [Makefile:146: sub-make] Error 2

**Comment by tiann** [comment]
You skipped some steps here: https://kernelsu.org/guide/how-to-integrate-for-non-gki.html#manually-modify-the-kernel-source

**Comment by Vaz15k** [comment]
> You skipped some steps here: https://kernelsu.org/guide/how-to-integrate-for-non-gki.html#manually-modify-the-kernel-source

I did all the steps and redid them too, version 0.6.7 is compiling normally...
Only 0.6.8 and 0.6.9 are not...

**Comment by RashadGasimly** [comment]
hello, also i got these errors

**Comment by Meghthedev** [comment]
+1, same error. 4.14.220 kernel version

**Comment by Meghthedev** [comment]
> You skipped some steps here: https://kernelsu.org/guide/how-to-integrate-for-non-gki.html#manually-modify-the-kernel-source

Can you check once please, still facing the issue, stuck on 0.6.7. How is it possible that the sane source works for 6.7 but not for newer ones? Kernel version is 4.14.220

**Comment by Vaz15k** [comment]
> > You skipped some steps here: https://kernelsu.org/guide/how-to-integrate-for-non-gki.html#manually-modify-the-kernel-source
> 
> Can you check once please, still facing the issue, stuck on 0.6.7. How is it possible that the same source works for 6.7 but not for newer ones? Kernel version is 4.14.220

check if you have the following information active in defconfig: 
CONFIG_KSU=y 
CONFIG_OVERLAY_FS=Y

If you are trying to do the version with krprobes, also check if the following are active: 
CONFIG_KPROBES=y
CONFIG_HAVE_KPROBES=y
CONFIG_KPROBE_EVENTS=y
CONFIG_KPROBE_EVENT=y

If not, activate them or add them in the case of CONFIG_KSU

**Comment by Meghthedev** [comment]
> > > You skipped some steps here: https://kernelsu.org/guide/how-to-integrate-for-non-gki.html#manually-modify-the-kernel-source
> > 
> > Can you check once please, still facing the issue, stuck on 0.6.7. How is it possible that the same source works for 6.7 but not for newer ones? Kernel version is 4.14.220
> 
> check if you have the following information active in defconfig: 
> CONFIG_KSU=y 
> CONFIG_OVERLAY_FS=Y
> 
> If you are trying to do the version with krprobes, also check if the following are active: 
> CONFIG_KPROBES=y
> CONFIG_HAVE_KPROBES=y
> CONFIG_KPROBE_EVENTS=y
> CONFIG_KPROBE_EVENT=y
> 
> If not, activate them or add them in the case of CONFIG_KSU 

Enabling config_ksu and overlay_fs dosent help, I am doing it without kprobes, ie manually

**Comment by Vaz15k** [comment]
> > > > You skipped some steps here: https://kernelsu.org/guide/how-to-integrate-for-non-gki.html#manually-modify-the-kernel-source
> > > 
> > > 
> > > Can you check once please, still facing the issue, stuck on 0.6.7. How is it possible that the same source works for 6.7 but not for newer ones? Kernel version is 4.14.220
> > 
> > 
> > check if you have the following information active in defconfig:
> > CONFIG_KSU=y
> > CONFIG_OVERLAY_FS=Y
> > If you are trying to do the version with krprobes, also check if the following are active:
> > CONFIG_KPROBES=y
> > CONFIG_HAVE_KPROBES=y
> > CONFIG_KPROBE_EVENTS=y
> > CONFIG_KPROBE_EVENT=y
> > If not, activate them or add them in the case of CONFIG_KSU
> 
> Enabling config_ksu and overlay_fs dosent help, I am doing it without kprobes, ie manually

So the only thing left to check is whether kprobes has all its options set to "is not set"
