### ISSUE TITLE
不指定 boot 分区槽位直接刷入内核镜像可能损坏系统

### ISSUE THREAD

**Issue by ky-bd** [tiann/KernelSU#1035]
**Describe the bug**

在 MIUI 14.0.31 直接使用 `fastboot flash boot android13-5.15.74_2023-01-boot.img` 刷入 KernelSU 内核会损坏系统，开机提示 "Your device is corrupt. It cant be trusted and may work properly. Visit this link on another device: g.co\ABH" ，无法启动，此时即使刷入 MIUI 原版线刷包中的 boot.img 也无法修复。刷入 KSU 镜像之前已使用 `fastboot boot` 验证过该镜像可以启动， recovery 和 fastboot 也还能正常工作。

使用原版线刷包中 `flash_all_except_storage` 不清数据重新刷机后可以正常启动，重新进入 fastboot 后使用 `fastboot flash boot_ab android13-5.15.74_2023-01-boot.img` ，此时可以刷入 KSU 并进入系统。在之前的 MIUI 版本中使用 `fastboot flash boot` 也可以正常刷入，不会出现此问题。

这可能不是 KSU 的 bug，目前搜索到在 https://blog.drxian.cn/archives/507 这篇博文中提到， 8G2 机型上 fastboot flash 必须带有分区槽位，否则可能损坏。但尚不清楚为何先前版本不指定槽位也可以正常刷入，以及不指定槽位时具体损坏了哪个分区。

**To Reproduce**

1. 安装 MIUI 14.0.31
2. `adb reboot bootloader` 进入 fastboot
3. `fastboot flash boot android13-5.15.74_2023-01-boot.img` 刷入 KernelSU 内核
4. `fastboot reboot`

**Expected behaviour**

希望在文档中加入说明，提醒刷入内核镜像时可能需要指定 boot 分区槽位，以及相应救砖方法。

**Screenshots**

无

**Smartphone (please complete the following information):**

 - Device: 小米 13 (fuxi)
 - OS: MIUI
 - Version 14.0.31.0 稳定版，内核 5.15.74

**Additional context**

再次验证不能晚上搞机，差点要整通宵 😓

**Comment by tiann** [comment]
自己整蛊自己解决。

**Comment by mengguyi** [comment]
> 回想了一下，可能不是更新 MIUI 导致的，因为系统更新之后我应该重新刷过 KSU 0.6.7 。
> 
> 倒有可能是和 Magisk 兼容的问题，之前是 KSU 0.6.7 + Magisk 26.3 ，按照上面说的重新线刷和 KSU 0.6.9 之后，给 Magisk App root 权限，自动安装 Magisk 后会不断重启，然后进入 fastboot ，`fastboot getvar all` 可见 `(bootloader) slot-unbootable:a:yes` ，需要重刷 init_boot 和 recovery 分区才能启动；如果用 Magisk App 修补 KSU 0.6.9 镜像后手动刷入，那么能正常启动，但是 Magisk App 识别不到 Magisk 。

这种情况我遇到过，一次是给小米13Ultra刷boot忘记解压了，另一次是给13u刷了PE后直接刷KernelSU releases里的内核导致这样的问题。

出现这样的问题大概率是刷入的 boot 和 ROM 里给的 boot 压缩算法不一样。或者是刷入的 boot 压根无法识别。
并且使用 fastboot boot xxx 命令启动后也会出现这样的错误。且强制重启无法解决。只能重刷 ROM
