### ISSUE TITLE
Skipping insecure file: Try again

### ISSUE THREAD

**Issue by minhdanhsc** [tiann/KernelSU#1036]
In the system init, I cannot load files when integrating kernelSU
It gives error: Skipping insecure file: Try again

[    4.043573] init: processing action (post-fs-data) from (/vendor/etc/init/android.hardware.neuralnetworks@1.3-service-qti.rc:13)
[    4.044436] init: processing action (post-fs-data) from (/vendor/etc/init/hostapd.android.rc:9)
[    4.045892] init: processing action (post-fs-data) from (/vendor/etc/init/vendor.google.wifi_ext@1.0-service.rc:7)
[    4.046790] init: processing action (load_persist_props_action) from (/system/etc/init/hw/init.rc:462)
[    4.047213] init: Couldn't load file '/data/config/default.prop': Skipping insecure file: Try again

**Comment by tiann** [comment]
Nothing to do with KernelSU.
