### ISSUE TITLE
管理器未识别到kernelsu已经安装

### ISSUE THREAD

**Issue by Weizili114514** [tiann/KernelSU#1037]
因为恶意程序接管管理器的漏洞，我更新了最新的ci版内核，然后更新了最新版的管理器，然后发现管理器显示未安装，但是之前授权的程序可以正常使用root权限
小米12s ultra
miui14.0.23.10.8dev
![Screenshot_2023-10-14-02-50-13-287_com miui home](https://github.com/tiann/KernelSU/assets/95065474/bdcbef11-329d-4224-98db-6ac853d82781)

**Comment by tiann** [comment]
你要用 main 分支的 ci 包, pr 的不行。
