### ISSUE TITLE
Galaxy S23 not booting with kernelsu

### ISSUE THREAD

**Issue by switch-gott** [tiann/KernelSU#1038]
Hi,
i have a small problem while booting galaxy s23 kernel with kernesu inside.

Without compiling kernelsu, the kernel is starting without problems.

First time i start the kernel, the devices boots up. But after 3 reboots, the device ends up with bootloop.

If you flash the kernel boot.img with twrp and boot the os, the sammy logo appears, but after the device is rebooting.

So entering the OS is not possible with kernelsu.

Device:
Samsung Galaxy S23 
Android 13

Kernel build: 5.15.78

Realy thanks for help

**Comment by tiann** [comment]
Search the issues first.
