### ISSUE TITLE
OnePlus ColorOS14 5.15.94 kernel can't use anykernel.zip

### ISSUE THREAD

**Issue by Andyanna** [tiann/KernelSU#1039]
My phone is OnePlus Ace2 Pro, and the factory version kernel is Coloros13 for Android 13. The kernel version is 5.15.74. Previously, I used IMG and anykernel.zip from your Github warehouse to use the kernelsu software normally when swiping into my phone. A few days ago, I upgraded Coloros14 based on Android 14 and found that its kernel has been upgraded to 5.15.94. So, I tried refreshing the zip and IMG, but they couldn't boot up properly. After swiping the first screen of the boot card, I have also tried to turn off the strict kernel policy (AVB verification) and restore the official boot. img image to boot normally. Please provide the latest technical support update for this ColorOS14 system. We really want to use kernelsu on ColorOS14

**Comment by Andyanna** [comment]
I have tried two manual kernel compilation methods provided on your page, but none of the compiled kernels work properly. I have searched for many posts on Ku'an, but there is no solution. Some netizens have said that Oppo's engineers have made magic changes to the kernel of coloros14

**Comment by tiann** [comment]
we can do nothing without logs

**Comment by Atroc-X** [comment]
https://github.com/tiann/KernelSU/releases/download/v0.7.0/AnyKernel3-android13-5.15.119_2023-09.zip
It is possible to use this kernel and it will work fine.

**Comment by 949331213** [comment]
终于理解 color os14 酷安的评分怎么来的了
