### ISSUE TITLE
内置zygisk和shamiko开关这一对，这会非常方便[Feature]

### ISSUE THREAD

**Issue by GWLCZY** [tiann/KernelSU#1040]
### Is your feature request related to a problem? Please describe.

像面具那样，直接内置zygisk和shamiko开关，符合主流用户。

### Describe the solution you'd like.

，

### Describe alternatives you've considered.

，

### Additional context

，

**Comment by tiann** [comment]
为什么你要把自己定义为“主流”。

**Comment by GWLCZY** [comment]
> 为什么你要把自己定义为“主流”。

有没有可能，我并没有把自己定义为主流，而是你主观强加的。我仅仅是描述了一下现状而已，内核root既然是下一代root，自然要继承大量magisk用户，这不能否认吧，尽管root有一定门槛，但依然是小白用户占大多数，而使用magisk的小白用户，不装lsp的很少，只有少数开发者或者没需求的人才不用，希望开发者不要为了否定而否定，不想加又没人逼你。我也仅仅提出一个想法而已，莫要存在那么大的攻击性

**Comment by tiann** [comment]
我只是在陈述事实，怎么就攻击了？

如果你认为是主流，就拿出数据来，莫要一上来就说是主流；质疑一下都不行是吧？

**Comment by tiann** [comment]
> 内核root既然是下一代root，自然要继承大量magisk用户，这不能否认吧

我什么时候说 KernelSU 是下一代 root 了，有什么时候说要继承 magisk 用户了？这一切都是你自作多情。自己的想法不要强加到别人头上，OK？

**Comment by GWLCZY** [comment]
> > 内核root既然是下一代root，自然要继承大量magisk用户，这不能否认吧
> 
> 我什么时候说 KernelSU 是下一代 root 了，又什么时候说要继承 magisk 用户了？这一切都是你自作多情。自己的想法不要强加到别人头上，OK？

自己说的完美隐藏，最少5.10，现在就不认了，这不就是我叫鲁迅不叫周树人吗，真幽默。而且我并没有说是你说的啊，难不成你的意思是内核root是在开倒车？自己喜欢说别人还说别人臆想哈哈哈

**Comment by GWLCZY** [comment]
> 我只是在陈述事实，怎么就攻击了？
> 
> 如果你认为是主流，就拿出数据来，莫要一上来就说是主流；质疑一下都不行是吧？

你认为不是主流，你的证据呢，你的反驳没证据行吗，开发者

**Comment by tiann** [comment]
"谁主张，谁举证“，你说是主流需要你自己证明。

很简单的道理，按照你的逻辑，我说我是你爹，你说不是；那你要给出不是的理由，对不？
