### ISSUE TITLE
Modules disappearing from the app KernelSu

### ISSUE THREAD

**Issue by Amoulier** [tiann/KernelSU#1045]
**Describe the bug**
The application of kernelSu do not recognize the modules as installed,
[KernelSU_bugreport_2023-10-15_19_29.tar.gz](https://github.com/tiann/KernelSU/files/12910893/KernelSU_bugreport_2023-10-15_19_29.tar.gz)
 after 2 min of the devices been rebooted.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install Modules
2. Reboot devices
3. Wait 2 minutes
4. The installed modules desapear from de kernelsu apk

**Expected behaviour**
abilitie to unistall or desable the modules without  the need of rebooting the device prior to desinstalling or desabling

**Smartphone (please complete the following information):**
 - Device: Pixel6 Pro
 - OS: andorid13 and android14

**Comment by tiann** [comment]
Do you use some modules that may affect other modules? please uninstall it and try again.

**Comment by Amoulier** [comment]
Found the culprit is an application (Pixel Launcher Mods), just installing it makes the modules disappear... since the last kernelsu update.

**Comment by tiann** [comment]
Please disable "Umount modules by default" in Settings or disable "Umount modules" in App Profile for "Pixel Launcher".

**Comment by Weltolk** [comment]
> Please disable "Umount modules by default" in Settings or disable "Umount modules" in App Profile for "Pixel Launcher".

这问题目前依旧存在

**Comment by TigerBeanst** [comment]
> > Please disable "Umount modules by default" in Settings or disable "Umount modules" in App Profile for "Pixel Launcher".
> 
> 这问题目前依旧存在

问下你是啥设备啥系统（

**Comment by Weltolk** [comment]
> > > Please disable "Umount modules by default" in Settings or disable "Umount modules" in App Profile for "Pixel Launcher".
> > 
> > 这问题目前依旧存在
> 
> 问下你是啥设备啥系统（

一加 13 ColorOS15.0
