### ISSUE TITLE
模块突然消失

### ISSUE THREAD

**Issue by Skwater** [tiann/KernelSU#1049]
**Describe the bug**
使用时突然发现模块没有生效，进入管理器发现模块列表为空

**To Reproduce**
使用中突然发生，无法复现

**Expected behaviour**
模块全部失效，管理器内模块列表为空，使用mt管理器查看模块目录为空，重启后恢复正常

**Smartphone (please complete the following information):**
 - Device: Redmi K50(rubens)
 - OS: Android 13(MIUI 14.0.7)

**Additional context**
[KernelSU_bugreport_2023-10-16_17_14.tar.gz](https://github.com/tiann/KernelSU/files/12936483/KernelSU_bugreport_2023-10-16_17_14.tar.gz)

**Comment by tiann** [comment]
你可以把日志之家传到 github 上吗？百度要登陆而且还限速。

**Comment by Skwater** [comment]
[KernelSU_bugreport_2023-10-16_17_14.tar.gz](https://github.com/tiann/KernelSU/files/12935949/KernelSU_bugreport_2023-10-16_17_14.tar.gz)

**Comment by tiann** [comment]
你这个日志似乎不是复现之后抓取的，看日志内容是正常的。
