### ISSUE TITLE
安卓14(coloros14）使用fastboot刷入android12-5.10.168_2023-05-boot.img无限重启

### ISSUE THREAD

**Issue by ConneRSama** [tiann/KernelSU#1051]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
4. See the error

**Expected behaviour**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by wxt1221** [comment]
It may cause by your device. There might be some problems with GKI kernel. Check if you choose the correct kernel. Then, you can try AnyKernel.

**Comment by fkueyu** [comment]
遇到同样的问题，无论直接使用提供的内核刷入，还是提取卡刷包的boot用AnyKernel里的内核进行修补后刷入，都是无限重启，手机型号为一加ACE 2V，系统为coloros14。但用magisk delta修补boot刷入后magisk delta能正常工作。

**Comment by wxt1221** [comment]
[https://source.android.com/docs/core/architecture/kernel/gki-android12-5_10-release-builds?hl=zh-cn](https://source.android.com/docs/core/architecture/kernel/gki-android12-5_10-release-builds?hl=zh-cn)

这里面去下不带gki的包试试呢

**Comment by fkueyu** [comment]
https://source.android.com/docs/core/architecture/kernel/gki-android12-5_10-release-builds?hl=zh-cn

下载了这个版本，gki-certified-boot-android12-5.10-2023-04_r1-gz，刷入后同样无限重启。

**Comment by wxt1221** [comment]
那就说明是gki的bug关掉issue因为不关ksu的事

**Comment by tiann** [comment]
ksu 启动失败后，刷回带有 magisk 的 boot 提供一下 pstore 日志。

**Comment by wxt1221** [comment]
参考一下Linux

**Comment by tiann** [comment]
/sys/fs/pstore 下的文件发出来

**Comment by fkueyu** [comment]
谢谢，这个目录我也查到了，里面是空的，所以才来请教怎么获取日志，明天要出差，下周回来试试先刷ksu启动失败后，再刷回带有 magisk 的 boot看看里面会不会有文件。

**Comment by tiann** [comment]
正常情况下这里就是空的，只有异常启动里面才会有日志

**Comment by Quelaan1** [comment]
The same thing happens for Xiaomi 12 Pro.

Rom: CRDroid
Working Kernel (Not KSU): Linux version 5.10.168-android12-9-dirty (build-user@build-host) (Android (7284624, based on r416183b) clang version 12.0.5 (https://android.googlesource.com/toolchain/llvm-project c935d99d7cf2016289302412d708641d52d2f7ee), LLD 12.0.5 (/buildbot/src/android/llvm-toolchain/out/llvm-project/lld c935d99d7cf2016289302412d708641d52d2f7ee)) #1 SMP PREEMPT Thu Jul 13 05:31:46 UTC 2023


Tried KSU - AnyKernel3-android13-5.10.168_2023-05.zip
                   AnyKernel3-android12-5.10.168_2023-05.zip
                   
                   Through TWRP and Kernel Flasher

**Comment by tiann** [comment]
We can do nothing without any logs

**Comment by Quelaan1** [comment]
The folder is empty

**Comment by hamjin** [comment]
进Recovery清除数据就可以开机了

**Comment by fkueyu** [comment]
> 正常情况下这里就是空的，只有异常启动里面才会有日志

刷入android12-5.10.168_2023-05-boot-gz启动失败后，重新刷入带有 magisk 的 boot，开机后/sys/fs/pstore目录还是空的

**Comment by tiann** [comment]
> 进Recovery清除数据就可以开机了

按照这个说法，可能是 dm-verity 的问题，建议你们关闭 dm-verity 或者清除数据再试。

**Comment by snipking** [comment]
> > 进Recovery清除数据就可以开机了
> 
> 按照这个说法，可能是 dm-verity 的问题，建议你们关闭 dm-verity 或者清除数据再试。

并不能，关闭 dm-verity 没用

**Comment by tiann** [comment]
"进Recovery清除数据就可以开机了" 这样操作呢？

**Comment by fkueyu** [comment]
> "进Recovery清除数据就可以开机了" 这样操作呢？

这个我验证了，清除数据后正常开机，ksu也正常工作

**Comment by ConneRSama** [comment]
> > "进Recovery清除数据就可以开机了" 这样操作呢？
> 
> 这个我验证了，清除数据后正常开机，ksu也正常工作

但是我刷入的时候甚至没法进入rec，进入fastboot后一分钟左右不操作会自动重启

**Comment by ConneRSama** [comment]
> > > "进Recovery清除数据就可以开机了" 这样操作呢？
> > 
> > 这个我验证了，清除数据后正常开机，ksu也正常工作
> 
> 但是我刷入的时候甚至没法进入rec，进入fastboot后一分钟左右不操作会自动重启

刷入magisk后偶尔会无法开机，报错zygote died，可能是zygisk的问题？因为我KernelSu也装了zygisk

**Comment by Atroc-X** [comment]
https://github.com/tiann/KernelSU/releases/download/v0.7.0/AnyKernel3-android12-5.10.185_2023-09.zip
It is possible to use this kernel and it will work fine.
Using the updated kernel from 2023-September will work normally.

**Comment by snipking** [comment]
> https://github.com/tiann/KernelSU/releases/download/v0.7.0/AnyKernel3-android12-5.10.185_2023-09.zip It is possible to use this kernel and it will work fine. Using the updated kernel from 2023-September will work normally.

试过了不行，一加11 coloros 14 kernel 版本 5.15.94-android13-8-o-00689-g1457669e1c45，试了下面这些都不行

[AnyKernel3-android13-5.15.94_2023-05.zip](https://github.com/tiann/KernelSU/releases/download/v0.7.0/AnyKernel3-android13-5.15.94_2023-05.zip)
[AnyKernel3-android13-5.15.104_2023-07.zip](https://github.com/tiann/KernelSU/releases/download/v0.7.0/AnyKernel3-android13-5.15.104_2023-07.zip)
[AnyKernel3-android13-5.15.119_2023-09.zip](https://github.com/tiann/KernelSU/releases/download/v0.7.0/AnyKernel3-android13-5.15.119_2023-09.zip)
[AnyKernel3-android13-5.15.123_2023-10.zip](https://github.com/tiann/KernelSU/releases/download/v0.7.0/AnyKernel3-android13-5.15.123_2023-10.zip)
[android13-5.15.94_2023-05-boot.img.gz](https://github.com/tiann/KernelSU/releases/download/v0.7.0/android13-5.15.94_2023-05-boot.img.gz)
[android13-5.15.119_2023-09-boot.img.gz](https://github.com/tiann/KernelSU/releases/download/v0.7.0/android13-5.15.119_2023-09-boot.img.gz)
[android13-5.15.123_2023-10-boot.img.gz](https://github.com/tiann/KernelSU/releases/download/v0.7.0/android13-5.15.123_2023-10-boot.img.gz)

**Comment by bugme2** [comment]
黑厂往gki里加料了，不关ksu的事，目前的解决方式是用fastboot -w格式化，官方和twrp格式化失败。

**Comment by snipking** [comment]
> 黑厂往gki里加料了，不关ksu的事，目前的解决方式是用fastboot -w格式化，官方rec和twrp格式化不了，如果刷回官方内核，估计又得再格式化一遍才能用第三方内核了。 ![Screenshot_2023-10-25-09-38-38-89_baaa51257c82a8b3f281ce09e6f2493f](https://user-images.githubusercontent.com/40169265/277897643-18fdd8db-00ff-487d-a687-2b124db45cdf.png)

诶，那岂不是以后每次升级都得格式化，WTF

**Comment by tiann** [comment]
这个跟 GKI 无关吧？三星的设备，从官方刷第三方第一次也需要清数据。

**Comment by bugme2** [comment]
> 跟这个GKI关联吧？三星的设备，从官方刷第三方第一次也需要清数据。 解锁清一次，刷开机还要再清一次。

我这边13不用格，都是直接刷，14的官方内核加了点料，不是纯粹的GKI

**Comment by bugme2** [comment]
> > 黑厂往gki里加料了，不关ksu的事，目前的解决方式是用fastboot -w格式化，官方rec和twrp格式化不了，如果刷回官方内核，估计又得再格式化一遍才能用第三方内核了。 ![Screenshot_2023-10-25-09-38-38-89_baaa51257c82a8b3f281ce09e6f2493f](https://user-images.githubusercontent.com/40169265/277897643-18fdd8db-00ff-487d-a687-2b124db45cdf.png)
> 
> 诶，那岂不是以后每次升级都得格式化，WTF

保留root升级呗

**Comment by fatinghenji** [comment]
> 黑厂往gki里加料了，不关ksu的事，目前的解决方式是用fastboot -w格式化，官方rec和twrp格式化不了，如果刷回官方内核，估计又得再格式化一遍才能用第三方内核了。 ![Screenshot_2023-10-25-09-38-38-89_baaa51257c82a8b3f281ce09e6f2493f](https://user-images.githubusercontent.com/40169265/277897643-18fdd8db-00ff-487d-a687-2b124db45cdf.png)

请问使用`fastboot -w`格式化会清空哪些文件呢？

**Comment by 0xABADBABY** [comment]
> > 黑厂往gki里加料了，不关ksu的事，目前的解决方式是用fastboot -w格式化，官方rec和twrp格式化不了，如果刷回官方内核，估计又得再格式化一遍才能用第三方内核了。 ![Screenshot_2023-10-25-09-38-38-89_baaa51257c82a8b3f281ce09e6f2493f](https://user-images.githubusercontent.com/40169265/277897643-18fdd8db-00ff-487d-a687-2b124db45cdf.png)
> 
> 请问使用`fastboot -w`格式化会清空哪些文件呢？会清空`data`吗？

别用fastboot -w, 刷官方boot,进rec清空data分区,再刷kernelsu boot

**Comment by fatinghenji** [comment]
> > > 黑厂往gki里加料了，不关ksu的事，目前的解决方式是用fastboot -w格式化，官方rec和twrp格式化不了，如果刷回官方内核，估计又得再格式化一遍才能用第三方内核了。 ![Screenshot_2023-10-25-09-38-38-89_baaa51257c82a8b3f281ce09e6f2493f](https://user-images.githubusercontent.com/40169265/277897643-18fdd8db-00ff-487d-a687-2b124db45cdf.png)
> > 
> > 
> > 请问使用`fastboot -w`格式化会清空哪些文件呢？会清空`data`吗？
> 
> 别用fastboot -w, 刷官方boot,进rec清空data分区,再刷kernelsu boot

进入官方rec后清空data分区，结束后自动重启进入系统，没法继续刷kernelsu boot

**Comment by 0xABADBABY** [comment]
@fatinghenji 重启之前按下音量下加电源，进入fastboot

**Comment by ashoktvm** [comment]
So there is no perfect solution yet?

**Comment by ashoktvm** [comment]
@tiann  Is this happening because source code not released for the kernel?

**Comment by tiann** [comment]
I don't know, i don't have such devices.

**Comment by weiwei-cool** [comment]
我与各位遇到了同样的情况，无论直接使用提供的内核刷入，还是提取卡刷包的boot用AnyKernel里的内核进行修补后刷入，都是无限重启，手机型号为一加ACE 2V，系统为coloros14。

**Comment by weiwei-cool** [comment]
在重启后会自动进入系统的rec，在系统rec中选择重启后进入循环，刷回官方boot后恢复正常。

**Comment by weiwei-cool** [comment]
> 在重启后会自动进入系统的rec，在系统rec中选择重启后进入循环，刷回官方boot后恢复正常。

目前未尝试在rec中选择清除数据是否能回复，依据此前的对话应该可以，明日尝试后回复。

**Comment by ashoktvm** [comment]
> > After restarting, it will automatically enter the REC of the system, select Restart in the system REC to enter the loop, and return to normal after flashing back to the official BOOT.
> 
> At present, I have not tried to select whether I can reply to clear the data in the REC, but it should be possible based on the previous conversation, and I will reply after trying tomorrow.

你能尝试一下吗？

**Comment by 949331213** [comment]
> 遇到同样的问题，无论直接使用提供的内核刷入，还是提取卡刷包的boot用AnyKernel里的内核进行修补后刷入，都是无限重启，手机型号为一加ACE 2V，系统为coloros14。但用magisk delta修补boot刷入后magisk delta能正常工作。

我的一加ace2遇到了一摸一样的问题

**Comment by ashoktvm** [comment]
> > "Go to Recovery to clear the data and boot up" How about this operation?
> 
> I verified this, after clearing the data, it turned on normally, and KSU also worked normally

Which kernel version you are using exactly?

**Comment by sky96111** [comment]
Tested on OnePlus 12 ColorOS 14 android14-6.1.25 . Device still got fastboot-loop after wipe data partition

**Comment by ashoktvm** [comment]
> Tested on OnePlus 12 ColorOS 14 android14-6.1.25 . Device still got fastboot-loop after wipe data partition

So kernelsu some how stopped working for Color OS 14 and OOS 14

**Comment by tiann** [comment]
try latest ci version

**Comment by snipking** [comment]
> > Tested on OnePlus 12 ColorOS 14 android14-6.1.25 . Device still got fastboot-loop after wipe data partition
> 
> So kernelsu some how stopped working for Color OS 14 and OOS 14

@ashoktvm @sky96111 wipe data partiton works on oneplus 12 ColorOS 14 PJD110_14.0.0.232(CN01) with ak3-android14-6.1.25
![WechatIMG204](https://github.com/tiann/KernelSU/assets/2351675/97682aaf-9a31-4f25-bcfb-dd97ca3e29b7)

**Comment by ashoktvm** [comment]
> try latest ci version

can we try using android image kitchen?

**Comment by ashoktvm** [comment]
> try latest ci version

Where to get that?

**Comment by ashoktvm** [comment]
> try latest ci version

If u meant by file in the group. It doesnt have android 12 kernel version

**Comment by neoshui** [comment]
> > try latest ci version
> 
> If u meant by file in the CI group. It seems to have android 13 and 14 kernel versions

try this :https://github.com/tiann/KernelSU/actions/runs/7180854283       [AnyKernel3-android14-6.1.25_2023-10](https://github.com/tiann/KernelSU/suites/18970098541/artifacts/1109010623)  and  [AnyKernel3-android14-6.1.25_2023-10](https://github.com/tiann/KernelSU/suites/18970098541/artifacts/1109010623)

**Comment by ashoktvm** [comment]
> > > try latest ci version
> > 
> > 
> > If u meant by file in the CI group. It seems to have android 13 and 14 kernel versions
> 
> try this :https://github.com/tiann/KernelSU/actions/runs/7180854283 [AnyKernel3-android14-6.1.25_2023-10](https://github.com/tiann/KernelSU/suites/18970098541/artifacts/1109010623) and [AnyKernel3-android14-6.1.25_2023-10](https://github.com/tiann/KernelSU/suites/18970098541/artifacts/1109010623)

Sorry to say but I have a different version of Kernel 5.10.168 Android12-9

**Comment by ashoktvm** [comment]
@tiann no solution for this yet?

**Comment by tufeigunchu** [comment]
怎么就closed了呢？还没解决呢

**Comment by ashoktvm** [comment]
> Why is it closed? It hasn't been solved yet

exactly my question. I don't know developer doesn't seem to care about this issue

**Comment by tiann** [comment]
仔细阅读本 issue，你会找到解决方案。https://github.com/tiann/KernelSU/issues/1051#issuecomment-1772389941

**Comment by neoshui** [comment]
> 仔细阅读本 issue，你会找到解决方案。[#1051 (comment)](https://github.com/tiann/KernelSU/issues/1051#issuecomment-1772389941)

第一次刷入清空数据这都不是啥问题，现在有个问题是夜间充电手机会进入假死状态，必须强制重启，这个问题比较麻烦

**Comment by snipking** [comment]
> > 仔细阅读本 issue，你会找到解决方案。[#1051 (comment)](https://github.com/tiann/KernelSU/issues/1051#issuecomment-1772389941)
> 
> 第一次刷入清空数据这都不是啥问题，现在有个问题是夜间充电手机会进入假死状态，必须强制重启，这个问题比较麻烦

+1，确实会假死，一加12，我还没确认是 ksu 的问题，这两天还在关各种模块尝试

**Comment by neoshui** [comment]
> > > 仔细阅读本 issue，你会找到解决方案。[#1051 (comment)](https://github.com/tiann/KernelSU/issues/1051#issuecomment-1772389941)
> > 
> > 
> > 第一次刷入清空数据这都不是啥问题，现在有个问题是夜间充电手机会进入假死状态，必须强制重启，这个问题比较麻烦
> 
> +1，确实会假死，一加12，我还没确认是 ksu 的问题，这两天还在关各种模块尝试，如果能确认是 ksu 导致的建议重开一个 issue

我换了magisk 再没出现过，主要是这个假死问题我没抓到过有效的log，没法开issue

**Comment by ashoktvm** [comment]
> Read this issue carefully and you'll find a solution. [#1051 (comment)](https://github.com/tiann/KernelSU/issues/1051#issuecomment-1772389941)

Sorry to say it may have worked on Oneplus 11. But it didn't worked on OnePlus 11R, also wiping data everything an update comes for kernelsu doesn't seem viable

**Comment by tufeigunchu** [comment]
> > 跟这个GKI关联吧？三星的设备，从官方刷第三方第一次也需要清数据。 解锁清一次，刷开机还要再清一次。
> 
> 我这边13不用格，都是直接刷，14的官方内核加了点料，不是纯粹的GKI

你是ace2v吗？ 是否支持fastboot boot直接启动？

**Comment by sky96111** [comment]
Anyone tried the new LKM? Is device still freezeing on this mode? I have returned my unit for this issue.

**Comment by snipking** [comment]
> Anyone tried the new LKM? Is device still freezeing on this mode? I can't test it because I've already returned my device due to this issue.

with wipe data, kernelsu works. and freezeing at night when charging with smart charge on.

**Comment by SK-415** [comment]
LKM works good. No wipe data needed. Charged whole last night and haven't met the freezing problem yet.

![Screenshot_2024-04-04-16-36-57-60_baaa51257c82a8b3f281ce09e6f2493f.jpg](https://github.com/tiann/KernelSU/assets/36433929/f9cab678-375b-475f-80bc-96f05d87f224)
