### ISSUE TITLE
无法使用root权限，app profile在手机重启后也消失 cannot use root privileges and app files disappear after rebooting

### ISSUE THREAD

**Issue by 0warning0error** [tiann/KernelSU#1052]
**Describe the bug**
I cannot use root privilege even if I ENABLE IT. AND after rebooting, the app profile should have been saved.(actually not)

**To Reproduce**
Steps to reproduce the behaviour:
1. you have a motorola edge s(20) pro. flash lineage os 20 and compile kernel with kernelsu. 
2. randomly set app profiles and reboot

**Expected behaviour**
the app profile should be saved

**Screenshots**
![Screenshot_20231018-164807_Trebuchet](https://github.com/tiann/KernelSU/assets/42114116/50e0faf2-3bbd-43a7-abfb-b6a83a6ebacf)

**Smartphone (please complete the following information):**
 - Device: Motorola edge s pro (edge 20 pro)
 - OS: lineage os 20 (compile kernel with kernelsu by myself)
 - Version 11272

**Additional context**
system log . seems that app profiles failed to be saved
https://wwzl.lanzoue.com/ivMmJ1c4v2ef

**Comment by tiann** [comment]
Please disable all module and try again, logs show it works well.
