### ISSUE TITLE
KernelSu Manager showing "No Modules Installed"

### ISSUE THREAD

**Issue by selfmusing** [tiann/KernelSU#1056]
Bug Description: I've flashed these modules on my device via kernel su manager v0.6.9 release build :

![Screenshot_20231019-172451](https://github.com/tiann/KernelSU/assets/109387456/96bde5d2-6d97-4292-8d3c-d7717d9e4a5f)
 
KSU version: 11279
Kernel: 4.14.255-Xcalibur-v3.0-KernelSu

But it's showing this error after reboot , the issue persists even if I only use a single module .

Screenshot : 
![Screenshot_20231019-172440](https://github.com/tiann/KernelSU/assets/109387456/7d1381cf-dc20-4200-a9a9-cea7570e15d4)
![Screenshot_20231019-172434](https://github.com/tiann/KernelSU/assets/109387456/b0ebcfec-aec5-4e8a-830c-c8b3430af698)

**To Reproduce**
Steps to reproduce the behaviour:
1. Flash any module 
2.  Then reboot the device 
3. get this error "no modules installed"

**Expected behaviour**
Earlier, It was working fine for me , but I don't understand what's wrong v0.6.9

KSU Logs : 
[KernelSU_bugreport_2023-10-19_17_25.tar.gz](https://github.com/tiann/KernelSU/files/13042262/KernelSU_bugreport_2023-10-19_17_25.tar.gz)

**Smartphone info :**
 - Device:  Redmi Note 7 Pro
 - OS: DerpFest
 - Version : Android 14 (UP1A.231005.007) 

( ALL THE MODULES WORK WELL , THE ONLY ISSUE IS WITH THE MANAGER )

**Comment by tiann** [comment]
Please uninstall module one by one to check which module is problematic

**Comment by selfmusing** [comment]
OKAY , I'll try .

**Comment by selfmusing** [comment]
> Please uninstall module one by one to check which module is problematic


1. I've tried to delete all my modules 1 by 1 one to check which one is causing this issue , but it didn't help.
2. So I deleted these files & folders:
- /data/adb/ksu/log/
- module.img and update file

**Comment by tiann** [comment]
maybe it is because `magisk.db`, some modules relies on it.
