### ISSUE TITLE
0.6.9版本王者荣耀自己授权了root

### ISSUE THREAD

**Issue by zy777777** [tiann/KernelSU#1063]
手机是小米pro安卓13，kernelsu版本是0.6.9，昨天下载了王者荣耀，用隐藏应用列表屏蔽了所有lsp插件和授权root的软件，还开了透视打了一把游戏，今早去kernelsu看自动给了王者荣耀root权限

**Comment by tiann** [comment]
用 CI 版本的 kernel 再试；https://github.com/tiann/KernelSU/commit/b1830049f12a5b8c35d5fc3a27cd4afc3d24663c
