### ISSUE TITLE
modules unmounted 

### ISSUE THREAD

**Issue by msalah-kw** [tiann/KernelSU#1067]
I always find the KSU app without any modules. However, I installed some, when I restart my phone, I find the modules back to work properly 

Samsung S22 ultra
SM-S908E
Android 13
OneUi 5.1
Kernel
5.10.136-android12-9-gb3068d3f7169
Manager Version
v0.6.9 (11272)

[KernelSU_bugreport_2023-10-22_14_32.tar.gz](https://github.com/tiann/KernelSU/files/13063120/KernelSU_bugreport_2023-10-22_14_32.tar.gz)

**Comment by tiann** [comment]
use the latest ci please.

**Comment by tiann** [comment]
#1045

**Comment by sha3rawi33** [comment]
@msalah-kw 
Hi, can you help me choose a kernel SU boot.img from the list? I tried and boot-looped twice xD

I have S22U (SM-S908E) with oneui 6 and android 14, security patch is dec 2023. is this the reason?

if not, which kernel boot image are you using now? and how are you flashing it to your phone?

**Comment by msalah-kw** [comment]
> @msalah-kw 
> Hi, can you help me choose a kernel SU boot.img from the list? I tried and boot-looped twice xD
> 
> I have S22U (SM-S908E) with oneui 6 and android 14, security patch is dec 2023. is this the reason?
> 
> if not, which kernel boot image are you using now? and how are you flashing it to your phone?

Settings>About phone>Software information
Then check your **Kernel Version**
