### ISSUE TITLE
android14 無法使用AK3刷入

### ISSUE THREAD

**Issue by jeffpeng3** [tiann/KernelSU#1068]
**Describe the bug**
因為只能使用64-bit
所以無法使用包含32bit ELF的AK3 zip刷入

**To Reproduce**
下載[AnyKernel3-android14-5.15.110_2023-09](https://github.com/tiann/KernelSU/suites/17499154240/artifacts/999852444)
使用[Kernel Flasher](https://github.com/capntrips/KernelFlasher/releases)試圖刷入
刷入錯誤

**Expected behaviour**
正常刷入

**Smartphone (please complete the following information):**
 - Device: Pixel 8 Pro
 - OS: Android 14
 - Version UD1A.230803.041

[ak3-log--2023-10-22--20-51.log](https://github.com/tiann/KernelSU/files/13063299/ak3-log--2023-10-22--20-51.log)

**Comment by tiann** [comment]
I think you should report it to upstream: https://github.com/osm0sis/AnyKernel3

**Comment by osm0sis** [comment]
I'll make a PR for you to fix it.

KernelSU's AK3 fork will need to be updated with the arm64 binaries. I think every device officially supported with an AK3 zip here is arm64 so that should be fine.

**Comment by tiann** [comment]
Thank you, i will do it tomorrow.

**Comment by osm0sis** [comment]
Perfect! I'd suggest merging to latest upstream, then committing the arm64 tools over top. 🤘😁

**Comment by amteza** [comment]
> Perfect! I'd suggest merging to latest upstream, then committing the arm64 tools over top. 🤘😁

@osm0sis, tested, it works flawlessly. However, @tiann, your compiled android14-5.15.110 kernel does not boot in Pixel 8 Pro, it causes boot loop. Both flashing with `fastboot flash boot` and using the updated AK3 zip with the `arm64` tools.

**Comment by tiann** [comment]
I added the arm64 just now: https://github.com/Kernel-SU/AnyKernel3/commit/1abdfc565596fef880ae16ee60224194f94ce302

> compiled android14-5.15.110 kernel does not boot in Pixel 8 Pro, it causes boot loop.

Do you try the magiskboot way? Maybe it is a vbmeta issue.

**Comment by amteza** [comment]
> > compiled android14-5.15.110 kernel does not boot in Pixel 8 Pro, it causes boot loop.
> Do you try the magiskboot way? Maybe it is a vbmeta issue.

Nope, but I have time right now to try. Give me a second and I will let you know.
