### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by 4everrrrr** [tiann/KernelSU#1073]
After installing kernel su (v0.6.9 and earlier) modules when i try to open app named Nafath (KSA country specific) it crashes instantly. i tried many modules one by one and also try kernel su without modules but nafath app crash other working fine (without module first time it work but when i reboot phone it start crashing again)

 - Device: alioth (Mi 11x)
 - OS: android 
 - Version 13 (Miui 14.0.8 china stable)
Crashing in every miui based rom didn't try with aosp
![Screenshot_2023-10-22-22-26-47-077_com arumcomm crashlogviewer-edit](https://github.com/tiann/KernelSU/assets/148725289/06f0dc43-8517-472f-b630-b771a61af62d)
[log_aliothin_V14.0.8.0.TKHCNXM.txt](https://github.com/tiann/KernelSU/files/13064723/log_aliothin_V14.0.8.0.TKHCNXM.txt)
/

**Comment by tiann** [comment]
1. KernelSU Manager - Settings - Send Log
2. The download link of the App.

**Comment by 4everrrrr** [comment]
> 1. KernelSU Manager - Settings - Send Log
> 2. The download link of the App.

[KernelSU_bugreport_2023-10-23_23_46.tar.gz](https://github.com/tiann/KernelSU/files/13079088/KernelSU_bugreport_2023-10-23_23_46.tar.gz)

https://play.google.com/store/apps/details?id=sa.gov.moi&pli=1

**Comment by tiann** [comment]
#1062 

The app works well on my device.

**Comment by 4everrrrr** [comment]
> #1062
> 
> The app works well on my device.

Working in aosp rom but not in miui
