### ISSUE TITLE
KernelSU Support for Pixel 8 Pro Devices

### ISSUE THREAD

**Issue by dongltron** [tiann/KernelSU#1077]
Specifically Kernel Version 5.15.110-android 14 -11-ga6d7915820a0-ab10726252. Would love to see this kernel supported, and just curious on how long that would be expected to take? Thanks!

**Comment by tiann** [comment]
Try this one https://github.com/tiann/KernelSU/actions/runs/6614627841

**Comment by tiann** [comment]
Please try newly release.
