### ISSUE TITLE
[Feature] Log Section in  Manager App

### ISSUE THREAD

**Issue by rushiranpise** [tiann/KernelSU#1080]
### Is your feature request related to a problem? Please describe.

Currently,there is only option to share/export logs as a bug report in the manager app.

### Describe the solution you'd like.

Possible to add log section ,similar to what magisk app has?

![image](https://github.com/tiann/KernelSU/assets/37355997/5ed0e9c8-7530-4105-9417-d050817b1a3b)

### Describe alternatives you've considered.

-

**Comment by tiann** [comment]
It's certainly possible, but I personally wouldn't add it. Because no matter how much effort you spend, you can't do it better than a professional file manager or log viewer.
