### ISSUE TITLE
Support for oxygen os 14 one plus 

### ISSUE THREAD

**Issue by Ibbu37** [tiann/KernelSU#1081]
I was using kernel su same device one plus 10 pro on android 13 i.e oxygen os 13.1 now upgraded to open beta oxygen os 14 i.e android 14 kernel version changed previous it was a12 5.10.136
Now after updating the kernel version it changed to a12 5.10.168 and when i patch anykernel to it like previous version the device does not boot up but in magisk patch boot it boots so i need kernel su any how to work on it

**Comment by tiann** [comment]
https://github.com/tiann/KernelSU/issues/1051#issuecomment-1772389941
