### ISSUE TITLE
Default root profile Template 

### ISSUE THREAD

**Issue by shadowelite-sec** [tiann/KernelSU#1087]
Can I get the default profile Template for root, so it will be easy to modify/add the new Template

**Comment by tiann** [comment]
When you "create template" in Settings page, the default template is created, you only need to give it an new id.

**Comment by shadowelite-sec** [comment]
> When you "create template" in Settings page, the default template is created, you only need to give it an new id.

No . I mean the default root permission
This one 

#
![Screenshot_20231026-000958_KernelSU~2](https://github.com/tiann/KernelSU/assets/54718375/2f250730-52da-4a84-9d71-1de699adfb47)


Or it will be nice having a feature in `ksud`
Something like `ksud profile get-template Default`
To get the default template

**Comment by shadowelite-sec** [comment]
> > When you "create template" in Settings page, the default template is created, you only need to give it an new id.
> 
> No . I mean the default root permission This one
> 
> ![Screenshot_20231026-000958_KernelSU~2](https://user-images.githubusercontent.com/54718375/278115121-2f250730-52da-4a84-9d71-1de699adfb47.png)
> 
> Or it will be nice having a feature in `ksud` Something like `ksud profile get-template Default` To get the default template

@tiann
