### ISSUE TITLE
Root detectable

### ISSUE THREAD

**Issue by damianTC** [tiann/KernelSU#1089]
La aplicación http inyector detecta el uso de root.
![IMG_20231024_164242_471](https://github.com/tiann/KernelSU/assets/38479551/91c0ea9e-ed04-4ef5-b4b0-cf79d9e03adf)

Esto podría hacer que otras aplicaciones opten por la misma solución (apps bancarias por ejemplo)
![IMG_20231024_164246_724](https://github.com/tiann/KernelSU/assets/38479551/4ada675a-685e-4c34-8f69-8e44fbb40d69)

Nota: no se ha instalado ningún administrador root ni concedido permisos.
El kernel proviene de una room personalizada, podría ser ese problema?

**Comment by damianTC** [comment]
![IMG_20231024_165245_398](https://github.com/tiann/KernelSU/assets/38479551/3e70a75d-98ba-4995-a613-3d7187da4b0a)

**Comment by tiann** [comment]
1. use English please.
2. send log
3. check issue first, maybe #1061
