### ISSUE TITLE
Detected Trojan:Script/Wacatac.B!ml in KernelSU_v0.7.0_11326-release.apk

### ISSUE THREAD

**Issue by RobertsGhostBusterFan** [tiann/KernelSU#1092]
**Describe the bug**
Detected Trojan:Script/Wacatac.B!ml

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Windows Subsystem for Android', Apps KernelSU in app settings for updates" 
2. Click on 'Download and try to install KernelSU_v0.7.0_11326-release.apk from System and Files'
Windows Security blocks and deletes the file as it says it Detected  Trojan:Script/Wacatac.B!ml in newest version released.

**Expected behaviour**
like build KernelSU_v0.6.9_11272-release which was not detected as having a Trojan that what I would Expected to be the normal behaviour, but these things happen.

**Screenshots**
<img width="890" alt="image" src="https://github.com/tiann/KernelSU/assets/95888975/bfb04a82-c25a-4f16-9c18-ab297205735e">
<img width="895" alt="image" src="https://github.com/tiann/KernelSU/assets/95888975/3b4bd095-c0db-4413-bf24-712a1f86c5ea">

**Smartphone (please complete the following information):**
 - Device: WSA_2308.40000.3.0_x64
 - OS: [Windows 11]
 - Version [version 22H2]

**Comment by tiann** [comment]
KernelSU is opensource, the manager is build from Github Action directly.

Please tell me which part of the code is "Detected Trojan:Script/Wacatac.B!ml".

**Comment by tiann** [comment]
I can do nothing for that.
