### ISSUE TITLE
在Redmi Note 12 Turbo上使用Shamiko隐藏root会使chrome显示网页失效

### ISSUE THREAD

**Issue by twoone-3** [tiann/KernelSU#1095]
**Describe the bug**
当我使用shamiko zygisk on kernelsu时，chrome将会无法显示网页
**To Reproduce**
Steps to reproduce the behaviour:
1. 安装zygisk on ksu，shamiko
2. 打开chrome，访问任意网页
3. 白屏（黑屏）
4. 转到ksu 给chrome root权限（主要是给shamiko白名单，chrome不会调用root）
5. 回到chrome，访问正常

**Smartphone (please complete the following information):**
 - Device: Redmi Note 12 Turbo
 - OS: Derpfest（在MIUI以及其它类原生都可以复现）
 - Version 25/10/23
[KernelSU_bugreport_2023-10-26_08_29.tar.gz](https://github.com/tiann/KernelSU/files/13171763/KernelSU_bugreport_2023-10-26_08_29.tar.gz)

**Additional context**

https://github.com/tiann/KernelSU/assets/62778573/f6393dd1-d9a9-4ccf-8fc5-661aa50c09c2

[KernelSU_bugreport_2023-10-26_08_29.tar.gz](https://github.com/tiann/KernelSU/files/13171778/KernelSU_bugreport_2023-10-26_08_29.tar.gz)

**Comment by tiann** [comment]
Disable "Umount modules by default" in Settings.
