### ISSUE TITLE
Some Banking App Detecting KernelSU as Malware

### ISSUE THREAD

**Issue by RazaDroid** [tiann/KernelSU#1098]
I tried using a banking app "indie by indusind bank" it's detected KernelSU as Malware
![Screenshot_20231027-140341_INDIE](https://github.com/tiann/KernelSU/assets/37952910/23ac1e36-bba4-4d43-9c69-6d3bba51549f)

**Smartphone (please complete the following information):**
 - Device: Moto G9
 - OS: Android
 - Version: 14

**Comment by tiann** [comment]
Search issue first please and stop sending useless reports.
