### ISSUE TITLE
[ASK] fbind folder in /sdcard

### ISSUE THREAD

**Issue by JeelsBoobz** [tiann/KernelSU#1099]
How to fbind folder source `/sdcard/a` to destination `/sdcard/b`
Like foldermount/fbind module
Use `mount --bind /data/media/0/a /data/media/0/b`, but break my KernelSU
Thanks

**Comment by DerGoogler** [comment]
This might not work.

**Comment by tiann** [comment]
Nothing to do with KernelSU, if you need help, go to discussion, don't abuse issues.
