### ISSUE TITLE
build error: undefined reference to "xxx"

### ISSUE THREAD

**Issue by xyz-sundram** [tiann/KernelSU#1100]
### Describe your problem.

Hey there i am having this build error, I have tried picking ksu again but it is giving the same error..
my device: galaxy m30s
kernel version : 4.14.120
ksu manual method
my kernel repo: https://github.com/xyz-sundram/kernel_m30s (pls ignore commit history -_-)

aarch64-linux-gnu-ld: fs/open.o: in function SYSC_faccessat':
/home/runner/work/kernel_m30s/kernel_m30s/out/../fs/open.c:375: undefined reference to ksu_handle_faccessat'
/home/runner/work/kernel_m30s/kernel_m30s/out/../fs/open.c:375:(.text+0x604): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol ksu_handle_faccessat'
aarch64-linux-gnu-ld: fs/read_write.o: in function vfs_read':
/home/runner/work/kernel_m30s/kernel_m30s/out/../fs/read_write.c:444: undefined reference to ksu_vfs_read_hook'
/home/runner/work/kernel_m30s/kernel_m30s/out/../fs/read_write.c:444:(.text+0x788): relocation truncated to fit: R_AARCH64_ADR_PREL_PG_HI21 against undefined symbol ksu_vfs_read_hook'
aarch64-linux-gnu-ld: /home/runner/work/kernel_m30s/kernel_m30s/out/../fs/read_write.c:444: undefined reference to ksu_vfs_read_hook'
aarch64-linux-gnu-ld: /home/runner/work/kernel_m30s/kernel_m30s/out/../fs/read_write.c:445: undefined reference to ksu_handle_vfs_read'
/home/runner/work/kernel_m30s/kernel_m30s/out/../fs/read_write.c:445:(.text+0x8d4): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol ksu_handle_vfs_read'
aarch64-linux-gnu-ld: fs/stat.o: in function vfs_statx':
/home/runner/work/kernel_m30s/kernel_m30s/out/../fs/stat.c:175: undefined reference to ksu_handle_stat'
/home/runner/work/kernel_m30s/kernel_m30s/out/../fs/stat.c:175:(.text+0x260): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol ksu_handle_stat'
aarch64-linux-gnu-ld: fs/exec.o: in function do_execveat_common':
/home/runner/work/kernel_m30s/kernel_m30s/out/../fs/exec.c:1949: undefined reference to ksu_execveat_hook'
/home/runner/work/kernel_m30s/kernel_m30s/out/../fs/exec.c:1949:(.text+0x1da8): relocation truncated to fit: R_AARCH64_ADR_PREL_PG_HI21 against undefined symbol ksu_execveat_hook'
aarch64-linux-gnu-ld: /home/runner/work/kernel_m30s/kernel_m30s/out/../fs/exec.c:1949: undefined reference to ksu_execveat_hook'
aarch64-linux-gnu-ld: /home/runner/work/kernel_m30s/kernel_m30s/out/../fs/exec.c:1952: undefined reference to ksu_handle_execveat_sucompat'
/home/runner/work/kernel_m30s/kernel_m30s/out/../fs/exec.c:1952:(.text+0x1dd8): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol ksu_handle_execveat_sucompat'
aarch64-linux-gnu-ld: /home/runner/work/kernel_m30s/kernel_m30s/out/../fs/exec.c:1950: undefined reference to ksu_handle_execveat'
/home/runner/work/kernel_m30s/kernel_m30s/out/../fs/exec.c:1950:(.text+0x237c): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol ksu_handle_execveat'
aarch64-linux-gnu-ld: drivers/input/input.o: in function input_handle_event':
/home/runner/work/kernel_m30s/kernel_m30s/out/../drivers/input/input.c:381: undefined reference to ksu_input_hook'
/home/runner/work/kernel_m30s/kernel_m30s/out/../drivers/input/input.c:381:(.text+0xccd4): relocation truncated to fit: R_AARCH64_ADR_PREL_PG_HI21 against undefined symbol ksu_input_hook'
aarch64-linux-gnu-ld: /home/runner/work/kernel_m30s/kernel_m30s/out/../drivers/input/input.c:381: undefined reference to ksu_input_hook'
aarch64-linux-gnu-ld: /home/runner/work/kernel_m30s/kernel_m30s/out/../drivers/input/input.c:382: undefined reference to ksu_handle_input_handle_event'
/home/runner/work/kernel_m30s/kernel_m30s/out/../drivers/input/input.c:382:(.text+0xcf28): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol ksu_handle_input_handle_event'
make[1]: *** [/home/runner/work/kernel_m30s/kernel_m30s/Makefile:1120: vmlinux] Error 1
make: *** [Makefile:146: sub-make] Error 2
make[1]: Leaving directory '/home/runner/work/kernel_m30s/kernel_m30s/out'

Compilation failed!
Error: Process completed with exit code 1.

**Comment by tiann** [comment]
#943
