### ISSUE TITLE
Files in `/apex` not overlay by module.

### ISSUE THREAD

**Issue by hereblur** [tiann/KernelSU#1101]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

I trying to create module to replacing `libart.so`.
but files in `/apex` not overlay by module.
After reboot, files in `/apex` not changes (check by `md5sum`). 
while other directory like /system is working fine..

Is it possible to overlay on Apex image mount? or Am I do something wrong?

### To Reproduce

1. Create module following this structure.
```
curtana:/data/adb/modules/hoox.k.extract.dex # find . -print | sort | sed 's;[^/]*/;|---;g;s;---|; |;g'                                                                         
.
|---apex
| |---com.android.art
| | |---lib
| | | |---libart.so
| | |---lib64
| | | |---libart.so
| |---com.android.art@330400000
| | |---lib
| | | |---libart.so
| | |---lib64
| | | |---libart.so
|---module.prop
|---system
|---system.prop
```
2. Compare file's md5 to see if it's replaced.

### Expected behavior

Files in /apex are overlaid.

### Logs

[KernelSU_bugreport_2023-10-30_08_46.tar.gz](https://github.com/tiann/KernelSU/files/13200011/KernelSU_bugreport_2023-10-30_08_46.tar.gz)

### Device info

- Device: Redmi Note9S
- OS Version: LineageOS 20.0
- KernelSU Version: 0.7.0
- Kernel Version: 4.14.230

**Comment by tiann** [comment]
KernelSU doesn't handle the `apex` mount, so it is not working as expected. Maybe you need to mount it yourself. We have no plan to support it yet.
