### ISSUE TITLE
Bootloop Android 14

### ISSUE THREAD

**Issue by Denzshow** [tiann/KernelSU#1104]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

After flashing via adb fastboot instantly got bootlooped. Restored boot.img so I can boot

### Logs

[KernelSU_bugreport_2023-11-01_20_34.tar.gz](https://github.com/tiann/KernelSU/files/13226936/KernelSU_bugreport_2023-11-01_20_34.tar.gz)

### Device info

- Device: Realme GT Neo5 SE
- OS Version: Realme UI 5 Android 14
- KernelSU Version:  0.7.0
- Kernel Version: 5.10.168-android12-9-o-g63cc297a7b34

**Comment by tiann** [comment]
#1051
