### ISSUE TITLE
[BUG] Button install in KernelSU Manager

### ISSUE THREAD

**Issue by JeelsBoobz** [tiann/KernelSU#1110]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [x] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

The install module button is often missing

### Screenshots

![Screenshot_2023-11-04-18-54-44-520_me weishu kernelsu](https://github.com/tiann/KernelSU/assets/38210868/690f2925-a495-4715-89fc-09fe42c4eba2)

### Device info

- Device: Poco X3 NFC
- OS Version: 12
- KernelSU Version: 11338
- Kernel Version: 4.14.328

**Comment by tiann** [comment]
Why you check the checkbox without checking it?
