### ISSUE TITLE
Modules disappear in manager.

### ISSUE THREAD

**Issue by wxt1221** [tiann/KernelSU#1111]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

1.open the manager
2.no modules
3.find module files in MT 

The manager was complied by myself but with no modification.

main branch

### Screenshots

![image](https://github.com/tiann/KernelSU/assets/74451279/b37451b7-e6d0-406e-a4df-35fce5f7ef4d)
![image](https://github.com/tiann/KernelSU/assets/74451279/4f269db4-97bc-431a-b8ae-97c9a1f71eaf)
![image](https://github.com/tiann/KernelSU/assets/74451279/c80b7701-ee28-4420-9f06-a3d3a4343122)

### Logs

[KernelSU_bugreport_2023-11-04_22_26.tar.gz](https://github.com/tiann/KernelSU/files/13256883/KernelSU_bugreport_2023-11-04_22_26.tar.gz)

### Device info

- Device:Oneplus 6T
- OS Version:Crdroid 9.9 android 13
- KernelSU Version:11348
- Kernel Version:4.9.337

It was worked before I updated to the newest.

**Comment by tiann** [comment]
We won't accept issues with an unofficial manager.
If you need to compile yourself, you should check the official github action to ensure every step is right.
