### ISSUE TITLE
[FR] Add Multi-User Mode Support

### ISSUE THREAD

**Issue by GhettiGuru** [tiann/KernelSU#1112]
### Is your feature request related to a problem? Please describe.

Adding multi user mode support for workspace and managed profiles for applications such as island, insular, and shelter.

### Describe the solution you'd like.

Hello, sorry for the trouble, I very rarely jump into GitHub if can be at all avoided, I solve it myself. However this one will have to be added to the application itself. The multi user mode support that allows for hiding root over on work profile, (such as Island, shelter or insular), is quite literally one of the best option we have for hiding root, as if you toggle that multi user mode off on magisk, none of the other users get root access to even call for it, people with non-broken Tee partitions have actually been able to pull off passing strong integrity over there using something like bootloader spoofer exposed, they are able to use otherwise zygisk problematic applications like 8 ball pool and opening their apps for banking and other picky ones while still maintaining a root environment.. if this is as easily implemented as I'm thinking, as it's overlays and mounting should be the same, can we please think about adding this feature. Thank you very much for your time.

### Describe alternatives you've considered.

If for whatever reason this is not possible, to allow or disallow root and control it by profile, is there a way to just stop mounting and providing root access all together for the work profile?

**Comment by GhettiGuru** [comment]
As this is one of the only ways with a rooted device to achieve access to certain picky applications, is there not a way to implement a profile wide blocking and denial of root access? It seems and has proven to be away around two of the most picky applications I am aware of.

**Comment by GhettiGuru** [comment]
To be as precise as possible, what I'm getting at here, is that for whatever reason it may be, one of the only resorts for root users for using certain applications right now is to go to turn off multi user mode and use magisk. Good we may be consider adding a user Global denial of root access for the ease of the users, and possible way around getting detection as it's proven to be a method already on ksu's alternative? To block route all together for any user besides the main, as someone might have children that have their own profile and they don't want them to accidentally trigger stuff or whatever the case.

**Comment by GhettiGuru** [comment]
To be as precise as possible, for whatever the reason may be right now the best way and the only way to access certain applications while being on a rooted device is to resort to going back to magisk, disabling multi-user mode and going to the work profile. This is proven to work on some of the most problematic applications we have, and adding this functionality would only make it easier on users that would otherwise have to be white listing and black listing applications constantly for their workspace. Also, I see a benefit and users that have children and wouldn't want their children to get in and access root and mess up the device or cause all kinds of havoc. I can only see about three benefits and no real downside to adding a user variable toggle to turn root access off to anybody but the main user, is this a functionality that can be ported to ksu?

**Comment by GhettiGuru** [comment]
> root doesn't exist by default on workspace, it doesn't exist by default anywhere.

To be as precise as possible, for whatever reason it may be, one of the only resorts we have right now is a rooted user to get into certain applications is to go into magisk and disable multi-user mode, this has proven to be a reliable and working method for getting into some of our applications. Also, adding this feature would serve to make it easier on the users, that would otherwise have to be white listing in Black listing every application they add to their workspace. Also I see a third benefit, users that have children or multiple users on a device like a tablet, you don't need their children having root access and messing things up. This has proven to be a reliable and almost necessary feature on ksu's alternative, and I'm asking if we could Port this functionality to deny root access to everybody but the main user, the administrator, to ksu?

**Comment by tiann** [comment]
Please describe your issue clearly. 
KernelSU supports to grant root to work profile app out of box.

**Comment by GhettiGuru** [comment]
Yes but as far as I'm aware, there's no option to unmount it and not allow it over there that's what we need

**Comment by GhettiGuru** [comment]
> root doesn't exist by default on workspace, it doesn't exist by default anywhere.

To be as precise as possible, for whatever reason it may be, one of the only resorts we have right now is a rooted user to get into certain applications is to go into magisk and disable multi-user mode, this has proven to be a reliable and working method for getting into some of our applications. Also, adding this feature would serve to make it easier on the users, that would otherwise have to be white listing in Black listing every application they add to their workspace. Also I see a third benefit, users that have children or multiple users on a device like a tablet, you don't need their children having root access and messing things up. This has proven to be a reliable and almost necessary feature on ksu's alternative, and I'm asking if we could Port this functionality to deny root access to everybody but the main user, the administrator, to ksu?

*Having VPN drama apparently*

**Comment by tiann** [comment]
KernelSU is not Magisk, it uses white list by default, so if you don't grant root an app, it has no root, you don't need to disallow it.

**Comment by GhettiGuru** [comment]
I didn't intend to argue logistics just requesting feature if you don't see any need for it, I'm, out, I just hope you consider it for users that have children and other benefits besides the one that is obviously in the way, super user access being detected, for whatever the reason.

**Comment by GhettiGuru** [comment]
But instead of having to individually unmount every application that one adds to their workspace and work profile, is there not a way to look at how magisk does this by profile to make it easier on the end users? And that way they won't have to go in every time they add an application to their work profile and white list things?

**Comment by tiann** [comment]
root doesn't exist by default on workspace, it doesn't exist by default anywhere.

**Comment by tiann** [comment]
Some people use chopsticks to eat, and some people use forks to eat. Why do you want to make the chopsticks into forks?

**Comment by GhettiGuru** [comment]
So your kids don't destroy your device, and you can use applications that you otherwise can't right now with a simple feature ad that can be implemented most likely just as easy as it uses overlays and mirrors to do what it does systemlessly the same way as your counterpart that can achieve these applications this way, which also benefits and users in various ways as described

**Comment by jiesou** [comment]
Hidden root aside, KernelSU still doesn't support managing ROOT permissions for applications in another user.
It does support grant root to work profile apps, but not apps in another user.

**Comment by jiesou** [comment]
I tried installing the KernelSU manager to another user, but it doesn't recognize the KernelSU installation.

**Comment by Snuupy** [comment]
can this be reopened? I'm trying to get root permissions on other users to theme the OS but I can't because other users can't access root permissions
