### ISSUE TITLE
[d2s] [Unofficial device] [Question] Building KernelSU into LOS kernel results in non-functional su

### ISSUE THREAD

**Issue by Unb0rn** [tiann/KernelSU#1113]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

I'm trying to build KernelSU into official exynos9820 LineageOS kernel. This kernel has Kprobes enabled by default. I also found a [repo](https://github.com/awakened1712/android_kernel_samsung_exynos9820) in unofficially supported devices, the problem is - it is outdated a bit, there are no prebuilt images and I'm unable to build it myself, and here's why:
Defconfigs in the repo above still have Kprobes enabled and at the same time it has the [commit](https://github.com/awakened1712/android_kernel_samsung_exynos9820/commit/125596f8cb00038677e315ba8a2dbb7789d2127c) that adds the manual fs patches, but omitting any conditionals at all. If I try to add the reference patch I get those errors like `undefined symbol: ksu_vfs_read_hook` which, again, I think may be related to Kprobes left enabled.

I decided to try and build the kernel myself using the Kprobes method, the kernel was built successfully but after installing the manager app from 0.7.0 release all I see in SuperUser tab is a spinning wheel. After trying to debug it, I got several logs from logcat - both KsuCLI and avc related:
[ksu-avc.log](https://github.com/tiann/KernelSU/files/13260903/ksu-avc.log)
[ksu-cli.log](https://github.com/tiann/KernelSU/files/13260904/ksu-cli.log)

I tried disabling SELiux with Magisk for testing and it seemingly resolved the issues at first - manager app detected all the apps and allowed to change the su permissions, although those changes had no effect but after reboot (and re-enabling SELinux) it turned out no settings would stick.

Attaching the debug archive:
[KernelSU_bugreport_2023-11-06_01_11.tar.gz](https://github.com/tiann/KernelSU/files/13260921/KernelSU_bugreport_2023-11-06_01_11.tar.gz)

Tried searching the issues, but I can't understand - is it SELinux that interferes with KSU, or problems with Kprobes render KSU inoperable. Any help is appreciated...

### Expected behavior

KernelSU loads and makes it possible to assign su permissions through the manager app.

### Device info

- Device: Samsung Galaxy Note 10+, SM-N975F (d2s)
- OS Version: Android 13 (TQ3A.230901.001)
- KernelSU Version: 0.7.0 (11326)
- Kernel Version: 4.14.316

**Comment by tiann** [comment]
You should use the manual way to integrate, the compile error is because the source change and you need to make some changes to the patch. You can follow the instructions and re-integrate it again, it should work well.

**Comment by Unb0rn** [comment]
@tiann Thank you for a quick response and sorry for bothering again) I did as you told me and it's mostly working now - su, modules, only profiles don't stick, but I think I'll try to figure it out in the discussions section myself.

The only question I have left - I discovered several kernels in [Unofficial device support](https://kernelsu.org/guide/unofficially-support-devices.html): [Samsung a50](https://github.com/GiovanYCringe-Experiments/kernel_a50/commit/52b17d53a0b1e32831776aa02117b6937dec7dac), [Exynos9820](https://github.com/awakened1712/android_kernel_samsung_exynos9820/commit/125596f8cb00038677e315ba8a2dbb7789d2127c), [Samsung Tab S7](https://github.com/tiandoufayale/android_kernel_samsung_sm8250/commit/fd3c6fe00c010cc2791736878c3b0a8ad4f0b0a3) - just a few to mention - all of which use the same approach - they use the reference manual patch for adding the hooks, however, all of them omit all the conditionals for `ksu_handle_execveat`, `ksu_handle_vfs_read` and `ksu_handle_input_handle_event`. So for example the call 
```
if (unlikely(ksu_vfs_read_hook))
	ksu_handle_vfs_read(&file, &buf, &count, &pos);
```
becomes just
`ksu_handle_vfs_read(&file, &buf, &count, &pos);`

I'm not sure if I understand what this flag does: `ksu_vfs_read_hook` so I have to ask - Speaking security- and performance-wise is it okay to use such an approach?
Also added the same hooks to my [repo](https://github.com/Unb0rn/android_kernel_samsung_exynos9820/tree/lineage-20-ksu)
Thanks again!
