### ISSUE TITLE
Failed to boot with manually patched image

### ISSUE THREAD

**Issue by cccClyde** [tiann/KernelSU#1117]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

After flashing the manually patched boot.img, the phone boots directly into Bootloader and displays as "boot failure".

### To Reproduce

1. I'm using Pixel 8 Pro, downloaded `AnyKernel3-android14-5.15.110_2023-09.zip` from the latest release
2. I patched the boot.img of Pixel November upate with Android Image Kitchen
3. Flashed the output image 
4. The phone boots directly into Bootloader and displays as "boot failure"

### Expected behavior

Successfully boot like Oct update.

### Device info

- Device: Pixel 8 Pro
- OS Version: 14.0.0 (UD1A.231105.004, Nov 2023)
- KernelSU Version: KernelSU_v0.7.0_11326
- Kernel Version: 5.15.110-Android14

**Comment by symbuzzer** [comment]
Is there a roadmap on how you can patch the kernel by reverse engineering?

**Comment by cccClyde** [comment]
> Is there a roadmap on how you can patch the kernel by reverse engineering?

I followed the dev's guide here: https://kernelsu.org/guide/installation.html#patch-boot-img-manually

**Comment by tiann** [comment]
Maybe you should try newer version, such as `2023-10`

**Comment by amteza** [comment]
> > Is there a roadmap on how you can patch the kernel by reverse engineering?

> I followed the dev's guide here: https://kernelsu.org/guide/installation.html#patch-boot-img-manually

magiskboot method works fine in November's update, same device, Pixel 8 Pro.

**Comment by cccClyde** [comment]
> > > Is there a roadmap on how you can patch the kernel by reverse engineering?
> 
> > I followed the dev's guide here: https://kernelsu.org/guide/installation.html#patch-boot-img-manually
> 
> magiskboot method works fine in November's update, same device, Pixel 8 Pro.

Yes I can confirm that it works for me too.
