### ISSUE TITLE
需要 5.10.188 的 内核 给 Android 13 的 ARCVM 使用

### ISSUE THREAD

**Issue by 1457384613gh** [tiann/KernelSU#1118]
需要 5.10.188 的 内核 给 Android 13 的 ARCVM 使用。

chromeOS 更新到 r118，
ARCVM 会升级到 Android 13，其内核也升级了小版本。

KernelSU 的 Releases 里面，只有 ARCVM 5.10.178 的，暂时还没有 5.10.188 的，
希望可以加上 5.10.188 的。

![Screenshot 2023-11-07 12.11.13.png](https://github.com/tiann/KernelSU/assets/69227436/6103f6ec-39ff-40cb-8790-56120478df11)

**Comment by General110** [comment]
小版本号不一样也可以刷吧？

**Comment by tiann** [comment]
请直接提交 PR，我们开发人员没有 ARCVM 做测试。
