### ISSUE TITLE
刷入了KernelSU 提供的 boot.img，无法进入recovery，反复重启。

### ISSUE THREAD

**Issue by lihaobaba** [tiann/KernelSU#1122]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

在刷入了KernelSU 提供的 boot.img，想进入recovery，但是无法进入recovery，反复重启。

### To Reproduce

-1.刷入了KernelSU 提供的 boot.img，v0.7.0(11326) android13-5.15.78_2023-03-boot.img，版本为[v0.7.0](https://github.com/tiann/KernelSU/releases/tag/v0.7.0)
-2.在KernelSU管理器里面选择重启到recovery，或者自己重启时按住“音量+”键。
-3.无法进入recovery,bootloop.

### Expected behavior

正常重启进入recovery 

### Screenshots

设备信息截图
![Screenshot_2023-11-08-13-23-25-470_me weishu kern](https://github.com/tiann/KernelSU/assets/79950458/1926794b-5268-488c-84f3-d8ba44f83df8)
![Screenshot_2023-11-08-13-23-51-753_com android se](https://github.com/tiann/KernelSU/assets/79950458/32fe2e70-2f3d-4751-bc20-077343de1fec)

### Logs

日志太大 无法上传 
![image](https://github.com/tiann/KernelSU/assets/79950458/56a05fc8-a982-4d7c-a5d4-7a2dd763aa83)

我放在了百度网盘里面 
链接：https://pan.baidu.com/s/1HwBn5dFl3ssQ-dF8j22iuA?pwd=yu36 
提取码：yu36
![D57D4C083AF9E9351AE9B7B2FB79DB63](https://github.com/tiann/KernelSU/assets/79950458/6afd634e-ba47-46c0-abd5-2216301b9ccf)

### Device info

- Device:小米13Pro
- OS Version:正式版内测V14.0.4.0 Android14
- KernelSU Version:v0.7.0(11326) android13-5.15.78_2023-03-boot.img
- Kernel Version:5.15.78-android13-8-00005-gb741ddfc2192-ab10346399

### Additional context

在升级到Android14之后就有这个问题了。在刷入官方boot镜像之后就可以正常进入recovery 。

**Comment by Miuzarte** [comment]
Same OSVersion, KMIVersion and KSUVersion but on Xiaomi 13(fuxi)

**Comment by lihaobaba** [comment]
> Same OSVersion, KMIVersion and KSUVersion but on Xiaomi 13(fuxi), flash by using TWRP (救回来了，14.0.4.0可以用14.0.3.0的boot)

是可以救回来，但是就是进不去recovery。

**Comment by tiann** [comment]
你说的 recovery 是第三方 recovery 还是官方 recovery？

**Comment by Miuzarte** [comment]
> 你说的 recovery 是第三方 recovery 还是官方 recovery？

我试了下，两者都会导致这种情况

**Comment by tiann** [comment]
建议你换一下其他版本的 kernel 试下，我这边实测可以进官方 recovery。日志显示有驱动加载失败，可能recovery不遵守gki？

**Comment by Miuzarte** [comment]
> 建议你换一下其他版本的 kernel 试下，我这边实测可以进官方 recovery。日志显示有驱动加载失败，可能recovery不遵守gki？

其他版本是指0.6.9及其之前吗？目前没啥时间折腾

**Comment by tiann** [comment]
同 KMI 的其他版本，我是 Xiaomi 12SU

**Comment by lihaobaba** [comment]
> 你说的 recovery 是第三方 recovery 还是官方 recovery？

官方recovery和第三方recovery都试了，都是一样进不去。
我已经试了0.6.8，0.6.9都一样。一样都是bootloop。

**Comment by lihaobaba** [comment]
> > 你说的 recovery 是第三方 recovery 还是官方 recovery？
> 
> 官方recovery和第三方recovery都试了，都是一样进不去。 我已经试了0.6.8，0.6.9都一样。一样都是bootloop。

哦，另外提一句，这个问题在我更新了MIUI正式版内测V14.0.2.0 （Android 14）之后，在0.6.8这个版本开始发现的，后面一直都有这个问题。

**Comment by tiann** [comment]
这个目前修不了，recovery 中有驱动符号布局不兼容 GKI 内核；你应该尝试“同 KMI 其他版本内核”，并非使用老版本。

**Comment by lihaobaba** [comment]
好的，谢谢了

**Comment by Miuzarte** [comment]
HyperOS(1.0.23.11.8_Dev)似乎没有这个问题了，ksu0.7.0能正常进入rec，内核版本5.15.94

(重启进FASTBOOT反应过来发现音量键按错了，还好进去了)

**Comment by BlueSword03** [comment]
现在OS1.0.23.12.11DEV干脆就是完全装不上GKI版内核了，安装上就进fastboot😭整个android13-5.15的所有KMI都试了

**Comment by Miuzarte** [comment]
> 现在OS1.0.23.12.11DEV干脆就是完全装不上GKI版内核了，安装上就进fastboot😭整个android13-5.15的所有KMI都试了

不应该啊，我12.4dev还在用5.15.94 a13

**Comment by BlueSword03** [comment]
> > 现在OS1.0.23.12.11DEV干脆就是完全装不上GKI版内核了，安装上就进fastboot😭整个android13-5.15的所有KMI都试了
> 
> 不应该啊，我12.4dev还在用5.15.94 a13

我甚至都尝试像magisk那样先刷完整包再向两个槽位都刷了还是不行🤦‍♂️

**Comment by Supersioxm** [comment]
我的小米13pro也是这情况
