### ISSUE TITLE
Mc Donalds App Detecting KSU Still Pls Fix I Even Tried ZygiskOnKSU 

### ISSUE THREAD

**Issue by parasgargexx20** [tiann/KernelSU#1124]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Mc Donalds App Detecting KSU Still Pls Fix I Even Tried ZygiskOnKSU 

### To Reproduce

1. Go To Playstore (Search McDonalds) (https://play.google.com/store/apps/details?id=com.mcdonalds.mobileapp)
2. Open It 
3. Select Region As India (West South)
4. U Will See Error Message (Like Me) (Upon Clicking Confirm Button)

### Expected behavior

It should not detect it 

### Screenshots

![Screenshot_20231108-211620_McDonald's](https://github.com/tiann/KernelSU/assets/102552831/49f77a75-78c2-405d-a96c-cfd89e80adf1)
![Screenshot_20231108-211620_McDonald's](https://github.com/tiann/KernelSU/assets/102552831/52df9819-b912-46ee-9bf2-6fc8
![Screenshot_20231108-211839_Yet Another SafetyNet Attestation Checker](https://github.com/tiann/KernelSU/assets/102552831/cfe84c36-a65a-4645-ae4e-0e5df34152e8)
989bc65d)
![Screenshot_20231108-212254_Settings](https://github.com/tiann/KernelSU/assets/102552831/e17db61d-56f7-4e74-a515-8a38de8e11a1)
![Screenshot_20231108-212513_KernelSU](https://github.com/tiann/KernelSU/assets/102552831/f1d29821-ab6f-46c3-873c-5a8c4e13fa7c)
![Screenshot_20231108-212537_Chrome Beta](https://github.com/tiann/KernelSU/assets/102552831/91e50bf5-48a9-47e9-b9e2-0a0fc81abe70)

### Logs

[KernelSU_bugreport_2023-11-08_21_10.tar.gz.zip](https://github.com/tiann/KernelSU/files/13298697/KernelSU_bugreport_2023-11-08_21_10.tar.gz.zip)

### Device info

- Device: Redmi Note 9 Pro 4G (miatoll)
- OS Version: 14
- KernelSU Version: 0.7.0
- Kernel Version: 4.14.328

### Additional context

Im Using Evolution X A14 (Community Build) (Initial A14 Build)
Kinesis Kernel (With KSU Support) (by clarencelol)
Safetynet Still Passing
His Repo https://github.com/clarencelol/kernel_xiaomi_sm6250
I Dont Have LSPosed App Installed
Please Refer All Screenshots

**Comment by parasgargexx20** [comment]
This Issue Persist Even Without Iconify And LSPosed And Zygisk Next Module

**Comment by anuragpindoriya** [comment]
@parasgargexx20 we have lsposed module that fix your problem please check this 

https://github.com/Xposed-Modules-Repo/ru.mike.mcroot/releases/tag/8-2.1

**Comment by parasgargexx20** [comment]
> @parasgargexx20 we have lsposed module that fix your problem please check this
> 
> https://github.com/Xposed-Modules-Repo/ru.mike.mcroot/releases/tag/8-2.1

But Its Apk So U Mean I Install The Apk?

**Comment by parasgargexx20** [comment]
Ok After Installing Apk It Shows The Module Not Active So Enabled

**Comment by parasgargexx20** [comment]
I May Reboot Now

**Comment by parasgargexx20** [comment]
Now It Didnt

**Comment by parasgargexx20** [comment]
> @parasgargexx20 we have lsposed module that fix your problem please check this
> 
> https://github.com/Xposed-Modules-Repo/ru.mike.mcroot/releases/tag/8-2.1

No It Didnt

**Comment by anuragpindoriya** [comment]
> No It Didnt

You need to install first apk file of module 
Then after enable module and select mac app

**Comment by parasgargexx20** [comment]
> > No It Didnt
> 
> You need to install first apk file of module Then after enable module and select mac app

Did Exactly That Installed Apk Enabled The Module  And Then Restart

**Comment by parasgargexx20** [comment]
Then Opened Mc Donald

**Comment by anuragpindoriya** [comment]
Can you try clear data of mac app and then reboot and then try to open ( if you uninstall module please do first and try this )

**Comment by parasgargexx20** [comment]
> Can you try clear data of mac app and then reboot and then try to open ( if you uninstall module please do first and try this )

Now I Force Stop
Clear Data Of Mc Donald
Remove Module
Then Reinstall Module
Reboot
Reopen App Still Not Working

**Comment by parasgargexx20** [comment]
> Can you try clear data of mac app and then reboot and then try to open ( if you uninstall module please do first and try this )

Maybe My Play Integrity Broke Due To Google Messing Up Things From Server Side

**Comment by parasgargexx20** [comment]
https://t.me/EvolutionX/780100

**Comment by tiann** [comment]
I think this has nothing to do with KernelSU.
