### ISSUE TITLE
Coloros14开机卡开机动画无法启动（带日志）

### ISSUE THREAD

**Issue by lengyefenghan** [tiann/KernelSU#1132]
### Please check before submitting an issue

- [ ] I have searched the issues and haven't found anything relevant
- [ ] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

与 安卓14(coloros14）使用fastboot刷入android12-5.10.168_2023-05-boot.img无限重启 #1051 的问题近似，只是是采用magiskboot修补的内核
[boot-2023-11-12-ksu_boot_failed.log](https://github.com/tiann/KernelSU/files/13327660/boot-2023-11-12-ksu_boot_failed.log)

### To Reproduce

刷入内核后使用 adb logcat 命令抓取日志，当等待一段时间无法重启时强制关机，同时日志结束抓取

### Device info

- Device:PGZ110
- OS Version:ColorOS14(Android14)
- KernelSU Version:AnyKernel3-android12-5.10.168_2023-05
- Kernel Version:5.10.168-android12-9-o-g586a247351db

**Comment by 2046553272** [comment]
可以自己试试编译一个带kernelsu的版本为5.10.199通用内核，然后进行刷入

**Comment by tiann** [comment]
你可以试一下  patch_level 更高的内核，比如：`2023-10`

**Comment by hamjin** [comment]
https://github.com/oppo-source/android_kernel_oppo_sm8475/blob/oppo/sm8475_u_14.0.0_find_n2/ COS14已经开源了，可以找找不同之处

**Comment by 949331213** [comment]
我也遇到了一样的问题

**Comment by Kara-ism** [comment]
After trying patched via magiskboot as Kernel "AnyKernel3-android12-5.10.168_2023-05" and "AnyKernel3-android12-5.10.198_2023-11" on **OnePlus 10T** with Oxygen OS 14 (Official Kernel：android12-5.10.168) ,
still occurs bootloop/fastboot mode.

尝试自行以magiskboot方式（AnyKernel3-android12-5.10.168_2023-05及AnyKernel3-android12-5.10.198_2023-11都尝试了）
打**一加AcePro**的Oxygen OS 14操作系统补丁（官方内核：android12-5.10.168），仍然卡bootloader或卡在fastboot模式。

**My phone has been flashed to international ROM. Thus I says patched at Oxygen OS 14.

**Comment by tufeigunchu** [comment]
会不会跟avb签名有关。我感觉这个比较奇怪，为何用google公开的testkey_rsa2048.pem来avb签名也可以。难道厂商不会替换成自己的key吗

**Comment by LarissaLycoris** [comment]
刷完以后 fastboot -w  就能重启 清楚用户数据的，但是每次更新都需要这样，亦或者你刷完进rec 选清楚用户数据也能解决。这个方法解决有概率遇到充电死机，电池不显示的bug，应该是一加那边魔改过 不是标准gki，目前解决方法是这样，解决了可以说一下

**Comment by LckHot** [comment]
Realme GT neo5 SE realmeUI5 遇到相同问题。

**Comment by 873578156** [comment]
同样问题

**Comment by weisuofayube** [comment]
好

**Comment by AzusaHana** [comment]
> 刷完以后 fastboot -w 就能重启 清楚用户数据的，但是每次更新都需要这样，亦或者你刷完进rec 选清楚用户数据也能解决。这个方法解决有概率遇到充电死机，电池不显示的bug，应该是一加那边魔改过 不是标准gki，目前解决方法是这样，解决了可以说一下

并不需要每次更新都清除数据，只要保证不使用官方内核开机就不需要清除数据，更新重启前刷 ak3 到另一槽位即可

**Comment by hamjin** [comment]
@tiann 建议关闭此issue，ColorOS14就算清除数据刷入后能开机也会出现待机一段时间后部分应用无法正常启动，直接不兼容14就行了
