### ISSUE TITLE
[manager] Crash after refreshing app profile template page

### ISSUE THREAD

**Issue by Rem01Gaming** [tiann/KernelSU#1136]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

KernelSU's Manager Crash after refreshing app profile template page

### To Reproduce

1. Open settings, App profile template
2. Click the refresh button (next to the sort button)
3. KernelSU crashed

### Expected behavior

The manager crashed, and if you reopen the app's profile template, it will crashed with the same error.

### Screenshots

![Screenshot_20231113-122853_Logcat Reader Professional](https://github.com/tiann/KernelSU/assets/85148357/35472042-637c-4aba-94ba-ce35f41bfcef)

### Logs

- [KernelSU's bugreport](https://github.com/tiann/KernelSU/files/13331095/KernelSU_bugreport_2023-11-13_12_40.tar.gz)

- [KernelSU logcat](https://github.com/tiann/KernelSU/files/13331104/kernelsu_logcat_bugreport.txt)

### Device info

- Device: Realme C25 (even)
- OS Version: DotOS v6.0 (A12L)
- KernelSU Version: 11326(Manager) 11278(KernelSU)
- Kernel Version: v4.14.195

**Comment by tiann** [comment]
`rm -rf /data/adb/ksu/profile/templates` should be ok, this is because the online template id is not equal the file name.
