### ISSUE TITLE
[Feature]如何使用ksu为不同用户授权？

### ISSUE THREAD

**Issue by l-i-git** [tiann/KernelSU#1147]
### Is your feature request related to a problem? Please describe.

我的墓碑类管理应用在两个空间中都生效了，但我仅能在用户0中授予白名单，而无法在用户1中进行管理，导致我现在无法在用户1中正常使用任何输入法，即使已经授予在其他应用上运行权限。

用户0的ksu仅能读取和授权到用户0安装的软件，不能获取到用户1安装的软件更无法授权。

尝试在用户1安装ksu管理器，打开后显示未安装。但事实上用户0中的许多软件都可以读取到用户1，因为我的ksu模块在用户1同样起效，lsp模块也可以按照不同用户管理模块的作用域。

### Describe the solution you'd like.

我需要了解如何使用ksu对用户1中的软件授予root权限，我想：在用户0可读取用户1中的软件并授权，或者可以在用户1中正常启用ksu管理器。

### Describe alternatives you've considered.

在用户0可读取用户1并授权root，或者可以在用户1中正常启用ksu管理器

**Comment by tiann** [comment]
我 MIUI 测试可以在主用户为双开用户授予 root 权限，你什么都没说，所以我无能为力。
