### ISSUE TITLE
关于编译6.1.25内核不开机问题

### ISSUE THREAD

**Issue by LarissaLycoris** [tiann/KernelSU#1148]
我拉的是最新android14-6.1-2023-10
按照官方提供命令tools/bazel build --config=fast //common:kernel_aarch64_dist
编译成功后无法开机
去除ksu版本以后依旧无法开机
官方的ksu 6.1.25内核可以正常开机
想问一下是否需要设置什么东西

**Comment by tiann** [comment]
参考 Github Action。

**Comment by LarissaLycoris** [comment]
> 参考Github Action。

感谢 完美解决 可以开机了

**Comment by LarissaLycoris** [comment]
> 参考 Github Action。

我参考Github Action来编译
发现可以正常开机但是需要2分钟
然后开机以后网络不正常，还有一些奇怪的小bug
我的命令
repo init --depth=1 --u https://android.googlesource.com/kernel/manifest -b common-android14-6.1-2023-10
repo sync -c -j8 --no-tags
tools/bazel run --disk_cache=/home/ubuntumax/android-kernel/cachebazel --config=fast --config=stamp --lto=thin //common:kernel_aarch64_dist -- --dist_dir=dist

我反复研究了Action的编译流程，没发现有特殊的设置地方，是我遗漏了什么么？还需要额外在设置什么？

**Comment by JiuGeFaCai** [comment]
你编译命令用的什么

**Comment by lxsclnb6** [comment]
怎么解决的
