### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by shimabde** [tiann/KernelSU#1152]
### Is your feature request related to a problem? Please describe.

![Screenshot_20231118-000729_Settings~2](https://github.com/tiann/KernelSU/assets/10106046/3d1a36f3-693b-45ec-bbf4-a119c548d555)

### Describe the solution you'd like.

asking for android 12 5.10.189 there's no build for that version since devwlover @ArianK16a build seems based A12

### Describe alternatives you've considered.

tried A13 5.10.189 failed

**Comment by tiann** [comment]
https://github.com/tiann/KernelSU/commit/0db7aa573ed46b0016772dcbda9d9fff33def1be
