### ISSUE TITLE
内核刷入错误

### ISSUE THREAD

**Issue by FanhuaAwA** [tiann/KernelSU#1155]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

红米note13刷入最新版本kernelsu内核包会导致第一屏无限重启 内核版本包为android13-5.10.168_2023-05-boot-gz
重新刷回老版本则无问题

### Device info

- Device:
- OS Version:
- KernelSU Version:11366
- Kernel Version:0.71（11366）

**Comment by FanhuaAwA** [comment]
[Uploading KernelSU_bugreport_2023-11-18_19_14.tar.gz…]()

**Comment by tiann** [comment]
请你尝试使用 magiskboot 这个方式。
