### ISSUE TITLE
有办法隐藏特定文件夹/文件吗？

### ISSUE THREAD

**Issue by daiaji** [tiann/KernelSU#1158]
### Describe your problem.

![Screenshot_20231119-120517_Momo](https://github.com/tiann/KernelSU/assets/25875791/b4b61949-6408-4986-a597-9c337c037e66)

对非原厂系统的检测似乎是通过枚举/system/addon.d实现的。

![Screenshot_20231119-120705_Termux](https://github.com/tiann/KernelSU/assets/25875791/a5966904-2d97-4c4b-8d94-6ad54963ccd7)

普通用户还真能枚举这个文件夹🙃

SELinux似乎只能阻止访问…

https://lore.kernel.org/all/7061.1058873866@www9.gmx.net/T/

这个讨论说需要多实例化目录。

通过检测文件夹/文件是否存在确实是老检测手段了。
能提供个通用的隐藏文件夹/文件的解决方案吗？

2003年的Linux的邮件列表说是未来会有多实例化目录，现在不知道有没有。

不知道是不是Feature，搞不了就当个讨论吧。

**Comment by tiann** [comment]
“非原厂系统的检测”的方法千千万，跟 KernelSU 有什么关系。
