### ISSUE TITLE
[Feature] applock

### ISSUE THREAD

**Issue by foxjaw** [tiann/KernelSU#1159]
### Is your feature request related to a problem? Please describe.

Accidental stuff always happen when our devices used by others. Having the ability to lock KernelSU app will prevent others from avoiding root access grants.

### Describe the solution you'd like.

Ability to lock KernelSU within, and support for biometric authentication too, for convenience.

### Describe alternatives you've considered.

Or like how magisk implemented Prompt method to grant root access every time an app requests it.

**Comment by tiann** [comment]
PRs welcome
