### ISSUE TITLE
Work profile detects root after module installation

### ISSUE THREAD

**Issue by omarilzz** [tiann/KernelSU#1165]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Work profile Microsoft intune company portal detects root once a module is installed in KSU so no work apps would work resulting in a screen stating 
"Device non-complaint This app can't be used because you are using a rooted device. Contact your administrator for help."

In order to be able to use the work apps once more all modules need to be deleted and modules.img to be deleted as well
Although personal apps will work fine whether modules are installed or not

### To Reproduce

KSU Manager
Install a Module
Reboot
Unlock Screen
Navigate and Launch any Work app e.g (Teams,Outlook,etc..)
App loads for a brief moment
Error "Device non-complaint"

### Expected behavior

To behave normally like device isn't even rooted

### Screenshots

![1089356152330256384](https://github.com/tiann/KernelSU/assets/24835326/6603fecb-9316-4797-9583-ea3c7e9f73c2)

### Logs

[bug.zip](https://github.com/tiann/KernelSU/files/13430372/bug.zip)

### Device info

- Device: Redmi Note 9 Pro ( Joyeuse )
- OS Version: 14
- KernelSU Version: 0.7.1
- Kernel Version: 4.14.330

### Additional context

If logs needed kindly advise what type of logs and i will surely share

**Comment by wxt1221** [comment]
你的内核4.14没有使用模块卸载，就会被检测。


Your kernel is 4.14 without umount modules support .

View this:
https://github.com/tiann/KernelSU/discussions/955#discussioncomment-7617166

你可以参考这个。

**Comment by omarilzz** [comment]
I will update the ticket once the maintainer responds

**Comment by omarilzz** [comment]
[bug.zip](https://github.com/tiann/KernelSU/files/13430372/bug.zip)
Bugreport from KSU Manager
We already implemented the fixes you mentioned and yet when ever the simplist module gets installed the work profile gets triggered once modules.img is created

**Comment by tiann** [comment]
> We already implemented the fixes you mentioned 

Please show your kernel source

**Comment by tiann** [comment]
https://github.com/tiann/KernelSU/issues/1062#issuecomment-1773841114
