### ISSUE TITLE
在HyperOS（安卓14）上对Fake Location授予Root权限成功 但软件不能正常使用

### ISSUE THREAD

**Issue by yueqingyou** [tiann/KernelSU#1166]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

猜测是内核的原因（排除法）

**小米14pro**上使用Magisk获取root权限后能够正常使用fake location（虚拟定位软件 1.3.5 beta 1588版本）
换回最新KernelSU后失败

**K60U**上使用Magisk和KSU均能够正常使用

均使用默认的app profile

### To Reproduce

- 授予 fake location 权限
- 点击 启动模拟
- 显示 虚拟位置服务连接失败

### Expected behavior

希望能够正常运行

### Screenshots

![Screenshot_2023-11-22-17-26-33-013_com lerist fakelocation](https://github.com/tiann/KernelSU/assets/70048863/f7879386-cb01-471a-affb-9e3d1661df20)

### Logs

等我重启手机直接运行fake location后再上传 缩小log大小
待上传

### Device info

- Device: 小米14pro
- OS Version: HyperOS 1.0.25.0.UNBCNXM
- KernelSU Version: 11366
- Kernel Version: 11369

**Comment by tiann** [comment]
我不认为是 kernel 的问题。

**Comment by c200154** [comment]
MIUI系统正常用，升级OS系统一启动就重启，kernelsu变宽容模式，去fakelocation启动还是手机重启

**Comment by wlnwl** [comment]
magisk也是一样的启动fakelocation就重启
