### ISSUE TITLE
[Feature] custom resetprop hiding

### ISSUE THREAD

**Issue by privacyguy123** [tiann/KernelSU#1170]
### Is your feature request related to a problem? Please describe.

Many apps detect resetprop editing and refuse to open with apps that use this like Play Integrity Fix as a major example. 

### Describe the solution you'd like.

I noticed builds of Delta and PIF had this feature coded in then strangely removed overnight without explanation. I wonder can KSU adopt such a feature? 

### Describe alternatives you've considered.

Delta/PIF with said code.

**Comment by meiser79** [comment]
It's discussed [here](https://github.com/chiteroman/PlayIntegrityFix/issues/79). The commit is [this](https://github.com/HuskyDG/Magisk/commit/506244f5b) one.

**Comment by backslashxx** [comment]
+1

**Comment by Ylarod** [comment]
KernelSU dosen't modify props, please use third party hiding module like [Shamiko](https://github.com/LSPosed/LSPosed.github.io/releases)
