### ISSUE TITLE
在使用小米内核源码给米8屏幕指纹版集成KSU编译时碰到的问题

### ISSUE THREAD

**Issue by OldGodShen** [tiann/KernelSU#1172]
### Please check before submitting an issue

- [x] I have searched the issues and haven't found anything relevant
- [ ] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

[kernel.log](https://github.com/tiann/KernelSU/files/13467037/kernel.log)
其中报错为
../drivers/kernelsu/apk_sign.c: In function 'check_block':
../drivers/kernelsu/apk_sign.c:101:14: warning: passing argument 1 of 'IS_ERR' makes pointer from integer without a cast
error, forbidden warning: apk_sign.c:101
make[3]: *** [../scripts/Makefile.build:339: drivers/kernelsu/apk_sign.o] Error 1
make[3]: *** Waiting for unfinished jobs....
  CC      drivers/irqchip/irq-gic-v3-its.o
make[2]: *** [../scripts/Makefile.build:653: drivers/kernelsu] Error 2
make[2]: *** Waiting for unfinished jobs....

使用编译的脚本为
export ARCH=arm64
export SUBARCH=arm64
export CROSS_COMPILE=/home/ogs/Kernel/toolchains/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9/bin/aarch64-linux-android-

make O=out equuleus_user_defconfig
make -j$(nproc) O=out 2>&1 | tee kernel.log

toolchain是谷歌的gcc

源码仓库为 https://github.com/OldGodShen/Xiaomi_Kernel_OpenSource
分支为dipper-q-oss

### Device info

- Device:Mi 8 UD
- OS Version:
- KernelSU Version:
- Kernel Version:11366

**Comment by Coconutat** [comment]
如果有兴趣，请参考这个:https://github.com/Coconutat/android_kernel_xiaomi_sdm845_exp

**Comment by Coconutat** [comment]
如果有兴趣，请参考这个:https://github.com/Coconutat/android_kernel_xiaomi_sdm845_exp

**Comment by OldGodShen** [comment]
小米探索版的屏幕指纹工作吗

**Comment by Coconutat** [comment]
> 小米探索版的屏幕指纹工作吗

依然会掉指纹。

**Comment by OldGodShen** [comment]
掉指纹是ksu的问题还是小米源码的问题
还有就是我在编译时gcc不会出错，但是使用Proton-Clang就会出错编译失败

**Comment by Coconutat** [comment]
> 掉指纹是ksu的问题还是小米源码的问题 还有就是我在编译时gcc不会出错，但是使用Proton-Clang就会出错编译失败

官方源码就是只能用GCC，Proton-Clang是我自己修改源码后支持的。然后我顺便Upstream了源码。OLD_KernelSU分支那个是原始的只增加了KSU的源码。

**Comment by OldGodShen** [comment]
懂了
那掉指纹是官方源码的问题吗
