### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by jemsvaib** [tiann/KernelSU#1177]
My phone is infinix note 12 2023
Processor g99 (auth bypass patched )
 it use super.img and have no official custom rom.
I used self build twrp + unofficial twrp both bootloop. As auth bypass patched i had to take it to official customer care and caused me a huge problem.
.
I previously used magisk (now nom root).
I want to install kernel su which method is suitable??

Q1) is your provided boot image risk free?
Q2) if i install magisk and then switch to kernelsu will magisk completely removed?

**Comment by jemsvaib** [comment]
> A1:Official ksu source is from google common kernel(5.10-6.1). Read the guide on ksu official site carefully when flashing images. A2:No. magisk patch the ramdisk, ksu patch the kernel, they are different parts in boot image. Check the guide on kernelsu.org before asking questions.

I mean i want to root with magisk then flash via kernel manager is it okay?

**Comment by jemsvaib** [comment]
> > I mean i want to root with magisk then flash via kernel manager is it okay?
> 
> Yes if you have kernel img then first root with magisk then flash kernel after After check if it cause not any problem then uninstall magisk from magisk manage

I what if i directly flash boot.img by kernelsu?

**Comment by Coconutat** [comment]
> > > I mean i want to root with magisk then flash via kernel manager is it okay?
> > 
> > 
> > Yes if you have kernel img then first root with magisk then flash kernel after After check if it cause not any problem then uninstall magisk from magisk manage
> 
> I what if i directly flash boot.img by kernelsu?

Use Android Image Kitchen unpack boot.img and replace kernel.Then repack it.Now flash the you repacked new boot.img.

**Comment by jemsvaib** [comment]
``

> > > > I mean i want to root with magisk then flash via kernel manager is it okay?
> > > 
> > > 
> > > Yes if you have kernel img then first root with magisk then flash kernel after After check if it cause not any problem then uninstall magisk from magisk manage
> > 
> > 
> > I what if i directly flash boot.img by kernelsu?
> 
> Use Android Image Kitchen unpack boot.img and replace kernel.Then repack it.Now flash the you repacked new boot.img.

Can i communicate with you in telegram/other? I need detailed help please.

**Comment by Coconutat** [comment]
> ``
> 
> > > > > I mean i want to root with magisk then flash via kernel manager is it okay?
> > > > 
> > > > 
> > > > Yes if you have kernel img then first root with magisk then flash kernel after After check if it cause not any problem then uninstall magisk from magisk manage
> > > 
> > > 
> > > I what if i directly flash boot.img by kernelsu?
> > 
> > 
> > Use Android Image Kitchen unpack boot.img and replace kernel.Then repack it.Now flash the you repacked new boot.img.
> 
> Can i communicate with you in telegram/other? I need detailed help please.

Just see it:https://xdaforums.com/t/tool-android-image-kitchen-unpack-repack-kernel-ramdisk-win-android-linux-mac.2073775/

**Comment by jemsvaib** [comment]
> ``
> 
> > > > > I mean i want to root with magisk then flash via kernel manager is it okay?
> > > > 
> > > > 
> > > > Yes if you have kernel img then first root with magisk then flash kernel after After check if it cause not any problem then uninstall magisk from magisk manage
> > > 
> > > 
> > > I what if i directly flash boot.img by kernelsu?
> > 
> > 
> > Use Android Image Kitchen unpack boot.img and replace kernel.Then repack it.Now flash the you repacked new boot.img.
> 
> Can i communicate with you in telegram/other? I need detailed help please.

I used same process for making own twrp + used unofficial twrp that caused my phone brick.
.
1)I  will install Magisk then flash kernelsu kernel and uninstall magisk via magisk manager.
2) directly download gki boot.img  and flash?
Which is better? (I don't wanna take risk of making own kernelsu caused g99 auth bypass patched )

**Comment by Coconutat** [comment]
> > ``
> > > > > > I mean i want to root with magisk then flash via kernel manager is it okay?
> > > > > 
> > > > > 
> > > > > Yes if you have kernel img then first root with magisk then flash kernel after After check if it cause not any problem then uninstall magisk from magisk manage
> > > > 
> > > > 
> > > > I what if i directly flash boot.img by kernelsu?
> > > 
> > > 
> > > Use Android Image Kitchen unpack boot.img and replace kernel.Then repack it.Now flash the you repacked new boot.img.
> > 
> > 
> > Can i communicate with you in telegram/other? I need detailed help please.
> 
> I used same process for making own twrp + used unofficial twrp that caused my phone brick. . 1)I will install Magisk then flash kernelsu kernel and uninstall magisk via magisk manager. 2) directly download gki boot.img and flash? Which is better? (I don't wanna take risk of making own kernelsu caused g99 auth bypass patched )

I don't think it's a question of which method is better. Perhaps the universal kernel is not compatible with your phone, and they may all be GKI 2.0 standards. But you cannot guarantee that every mobile phone manufacturer follows the standards. So, you should try to find the open-source kernel for your phone and integrate it with KernelSU for compilation.Or just because you haven't reformatted your phone. But I don't recommend you doing this.

**Comment by wxt1221** [comment]
三星的破玩意貌似刷内核需要清除data才能启动，之前有相同的issue提到这个问题
