### ISSUE TITLE
OxygenOS 14 Not Supported?

### ISSUE THREAD

**Issue by H4X0R46** [tiann/KernelSU#1182]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

I'm using a OnePlus 11 USA variant on OxygenOS 14. When I download the correct kernelsu file and try to boot it with fastboot, it sends the phone to the recovery menu... When rebooting from recovery, it of course defaults back to the phones installed boot.

So using "fastboot boot <kernelsu>.img just sent the device into recovery menu. 

I also tried the anykernel3 option and built one, did the same thing for me.

### To Reproduce

using "fastboot boot <kernelsu>.img just sent the device into recovery menu. 

### Expected behavior

It should boot with kernelsu working.

### Device info

- Device: CPH2451
- OS Version: OOS 14.0.0.201(EX01)
- KernelSU Version: android13-5.15.94_2023-05-boot-gz.img.gz
- Kernel Version: 5.15.94

**Comment by tiann** [comment]
try magiskboot way

**Comment by ashoktvm** [comment]
Same issue here. Not able to boot into OS in Android 14 after using correct anykernel3 version

**Comment by tiann** [comment]
#1051
