### ISSUE TITLE
Oooof! Not an issue, just had to vent

### ISSUE THREAD

**Issue by CamsShaft** [tiann/KernelSU#1190]
My head hurts from reading all that! Haha
 Anyways, it looks great and it's pretty technical stuff. I've got an SM-S901W S22 Android 14 with this kernel: 5.10.168-android12-9-27760517-abS901WVLU3DWK5 which is all fine and dandy EXCEPT my bootloader is locked. I made it all the way to the end when I read the faq saying I need my bootloader unlocked. So that's awesome... I'm seriously done with samsung when the next shitty upgrade comes out. Before this one I had an S10 and can't do anything with that one either. It's so annoying seeing all these great upgrades and mods on the exact same phone as mine and I'm stuck with daddy google in a gimp suit in some truck stop bathroom while everyone points and laughs. I wish I never started learning about customizing and stayed ignorant. Grrrr. Rant over, thanks for all your hard work anyways and hope my next phone doesn't suck so I can start supporting you guys!

**Comment by wxt1221** [comment]
Why an issue？

**Comment by CamsShaft** [comment]
> Why an issue？

Because in order to install this I need to unlock the bootloader which I can't do on my phone.

**Comment by jason-eu** [comment]
What operator, baseband and firmware version?

**Comment by CamsShaft** [comment]
> What operator, baseband and firmware version?

Operator? Which carrier you mean? Baseband is S901WVLU3DWK5 and it's Android 14. Sorry, I think I need a bit more info from you... is this what you need? Service provider software version
SAOMC_SM-S901W_OYV_PMB_14_0006
PMB/PMB,PMB/XAC/KDO

**Comment by jason-eu** [comment]
Carrier. Yes.

**Comment by CamsShaft** [comment]
> Carrier. Yes.

Oh okay, public mobile in Canada. They're a subsidiary of Telus which is a major company

**Comment by CamsShaft** [comment]
> Carrier. Yes.

I've also exhausted my brain on xda forums and apparently the Snapdragon variant can not be unlocked so I just kinda stopped looking.

**Comment by CamsShaft** [comment]
> So it isn't that you're just on a locked bootloader, but also, you're specifically on a carrier locked bootloader.

I can switch out sim cards for any carrier, doesn't that mean it's unlocked? And besides that, I already knew what you've said. Not sure where this conversation is going.

**Comment by jason-eu** [comment]
Maybe.

It just seems that you have a model that is normally under a contract with the operator, and I don't think anyone has the source for those yet, best I could find was up to S20.

Anything higher looked like scam unlocks.

**Comment by CamsShaft** [comment]
> Maybe.
> 
> It just seems that you have a model that is normally under a contract with the operator, and I don't think anyone has the source for those yet, best I could find was up to S20.
> 
> Anything higher looked like scam unlocks.

Huh, weird. Never heard of that. I can cancel at any time and go with bell, rogers, t-mobile etc if I wanted to. I've mainly been bothering the hell out of samsung and google in the hopes they just relent or just completely boot me so they have no choice but to take their "spyware" off my system lol. Wishful thinking

**Comment by jason-eu** [comment]
SAMPWND on telegram used to do paid unlocks but I think they stopped a while ago, mainly due to lack of access to source code.

**Comment by CamsShaft** [comment]
Yeah, I followed that for a while but didn't feel like paying for it. It's definitely worth the time and effort these guys put into it, I'd just rather wait until something else comes up. I dunno if that'll ever happen though since android keeps pushing new devices and code into the world. Devs can't keep up I'm sure. I'm surprised magisk is still kicking it but I guess @topjohnwu is pretty much a cyborg anyways so he just knows haha
