### ISSUE TITLE
[Feature] Build for aarch32

### ISSUE THREAD

**Issue by scarlettekk** [tiann/KernelSU#1193]
### Is your feature request related to a problem? Please describe.

Some older devices and exotic newer devices (ie. Pixel Watch 2) run in 32-bit armv8l mode. KernelSU is currently only built for AMD64 and aarch64

### Describe the solution you'd like.

It would be nice if 32 bit manager apks were built in arm 32 bit packages as well to make installation easier.

### Describe alternatives you've considered.

Compiling manually is probably possible but bothersome.

### Additional context

armv8l should be compatible with armv7l? not sure though

**Comment by tiann** [comment]
It's not just as simple as recompiling the manager. And we have no plan to support 32bit devices.

**Comment by tiann** [comment]
1. We have data structure mapping from kernel, so the kernel must adopt for 32bit.
2. We must make `ksud` working for 32bit.
3. We use `resetprop` and `busybox`, it also needs to work on 32bit.

I don't think it is worth to do that, 32 bit is already history.

**Comment by scarlettekk** [comment]
Hmm. I guess I'll stick to magisk on my watch then

**Comment by backslashxx** [comment]
If anyone tried to look, this is doable, but theres a small near-null pointer dereference bug that has to be patched for 64-bit-kernel-with-32-bit-userspace. 64-on-64 / 32-on-32 is not an issue.

small patch for kernel driver: https://github.com/BYZYB/android_kernel_xiaomi_libra/commit/2228f8de5193a5431d55b04595d3e29726bc9170

manager side:
https://github.com/tiann/KernelSU/commits/6173646/

Squashed
https://github.com/tiann/KernelSU/compare/60cdbea..be33f8c


Ofcourse this is not recommended to be done with kprobes/lkm integration as you have to add those symbols on arch.h.
this'll work as is on manual integration
