### ISSUE TITLE
Boot failure after installing December 2023 update on my Google Pixel 6 Pro

### ISSUE THREAD

**Issue by TebbeUbben** [tiann/KernelSU#1195]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

I have installed the December 2023 update for my phone, but can't get KernelSU working anymore. I have tried to patch the boot.img using magiskboot, Android-Image-Kitchen and Kernel Flasher (by installing Magisk first), but it always boots back into the bootloader and shows reason "boot failure". The kernel version has increased from 5.10.157 to 5.10.177.

### Logs

[KernelSU_bugreport_2023-12-08_12_58.tar.gz](https://github.com/tiann/KernelSU/files/13613822/KernelSU_bugreport_2023-12-08_12_58.tar.gz)

### Device info

- Device: Google Pixel 6 Pro
- OS Version: 14.0.0 (UQ1A.231205.015, Dec 2023)
- KernelSU Version: v0.7.1
- Kernel Version: 5.10.177-android13-4-00003-ga7208022a7ea-ab10815828

**Comment by SinhoMoeme** [comment]
have this issue too!

**Comment by tiann** [comment]
Which factory image do you use? it works well on my Pixel 6.

**Comment by TebbeUbben** [comment]
> Which factory image do you use? it works well on my Pixel 6.

[https://developers.google.com/android/images#ravenuq1a.231205.015](https://developers.google.com/android/images#ravenuq1a.231205.015)

The international version (14.0.0 (UQ1A.231205.015, Dec 2023), so not the AT&T image.

**Comment by wankenobi666** [comment]
> > Which factory image do you use? it works well on my Pixel 6.
> 
> https://developers.google.com/android/images#ravenuq1a.231205.015
> 
> The international version (14.0.0 (UQ1A.231205.015, Dec 2023), so not the AT&T image.

me too. how you solve this issue?

**Comment by hendryaripin** [comment]
> Which factory image do you use? it works well on my Pixel 6.

same problem also but on pixel 7 pro, before update to dec patch, restoring november boot.img using fastboot flash boot boot.img, then update using system update direct from the phone.

for dec boot.img grab from downloaded factory image from google.

14.0.0 (UQ1A.231205.015, Dec 2023)
https://dl.google.com/dl/android/aosp/cheetah-uq1a.231205.015-factory-99c57348.zip

non verizon version.

**Comment by wankenobi666** [comment]
> > Which factory image do you use? it works well on my Pixel 6.
> 
> same problem also but on pixel 7 pro, before update to dec patch, restoring november boot.img using fastboot flash boot boot.img, then update using system update direct from the phone.
> 
> for dec boot.img grab from downloaded factory image from google.
> 
> 14.0.0 (UQ1A.231205.015, Dec 2023) https://dl.google.com/dl/android/aosp/cheetah-uq1a.231205.015-factory-99c57348.zip
> 
> non verizon version.

Nevermind just solve my problem using image 5.10.189-android13. The image from 5.10.177-android13 not working for me

**Comment by hendryaripin** [comment]
> > > Which factory image do you use? it works well on my Pixel 6.
> > 
> > 
> > same problem also but on pixel 7 pro, before update to dec patch, restoring november boot.img using fastboot flash boot boot.img, then update using system update direct from the phone.
> > for dec boot.img grab from downloaded factory image from google.
> > 14.0.0 (UQ1A.231205.015, Dec 2023) https://dl.google.com/dl/android/aosp/cheetah-uq1a.231205.015-factory-99c57348.zip
> > non verizon version.
> 
> Nevermind just solve my problem using image 5.10.189-android13. The image from 5.10.177-android13 not working for me

will try that later. thanks.

**Comment by xhemp** [comment]
> Nevermind just solve my problem using image 5.10.189-android13. The image from 5.10.177-android13 not working for me

Interesting that worked for me on a Pixel 7 Pro, thanks!

**Comment by tiann** [comment]
The security patch level must not less than the stock image's security patch level.

**Comment by mdogwoop** [comment]
Doesn't seem to work on pixel 7, neither 5.10.177 nor 5.10.189 works

**Comment by onokatio** [comment]
Same (on Pixel7 panther).
Not working on 5.10.189
