### ISSUE TITLE
一加12刷入失败

### ISSUE THREAD

**Issue by jiemo9527** [tiann/KernelSU#1204]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

无论是bootloader刷入，还是anykernel修补boot，还是什么刷原boot清data再刷；君无效
求解

### Device info

- Device:一加12
- OS Version:coloros14.0
- KernelSU Version:0.71
- Kernel Version:0.71

**Comment by jiemo9527** [comment]
内核6.1.25

**Comment by 949331213** [comment]
我的一加ace2 也是有同样的问题，看到别人的解决办法是  刷入 boot后  需要进re清楚数据，之后重启就可以正常，这一定是COloros14的问题，不知道后续能不能解决，怕就在以后每次ota升级是需要清理数据才能恢复

**Comment by tiann** [comment]
请把issue模版写全。

**Comment by tiann** [comment]
你反馈个问题，什么都不填，操作步骤也不说，你指望别人怎么修？算命是吧

**Comment by jiemo9527** [comment]
我删了 问你也没用
你自己的安装教程方式三和四  还来问我

**Comment by jiemo9527** [comment]
勿Q 已取关

**Comment by tiann** [comment]
你装的是master版本还是ci版本，你全文没一句有信息的话；赶紧取关吧，小学生
