### ISSUE TITLE
color os14  无法刷入KernelSU boot后无法启动

### ISSUE THREAD

**Issue by 949331213** [tiann/KernelSU#1205]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

我试过自行修补boot和开发者提供的boot都是无法开机使用

### Device info

- Device:一加ace2
- OS Version: os14
- KernelSU Version:  0.7.1
- Kernel Version:5.10.168-Android12-9

**Comment by tiann** [comment]
你刷的是哪个版本，具体是怎么刷的？什么都不讲，我只能认为是无效反馈。
