### ISSUE TITLE
一加12刷android14-6.1.25_2023-10变砖

### ISSUE THREAD

**Issue by MaverickYing** [tiann/KernelSU#1206]
### Please check before submitting an issue

- [ ] I have searched the issues and haven't found anything relevant
- [ ] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

一加12 可以刷init_boot获得面具，但无法直接通过刷android14-6.1.25_2023-10-boot.img （特征为fastboot boot后进入fastbootd而不是系统）,面具root后通过Kernel Flasher刷AnyKernel3-android14-6.1.25_2023-10.zip直接变砖

### Device info

- Device:Oneplus 12 PJD110
- OS Version:ColorOS14
- KernelSU Version:android14-6.1.25_2023-10
- Kernel Version:6.1.25-android14-11-g9b16c7ea69e8

**Comment by ashoktvm** [comment]
Looks like issues are coming up for Oxygen OS. @tiann  please loo into this and the OnePlus 11R 5.10.168 OOS 14 issue

**Comment by tiann** [comment]
试一下最新的 ci 版本，用 magiskboot 的方式。

**Comment by ashoktvm** [comment]
> 试一下最新的 ci 版本，用 magiskboot 的方式。

can we try using android image kitchen?

**Comment by MaverickYing** [comment]
solved
解决了
刷完自修补boot以后需要fastboot -w
而且电脑不能用锐龙CPU.......

**Comment by MaverickYing** [comment]
solved
color OS must type fastboot -w after flash boot.img

**Comment by weihaiwh** [comment]
> solved 解决了 刷完自修补boot以后需要fastboot -w 而且电脑不能用锐龙CPU.......

我焯 感谢！！！ 同款 解决了

**Comment by ashoktvm** [comment]
> solved color OS must type fastboot -w after flash boot.img

Doesnt that wipe all the data. And isnt that creates unnecessary data wiping everytime an update is released?

**Comment by 949331213** [comment]
> solved 解决了 刷完自修补boot以后需要fastboot -w 而且电脑不能用锐龙CPU.......

但是我还有问题，后续ota升级是否需要再次清除数据，以及使用中还有什么潜在问题，不知道后续这个问题能否解决

**Comment by tiann** [comment]
如果还想测试，可以刷回官方 boot，然后再刷这个：https://github.com/tiann/KernelSU/actions/runs/7180854283 
里面的 6.1.43 试一下不 fastboot -w 能否启动。

**Comment by neoshui** [comment]
> 如果还想测试，可以刷回官方 boot，然后再刷这个：https://github.com/tiann/KernelSU/actions/runs/7180854283 里面的 6.1.43 试一下不 fastboot -w 能否启动。

我把 6.1.* 都试过一遍了，刷完不清除数据无法开机。

**Comment by tiann** [comment]
> > 如果还想测试，可以刷回官方 boot，然后再刷这个：https://github.com/tiann/KernelSU/actions/runs/7180854283 里面的 6.1.43 试一下不 fastboot -w 能否启动。
> 
> 一加12，colorOS 14 Android 14，内核6.1.25，我把 6.1.* 都试过一遍了，刷完不清除数据无法开机。

用 magiskboot 方式刷的？

**Comment by weigeloveu** [comment]
> solved 解决了 刷完自修补boot以后需要fastboot -w 而且电脑不能用锐龙CPU.......

这个不能用锐龙cpu是什么鬼？我是用aik打包的，尝试了release版本跟ci的6.1.43版本，-w也是进不去系统

**Comment by MaverickYing** [comment]
> > solved 解决了 刷完自修补boot以后需要fastboot -w 而且电脑不能用锐龙CPU.......
> 
> 这个不能用锐龙cpu是什么鬼？我是用aik打包的，尝试了release版本跟ci的6.1.43版本，-w也是进不去系统

锐龙CPU在用fastboot和adb的时候会有连接失败的bug 公司电脑是12代i 一点问题没有

**Comment by weigeloveu** [comment]
> > > solved 解决了 刷完自修补boot以后需要fastboot -w 而且电脑不能用锐龙CPU.......
> > 
> > 
> > 这个不能用锐龙cpu是什么鬼？我是用aik打包的，尝试了release版本跟ci的6.1.43版本，-w也是进不去系统
> 
> 锐龙CPU在用fastboot和adb的时候会有连接失败的bug 公司电脑是12代i 一点问题没有

我这边显示执行命令成功了，也不好使吗？不过解锁之后确实是连不上adb了，解锁之前还可以的。话说大佬用的是哪个boot，现在aik打包不行了吗？要用magisk的方法？
```
 .\fastboot.exe -w
Erasing 'userdata'                                 OKAY [  0.047s]

    F2FS-tools: mkfs.f2fs Ver: 1.16.0 (2023-04-11)

Info: Disable heap-based policy
Info: Debug level = 1
Info: Trim is disabled
Info: Set conf for android
Info: Enable Project quota
Info: Segments per section = 1
Info: Sections per zone = 1
Info: sector size = 512
Info: total sectors = 456099960 (222705 MB)
Info: zone aligned segment0 blkaddr: 512
Info: add quota type = 0 => 4
Info: add quota type = 1 => 5
Info: add quota type = 2 => 6
Info: format version with
  ""
[f2fs_init_sit_area: 638]       Filling sit area at offset 0x00600000
[f2fs_init_nat_area: 672]       Filling nat area at offset 0x01600000
[f2fs_add_default_dentry_root:1255]     Writing default dentry root, at offset 0x2b000
[f2fs_write_root_inode:1300]    Writing root inode (hot node), offset 0x2aa00
[f2fs_write_default_quota:1389]         Writing quota data, at offset 0002b001, 0002b002
[f2fs_write_qf_inode:1438]      Writing quota inode (hot node), offset 0x2aa01
[f2fs_write_default_quota:1389]         Writing quota data, at offset 0002b003, 0002b004
[f2fs_write_qf_inode:1438]      Writing quota inode (hot node), offset 0x2aa02
[f2fs_write_default_quota:1389]         Writing quota data, at offset 0002b005, 0002b006
[f2fs_write_qf_inode:1438]      Writing quota inode (hot node), offset 0x2aa03
[f2fs_update_nat_default:1475]  Writing nat root, at offset 0x00001600
Info: Overprovision ratio = 0.300%
Info: Overprovision segments = 342 (GC reserved = 340)
[f2fs_write_check_point_pack: 854]      Writing main segments, cp at offset 0x00000200
[f2fs_write_check_point_pack: 942]      Writing Segment summary for HOT/WARM/COLD_DATA, at offset 0x00000201
[f2fs_write_check_point_pack: 956]      Writing Segment summary for HOT_NODE, at offset 0x00000202
[f2fs_write_check_point_pack: 968]      Writing Segment summary for WARM_NODE, at offset 0x00000203
[f2fs_write_check_point_pack: 979]      Writing Segment summary for COLD_NODE, at offset 0x00000204
[f2fs_write_check_point_pack: 987]      Writing cp page2, at offset 0x00000205
[f2fs_write_check_point_pack:1007]      Writing NAT bits pages, at offset 0x000003fe
[f2fs_write_check_point_pack:1028]      Writing cp page 1 of checkpoint pack 2, at offset 0x00000400
[f2fs_write_check_point_pack:1047]      Writing cp page 2 of checkpoint pack 2, at offset 0x00000405
[f2fs_write_super_block:1080]   Writing super block, at offset 0x00000000
Info: format successful
Sending 'userdata' (97 KB)                         OKAY [  0.016s]
Writing 'userdata'                                 OKAY [  0.031s]
wipe task partition not found: cache
Erasing 'metadata'                                 OKAY [  4.301s]

    F2FS-tools: mkfs.f2fs Ver: 1.16.0 (2023-04-11)

Info: Disable heap-based policy
Info: Debug level = 1
Info: Trim is disabled
Info: Set conf for android
Info: Enable Project quota
Info: Segments per section = 1
Info: Sections per zone = 1
Info: sector size = 512
Info: total sectors = 131072 (64 MB)
Info: zone aligned segment0 blkaddr: 512
Info: add quota type = 0 => 4
Info: add quota type = 1 => 5
Info: add quota type = 2 => 6
Info: format version with
  ""
[f2fs_init_sit_area: 638]       Filling sit area at offset 0x00600000
[f2fs_init_nat_area: 672]       Filling nat area at offset 0x00a00000
[f2fs_add_default_dentry_root:1255]     Writing default dentry root, at offset 0x1600
[f2fs_write_root_inode:1300]    Writing root inode (hot node), offset 0x1000
[f2fs_write_default_quota:1389]         Writing quota data, at offset 00001601, 00001602
[f2fs_write_qf_inode:1438]      Writing quota inode (hot node), offset 0x1001
[f2fs_write_default_quota:1389]         Writing quota data, at offset 00001603, 00001604
[f2fs_write_qf_inode:1438]      Writing quota inode (hot node), offset 0x1002
[f2fs_write_default_quota:1389]         Writing quota data, at offset 00001605, 00001606
[f2fs_write_qf_inode:1438]      Writing quota inode (hot node), offset 0x1003
[f2fs_update_nat_default:1475]  Writing nat root, at offset 0x00000a00
Info: Overprovision ratio = 55.000%
Info: Overprovision segments = 10 (GC reserved = 8)
[f2fs_write_check_point_pack: 854]      Writing main segments, cp at offset 0x00000200
[f2fs_write_check_point_pack: 942]      Writing Segment summary for HOT/WARM/COLD_DATA, at offset 0x00000201
[f2fs_write_check_point_pack: 956]      Writing Segment summary for HOT_NODE, at offset 0x00000202
[f2fs_write_check_point_pack: 968]      Writing Segment summary for WARM_NODE, at offset 0x00000203
[f2fs_write_check_point_pack: 979]      Writing Segment summary for COLD_NODE, at offset 0x00000204
[f2fs_write_check_point_pack: 987]      Writing cp page2, at offset 0x00000205
[f2fs_write_check_point_pack:1007]      Writing NAT bits pages, at offset 0x000003ff
[f2fs_write_check_point_pack:1028]      Writing cp page 1 of checkpoint pack 2, at offset 0x00000400
[f2fs_write_check_point_pack:1047]      Writing cp page 2 of checkpoint pack 2, at offset 0x00000405
[f2fs_write_super_block:1080]   Writing super block, at offset 0x00000000
Info: format successful
Sending 'metadata' (92 KB)                         OKAY [  0.000s]
Writing 'metadata'                                 OKAY [  0.202s]
Finished. Total time: 6.675s

```

**Comment by MaverickYing** [comment]
> > > > solved 解决了 刷完自修补boot以后需要fastboot -w 而且电脑不能用锐龙CPU.......
> > > 
> > > 
> > > 这个不能用锐龙cpu是什么鬼？我是用aik打包的，尝试了release版本跟ci的6.1.43版本，-w也是进不去系统
> > 
> > 
> > 锐龙CPU在用fastboot和adb的时候会有连接失败的bug 公司电脑是12代i 一点问题没有
> 
> 我这边显示执行命令成功了，也不好使吗？不过解锁之后确实是连不上adb了，解锁之前还可以的。话说大佬用的是哪个boot，现在aik打包不行了吗？要用magisk的方法？
> 
> ```
>  .\fastboot.exe -w
> Erasing 'userdata'                                 OKAY [  0.047s]
> 
>     F2FS-tools: mkfs.f2fs Ver: 1.16.0 (2023-04-11)
> 
> Info: Disable heap-based policy
> Info: Debug level = 1
> Info: Trim is disabled
> Info: Set conf for android
> Info: Enable Project quota
> Info: Segments per section = 1
> Info: Sections per zone = 1
> Info: sector size = 512
> Info: total sectors = 456099960 (222705 MB)
> Info: zone aligned segment0 blkaddr: 512
> Info: add quota type = 0 => 4
> Info: add quota type = 1 => 5
> Info: add quota type = 2 => 6
> Info: format version with
>   ""
> [f2fs_init_sit_area: 638]       Filling sit area at offset 0x00600000
> [f2fs_init_nat_area: 672]       Filling nat area at offset 0x01600000
> [f2fs_add_default_dentry_root:1255]     Writing default dentry root, at offset 0x2b000
> [f2fs_write_root_inode:1300]    Writing root inode (hot node), offset 0x2aa00
> [f2fs_write_default_quota:1389]         Writing quota data, at offset 0002b001, 0002b002
> [f2fs_write_qf_inode:1438]      Writing quota inode (hot node), offset 0x2aa01
> [f2fs_write_default_quota:1389]         Writing quota data, at offset 0002b003, 0002b004
> [f2fs_write_qf_inode:1438]      Writing quota inode (hot node), offset 0x2aa02
> [f2fs_write_default_quota:1389]         Writing quota data, at offset 0002b005, 0002b006
> [f2fs_write_qf_inode:1438]      Writing quota inode (hot node), offset 0x2aa03
> [f2fs_update_nat_default:1475]  Writing nat root, at offset 0x00001600
> Info: Overprovision ratio = 0.300%
> Info: Overprovision segments = 342 (GC reserved = 340)
> [f2fs_write_check_point_pack: 854]      Writing main segments, cp at offset 0x00000200
> [f2fs_write_check_point_pack: 942]      Writing Segment summary for HOT/WARM/COLD_DATA, at offset 0x00000201
> [f2fs_write_check_point_pack: 956]      Writing Segment summary for HOT_NODE, at offset 0x00000202
> [f2fs_write_check_point_pack: 968]      Writing Segment summary for WARM_NODE, at offset 0x00000203
> [f2fs_write_check_point_pack: 979]      Writing Segment summary for COLD_NODE, at offset 0x00000204
> [f2fs_write_check_point_pack: 987]      Writing cp page2, at offset 0x00000205
> [f2fs_write_check_point_pack:1007]      Writing NAT bits pages, at offset 0x000003fe
> [f2fs_write_check_point_pack:1028]      Writing cp page 1 of checkpoint pack 2, at offset 0x00000400
> [f2fs_write_check_point_pack:1047]      Writing cp page 2 of checkpoint pack 2, at offset 0x00000405
> [f2fs_write_super_block:1080]   Writing super block, at offset 0x00000000
> Info: format successful
> Sending 'userdata' (97 KB)                         OKAY [  0.016s]
> Writing 'userdata'                                 OKAY [  0.031s]
> wipe task partition not found: cache
> Erasing 'metadata'                                 OKAY [  4.301s]
> 
>     F2FS-tools: mkfs.f2fs Ver: 1.16.0 (2023-04-11)
> 
> Info: Disable heap-based policy
> Info: Debug level = 1
> Info: Trim is disabled
> Info: Set conf for android
> Info: Enable Project quota
> Info: Segments per section = 1
> Info: Sections per zone = 1
> Info: sector size = 512
> Info: total sectors = 131072 (64 MB)
> Info: zone aligned segment0 blkaddr: 512
> Info: add quota type = 0 => 4
> Info: add quota type = 1 => 5
> Info: add quota type = 2 => 6
> Info: format version with
>   ""
> [f2fs_init_sit_area: 638]       Filling sit area at offset 0x00600000
> [f2fs_init_nat_area: 672]       Filling nat area at offset 0x00a00000
> [f2fs_add_default_dentry_root:1255]     Writing default dentry root, at offset 0x1600
> [f2fs_write_root_inode:1300]    Writing root inode (hot node), offset 0x1000
> [f2fs_write_default_quota:1389]         Writing quota data, at offset 00001601, 00001602
> [f2fs_write_qf_inode:1438]      Writing quota inode (hot node), offset 0x1001
> [f2fs_write_default_quota:1389]         Writing quota data, at offset 00001603, 00001604
> [f2fs_write_qf_inode:1438]      Writing quota inode (hot node), offset 0x1002
> [f2fs_write_default_quota:1389]         Writing quota data, at offset 00001605, 00001606
> [f2fs_write_qf_inode:1438]      Writing quota inode (hot node), offset 0x1003
> [f2fs_update_nat_default:1475]  Writing nat root, at offset 0x00000a00
> Info: Overprovision ratio = 55.000%
> Info: Overprovision segments = 10 (GC reserved = 8)
> [f2fs_write_check_point_pack: 854]      Writing main segments, cp at offset 0x00000200
> [f2fs_write_check_point_pack: 942]      Writing Segment summary for HOT/WARM/COLD_DATA, at offset 0x00000201
> [f2fs_write_check_point_pack: 956]      Writing Segment summary for HOT_NODE, at offset 0x00000202
> [f2fs_write_check_point_pack: 968]      Writing Segment summary for WARM_NODE, at offset 0x00000203
> [f2fs_write_check_point_pack: 979]      Writing Segment summary for COLD_NODE, at offset 0x00000204
> [f2fs_write_check_point_pack: 987]      Writing cp page2, at offset 0x00000205
> [f2fs_write_check_point_pack:1007]      Writing NAT bits pages, at offset 0x000003ff
> [f2fs_write_check_point_pack:1028]      Writing cp page 1 of checkpoint pack 2, at offset 0x00000400
> [f2fs_write_check_point_pack:1047]      Writing cp page 2 of checkpoint pack 2, at offset 0x00000405
> [f2fs_write_super_block:1080]   Writing super block, at offset 0x00000000
> Info: format successful
> Sending 'metadata' (92 KB)                         OKAY [  0.000s]
> Writing 'metadata'                                 OKAY [  0.202s]
> Finished. Total time: 6.675s
> ```

我用的首页里面自修补的[Android-Image-Kitchen] 一加12的安装方法是不能用fastboot boot的 是必须直接fastboot flash boot xxxx.img 刷完再接fastboot -w 所以你要备份一个原厂boot镜像防止变砖
黑厂真的要事情

**Comment by weigeloveu** [comment]
> > > > > solved 解决了 刷完自修补boot以后需要fastboot -w 而且电脑不能用锐龙CPU.......
> > > > 
> > > > 
> > > > 这个不能用锐龙cpu是什么鬼？我是用aik打包的，尝试了release版本跟ci的6.1.43版本，-w也是进不去系统
> > > 
> > > 
> > > 锐龙CPU在用fastboot和adb的时候会有连接失败的bug 公司电脑是12代i 一点问题没有
> > 
> > 
> > 我这边显示执行命令成功了，也不好使吗？不过解锁之后确实是连不上adb了，解锁之前还可以的。话说大佬用的是哪个boot，现在aik打包不行了吗？要用magisk的方法？
> > ```
> >  .\fastboot.exe -w
> > Erasing 'userdata'                                 OKAY [  0.047s]
> > 
> >     F2FS-tools: mkfs.f2fs Ver: 1.16.0 (2023-04-11)
> > 
> > Info: Disable heap-based policy
> > Info: Debug level = 1
> > Info: Trim is disabled
> > Info: Set conf for android
> > Info: Enable Project quota
> > Info: Segments per section = 1
> > Info: Sections per zone = 1
> > Info: sector size = 512
> > Info: total sectors = 456099960 (222705 MB)
> > Info: zone aligned segment0 blkaddr: 512
> > Info: add quota type = 0 => 4
> > Info: add quota type = 1 => 5
> > Info: add quota type = 2 => 6
> > Info: format version with
> >   ""
> > [f2fs_init_sit_area: 638]       Filling sit area at offset 0x00600000
> > [f2fs_init_nat_area: 672]       Filling nat area at offset 0x01600000
> > [f2fs_add_default_dentry_root:1255]     Writing default dentry root, at offset 0x2b000
> > [f2fs_write_root_inode:1300]    Writing root inode (hot node), offset 0x2aa00
> > [f2fs_write_default_quota:1389]         Writing quota data, at offset 0002b001, 0002b002
> > [f2fs_write_qf_inode:1438]      Writing quota inode (hot node), offset 0x2aa01
> > [f2fs_write_default_quota:1389]         Writing quota data, at offset 0002b003, 0002b004
> > [f2fs_write_qf_inode:1438]      Writing quota inode (hot node), offset 0x2aa02
> > [f2fs_write_default_quota:1389]         Writing quota data, at offset 0002b005, 0002b006
> > [f2fs_write_qf_inode:1438]      Writing quota inode (hot node), offset 0x2aa03
> > [f2fs_update_nat_default:1475]  Writing nat root, at offset 0x00001600
> > Info: Overprovision ratio = 0.300%
> > Info: Overprovision segments = 342 (GC reserved = 340)
> > [f2fs_write_check_point_pack: 854]      Writing main segments, cp at offset 0x00000200
> > [f2fs_write_check_point_pack: 942]      Writing Segment summary for HOT/WARM/COLD_DATA, at offset 0x00000201
> > [f2fs_write_check_point_pack: 956]      Writing Segment summary for HOT_NODE, at offset 0x00000202
> > [f2fs_write_check_point_pack: 968]      Writing Segment summary for WARM_NODE, at offset 0x00000203
> > [f2fs_write_check_point_pack: 979]      Writing Segment summary for COLD_NODE, at offset 0x00000204
> > [f2fs_write_check_point_pack: 987]      Writing cp page2, at offset 0x00000205
> > [f2fs_write_check_point_pack:1007]      Writing NAT bits pages, at offset 0x000003fe
> > [f2fs_write_check_point_pack:1028]      Writing cp page 1 of checkpoint pack 2, at offset 0x00000400
> > [f2fs_write_check_point_pack:1047]      Writing cp page 2 of checkpoint pack 2, at offset 0x00000405
> > [f2fs_write_super_block:1080]   Writing super block, at offset 0x00000000
> > Info: format successful
> > Sending 'userdata' (97 KB)                         OKAY [  0.016s]
> > Writing 'userdata'                                 OKAY [  0.031s]
> > wipe task partition not found: cache
> > Erasing 'metadata'                                 OKAY [  4.301s]
> > 
> >     F2FS-tools: mkfs.f2fs Ver: 1.16.0 (2023-04-11)
> > 
> > Info: Disable heap-based policy
> > Info: Debug level = 1
> > Info: Trim is disabled
> > Info: Set conf for android
> > Info: Enable Project quota
> > Info: Segments per section = 1
> > Info: Sections per zone = 1
> > Info: sector size = 512
> > Info: total sectors = 131072 (64 MB)
> > Info: zone aligned segment0 blkaddr: 512
> > Info: add quota type = 0 => 4
> > Info: add quota type = 1 => 5
> > Info: add quota type = 2 => 6
> > Info: format version with
> >   ""
> > [f2fs_init_sit_area: 638]       Filling sit area at offset 0x00600000
> > [f2fs_init_nat_area: 672]       Filling nat area at offset 0x00a00000
> > [f2fs_add_default_dentry_root:1255]     Writing default dentry root, at offset 0x1600
> > [f2fs_write_root_inode:1300]    Writing root inode (hot node), offset 0x1000
> > [f2fs_write_default_quota:1389]         Writing quota data, at offset 00001601, 00001602
> > [f2fs_write_qf_inode:1438]      Writing quota inode (hot node), offset 0x1001
> > [f2fs_write_default_quota:1389]         Writing quota data, at offset 00001603, 00001604
> > [f2fs_write_qf_inode:1438]      Writing quota inode (hot node), offset 0x1002
> > [f2fs_write_default_quota:1389]         Writing quota data, at offset 00001605, 00001606
> > [f2fs_write_qf_inode:1438]      Writing quota inode (hot node), offset 0x1003
> > [f2fs_update_nat_default:1475]  Writing nat root, at offset 0x00000a00
> > Info: Overprovision ratio = 55.000%
> > Info: Overprovision segments = 10 (GC reserved = 8)
> > [f2fs_write_check_point_pack: 854]      Writing main segments, cp at offset 0x00000200
> > [f2fs_write_check_point_pack: 942]      Writing Segment summary for HOT/WARM/COLD_DATA, at offset 0x00000201
> > [f2fs_write_check_point_pack: 956]      Writing Segment summary for HOT_NODE, at offset 0x00000202
> > [f2fs_write_check_point_pack: 968]      Writing Segment summary for WARM_NODE, at offset 0x00000203
> > [f2fs_write_check_point_pack: 979]      Writing Segment summary for COLD_NODE, at offset 0x00000204
> > [f2fs_write_check_point_pack: 987]      Writing cp page2, at offset 0x00000205
> > [f2fs_write_check_point_pack:1007]      Writing NAT bits pages, at offset 0x000003ff
> > [f2fs_write_check_point_pack:1028]      Writing cp page 1 of checkpoint pack 2, at offset 0x00000400
> > [f2fs_write_check_point_pack:1047]      Writing cp page 2 of checkpoint pack 2, at offset 0x00000405
> > [f2fs_write_super_block:1080]   Writing super block, at offset 0x00000000
> > Info: format successful
> > Sending 'metadata' (92 KB)                         OKAY [  0.000s]
> > Writing 'metadata'                                 OKAY [  0.202s]
> > Finished. Total time: 6.675s
> > ```
> 
> 我用的首页里面自修补的[Android-Image-Kitchen] 一加12的安装方法是不能用fastboot boot的 是必须直接fastboot flash boot xxxx.img 刷完再接fastboot -w 所以你要备份一个原厂boot镜像防止变砖 黑厂真的要事情

我用的也是aik修补的，我再试一下刷完直接-w行不行

**Comment by weigeloveu** [comment]
> > > 如果还想测试，可以刷回官方 boot，然后再刷这个：https://github.com/tiann/KernelSU/actions/runs/7180854283 里面的 6.1.43 试一下不 fastboot -w 能否启动。
> > 
> > 
> > 一加12，colorOS 14 Android 14，内核6.1.25，我把 6.1.* 都试过一遍了，刷完不清除数据无法开机。
> 
> 用 magiskboot 方式刷的？

我刚才用magisk模式patch了一遍ci版本的6.1.43，开机卡解锁警告界面

**Comment by weigeloveu** [comment]
> 如果还想测试，可以刷回官方 boot，然后再刷这个：https://github.com/tiann/KernelSU/actions/runs/7180854283 里面的 6.1.43 试一下不 fastboot -w 能否启动。

千万不要这么弄，直接刷死，bootloader都进不去，卡黄字警告，只能9008

**Comment by MaverickYing** [comment]
> > 如果还想测试，可以刷回官方 boot，然后再刷这个：https://github.com/tiann/KernelSU/actions/runs/7180854283 里面的 6.1.43 试一下不 fastboot -w 能否启动。
> 
> 千万不要这么弄，直接刷死，bootloader都进不去，卡黄字警告，只能9008

你是不是刷错了 把intl-boot和boot搞混了？我没成功的时候都是卡bootlloader的

**Comment by neoshui** [comment]
> > > 如果还想测试，可以刷回官方 boot，然后再刷这个：https://github.com/tiann/KernelSU/actions/runs/7180854283 里面的 6.1.43 试一下不 fastboot -w 能否启动。
> > 
> > 
> > 一加12，colorOS 14 Android 14，内核6.1.25，我把 6.1.* 都试过一遍了，刷完不清除数据无法开机。
> 
> 用 magiskboot 方式刷的？

是的，使用 magiskboot  修补 boot，再刷入，还是必须清空数据才能开机。另外刷上ksu之后，晚上充电手机都会假死，必须强制开机。sys/fs/pstore 文件夹是空的，我把kernelsu app内获取到的日志发到tg了

**Comment by fatinghenji** [comment]
> > > > 如果还想测试，可以刷回官方 boot，然后再刷这个：https://github.com/tiann/KernelSU/actions/runs/7180854283 里面的 6.1.43 试一下不 fastboot -w 能否启动。
> > > 
> > > 
> > > 一加12，colorOS 14 Android 14，内核6.1.25，我把 6.1.* 都试过一遍了，刷完不清除数据无法开机。
> > 
> > 
> > 用 magiskboot 方式刷的？
> 
> 是的，使用 magiskboot 修补 boot，再刷入，还是必须清空数据才能开机。另外刷上ksu之后，晚上充电手机都会假死，必须强制开机。sys/fs/pstore 文件夹是空的，我把kernelsu app内获取到的日志发到tg了

请问目前假死的问题解决了吗？

**Comment by neoshui** [comment]
> > > > > 如果还想测试，可以刷回官方 boot，然后再刷这个：https://github.com/tiann/KernelSU/actions/runs/7180854283 里面的 6.1.43 试一下不 fastboot -w 能否启动。
> > > > 
> > > > 
> > > > 一加12，colorOS 14 Android 14，内核6.1.25，我把 6.1.* 都试过一遍了，刷完不清除数据无法开机。
> > > 
> > > 
> > > 用 magiskboot 方式刷的？
> > 
> > 
> > 是的，使用 magiskboot 修补 boot，再刷入，还是必须清空数据才能开机。另外刷上ksu之后，晚上充电手机都会假死，必须强制开机。sys/fs/pstore 文件夹是空的，我把kernelsu app内获取到的日志发到tg了
> 
> 请问目前假死的问题解决了吗？

我换用其它root方案了，根据网友情况，假死问题依旧存在
