### ISSUE TITLE
Not able to boot with patched boot.img on a Pixel 7 Pro

### ISSUE THREAD

**Issue by xhemp** [tiann/KernelSU#1207]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Trying to patch a boot.img and flash it with KernelSU doesn't work, device keeps boot looping after the Google (G) logo.

### To Reproduce

- Downloaded cheetah_beta-ap11.231117.006-factory-733e0d9a.zip from https://developer.android.com/about/versions/14/download
- Extracted boot.img from it
- Unpacked with magiskboot
- Moved Image from [AnyKernel3-android13-5.10.177_2023-06.zip] to kernel
- Packed with Magisk
- Tried to boot with the new-boot.img created to no avail

### Expected behavior

To boot with KernelSU

### Device info

- Device: Pixel 7 Pro
- OS Version: Android 14
- KernelSU Version: 0.7.1
- Kernel Version: 5.10.177

### Additional context

Haven't uploaded the Report.log as the device doesn't boot with KernelSU

**Comment by TebbeUbben** [comment]
Probably related to #1195

**Comment by hendryaripin** [comment]
got the same problem also...

**Comment by hendryaripin** [comment]
solved the problem https://github.com/tiann/KernelSU/issues/1195#issuecomment-1857113124

**Comment by xhemp** [comment]
Just to add what I added on 1195, this has been resolved by installing kernel 5.10.189.
