### ISSUE TITLE
Blocking the SIM Card (PIN SIM card) crashes the system and sends it to recovery

### ISSUE THREAD

**Issue by Insidevk18** [tiann/KernelSU#1211]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

When you put a pin on the SIM card, after a reboot, the system crashes (I think it crashes the system UI), the screen flashes black and after 5 seconds, it sends to the custom recovery.
Curiously, when I turn it off and on (not restart) it gives me a couple of seconds to enter the SIM PIN, and then it enters the system normally. I had to remove the SIM PIN to avoid this "crash", but I think this feature is very important in terms of security.

Note: With the Stock Kernel of the rom this crash or problem did not happen.

### To Reproduce

Go to settings

security

activate SIM PIN (Lock SIM)

Restart

### Expected behavior

Crashes the UI, flashes black and sends to recovery, if you boot again the system repeats itself in a loop.

Apparent Solution:
Turn off, then turn on

Quickly set the SIM PIN

Remove SIM PIN in settings

### Screenshots

Cannot take screenshot of the bug

### Logs

I didn't find log

### Device info

- Device: Redmi Note 11 (spes)
- OS Version: Custom ROM - DroidX UI 1.7 LTS
- KernelSU Version: 0.7.1
- Kernel Version: Custom Kernel: 4.19.298 Snowgrave 

### Additional context

Maybe it could be a compatibility problem of the Custom kernel with the Custom ROM, and maybe I should notify the Kernel dev instead of here, I hope this bug does not appear in other models.

**Comment by tiann** [comment]
Do you install any module? I don't think this is a KernelSU issue.
