### ISSUE TITLE
Missing an android12-5.10.198

### ISSUE THREAD

**Issue by orionbg** [tiann/KernelSU#1212]
### Is your feature request related to a problem? Please describe.

Hello KernelSU developer,

Any chance you can add the android12-5.10.198 patched kernel image?
The original one can be found at: https://source.android.com/docs/core/architecture/kernel/gki-android12-5_10-release-builds
The one called: android12-5.10-2023-11_r2

Thank you!

### Describe the solution you'd like.

Patched img

### Describe alternatives you've considered.

Could use an older one probably but this one seems to have some newer code that helps my Foldable phone run better.

**Comment by tiann** [comment]
https://github.com/tiann/KernelSU/actions/runs/7158924415
