### ISSUE TITLE
android 14 6.1.25的内核 直接编译刷入小米14后卡开机第二屏

### ISSUE THREAD

**Issue by androiddisk** [tiann/KernelSU#1217]
### Describe your problem.

https://github.com/tiann/KernelSU/releases/download/v0.7.1/AnyKernel3-android14-6.1.25_2023-10.zip
首先从发布页面提取6.1.25中的Image 然后用教程的magiskboot 打补丁到小米14的内核是能开机并且kernelsu的app检测到kernelsu正常运行了，那说明我按照代码里面使用的分支的common-android14-6.1-2023-10 小米14是可以开机的才对

但是我手动拉代码来编译，编译成功后开机就卡第二屏了

这是 我拉代码的命令

```
  mkdir android-kernel && cd android-kernel
  repo init --depth=1 --u https://android.googlesource.com/kernel/manifest -b common-android14-6.1-2023-10 --repo-rev=v2.16
  REMOTE_BRANCH=$(git ls-remote https://android.googlesource.com/kernel/common android14-6.1-2023-10)
  DEFAULT_MANIFEST_PATH=.repo/manifests/default.xml
  if grep -q deprecated <<< $REMOTE_BRANCH; then
    echo "Found deprecated branch: android14-6.1-2023-10"
    sed -i 's/"android14-6.1-2023-10"/"deprecated\/android14-6.1-2023-10"/g' $DEFAULT_MANIFEST_PATH
    cat $DEFAULT_MANIFEST_PATH
  fi
  repo --version
  repo --trace sync -c -j$(nproc --all) --no-tags

```
编译命令试过
```
tools/bazel build --config=fast //common:kernel_aarch64_dist

```
还有
```
 tools/bazel run --disk_cache=/home/runner/.cache/bazela --config=fast --config=stamp --lto=thin //common:kernel_aarch64_dist -- --dist_dir=dist

```

编译出来的Image 提取改名成kernel 用magiskboot打包回去 就卡第二屏了。  搞了一整天了 不知道是哪里没弄对，求解 感激不尽

**Comment by JTAHQO** [comment]
用11月的可以开机，但是wifi数据都失效了，不知道你有没有遇到过

**Comment by JiuGeFaCai** [comment]
目前我也是用的tools/bazel run --config=fast --config=stamp --lto=thin //common:kernel_aarch64_dist -- --dist_dir=dist这个命令，也不能开机为啥

**Comment by JiuGeFaCai** [comment]
> 用11月的可以开机，但是wifi数据都失效了，不知道你有没有遇到过

你编译6.1用的哪一条命令开机的？
