### ISSUE TITLE
Not available on Pixel 7 (panther) updated to December patch (UQ1A.231205.015)

### ISSUE THREAD

**Issue by mdogwoop** [tiann/KernelSU#1219]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Any 5.10-a13 kernels are not available, like #1195 

### Logs

[KernelSU_bugreport_2023-12-20_23_48.tar.gz](https://github.com/tiann/KernelSU/files/13729381/KernelSU_bugreport_2023-12-20_23_48.tar.gz)

### Device info

- Device: Google Pixel 7
- OS Version:14 (UQ1A.231205.015)
- KernelSU Version:N/A
- Kernel Version:5.10.177-android13-4-00003-ga7208022a7ea-ab10815828
#1 Fri Sep 15 16:40:54 UTC 2023

**Comment by BakaChocolate** [comment]
Someone mentioned this in the Telegram group: use android13-5.10.189_2023-10 instead.

**Comment by mdogwoop** [comment]
> 有人在 Telegram 中提到过这一点：使用 android13-5.10.189_2023-10 代替。

This seems to be only for pixel 7 pro and not pixel 7

**Comment by BakaChocolate** [comment]
> > 有人在 Telegram 中提到过这一点：使用 android13-5.10.189_2023-10 代替。
> 
> This seems to be only for pixel 7 pro and not pixel 7

It should work on all Pixels on Android 14 stable with December security patch.

**Comment by mdogwoop** [comment]
Oh sorry maybe it's android-image-kitchen problem 

> > > 有人在 Telegram 中提到过这一点：使用 android13-5.10.189_2023-10 代替。
> > 
> > 
> > This seems to be only for pixel 7 pro and not pixel 7
> 
> It should work on all Pixels on Android 14 stable with December security patch.

Oh sorry maybe it's android-image-kitchen problem, magiskboot is work

**Comment by tiann** [comment]
Android Image Kitchen is not recommended now: https://github.com/tiann/KernelSU/commit/534ac8819520db2f234df279e7b801130c29e433
