### ISSUE TITLE
The application detected root.

### ISSUE THREAD

**Issue by andheartman** [tiann/KernelSU#1224]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [x] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

tr.gov.saglik.MHRSMOBIL Root detects..

### Screenshots

![Screenshot_2023-12-23-10-50-38-176_tr gov saglik MHRSMOBIL](https://github.com/tiann/KernelSU/assets/57493481/7618c031-15a2-4622-81a4-09258b49ca09)
![Screenshot_2023-12-23-10-53-29-932_com miui securitycenter](https://github.com/tiann/KernelSU/assets/57493481/52d4b0f7-eec6-42df-800c-a94f1fd48af2)
![Screenshot_2023-12-23-10-53-33-964_com miui securitycenter](https://github.com/tiann/KernelSU/assets/57493481/b104580b-7cfa-4f15-b2d5-48b280007a24)
![Screenshot_2023-12-23-10-53-41-651_com miui securitycenter](https://github.com/tiann/KernelSU/assets/57493481/8a851bbc-dbe6-4cdd-9b30-84ee7f3cb106)

### Logs

[KernelSU_bugreport_2023-12-23_11_00.tar.gz](https://github.com/tiann/KernelSU/files/13758399/KernelSU_bugreport_2023-12-23_11_00.tar.gz)

### Device info

- Device:
- OS Version:
- KernelSU Version:
- Kernel Version:

**Comment by andheartman** [comment]
My phone detected root for the first time. Even root checker doesn't see root.

**Comment by andheartman** [comment]
Device: Note 9 Pro Joyeuse
Os Versiyon: Mi 14 Android 12
KernelSu: 0.7.1
Version: 11366

**Comment by andheartman** [comment]
![Screenshot_2023-12-23-11-07-28-236_me weishu kernelsu](https://github.com/tiann/KernelSU/assets/57493481/b9e447eb-fc3d-41ca-a584-f0ce86894f68)

**Comment by andheartman** [comment]
I tried using MHRS application from KernelSu, but the problem was not solved. Custom settings, etc.

**Comment by meiser79** [comment]
There was a module to unmount the modules, it was [here](https://github.com/HuskyDG/ksu_unmount_injector/releases)

I found a fork [here](https://github.com/gmh5225/ksu_unmount_injector/tags), but you need to compile on your own.

Or you could try my compiled version (I removed the systemless hosts mount feature): 
[ksu_unmount_injector-1.11.2-module.zip](https://github.com/tiann/KernelSU/files/13761103/ksu_unmount_injector-1.11.2-module.zip)

**Comment by andheartman** [comment]
> There was a module to unmount the modules, it was [here] (https://github.com/HuskyDG/ksu_unmount_injector/releases) 
> 
> I found a fork [here](https://github.com/gmh5225/ksu_unmount_injector/tags), but you need to compile on your own.
> 
> Or you could try my compiled version (I removed the systemless hosts mount feature): [ksu_unmount_injector-1.11.2-module.zip](https://github.com/tiann/KernelSU/files/13761103/ksu_unmount_injector-1.11.2-module.zip)

Not work🥲 I don't know how to compile.

**Comment by tiann** [comment]
#1062
