### ISSUE TITLE
授权多用户中的同一应用再将其卸载导致 bootloop

### ISSUE THREAD

**Issue by MoeBakaW** [tiann/KernelSU#1227]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [ ] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

为两个用户内的同一应用都授予 root 权限，再将其卸载，卸载完成时就会直接黑屏并无限重启卡第二屏（已复现成功）；进入 rec 内删除 .allowlist 文件后恢复正常。

### To Reproduce

1. 为两个用户内的同一应用都授予 root 权限
2. 在两个用户内都把这个应用卸载
3. bootloop

### Device info

- Device: Redmi Note 12 Turbo (marble)
- OS Version: crDroid 10 (Android 14)
- KernelSU Version: 0.7.1(11366)
- Kernel Version: 5.10.204

**Comment by tiann** [comment]
请在复现后在 recovery 中保存一份 allowlist 传上来
