### ISSUE TITLE
I want to use kernelsu on Docker container Android 12, is this feasible?

### ISSUE THREAD

**Issue by 124ffee** [tiann/KernelSU#1234]
My system is Ubuntu 22.04 ARM64 kernel version is 5.10.160. Can I use kernelsu? I install Docker container in this Ubuntu system and run Redroid Android 12.I want to grant kernelsu privileges to this Android 12 systemIf you can take a look, please provide me with some guidance.This is the Redroid project address“https://github.com/remote-android/redroid-doc”

**Comment by tiann** [comment]
It is feasible, but you need to try yourself.

**Comment by 124ffee** [comment]
> It is feasible, but you need to try yourself.

Can you give me an idea? Kernelsu is equivalent to repairing the boot kernel of Android, but I am a Docker container. Android does not have a kernel and shares the same kernel with the host Ubuntu 22.04. Is it possible for me to modify Ubuntu's kernel file

**Comment by wxt1221** [comment]
It is hard to say. KernelSU works in kernel. But docker just uses kernel in your real machine. You can try to install KernelSU in your kernel in physical machine. You should complie kernel by yourself.




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "tiann/KernelSU"                                                                                    ***@***.***&gt;;
Date:&nbsp;Fri, Dec 29, 2023 03:05 PM
***@***.***&gt;;
***@***.***&gt;;
Subject:&nbsp;Re: [tiann/KernelSU] I want to use kernelsu on Docker container Android 12, is this feasible? (Issue #1234)





  
It is feasible, but you need to try yourself.
  
Can you give me an idea? Kernelsu is equivalent to repairing the boot kernel of Android, but I am a Docker container. Android does not have a kernel and shares the same kernel with the host Ubuntu 22.04. Is it possible for me to modify Ubuntu's kernel file
