### ISSUE TITLE
[BUG] Missing Ram memory

### ISSUE THREAD

**Issue by ItsMadruga** [tiann/KernelSU#1236]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

The error comes from previous updates, my device contains **8 GB of RAM**, but when I install KernelSU, in any part of the system or applications it shows that it only contains **6 GB of RAM**, I have previously made a complaint to the creator and he did not respond concrete or whether you would try to solve the problem.

### To Reproduce

- Install KernelSu

### Expected behavior

The device must contain **8GB RAM**

### Screenshots

![Screenshot_20231229_164737_DevCheck](https://github.com/tiann/KernelSU/assets/104334266/5d5e9111-b7de-40fc-b723-c8678a4de882)
![Screenshot_20231229_164351_Device care](https://github.com/tiann/KernelSU/assets/104334266/16cfb565-8286-44ac-a5b7-326cc8cd7bbd)
![image](https://github.com/tiann/KernelSU/assets/104334266/06b32d84-91c1-419d-ad5a-dc08b231dc09)

### Logs

[KernelSU_bugreport_2023-12-29_16_42.tar.gz](https://github.com/tiann/KernelSU/files/13795749/KernelSU_bugreport_2023-12-29_16_42.tar.gz)

### Device info

- Device: SM-A546E
- OS Version: 14 (One Ui 6.0)
- KernelSU Version: [v0.7.1](https://github.com/tiann/KernelSU/releases/tag/v0.7.1)
- Kernel Version: 5.15.104-android13-8-ga041cbdf86aa

### Additional context

Please resolve this, thanks in advance

**Comment by ItsMadruga** [comment]
## Update

- I tested the new version and again the error persists

@tiann

**Comment by Aryanxfa** [comment]
I not a official ksu support, your bootloader shows 8gb ram as detected. So I am interested to know why the kernel reduces the ram size for whatever reason. I am looking for KMSG logs that start with 
Booting Linux Kernel version 5.15.104 
You can either get kmsg with adb or Liveboot with Android 13. remember to get them at log time. they are lost as the system progresses with boot

**Comment by ItsMadruga** [comment]
> Não sou um suporte oficial do ksu, seu bootloader mostra 8 GB de RAM detectado. Então, estou interessado em saber por que o kernel reduz o tamanho da memória RAM por qualquer motivo. Estou procurando logs KMSG que começam com Booting Linux Kernel versão 5.15.104. Você pode obter kmsg com adb ou Liveboot com Android 13. lembre-se de obtê-los no momento do log. eles são perdidos à medida que o sistema avança com a inicialização

Hello, thank you for your interest, I'm not very experienced in this part, if you can teach me how to help you, I'll do it with good pleasure.

**Comment by Aryanxfa** [comment]
> > I not a official ksu support, your bootloader shows 8gb ram as detected. So I am interested to know why the kernel reduces the ram size for whatever reason. I am looking for KMSG logs that start with
> > "Booting Linux Kernel version 5.15.104"
> > You can either get kmsg with adb or Liveboot with Android 13. remember to get them at log time. they are lost as the system progresses with boot
> > cc @ItsMadruga
> 
> Hello, thank you for your interest, I'm not very experienced in this part, if you can teach me how to help you, I'll do it with good pleasure.
> 
> @Aryanxfa

Sure, bit radical method but i would suggest to let the device boot till the device logo changes from A54 to just before Samsung Galaxy. now break its boot by holding down all vol+, vol- and power (it takes about 10-15 seconds depending on device. time it before or after So that you can get that logs) till it goes to a black. once you see black screen switch to vol+ and power and boot to twrp. in twrp adb pull /dev/last_kmsg . open it and see if it has that line and a few more lines after it. 

what we are doing here is just stopping the boot process right before android startup and preserving the kernel logs. since that is the only part that is changed to use ksu.
Also i would like to ask if you tried compiling and running the kernel without KSU patches to see if there is any error in the kernel source.

**Comment by ItsMadruga** [comment]
> > > I not a official ksu support, your bootloader shows 8gb ram as detected. So I am interested to know why the kernel reduces the ram size for whatever reason. I am looking for KMSG logs that start with
> > > "Booting Linux Kernel version 5.15.104"
> > > You can either get kmsg with adb or Liveboot with Android 13. remember to get them at log time. they are lost as the system progresses with boot
> > > cc @ItsMadruga
> > 
> > 
> > Hello, thank you for your interest, I'm not very experienced in this part, if you can teach me how to help you, I'll do it with good pleasure.
> > @Aryanxfa
> 
> Sure, bit radical method but i would suggest to let the device boot till the device logo changes from A54 to just before Samsung Galaxy. now break its boot by holding down all vol+, vol- and power (it takes about 10-15 seconds depending on device. time it before or after So that you can get that logs) till it goes to a black. once you see black screen switch to vol+ and power and boot to twrp. in twrp adb pull /dev/last_kmsg . open it and see if it has that line and a few more lines after it.
> 
> what we are doing here is just stopping the boot process right before android startup and preserving the kernel logs. since that is the only part that is changed to use ksu. Also i would like to ask if you tried compiling and running the kernel without KSU patches to see if there is any error in the kernel source.

Right, this part of twrp to obtain kmsg will not be viable, as I do not use a custom recovery, and regarding the second question, no, I even tried to research a little, to build the su kernel from Samsung's own kernel, as it modifies them, but I wasn't successful, as I didn't have experience, I was afraid of ruining the device.

**Comment by ItsMadruga** [comment]
@Aryanxfa The Lsposed module obtains kmsg, would it be useful?

**Comment by Aryanxfa** [comment]
> @Aryanxfa The Lsposed module obtains kmsg, would it be useful?

It could be check if it has that line

**Comment by Aryanxfa** [comment]
> 
> I didn't find anything like that, see the file below
> 
> [kmsg.log](https://github.com/tiann/KernelSU/files/13839708/kmsg.log)
> 
> @Aryanxfa

not useful

**Comment by ItsMadruga** [comment]
> > I didn't find anything like that, see the file below
> > [kmsg.log](https://github.com/tiann/KernelSU/files/13839708/kmsg.log)
> > @Aryanxfa
> 
> not useful

Would there be another way to get it?

**Comment by ItsMadruga** [comment]
[last_kmsg.txt](https://github.com/tiann/KernelSU/files/13840024/last_kmsg.txt)

Would it be useful?

@Aryanxfa

**Comment by ItsMadruga** [comment]
@tiann Would you help me?

**Comment by tiann** [comment]
I think this may be a samsung issue of GKI kernel, similar: #756 

You can try the samsung offical kernel source with KernelSU: https://github.com/BlackMesa123/android_kernel_samsung_s5e8835

**Comment by ItsMadruga** [comment]
@tiann

I just found a version built for my device, made by @BlackMesa123 , in version v0.7.5, and the error was resolved.

https://xdaforums.com/t/kernel-a546b-e-kernelsu-v0-7-5-for-galaxy-a54-5g.4607539/
