### ISSUE TITLE
Inbuilt App Lock and Biometric unlock in KernelSU Manager 

### ISSUE THREAD

**Issue by y0geshx** [tiann/KernelSU#1238]
### Is your feature request related to a problem? Please describe.

It's always better to have extra layer of protection cuz it's a root manager 

### Describe the solution you'd like.

Add AppLock and biometric unlock in KernelSU manager 

### Describe alternatives you've considered.

There is alternative you can use AppLock that's provide by your OEM rom, sadly my rom doesn't provide one (⁠´⁠;⁠︵⁠;⁠`⁠)

**Comment by tiann** [comment]
The lock screen guard is the final defense of your device security. Adding app lock does nothing except giving you psychological comfort.

Do you need to add app lock for every root app? they can do everything same as manager in theory.
