### ISSUE TITLE
kernelsu升级到11414版本，但busybox未跟着升级

### ISSUE THREAD

**Issue by powerAn2020** [tiann/KernelSU#1242]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

管理器版本和kernel版本已升级到最新，但是busybox版本没有跟着升级

### Expected behavior

busybox升级到1.36.1

### Screenshots

![6a2b4eb46b5b57b8a22ed82aa1cc6ef](https://github.com/tiann/KernelSU/assets/25736019/5e938f3b-0a9b-42e7-a8ad-9c14802e0182)
![image](https://github.com/tiann/KernelSU/assets/25736019/2a58e1be-a617-4071-9b18-76badcc8b3a8)

### Logs

[KernelSU_bugreport_2024-01-02_14_31.tar.gz](https://github.com/tiann/KernelSU/files/13807670/KernelSU_bugreport_2024-01-02_14_31.tar.gz)

### Device info

- Device: Redmi K40
- OS Version: miui 14.0.8.0
- KernelSU Version: 11414
- Kernel Version: 4.19.298

**Comment by tiann** [comment]
删除 `/data/adb/ksu/bin` 目录可以重新生成
