### ISSUE TITLE
关于5.10-gki内核不支持overlay的一些问题

### ISSUE THREAD

**Issue by ItosEO** [tiann/KernelSU#1248]
您好，weishu
我有一个设备是5.10.149-gki内核
我刷入ksu的img后会卡开机，刷入ak3后su正常使用，但是无法使用模块系统，ksu管理器提示内核不支持overlay
这种情况有什么解决办法吗，没有内核源代码

**Comment by wxt1221** [comment]
您猜猜GKI干什么的

**Comment by tiann** [comment]
log

**Comment by ItosEO** [comment]
您好，可以简单说说怎么搞吗

**Comment by wxt1221** [comment]
![image](https://github.com/tiann/KernelSU/assets/74451279/99eb1e8a-098b-48e7-86e7-6463b84af964)
@ItosEO
