### ISSUE TITLE
Selecting apps that are allowed root access does not persist reboot

### ISSUE THREAD

**Issue by privacyguy123** [tiann/KernelSU#1249]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

When I select apps to use Root and reboot, they are not remembered.

### To Reproduce

1. Add app to root profile
2. Reboot

### Expected behavior

Apps I selected to allow root should persist on reboot.

### Logs

[KernelSU_bugreport_2024-01-05_00_40.tar.gz](https://github.com/tiann/KernelSU/files/13836759/KernelSU_bugreport_2024-01-05_00_40.tar.gz)

### Device info

- Device: Samsung S20 FE
- OS Version: A13
- KernelSU Version: 11413
- Kernel Version:  11413

**Comment by Ylarod** [comment]
dup with #436 

read #943

**Comment by privacyguy123** [comment]
> dup with #436
> 
> read #943

Linked issue does not show solution. I am not stupid and don't need walked through how to build the Kernel... I need an explanation as to why this issue exists in my already built Kernel. 🤔

**Comment by privacyguy123** [comment]
> If you read the issue carefully, you won't ask this.

Sorry I did not translate all posts - I will see if kernel dev understands PR you linked.

**Comment by Sinclair19** [comment]
> > If you read the issue carefully, you won't ask this.
> 
> Sorry I did not translate all posts - I will see if kernel dev understands PR you linked.
> 
> What doesn't make sense is that it's from v0.6.6 and I'm on latest 0.7.2

I fixed this by editing some code like 
```
if LINUX_VERSION_CODE < KERNEL_VERSION(4, 10, 0)
```
(4, 10, 0) to (4, 15, 0)
to let it work on my 4.14 kernel temporarily. You could have a try

A old commit as a reference
https://github.com/roberto-sartori-gl/KernelSU/commit/2c7cce67cf03361c22a07f13575eece82ef47517

**Comment by privacyguy123** [comment]
> > > If you read the issue carefully, you won't ask this.
> > 
> > 
> > Sorry I did not translate all posts - I will see if kernel dev understands PR you linked.
> > What doesn't make sense is that it's from v0.6.6 and I'm on latest 0.7.2
> 
> I fixed this by editing some code like
> 
> ```
> if LINUX_VERSION_CODE < KERNEL_VERSION(4, 10, 0)
> ```
> 
> (4, 10, 0) to (4, 15, 0) to let it work on my 4.14 kernel temporarily. You could have a try
> 
> A old commit as a reference [roberto-sartori-gl@2c7cce6](https://github.com/roberto-sartori-gl/KernelSU/commit/2c7cce67cf03361c22a07f13575eece82ef47517)

Can you explain more why my system is not able to write to .allowlist file though?

**Comment by privacyguy123** [comment]
> > > If you read the issue carefully, you won't ask this.
> > 
> > 
> > Sorry I did not translate all posts - I will see if kernel dev understands PR you linked.
> > What doesn't make sense is that it's from v0.6.6 and I'm on latest 0.7.2
> 
> I fixed this by editing some code like
> 
> ```
> if LINUX_VERSION_CODE < KERNEL_VERSION(4, 10, 0)
> ```
> 
> (4, 10, 0) to (4, 15, 0) to let it work on my 4.14 kernel temporarily. You could have a try
> 
> A old commit as a reference [roberto-sartori-gl@2c7cce6](https://github.com/roberto-sartori-gl/KernelSU/commit/2c7cce67cf03361c22a07f13575eece82ef47517)

Revisiting this issue to try and fix - did you try this PR on Samsung devices to confirm if KSU can access .allowlist file with encrypted device?

**Comment by Sinclair19** [comment]
> > > > If you read the issue carefully, you won't ask this.
> > > 
> > > 
> > > Sorry I did not translate all posts - I will see if kernel dev understands PR you linked.
> > > What doesn't make sense is that it's from v0.6.6 and I'm on latest 0.7.2
> > 
> > 
> > I fixed this by editing some code like
> > ```
> > if LINUX_VERSION_CODE < KERNEL_VERSION(4, 10, 0)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > (4, 10, 0) to (4, 15, 0) to let it work on my 4.14 kernel temporarily. You could have a try
> > A old commit as a reference [roberto-sartori-gl@2c7cce6](https://github.com/roberto-sartori-gl/KernelSU/commit/2c7cce67cf03361c22a07f13575eece82ef47517)
> 
> Revisiting this issue to try and fix - did you try this PR on Samsung devices to confirm if KSU can access .allowlist file with encrypted device?

I don't have Samsung device. So I don't know.

**Comment by privacyguy123** [comment]
> > > > > If you read the issue carefully, you won't ask this.
> > > > 
> > > > 
> > > > Sorry I did not translate all posts - I will see if kernel dev understands PR you linked.
> > > > What doesn't make sense is that it's from v0.6.6 and I'm on latest 0.7.2
> > > 
> > > 
> > > I fixed this by editing some code like
> > > ```
> > > if LINUX_VERSION_CODE < KERNEL_VERSION(4, 10, 0)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > (4, 10, 0) to (4, 15, 0) to let it work on my 4.14 kernel temporarily. You could have a try
> > > A old commit as a reference [roberto-sartori-gl@2c7cce6](https://github.com/roberto-sartori-gl/KernelSU/commit/2c7cce67cf03361c22a07f13575eece82ef47517)
> > 
> > 
> > Revisiting this issue to try and fix - did you try this PR on Samsung devices to confirm if KSU can access .allowlist file with encrypted device?
> 
> I don't have Samsung device. So I don't know.

It works on your device with some sort of encryption enabled tho?

**Comment by Sinclair19** [comment]
> > > > > > If you read the issue carefully, you won't ask this.
> > > > > 
> > > > > 
> > > > > Sorry I did not translate all posts - I will see if kernel dev understands PR you linked.
> > > > > What doesn't make sense is that it's from v0.6.6 and I'm on latest 0.7.2
> > > > 
> > > > 
> > > > I fixed this by editing some code like
> > > > ```
> > > > if LINUX_VERSION_CODE < KERNEL_VERSION(4, 10, 0)
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > (4, 10, 0) to (4, 15, 0) to let it work on my 4.14 kernel temporarily. You could have a try
> > > > A old commit as a reference [roberto-sartori-gl@2c7cce6](https://github.com/roberto-sartori-gl/KernelSU/commit/2c7cce67cf03361c22a07f13575eece82ef47517)
> > > 
> > > 
> > > Revisiting this issue to try and fix - did you try this PR on Samsung devices to confirm if KSU can access .allowlist file with encrypted device?
> > 
> > 
> > I don't have Samsung device. So I don't know.
> 
> It works on your device with some sort of encryption enabled tho?

yes
