### ISSUE TITLE
[BUG]模块安装功能异常

### ISSUE THREAD

**Issue by natsumerinchan** [tiann/KernelSU#1252]
### Please check before submitting an issue

- [x] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

从 https://github.com/tiann/KernelSU/commit/b99701d21649b8e5885d2bc7a63bdd41b501ecdb 这个提交开始我的设备无法再安装任何模块，会显示"Error: Failed to extract assets"

### To Reproduce

1、安装 https://github.com/tiann/KernelSU/commit/b99701d21649b8e5885d2bc7a63bdd41b501ecdb 这个提交以后的管理器
2、进入模块页面
3、安装任意模块

### Expected behavior

能正常安装模块

### Screenshots

![photo_2024-01-05_20-25-27](https://github.com/tiann/KernelSU/assets/64072399/fc1d7896-29dc-46fa-af43-c722b6a350bf)

### Logs

[KernelSU_bugreport_2024-01-05_20_17.tar.gz](https://github.com/tiann/KernelSU/files/13842018/KernelSU_bugreport_2024-01-05_20_17.tar.gz)

### Device info

- Device:Oneplus 9RT(martini)
- OS Version:PixelExperience (Android 13)
- KernelSU Version: KernelSpace(11423) + UserSpace(11425)
- Kernel Version:5.4.256

**Comment by 5ec1cff** [comment]
用 cli 能复现问题吗

**Comment by 5ec1cff** [comment]
检查一下你的系统中是否有持续运行的 busybox （比如某些模块）

**Comment by tiann** [comment]
试一下这个：https://github.com/tiann/KernelSU/actions/runs/7422996484

**Comment by natsumerinchan** [comment]
> 用 cli 安装能复现问题吗
> 
> ```
> ksud module install <module zip>
> ```

cli安装也报一样的错



> 试一下这个：https://github.com/tiann/KernelSU/actions/runs/7422996484

现在可以用了

**Comment by 5ec1cff** [comment]
https://github.com/tiann/KernelSU/pull/1253
