### ISSUE TITLE
无法使用太极 阳

### ISSUE THREAD

**Issue by weizili25830** [tiann/KernelSU#126]
我安装了太极，然后安装了太极模块zygsic版本后，可以正常开机，但是太极里面还显示太极阴，使用magisk模块后，重启卡米标接近十分钟，我强制关机，然后开机，仍然无法使用太极阳仍然显示太极阴且magisk版本太极为灰色开启状态无法调节
我卸载了所有模块和太极阴，直接安装太极zygsic版本提示需要先安装太极，安装之后模块在管理器中消失，太极仍旧显示阴，magisk版本也是一样
【超级会员V5】通过百度网盘分享的文件：qqqqq
链接:https://pan.baidu.com/s/1sujcCPXVu0MwKIH563KaXw?pwd=095z 
提取码:095z
复制这段内容打开「百度网盘APP 即可获取」
I installed Tai Chi, and then installed the zygsic version of the Tai Chi module, which can be started normally. However, Tai Chi Yin is also displayed in Tai Chi. After using the magisk module, restart the Kami sign for nearly ten minutes. I forced to shut down, and then start up, still unable to use Tai Chi Yang, which still displays Tai Chi Yin, and the magisk version of Tai Chi is gray and cannot be adjusted
I uninstalled all modules and Taiji Yin, and directly installed the Taiji zygsic version, which prompted that Taiji needs to be installed first. After installation, the module disappears in the manager, and Taiji still displays Yin, and so does the magisk version

**Comment by Ylarod** [comment]
请提供相关日志和设备信息

**Comment by Dreamail** [comment]
magisk开启zygisk并且在magisk刷的太极阳么

**Comment by Dreamail** [comment]
kernelsu不支持zygisk如需注入zygote请使用riru for kernelsu或改用magisk

**Comment by tiann** [comment]
[taichi_v7.0.6.zip](https://github.com/tiann/KernelSU/files/10519284/taichi_v7.0.6.zip)
