### ISSUE TITLE
模块安装异常

### ISSUE THREAD

**Issue by iceBear67** [tiann/KernelSU#1265]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

表现为模块管理界面内无法操作模块。

![image](https://github.com/tiann/KernelSU/assets/48877375/5c806e2a-514a-4673-b827-d432b4c711ec)

然而 json 内指示这些模块都是开着的

![image](https://github.com/tiann/KernelSU/assets/48877375/14a03e4e-6456-4fa2-80f4-d160ba342f1d)

但是模块目录内实际上为空，安装模块的时候也没有提示错误
![image](https://github.com/tiann/KernelSU/assets/48877375/9af2ebc3-6b04-4e16-b742-d9212970cc4b)

### Expected behavior

模块正常运行

### Screenshots

![image](https://github.com/tiann/KernelSU/assets/48877375/5c806e2a-514a-4673-b827-d432b4c711ec)

### Logs

[KernelSU_bugreport_2024-01-07_17_05.tar.gz](https://github.com/tiann/KernelSU/files/13852767/KernelSU_bugreport_2024-01-07_17_05.tar.gz) 这是安装了 ZygiskNext 后重启得到的 log

[KernelSU_bugreport_2024-01-07_17_07.tar.gz](https://github.com/tiann/KernelSU/files/13852768/KernelSU_bugreport_2024-01-07_17_07.tar.gz) 这是安装 safetynetfix 后直接得到的 log

### Device info

- Device: Galaxy Note 9 (N960N/Exynos 9810)
- OS Version: Android 10
- KernelSU Version: 11443, 上一个版本也有这个问题
- Kernel Version: 4.9.321

### Additional context

SELinux enforcing + neverallow

使用了自编译内核+修改源码支持KSU方案:  https://github.com/iceBear67/android_kernel_exynos9810_kernelsu  
~~(第一次搞 乱七八糟)~~

之前在系统上使用过 Magisk Alpha, 但是现在已经卸载掉了（不过这个ROM之前是内置magisk的，不知道会不会干扰）

**Comment by iceBear67** [comment]
另外，卸载也有问题（
我在 /data/adb/module 内手动删才删掉

**Comment by iceBear67** [comment]
[boot.log](https://github.com/tiann/KernelSU/files/13852871/boot.log)

补充 boot.log
压缩包内的是空的

**Comment by wxt1221** [comment]
cli能否使用？

**Comment by iceBear67** [comment]
在群里大佬的协助下完成了修复（

解决方案是合并了 https://github.com/sticpaper/android_kernel_xiaomi_msm8998-ksu/commit/646d0c836053ffa8743519c39fcabaecb258f00b

https://github.com/sticpaper/android_kernel_xiaomi_msm8998-ksu/commit/646d0c836053ffa8743519c39fcabaecb258f00b#diff-798a64f5b6674cae172dc9699756a73dc22ee04529390eed34f6acf3c5453c08 也是

可能其他老内核（4.9）也有这种情况，可以贴 warning 里面看看？

**Comment by wxt1221** [comment]
https://github.com/tiann/KernelSU/discussions/955

参考这个 @iceBear67
