### ISSUE TITLE
Start crash on coloros dev.

### ISSUE THREAD

**Issue by lshilshi** [tiann/KernelSU#1275]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Env: oneplus ACE2, coloros 13, Android 12
kernel: AnyKernel3-android12-5.10.149

Frome ver 0.7.2
It's crash when start kernelsu app.

Clear Cache & Clear Data & Reboot,
It's crash too.

### Screenshots

![微信图片_20240108104137](https://github.com/tiann/KernelSU/assets/36767310/55f0440e-3461-4218-a293-f85e61090309)

### Logs

Unknown bits set in runtime_flags:0x4000000

Not starting debugger since process cannot load the jdwp agent.

sysopen failed with error Permission denied.

sharedImFd failed with error=Permission denied.

Loaded layer handle (17757632225046506550) for layer /my product/lib64/libcolorx-loader.S0

Found Colorx_Check for /my_product/lib64/libcolorx-loader.so.

### Device info

- Device: Oneplus ACE2
- OS Version: Android 12
- KernelSU Version: 0.7.2-0.7.5
- Kernel Version: android12-5.10.149

**Comment by tiann** [comment]
please upload full logcat

**Comment by lshilshi** [comment]
> please upload full logcat

我现在不能进 KernelSU Manager.不是很好导出log.

另外：刚刚在发完issue后，我回到了0.7.1（kenel boot.img同步刷回）
进入manager还是闪退（原以为回到0.7.1应该正常的）
且因为重启的缘故，可能是权限的问题，刚刚查看log的app，并不能读取manager的log

自从kenelsu安装后
应该是没有动过系统设置的（自然更没有os升级等操作）
只是升级普通用户app

**Comment by tiann** [comment]
可以用电脑 adb 抓 log

**Comment by lshilshi** [comment]
[kernelsu.log](https://github.com/tiann/KernelSU/files/13856017/kernelsu.log)
只过滤了kenelsu的log，请查阅！

**Comment by lshilshi** [comment]
```
01-08 10:58:55.113 14075 14075 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 14075 (weishu.kernelsu), pid 14075 (weishu.kernelsu)
01-08 10:58:55.388 14160 14160 F DEBUG   : Process name is me.weishu.kernelsu, not key_process
01-08 10:58:55.388 14160 14160 F DEBUG   : keyProcess: 0
01-08 10:58:55.388 14160 14160 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
01-08 10:58:55.388 14160 14160 F DEBUG   : Build fingerprint: 'OnePlus/PHK110/OP5913L1:13/SKQ1.221012.001/T.119565e-24c-14506e:user/release-keys'
01-08 10:58:55.388 14160 14160 F DEBUG   : Revision: '0'
01-08 10:58:55.388 14160 14160 F DEBUG   : ABI: 'arm64'
01-08 10:58:55.388 14160 14160 F DEBUG   : Timestamp: 2024-01-08 10:58:55.163859406+0800
01-08 10:58:55.388 14160 14160 F DEBUG   : Process uptime: 1s
01-08 10:58:55.388 14160 14160 F DEBUG   : Cmdline: me.weishu.kernelsu
01-08 10:58:55.388 14160 14160 F DEBUG   : pid: 14075, tid: 14075, name: weishu.kernelsu  >>> me.weishu.kernelsu <<<
01-08 10:58:55.388 14160 14160 F DEBUG   : uid: 10299
01-08 10:58:55.388 14160 14160 F DEBUG   : tagged_addr_ctrl: 0000000000000001 (PR_TAGGED_ADDR_ENABLE)
01-08 10:58:55.388 14160 14160 F DEBUG   : pac_enabled_keys: 000000000000000f (PR_PAC_APIAKEY, PR_PAC_APIBKEY, PR_PAC_APDAKEY, PR_PAC_APDBKEY)
01-08 10:58:55.388 14160 14160 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0000000000000000
01-08 10:58:55.388 14160 14160 F DEBUG   : Cause: null pointer dereference
01-08 10:58:55.388 14160 14160 F DEBUG   :     x0  0c0200009b47931d  x1  0000007e0dea8d20  x2  0000007e0de00000  x3  0000000000000002
01-08 10:58:55.388 14160 14160 F DEBUG   :     x4  00000000000000a8  x5  0000000000007e7e  x6  1f646b68651f6c6e  x7  7f7f7f7f7f7f7f7f
01-08 10:58:55.388 14160 14160 F DEBUG   :     x8  308941c94aa35cf7  x9  308941c94aa35cf7  x10 00000000000000a8  x11 0000000000000001
01-08 10:58:55.388 14160 14160 F DEBUG   :     x12 0000007fee3db270  x13 0000000000000041  x14 0000007fee3dc5b8  x15 0000000050396740
01-08 10:58:55.388 14160 14160 F DEBUG   :     x16 0000007f37eb9768  x17 0000007f37eb6fb8  x18 0000007f39014000  x19 0000000000000000
01-08 10:58:55.388 14160 14160 F DEBUG   :     x20 b400007e620e4f60  x21 b400007e620e4f40  x22 b400007e620e4f40  x23 b400007e0dd8e040
01-08 10:58:55.388 14160 14160 F DEBUG   :     x24 0000007fee3dcb50  x25 b400007e621be100  x26 0000000000000000  x27 0000007f38a38000
01-08 10:58:55.388 14160 14160 F DEBUG   :     x28 0000000000000004  x29 0000007fee3dcaf0
01-08 10:58:55.388 14160 14160 F DEBUG   :     lr  0056ceff37e950f4  sp  0000007fee3dcac0  pc  0000007f37e94a18  pst 0000000060001000
```

前面log文件是I级别，查看完整的log，发现还有debug基本信息

**Comment by tiann** [comment]
不要过滤，发完整的

**Comment by lshilshi** [comment]
> 不要过滤，发完整的

[kernelsu-full.log](https://github.com/tiann/KernelSU/files/13856536/kernelsu-full.log)
已发，请查收！

**Comment by tiann** [comment]
你装了字体模块吗？

**Comment by lshilshi** [comment]
> 你装了字体模块吗？

是的，有字体模块.

**Comment by lshilshi** [comment]
> 你装了字体模块吗？

但是此前正常啊。

**Comment by tiann** [comment]
你把字体模块删掉看看是否恢复正常？

**Comment by lshilshi** [comment]
> 你把字体模块删掉看看是否恢复正常？

测试，正常，谢谢！

但是在升级0.7.2之前
我启用了字体模块，关闭/重启/再打开，都是正常，manager不会闪退的

请问，现在还能顺利启用字体模块吗？
之前看到好像要刷overlay fs模块，但是能正常用，能少个模块就少个模块啊

**Comment by tiann** [comment]
你是不是改了设置里面的“默认卸载模块”这个设置？或者你装了其他的模块启用了卸载，但没有针对管理器跳过。

**Comment by lshilshi** [comment]
> 你是不是改了设置里面的“默认卸载模块”这个设置？或者你装了其他的模块启用了卸载，但没有针对管理器跳过。

“默认卸载模块”这个设置默认值是 “启用”的吧？
应该没有装了其他的模块启用了卸载
从0.71-0.72/0.75的过程中
变化就是升级了zygisknext & shamiko 模块，无其它对system分区和核心的变动

ps：怎么针对管理器跳过？

**Comment by tiann** [comment]
如果你用字体模块，建议关闭默认卸载
