### ISSUE TITLE
KernelSU APK in  aosp build

### ISSUE THREAD

**Issue by rdkartono** [tiann/KernelSU#1292]
I played with KernelSU and patched kernel 5.15 succesfully.
Then I installed KernelSU apk using adb install, and it  showed "Working" Status.

However if I want to include the same APK in my AOSP build, the icon showed in drawer, but when opened, it showed "Not installed" status. Clicking the status, will open web browser for KernelSU URL.

My Android.mk is like below, please give suggestion if anything wrong.
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE_TAGS := optional
LOCAL_MODULE := KernelSU
LOCAL_SRC_FILES := KernelSU.apk
LOCAL_MODULE_CLASS := APPS
#LOCAL_CERTIFICATE := PRESIGNED
LOCAL_CERTIFICATE := platform
LOCAL_PRIVILEGED_MODULE := true
# LOCAL_MODULE_PATH := $(TARGET_OUT_DATA)
# LOCAL_OVERRIDES_PACKAGES := Home Launcher2  Launcher3

LOCAL_MODULE_SUFFIX :=  $(COMMON_ANDROID_PACKAGE_SUFFIX)

include $(BUILD_PREBUILT)

**Comment by tiann** [comment]
https://github.com/tiann/KernelSU/issues/559#issuecomment-1588546964
