### ISSUE TITLE
[Feature Request]: Adding the option to specify enabled applications/processes for each module

### ISSUE THREAD

**Issue by Nobooooody** [tiann/KernelSU#1295]
### Is your feature request related to a problem? Please describe.

Currently, we have four modules (module names: a, b, c, d) and four applications/processes (application names: A, B, C, D). I would like to have the ability to enable module x only in application/process X, to prevent the impact of certain larger-scoped modules on other dedicated modules, causing conflicts and failures.

当前，我们有四个模块（模块名称：a、b、c、d）和四个应用程序/进程（应用程序名称：A、B、C、D）。我希望能够让模块x只在应用程序/进程X中启用，以防止某些功能范围较大的模块影响到其他专用模块而导致冲突失效。

### Describe the solution you'd like.

I would like to propose adding a feature to Kernelsu that allows specifying the enabled applications or processes for each module. 

我希望在Kernelsu中添加一个功能，以便能够为每个模块指定启用的应用程序或进程。

### Describe alternatives you've considered.

‭

### Additional context

Thank you very much for considering this feature request! I hope this suggestion is helpful to you. 🙂

非常感谢您考虑这个功能请求！希望这个建议能对您有所帮助。🙂

**Comment by Nobooooody** [comment]
This feature maybe look like lsposed.module scope

**Comment by tiann** [comment]
有 root 权限的模块可以轻易实施全局影响，比如修改属性，直接注入 zygote 等，因此你所描述的无法实现。

**Comment by Nobooooody** [comment]
> This feature maybe looks like lsposed module scope.

What I mean is to unmount modules.

I know that undoing the global impact of injecting into zygote/resetprop is impossible. It is definitely not possible to achieve those functionalities.

**Comment by tiann** [comment]
#759
