### ISSUE TITLE
[BUG] mount failed: invalid argument

### ISSUE THREAD

**Issue by Ani4k** [tiann/KernelSU#1296]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

I recently compiled paranoid with kernelSU. 
and i installed KSU.apk and its says working.
but when i go module tab and try to install any module it gives me an error called 
"Mount failed: Invalid argument (os error 21), retry with system mount"
and it happens with every module I install.
can't even get log.

device = oneplus9/lemonade
kernel version = 5.4.242
OS = paranoid uvite
android version = 14

### To Reproduce

1. clone paranoid uvite manifest
2. ./rom-builder.sh oneplus9. it will automatically download all the dependencies for the device.
3. clone kernelsu in kernel/msm-5.4
4. compile the rom using ./rom-builder.sh
5. flash it one oneplus9

### Screenshots

![Screenshot_20240117-162915](https://github.com/tiann/KernelSU/assets/22926051/b44897ef-9772-4a10-847a-40d31acee24e)
![Screenshot_20240117-170728](https://github.com/tiann/KernelSU/assets/22926051/cca0f0fd-cde8-4572-b929-496e1179e157)
![Screenshot_20240117-170805](https://github.com/tiann/KernelSU/assets/22926051/5475f24d-5ee6-4239-a7f2-a41a9176f87b)
![Screenshot_20240117-170815](https://github.com/tiann/KernelSU/assets/22926051/eb4ff945-fc3d-4914-8a03-300ab63cf58d)

### Logs

[KernelSU_install_log_2024-01-17-16-33-12.log](https://github.com/tiann/KernelSU/files/13962897/KernelSU_install_log_2024-01-17-16-33-12.log)

### Device info

- Device:oneplus9
- OS Version:A14
- KernelSU Version:11434
- Kernel Version:5.4.242

**Comment by tiann** [comment]
This isn't a bug.
