### ISSUE TITLE
[Feature] Add switch off automatically check for updates

### ISSUE THREAD

**Issue by pheotry** [tiann/KernelSU#1303]
### Is your feature request related to a problem? Please describe.

My device kernel had been stopped support.
The kernel don't update forever.
But The kernnelSU management will check for update.
I hope to add a switch to close the checking

### Describe the solution you'd like.

add a switch to close the checking for updates

### Describe alternatives you've considered.

.

**Comment by backslashxx** [comment]
would be nice for modules too, like disable module update checks.
