### ISSUE TITLE
error: undefined symbol: ksu_vfs_read_hook

### ISSUE THREAD

**Issue by ucxl** [tiann/KernelSU#1310]
ld.lld: error: undefined symbol: ksu_vfs_read_hook
>>> referenced by read_write.c:461 (../fs/read_write.c:461)
>>>               vmlinux.o:(vfs_read)
>>> referenced by read_write.c:461 (../fs/read_write.c:461)
>>>               vmlinux.o:(vfs_read)

ld.lld: error: undefined symbol: ksu_execveat_hook
>>> referenced by exec.c:1935 (../fs/exec.c:1935)
>>>               vmlinux.o:(do_execveat_common)
>>> referenced by exec.c:1935 (../fs/exec.c:1935)
>>>               vmlinux.o:(do_execveat_common)

**Comment by wxt1221** [comment]
> ld.lld: error: undefined symbol: ksu_vfs_read_hook
> 
> > > > referenced by read_write.c:461 (../fs/read_write.c:461)
> > > > vmlinux.o:(vfs_read)
> > > > referenced by read_write.c:461 (../fs/read_write.c:461)
> > > > vmlinux.o:(vfs_read)
> 
> ld.lld: error: undefined symbol: ksu_execveat_hook
> 
> > > > referenced by exec.c:1935 (../fs/exec.c:1935)
> > > > vmlinux.o:(do_execveat_common)
> > > > referenced by exec.c:1935 (../fs/exec.c:1935)
> > > > vmlinux.o:(do_execveat_common)

内核版本？手机型号？又让我猜？

**Comment by ucxl** [comment]
抱歉，手机是三星s21u国行 sm-g9980 安卓14

**Comment by ucxl** [comment]
内核版本是5.4.233

**Comment by tiann** [comment]
内核问题与 KernelSU 无关
