### ISSUE TITLE
kernelsu是否支持 ubuntu内核？

### ISSUE THREAD

**Issue by Qiaijueqing** [tiann/KernelSU#1313]
电脑平台 x86_64  我尝试了 ubuntu20.04 5.10.52内核 ubuntu22.04 5.15.131内核 ubuntu24.04 6.6.3内核 替换内核后 dmesg| grep KernelSU 没有任何记录  不支持？ 
安卓内核测试5.10 5.15 6.1 均支持可用  
构建方式：拉取内核源代码 拉取kernelsu 源代码 配置项开启kernelsu要求支持项  最后编译 替换内核 
安卓 ubuntu构建内核过程中 无任何错误提示 无任何不支持提示  内核替换运行后无任何异常问题

**Comment by tiann** [comment]
不支持 Linux PC.
