### ISSUE TITLE
[Custom] 关于img机制的一些疑惑

### ISSUE THREAD

**Issue by huajideshutiao** [tiann/KernelSU#1320]
### Describe your problem.

ksu使用modules.img来加载模块，这个img文件的大小似乎是固定的，模块超过这个大小会怎么样？有没有什么办法，或者是否可以将这个img文件改为动态大小的？

**Comment by tiann** [comment]
img 大小 = zip 解压后大小 + 256M；如果模块在安装过程中动态下载文件，会失败。

**Comment by huajideshutiao** [comment]
> img 大小 = zip 解压后大小 + 256M；如果模块在安装过程中动态下载文件，太大了会失败。

谢谢解答
