### ISSUE TITLE
Unexpected error.

### ISSUE THREAD

**Issue by sawdoctor** [tiann/KernelSU#1326]
Pretty new to this so apologise if this has been asked before. Trying to patch a kernel for the pixel fold, everything seemed to work and I get a new boot.img but I get an error which i think is related to signing. Is this an error or just a warning I can ignore ?
[sawdoctor@sawdoctor-gs726qe Untitled Folder]$ chmod +x magiskboot
[sawdoctor@sawdoctor-gs726qe Untitled Folder]$ ./magiskboot unpack boot.img
Parsing boot image: [boot.img]
HEADER_VER      [4]
KERNEL_SZ       [24954449]
RAMDISK_SZ      [0]
PAGESIZE        [4096]
CMDLINE         []
KERNEL_FMT      [lz4_legacy]
unexpected ASN.1 DER tag: expected SEQUENCE, got APPLICATION [1] (primitive)
VBMETA
[sawdoctor@sawdoctor-gs726qe Untitled Folder]$ mv -f Image kernel
[sawdoctor@sawdoctor-gs726qe Untitled Folder]$ ./magiskboot repack boot.img
Parsing boot image: [boot.img]
HEADER_VER      [4]
KERNEL_SZ       [24954449]
RAMDISK_SZ      [0]
PAGESIZE        [4096]
CMDLINE         []
KERNEL_FMT      [lz4_legacy]
unexpected ASN.1 DER tag: expected SEQUENCE, got APPLICATION [1] (primitive)
VBMETA
Repack to boot image: [new-boot.img]
HEADER_VER      [4]
KERNEL_SZ       [21199288]
RAMDISK_SZ      [0]
PAGESIZE        [4096]
CMDLINE         []
[sawdoctor@sawdoctor-gs726qe Untitled Folder]$

**Comment by tiann** [comment]
This is not an error, by the way, you should report it to Magisk

**Comment by sawdoctor** [comment]
Thanks for the reply, so the kernel patched correctly which is what I was worried about.

I've seen the bug reported by osmosis to magisk a few months ago and it's supposed to have been fixed
