### ISSUE TITLE
Unable to access app data

### ISSUE THREAD

**Issue by androidacy-user** [tiann/KernelSU#1327]
### Describe your problem.

Hi!

We're not really sure if this is a bug or intended behavior, but with KernelSU on WSA app data directories return "Permission denied" whereas Magisk has no such issue. 

What we've tried:
- Switching namespace to global
- Adding "app" to the user groups

Is this intended behavior, a setting we need to change, or a bug? If it's a bug, what information should I provide?

**Comment by tiann** [comment]
Maybe it is a bug, you can use adb shell and execute `su -mm`, then `ls -al /data/data`, can you see any data?

**Comment by tiann** [comment]
And also, which app do you test?
