### ISSUE TITLE
Payback app detects root

### ISSUE THREAD

**Issue by meiser79** [tiann/KernelSU#1328]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

The [Payback](https://play.google.com/store/apps/details?id=de.payback.client.android) app version 24.01.1800 detects root and just a message about an insecure environment.

May I ask you to have a look how it does the detection? Uninstalling the manager app or clearing app data/cache do not solve the issue.

Thanks a lot,
meiser

### To Reproduce

1. Install the app
2. See the message about insecure environment

### Device info

- Device: Poco F3
- OS Version: crDroid 9.13
- KernelSU Version: 0.7.6 (11461), manager app 0.7.6 (11458)
- Kernel Version: 4.19.305, [InfiniR alioth](https://github.com/raystef66/InfiniR_kernel_alioth) with modules umount patch by wx1221

**Comment by tiann** [comment]
Uninstall all modules and try again.

**Comment by meiser79** [comment]
Still the same. I disabled the modules instead of uninstalling, but this should be the same, right?

**Comment by pckotzer** [comment]
Did yout tried it without kernelSU? It may be a Rom problem

**Comment by meiser79** [comment]
It's not custom ROM related as it works with previous Payback version 23.11.1403. Just the update to version 24.01.1800  triggers the root detection.

**Comment by pckotzer** [comment]
Did you tryed stock kernel. If you compile kernel by yourself try without localversion in defconfig 
Google ban now various kernel names including crdroid in kernel name or other popular kernel names line lineageos or whatever is used. What does your localversion show?

**Comment by meiser79** [comment]
Am I right that any app can find KernelSU by just checking "mount". There are KSU mount names. Any chance to rename these ones?

**Comment by pckotzer** [comment]
Try do do backup of data and then do clean install without a kernelsu kernel to be 100% sure

**Comment by meiser79** [comment]
If I fully remove kernelsu, the app works fine.

**Comment by pckotzer** [comment]
Another kernel?

**Comment by meiser79** [comment]
What do you mean? I recompiled the kernel tree without kernelsu. With this kernel, the app starts fine.

**Comment by meiser79** [comment]
@tiann even if I uninstall all modules by renaming the modules.img, the app detects root. So it's not the mountpoint, right?

**Comment by pckotzer** [comment]
Perfect, thats what i wanted to hear xd

**Comment by goldwoods2005** [comment]
Same as the bank app Vietbank
https://play.google.com/store/apps/details?id=com.vnpay.vietbank

Ksu with no module install, lastest version of the app find root
Change the kernel without ksu, app start normally
Still not find a way to bypass this app

**Comment by YlarodAli** [comment]
Problem located, will fix soon

**Comment by ToucH9000** [comment]
> Same as the bank app Vietbank https://play.google.com/store/apps/details?id=com.vnpay.vietbank
> 
> Ksu with no module install, lastest version of the app find root Change the kernel without ksu, app start normally Still not find a way to bypass this app

same here

**Comment by meiser79** [comment]
Thanks so much! I really appreciate your work! I verified that it works with this commit.

**Comment by Niemandausduisburg** [comment]
@meiser79 How you get latest Payback working? I picked this commit and it doesn't work for me. Only downgrade Payback seems to be help.

**Comment by meiser79** [comment]
@Niemandausduisburg You have to either freeze the manager app with e.g. [Ice Box](https://play.google.com/store/apps/details?id=com.catchingnow.icebox) or deinstall it.

**Comment by Niemandausduisburg** [comment]
@meiser79 Don't work for me

**Comment by meiser79** [comment]
You might be right, I just got a broken Payback app again.
It seems that KernelSU_v0.7.6-55-g20c19d7_11513-release.apk broke it again, but KernelSU_v0.7.6-51-gabf0dac_11509-release.apk works fine.

Which version do you run exactly (kernel and app)?

**Comment by Niemandausduisburg** [comment]
![Screenshot_20240219-064049_KernelSU](https://github.com/tiann/KernelSU/assets/76850396/d746890f-1c13-4810-aadf-012ab6601de3)

**Comment by meiser79** [comment]
@tiann kernelsu v0.8.0 (kernel and app at 11551) breaks the Payback app again. May I ask you to have a look again? Thanks a lot!

**Comment by sd535682** [comment]
> @meiser79 The issue isn't KernelSU.
> Payback is looking if you have unlocked your bootloader (custom ROM).

I guess no. I was using the def KSU kernel on my device. After flashing any module the Yono app crashes. If there was an issue with unlocked BL it would have been detected earlier.

**Comment by sd535682** [comment]
> You might be right, I just got a broken Payback app again.
> It seems that KernelSU_v0.7.6-55-g20c19d7_11513-release.apk broke it again, but KernelSU_v0.7.6-51-gabf0dac_11509-release.apk works fine.
> 
> Which version do you run exactly (kernel and app)?

have you tried Shamiko?

**Comment by hummermann87** [comment]
> > You might be right, I just got a broken Payback app again.
> > It seems that KernelSU_v0.7.6-55-g20c19d7_11513-release.apk broke it again, but KernelSU_v0.7.6-51-gabf0dac_11509-release.apk works fine.
> > Which version do you run exactly (kernel and app)?
> 
> have you tried Shamiko?

Shamiko user here, doesn't work on LineageOS 20. :(

**Comment by hummermann87** [comment]
> > > You might be right, I just got a broken Payback app again.
> > > It seems that KernelSU_v0.7.6-55-g20c19d7_11513-release.apk broke it again, but KernelSU_v0.7.6-51-gabf0dac_11509-release.apk works fine.
> > > Which version do you run exactly (kernel and app)?
> > 
> > 
> > have you tried Shamiko?
> 
> Shamiko user here, doesn't work on LineageOS 20. :(

It finally works! I have used the module posted here: https://github.com/Magisk-Modules-Alt-Repo/ezme-nodebug/issues/1

**Comment by meiser79** [comment]
Latest Payback app (version 24.04.2501) detects root running KernelSU version 11848.

**Comment by Niemandausduisburg** [comment]
> Latest Payback app (version 24.04.2501) detects root running KernelSU version 11848.
> 
> Payback app version [24.04.1101](https://apkpure.com/de/payback-karte-und-coupons/de.payback.client.android/download/24.04.1101) is the latest working version.

I have the same issue. Payback was working fine before update playcurl

**Comment by meiser79** [comment]
Got it working by using a different app to freeze/hide the manager app.

**Comment by Niemandausduisburg** [comment]
> Got it working by using a different app to freeze/hide the manager app.

Which app do you use to hide/freeze the manager?
I tried Icebox without any luck

**Comment by sevbest** [comment]
> Got it working by using a different app to freeze/hide the manager app.

@meiser79 if you dont mind, which app did you use to hide kernelsu ?

**Comment by meiser79** [comment]
@sevbest If I mentioned it here, it would maybe stop working soon. Sorry!

**Comment by sevbest** [comment]
I found one that works !

**Comment by Niemandausduisburg** [comment]
@sevbest Which app did you found for hide KernelSU?

**Comment by justinh998** [comment]
> > > > You might be right, I just got a broken Payback app again.
> > > > It seems that KernelSU_v0.7.6-55-g20c19d7_11513-release.apk broke it again, but KernelSU_v0.7.6-51-gabf0dac_11509-release.apk works fine.
> > > > Which version do you run exactly (kernel and app)?
> > > 
> > > 
> > > have you tried Shamiko?
> > 
> > Shamiko user here, doesn't work on LineageOS 20. :(
> 
> It finally works! I have used the module posted here: https://github.com/Magisk-Modules-Alt-Repo/ezme-nodebug/issues/1 

Does it still work for you ? I flashed the zip in your Linked therd in kernelsu and payback still doesnt work.

**Comment by Niemandausduisburg** [comment]
@justinh998 Payback still broken for me. 
I tried many things to get it working. 
All other apps are working fine.

**Comment by pckotzer** [comment]
@Niemandausduisburg did you tried to delete the KernelSU app and then try again?

**Comment by Niemandausduisburg** [comment]
@pckotzer Yes Payback is still crashing for me

**Comment by NCLnclNCL** [comment]
[reset-los-props.zip](https://github.com/user-attachments/files/16622491/reset-los-props.zip)
Use this to hide LOS

**Comment by Niemandausduisburg** [comment]
> [reset-los-props.zip](https://github.com/user-attachments/files/16622491/reset-los-props.zip) Use this to hide LOS

Don't work for me on latest VoltageOS

**Comment by pckotzer** [comment]
> > [reset-los-props.zip](https://github.com/user-attachments/files/16622491/reset-los-props.zip) Use this to hide LOS
> 
> Don't work for me on latest VoltageOS

Work here on ProjectEverest, remove the kernelsu app

**Comment by Niemandausduisburg** [comment]
> > > [reset-los-props.zip](https://github.com/user-attachments/files/16622491/reset-los-props.zip) Use this to hide LOS
> > 
> > 
> > Don't work for me on latest VoltageOS
> 
> Work here on ProjectEverest, remove the kernelsu app

Already tried without any luck :-(

**Comment by pckotzer** [comment]
> > > > [reset-los-props.zip](https://github.com/user-attachments/files/16622491/reset-los-props.zip) Use this to hide LOS
> > > 
> > > 
> > > Don't work for me on latest VoltageOS
> > 
> > 
> > Work here on ProjectEverest, remove the kernelsu app
> 
> Already tried without any luck :-(

Cant be, remove app that has something to do with root, i can use it with basic attestation

**Comment by Niemandausduisburg** [comment]
> > > > > [reset-los-props.zip](https://github.com/user-attachments/files/16622491/reset-los-props.zip) Use this to hide LOS
> > > > 
> > > > 
> > > > Don't work for me on latest VoltageOS
> > > 
> > > 
> > > Work here on ProjectEverest, remove the kernelsu app
> > 
> > 
> > Already tried without any luck :-(
> 
> Cant be, remove app that has something to do with root, i can use it with basic attestation

KSU manager is removed. All apps are working fine. Only Payback is crashing.

**Comment by pckotzer** [comment]
U use latest kernelsu in kernel? Is it gki?

**Comment by Niemandausduisburg** [comment]
> U use latest kernelsu in kernel? Is it gki?

Sadly no. Kernel is 4.19

**Comment by Niemandausduisburg** [comment]
> Then just use magisk, hide in magisk delete magisk app and done. Also remove kernelsu from kernel

It's working now after change ROM and switch to Magisk 😂

**Comment by pckotzer** [comment]
KernelSU break also here on GKI, it detects root, also without the app.
