### ISSUE TITLE
[bug]5.4内核system分区挂载overlayfs失败

### ISSUE THREAD

**Issue by natsumerinchan** [tiann/KernelSU#1331]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

自PR https://github.com/tiann/KernelSU/pull/1325 合并后我的设备上需要挂载system分区的模块会失效（如字体模块，nano-ndk等），但root功能正常

### To Reproduce

1.安装 PR https://github.com/tiann/KernelSU/pull/1325 以后的管理器
2.打开app
3.重启系统

### Logs

[KernelSU_bugreport_2024-02-01_21_56.tar.gz](https://github.com/tiann/KernelSU/files/14126616/KernelSU_bugreport_2024-02-01_21_56.tar.gz)

### Device info

- Device: Oneplus 9RT(martini)
- OS Version:Pixel Experience 13 (Plus edition) (Android13)
- KernelSU Version: kernelspace(11497) + userspace(11497)
- Kernel Version: 5.4.256

**Comment by natsumerinchan** [comment]
在boot.log发现的错误
```
06-29 22:49:36.104   728   728 I KernelSU: ksud::module: load /data/adb/modules/Hc_memory system.prop
06-29 22:49:36.106   728   728 I KernelSU: ksud::module: load /data/adb/modules/yc_dfps system.prop
06-29 22:49:36.109   728   728 I KernelSU: ksud::event: module: /data/adb/modules/lost+found is disabled, ignore!
06-29 22:49:36.109   728   728 I KernelSU: ksud::event: module: /data/adb/modules/systemless-hosts-KernelSU-module skip_mount exist, skip!
06-29 22:49:36.110   728   728 I KernelSU: ksud::event: module: /data/adb/modules/ssh skip_mount exist, skip!
06-29 22:49:36.110   728   728 I KernelSU: ksud::mount: mount overlay for /system
06-29 22:49:36.110   728   728 I KernelSU: ksud::mount: mount overlayfs on "/system", lowerdir=/data/adb/modules/com.aurora.services/system:/data/adb/modules/HideNavBar/system:/data/adb/modules/xmlpak/system:/data/adb/modules/NFC_Card_Emulator/system:/data/adb/modules/ViPER4Android-RE/system:/data/adb/modules/lhroot/system:/data/adb/modules/lxgwttftemplatec/system:/data/adb/modules/WorkSettingPro/system:/data/adb/modules/busybox-ndk/system:/data/adb/modules/zipsigner/system:/data/adb/modules/nano-ndk/system:/data/adb/modules/Hc_memory/system:/data/adb/modules/adb-ndk/system:/data/adb/modules/trichromelibrary-squoosh/system:/system, upperdir=None, workdir=None
06-29 22:49:36.111   728   728 W KernelSU: ksud::event: mount system failed: mount overlayfs for root failed: Invalid argument (os error 22)
06-29 22:49:36.111   728   728 W KernelSU: ksud::event: partition: odm lowerdir is empty
06-29 22:49:36.111   728   728 I KernelSU: ksud::mount: mount overlay for /product
06-29 22:49:36.111   728   728 I KernelSU: ksud::mount: mount overlayfs on "/product", lowerdir=/data/adb/modules/lxgwttftemplatec/product:/product, upperdir=None, workdir=None
06-29 22:49:36.111   728   728 W KernelSU: ksud::event: partition: oem lowerdir is empty
06-29 22:49:36.111   728   728 I KernelSU: ksud::mount: mount overlay for /vendor
06-29 22:49:36.112   728   728 I KernelSU: ksud::mount: mount overlayfs on "/vendor", lowerdir=/data/adb/modules/NFC_Card_Emulator/vendor:/data/adb/modules/ViPER4Android-RE/vendor:/vendor, upperdir=None, workdir=None
06-29 22:49:36.112   728   728 I KernelSU: ksud::mount: bind mount ./bt_firmware -> /vendor/bt_firmware
06-29 22:49:36.112   728   728 I KernelSU: ksud::mount: bind mount ./dsp -> /vendor/dsp
06-29 22:49:36.112   728   728 I KernelSU: ksud::mount: bind mount ./firmware_mnt -> /vendor/firmware_mnt
06-29 22:49:36.112   728   728 W KernelSU: ksud::event: partition: system_ext lowerdir is empty
06-29 22:49:36.112   728   728 I KernelSU: ksud::utils: safemode: false
06-29 22:49:36.112   728   728 I KernelSU: ksud::utils: kernel_safemode: false
06-29 22:49:36.112   728   728 I KernelSU: ksud::module: /data/adb/post-mount.d not exists, skip
06-29 22:49:36.113   728   728 I KernelSU: ksud::module: /data/adb/modules/lost+found is disabled, skip
```

**Comment by natsumerinchan** [comment]
> [4efc816](https://github.com/tiann/KernelSU/commit/4efc8164f1538ceee4b01341aab2a3c6299b15ec) 4EFC816系列

我把KernelSU更新到kernelspace(11508) + userspace(11503)后system分区仍然挂载overlayfs失败

[KernelSU_bugreport_2024-02-04_22_46.tar.gz](https://github.com/tiann/KernelSU/files/14157237/KernelSU_bugreport_2024-02-04_22_46.tar.gz)

**Comment by tiann** [comment]
https://github.com/tiann/KernelSU/commit/abf0dacb3628527ca3c2b636aef66e68ed52f704

**Comment by natsumerinchan** [comment]
> [abf0dac](https://github.com/tiann/KernelSU/commit/abf0dacb3628527ca3c2b636aef66e68ed52f704) ABF0DAC的

[KernelSU_bugreport_2024-02-05_20_18.tar.gz](https://github.com/tiann/KernelSU/files/14165592/KernelSU_bugreport_2024-02-05_20_18.tar.gz)

**Comment by DaniAndTheWeb** [comment]
Same issue happening on kernel 5.10.198-2023_11.

**Comment by simplerick-simplefun** [comment]
我的也挂载system失败，跟OP一个问题。刷的最新ksu android12-5.10.198

**Comment by tiann** [comment]
upload bugreport please

**Comment by natsumerinchan** [comment]
@DaniAndTheWeb @simplerick-simplefun Can you test it when it's compiled?（Need flash the kernel and install manager）

https://github.com/natsumerinchan/KernelSU/actions/runs/8128423684

**Comment by DaniAndTheWeb** [comment]
> @DaniAndTheWeb @simplerick-simplefun Can you test it after it's compiled?（Need flash the kernel and install manager）
> 
> https://github.com/natsumerinchan/KernelSU/actions/runs/8128423684

This build fixes the mount issue i was having with the /system/ partition. @tiann If a bug report of the latest stable build is still needed just let me know.

**Comment by hamjin** [comment]
Same Problem
[KernelSU_bugreport_2024-03-04_09_30.zip](https://github.com/tiann/KernelSU/files/14475949/KernelSU_bugreport_2024-03-04_09_30.zip)

**Comment by tiann** [comment]
try this one: https://github.com/tiann/KernelSU/actions/runs/8135736330

**Comment by hamjin** [comment]
> try this one: https://github.com/tiann/KernelSU/actions/runs/8135736330

This one is OK for me
release-0.8.1 reproduced the bug and found invalid argument reported by kernel
![image](https://github.com/tiann/KernelSU/assets/30927889/7b0c0cae-c713-476c-81f3-0819bab2777c)

for some argument is too long https://github.com/aosp-mirror/kernel_common/blob/android13-5.15/fs/fsopen.c#L397
