### ISSUE TITLE
Unable to disable or uninstall module

### ISSUE THREAD

**Issue by nyakze** [tiann/KernelSU#1338]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

I am unable to uninstall a module that I used to change a bootanimation.

### To Reproduce

1. Install a module Theme A13
2. Reboot
3. Try to uninstall/disable it

### Expected behavior

Module should uninstall

### Screenshots

![image](https://github.com/tiann/KernelSU/assets/10108639/1e5496e4-1071-477e-b929-ab94ed950ae0)

### Logs

[KernelSU_bugreport_2024-02-02_18_01.tar.gz](https://github.com/tiann/KernelSU/files/14141163/KernelSU_bugreport_2024-02-02_18_01.tar.gz)

### Device info

- Device: Poco F5
- OS Version: MIUI 14 (Xiaomi.eu) Android 13; HyperOS 1.0.2.0 (Xiaomi.EU) Android 14
- KernelSU Version: 11434 (0.7.6)
- Kernel Version: 5.10.206-Melt-v.2.5-ksu

### Additional context

The module in question (couldn't upload to github due to size limit): https://drive.google.com/file/d/1IBxW07PkipxsttBTYXgsQqV6G7EPAsJX/view?usp=sharing

**Comment by tiann** [comment]
Please try this CI version: https://github.com/tiann/KernelSU/actions/runs/7751385178

**Comment by tiann** [comment]
closed since no feedback

**Comment by nyakze** [comment]
> closed since no feedback

I am sorry for the late response, I would appreciate it if you are still willing to take a look into it. I have since switched to silvercore kernel 5.10.209 and kernelsu manager 0.8.1, but the issue is still there.
I wasn't able to test the version you posted unfortunately.
To clarify, in order to test the version you posted, I just have to replace the ksud in my /data/adb/? I had ksu preinstalled in the kernel.

**Comment by devnoname120** [comment]
Same issue for me but with another module.

**Comment by realravipandit** [comment]
I am also getting the issue when I installed the module advancedtexture and not able to uninstall the module

![Image](https://github.com/user-attachments/assets/718902a5-e98e-4cf0-a27d-74260786814a)

**Comment by iddo** [comment]
I'm experiencing the same issue

**Comment by 2shrestha22** [comment]
This is how you remove module manually.
```
adb shell
su
cd /data/adb/modules
ls
```

```
rm -rf EXACT_MODULE_NAME
```

reboot
