### ISSUE TITLE
KernelSU doesn't keep settings after reboot

### ISSUE THREAD

**Issue by Fede2782** [tiann/KernelSU#1346]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

KernelSU root and the entire module system work, there isn't any kind of issue in all the module part and root. However root access and app profile preferences aren't keep after reboot. Before reboot they are applied and work correctly but each reboot seems to reset preferences. 

### To Reproduce

Go in KernelSU app and root access section, grant root access to an app and reboot. Even the setting in unmount modules isn't maintained after reboot and always resets to enabled. 

### Expected behavior

Settings should be kept between reboots. 

### Logs

[KernelSU_bugreport_2024-02-04_00_31.tar.gz](https://github.com/tiann/KernelSU/files/14154535/KernelSU_bugreport_2024-02-04_00_31.tar.gz)

### Device info

- Device: Galaxy Tab S6 Lite LTE (gta4xl)
- OS Version: Android 13
- KernelSU Version: v0.7.6 
- Kernel Version: 4.14.113

### Additional context

This is the source i'm using https://github.com/Fede2782/android_kernel_samsung_gta4xl/tree/sep-14.5/ksu. I also tried applying this selinux patch https://github.com/F-19-F/android_kernel_oneplus_msm8998/commit/1042d5601a1c0db08c9a9cea89d1895e74576a27

Integration of KernelSU has been done using manual method. I've checked many times #943 before posting

**Comment by privacyguy123** [comment]
What was the fix? I see you marked this as closed.

**Comment by Fede2782** [comment]
> What was the fix? I see you marked this as closed.

My Kernel 4.14 didn't have all required init_keyring things. I had to enable pre-4.10 support on KernelSU during build. Another way could have been to upgrade kernel to latest 4.14.338 but i didn't have time

**Comment by privacyguy123** [comment]
> > What was the fix? I see you marked this as closed.
> 
> My Kernel 4.14 didn't have all required init_keyring things. I had to enable pre-4.10 support on KernelSU during build. Another way could have been to upgrade kernel to latest 4.14.338 but i didn't have time

I found this issue on 4.19 Samsung device ... which commits am I missing? 😕

**Comment by Fede2782** [comment]
> > > What was the fix? I see you marked this as closed.
> > 
> > 
> > My Kernel 4.14 didn't have all required init_keyring things. I had to enable pre-4.10 support on KernelSU during build. Another way could have been to upgrade kernel to latest 4.14.338 but i didn't have time
> 
> I found this issue on 4.19 Samsung device ... which commits am I missing? 😕

Which is your device? In any case with Samsung if you plan to use that kernel with One UI use this patch during KernelSU building, adapt to 4.20 where is 4.15

https://github.com/Fede2782/android_kernel_samsung_gta4xl/blob/sep-14.5/ksu/0001-Enable-pre-4.10-init-keyring-also-on-4.14.patch

If you plan to use with AOSP you need to backport and (painfully) update to keep track of AOSP kernel
