### ISSUE TITLE
Zips with customized backends don't flash correctly

### ISSUE THREAD

**Issue by osm0sis** [tiann/KernelSU#1348]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Official Magisk only replaces the zip backend scripts when a module is doing an auto-update through the app, so all manually flashed (in the app) zips rely on their own backend if they have one. This allows things like TWRP A/B Installer zips to be flashed in the Magisk app, and is a pretty long-standing, expected behavior.

https://github.com/osm0sis/twrp_abtemplate/tree/master/META-INF/com/google/android

KernelSU seems to break with this behavior and always replaces the backend regardless of flashing method, resulting in the TWRP zips (and any others using custom backends) not doing anything when flashed.

Any way to have things more in-line with Magisk to restore more zip compatibility?

Thanks for your consideration!

### Device info

- Device: All
- OS Version: All
- KernelSU Version: All
- Kernel Version: All

**Comment by yujincheng08** [comment]
KSU does not support installing modules from TWRP. We break this intentionally. See https://kernelsu.org/guide/module.html#module-installer

**Comment by osm0sis** [comment]
This isn't about installing modules in TWRP, it's about flashing zips with a custom backend, like a TWRP A/B Installer zip.

**Comment by tiann** [comment]
What is custom backend script can do but `customize.sh` can't?

**Comment by osm0sis** [comment]
> What is custom backend script can do but `customize.sh` can't?

A valid question! The zips which work in Magisk app currently but don't in KernelSU app could indeed be updated to use customize.sh instead.

However, I was still curious if anything could be done on the KernelSU app's side, considering this is long-established behavior from the Magisk app, and there are a lot of zips out there (TWRP and otherwise) that use this behavior to be flashed in the Magisk app even though they're not an actual module.
