### ISSUE TITLE
Tracing syscalls

### ISSUE THREAD

**Issue by mrmischi3f** [tiann/KernelSU#1350]
I've recently come across this project and I read in the description of the website that having root at kernel level allows you to intercept syscalls.

I would like to know how is that possible. Is it a matter of writing a module? Or do I have to write some code and compile a kernel with some of your code modified?

**Comment by tiann** [comment]
it is still in plan...

**Comment by tiann** [comment]
Here is a good choice: https://github.com/SeeFlowerX/stackplz
