### ISSUE TITLE
给了systemui权限就会导致chrome(kiwi)浏览器网页空白

### ISSUE THREAD

**Issue by setcurl** [tiann/KernelSU#1360]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

我下在了一个short模块，该软件需要systemui拥有权限才能执行shell，可是给了systemui权限就会蹦出来一堆系统组件，导致部分浏览器访问网页空白，我重启了好几次都是空白，直到我把systemui权限取消了，浏览器就正常了....目前已知影响到的浏览器chrome,kiwi browser

### To Reproduce

这个问题应该不用上次日志了吧？...

### Expected behavior

有没有办法单独给systemui权限，而不是给一堆UID相同的软件权限？🤔

### Screenshots

...

### Logs

...

### Device info

- Device:红米k70
- OS Version:澎湃1.0.14.0
- KernelSU Version:v0.7.6
- Kernel Version:5.15.94

**Comment by tiann** [comment]
#1095
