### ISSUE TITLE
[Feature] Add ARMv7(32-bit) Support

### ISSUE THREAD

**Issue by EliezerB03** [tiann/KernelSU#1361]
### Is your feature request related to a problem? Please describe.

Add 32-bit support to KernelSU Manager in future versions if is possible, please 

### Describe the solution you'd like.

In future versions if is possible, they can compile an APK for ARMv7 (32-bit)

### Describe alternatives you've considered.

the only considerable alternative is magisk, and unfortunately magisk degrades performance on some phones, and root hiding is not as effective as kernelsu

**Comment by tiann** [comment]
#1193

**Comment by EliezerB03** [comment]
understood, thanks @tiann :)
