### ISSUE TITLE
[Feature] Unshallow the repo in Makefile

### ISSUE THREAD

**Issue by hmtheboy154** [tiann/KernelSU#1365]
### Is your feature request related to a problem? Please describe.

Recently we start to build BlissOS on Jenkins, some users report that KernelSU version is old even though I just updated it. When checking I realized that the repo is a shallow clone, which only contain HEAD commit, ended up making version number 10000 + 1 + 200 = 10201

### Describe the solution you'd like.

Check if the repo is shallow clone with `git rev-parse --is-shallow-repository` and then `git fetch --unshallow` directly in the Makefile.

### Describe alternatives you've considered.

None so far

**Comment by Fede2782** [comment]
+1 I can confirm i have this issue also on my builds.
