### ISSUE TITLE
[Feature] 可以在需要时调整镜像大小以节省空间

### ISSUE THREAD

**Issue by DemonPlayer0** [tiann/KernelSU#1367]
### Is your feature request related to a problem? Please describe.

**KernalSU**的overlayfs镜像文件似乎不会自动缩小，在刷入比较大型的模块（如**MIUI ODEX**）时，卸载后容易空出过大的空间而无法使用。
![Screenshot_2024-02-19-07-42-55-852_bin mt plus](https://github.com/tiann/KernelSU/assets/152860010/253c05fe-575a-4a27-92c6-ec464e6769ef)
![Screenshot_2024-02-19-07-43-12-120_bin mt plus](https://github.com/tiann/KernelSU/assets/152860010/9b39f281-ec83-4e28-9eab-872ae7a31d4b)

### Describe the solution you'd like.

能够在需要时调整**overlayfs**镜像大小。

### Describe alternatives you've considered.

可以尝试以下规则来规定镜像大小：
1.如果存储模块所需的镜像大小超过当前镜像文件所能容纳的大小，则将镜像文件的大小扩展为存储模块所需大小的125%。
2.如果存储模块所需的镜像大小小于当前镜像文件所能容纳的大小的50%，则将镜像文件的大小缩小为存储模块所需大小的125%。
3.扩展镜像使用**resize2fs**或类似工具，缩小镜像使用重构方式。

**Comment by tiann** [comment]
你说的这个方法，就是之前的实现方式。问题是，你不知道“存储模块所需大小”是多少，有的模块会带zip 自解压，有的模块还会去网络上下载。

**Comment by tiann** [comment]
为什么你这个会显示 2.65G？mt 管理器支持显示文件实际大小了？

**Comment by DemonPlayer0** [comment]
经过测试，在安装模块并重启后，**modules.img**缩小至正常状态。因为在安装过程中，**KernelSU**计算了镜像文件的大小，然后重建镜像文件到**modules_update.img**。
要解决镜像文件不会自动缩小的问题，可以在卸载模块后检查镜像的可用空间。如果可用空间过多（例如空余超过50%），则重建镜像文件。

**Comment by DemonPlayer0** [comment]
mt管理器显示的大小是**modules.img**镜像文件的大小。

**Comment by tiann** [comment]
哦，你用的不是最新的ci，我们是鸡同鸭讲
