### ISSUE TITLE
iQOO设备无法刷入ksu

### ISSUE THREAD

**Issue by ItosEO** [tiann/KernelSU#1368]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

iQOO设备无法输入ak3
直接没刷进去
仅0.7.6存在此问题
0.7.5正常，但是刷入后会导致magisk无法使用超级用户功能（掉root，但是模块正常）
经测试此提交https://github.com/tiann/KernelSU/commit/e934bfb64850ef1584d7920eab3dbf53507b3bd8可以正常使用，希望后续版本可以加入此提交修改的selinux内容，谢谢

### Expected behavior

iQOO设备无法输入ak3
直接没刷进去
仅0.7.6存在此问题
0.7.5正常，但是刷入后会导致magisk无法使用超级用户功能（掉root，但是模块正常）
经测试此提交https://github.com/tiann/KernelSU/commit/e934bfb64850ef1584d7920eab3dbf53507b3bd8可以正常使用，希望后续版本可以加入此提交修改的selinux内容，谢谢

### Logs

由于无法刷入，所以没有日志

### Device info

- Device: iQOO 9
- OS Version: Android 13
- KernelSU Version: 0.7.5(0.7.6刷不进去)
- Kernel Version: 5.10.177

**Comment by tiann** [comment]
这个提交不是本来就在 0.7.6 里面吗

**Comment by ItosEO** [comment]
> 这个提交不是本来就在 0.7.6 里面吗

我找了3个人测试，076都刷不进去，075或者那个提交就行可以，不过075掉root

**Comment by ItosEO** [comment]
> 啥叫没刷进去，bootloop吗，你的意思是把那个提交backport过来然后不能用还是用那个提交的源码
> 
> 你把[5b920f8](https://github.com/tiann/KernelSU/commit/5b920f8230ecd56c8a380d83dbc4dd18f84cfa1c) revert掉看看
> 
> @ItosEO

意思是 kernel flash刷ak3，没输出
FKM刷有输出
重启后校验boot分区hash没有变化

**Comment by ItosEO** [comment]
> > 啥叫没刷进去，bootloop吗，你的意思是把那个提交backport过来然后不能用还是用那个提交的源码
> > 你把[5b920f8](https://github.com/tiann/KernelSU/commit/5b920f8230ecd56c8a380d83dbc4dd18f84cfa1c) revert掉看看
> > @ItosEO
> 
> 意思是 kernel flash刷ak3，没输出 FKM刷有输出 重启后校验boot分区hash没有变化



> 并不认为与KSU相关，你可以尝试一下把能正常刷入的AK3包中的Image替换为0.7.6的Image。
> 
> @ItosEO

好的，我尝试一下

**Comment by ItosEO** [comment]
> 并不认为与KSU相关，你可以尝试一下把能正常刷入的AK3包中的Image替换为0.7.6的Image。
> 
> @ItosEO

你说对了，确实与ksu无关，替换Image后依然正常使用，难道是刷入脚本的问题？

**Comment by ItosEO** [comment]
所以，这究竟是为什么呢 @tiann

**Comment by ItosEO** [comment]
> 不是说刷入脚本的问题吗

下版本考虑修复？

**Comment by tiann** [comment]
我拿什么修复，算命吗？

**Comment by ItosEO** [comment]
> 我拿什么修复，算命吗？

那我以后还是通过替换Image刷入吧
