### ISSUE TITLE
[Feature] Add randomized package name for KSU Manager

### ISSUE THREAD

**Issue by nya1998** [tiann/KernelSU#1370]
### Is your feature request related to a problem? Please describe.

Recently, my mobile banking apps push an update. Since the update, the mobile banking apps check is KernelSU Manager is installed or not. If it installed, the app will refuse to be used and exit immediately.

### Describe the solution you'd like.

Just add randomized package name feature like Magisk, maybe it will resolve the issue

### Describe alternatives you've considered.

None

**Comment by TinyHai** [comment]
just uninstall ksu manager

**Comment by tiann** [comment]
https://github.com/tiann/KernelSU/issues?q=is%3Aissue+package+is%3Aclosed
