### ISSUE TITLE
4.14 内核，KernelSU 已经把自己应用设置为root ，但是执行 mount 命令失败

### ISSUE THREAD

**Issue by hjc19901119** [tiann/KernelSU#1373]
KernelSU 已经把自己应用设置为root ，但是在 app 内部执行 mount 命令时失效，是什么原因导致

**Comment by hjc19901119** [comment]
> Offer logs please.

这个日志怎么获取

**Comment by hjc19901119** [comment]
@tiann 您好，不太清楚，这个问题被关闭了的原因？

**Comment by tiann** [comment]
不按模板提交会被直接关闭。你节省的是自己的时间，浪费的是别人的时间。

**Comment by twMarriot** [comment]
> 不按模板提交会被直接关闭。你节省的是自己的时间，浪费的是别人的时间。

@tiann 非常抱歉，因为第一次提问，不太清楚提问方式。我可以参考哪个模版，我这边重新弄一下。
