### ISSUE TITLE
KernelSU 管理器应用闪退

### ISSUE THREAD

**Issue by Mooling0602** [tiann/KernelSU#1375]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

尝试打开KernelSU应用时白屏闪退，安装的模块仍能够正常工作，但是管理器打不开。
重启手机无法解决问题。
KernelSU 管理器版本：v0.7.6
机型名称：Redmi Note 11T Pro
机型代码：xaga
安卓版本：13
内核：5.10.101-android12-9-g9b99f8099824
#1 Thu Jan 18 14:29:33 UTC 2024
ROM：DerpFest
ROM版本：13-Official-Tango-xaga-20231215-1406
SELinux 状态：强制执行
如果需要更进一步操作获取更多信息以排查问题，请指示。

### Logs

暂无法抓取，需要帮助

### Device info

- Device: Redmi Note 11T Pro (xaga)
- OS Version: Android 13
- KernelSU Version: 0.7.6
- Kernel Version: android12-5.10.101_2022-05

**Comment by tiann** [comment]
删掉字体模块再试

**Comment by Mooling0602** [comment]
> 删掉字体模块再试

有用，但是我不信这个邪，然后把手机搞砖了
![Image_1707820198766](https://github.com/tiann/KernelSU/assets/147964268/b5252df9-a47a-4abd-a193-c72e6bfdd73d)
