### ISSUE TITLE
可能由新型模块镜像引起的系统损毁问题

### ISSUE THREAD

**Issue by DemonPlayer0** [tiann/KernelSU#1379]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

由KernelSU引起的重大问题。包括（但不限于）：
1.boot至system的启动阶段（手机震动后，未显示第二屏，ADB可连接）启动异常，卡第一屏。
2.在启动MT管理器的终端时zygote崩溃。

### To Reproduce

刷入并重启即可出现（或者触发创建modules.img，并重启来让KernelSU挂载modules.img）。

### Expected behavior

KernelSU应能成功走完启动流程

### Logs

[KernelSU_bugreport_2024-02-24_18_26.tar.gz](https://github.com/tiann/KernelSU/files/14392782/KernelSU_bugreport_2024-02-24_18_26.tar.gz)

### Device info

- Device:XiaoMi 12 Pro Dimensity
- OS Version:MIUI 13.0.2
- KernelSU Version:0.8.0
- Kernel Version:android12-5.10.101_2022_05

### Additional context

事件流程：
使用11458（0.7.6）版本内核作为日常使用

刷入11551版本内核镜像并重启，一切正常（暂时）
安装模块，modules_update.img在MT管理器中大小显示为1T（我的设备只有128G）。
重启，系统发生问题1。
音量键进入安全模式。成功重启，但仍发生问题1。
进入TWRP，尝试救援无效。备份数据刷机。

刷机完毕后，刷入11553（0.8.0）内核，授予MT管理器root权限后，MT管理器卡死。
反复尝试几次后，MT管理器成功启动，在启动终端后几秒内发生zygote崩溃。
zygote未自动重启，电源键强制重启后，收集日志并上传至本issue的Logs一栏。

FAQ：
1.TWRP和模块是否干扰了测试结果？
答：否。旧版本的KernelSU都是在同样的TWRP和模块环境中运行的。
2.刷机前后的KernelSU版本不一致，是否干扰实验结果？
答：否。根据TG的消息来看，最近KernelSU在忙着做webUI。
3.为何认为是模块系统出现的问题？
答：从11458至11553似乎只有模块系统和webUI进行了改变。并且在刷入11551版本内核镜像后安装模块时，KernelSU将modules.img替换为了新版。
4.能在后续提供更多信息吗？
答：能，但是我无法再次刷入KernelSU进行测试，直到问题修复。

**Comment by tiann** [comment]
你上传的日志中，KernelSU 内核版本为 11458，与描述不符。

建议你去 TWRP 中删除 modules.img 与 modules_update.img 再试。

**Comment by DemonPlayer0** [comment]
已切换到magisk。
当时分别使用了ADB和TWRP进行删除，但删除无效。文件未被移除。

**Comment by Grill-Laux** [comment]
同样遇到这个问题。
但是，从11510版本升级到11551版本同样会出现这个问题。朋友使用的11510版本的内核，升级到11551后，module.img和update_tmp每个占用都是1T，这样占用到达了2T。

**Comment by tiann** [comment]
显示 1T 并不是问题

**Comment by tiann** [comment]
文件都删不了，那是那是你其他东西有问题。
按照你们的描述，没有证据表明 KernelSU 哪里有问题。

**Comment by tiann** [comment]
如果你的日志显示都有错误，拿拿什么去查问题呢？

**Comment by powerAn2020** [comment]
我的解决方法是先刷magisk_patch的boot镜像，然后利用magisk root删除`/data/adb/ksu`目录，然后重新刷回kernelsu boot镜像，即可解决。但没找到原因。。。

**Comment by Grill-Laux** [comment]
> 我的解决方法是先刷magisk_patch的boot镜像，然后利用magisk root删除`/data/adb/ksu`目录，然后重新刷回kernelsu boot镜像，即可解决。但没找到原因。。。

咱还是老老实实更新内核吧

**Comment by powerAn2020** [comment]
> > 我的解决方法是先刷magisk_patch的boot镜像，然后利用magisk root删除`/data/adb/ksu`目录，然后重新刷回kernelsu boot镜像，即可解决。但没找到原因。。。
> 
> 咱还是老老实实更新内核吧

主要是k40 4.19的内核，我这都是每次升级都重新构建的，结果问题还存在，就只能删除重建修复了。
