### ISSUE TITLE
`/vendor/lib/modules` 文件夹被完全覆盖，而不是合并

### ISSUE THREAD

**Issue by ztc1997** [tiann/KernelSU#1380]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

我做了一个模块，想要替换 `/vendor/lib/modules` 里的两个驱动，我在`$MODDIR/vendor/lib/modules`放入了这两个文件。
![Screenshot_2024-02-25-00-50-34-154_com mixplorer silver](https://github.com/tiann/KernelSU/assets/6487102/5c2676ec-7e00-4841-bd88-b070977c0b14)
但是这么做确导致 `/vendor/lib/modules` 里只有我替换的两个文件，原来其他的文件消失了。
![Screenshot_2024-02-25-00-50-41-700_com mixplorer silver](https://github.com/tiann/KernelSU/assets/6487102/b68cb4d4-d357-4a6c-999f-627be1aad9ef)
原本的 `/vendor/lib/modules` 是这样的
![Screenshot_2024-02-25-00-47-15-187_com mixplorer silver](https://github.com/tiann/KernelSU/assets/6487102/882364fc-03ab-4784-83aa-3f029992e65b)

### Expected behavior

`/vendor/lib/modules` 里应该是模块中的两个文件被替换，其他文件被保留

### Device info

- Device: Redmi K50
- OS Version: HyperOS 1, Android 14
- KernelSU Version: 11551
- Kernel Version: 5.10.198
---
- Device: Xiaomi 12S
- OS Version: HyperOS 1, Android 14
- KernelSU Version: 11551
- Kernel Version: 5.10.198

**Comment by tiann** [comment]
上传一下日志

**Comment by ztc1997** [comment]
> 上传一下日志

[KernelSU_bugreport_2024-02-25_11_42.tar.gz](https://github.com/tiann/KernelSU/files/14395149/KernelSU_bugreport_2024-02-25_11_42.tar.gz)

**Comment by tiann** [comment]
执行一下 `ls -alRZ /data/adb/modules/ztc1997_kernel/vendor` 我看看

**Comment by ztc1997** [comment]
> 执行一下 `ls -alRZ /data/adb/modules/ztc1997_kernel/vendor` 我看看

```
/data/adb/modules/ztc1997_kernel/vendor:
total 6
drwxr-xr-x 3 root root u:object_r:system_file:s0  1024 2024-02-25 11:38 .
drwxr-xr-x 3 root root u:object_r:system_file:s0  1024 2024-02-25 11:48 ..
drwxr-xr-x 3 root root u:object_r:system_file:s0  1024 2024-02-25 11:38 lib

/data/adb/modules/ztc1997_kernel/vendor/lib:
total 6
drwxr-xr-x 3 root root u:object_r:system_file:s0  1024 2024-02-25 11:38 .
drwxr-xr-x 3 root root u:object_r:system_file:s0  1024 2024-02-25 11:38 ..
drwxr-xr-x 2 root root u:object_r:system_file:s0  1024 2024-02-25 11:38 modules

/data/adb/modules/ztc1997_kernel/vendor/lib/modules:
total 150
drwxr-xr-x 2 root root u:object_r:system_file:s0   1024 2024-02-25 11:38 .
drwxr-xr-x 3 root root u:object_r:system_file:s0   1024 2024-02-25 11:38 ..
-rw-r--r-- 1 root root u:object_r:system_file:s0  70888 2024-02-25 11:38 zram.ko
-rw-r--r-- 1 root root u:object_r:system_file:s0  75280 2024-02-25 11:38 zsmalloc.ko
```

**Comment by tiann** [comment]
你试试放在 `/system/vendor` 目录下呢？

**Comment by ztc1997** [comment]
> 你试试放在 `/system/vendor` 目录下呢？

安装的时候会被自动移到 `/vendor`，然后一样的结果。
![Screenshot_2024-02-25-13-14-04-201_me weishu kernelsu](https://github.com/tiann/KernelSU/assets/6487102/dda1d72a-1eee-47a5-a7fa-ff17a937d469)

**Comment by tiann** [comment]
```sh
lrw-r--r--  1 root root    24 2009-01-01 08:00 modules -> /vendor_dlkm/lib/modules
```

`/vendor/lib/modules` is a symlink, you should put the files to `/vendor_dlkm/lib/modules`, but KernelSU doesn't support mount `vendor_dlkm` partition now. You can manully mount it in `post-fs-data.sh`:

```
mount -t overlay KSU -o lowerdir=/data/adb/modules/test/vendor_dlkm/lib/modules/:/vendor/lib/modules /vendor/lib/modules
```
