### ISSUE TITLE
The SparseFile doesn't work correctly on 0.8.0

### ISSUE THREAD

**Issue by AMWss** [tiann/KernelSU#1381]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [x] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [x] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

It seems that the kernelsu manager incorrectly handled 'module.img' with sparse files, resulting in continuous writing of 'update_tmp.img' to storage.

### To Reproduce

1. update the manager to 0.8.0
2. do some actions with modules like install or uninstall or enable or disable
3. problem appear

### Expected behavior

I expect changing the module could work fine

### Screenshots

![IMG_20240225_012522](https://github.com/tiann/KernelSU/assets/100455586/874d1d85-88db-41a9-bdd4-e11da314c510)
It is not possible that my modules files are 66.97GB, only zygisk_next and lsposed and shamiko installed

### Logs

Sorry, currently I back to 0.7.6 and delete all the files in /data/adb

### Device info

- Device:Redmi K50 Ultra
- OS Version:Android 13
- KernelSU Version:11510
- Kernel Version:5.10.177-android12-9

### Additional context

And I think the problem probably is on the manager not the kernel.
Thx for your project!!!

**Comment by tiann** [comment]
If you can't provide logs, how can i fix it？

**Comment by AMWss** [comment]
> If you can't provide logs, how can i fix it？

Sure, plz wait for few minutes and i will provide the logs

**Comment by CJYKK** [comment]
[KernelSU_bugreport_2024-02-25_01_44.tar.gz](https://github.com/tiann/KernelSU/files/14393797/KernelSU_bugreport_2024-02-25_01_44.tar.gz)
Same question.
Redmi K40S
KernelSU Manager v0.7.6
KernelSU v0.7.6
我先把KernelSU管理器升级到了v0.8.0（但是没有升内核），然后在安装新模块的时候发现卡住不动。后退回管理器到v0.7.6，但问题依旧。

**Comment by tiann** [comment]
如果你安装新版管理器，安装模块时没有等待其结束，然后强制中断回退到旧版管理器，一定会出现致命问题。

因为旧版管理器无法处理稀疏文件，它有可能吃尽你的存储空间。

我建议你删掉 /data/adb/ksu/modules.img 和 /data/adb/ksu/modules_update.img 然后重新安装模块。否则下次开机必炸。

**Comment by CJYKK** [comment]
> 如果你安装新版管理器，安装模块时没有等待其结束，然后强制中断回退到旧版管理器，一定会出现致命问题。
> 
> 因为旧版管理器无法处理稀疏文件，它有可能吃尽你的存储空间。
> 
> 我建议你删掉 /data/adb/ksu/modules.img 和 /data/adb/ksu/modules_update.img 然后重新安装模块。否则下次开机必炸。

因为新版管理器在安装模块时未响应了，然后被系统弹窗强制终止了（
不过这只是我的问题，不一定是题主的情况，但是现在还没有发log（
总之还是谢谢大佬！

**Comment by AMWss** [comment]
> 如果你安装新版管理器，安装模块时没有等待其结束，然后强制中断回退到旧版管理器，一定会出现致命问题。
> 
> 因为旧版管理器无法处理稀疏文件，它有可能吃尽你的存储空间。
> 
> 我建议你删掉 /data/adb/ksu/modules.img 和 /data/adb/ksu/modules_update.img 然后重新安装模块。否则下次开机必炸。

刚刚升级到0.8.0没有任何降级行为进行了模块更改，然后最开始没有问题，后来出现卡顿，打开mt管理器占满内存甚至疯狂弹系统界面已停止运行，当时由于太慌了没有及时备份log而卸载kernelsu导致丢失，我再试一次吧，哭泣……
![Screenshot_2024-02-25-02-00-29-355_bin mt plus](https://github.com/tiann/KernelSU/assets/100455586/2fe7a715-cafd-4b45-8148-8898943072c0)
![Screenshot_2024-02-25-02-01-41-043_me weishu kernelsu](https://github.com/tiann/KernelSU/assets/100455586/00ee4162-efaf-4c81-96c5-c4f1c73c1b4b)

**Comment by CJYKK** [comment]
> > 如果你安装新版管理器，安装模块时没有等待其结束，然后强制中断回退到旧版管理器，一定会出现致命问题。
> > 
> > 因为旧版管理器无法处理稀疏文件，它有可能吃尽你的存储空间。
> > 
> > 我建议你删掉 /data/adb/ksu/modules.img 和 /data/adb/ksu/modules_update.img 然后重新安装模块。否则下次开机必炸。
> 
> 刚刚升级到0.8.0没有任何降级行为进行了模块更改，然后最开始没有问题，后来出现卡顿，打开mt管理器占满内存甚至疯狂弹系统界面已停止运行，当时由于太慌了没有及时备份log而卸载kernelsu导致丢失，我再试一次吧，哭泣……
> ![Screenshot_2024-02-25-02-00-29-355_bin mt plus](https://github.com/tiann/KernelSU/assets/100455586/2fe7a715-cafd-4b45-8148-8898943072c0)
> ![Screenshot_2024-02-25-02-01-41-043_me weishu kernelsu](https://github.com/tiann/KernelSU/assets/100455586/00ee4162-efaf-4c81-96c5-c4f1c73c1b4b)
> 

我是在升级后第一次装模块的时候就卡死，管理器被系统强制杀死，所以没有留下log直接就降级了…… T_T
刚救了好久的砖回来……

**Comment by Wojtaz0w** [comment]
For me the file is 1.1 TERABYTE
![Screenshot_20240225-001304_Material Files.png](https://github.com/tiann/KernelSU/assets/104674625/28d9226d-f973-47ac-ad5b-f5ccfe5905b0)

Here is bug report from KernelSU manager:
https://mega.nz/file/coERhKJS#pBzw6-o-hQr_pSq7gSQbhcW7CgZG83N4J4idmB49lh4

**Comment by tiann** [comment]
> https://www.123pan.com/s/AteyVv-f7Oyh.html

直接传到 github，你这个链接要登陆，下载还要钱

**Comment by tiann** [comment]
> For me the file is 1.1 TERABYTE ![Screenshot_20240225-001304_Material Files.png](https://private-user-images.githubusercontent.com/104674625/307556391-28d9226d-f973-47ac-ad5b-f5ccfe5905b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4MzE1MTYsIm5iZiI6MTcwODgzMTIxNiwicGF0aCI6Ii8xMDQ2NzQ2MjUvMzA3NTU2MzkxLTI4ZDkyMjZkLWY5NzMtNDdhYy1hZDViLWY1Y2NmZTU5MDViMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNVQwMzIwMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZTk4NjdhMTNiNjBlOTM2NjA3ZjBkZTFhOTMxOWZiZTllZWI1NDc2YTI0MGY1ZmQ1YWVhZTA5YTA1OTM0MTI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.96DgSPa-ecR63T19DZOddgHUSxECueLU18laU30qBq4)
> 
> Here is bug report from KernelSU manager: https://mega.nz/file/coERhKJS#pBzw6-o-hQr_pSq7gSQbhcW7CgZG83N4J4idmB49lh4

Show 1T is not a bug：https://kernelsu.org/guide/faq.html#why-is-there-a-huge-1t-file

**Comment by tiann** [comment]
> > If you can't provide logs, how can i fix it？
> 
> @tiann 我已上传KernelSU日志，从88G到92G https://www.123pan.com/s/AteyVv-f7Oyh.html 没有提取码,7天后过期，把磁盘整掉速了，哎 ![Screenshot_2024-02-25-02-49-00-035_com x1y9 probe](https://private-user-images.githubusercontent.com/100455586/307544653-14812c91-a665-4204-a20c-18e4242a6308.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4MzE1MTYsIm5iZiI6MTcwODgzMTIxNiwicGF0aCI6Ii8xMDA0NTU1ODYvMzA3NTQ0NjUzLTE0ODEyYzkxLWE2NjUtNDIwNC1hMjBjLTE4ZTQyNDJhNjMwOC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNVQwMzIwMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MzE0YTkzYTc0YzA2ZjRkMTdkNGEyMTJkNmI1NjY2NGVmZjU0MDU4OTVmNjY4YjViNGJkYTA1ZGUwN2YzOWFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7CyRuZDcn-oV3b-v8nykI_RycNjyJWbURv3YKpTbo_Q)

你说的 88G 到 92G 指的是哪个文件？能说一下你在上传这个日志之前的操作吗？

**Comment by AMWss** [comment]
> > > If you can't provide logs, how can i fix it？
> > 
> > 
> > @tiann 我已上传KernelSU日志，从88G到92G https://www.123pan.com/s/AteyVv-f7Oyh.html 没有提取码,7天后过期，把磁盘整掉速了，哎 ![Screenshot_2024-02-25-02-49-00-035_com x1y9 probe](https://private-user-images.githubusercontent.com/100455586/307544653-14812c91-a665-4204-a20c-18e4242a6308.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4MzE1MTYsIm5iZiI6MTcwODgzMTIxNiwicGF0aCI6Ii8xMDA0NTU1ODYvMzA3NTQ0NjUzLTE0ODEyYzkxLWE2NjUtNDIwNC1hMjBjLTE4ZTQyNDJhNjMwOC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNVQwMzIwMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MzE0YTkzYTc0YzA2ZjRkMTdkNGEyMTJkNmI1NjY2NGVmZjU0MDU4OTVmNjY4YjViNGJkYTA1ZGUwN2YzOWFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7CyRuZDcn-oV3b-v8nykI_RycNjyJWbURv3YKpTbo_Q)
> 
> 你说的 88G 到 92G 指的是哪个文件？能说一下你在上传这个日志之前的操作吗？

我安装了若干个模块，zygisknext和lsposed和shamiko还有另外两个正常模块，非常普通的挂载修改系统那种。
安装完成重启后进行了若干次启用，禁用，卸载，重新安装等操作，因为速度基本上是以6-10秒的时间上升0.01G占用，所以最开始我并没有意识到问题已经reproduce，而且module.img和module_update.img都没有大小变化均为1T，过了一阵子我才发现我的内置存储从88到92，但是在此期间我确保并没有任何大文件的上传或卸载，而且在我发现后，大小仍以上提到的速度爬升，后来我快速导出log就卸载了kernelsu删除了module.img和module_update.img，以及ksu文件以确保0.8.0的完全卸载……（后省略）
其中我发现问题，安装和修改模块过程有几率变长，修改sparse image的方法可能并不稳定，有时会出错，导致无限占用内存，可能是系统适配的原因，也有可能是代码逻辑的原因，这个我不是特别清除，但是有一点可以确定，随模块数量和大小的增加，以及模块修改后开机运行的时间增加（意思是修改完模块后不重启），问题有大概率甚至100%出现，具体体现为，设备已使用内存会以一定速率增加

**Comment by AMWss** [comment]
> > https://www.123pan.com/s/AteyVv-f7Oyh.html
> 
> 直接传到 github，你这个链接要登陆，下载还要钱

另外这个log有100MB以上，无法直接上传，这个网盘应该可以直接注册手机号登录就可以浏览器下载了，不需要付费，网速也还不错

**Comment by tiann** [comment]
你说的 88 -> 92 指的是你整个手机的存储？

**Comment by tiann** [comment]
看起来与这个 #1384 相同，镜像文件的 journal size 会增加，但不是无限增加的。

**Comment by AMWss** [comment]
> 你说的 88 -> 92 指的是你整个手机的存储？

没错，从88占到92，而且还在不断增加，所以我将其强行终止了，我导出log的时候是92，实际上到处完毕后又占到96了

**Comment by endolith** [comment]
The release notes say we have to install a module to fix this? Which module?

**Comment by endolith** [comment]
Is this causing general slowness of the whole phone?  It seems to have become much worse in the last few weeks.  I've never installed a module, how do I do it?  If I click **Install**, it just shows me my phone's storage, with "No items" shown.
