### ISSUE TITLE
管理器WebView控件无法访问http

### ISSUE THREAD

**Issue by heinu123** [tiann/KernelSU#1382]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

WebView从Android API28开始 默认情况下禁用明文支持，例如访问本地clash api会报错ERR_CLEARTEXT_NOT_PERMITTED

从Google上搜索的解决方法是在AndroidManifest.xml 文件的 <application> 元素中添加 android:usescleartexttraffic = "true"

### Device info

- Device: Redmi note 12T pro
- OS Version: 13
- KernelSU Version: v0.8.0(115151)
- Kernel Version: 5.10.160-android12-9-g72c3abb56738

**Comment by tiann** [comment]
这是有意为之的，但 localhost 可以访问 http；如果你确实需要 http，请说明理由。

**Comment by heinu123** [comment]
> 这是有意为之的，但 localhost 可以访问 http；如果你确实需要 http，请说明理由。

然后并不行:(
网页无法打开
位于 http://localhost:9090/ui 的网页无法加载，因为：

net::ERR_CLEARTEXT_NOT_PERMITTED

**Comment by Nep-Timeline** [comment]
> > 这是有意为之的，但 localhost 可以访问 http；如果你确实需要 http，请说明理由。
> 
> 然后并不行:( 网页无法打开 位于 http://localhost:9090/ui 的网页无法加载，因为：
> 
> net::ERR_CLEARTEXT_NOT_PERMITTED

试试使用127.0.0.1而不是localhost？

**Comment by heinu123** [comment]
> > > 这是有意为之的，但 localhost 可以访问 http；如果你确实需要 http，请说明理由。
> > 
> > 
> > 然后并不行:( 网页无法打开 位于 http://localhost:9090/ui 的网页无法加载，因为：
> > net::ERR_CLEARTEXT_NOT_PERMITTED
> 
> 试试使用127.0.0.1而不是localhost？

同样的，这是协议问题 而不是ip(

**Comment by Nep-Timeline** [comment]
> > > > 这是有意为之的，但 localhost 可以访问 http；如果你确实需要 http，请说明理由。
> > > 
> > > 
> > > 然后并不行:( 网页无法打开 位于 http://localhost:9090/ui 的网页无法加载，因为：
> > > net::ERR_CLEARTEXT_NOT_PERMITTED
> > 
> > 
> > 试试使用127.0.0.1而不是localhost？
> 
> 同样的，这是协议问题 而不是ip(

可能是networkSecurityConfig的问题(

**Comment by Nep-Timeline** [comment]
https://github.com/tiann/KernelSU/actions/runs/8027893658
下载此CI版本 0.8.0正式版没有包含 a395b10

**Comment by tiann** [comment]
有需要可以在这个文件里面添加：https://github.com/tiann/KernelSU/blob/main/manager/app/src/main/res/xml/network_security_config.xml

欢迎 PR

**Comment by tiann** [comment]
#1385
