### ISSUE TITLE
Android Emulator Support

### ISSUE THREAD

**Issue by WeeslaX** [tiann/KernelSU#1383]
### Is your feature request related to a problem? Please describe.

Lack of instructions/resources for installing KernelSU on Android Emulator.

### Describe the solution you'd like.

Instructions/Resources/Tool to use KernelSU with Android Emulator.

### Describe alternatives you've considered.

I have not considered alternatives.

### Additional context

Actually, just curious whether there will be KernelSU support on Android Emulators?

**Comment by natsumerinchan** [comment]
You can compile it yourself, if the kernel is open source.

**Comment by tiann** [comment]
Just compile the emulator kernel and it should work.

**Comment by HiHiFromMe** [comment]
how do you compile the kernel yourself for the emulator?  I can't find the boot.img for the versions of the emulator online. Do we just use a kernelSU boot.img?

**Comment by yukiQLF** [comment]
> how do you compile the kernel yourself for the emulator?  I can't find the boot.img for the versions of the emulator online. Do we just use a kernelSU boot.img?

Do you find ant info regarding this ?

**Comment by nnnphu269** [comment]
> > how do you compile the kernel yourself for the emulator?  I can't find the boot.img for the versions of the emulator online. Do we just use a kernelSU boot.img?
> 
> Do you find ant info regarding this ?

any updates? i'm new to this
