### ISSUE TITLE
`/data/adb/ksu/modules.img` 镜像文件异常占用问题

### ISSUE THREAD

**Issue by Aquarius223** [tiann/KernelSU#1384]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

`1. /data/adb/ksu/modules.img 会无休止的增加大小, 直至镜像增长至 1.1 GB`

### To Reproduce

` 1 - 随便安装任意几个模块, 我使用的是 "把机型修改为 Xiaomi Pad 6S Pro" 模块 和 “Zygisk Next 版本为 v4-0.9.2.1 (204-e2bbde1-release)” 模块, 让管理器(ksud) 创建 modules.img`
`  2 - 观察 /data/adb/ksu/modules.img 镜像的实际占用 `
`  3 - 将全部模块关闭并卸载 (即模块页面提示 “没有安装模块” ) 后 modules.img 镜像 仍在不断增大 `

`以下是我的操作命令:`
```
装模块:
sagit:/ # ls -lsh /data/adb/ksu/modules.img && sleep 120 && ls -lsh /data/adb/ksu/modules.img                                                                                                             
507M -rw------- 1 root root 1.0T 2024-02-25 16:05 /data/adb/ksu/modules.img
534M -rw------- 1 root root 1.0T 2024-02-25 16:07 /data/adb/ksu/modules.img
sagit:/ # cd /data/adb/modules                                                                                                                                                                            
sagit:/data/adb/modules # du -ach                                                                                                                                                                         
2.0K	./zygisksu/sepolicy.rule
3.0K	./zygisksu/post-fs-data.sh
77K	./zygisksu/lib/libzygisk.so
79K	./zygisksu/lib
2.0K	./zygisksu/bin/zygisk-ctl
242K	./zygisksu/bin/zygisk-ptrace64
186K	./zygisksu/bin/zygiskd32
435K	./zygisksu/bin/zygiskd64
167K	./zygisksu/bin/zygisk-ptrace32
1.0M	./zygisksu/bin
2.0K	./zygisksu/mazoku
1.0K	./zygisksu/disable
2.0K	./zygisksu/service.sh
2.0K	./zygisksu/module.prop
91K	./zygisksu/lib64/libzygisk.so
93K	./zygisksu/lib64
2.0K	./zygisksu/machikado
1.1M	./zygisksu
1.0K	./YUGE./disable
2.0K	./YUGE./system.prop
2.0K	./YUGE./module.prop
7.0K	./YUGE.
12K	./lost+found
1.2M	.
1.2M	total
sagit:/data/adb/modules # 
```

```
无模块:
# amktiao ./ls -lsh /data/adb/ksu/modules.img
 845.2M -rw-------    1 root     root        1.0T Feb 25 16:31 /data/adb/ksu/modules.img
# amktiao cd /data/adb/modules
# modules du -ach
12.0K   ./lost+found
14.0K   .
14.0K   total
# modules
```

` 截至发送 Issuse 时, modules.img 已增长至 1.02GB `

### Expected behavior

` 解决模块镜像的占用问题 `

### Logs

[(无模块)KernelSU_bugreport_2024-02-25_16_31.tar.gz](https://github.com/tiann/KernelSU/files/14395743/KernelSU_bugreport_2024-02-25_16_31.tar.gz)
[(装模块)KernelSU_bugreport_2024-02-25_16_09.tar.gz](https://github.com/tiann/KernelSU/files/14395744/KernelSU_bugreport_2024-02-25_16_09.tar.gz)

### Device info

- Device: Xiaomi MI 6
- OS Version: Lineage-21-20240208-UNOFFICIAL-sagit (Android 14)
- KernelSU Version: 11553 (管理器版本: v0.8.0 , ksud版本: ksud 0.8.0)
- Kernel Version: 4.4.302

**Comment by Aquarius223** [comment]
`  个人的后续测试: `
` 进入 REC 在终端使用 e2fsck -f modules.img 再使用 tune2fs -O ^has_journal modules.img 去除journal后开机`
`  再使用 ksud module shrink 进行 resize2fs 后 modules.img 变为 4MB 然后依然会一直增长大小, 直至镜像大小至1.1GB `

**Comment by tiann** [comment]
1.1G 包含了journal 的大小，因为你的镜像是使用旧镜像扩容得到的。旧镜像没有指定日志的大小，你可以这么做：

1. `tune2fs -O ^has_journal modules.img`, `tune2fs -j -J size=8 modules.img` 
2. 直接删掉 modules.img 重新安装模块，让 ksu 创建全新的镜像再观察。

**Comment by Aquarius223** [comment]
> 1.1G 包含了journal 的大小，因为你的镜像是使用旧镜像扩容得到的。旧镜像没有指定日志的大小，你可以这么做：
> 
> 1. `tune2fs -O ^has_journal modules.img`, `tune2fs -j -J size=8 modules.img`
> 2. 或者直接删掉 modules.img 重新安装模块，让 ksu 创建全新的镜像再观察。

我目前使用了第二种方法 rm -f modules.img && reboot 后 进行 安装模块 删除模块 卸载模块 没再出现过镜像体积增长的问题
我稍后再试一下是不是从老版本ksud升级上来导致的问题
```
1. 删除 modules.img 重启
sagit:/ # rm -f /data/adb/ksu/modules.img && reboot

2. 重启后检查 modules.img 是否存在
builder@papercom:~$ adb shell
sagit:/ $ su
sagit:/ # ls /data/adb/ksu
bin  log

3. 安装一个模块后(未重启)
sagit:/ # ls /data/adb/ksu
bin  log  modules_update.img  update

4. 等待2分钟 对比 modules_update.img 实际占用磁盘差异
sagit:/ # ls -lsh /data/adb/ksu/modules_update.img && sleep 120 && ls -lsh /data/adb/ksu/modules_update.img
6.4M -rw------- 1 root root 1.0T 2024-02-25 17:58 /data/adb/ksu/modules_update.img
6.4M -rw------- 1 root root 1.0T 2024-02-25 17:58 /data/adb/ksu/modules_update.img

5. 重启手机
sagit:/ # reboot

6. 等待2分钟  对比 modules.img 实际占用磁盘差异
builder@papercom:~$ adb shell
sagit:/ $ su
sagit:/ # ls -lsh /data/adb/ksu/modules.img && sleep 120 && ls -lsh /data/adb/ksu/modules.img
6.4M -rw------- 1 root root 1.0T 2024-02-25 18:03 /data/adb/ksu/modules.img
6.4M -rw------- 1 root root 1.0T 2024-02-25 18:03 /data/adb/ksu/modules.img

7. 再安装一个模块后 等待2分钟  对比 modules_update.img 和 modules.img 实际占用磁盘差异
sagit:/ # ls -lsh /data/adb/ksu/modules_update.img && sleep 120 && ls -lsh /data/adb/ksu/modules_update.img
6.4M -rw------- 1 root root 1.0T 2024-02-25 18:07 /data/adb/ksu/modules_update.img
6.4M -rw------- 1 root root 1.0T 2024-02-25 18:07 /data/adb/ksu/modules_update.img
sagit:/ #
sagit:/ # ls -lsh /data/adb/ksu/modules.img && sleep 120 && ls -lsh /data/adb/ksu/modules.img
6.4M -rw------- 1 root root 1.0T 2024-02-25 18:07 /data/adb/ksu/modules.img
6.4M -rw------- 1 root root 1.0T 2024-02-25 18:07 /data/adb/ksu/modules.img

8. 在系统内重启手机
9. 等待2分钟  对比 modules.img 实际占用磁盘差异
builder@papercom:~$ adb shell
sagit:/ $ su
sagit:/ # ls -lsh /data/adb/ksu/modules.img && sleep 120 && ls -lsh /data/adb/ksu/modules.img
6.4M -rw------- 1 root root 1.0T 2024-02-25 18:13 /data/adb/ksu/modules.img
6.4M -rw------- 1 root root 1.0T 2024-02-25 18:13 /data/adb/ksu/modules.img
```

**Comment by Aquarius223** [comment]
复现尝试1:
1. 卸载0.8.0管理器 重启至REC 在终端执行 rm -rf /data/adb
2. 开机后安装 0.7.0 管理器启动它 并给 Shell 和 MT 管理器 启用超级用户 (未安装模块)
3. 重启手机
4. 开机后 ( 此时 ksud 为 0.7.0, ksu为 11153 ) 安装 0.8.0 的管理器 并启动 安装模块 后 重启手机
5. 进行 添加 删除 禁用模块 重启手机
它又恢复正常了, 并未出现体积增长的问题, 看起来需要 内核(ksu) 和 管理器(ksud) 同时升级才会复现?

**Comment by tiann** [comment]
> 复现尝试1:
> 
> 1. 卸载0.8.0管理器 重启至REC 在终端执行 rm -rf /data/adb
> 2. 开机后安装 0.7.0 管理器启动它 并给 Shell 和 MT 管理器 启用超级用户 (未安装模块)
> 3. 重启手机
> 4. 开机后 ( 此时 ksud 为 0.7.0, ksu为 11153 ) 安装 0.8.0 的管理器 并启动 安装模块 后 重启手机
> 5. 进行 添加 删除 禁用模块 重启手机
>    它又恢复正常了, 并未出现体积增长的问题, 看起来需要 内核(ksu) 和 管理器(ksud) 同时升级才会复现?

你需要用低版本管理器安装一个模块，然后再升级到高版本，应该是这种情况。如果之前没有安装过任何模块，那不影响。

**Comment by Aquarius223** [comment]
> > 复现尝试1:
> > 
> > 1. 卸载0.8.0管理器 重启至REC 在终端执行 rm -rf /data/adb
> > 2. 开机后安装 0.7.0 管理器启动它 并给 Shell 和 MT 管理器 启用超级用户 (未安装模块)
> > 3. 重启手机
> > 4. 开机后 ( 此时 ksud 为 0.7.0, ksu为 11153 ) 安装 0.8.0 的管理器 并启动 安装模块 后 重启手机
> > 5. 进行 添加 删除 禁用模块 重启手机
> >    它又恢复正常了, 并未出现体积增长的问题, 看起来需要 内核(ksu) 和 管理器(ksud) 同时升级才会复现?
> 
> 你需要用低版本管理器安装一个模块，然后再升级到高版本，应该是这种情况。如果之前没有安装过任何模块，那不影响。

测试了4种复现方法, 根本原因是 低版本管理器安装模块然后升级了高版本管理器 并且对 modules.img 有操作 (比如安装 卸载 禁用), 然后即可复现以上bug
同时我尝试了最新的管理器ci构建 : https://github.com/tiann/KernelSU/actions/runs/8037898164
依然存在这个问题:
```
sagit:/data/adb # ./ksud -V
ksud 0.8.0-4-gb670db2
sagit:/data/adb # cd ksu
sagit:/data/adb/ksu # du -sh modules.img && sleep 120 && du -sh modules.img
167M	modules.img
194M	modules.img
sagit:/data/adb/ksu #
```

**Comment by tiann** [comment]
https://github.com/tiann/KernelSU/actions/runs/8038672786

再用这个测试一下呢？

**Comment by Aquarius223** [comment]
> https://github.com/tiann/KernelSU/actions/runs/8038672786
> 
> 再用这个测试一下呢？

没问题了 以下是我的测试步骤 截止23:05分 实际占用依然是13MB
```
sagit:/ $ su
sagit:/ # cd /data/adb
sagit:/data/adb # ./ksud -V
ksud 0.7.0
sagit:/data/adb # ls -lsh ksu/modules.img
8.2M -rw------- 1 root root 256M 2024-02-25 22:53 ksu/modules.img
sagit:/data/adb # ls -lsh ksu/modules.img
8.2M -rw------- 1 root root 256M 2024-02-25 22:53 ksu/modules.img

- 期间更新 0.8.0-6-g300d9d4 的管理器

sagit:/data/adb # ./ksud -V
ksud 0.8.0-6-g300d9d4

- 期间随便安装了个模块 并重启

sagit:/data/adb # builder@papercom:~$ adb shell
sagit:/ $ su
sagit:/ # cd /data/adb
sagit:/data/adb # ./ksud -V
ksud 0.8.0-6-g300d9d4

- 等待 2分钟 确认镜像是否还存在占用问题

sagit:/data/adb # ls -lsh ksu/modules.img && sleep 120 && ls -lsh ksu/modules.img
13M -rw------- 1 root root 1.0T 2024-02-25 22:56 ksu/modules.img
13M -rw------- 1 root root 1.0T 2024-02-25 22:56 ksu/modules.img
sagit:/data/adb # 
```

**Comment by Aquarius223** [comment]
> https://github.com/tiann/KernelSU/actions/runs/8038672786
> 
> 再用这个测试一下呢？

同时又装了4个模块 禁用了一个, 卸载了一个, 重启后使用上述命令测试镜像实际占用空间, 2分钟前后大小一致, 同时也不会出现 点击开关禁用和点击卸载按钮 长时间转圈圈的问题了
