### ISSUE TITLE
[Question] Modules umount feature

### ISSUE THREAD

**Issue by Fede2782** [tiann/KernelSU#1386]
First of all if you want to close this issue because it's irrelevant and unuseful feel free to do it. 😊

I would like to ask what does the umount modules feature do and if there is a way to check its functioning? Are there benefits and when enabled do the app see the stock/actual system? I've read the documentation but i haven't found an answer to my questions, sorry

**Comment by tiann** [comment]
> what does the umount modules feature do

Some modules need mount files to system, but some apps don't like this, if they find the mount they will refuse to run. "umount modules" remove the influence of the modules to specific apps.

> if there is a way to check its functioning

```sh
cat /proc/<pid>/mountinfo | grep modules
```

If there is nothing, then it is functioning.

**Comment by Fede2782** [comment]
> > what does the umount modules feature do
> 
> Some modules need mount files to system, but some apps don't like this, if they find the mount they will refuse to run. "umount modules" remove the influence of the modules to specific apps.
> 
> > if there is a way to check its functioning
> 
> ```shell
> cat /proc/<pid>/mountinfo | grep modules
> ```
> 
> If there is nothing, then it is functioning.

Thanks a lot
