### ISSUE TITLE
Samsung My Files showing abnormal storage with new KernelSU

### ISSUE THREAD

**Issue by Fede2782** [tiann/KernelSU#1389]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [x] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Samsung (system) apps showing 2TB of storage instead of the actual device storage size

### To Reproduce

Use KernelSU v0.8.0 on a Samsung device with Android 13 (One UI 5.x.x) and see how the storage calculation is now completely a mess showing 2TB in some menus full in others empty on my 64GB storage device. Tried with modules and without, also with shamiko umount but still showing this storage amount at least in the Settings Device Care menu

### Expected behavior

I should see my real device storage in all the system. 

### Screenshots

![Screenshot_20240225_131103_My Files](https://github.com/tiann/KernelSU/assets/78815152/893cb1dc-3e36-4e37-8a93-1090fb20e308)

### Logs

[KernelSU_bugreport_2024-02-25_13_22.tar.gz](https://github.com/tiann/KernelSU/files/14396347/KernelSU_bugreport_2024-02-25_13_22.tar.gz)

### Device info

- Device: Galaxy Tab S6 Lite (gta4xl)
- OS Version: 13 (One UI 5.1.1)
- KernelSU Version: v0.8.0
- Kernel Version: 4.14.113 [FXA1 release](https://github.com/Fede2782/android_kernel_samsung_gta4xl)

### Additional context

Samsung One UI 6 changes storage measure method so this issue may only affect Android 13 and lower

**Comment by tiann** [comment]
https://kernelsu.org/guide/faq.html#why-is-there-a-huge-1t-file

Ask samsung to add support for sparse image file

**Comment by Fede2782** [comment]
> https://kernelsu.org/guide/faq.html#why-is-there-a-huge-1t-file
> 
> Ask samsung to add support for sparse image file

I know but this issue would affect a lot of devices with One UI, i'll investigate more.

**Comment by Shirayuki39** [comment]
> > https://kernelsu.org/guide/faq.html#why-is-there-a-huge-1t-file
> > Ask samsung to add support for sparse image file
> 
> I know but this issue would affect a lot of devices with One UI, i'll investigate more.

This issue also affects Infinix XOS' about device pane and storage menu

**Comment by ExtremeXT** [comment]
This problem is present on OneUI 6.0 as well, and resolving it is obviously not as easy as inquiring to Samsung about it. If possible, this should be addressed, the majority of Android users are from Samsung.

**Comment by zeta96** [comment]
happens on my custom rom, cant install anything, app auto stop working
