### ISSUE TITLE
Cannot install/update modules after upgrading to v0.8.1

### ISSUE THREAD

**Issue by belinux** [tiann/KernelSU#1397]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

An error occurred whiled updating a module. (I tried with different modules, all of them gave me the same error, check the log attached.)

### To Reproduce

1. Install kernelsu v0.8.1
2. Install or update any module.

### Expected behavior

Module installed or updated

### Logs

  _  __                    _ ____  _   _ 
 | |/ /___ _ __ _ __   ___| / ___|| | | |
 | ' // _ \ '__| '_ \ / _ \ \___ \| | | |
 | . \  __/ |  | | | |  __/ |___) | |_| |
 |_|\_\___|_|  |_| |_|\___|_|____/ \___/ 

- Preparing image
- Module size: 306.87 kB
- Legacy image, migrating to new format, please be patient...
e2fsck 1.46.6 (1-Feb-2023)
- Error: No such file or directory (os error 2)
Error: No such file or directory (os error 2)

[KernelSU_bugreport_2024-02-26_13_21.tar.gz](https://github.com/tiann/KernelSU/files/14404494/KernelSU_bugreport_2024-02-26_13_21.tar.gz)

### Device info

- Device: Pixel 7 Pro
- OS Version: 14
- KernelSU Version: 0.8.1
- Kernel Version:  AnyKernel3-android13-5.10.198_2023-12.zip

**Comment by tiann** [comment]
upload logs

**Comment by belinux** [comment]
@tiann uploaded, sorry i missed that one

**Comment by Fede2782** [comment]
I had to force remove /data/adb/* to fix this

**Comment by Trisn0802** [comment]
Just uninstall the newest version of 0.81 KSU apps, and use the previous version, mine already tried and it worked 
![Screenshot_20240227-103631_KernelSU](https://github.com/tiann/KernelSU/assets/86393440/c3591803-9899-420c-837d-746985f11ba6)

**Comment by belinux** [comment]
> I had to force remove /data/adb/* to fix this on my devices

I want to try this, should I reboot after removing? reinstall anything else beside the modules?

**Comment by bugme2** [comment]
@tiann 已安装模块目录中存在REMOVE或者mknod创建的文件时，安装新的模块或者更新模块就会报错文件不存在(已安装模块目录中mknod创建的文件)，禁用模块后可以正常安装。

**Comment by belinux** [comment]
> @tiann 已安装模块目录中存在REMOVE或者mknod创建的文件时，安装新的模块或者更新模块就会报错文件不存在(已安装模块目录中mknod创建的文件)，禁用模块后可以正常安装。

Disabling the module before allowed me to update it. Thanx a lot!
