### ISSUE TITLE
Update 0.8.1 or 0.8.0 exposes root. 

### ISSUE THREAD

**Issue by Wojtaz0w** [tiann/KernelSU#1398]
Now momo shows partition mounted abnormally and playstation remote play shows root error. Please look into this, I am going to rollback to 0.8.0 for now and see if it works. ![Screenshot_20240226-113103_Momo.png](https://github.com/tiann/KernelSU/assets/104674625/f70dc40d-ea52-4372-be67-54484a82a29b)

**Comment by Wojtaz0w** [comment]
0.8.0 didn't fix the issue. ![Screenshot_20240226-113827_KernelSU.png](https://github.com/tiann/KernelSU/assets/104674625/85918fde-9183-46b3-81c2-40219ca7fac3)

![Screenshot_20240226-113830_KernelSU.png](https://github.com/tiann/KernelSU/assets/104674625/0808f996-3a12-47be-9551-b7b6d1c90c8c)

**Comment by tiann** [comment]
nothing to do with KernelSU.

**Comment by Wojtaz0w** [comment]
Ok sorry bro... it was hosts module 
Have a great day 🙏🏻
