### ISSUE TITLE
System partition increasing its size automatically after 0.8.1 version 

### ISSUE THREAD

**Issue by improbir** [tiann/KernelSU#1401]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

After updating to 0.8.1 version.. suddenly I am experiencing system partition is increasing automatically on its own. I have removed all the modules but problem remains there.
![Screenshot_20240227-075925_Settings](https://github.com/tiann/KernelSU/assets/25155316/b3c0e2be-605d-4257-bafe-047fcfc8aa49)
![Screenshot_20240227-080704_Settings](https://github.com/tiann/KernelSU/assets/25155316/491861da-965f-42b0-b3db-92b999b8b3eb)
![Screenshot_20240227-080857_KernelSU](https://github.com/tiann/KernelSU/assets/25155316/a32ad68b-0e3c-413d-82b0-0ce2ef8e79fe)

You can check my screenshot along with the statusbar timestamp.
![Screenshot_20240227-081139_Settings](https://github.com/tiann/KernelSU/assets/25155316/4cff49e6-993d-45d9-a898-2403e0721fda)

### To Reproduce

First experienced this bug in 0.8.0 version 

### Device info

- Device: Realme XT
- OS Version: 14
- KernelSU Version: 0.8.1
- Kernel Version: 4.9.337

**Comment by improbir** [comment]
![Screenshot_20240227-081607_Settings](https://github.com/tiann/KernelSU/assets/25155316/84b17baf-4a56-40e4-b2bd-e71c799a17a1)

And now this..

**Comment by improbir** [comment]
And now situation is this..
![Screenshot_20240227-082556_Settings](https://github.com/tiann/KernelSU/assets/25155316/a5adc01c-5486-46f7-b958-1f0ce3fce11a)

**Comment by improbir** [comment]
[KernelSU_bugreport_2024-02-27_08_32.tar.gz](https://github.com/tiann/KernelSU/files/14413767/KernelSU_bugreport_2024-02-27_08_32.tar.gz)

**Comment by tiann** [comment]
I can't understand

**Comment by tiann** [comment]
`rm -rf /data/adb/ksu/*.img` and reboot

**Comment by improbir** [comment]
> I can't understand

see all my screenshot..you will notice that the system partition size is increasing but i am not doing anything.. and the device is not a dynamic partition so i hope you understood it.

**Comment by improbir** [comment]
> `rm -rf /data/adb/ksu/*.img` and reboot

i did it but no solution... the only solution for this issue is just uninstall the KSU and storage issue will be fixed immediately.

**Comment by tiann** [comment]
uninstall the manager or kernel?

**Comment by improbir** [comment]
> uninstall the manager or kernel?

I reflashed the rom zip which completely remove the ksu from my system and that's how it's fixed

**Comment by improbir** [comment]
maybe look into this commit - https://github.com/tiann/KernelSU/commit/65bff7bf0365d93a2ef9518445fc460074ecfce6

**Comment by zeta96** [comment]
maybe you need phone with 1 TB storage free if you want to use v0.8.1

**Comment by tiann** [comment]
> > uninstall the manager or kernel?
> 
> I reflashed the rom zip which completely remove the ksu from my system and that's how it fixed

What if you flash the kernel but don't install the manager(You should `rm -rf /data/adb/ksu` first)?

**Comment by Fede2782** [comment]
Similar to #1389

**Comment by improbir** [comment]
> > > uninstall the manager or kernel?
> > 
> > 
> > I reflashed the rom zip which completely remove the ksu from my system and that's how it fixed
> 
> What if you flash the kernel but don't install the manager(You should `rm -rf /data/adb/ksu` first)?

Sorry I gave you little headache. Fault was from my side.. I haven't up-streamed the Anykernel3 repo for a while maybe that's lead to this issue. I just built a new kernel with updated Anykernel3.. everything seems fine at the moment. Hence i am closing the issue.

**Comment by improbir** [comment]
tbh new implementation is just created 69 issues across several devices..

> https://kernelsu.org/guide/faq.html#why-is-there-a-huge-1t-file
> 
> #1389

tbh new implementation is just created 69 issues across several devices..

**Comment by Fede2782** [comment]
> tbh new implementation is just created 69 issues across several devices..
> 
> > https://kernelsu.org/guide/faq.html#why-is-there-a-huge-1t-file
> > #1389
> 
> tbh new implementation is just created 69 issues across several devices..

This implementation is completely useless. The best way would have been to let module developers decide a module size using a value in module.prop in this way the sparse image grows only if necessary

**Comment by improbir** [comment]
> > tbh new implementation is just created 69 issues across several devices..
> > > https://kernelsu.org/guide/faq.html#why-is-there-a-huge-1t-file
> > > #1389
> > 
> > 
> > tbh new implementation is just created 69 issues across several devices..
> 
> This implementation is completely useless. The best way would have been to let module developers decide a module size using a value in module.prop in this way the sparse image grows only if necessary

i agree
