### ISSUE TITLE
support arm32 arch

### ISSUE THREAD

**Issue by ndl1302732** [tiann/KernelSU#1404]
### Is your feature request related to a problem? Please describe.

some phone has arm32 arch.
my dear da lao ,please support arm32 arch

### Describe the solution you'd like.

my dear da lao ,please support arm32 arch

### Describe alternatives you've considered.

my dear da lao ,please support arm32 arch

### Additional context

my dear da lao ,please support arm32 arch

**Comment by tiann** [comment]
#701
