### ISSUE TITLE
Magisk compatibility for Audio modules

### ISSUE THREAD

**Issue by kgursu** [tiann/KernelSU#1406]
### Is your feature request related to a problem? Please describe.

I cannot use zyhk's audio modules after upgrading to the latest KernelSU version. I asked zyhk for a technical response.

### Describe the solution you'd like.

His answer is here: "I need mirrored partitions as Magisk offers for properly updating my module (already installed) by using "customize.sh" because of avoiding files already modified by the module itself."

### Describe alternatives you've considered.

I don't know any alternatives, but I can ask again.

**Comment by tiann** [comment]
i can't understand the situation, please describe the issue more clearly

**Comment by kgursu** [comment]
I asked him to jump in.

**Comment by yzyhk904** [comment]
When updating a magisk module (already installed), updating "customize.sh" refers modified files by its older module without mirrored file systems which Magisk now offers. This causes a wrong result. For example, see my module [DRC remover](https://github.com/Magisk-Modules-Alt-Repo/drc-remover).

I think this situation can be avoided by moving a customize process into "post-fs-data.sh", but I don't want this.
