### ISSUE TITLE
Installing more than 1 module changes the storage values in Xiaomi HyperOS

### ISSUE THREAD

**Issue by Insidevk18** [tiann/KernelSU#1419]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

I have a module (any) previously installed, when flashing another module and restarting, the storage values that were previously:

- Occupied space 23.8 GB / Total Space 128 GB

Change after flashing to:
-Occupied space 1.8 TB / Total Space 2 TB

The problem is not with the modules since I tried 4 different modules that previously did not generate errors in MIUI 14 (before updating to HyperOS 1.0.3)

This problem is only on the cell phone, since when I connect the cell phone to the PC the storage values are normal (Occupied space 23.8 GB / Total Space 128 GB).

### To Reproduce

-1. Go to KernelSU
-2. Go to module section
-3. search module file
-4. flash module and reboot
-5. repeat the process with any other module
-6. reboot
-7. When entering settings, the storage changes values

### Expected behavior

The storage values that were previously:
- Occupied space 23.8 GB / Total Space 128 GB

Change to:
-Occupied space 1.8 TB / Total Space 2 TB

### Screenshots

BEFORE (1 MODULE):
![WhatsApp Image 2024-03-04 at 3 03 14 PM](https://github.com/tiann/KernelSU/assets/94028610/fd50cd1e-0866-42f1-996e-9eadc0459e99)

AFTER (2 MOULE):
![WhatsApp Ima1ge 2024-03-04 at 3 08 36 PM](https://github.com/tiann/KernelSU/assets/94028610/50781568-8ad2-42cc-818e-6cf574f6ea03)
![WhatsApp Image 2024-03-04 at 3 08 36 PM](https://github.com/tiann/KernelSU/assets/94028610/72852f11-21bc-4c55-8b47-4d6ef489df70)

### Logs

[KernelSU_bugreport_2024-03-04_15_07.tar.gz](https://github.com/tiann/KernelSU/files/14486673/KernelSU_bugreport_2024-03-04_15_07.tar.gz)

### Device info

- Device: Redmi Note 11 (spes)
- OS Version: HyperOS 1.0.3.0.TGKMIXM Estable
- KernelSU Version: 0.8.1-20-gdbe43b1(11583)
- Kernel Version: 4.19.307-DragonTurbo-GuiixX-gbf452821bd82-dirty

### Additional context

This problem only alters the sample storage values on the cell phone, since on the computer I verified that the storage remained the same.
This problem did not happen to me in Xiaomi MIUI 14, it is recent from Xiaomi HyperOS.

**Comment by zeta96** [comment]
https://github.com/tiann/KernelSU/issues/1411

https://github.com/tiann/KernelSU/issues/1389

https://github.com/tiann/KernelSU/issues/1401

https://kernelsu.org/guide/faq.html#why-is-there-a-huge-1t-file

**Comment by Insidevk18** [comment]
> #1411
> 
> #1389
> 
> #1401
> 
> https://kernelsu.org/guide/faq.html#why-is-there-a-huge-1t-file
_____________________________________________________________________________________________
Excuse my ignorance, after reading the other posts, I should understand that:

- Does this storage problem not affect the cell phone or its performance in any way and will I be able to install applications and my phone function normally?

-Couldn't this problem be solved since the problem comes from the modules?

**Comment by tiann** [comment]
https://github.com/tiann/KernelSU/issues/1411#issuecomment-1977914161

By the way, the latest HyperOS has fixed this:

![image](https://github.com/tiann/KernelSU/assets/4233744/2c55eeb6-508b-4c29-9600-1ce604a276e0)
