### ISSUE TITLE
[Feature] Add docs for building android14 GKI  

### ISSUE THREAD

**Issue by singer233** [tiann/KernelSU#1420]
### Is your feature request related to a problem? Please describe.

In some android 14 devices (such as pixel 8) sometime we need delete the GKI protected exports to make WiFi/Bluetooth work but this is not documented on the website, although this is a googles issue, but i still think document is good 

### Describe the solution you'd like.

add the documentation for the android14 GKI protected export problem

### Describe alternatives you've considered.

just add the document

**Comment by tiann** [comment]
We don't teach building kernel, but PRs welcome.
