### ISSUE TITLE
can uninstall ksu

### ISSUE THREAD

**Issue by Abdurrahman98XX** [tiann/KernelSU#1425]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

installed ksu combined with kinesis kernal but and now cant uninstall ksu 

### To Reproduce

1. rm -rf /data/adb/ksu*
2. flash stock boot.img

### Expected behavior

ksu removed

### Device info

- Device: xiaomi note 9s
- OS Version: 14
- KernelSU Version: 0.8.1-20-gdbe43b1
- Kernel Version: 4.14.336-perf

**Comment by tiann** [comment]
If flashing the stock image still cannot be restored, then this has nothing to do with KernelSU.
