### ISSUE TITLE
4.4 Kernel ksu compilation error

### ISSUE THREAD

**Issue by wu17481748** [tiann/KernelSU#1426]
### Describe your problem.

In function `setup_groups':
/root/android_kernel_xiaomi_msm8998/out/../drivers/kernelsu/core_hook.c:99: undefined reference to `groups_sort'

**Comment by MarisaDAZA** [comment]
How to solve it! I also have this problem. :)

**Comment by Coconutat** [comment]
> How to solve it! I also have this problem. :)

Try This:https://github.com/riarumoda/KernelSU-4.4
