### ISSUE TITLE
KernalSU manager says not installed, however no kernal is found

### ISSUE THREAD

**Issue by eclipsek20** [tiann/KernelSU#1428]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

I have kernal 5.10.205-gki-g879a256feb4d installed on my phone, the manager says that "not installed" which implies that kernalsu is supported, however on the download page i cant find this version, why is this?

### Device info

- Device: Xiaomi 12 (cupid)
- OS Version: A14 (Evolution-X latest)
- KernelSU Version: v0.8.1
- Kernel Version: 5.10.205-gki-g879a256feb4d

**Comment by tiann** [comment]
read docs please.
