### ISSUE TITLE
Constantly Writing data to internal storage 

### ISSUE THREAD

**Issue by ankur-raikwar** [tiann/KernelSU#1430]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [ ] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

**After Upgraging to KSU 11563 (manager 0.8.1), my phone's Internal Storage is getting filled every second.**

Before KSU installation my Internal Storage was at 2.5* GB filled. But after installing KSU it is now 15.78 GB*+ and continously getting filled (I confirmed using Root Explorer app) and I am sure the file which is taking space is in "/data/adb/ksu/modules.img" is updating every sec.

### This is the list of modules that I had installed:

1. playcurl
2. PlayIntegrityFix - AutoPIF NEXT Fork
3. Zygisk Next

 **_I also confirmed that no app is downloaded/updated, hence actual space is eaten up by KernelSU_**.

**Kindly also check the Storage Screenshot to see what kind of data hogging KernelSU is doing**. 

### Screenshots

![Screenshot_20240307-174155_Settings](https://github.com/tiann/KernelSU/assets/3439247/2ccd5c2d-4da4-4ae1-8dae-f8d720293172)

### Device info

- Device: Redmi Note 6 Pro
- OS Version: Android 11 HyconOS
- KernelSU Version: 11563 (Manager 0.8.1)
- Kernel Version: 4.4.302

**Comment by tiann** [comment]
#1401
#1384 

Update your manager to 11583 should be ok.

**Comment by ankur-raikwar** [comment]
I confrim I was using Manager Version **0.8.1 11583**

![Screenshot_20240307-182126_KernelSU](https://github.com/tiann/KernelSU/assets/3439247/4ed2e00a-5c1f-40de-9db9-43fef6ff34e5)

**Comment by zeta96** [comment]
https://github.com/tiann/KernelSU/issues/1411 

use : ksud module shrink, or delete module.img should be ok

**Comment by improbir** [comment]
> #1411
> 
> #1389
> 
> use : ksud module shrink, or delete module.img should be ok

Link?
