### ISSUE TITLE
一个挂载问题

### ISSUE THREAD

**Issue by jrcloud-next** [tiann/KernelSU#1438]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [ ] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

管理器v0.8.1-20-gdbe43b1 通过模块把应用挂载到系统分区似乎有问题 能挂载上但是打开不了 之前版本没这个问题
[附图](https://img.hkspa.top/2024/03/09/65ec08a1345bf.jpg)

### Device info

- Device:
- OS Version:Android 14 UKQ1.231003.002
- KernelSU Version:v0.8.1-20-gdbe43b1
- Kernel Version:5.10.198-android12-9-00174-g73d9788812c5-dirty

**Comment by tiann** [comment]
没动过挂载，我不认为这是 KernelSU 的问题。
