### ISSUE TITLE
KernelSU not working on ARM64 WSA

### ISSUE THREAD

**Issue by TGSAN** [tiann/KernelSU#1450]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

After replaced kernel image using kernel-WSA-arm64, it will display the `Starting Windows Subsystem for Android™` window, and then disappear after a few minutes. During the window display, I noticed that `vmmemCmZygote` had no memory usage changes.

### Device info

- Device: Microsoft Surface Pro X
- OS Version: Windows Subsystem for Android 2311.40000.5.0
- KernelSU Version: v0.8.1
- Kernel Version: kernel-WSA-arm64-5.15.104.1/5.15.104.2/5.15.104.3/5.15.104.4/5.15.94.2

**Comment by tiann** [comment]
Since [Microsoft is ending support for the Windows Subsystem for Android™️ (WSA)](https://learn.microsoft.com/en-gb/windows/android/wsa), we will remove support for it soon, so no bugfix will be made.
