### ISSUE TITLE
KSU app detected by some Banking apps

### ISSUE THREAD

**Issue by sd535682** [tiann/KernelSU#1455]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

So when i am using KSU apk some banking apps are crashing. But after Uninstalling it fixes the issue. 

### Device info

- Device: Realme GT neo 3T
- OS Version: Android 14
- KernelSU Version: 0.8.1
- Kernel Version: 4.19.272

**Comment by tiann** [comment]
You can do some fixes.

**Comment by fa1conn** [comment]
What bank app？
