### ISSUE TITLE
After installing a module in manager 0.8.0 the modules.img file becomes too large

### ISSUE THREAD

**Issue by adhammagdy** [tiann/KernelSU#1466]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

When I install any module with kernelsu manager 0.8.0 or higher and reboot to twrp or orangefox recovery, the data size in data partition becomes messed up and is very large so impossible to take data backup.. after removing all modules or deleting modules.img the data size returns to normal.. this issue is not in manager 0.7.6
Also when I checked a file manager it showed that the modules.img file size is very large (in terabytes)

### To Reproduce

Install kernelsu manager 0.8.0 or higher
Install any module
Reboot to recovery or system
Check the modules.img file size

### Expected behavior

The modules.img file size should fit the modules only

### Screenshots

![file-manager](https://github.com/tiann/KernelSU/assets/37498515/248fabef-a6b7-4a38-8214-dd14752e05e5)
![recovery-data-size-after-module](https://github.com/tiann/KernelSU/assets/37498515/0b01f45f-666c-478a-a997-5fb056a57d43)
![recovery-data-size-before-module](https://github.com/tiann/KernelSU/assets/37498515/dba6da52-0168-41db-930f-81f37ea3ce23)

### Logs

[KernelSU_bugreport-before-module.tar.gz](https://github.com/tiann/KernelSU/files/14627107/KernelSU_bugreport-before-module.tar.gz)
[KernelSU_bugreport-after-module.tar.gz](https://github.com/tiann/KernelSU/files/14627108/KernelSU_bugreport-after-module.tar.gz)

### Device info

- Device: Poco F3 (Alioth)
- OS Version: 14
- KernelSU Version: 11434
- Kernel Version: 4.19.304-Baalam_7.0-Blade_KSU

**Comment by Fede2782** [comment]
Basically #1389

**Comment by meiser79** [comment]
https://kernelsu.org/guide/faq.html#why-is-there-a-huge-1-tb-file
