### ISSUE TITLE
[Request] Please add lz4 boot support

### ISSUE THREAD

**Issue by ItsMadruga** [tiann/KernelSU#1467]
My device only supports images compressed in .lz4, I tried to install it using lkm mode, but it is not possible to decompress lz4 files

**Comment by tiann** [comment]
lkm use `magiskboot` to pack image, there is no reason it doesn't support lz4.

**Comment by ItsMadruga** [comment]
![Screenshot_20240317_120558_KernelSU](https://github.com/tiann/KernelSU/assets/104334266/cf559e75-8479-4cfe-a23f-3fb56685499a)

When I try to patch init_boot.img.lz4 I get this error, if I use lz4 to transform it into init_boot.img it works perfectly, but my device does not support flashing .img only .img.lz4
