### ISSUE TITLE
ColorOS14.0.0系统通过LKM方式获得KernelSU 权限后无法正常调用模块

### ISSUE THREAD

**Issue by Leienjoy** [tiann/KernelSU#1469]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

系统版本：ColorOS14.0.0.131(CN01)
内核版本：5.15.94-android13-8-0-00703-qaafa2cb5a21a#1 Fri Dec 29 04:26:23 UTC 2023
目前遇到的问题:通过修补“init-boot”获取到了权限后，授予应用超级用户权限无问题，但刷入任何模块不会被调用，开关处于灰色状态，点击卸载模块重启后也无法被卸载

### To Reproduce

1.通过管理器修补“init-boot”
2.进入fastboot模式刷入
3.开机成功获得权限
4.刷入模块并重启
5.开机后发现如上问题

### Screenshots

![微信图片_20240318100612](https://github.com/tiann/KernelSU/assets/108409318/dd859b55-c843-44e2-852e-817c7ddead9a)

### Logs

[KernelSU_bugreport_2024-03-17_22_04.tar.gz](https://github.com/tiann/KernelSU/files/14630054/KernelSU_bugreport_2024-03-17_22_04.tar.gz)

### Device info

- Device: OnePlusAce2Pro(PJA110)
- OS Version: ColorOS14.0.0.131(CN01)
- KernelSU Version: v0.9.0-3.ga5e7655(11631)
- Kernel Version: 5.15.94-android13-8-0-00703-qaafa2cb5a21a#1 Fri Dec 29 04:26:23 UTC 2023

**Comment by Atroc-X** [comment]
The same problem, both OnePlus and Oppo have this problem.

**Comment by tiann** [comment]
重启设备，然后执行 `adb bugreport` 发送上来，因为没有 root，很多日志是空的。

**Comment by Leienjoy** [comment]
> 重启设备，然后执行 `adb bugreport` 发送上来，因为没有 root，很多日志是空的。

非常感谢您的回复，已经上传了我的log
[Uploading bugreport-PJA110-UKQ1.230924.001-2024-03-18-13-55-22.zip…]()

**Comment by tiann** [comment]
链接无法下载

**Comment by Leienjoy** [comment]
> 链接无法下载

[Uploading bugreport-PJA110-UKQ1.230924.001-2024-03-18-13-55-22.zip…]()

**Comment by Leienjoy** [comment]
> 链接无法下载

https://airportal.cn/577112/XSfCTtGaRa Github上传半天都不行

**Comment by tiann** [comment]
提取码是什么？

**Comment by Leienjoy** [comment]
> 提取码是什么？

577112，这个提取码只有两次下载机会有人下载了( 
这是123Pan地址：https://www.123pan.com/s/qvqA-VyxVv.html

**Comment by tiann** [comment]
`adb shell` 能获取 root 权限吗？

**Comment by Leienjoy** [comment]
> `adb shell` 能获取 root 权限吗？



> `adb shell` 能获取 root 权限吗？

<img width="433" alt="Snipaste_2024-03-18_14-35-52" src="https://github.com/tiann/KernelSU/assets/108409318/5c02b2b5-da0f-40b1-9ba5-97738371ab74">

**Comment by tiann** [comment]
`su`

**Comment by Leienjoy** [comment]
> `su`

<img width="388" alt="Snipaste_2024-03-18_14-42-41" src="https://github.com/tiann/KernelSU/assets/108409318/e9d70b3f-2b73-4f7d-a103-ce671d23fa25">

**Comment by tiann** [comment]
`$(pm path me.weishu.kernelsu | cut -d':' -f 2 | xargs dirname)/lib/arm64/libksud.so debug su`

**Comment by Leienjoy** [comment]
> $(pm path me.weishu.kernelsu | cut -d':' -f 2 | xargs dirname)/lib/arm64/libksud.so debug su

<img width="774" alt="Snipaste_2024-03-18_14-51-13" src="https://github.com/tiann/KernelSU/assets/108409318/1746e092-51c1-4037-85d2-75cac163f22a">

**Comment by tiann** [comment]
Ok, 你重启手机，然后立马 adb shell，执行这条命令，然后 dmesg > /data/local/tmp/dmesg.log 把这个 log 文件传上来

**Comment by Leienjoy** [comment]
> Ok, 你重启手机，然后立马 adb shell，执行这条命令，然后 dmesg > /data/local/tmp/dmesg.log 把这个 log 文件传上来

<img width="862" alt="Snipaste_2024-03-18_15-08-57" src="https://github.com/tiann/KernelSU/assets/108409318/d6874bf2-8d22-45d1-942d-8530ba8a8996">

**Comment by Leienjoy** [comment]
> > Ok, 你重启手机，然后立马 adb shell，执行这条命令，然后 dmesg > /data/local/tmp/dmesg.log 把这个 log 文件传上来
> 
> <img alt="Snipaste_2024-03-18_15-08-57" width="862" src="https://private-user-images.githubusercontent.com/108409318/313580205-d6874bf2-8d22-45d1-942d-8530ba8a8996.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NDYwOTQsIm5iZiI6MTcxMDc0NTc5NCwicGF0aCI6Ii8xMDg0MDkzMTgvMzEzNTgwMjA1LWQ2ODc0YmYyLThkMjItNDVkMS05NDJkLTg1MzBiYThhODk5Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQwNzA5NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YzU2MDBiYTcxMTg5ZmUyNjRjOWY0NjMyN2YzY2IzZjVhM2M2Mjk1OTU5NDg4YmY0M2RmZWE2ZThkMTA0ZDYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4s4Q7EHJpa624OSushAgwwEAw3uWibf8SgzD0k9RE3E">

log并没有产生

**Comment by tiann** [comment]
> > $(pm path me.weishu.kernelsu | cut -d':' -f 2 | xargs dirname)/lib/arm64/libksud.so debug su
> 
> <img alt="Snipaste_2024-03-18_14-51-13" width="774" src="https://private-user-images.githubusercontent.com/108409318/313576017-1746e092-51c1-4037-85d2-75cac163f22a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NDU2NzgsIm5iZiI6MTcxMDc0NTM3OCwicGF0aCI6Ii8xMDg0MDkzMTgvMzEzNTc2MDE3LTE3NDZlMDkyLTUxYzEtNDAzNy04NWQyLTc1Y2FjMTYzZjIyYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQwNzAyNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OGIyZGY0YWIwYzkwMjQyZDBkZmE2NjFmYzkxZjc3YzkzNGUzNGJiYjIxMWQxZmY0MzZmZWQzYTA4ZjBmOGExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Jz6szQg--M8vaElm8TVwQN7bVATaYtTZM95BoGTSSmo">

为什么你这个结果能获取到 root，是不是要先去管理器给 shell 权限。

**Comment by Leienjoy** [comment]
> dmesg > /data/local/tmp/dmesg.log

123Pan: https://www.123pan.com/8865782

**Comment by tiann** [comment]
你想办法把这个文件传上来吧，这注册完账号进去一看是空的，实在是难崩

**Comment by tiann** [comment]
有点太晚了，开机日志已经被冲掉了

**Comment by Leienjoy** [comment]
> dmesg > /data/local/tmp/dmesg.log



> 有点太晚了，开机日志已经被冲掉了

[dmesgV2.log](https://github.com/tiann/KernelSU/files/14634122/dmesgV2.log)
不知道这个行不行(

**Comment by tiann** [comment]
https://github.com/tiann/KernelSU/commit/2a64784a3356418f839c54aaf1b36c6553caedd8

**Comment by Leienjoy** [comment]
> https://github.com/tiann/KernelSU/commit/2a64784a3356418f839c54aaf1b36c6553caedd8

修好了嘛(●'◡'●)

**Comment by tiann** [comment]
修好了

**Comment by Leienjoy** [comment]
> 修好了

期待release😘

**Comment by tiann** [comment]
你装 CI 管理器，直接安装就行了。

**Comment by xyychenchen** [comment]
后面这个问题是如何解决的呢，我是非GKI设备，也遇见了这个问题，模块开关也是灰色的
