### ISSUE TITLE
KernelSU安装好模块之后，怎么启动模块图形界面？

### ISSUE THREAD

**Issue by zwl1619** [tiann/KernelSU#1479]
已经安装好了KernelSU的一些模块，如下截图所示：
![Screenshot_20240319-181656](https://github.com/tiann/KernelSU/assets/13177997/4b470ba4-a1d3-4bdd-90aa-140319b53574)

问题：
怎么启动截图里面的模块，让他们显示图形界面？

**Comment by TinyHai** [comment]
just click module card

**Comment by tiann** [comment]
它有图形界面你才能显示。
