### ISSUE TITLE
Telegram进群的考试，最后一步执行完之后会重启，不会显示进群密码

### ISSUE THREAD

**Issue by zwl1619** [tiann/KernelSU#1480]
申请进入Telegram群的时候，会有一个考试，如下截图所示：
![Snipaste_2024-03-19_17-35-17](https://github.com/tiann/KernelSU/assets/13177997/8f4fa638-b676-4cb6-8913-7f26555ffdaf)
按照上面截图的提示，对照官网文档，进行考试，截图如下：
![Snipaste_2024-03-19_17-34-48](https://github.com/tiann/KernelSU/assets/13177997/ff972307-437b-4f2d-b814-f99cdab3d10f)
上面截图红框中是最后一步，刷入boot镜像，按回车后会刷新页面，重新回到页面初始状态，并不会出现进群的密码。
是我哪里搞错了？但是我按官网的步骤，已经在真机上成功了。

**Comment by natsumerinchan** [comment]
你用ls命令查看一下，目录里压根没有`android12-5.10.157_2023-03-boot-lz4.img`

**Comment by natsumerinchan** [comment]
https://kernelsu.org/zh_CN/guide/installation.html#kmi

仔细阅读

**Comment by zwl1619** [comment]
可以了，谢谢

**Comment by zqw251** [comment]
所以刷入后密码到底是多少，人要傻来了
