### ISSUE TITLE
三星 s23u 国行的用修补的init_boot.img无法开机

### ISSUE THREAD

**Issue by ucxl** [tiann/KernelSU#1481]
内核版本是5.15.94-android13-8-1222390-abS9180ZCU2BXA4\n#1 SunFeb 2515:45:19 UTC 2024

**Comment by tiann** [comment]
已知问题，你可以试试用 magiskboot 关闭 knox

**Comment by ucxl** [comment]
好的，谢谢

**Comment by tiann** [comment]
已确认：

1. 在没有 KNOX 的机型上，LKM 模式可以正常运行。
2. 在优 KNOX 的机型上，无法启动；可能是由于 KernelSU 直接操作了 cred，这会被 RKP 阻止。

目前没有计划修复这个问题，建议用 GKI 内核或者编译三星内核。

**Comment by tiann** [comment]
[7254](https://github.com/topjohnwu/Magisk/issues/7254)
