### ISSUE TITLE
Delay at install/uninstalling modules

### ISSUE THREAD

**Issue by Zero00000000000000000000** [tiann/KernelSU#1484]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

When I installed a module it delayed for long time .after trying to uninstall a module its on loading screen. In some reboot system storage behaviors impractical ,automatically size increased in internal storage .

### Device info

- Device: Lavender (Redmi note 7)
- OS Version:  14
- KernelSU Version:9.0
- Kernel Version: nexus KSU

**Comment by tiann** [comment]
follow steps above.
