### ISSUE TITLE
Error patching init_boot.img with "Unknown KMI"

### ISSUE THREAD

**Issue by Dondrejohnson5** [tiann/KernelSU#1485]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

When patching an init-boot.img, an error occurs that states "Unknown KMI" and to use `--kmi` to specify it. How do I do that, and how is the KMI unknown to begin with?

### To Reproduce

Open the app
Tap "Not installed, click to install"
Select a boot.img or init_boot.img of a custom rom, such as LineageOS, of a device with the supported kernel

### Expected behavior

I expected a successful output of the patched init_boot.img

### Screenshots

![Screenshot_20240319-233550_KernelSU](https://github.com/tiann/KernelSU/assets/29732079/cd0111ab-4b5b-4bce-b2fd-18b7c0625f14)

### Logs

[KernelSU_bugreport_2024-03-19_23_51.tar.gz](https://github.com/tiann/KernelSU/files/14661822/KernelSU_bugreport_2024-03-19_23_51.tar.gz)

### Device info

- Device: Motorola Edge+ 2023 (rtwo_g)
- OS Version: Android 14
- KernelSU Version: 0.9.0 (11650)
- Kernel Version: 5.15.148-g1c2aa53515b7

**Comment by tiann** [comment]
Your kernel name does not follow the GKI specification, so it is not possible to determine which LKM should be used. You will need to manually execute the command line.

https://source.android.com/docs/core/architecture/kernel/gki-versioning#design

The "android13" label should not be removed.

**Comment by Dondrejohnson5** [comment]
Ok, so how do I execute the command line for my case?

**Comment by tiann** [comment]
`ksud boot-patch -b <your image> --magiskboot <magiskboot path> --kmi <your kmi>`

**Comment by Dondrejohnson5** [comment]
I'm guessing that line is for a desktop (I have Windows btw) but I don't seem to know where to install the right files to even execute ksud...
