### ISSUE TITLE
Install Error: Unknown KMI

### ISSUE THREAD

**Issue by Become-ILLUSORY** [tiann/KernelSU#1490]
如果内核是第三方，然后去修补原厂boot则失败，安装到另一个槽位也是如此，是否可以实现像magisk那样安装到另一个槽位时(由第三方自动恢复成被magisk修复的boot)，以及第三方可修补原厂boot

![Screenshot_2024-03-20-20-21-03-210_me.weishu.kernelsu.jpg](https://github.com/tiann/KernelSU/assets/79624137/e6c7cfb0-f3e2-4c01-ae52-8193cddb524a)

**Comment by tiann** [comment]
#1485
