### ISSUE TITLE
App profiles cant show translated strings

### ISSUE THREAD

**Issue by symbuzzer** [tiann/KernelSU#1495]
![Screenshot_20240321-092014_KernelSU](https://github.com/tiann/KernelSU/assets/9841184/62c47171-94eb-429d-90fa-b0046d270606)

Nearly all app profiles already translated to my language (Turkish) But it seems translations not work yet for app profiles

**Comment by tiann** [comment]
What is your device's language code and country code?

**Comment by symbuzzer** [comment]
@tiann Sir adaway.root still in English. All others have no problem. 
Language code: tr
Also adaway.root has tr strings
