### ISSUE TITLE
[Feature]关于"Unknown KMI" 的小建议

### ISSUE THREAD

**Issue by z1298808165** [tiann/KernelSU#1496]
### Is your feature request related to a problem? Please describe.

问题参考[1485](https://github.com/tiann/KernelSU/issues/1485)，部分用户会使用第三方内核，而第三方内核的名称可能会不符合GKI规范，因此导致管理器无法确定应该使用哪个LKM。

### Describe the solution you'd like.

增加Kernel Flasher中的检查内核版本功能，使管理器可以读取到恢复后的内核信息，这样就可以找到LKM并直接进行安装。

想法来源：用scene进行了boot还原（恢复了官方boot），发现管理器中的内核信息并没有立马更新（需要重新），但无意间使用Kernel Flasher里的当前活动插槽，并点击了检查内核版本，发现此时可以读取到恢复后的内核信息（官方核）。

### Describe alternatives you've considered.

使用scene等工具恢复官方boot或内核➡️重启➡️管理器直接安装KSU

### Additional context

![微信图片_20240321153307](https://github.com/tiann/KernelSU/assets/25720725/03b35d65-d643-463c-bdcf-ffecbfed1287)

**Comment by tiann** [comment]
现在管理器支持自己选择 LKM 文件，在右上角按钮

**Comment by z1298808165** [comment]
> 现在管理器支持自己选择 LKM 文件，在右上角按钮

哈哈好的，装了最新CI里的管理器已经看到了，但觉得相对来说用户在使用时可能还是会产生些疑问：①点击按钮是选择已经修补好的init_boot镜像还是LKM  ②LKM需要去哪里下  ③我该下哪个LKM  以及下载时可能会遇到网络问题

后面将LKM嵌入到ksud（#1472）大概也是因为很多人网络下载问题，以及方便用户的操作使用；所以我觉得如果我这个方法可行的话，可能会更方便些。哈哈哈，当然，这只是我个人的想法，最终实现还是听您的😊

**Comment by tiann** [comment]
后面会在解析 KMI 失败时，让用户自己选择 KMI；你说的这个方法是可行，但是太复杂了

**Comment by 1ulcerate** [comment]
Latest manager it patches successfully when on custom kernel, but after installing the patched img , boots without kernelSU
