### ISSUE TITLE
0.9.2版管理器中无法更新内核版本

### ISSUE THREAD

**Issue by szlaufai** [tiann/KernelSU#1499]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

机型：小米14
OS：hyperos 1.0.31
管理器版本：0.9.2(11682)
ksu 内核版本：11628
使用直接安装方式，未报错，重启后内核版本还是11628
安装日志如下：
_  __                    _ ____  _   _ 
 | |/ /___ _ __ _ __   ___| / ___|| | | |
 | ' // _ \ '__| '_ \ / _ \ \___ \| | | |
 | . \  __/ |  | | | |  __/ |___) | |_| |
 |_|\_\___|_|  |_| |_|\___|_|____/ \___/ 

- Bootdevice: /dev/block/by-name/init_boot_b
- Preparing assets
- KMI: android14-6.1
- Unpacking boot image
- Adding KernelSU LKM
- Repacking boot image
- Flashing new boot image
- Done!

### Logs

_  __                    _ ____  _   _ 
 | |/ /___ _ __ _ __   ___| / ___|| | | |
 | ' // _ \ '__| '_ \ / _ \ \___ \| | | |
 | . \  __/ |  | | | |  __/ |___) | |_| |
 |_|\_\___|_|  |_| |_|\___|_|____/ \___/ 

- Bootdevice: /dev/block/by-name/init_boot_b
- Preparing assets
- KMI: android14-6.1
- Unpacking boot image
- Adding KernelSU LKM
- Repacking boot image
- Flashing new boot image
- Done!

### Device info

- Device:小米14
- OS Version:hyperos 1.0.31
- KernelSU Version:0.9.2
- Kernel Version:6.1.25

**Comment by tiann** [comment]
0.9.2 版本的安装只适用于 LKM 模式，你需要刷回官方 boot，然后修补 init_boot。
