### ISSUE TITLE
No working initrd-magisk

### ISSUE THREAD

**Issue by dedsecproyt** [tiann/KernelSU#15]
When i updated my android x86 whith kernalsu i doesn't have access to magisk, i meen kernalsu blocks initrd-magisk

**Comment by tiann** [comment]
How did you do every step? I don't know what is inited-magisk and cannot firgure out what happened.

**Comment by tiann** [comment]
This project have no plan to keep compatible with `third-party` magisk. Please give more details, otherwise i will close this directly.

**Comment by dedsecproyt** [comment]
Im install from thith step by step `https://github.com/HuskyDG/initrd-magisk/wiki/How-to-install-initrd-magisk`, magisk loaded but no access to MagiskSU super user and Magisk Manager version

**Comment by dedsecproyt** [comment]
How to use kernalsu whith initrd-magisk ?

**Comment by tiann** [comment]
I don't know what is initrd-magisk and i have no interest making KernelSU compatible with a third-party Magisk(Official Magisk should works well).

**Comment by hmtheboy154** [comment]
> I don't know what is initrd-magisk and i have no interest making KernelSU compatible with a third-party Magisk(Official Magisk should work well).

It just an initrd for Android-x86 users to get Magisk, but I think it already fixed since this commit
https://github.com/tiann/KernelSU/commit/9aacf2a64dfe2e648131702f3fb3ccdaf53c2e79

**Comment by hmtheboy154** [comment]
![Screenshot_20221222-194952_Magisk](https://user-images.githubusercontent.com/39849246/209179699-5e0de18b-eb66-4889-bcf7-9a924b2408e0.png)
Additional info : `initrd-magisk` use official Magisk or @HuskyDG's Magisk Delta. This is official Magisk

**Comment by dedsecproyt** [comment]
> ![Screenshot_20221222-194952_Magisk](https://user-images.githubusercontent.com/39849246/209179699-5e0de18b-eb66-4889-bcf7-9a924b2408e0.png) Additional info : `initrd-magisk` use official Magisk or @HuskyDG's Magisk Delta. This is official Magisk

Im uses official magisk....
