### ISSUE TITLE
最新0.9.2使用直接直接安装后， KF无法识别boot.img

### ISSUE THREAD

**Issue by VIKINGYFY** [tiann/KernelSU#1502]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

最新0.9.2使用直接直接安装后， KF（kernel flasher）无法识别boot.img

官方版显示Invalid ramdisk in boot.img
修改版显示Invalid boot.img

- Device: 红米k60
- OS Version: MIUI 14.0.28
- KernelSU Version: v0.9.2(11682)
- Kernel Version: 
5.10.136-android12-9-gc530b6620313

**Comment by tiann** [comment]
请使用新版 KernelFlasher：https://github.com/capntrips/KernelFlasher/releases/tag/v1.0.0-alpha20

**Comment by VIKINGYFY** [comment]
> 请使用新版 KernelFlasher：https://github.com/capntrips/KernelFlasher/releases/tag/v1.0.0-alpha20

已经是新版了，就是提示Invalid ramdisk in boot.img

**Comment by tiann** [comment]
与 KernelSU 无关

**Comment by VIKINGYFY** [comment]
> 与 KernelSU 无关

之前一直是刷ak3的方式更新boot，0.9.2以后使用直接安装的方式更新之后就无法识别了，目前boot版本是11628，ksu是11682

请问一下大佬，我现在有必要刷回官方boot吗？还是继续用你提供的boot？

**Comment by tiann** [comment]
两种方法：

1. 刷回官方 boot，然后再管理器中修补，最后刷入。
2. 使用我提供的 boot。

你自行选择

**Comment by lovelyelfpop** [comment]
我也有这个问题。

我是K70 pro，因为我在fastbootd模式下运行 `fastboot flash init_boot kernelsu_patched_xxxxxxxx_xxxxx.img`，尽管显示 "Finished."，但是开机后kernelSU还是显示"未安装"。

所以我先装了Magisk，在Magisk的root环境下用 kernel flasher 1.0.0-alpha20(可正常使用)，刷了kernelSU修补的官方`kernelsu_patched_xxxxxxxx_xxxxx.img`。开机后 kernelSU 显示"工作中"，所以我就卸载掉了Magisk.apk。然后打开 kernel flasher 就报错了 "Invalid ramdisk in boot.img"（kernel flasher 有 root权限）

**Comment by YuukyuuKikan** [comment]
同样的问题所以汇报一下：
K50U，KernelSU LKM模式 11874，无magisk
KernelFlasher 1.0.0-alpha 13报告Invalid boot.img
升级到1.0.0-alpha 20报告Invalid ramdisk in boot.img

应该是兼容性问题。不过现在KSU已经提供了OTA刷写功能，KF应该用不上了。

**Comment by WOWGT1231** [comment]
机型: Redmi Note 12 Turbo
系统版本: hyperos 1.0.12.0.UMRCNXM
KernelSU 版本: 1. 0. 2(11198）
内核版本:
5.10.198-android12-9-00085-g226a9632f13d-ab11136126
A分区提示：Invalid ramdisk in boot.img
b分区提示：Invalid boot.img, no ramdisk or kernel found
具体情况如下：
![Screenshot_2024-12-10-19-22-45-107_com.github.capntrips.kernelflasher.jpg](https://github.com/user-attachments/assets/add11afe-d9f0-47e8-accd-186993e94c2a)
