### ISSUE TITLE
juicessh无法使用su

### ISSUE THREAD

**Issue by bugme2** [tiann/KernelSU#1503]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

更新到0.9.2后出现了和apatch一样的毛病，原来0.9.1以前是可以授权的
![Screenshot_2024-03-22-00-42-31-87_baaa51257c82a8b3f281ce09e6f2493f](https://github.com/tiann/KernelSU/assets/40169265/e27f904a-7044-4c0d-bbb1-85f59bf04885)
![Screenshot_2024-03-22-00-40-59-27_baaa51257c82a8b3f281ce09e6f2493f](https://github.com/tiann/KernelSU/assets/40169265/8a89e882-2cff-4405-86d4-e54f611fea04)
![Screenshot_2024-03-22-00-41-05-15_3d419158bad5872c40592a6c9956e692](https://github.com/tiann/KernelSU/assets/40169265/2744695f-cef2-4e98-9cbe-36a4af33b9b1)

### Device info

- Device:一加11
- OS Version:ColorOS13
- KernelSU Version:11682
- Kernel Version:11682

**Comment by tiann** [comment]
`/system/bin/su` 能授权吗？

**Comment by tiann** [comment]
juice 使用的是 bash shell 而非 android 的 ash，理论上可以兼容，但这样会导致其他不使用 juice 的用户在内核中运行额外的，压根就用不上的代码；因此我建议你自定义一个命令，让它执行 `/system/bin/su` 来解决这个问题。

除非有更多的 app 有这个现象，否则不考虑修复。

**Comment by bugme2** [comment]
> juice 使用的是 bash shell 而非 android 的 ash，理论上可以兼容，但这样会导致其他不使用 juice 的用户在内核中运行额外的，压根就用不上的代码；因此我建议你自定义一个命令，让它执行 `/system/bin/su` 来解决这个问题。
> 
> 除非有更多的 app 有这个现象，否则不考虑修复。

懂了，我更新替换了一下juicessh内置的bash文件后可以直接识别su命令了，原来内置的bash虽然PATH里有安卓环境的变量，但还是需要/system/bin/su才能识别，挺奇怪。

**Comment by ztc1997** [comment]
升级到0.9.4之后 `/system/bin/su`也不行了

**Comment by ztc1997** [comment]
> `/system/bin/su` 能授权吗？

升级到0.9.4之后 `/system/bin/su`也不行了
