### ISSUE TITLE
安装kernelsu后会导致调用系统webview的帧率异常

### ISSUE THREAD

**Issue by dnancheng** [tiann/KernelSU#1504]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

安装kernelsu后会导致调用系统webview的帧率异常，更新或降级系统webview版本无效

### Device info

- Device:redmi note12 turbo
- OS Version:hyper os 1.0.2.0
- KernelSU Version:11682
- Kernel Version:5.10.177

**Comment by tiann** [comment]
使用 LKM 模式应该可以解决此问题。

**Comment by dnancheng** [comment]
但是我就是LKM模式

**Comment by dnancheng** [comment]
> 使用 LKM 模式应该可以解决此问题。

已经使用lkm模式，仍然未解决

**Comment by tiann** [comment]
所以这就不是 KernelSU 的问题，你可以尝试卸载Webview的更新。

**Comment by dnancheng** [comment]
> 所以这就不是 KernelSU 的问题，你可以尝试卸载Webview的更新。

仔细重装和控制变量之后发现一安装scene的zram附加模块就会重新这个问题，这个应该向谁反馈

**Comment by hamjin** [comment]
> > 所以这不是 KernelSU 的问题，你可以尝试卸载Webview的更新。
> 
> 仔细重装和控制变量后发现安装场景的zram附加模块就可以重新这个问题，这个应该向谁反馈

点击链接加入QQ频道【SCENE7】：https://pd.qq.com/s/cmn1fb3rm
