### ISSUE TITLE
以后 GKI 内核只会为同一个 KMI 编译一个版本，建议使用 LKM 模式

### ISSUE THREAD

**Issue by 2046553272** [tiann/KernelSU#1507]
以后 GKI 内核只会为同一个 KMI 编译一个版本，建议使用 LKM 模式

_Originally posted by @tiann in https://github.com/tiann/KernelSU/issues/1505#issuecomment-2014138382_
            
因为用的三方系统，而在之前就刷了GKI内核并且没有备份原本的boot，现在电脑也不在身边流量也不够。所以能否提供一下a12-5.10.149对应的日期版本我自己fork一下修改后编译？

**Comment by 2046553272** [comment]
不好意思，没有找到那个直接回复

**Comment by tiann** [comment]
issue 不是你这样用的

**Comment by tiann** [comment]
你可以查看上个版本的源码

**Comment by 2046553272** [comment]
> 你可以查看上个版本的源码

好的，谢谢
