### ISSUE TITLE
insmod: failed to load /sdcard/android13-5.10_kernelsu.ko: No such file or directory

### ISSUE THREAD

**Issue by JuneLeo** [tiann/KernelSU#1509]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [x] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

使用insmod加载内核模块时，因为符号问题无法加载，我不确定是不是我的加载方式有问题。
是否可以提供文档。

### To Reproduce

- 1. 下载android13-5.10_kernelsu.ko
- 2. adb push android13-5.10_kernelsu.ko /sdcard/
- 3. adb shell 
- 4. su
- 5. insmod /sdcard/android13-5.10_kernelsu.ko

### Screenshots

![image](https://github.com/tiann/KernelSU/assets/22164576/059ead2d-4646-47b8-90cf-ccb4bed885a7)

### Logs

[  428.714344] kernelsu: Unknown symbol register_kprobe (err -2)
[  428.714393] kernelsu: Unknown symbol dentry_path_raw (err -2)
[  428.714410] kernelsu: Unknown symbol kern_path (err -2)
[  428.714426] kernelsu: Unknown symbol path_put (err -2)
[  428.714441] kernelsu: Unknown symbol unregister_kprobe (err -2)
[  428.714454] kernelsu: Unknown symbol kallsyms_lookup_name (err -2)
[  428.714467] kernelsu: Unknown symbol groups_free (err -2)
[  428.714480] kernelsu: Unknown symbol groups_alloc (err -2)
[  428.714491] kernelsu: Unknown symbol groups_sort (err -2)
[  428.714505] kernelsu: Unknown symbol set_groups (err -2)
[  428.714518] kernelsu: Unknown symbol path_umount (err -2)
[  428.714533] kernelsu: Unknown symbol security_hook_heads (err -2)
[  428.714545] kernelsu: Unknown symbol init_nsproxy (err -2)
[  428.714564] kernelsu: Unknown symbol filp_open (err -2)
[  428.714576] kernelsu: Unknown symbol kernel_read (err -2)
[  428.714587] kernelsu: Unknown symbol kernel_write (err -2)
[  428.714599] kernelsu: Unknown symbol strncpy_from_user_nofault (err -2)
[  428.714612] kernelsu: Unknown symbol security_secid_to_secctx (err -2)
[  428.714623] kernelsu: Unknown symbol security_release_secctx (err -2)
[  428.714632] kernelsu: Unknown symbol security_secctx_to_secid (err -2)
[  428.714643] kernelsu: Unknown symbol selinux_state (err -2)
[  428.714652] kernelsu: Unknown symbol selinux_blob_sizes (err -2)
[  428.714663] kernelsu: Unknown symbol symtab_search (err -2)
[  428.714674] kernelsu: Unknown symbol symtab_insert (err -2)
[  428.714687] kernelsu: Unknown symbol ebitmap_set_bit (err -2)
[  428.714697] kernelsu: Unknown symbol ebitmap_get_bit (err -2)
[  428.714710] kernelsu: Unknown symbol avtab_search_node (err -2)
[  428.714722] kernelsu: Unknown symbol avtab_search_node_next (err -2)
[  428.714733] kernelsu: Unknown symbol avtab_insert_nonunique (err -2)
[  428.714746] kernelsu: Unknown symbol policydb_filenametr_search (err -2)
[  428.714760] kernelsu: Unknown symbol __hashtab_insert (err -2)
[  428.714773] kernelsu: Unknown symbol avc_ss_reset (err -2)
[  428.714783] kernelsu: Unknown symbol selnl_notify_policyload (err -2)

### Device info

- Device: Pixel 6
- OS Version: Android 13
- KernelSU Version: 11682
- Kernel Version: 5.10.157-android13-4-00003

**Comment by tiann** [comment]
Expected behavior.

**Comment by intelligentpotato** [comment]
Hello @tiann.
Please elaborate on "expected behavior". I am building a kernel with ksu and experiencing exactly the same issue. Obviously it does not complete due to these errors.
