### ISSUE TITLE
How can I extract ksuinit from the Manager APK via Command Line?

### ISSUE THREAD

**Issue by newbit1** [tiann/KernelSU#1518]
Hi,

i would like to use the command line to patch an AVD ramdisk.img directly.

But it seems the ksuinit file is not extracted with the manager APK installation. It is neither in its apk dirs nor in the working dir (/data/adb/...).

How can I extract it from the manager apk? Is there an hidden command line option i'am missing? Or do I have do rename a certain file?

I can clearly see the ksuinit in the source of the arch dirs.

Thanks
NewBit

**Comment by tiann** [comment]
there isn't such interface, you can copy it from source.

**Comment by newbit1** [comment]
yeah sure, i did, but I need to implement this automated in my script. So please tell me, how can I get it out? or at least tell me where it is in the apk file. Than I can extract it myself.

Thanks

**Comment by tiann** [comment]
it's embeded in libksud.so, i don't think there is a easy way to extract it except modifying the source code and adding an interface

**Comment by newbit1** [comment]
Ok thanks, I will see.
How and when is the apk extract it?

I read the code, but I just can't find it when this is done.

**Comment by tiann** [comment]
https://github.com/tiann/KernelSU/blob/main/userspace/ksud/src/boot_patch.rs#L279

**Comment by newbit1** [comment]
> https://github.com/tiann/KernelSU/blob/main/userspace/ksud/src/boot_patch.rs#L279

Thx, I've seen this too, but I figured this asset copy function expects the ksuinit to be there already, it doesn't extract it from somewhere.
