### ISSUE TITLE
LKM修补提示分区问题

### ISSUE THREAD

**Issue by mrzzoxo** [tiann/KernelSU#1520]
首次修补 显示 init_boot ，这里应该是 boot，因为 一加 Ace2 没有 init_boot 
![image](https://github.com/tiann/KernelSU/assets/29866380/e0723d7f-bab7-416a-8b5b-11620db01e84)

刷入kernelsu后，再点修补 查看 就显示正确的 boot 了
难道是因为没有root权限 影响判断 导致提示错误显示？
![ace2-root](https://github.com/tiann/KernelSU/assets/29866380/4f4010ca-7812-41f7-a82a-789875923c07)

一加Ace2 内核是 5.10.149-Android12

虽然不影响使用   但是 这个提示 应该可以修修，或者干脆 不提示分区？😂
最新 CI 版 也是这样（应该还没人反馈这个问题？）

**Comment by tiann** [comment]
无法修复，因为你分区不规范。
