### ISSUE TITLE
【功能增强(或者安全性减弱？)】webui界面无法调用http请求

### ISSUE THREAD

**Issue by powerAn2020** [tiann/KernelSU#1521]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

![微信截图_20240324223832](https://github.com/tiann/KernelSU/assets/25736019/a31dc0a2-a144-432a-bb95-677d05edc7c5)

### To Reproduce

模块启用了zerotierOne的服务，想通过webui界面调用zerotier http api 动态修改接口信息，但报错，根据我搜索到的[信息](https://bbs.huaweicloud.com/blogs/218871)显示，高版本的webview禁用了http协议

### Expected behavior

可以调用http

### Device info

- Device: K40
- OS Version: android 13(miui14)
- KernelSU Version: 11682
- Kernel Version: 4.19.296

**Comment by tiann** [comment]
https://github.com/tiann/KernelSU/blob/main/manager/app/src/main/res/xml/network_security_config.xml

localhost 的 http 是允许的，你的问题在于，你在 https 的页面进行 http 的请求。

**Comment by powerAn2020** [comment]
> https://github.com/tiann/KernelSU/blob/main/manager/app/src/main/res/xml/network_security_config.xml
> 
> localhost 的 http 是允许的，你的问题在于，你在 https 的页面进行 http 的请求。

修改成127.0.0.1是被允许的，localhost还是不行
