### ISSUE TITLE
I can't patch a .lz4 image

### ISSUE THREAD

**Issue by ItsMadruga** [tiann/KernelSU#1522]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [x] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

My device works with boot.img.lz4, when I try to patch using lkm, it returns the following error 'magiskboot unpack failed'

### Screenshots

![Screenshot_20240317_120558_KernelSU](https://github.com/tiann/KernelSU/assets/104334266/cf559e75-8479-4cfe-a23f-3fb56685499a)

### Device info

- Device: SM-A546E
- OS Version: 14
- KernelSU Version: v0.9.2(11682)

**Comment by tiann** [comment]
you should uncompress it first.

**Comment by ItsMadruga** [comment]
I've already tried to unzip the file, and the patching part works, but as I said, my device doesn't support flashing .img, only .lz4, and when I try to compress the image again, it gives an invalid lz4 error.

@tiann
