### ISSUE TITLE
root detected (with 24 march commits)

### ISSUE THREAD

**Issue by xxjoe2** [tiann/KernelSU#1528]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [ ] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

hi

i have read about those root detected issues here and found there are a few updates and backported umount thing

desipte i have recompiled the kernel with your latest patches together with backported linux 4.9 commits, my banking app still detects root

i have renamed the image and rebooted but no luck
then i renamed the adb folder and rebooted, it still detected root

the banking app mentioned (global users with magisk reported root detection before with other versions too like US):
https://play.google.com/store/apps/details?id=com.citibank.mobile.hk

thanks

### Screenshots

![Screenshot_20240325_192022_Citibank HK](https://github.com/tiann/KernelSU/assets/83495134/3b510d96-982b-4d83-b112-ea99432a5474)

### Logs

N/A

### Device info

- Device: samsung note9
- OS Version: 13
- KernelSU Version: latest
- Kernel Version: 4.9.219

**Comment by tiann** [comment]
I can open it normally, that's nothing to do with KernelSU.

**Comment by xxjoe2** [comment]
and what about this?
![Screenshot_20240326_010720_KernelSU](https://github.com/tiann/KernelSU/assets/83495134/390b4382-a229-4ec4-a3c1-f45e11a1c103)

it happened after i update the ksu and apk, but the modules are working fine.
if i reinstall the apk (as an update), if resumes normal. however, it will change back to this after reboot. 

also  i noticed in the release notes that only GKI is supported since last update, but no more info. is it true that kernelsu will no longer work on non GKI kernel really?


thanks
