### ISSUE TITLE
xiaomi12,android12

### ISSUE THREAD

**Issue by xiaoy1988** [tiann/KernelSU#153]
sorry to bother you.
My phone is xiaomi12,android12；The bootloader is unlocked；The GKI version is 5.10.101. I've download the file : "Image-android12-5.10.101_2022-05"；
And I tried both the two files：Image、Image.lz4；Like this:
fastboot flash boot Image
fastboot reboot

fastboot flash boot Image.lz4
fastboot reboot

But It did not work?
Please help, and much grateful

**Comment by tiann** [comment]
Download the android12-5.10.101-boot-gz.img.gz from Telegram group CI channel.
