### ISSUE TITLE
WebUI on WSA

### ISSUE THREAD

**Issue by ManyullynSword** [tiann/KernelSU#1530]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

无法在WSA上打开任意模块的WebUI

### To Reproduce

-1.打开KernelSU（manager），
-2..进入模块Activity，
-3.打开任意模块的WebUI，
-4.KernelSU（manager）白屏，无法点击访问。

### Expected behavior

可以正常打开WebUI

### Device info

WSA

### Additional context

No

**Comment by crrashh1542** [comment]
正常现象，WSA的webview有问题

**Comment by ManyullynSword** [comment]
> 正常现象，WSA的webview有问题，微软去修也指望不上了ᕕ( ᐛ )ᕗ

难怪一些要联网的软件会卡住，像谷歌商店、LSPosed 和爱玩机仓库全都打不开

**Comment by ManyullynSword** [comment]
> 正常现象，WSA的webview有问题，微软去修也指望不上了ᕕ( ᐛ )ᕗ

好家伙，更新新版KSU内核后，可以正常Web Veiw（爱玩机不卡了）了，这绝不是巧合，谢谢术哥！
