### ISSUE TITLE
Please add the x86_64 LKM's as well to your releases.

### ISSUE THREAD

**Issue by newbit1** [tiann/KernelSU#1533]
Dear @tiann ,

i managed to add the ksuinit and the LKM to the AVDs ramdisk.

But the Kernel log conplaines about the wrong architectur of the module and can't load it.

It seems the provided LKM's on the release page are exclusiv arm or rather aarch64.

So could you please add the x86_64 LKM's to your release page as well?

Also, can you tell when you will release the AVD kernels? I tried the ones from the action workflows and they boot up right away.

Thanks
NewBit

**Comment by tiann** [comment]
avd kernel is not GKI, you must compile exactly the same version with the AVD, so we won't release avd kernels.

as for LKM, we may do it, you can copy the workflows and try first.

**Comment by tiann** [comment]
`build-lkm.yml` is the workflow to build LKM

**Comment by newbit1** [comment]
> `build-lkm.yml` is the workflow to build LKM

there are only the aarch64 LKM's in it,
but not the x86_64.

**Comment by tiann** [comment]
we never build x86_64 before, you should modify it

**Comment by newbit1** [comment]
ah ok I see, yeah I can't and further more, won't do that. I would like to stay with the official state of ksu. So my rootavd script users can have the up-to-date versions of ksu. It just doesn't makes sense, to have a ksu version besides the official one.

That is why asked you to add these arch and AVD kernel as well to the release.

So both emulator types can work with ksu. Ideally with both modes, kernel replacement and LKM.

Well I must say, I presume you just have to switch to another target and it will build. I don't want you to rewrite your code, just to have it compatible with AVDs. This would be way to much effort.

Thanks
