### ISSUE TITLE
system storage shows 1.1tb after flahing multiple modules in ksu

### ISSUE THREAD

**Issue by spidy2356** [tiann/KernelSU#1539]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

whenever I flash multiple module (almost 5...6), after reboot my system storage shown as 1.1 TB. and after disable extra modules and reboot it back to normal.

### Expected behavior

even if I flash multiple modules, system storage should be approx 7gb and total storage should be shown as 64gb. (54gb usable)

### Screenshots

![Screenshot_20240326-224654_Settings](https://github.com/tiann/KernelSU/assets/101243689/3ca8de30-5793-4abd-8d37-7f868b0ea173)
![Screenshot_20240326-224444_KernelSU](https://github.com/tiann/KernelSU/assets/101243689/3b939d06-778a-400b-938f-5628641aa54c)

### Logs

[KernelSU_bugreport_2024-03-26_22_47.tar.gz](https://github.com/tiann/KernelSU/files/14762297/KernelSU_bugreport_2024-03-26_22_47.tar.gz)

### Device info

- Device: poco x2
- OS Version: android 13 ( custom rom: alphadroid v1.10)
- KernelSU Version: manager version- v0.9.2 (11682)
- Kernel Version: 4.14.336-paradox-v7.0-EOL-ksu

### Additional context

I found other issue related to this and there dev says will fixed on v0.8.2 but didn't fixed yet for me. and those issue r too old (almost 1month), so I create issue again. thanks you, hope I will find a solution

**Comment by Fede2782** [comment]
https://kernelsu.org/guide/faq.html#why-does-my-device-show-wrong-storage-size

**Comment by tiann** [comment]
#1419
