### ISSUE TITLE
oppo pad2 这个设备有init_boot分区 但是没用 要用boot

### ISSUE THREAD

**Issue by xiaolinqing** [tiann/KernelSU#1541]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

oppo pad2 这个设备有init_boot分区 但是没用 要用boot   ksu默认init_boot无法安装

### Screenshots

![Screenshot_2024-03-27-12-23-59-25_baaa51257c82a8b3f281ce09e6f2493f](https://github.com/tiann/KernelSU/assets/87248741/61a8e3d9-0575-41d8-b3bc-277378cb6e5f)

### Logs

[KernelSU_bugreport_2024-03-27_12_16.tar.gz](https://github.com/tiann/KernelSU/files/14767445/KernelSU_bugreport_2024-03-27_12_16.tar.gz)
[KernelSU_install_log_2024-03-27-12-15-26.zip](https://github.com/tiann/KernelSU/files/14767479/KernelSU_install_log_2024-03-27-12-15-26.zip)

### Device info

- Device:OPD2201
- OS Version:14.0
- KernelSU Version:0.9.2（11682）
- Kernel Version:5.10.168-android 12-9-o-gce7e5093e0fb

**Comment by tiann** [comment]
你这种我没法修复的，我怎么知道一个设备用 init_boot 但是不用的情况？你只能自己手动来

**Comment by xiaolinqing** [comment]
绿厂的（别的厂家不太清楚）
天玑8000/8100/9000
这几个没有init_boot，但是他觉得你有
当时magisk就有这个问题（26.4）
