### ISSUE TITLE
internal storage increase to 1TB on ONEPLUS after installing module 

### ISSUE THREAD

**Issue by mananbhatt86** [tiann/KernelSU#1544]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

After enabling zygisk lsposed and zygisk next the storage size increase to 1tb. I am using Android 15 oxygen OS OnePlus 11 device.

### Expected behavior

After adding modules storage size should be shown actual and not in TB

### Screenshots

![Screenshot_2024-03-27-15-23-10-19_baaa51257c82a8b3f281ce09e6f2493f](https://github.com/tiann/KernelSU/assets/13099363/2a7700f8-d687-433f-9498-8613558076eb)

### Device info

- Device: OnePlus 11
- OS Version: 14
- KernelSU Version: 0.9.2
- Kernel Version: 5.15.123
![Screenshot_2024-03-27-15-27-34-05_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/tiann/KernelSU/assets/13099363/9e290934-80a4-4c87-9f5d-39b6796f056f)

**Comment by rsuntk** [comment]
A few device has a problem when reading a [sparse file](https://en.wikipedia.org/wiki/Sparse_file)

**Comment by tiann** [comment]
#1419
