### ISSUE TITLE
I can't find the my boot.img from [GitHub Release]. 5.10.177 not find Android Security version 2024-03-01

### ISSUE THREAD

**Issue by nEdAy** [tiann/KernelSU#1550]
### Describe your problem.

I can't find the my boot.img from [GitHub Release](https://github.com/tiann/KernelSU/releases)
such as android12-5.10.177_2024-03-boot.img.gz

My device info:
Kernel version -> 5.10.177-android12-9-00001-g219d8dfbba07-ab10551810
Android version
14 | Android security update: 2024-03-01

**Comment by Fede2782** [comment]
Which is your device? In any case you should see Kernel security patch tag not Android platform. Pure GKI android12-5.10.177 has been tagged as 2023-07 security patch.

**Comment by tiann** [comment]
read docs

**Comment by nEdAy** [comment]
> Which is your device? In any case you should see Kernel security patch tag not Android platform. Pure GKI android12-5.10.177 has been tagged as 2023-07 security patch.

Thanks for reply.
My device is Redmi K60 that security patch is March 1, 2024.
So i can use the Pure GKI android12-5.10.177 tagged as 2023-07 security patch?
