### ISSUE TITLE
掉root的情况下，如何删除kernelsu的模块？

### ISSUE THREAD

**Issue by Li-Qifeng** [tiann/KernelSU#1556]
我刷入一个模块后重启，成功进入系统但系统界面卡住无法操作，由于是自行修补的非gki内核，无法触发救砖机制，遂刷入原版boot后成功开机，但data目录下无adb文件夹，又尝试刷入修补boot，刷入后系统界面依旧卡住无法操作（意味着模块还在），请问这种情况下，有什么办法能够删除kernelsu的模块？

**Comment by bugme2** [comment]
不是有安全模式么...
或者twrp删除/data/adb，没有twrp就用面具或者apatch授权删，之后再转回ksu

**Comment by Li-Qifeng** [comment]
> 不是有安全模式么...
> 或者twrp删除/data/adb，没有twrp就用面具或者apatch授权删，之后再转回ksu

自行修补的非gki内核，应该是没有集成安全模式相关的代码，触发不了；
twrp也找不到adb文件夹，可能是没解锁data分区；
尝试了一下转apatch，成功解决了，谢谢！

**Comment by zhangguanzhang** [comment]
我twrp进/data/adb/后删掉modules重启就行了
