### ISSUE TITLE
[Custom] 功能更新｜360加固保新增KernelSU防御功能

### ISSUE THREAD

**Issue by google-mirror** [tiann/KernelSU#1557]
### Describe your problem.

360加固保引入了针对[KernelSU](https://github.com/tiann/KernelSU)方案的防御机制，经过大量测试，能准确地检测出手机是否采用了该root方案，可在企业版加固套餐中使用KernelSU防御功能，如有需要欢迎咨询在线客服或联系邮箱360jiagubao@360.cn。

**Comment by tiann** [comment]
？

**Comment by weirenren** [comment]
好奇，360怎么实现检测的🤔

**Comment by google-mirror** [comment]
> 好奇，360怎么实现检测的🤔

黑科技, 技术机密
