### ISSUE TITLE
某种条件下,管理器首页会提示"获取 root 失败!"

### ISSUE THREAD

**Issue by iKun4real** [tiann/KernelSU#1559]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

管理器首页提示"获取 root 失败!",模块数显示为0,但是实际功能正常,只是显示错误,后台清掉管理器重新打开则显示正常.

### To Reproduce

1. 装有Zygisk-Next模块,且打开web控制页面
2. 退回桌面或者切到其他APP,保持几分钟
3. 切回到KSU管理器,此时还是Zygisk-Next管理页面,退出并回到KSU管理器首页,此时会出现"获取 root 失败!"提示

### Screenshots

![318004587-e506a7e8-06fc-457f-8560-606d344fcf07](https://github.com/tiann/KernelSU/assets/24572324/2002983b-4612-4fb4-9cd1-6194372a1855)
![318004618-7c77c9b8-5f76-4197-b7c6-bdcb33d60638](https://github.com/tiann/KernelSU/assets/24572324/4426a293-58cf-4f08-bf85-44ec2582331b)

### Device info

- Device: OnePlus ACE3
- OS Version: ColorOS14(505)
- KernelSU Version: 11682
- Kernel Version: 5.15.94-android13

**Comment by tiann** [comment]
日志
