### ISSUE TITLE
RCS messages are not working 

### ISSUE THREAD

**Issue by himanu01** [tiann/KernelSU#1560]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

RCS messages are not working although Play integrity is passing 

### Device info

- Device: Redmi Note 8
- OS Version: Evolution x 8.3
- KernelSU Version: 0.9.2
- Kernel Version: 4.14.336

**Comment by osm0sis** [comment]
Not a KSU-specific issue: https://github.com/chiteroman/PlayIntegrityFix/issues/297
