### ISSUE TITLE
Add a basic terminal function in KSU [Feature]

### ISSUE THREAD

**Issue by iJahangard** [tiann/KernelSU#1561]
### Is your feature request related to a problem? Please describe.

Some modules need a basic command line interface to preform specific functions
Besides it always good if you have a secure terminal right in your root manager to do specific functions

### Describe the solution you'd like.

A basic terminal with support of su in it
Also it's better if there would be a bar with extra functions buttons

### Describe alternatives you've considered.

As i said!

**Comment by tiann** [comment]
Should we also add a root file manager? Should we add also root related function?
