### ISSUE TITLE
[Feature] Show Download Progress When Updating a Module

### ISSUE THREAD

**Issue by CanerKaraca23** [tiann/KernelSU#1566]
### Is your feature request related to a problem? Please describe.

No.

### Describe the solution you'd like.

Show download progress when updating a module on notification center or in manager.

### Describe alternatives you've considered.

-

**Comment by TinyHai** [comment]
if you want to know the progress of downloading, the downloader of system must be showing a notification while something is downloading.
if it's not, try to check if you grant notification permission to downloader.
