### ISSUE TITLE
在KSU最新的main分支版本出现了管理器没有找到KSU的问题

### ISSUE THREAD

**Issue by SCP-xiao-q** [tiann/KernelSU#1570]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

我在使用我在编译好最新的main版本(11747)的KernelSU后，刷入进手机
出现了如截图所示的情况，管理器没有发现KSU，但实际上我编译的内核已经添加ksu
管理器虽然没有发现ksu，但在未更新到11747的版本前(11563)是正常使用的
上个版本(11563)留下了的ROOT授权仍在，模块也正常使用。（我在频道里发过了，您应该记得我吧xwx）
我上传了log和管理器日志

### To Reproduce

1，刷入11747版本的kernel
2，下载安装并打开最新的Cl管理器
3，发现管理器没有发现ksu

### Screenshots

![IMG_20240331_225636_100](https://github.com/tiann/KernelSU/assets/96773038/21f1d00b-41c8-44e2-83df-dcf554cd2e6e)

### Logs

[log.zip](https://github.com/tiann/KernelSU/files/14816400/log.zip)
[KernelSU_bugreport_2024-03-31_22_35.tar.gz](https://github.com/tiann/KernelSU/files/14816401/KernelSU_bugreport_2024-03-31_22_35.tar.gz)

### Device info

- Device:Redmi Note 9 Pro
- OS Version:MIUI 14.0.2
- KernelSU Version:11747
- Kernel Version:4.19.113-android12

### Additional context

该机型的kprobe工作不正常

**Comment by androiddisk** [comment]
同样的情况

**Comment by tiann** [comment]
再拉一下最新的代码试一下。

**Comment by SCP-xiao-q** [comment]
> 再拉一下最新的代码试一下。

好的，但现在在做清明，等我有时间先awa

**Comment by SCP-xiao-q** [comment]
> @SCP-xiao-q Kprobe 不好用你先试试手动修改啊，另外，你的Kprobes没开，你再看一下内核编译选项。
> 
> ![image](https://private-user-images.githubusercontent.com/74451279/319064247-543df09e-1e67-45f7-ae18-0d395f469088.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMDI1MTUsIm5iZiI6MTcxMjIwMjIxNSwicGF0aCI6Ii83NDQ1MTI3OS8zMTkwNjQyNDctNTQzZGYwOWUtMWU2Ny00NWY3LWFlMTgtMGQzOTVmNDY5MDg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDAzNDMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyMmU0Y2EzYWZkMWU3ZjdhNmQ3MDFiYTA0OTk3MDFiNTU2MTYwZDk0MzUyOTFiMzI0NjM5NjcwYzk4MjY4ZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1p1x-BndC9J8JUzh9o7rffmy0AElEBgM_1krv8yqahc)

emmmm，我就是手动修改的，内核源码在本地操作xwx
