### ISSUE TITLE
modules.img file size

### ISSUE THREAD

**Issue by xxjoe2** [tiann/KernelSU#1572]
hi

ok, i believe you have reasons to use a sparse file to hold the modules. however, i 
just wonder why you decided to make a 1T (and incerased from 256T) sparse file to hold them. do we really need to init a 1T sparse file in the first place?

this sparse file is way too large and causes a few problems, eg:
- normal users wont be able to deal with this huge sparse file, eg to do a backup, many of them dont use cli (xcp)
- just tested, twrp wont be able to do a data partition backup because the detected partition size was 1xxxxxxMB
- i also performed a test and use tar (sparse file supported) in the recovery (ksud not working under recovery) to tar the adb folder, and it took more than an hour to finish
- although the img can be removed, users have to reinstall all the modules after that

and since a new img will be created every time there are changes to the existing modules, so why do we increase the size of the sparse file at this time when needed? i would suggest to create a much smaller file first, say 500mb, and then increase the file size when needed after a module is installed. a 500mb image is more than enough to hold many modules

what do you think?

**Comment by tiann** [comment]
The previous versions used to increase in size during installation, but many modules would self-extract and download content from the internet, making it difficult to determine how much to increase. This resulted in many module installation failures.

In addition, the expansion process takes a lot of time, which leads to a slow module installation process; frequent expansion also increases the likelihood of image file damage.

If you want to backup, you can go to the settings and select "Minimize module image" now.

**Comment by xxjoe2** [comment]
ok, i see. thank you

but where is the Minimize module image setting? i found in your strings.xml but couldnt find it in the app

**Comment by tiann** [comment]
Settings - Minimize Image file

**Comment by xxjoe2** [comment]
no such option, v0.92

**Comment by xxjoe2** [comment]
alright, i changed the font size and now the options at the boottom are now visible. that is, this is a bug for not scrollable (the first page too)



anyway, now i can see all the options but still no minimize image size option

**Comment by mt190502** [comment]
> Settings - Minimize Image file

I encountered a similar problem today. But I couldn't find this setting.
