### ISSUE TITLE
在安卓14上KSU无法正常修补内核

### ISSUE THREAD

**Issue by AMWss** [tiann/KernelSU#1573]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

机型：Redmi K50 Ultra
安卓14
HyperOS
KSU状态：给予了所有请求的权限
问题：报错Not Match Found
![Screenshot_2024-04-01-16-09-06-438_me weishu kernelsu](https://github.com/tiann/KernelSU/assets/100455586/0efadf4d-d5b0-4f3a-8d56-dda8dcbed7c4)
该问题在以下图选择右上角图标选择目标img后解决，但处理后的img并没有生效，刷入后无法获得root
![Screenshot_2024-04-01-16-15-56-773_me weishu kernelsu](https://github.com/tiann/KernelSU/assets/100455586/7e19ac99-6a80-4fca-a645-54f12bf04b52)
但是我通过在rec里修改/sdcard/Download/boot.img的权限为0777后开机正常修补，并且修补后的img是有效的，刷入后成功获得权限
而且似乎这也会影响在root环境下直接安装的功能
![Screenshot_2024-04-01-16-18-47-960_me weishu kernelsu](https://github.com/tiann/KernelSU/assets/100455586/905fafc5-7d97-4c63-8619-73b707e1d1fe)
我会尝试上传ksu日志至123网盘或者通过邮件，但是其他网盘我可能不行，其中123网盘若是无法网页下载，注册一个账号登录即可直接网页下载，若是需要邮件发送，请备注一下，然后发一下邮箱，我发给您

### To Reproduce

无

### Expected behavior

加入申请完全访问并管理所有文件权限以保证修补内核正常运行

### Device info

- Device:红米K50至尊
- OS Version:14
- KernelSU Version:0.9.2
- Kernel Version:LKM working on 5.10.198

**Comment by tiann** [comment]
你应该是使用了自定义内核，它的内核名字不符合 GKI 规范，你需要手动修补；请先查阅文档。

**Comment by AMWss** [comment]
> 你应该是使用了自定义内核，它的内核名字不符合 GKI 规范，你需要手动修补；请先查阅文档。

emm其实不是，因为我在测试过程中也用了原厂的内核，小米官方boot，也是报同样的错，所以排除内核名字的问题

**Comment by AMWss** [comment]
> 你应该是使用了自定义内核，它的内核名字不符合 GKI 规范，你需要手动修补；请先查阅文档。

并且我通过在rec里修改了目标文件的权限到777后，虽然不清楚它如何工作的但是它的确成功修补了
