### ISSUE TITLE
最新代码中 $(pm path me.weishu.kernelsu | cut -d':' -f 2 | xargs dirname)/lib/arm64/libksud.so debug su 无法再使用

### ISSUE THREAD

**Issue by androiddisk** [tiann/KernelSU#1577]
### Describe your problem.

https://github.com/tiann/KernelSU/commit/e1f9900b2f89e4e150c1353f4878657b54639625

```
	bool from_root = 0 == current_uid().val;
	bool from_manager = is_manager();

	if (!from_root && !from_manager) {
		// only root or manager can access this interface
		return 0;
	}
```

这么做的话 ` $(pm path me.weishu.kernelsu | cut -d':' -f 2 | xargs dirname)/lib/arm64/libksud.so debug su `就不能使用了

**Comment by tiann** [comment]
预期行为，不再需要这个了。
