### ISSUE TITLE
[Feature] 能否在一个non-GKI的集成KernelSU的内核上通过LKM安装新版KernelSU？

### ISSUE THREAD

**Issue by txmu** [tiann/KernelSU#1588]
### Is your feature request related to a problem? Please describe.

LKM安装法对KSU是个伟大的发明。
正如KernelSU官网所提到的：
> 不会替换掉设备原有的内核；如果你对设备原有的内核有特殊需求，或者你希望在使用第三方内核的同时使用 KernelSU，可以使用 LKM 模式

下面提到，当同时使用GKI和LKM时GKI优先级更高， **但对于集成KSU的非GKI内核来说，该点是否同样适用？**  如果不适用，那么能否如标题所说的：通过这种方法更新KSU？

（官网提到了可以通过管理器和一个命令行工具来安装LKM的KSU，在通过管理器尝试时，它会直接提醒我“版本过低”，而不会出现安装按钮）

如果并不可以，那么， **先使用Magisk/APatch/SKRoot（不包括Dirtypipe这种）之类方法获取Root权限，然后安装LKM的KSU，请问这是否可行？** 

### Describe the solution you'd like.

可以通过管理器或命令行在旧版本的non-GKI KSU内核上安装LKM的新KSU，或者退而求其次地：在使用了Magisk/APatch/SKRoot等其他方案的基础上通过类似以上的方法安装新版本的KSU。（Magisk与KSU存在的兼容问题我清楚）
以上只是一个理论上的问题想要求教作者，并不是一个严格意义上的特性请求，也不需要您提供任何相关文档或官方技术支持，只是需要一个理论上可行与否的答复。

### Describe alternatives you've considered.

以上已描述过，即采用Magisk/APatch/SKRoot先取得Root，再安装LKM的KSU
以及：请问这种情况下LKM的KSU能否脱离该boot原有的root方案而独立存在？
（设备安卓版本：Android 11）

**Comment by tiann** [comment]
不能

**Comment by txmu** [comment]
> 不能

那请问上文描述的 退而求其次的替代方案呢？

**Comment by tiann** [comment]
男人不会因为穿了女装就变得可以生孩子了

**Comment by txmu** [comment]
> 男人不会因为穿了女装就变得可以生孩子了

感谢大佬，懂了，就是说通用的LKM方案并不适用于non-GKI内核。
