### ISSUE TITLE
AirMusic magisk module fails with KernelSU

### ISSUE THREAD

**Issue by meiser79** [tiann/KernelSU#1594]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

I use [AirMusic](https://play.google.com/store/apps/details?id=app.airmusic.pro) which needs a magisk module to be able to stream music from all apps.
This module crashes when used with KernelSU, but not with Magisk 27.0. It can be downloaded [here](https://xdaforums.com/t/module-updated-airaudio-system-audio-mode.3753580/post-88410397).

May I ask you to have a look? The logcat output of the exception is below.

BTW, it's also reproducable with a GKI based smartphone (Xiaomi 12T Pro running crDroid 10.2 with HyperOS kernel) in LKM mode.

Thanks a lot,
meiser79

### Expected behavior

The module should work the same as with Magisk 27.0.

### Logs

[module-crashlog.txt](https://github.com/tiann/KernelSU/files/14887476/module-crashlog.txt)

[KernelSU_bugreport_2024-04-05_18_00.tar.gz](https://github.com/tiann/KernelSU/files/14887435/KernelSU_bugreport_2024-04-05_18_00.tar.gz)

### Device info

- Device: Xiaomi Poco F3
- OS Version: crDroid 9.15 (Android 13)
- KernelSU Version: 11747 (kernel), 11756 (manager)
- Kernel Version: 4.19.311

**Comment by tiann** [comment]
Disable “Umount modules by Default” in KernelSU manager's Settings and try again.

**Comment by meiser79** [comment]
Yes, this works, thanks for the hint. But to be honest, it's not yet clear to me how this unmount works. Why is only this airmusic module affected even though some other modules are not (e.g. [magisk ssh module](https://gitlab.com/d4rcm4rc/MagiskSSH))?

**Comment by tiann** [comment]
If there is an app that needs to use a module mounting file, you need to pay attention to this option. You can either turn it off globally or turn it off for a specific app.

**Comment by meiser79** [comment]
As the airmusic app also has root permission, it should see the magisk module even when not using the "Umount modules by Default" option.
It's not yet clear to me why the app which mounted and started by the magisk module crashes the whole time.

**Comment by meiser79** [comment]
@tiann May I ask you to shed some light on this issue? As mentioned, it's not yet clear to me why the app crashes the whole time.

**Comment by reyqn** [comment]
@meiser79 you should allow root for AMRSCService app in kernelsu
