### ISSUE TITLE
Storage misrepresentation 

### ISSUE THREAD

**Issue by realravipandit** [tiann/KernelSU#1595]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

The bug is that the storage system get messed with these ksu version upto 0.7.2 it was all correct but after that it got damaged. I have a device of 8 GB Ram and 128 GB of rom but it is showing total storage of 2tb and out if which 1.9tb is already full so I kindly request you to look into this problem as already this is and made many thing possible . I have asked for help from the devs of kernel , rom and in even official support channels of my device that is poco f4. I have attached an screenshot here so u can have a view
![Screenshot_2024-04-06-05-50-59-837_com android settings](https://github.com/tiann/KernelSU/assets/66828032/debbe337-6e05-4956-ad36-bdb3e090ffd2)
![Screenshot_2024-04-06-05-51-12-964_com miui securitycenter](https://github.com/tiann/KernelSU/assets/66828032/1f4a3099-d678-4f80-8720-cc030a49a0e4)

### To Reproduce

1.open setting of device 
2.click on about phone
3.click on storage 

### Expected behavior

It should show correct storage amount:- total or available

### Screenshots

`
![Screenshot_2024-04-06-05-50-59-837_com android settings](https://github.com/tiann/KernelSU/assets/66828032/0c2e9c86-0f7c-4229-9520-9d7f99e44560)
![Screenshot_2024-04-06-05-51-12-964_com miui securitycenter](https://github.com/tiann/KernelSU/assets/66828032/f174e162-fd6c-4212-82e0-dd7a943f9712)
![Screenshot_2024-04-06-05-50-59-837_com android settings](https://github.com/tiann/KernelSU/assets/66828032/00eccb6f-f72e-42c5-8c4e-df5b49840e15)
`

### Device info

- Device:Poco f4
- OS Version: miui 14.0.8(India)
- KernelSU Version:0.9.2
- Kernel Version:realking 15.4(4.19.308)

**Comment by meiser79** [comment]
#1419, #1544, #1572, and many more.

https://kernelsu.org/guide/faq.html#why-is-there-a-huge-1-tb-file

**Comment by xmicro** [comment]
I have the opposite issue where my 512 GB goes down to 8 GB and I can't save anything... And some of my apps crash due to libpairipcore. Only happens after a day or so after a reboot.

**Comment by Yeshey** [comment]
@xmicro I think I might be experiencing something similar. My system files say they're using all the space, and I'm already getting out of space warnings even tho i should still have space available. I'm in android 15 CRdroid custom ROM on 128GB Samsung A70.

<img width="441" height="940" alt="Image" src="https://github.com/user-attachments/assets/a45b5b37-02b8-4d2b-b74e-53fc829403dd" />

<img width="1080" height="2306" alt="Image" src="https://github.com/user-attachments/assets/a2605ec7-d59e-4240-a77f-acfb2b039f74" />.

A reboot fixes it for me for a couple days.
