### ISSUE TITLE
卡顿并可能会闪退

### ISSUE THREAD

**Issue by huanlu233** [tiann/KernelSU#1596]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

在0.92版本（redmi note12 pro）的ksu app中，出现掉帧的情况，使用感受很难受，在超级用户界面，搜索和启用某个软件的超级用户权限会卡住，并且有极大概率会闪退，导致我无法给某个软件的超级用户权限

### Device info

- Device:
- OS Version:
- KernelSU Version:
- Kernel Version:
红米note12 pro
澎湃官方版本1.0.2.0
0.92
5.10.177

**Comment by tiann** [comment]
请你先检查安装的其他模块，确保这是 KernelSU 导致的；我不认为 KernelSU 本身的代码会导致卡顿或者闪退。
