### ISSUE TITLE
无法安装模块

### ISSUE THREAD

**Issue by liboxuanzs** [tiann/KernelSU#1597]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

一安装模块就是这个样子，安装不了。已经重装了好几遍内核了，还是不行。是编译的内核的问题吗？还是其他的。
![af5f40271010ae58292a32c20e879f2](https://github.com/tiann/KernelSU/assets/108216103/77aaafc8-bc53-433d-ba8e-88fdb3c3c542)

### Logs

[KernelSU_install_log_2024-04-07-16-40-14.log](https://github.com/tiann/KernelSU/files/14896514/KernelSU_install_log_2024-04-07-16-40-14.log)

### Device info

- Device:redmi note 12 turbo
- OS Version:hyperos 1.0.2.0
- KernelSU Version:v0.9.2
- Kernel Version:5.10.177

**Comment by tiann** [comment]
删掉 `/data/adb/ksu` 目录重来
