### ISSUE TITLE
KernelSU on WSA

### ISSUE THREAD

**Issue by Schefflin** [tiann/KernelSU#1605]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Thank you for your work:
https://github.com/tiann/KernelSU/actions/runs/8534287672
kernelSU worked, but there is new problem: when WSA start running, those 'kernel' files will cause "COM Surrogate(which is under WSA)" occupying highly cpu and WSA will be killed automatically about ten minutes if you don't open any app.

### To Reproduce

https://github.com/tiann/KernelSU/actions/runs/8534287672
to replace /WSA/Tools/kernel

### Device info

- Device:MSI GF63 Thin 10SCSR
- OS Version:windows11
- KernelSU Version:0.92
- Kernel Version:5.15.104

### Additional context

WSA_LTS1_KernelSU

**Comment by Schefflin** [comment]
> ### Please check before submitting an issue
> * [x]  I have searched the issues and haven't found anything relevant
> * [x]  I will upload bugreport file in KernelSU Manager - Settings - Report log
> * [ ]  I know how to reproduce the issue which may not be specific to my device
> 
> ### Describe the bug
> Thank you for your work: https://github.com/tiann/KernelSU/actions/runs/8534287672 kernelSU worked, but there is new problem: when WSA start running, those 'kernel' files will cause "COM Surrogate(which is under WSA)" occupying highly cpu and WSA will be killed automatically about ten minutes if you don't open any app.
> 
> ### To Reproduce
> https://github.com/tiann/KernelSU/actions/runs/8534287672 to replace /WSA/Tools/kernel
> 
> ### Expected behavior
> _No response_
> 
> ### Screenshots
> _No response_
> 
> ### Logs
> _No response_
> 
> ### Device info
> * Device:MSI GF63 Thin 10SCSR
> * OS Version:windows11
> * KernelSU Version:0.92
> * Kernel Version:5.15.104
> 
> ### Additional context
> WSA_LTS1_KernelSU

@tiann @MustardChef 
Ok, I open an app, like "file", waiting for a long time, WSA would not be kill, and 'com surrogate' return normal, BUT it really take quite while……

**Comment by MustardChef** [comment]
> > ### Please check before submitting an issue
> > * [x]  I have searched the issues and haven't found anything relevant
> > * [x]  I will upload bugreport file in KernelSU Manager - Settings - Report log
> > * [ ]  I know how to reproduce the issue which may not be specific to my device
> > 
> > ### Describe the bug
> > Thank you for your work: https://github.com/tiann/KernelSU/actions/runs/8534287672 kernelSU worked, but there is new problem: when WSA start running, those 'kernel' files will cause "COM Surrogate(which is under WSA)" occupying highly cpu and WSA will be killed automatically about ten minutes if you don't open any app.
> > 
> > ### To Reproduce
> > https://github.com/tiann/KernelSU/actions/runs/8534287672 to replace /WSA/Tools/kernel
> > 
> > ### Expected behavior
> > _No response_
> > 
> > ### Screenshots
> > _No response_
> > 
> > ### Logs
> > _No response_
> > 
> > ### Device info
> > * Device:MSI GF63 Thin 10SCSR
> > * OS Version:windows11
> > * KernelSU Version:0.92
> > * Kernel Version:5.15.104
> > 
> > ### Additional context
> > WSA_LTS1_KernelSU
> 
> @tiann @MustardChef 
> Ok, I open an app, like "file", waiting for a long time, WSA would not be kill, and 'com surrogate' return normal, BUT it really take quite while……

It would be helpful to the developer if you build WSA via the MagiskOnWSALocal script and check if the issue occurs with that and then provide full reproduction including video recordings and logs.

**Comment by Schefflin** [comment]
> It would be helpful to the developer if you build WSA via the MagiskOnWSALocal script and check if the issue occurs with that and then provide full reproduction including video recordings and logs.

On WSA_LST2, just turn off "advanced settings" -- "share userfile", the problem won't happen. Anyway, thanks for your job.
