### ISSUE TITLE
ksu manager detected by banking app

### ISSUE THREAD

**Issue by xxjoe2** [tiann/KernelSU#1610]
hi

i have compiled 2 linux 4.9 kernels, one with ksu and one without

with ksu/manager, citibank app detected root, while without both of them the app could be opened without problem

with the non ksu version running without the manager, i successfully started the citibank app. i then closed it and installed the ksu manage without any module, and reopened the banking app again, root detected

next i uninstalled the manager and flashed the kernel with ksu. i could open the citibank app without problem

as a result, there are 2 possibilities:
1 it detects your manager's app name, and/or
2 it detects the adb mount point (i didnt check for the mount point nor the manager's implementation, may be you will know more)

i suggest to implement a magisk manager like feature to allow users to rename the manager app name asap, since ultimately it will be counted as root, not only for linux 4.9

also note that i have tried to install hide app name module but it failed too

thanks

**Comment by meiser79** [comment]
#628

**Comment by xxjoe2** [comment]
sorry i dont quite understand

you "suggest" not to use the manager, so i try the ksud command but i couldnt find a way to add or remove package to obtain su permission. is there any guide for adding packages to the allow list? if not, we still need the manager to grant su permission, rite?

**Comment by meiser79** [comment]
It's not about not using the manager app. The advice is to either freeze it (e.g. with [IceBox](https://play.google.com/store/apps/details?id=com.catchingnow.icebox)) or uninstall it as long as you don't need it.
