### ISSUE TITLE
[Feature] 能否解压并安装随机密码的zip模块

### ISSUE THREAD

**Issue by 2046553272** [tiann/KernelSU#1615]
### Is your feature request related to a problem? Please describe.

![Screenshot_2024-04-11-19-54-20-033_me weishu kernelsu](https://github.com/tiann/KernelSU/assets/70498814/e7cf8d71-c536-46f9-b6a4-d7904d5d4045)
![Screenshot_2024-04-11-19-49-44-237_bin mt plus](https://github.com/tiann/KernelSU/assets/70498814/f2b99591-6cf6-4bbb-a27a-9c37dcdcc2b9)
这种加了密码的模块无法正常安装

### Describe the solution you'd like.

希望像magisk那样能安装这种带密码的模块(作者说是随机密码)

### Describe alternatives you've considered.

可以试试像橙狐rec那样绕过密码解压？

**Comment by yujincheng08** [comment]
magisk 也不支持带密码的 zip 啊

**Comment by 2046553272** [comment]
> magisk 也不支持带密码的 zip 啊

关键这个带密码的模块就可以用magisk刷进去

**Comment by 2046553272** [comment]
> magisk 也不支持带密码的 zip 啊

magisk是可以刷入的，可以看看这个网盘的视频，刚刚录的

www.alipan.com/s/3EwjjCx6wnK

**Comment by 2046553272** [comment]
> magisk 也不支持带密码的 zip 啊

看看这个视频，是能正常刷入，但用文件管理器打开怎么就都要密码。而ksu刷入就抱上面的那个错误

VID_20240415_025426.mp4
https://www.alipan.com/s/zwo2xfwrz1W
点击链接保存，或者复制本段内容，打开「阿里云盘」APP ，无需下载极速在线查看，视频原画倍速播放。

**Comment by 2046553272** [comment]
> > magisk 也不支持带密码的 zip 啊
> 
> 看看这个视频，是能正常刷入，但用文件管理器打开怎么就都要密码。而ksu刷入就抱上面的那个错误
> 
> VID_20240415_025426.mp4 https://www.alipan.com/s/zwo2xfwrz1W 点击链接保存，或者复制本段内容，打开「阿里云盘」APP ，无需下载极速在线查看，视频原画倍速播放。

目前解决方法是转magisk安装后在移动出来然后刷ksu后在移动到ksu的模块目录下，但这样太麻烦了
