### ISSUE TITLE
安装模块显示 specified file not found in archive

### ISSUE THREAD

**Issue by Boom-Hacker** [tiann/KernelSU#1621]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

安装模块显示 specified file not found in archive

### To Reproduce

刷入此模块 https://mhtqqwx.lanzoul.com/iAq1S1ohoddi

### Logs

 specified file not found in archive

### Device info

- Device:Redmi K40S
- OS Version:miui14 android 13
- KernelSU Version:11682 ksud:11563
- Kernel Version:4.19

**Comment by GlassFoxowo-Dev** [comment]
## 首先，模块问题你应该去找模块作者提，而不是在这里提。
输出已经说的很明白“specified file not found in archive”，该模块不符合规范，缺少一些必要的描述文件以及脚本。
其次，你提供的模块文件内包含KernelSU*明确不支持*的行为 （KernelSU 不支持 .replace 方式），该模块无法在不修改的情况下在KernelSU下工作。
