### ISSUE TITLE
[Feature] Bypass environment detector of Octopus ("八達通") APP

### ISSUE THREAD

**Issue by citiao233** [tiann/KernelSU#1634]
### Is your feature request related to a problem? Please describe.

I'm not sure it is related to feature request or bug. Because the problem may mean a way can detect KernelSU.

Octopus App is an App which can manage transportation card of Hong Kong. It also has a balance function.
Before I installed KernelSU to my phone, most features of the APP can be used normally. (Even though my phone has unlocked Bootloader)
After installing KernelSU, the APP refused to initialize with a screen reported the environment is not safe.

I didn't give permission of ROOT or reading app list to it. I didn't start any module either.
Momo only report a abnormal of the unlock of Bootloader.

Octopus App version: 12.0.1 (from Google Play Store) updated on 2024/04/07
KernelSU version: 11682
KernelSU Management version: 11682

(P.S. After re-installing an older version 11.4.0 undated on 2024/03/18, Octopus APP can be used but also lost features I need in newer version.)
![IMG_20240415_223239](https://github.com/tiann/KernelSU/assets/76691379/e07bd49b-be21-483b-8487-11a751a1e78c)
![Screenshot_2024-04-15-21-07-21-941_com miui bugreport](https://github.com/tiann/KernelSU/assets/76691379/0fb13026-46aa-4cf8-9272-48e56bd695d3)

### Describe the solution you'd like.

Find a way to bypass environment detector of the APP though it may mean a way to detect KernelSU. This way may just be found in  the past few months.

### Describe alternatives you've considered.

Maybe a bug was been caught again? I have read #300 .

### Additional context

If this issue is inappropriate or misclassified, please help handle it. Thanks.

**Comment by tiann** [comment]
uninstall the manager app.
