### ISSUE TITLE
/system/vendor/无法被正常挂载

### ISSUE THREAD

**Issue by kanxinqing147** [tiann/KernelSU#1636]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

我安装了一个模块，这个模块会加载/system/vendor/etc/powerscntbl.xml文件，但是重启后只加载了这一个文件，/system/vendor/下的其他文件都没有加载。  
模块文件如下：
[scene_systemless.zip](https://github.com/tiann/KernelSU/files/14985725/scene_systemless.zip)

### To Reproduce

-1. 将模块解压，并置于/data/adb/modules/路径下
-2. 重启开机
–3. 发现/system/vendor/下只加载了/system/vendor/etc/powerscntbl.xml文件

### Expected behavior

原本在/system/vendor/路径下的文件继续存在，只不过/system/vendor/etc/powerscntbl.xml文件被替换

### Screenshots

出现问题后的/system/vendor/内容：  
![Screenshot_2024-04-16-09-14-58-290_bin mt plus](https://github.com/tiann/KernelSU/assets/70000323/9b3558c7-ac09-49e7-a9f5-03d8b879b560)
正常情况下的/system/vendor/内容：  
![Screenshot_2024-04-16-08-56-01-787_bin mt plus](https://github.com/tiann/KernelSU/assets/70000323/2bcb82e5-80af-4393-804e-9d0532d3fe10)

### Logs

[log.zip](https://github.com/tiann/KernelSU/files/14985758/log.zip)

### Device info

- Device: Redmi Note 11T Pro
- OS Version: Android14 | 安全更新: 2024-04-01 | HyperOS 1.0.1.0.ULOCNXM
- KernelSU Version: v0.9.2(11682)
- Kernel Version: 5.10.168-android12-9-00001-g81e7418c6466-ab10486262

### Additional context

这个问题是昨天我升级到HyperOS后出现的，在MIUI V14.0.7.0.TLOCNXM上并没有出现这个问题

**Comment by tiann** [comment]
> 将模块解压，并置于/data/adb/modules/路径下

你为什么不用标准的方式安装，要自己解压。

**Comment by kanxinqing147** [comment]
> > 将模块解压，并置于/data/adb/modules/路径下
> 
> 你为什么不用标准的方式安装，要自己解压。

标准安装也是一样的，只要模块涉及到/system/vendor/下的文件，原本/system/vendor/下的东西就不会加载
