### ISSUE TITLE
HUAWEI MatePad 11.5

### ISSUE THREAD

**Issue by enessmr** [tiann/KernelSU#1646]
Hi. I am a owner of this Device. I installed KernelSU APK. It's Compatible (kernel: 5.1). What boot archive should i use for this? 

Written from: Redmi Note 6 Pro from Chrome.

**Comment by Fede2782** [comment]
Kernel 5.1 is not gki. You must build it yourself

**Comment by enessmr** [comment]
Kernel (full): 5.10.136-gd2ad4cd9b200 ***@***.*** #1 Wed Jan 31
06:03:41 UTC 2024 (Turkey, made in China)

HarmonyOS: 3.1.0.168 (C432E2R1P1)

Please open this issue again.
It says Kurulmadı, kurmak için tıklayın. (Turkish language, PLease
translate the turkish text to English in Google Translate.)

**Comment by enessmr** [comment]
By the way, what boot image should i use? (Thanks to the GitHub filter for
not leaking personal Info.)

**Comment by Coconutat** [comment]
> By the way, what boot image should i use? (Thanks to the GitHub filter for not leaking personal Info.)

You can't use any kernel in here.The GKI generic kernel officially built by KernelSU does not work on any Huawei devices. These cannot be used regardless of whether Huawei equipment uses the GKI kernel.Huawei has added a lot of its own code to the kernel, some of which are compiled into modules, and many more are embedded in the kernel. You can only use Huawei's open source kernel source code to modify and build it yourself.

**Comment by enessmr** [comment]
I cannot post the screenshot. I need to transfer the picture to the PC or
redmi Note 8/6 Pro

**Comment by enessmr** [comment]
I am made for just to suffer.

**Comment by enessmr** [comment]
screenshot!
![Screenshot_20240420_104700_me weishu kernelsu](https://github.com/tiann/KernelSU/assets/136172887/8ec7bcd2-417c-4623-a237-45f442a3ffc3)

**Comment by enessmr** [comment]
I AM TALKING ABOUT. THIS!!!!!!!!!!!!!!!!

**Comment by Fede2782** [comment]
> screenshot! ![Screenshot_20240420_104700_me weishu kernelsu](https://private-user-images.githubusercontent.com/136172887/324163377-8ec7bcd2-417c-4623-a237-45f442a3ffc3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2MDAyNzQsIm5iZiI6MTcxMzU5OTk3NCwicGF0aCI6Ii8xMzYxNzI4ODcvMzI0MTYzMzc3LThlYzdiY2QyLTQxN2MtNDYyMy1hMjM3LTQ1ZjQ0MmEzZmZjMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMFQwNzU5MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNjRhY2Q5Njk1M2I2ZDk4M2M1NGYxNmNjNjM1MDY1ZjY1MGFkNDZiNDRmNTAyYWY3NjQxYzM0MzNmZWQ4OGU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Tm7V4Tu7We7IK5QINKkMsLzqJ5LD-luXnP-QHhwWR3Y)

You are using a non-GKI kernel. There is nothing we could do. You must build it yourself. That error is because you are not using a kernel with KernelSU

**Comment by enessmr** [comment]
Just understanded the kernel is actually compileable again (Gentoo Reference?).

**Comment by enessmr** [comment]
5.10.136

Is this GKI 1 or GKI 2?

**Comment by enessmr** [comment]
5.10.136

Is this GKI 1 or GKI 2?

Proof:
![Screenshot_20250301_121948.jpg](https://github.com/user-attachments/assets/97228154-33b4-4ef7-9216-be11aa133857)

**Comment by enessmr** [comment]
@Fede2782 and @tiann , Sorry. I made a mistake while typing the kernel.
Kernel was 5.10.

**Comment by enessmr** [comment]
Some app
![Screenshot_20250301_122339_com.rifsxd.ksunext.jpg](https://github.com/user-attachments/assets/13b17b2b-eb16-47b2-941c-b253a327e468)
