### ISSUE TITLE
KernelSU doesn't support ChromeOS ARM ARCVM

### ISSUE THREAD

**Issue by YsLtr** [tiann/KernelSU#1655]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

I replaced the kernel this path `/opt/google/vms/android/vmlinux` in my devices with @iceyear 's PR [here](https://github.com/tiann/KernelSU/pull/1642), it didm't work properly and cause the arcvm broken. No android application can start after reboot. We thought it's because kernelSU hasn't made a support to arm arcvm in ChromeOS.

### To Reproduce

1. Download latest arm arcvm compiled file from [ACTION](https://github.com/tiann/KernelSU/actions/runs/8747513979)
2. move the file to SD Card
3. Using `Ctrl + Alt + F2 (Flashing button on Chromebook)` to enter VT-2
4. log in and using `sudo -i` to ROOT
5. `mv /opt/google/vms/android/vmlinux /opt/google/vms/android/vmlinux.bak` to backup the kernel
6. `cp /media/removavle/SD\ Card/Image /opt/google/vms/android/vmlinux`
7. `reboot`

### Expected behavior

After reboot, I can get root in android.

### Screenshots

![image](https://github.com/tiann/KernelSU/assets/130123551/893634a0-564d-4fdf-a6ee-a1f32eba4396)

### Logs

Here is my [origin kernel](https://github.com/tiann/KernelSU/files/15021732/vmlinux.zip)

### Device info

- Device: HP Chromebook x2 11
- OS Version: ChromeOS 123.0.6312.132 and Android 11 in ARCVM
- KernelSU Version: 0.9.2
- Kernel Version: 5.10.209

### Additional context

I can supprt to test the new kernel on my device if ever.

**Comment by tiann** [comment]
We need the logs

**Comment by YsLtr** [comment]
> We need the logs

But how? I can't get logs from KernelSU Manager after replaced the kernel. Because it couldn't open.😭

**Comment by YsLtr** [comment]
[KernelSU_bugreport_2024-04-24_10_42.tar.gz](https://github.com/tiann/KernelSU/files/15087015/KernelSU_bugreport_2024-04-24_10_42.tar.gz)
This is the only one I can get after replace the kernel and recover it. I don't know if it's helpful.

**Comment by tiann** [comment]
I have not used ChromeOS, so I do not know; perhaps you need to search for how to use adb to connect to the Android system inside ChromeOS, and then use ADB to obtain logs.

**Comment by YsLtr** [comment]
> I have not used ChromeOS, so I do not know; perhaps you need to search for how to use adb to connect to the Android system inside ChromeOS, and then use ADB to obtain logs.

I tried.

However, it's useless. The Android system inside ChromeOS would not work with the kernel replaced with a wrong one. So adb couldn't found any devices if I want to connect android. 

Maybe I should try to build and test a kernel myself. But before I am able to learn about it, I think its wise to find another way to root the Android or wait for someone who can solve the problem.

**Comment by iceyear** [comment]
[Chromium OS Platform - Crash Collectors](https://chromium.googlesource.com/chromiumos/platform2/+/master/crash-reporter/docs/collectors.md) Maybe This would be helpful

**Comment by YsLtr** [comment]
Thank you. 
Here are two logs I found in `/var/log/` **after** replaced the kernel.
[arc.log](https://github.com/tiann/KernelSU/files/15094077/arc.log)
[arc.1.log](https://github.com/tiann/KernelSU/files/15094078/arc.1.log)

**Comment by YsLtr** [comment]
With @iceyear 's help. I got dmesg logs from `chrome://system/#arcvm_console_output`
And here are two different logs collected.
This is the one with **origin** kernel: 
[arcvm_console_output_Origin.txt](https://github.com/tiann/KernelSU/files/15109273/arcvm_console_output_Origin.txt)
This is the one with **replaced** kernel:
[arcvm_console_output_After_Replace.txt](https://github.com/tiann/KernelSU/files/15109281/arcvm_console_output_After_Replace.txt)

Wish it would be helpful.

**Comment by tiann** [comment]
You should confirm that the kernel compiled from source code would work well without KernelSU.

**Comment by YsLtr** [comment]
Some problem has been found:
My device (HP Chromebook x2 11) only got Android 11 but most of ChromeOS had got Android 13, so the kernel may even not work on my device without KernelSU.

**Comment by zanjie1999** [comment]
Kernel imagecan boot but not working,  
Kernel image能启动，但是kernelsu提示未安装，  
![4162bf18cdc2b0c5d859689b7820c931_720](https://github.com/tiann/KernelSU/assets/16502567/a9529c69-2613-43ba-9469-0fea984eff1d)

my logs
[KernelSU_bugreport_2024-04-29_11_43.tar.gz](https://github.com/tiann/KernelSU/files/15144971/KernelSU_bugreport_2024-04-29_11_43.tar.gz)

**Comment by tiann** [comment]
upload dmesg logs

**Comment by zanjie1999** [comment]
> upload dmesg logs

[chromeos-dmesg.txt](https://github.com/tiann/KernelSU/files/15145022/chromeos-dmesg.txt)

**Comment by tiann** [comment]
No KernelSU logs found. You can check the image to see if KernelSU is integrated correctly.

**Comment by zanjie1999** [comment]
Tips:  enable  chromeos arcvm adb without linux vm
 settings->apps->google play store->manage android preferences->system->developer options 

adb logcat of arcvm 
[arcvm-logcat.txt](https://github.com/tiann/KernelSU/files/15145151/arcvm-logcat.txt)

**Comment by zanjie1999** [comment]
> No KernelSU related logs found. You can check the image to see if KernelSU is integrated correctly.

I restored arcvm's default vmlinux:
![7fc2cd63cb7af829289e77ac964dca78_720](https://github.com/tiann/KernelSU/assets/16502567/c66c7600-1cad-4dd7-a5df-5ba381b6f37a)
kernel version is 5.10.209-997258

and I use  `Image` in `kernel-ARCVM-arm64-5.10.209.zip` download from releases  to replacement `vmlinux` file in `/opt/google/vms/android` :
![image](https://github.com/tiann/KernelSU/assets/16502567/c4565c48-4e85-4992-ad3e-e5be006b9c70)
kernel version is 5.10.209-android12-9

I think maybe kernel is OK, but KernelSU is not work

**Comment by tiann** [comment]
The fact is that there is no log for KernelSU in your log; even if it doesn't work, it will output at least one line of log during kernel module initialization.

**Comment by iceyear** [comment]
> > upload dmesg logs
> 
> [chromeos-dmesg.txt](https://github.com/tiann/KernelSU/files/15145022/chromeos-dmesg.txt) I have not adb access for arcvm, this log is outside of arcvm

@zanjie1999 It seems like this is the chromeos's dmesg but not arcvm's. Try chrome://system/#arcvm_console_output to fetch arcvm dmesg logs.

**Comment by zanjie1999** [comment]
> > > 上传 dmesg 日志
> > 
> > 
> > [chromeos-dmesg.txt](https://github.com/tiann/KernelSU/files/15145022/chromeos-dmesg.txt)我没有 arcvm 的 adb 访问权限，此日志位于 arcvm 之外
> 
> @zanjie1999看起来这是 chromeos 的 dmesg 而不是 arcvm 的。尝试使用 chrome://system/#arcvm_console_output 获取 arcvm dmesg 日志。

I've downgraded my system to ChromeOS 113 to use ARC++ (

**Comment by YsLtr** [comment]
> Kernel imagecan boot but not working, Kernel image能启动，但是kernelsu提示未安装， ![4162bf18cdc2b0c5d859689b7820c931_720](https://private-user-images.githubusercontent.com/16502567/326325851-a9529c69-2613-43ba-9469-0fea984eff1d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5MDg4NzQsIm5iZiI6MTcxNDkwODU3NCwicGF0aCI6Ii8xNjUwMjU2Ny8zMjYzMjU4NTEtYTk1MjljNjktMjYxMy00M2JhLTk0NjktMGZlYTk4NGVmZjFkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA1VDExMjkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1YWNkOTBjMmQyMDU2ZTE4YWZhZTEyNjI2MDBhZGJkYjcwNmQxNWU5YWFmYWM2NGQ4ZDZmM2U1YjZlMzFjYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.feGapRqaPIH3ewGa3a7vtg9tJt_LAzWD28-1r-77Fcs)
> 
> 现在的最新版本v0.9.3 使用 kernel-ARCVM-arm64-5.10.209.zip 中的Image替换vmlinux 可以正常启动，但是kernelsu管理器提示未安装，看内核版本确实已经替换成功了（我的是arm64 mt8183）
> 
> the latest version v0.9.3 use Image in kernel-ARCVM-arm64-5.10.209.zip to replacement vmlinux is working normally, but the kernelsu manager show not install , and the kernel version has been successfully updated (use arm64 mt8183 )
> 
> my logs [KernelSU_bugreport_2024-04-29_11_43.tar.gz](https://github.com/tiann/KernelSU/files/15144971/KernelSU_bugreport_2024-04-29_11_43.tar.gz)

It seems that your Android version is 12. It's different from mine (Android 11). So maybe only Android 12 can boot with this `vmlinux`.

**Comment by iceyear** [comment]
> > Kernel imagecan boot but not working, Kernel image能启动，但是kernelsu提示未安装， ![4162bf18cdc2b0c5d859689b7820c931_720](https://private-user-images.githubusercontent.com/16502567/326325851-a9529c69-2613-43ba-9469-0fea984eff1d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5MDg4NzQsIm5iZiI6MTcxNDkwODU3NCwicGF0aCI6Ii8xNjUwMjU2Ny8zMjYzMjU4NTEtYTk1MjljNjktMjYxMy00M2JhLTk0NjktMGZlYTk4NGVmZjFkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA1VDExMjkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1YWNkOTBjMmQyMDU2ZTE4YWZhZTEyNjI2MDBhZGJkYjcwNmQxNWU5YWFmYWM2NGQ4ZDZmM2U1YjZlMzFjYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.feGapRqaPIH3ewGa3a7vtg9tJt_LAzWD28-1r-77Fcs)
> > 现在的最新版本v0.9.3 使用 kernel-ARCVM-arm64-5.10.209.zip 中的Image替换vmlinux 可以正常启动，但是kernelsu管理器提示未安装，看内核版本确实已经替换成功了（我的是arm64 mt8183）
> > the latest version v0.9.3 use Image in kernel-ARCVM-arm64-5.10.209.zip to replacement vmlinux is working normally, but the kernelsu manager show not install , and the kernel version has been successfully updated (use arm64 mt8183 )
> > my logs [KernelSU_bugreport_2024-04-29_11_43.tar.gz](https://github.com/tiann/KernelSU/files/15144971/KernelSU_bugreport_2024-04-29_11_43.tar.gz)
> 
> It seems that your Android version is 12. It's different from mine (Android 11). So maybe only Android 12 can boot with this `vmlinux`.

![image](https://github.com/tiann/KernelSU/assets/75525564/db5878ea-eec5-4052-993c-8ab892e99aef)

**Comment by zanjie1999** [comment]
> > Kernel imagecan boot but not working, Kernel image能启动，但是kernelsu提示未安装， ![4162bf18cdc2b0c5d859689b7820c931_720](https://private-user-images.githubusercontent.com/16502567/326325851-a9529c69-2613-43ba-9469-0fea984eff1d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5MDg4NzQsIm5iZiI6MTcxNDkwODU3NCwicGF0aCI6Ii8xNjUwMjU2Ny8zMjYzMjU4NTEtYTk1MjljNjktMjYxMy00M2JhLTk0NjktMGZlYTk4NGVmZjFkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA1VDExMjkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1YWNkOTBjMmQyMDU2ZTE4YWZhZTEyNjI2MDBhZGJkYjcwNmQxNWU5YWFmYWM2NGQ4ZDZmM2U1YjZlMzFjYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.feGapRqaPIH3ewGa3a7vtg9tJt_LAzWD28-1r-77Fcs)
> > 现在的最新版本v0.9.3 使用 kernel-ARCVM-arm64-5.10.209.zip 中的Image替换vmlinux 可以正常启动，但是kernelsu管理器提示未安装，看内核版本确实已经替换成功了（我的是arm64 mt8183）
> > the latest version v0.9.3 use Image in kernel-ARCVM-arm64-5.10.209.zip to replacement vmlinux is working normally, but the kernelsu manager show not install , and the kernel version has been successfully updated (use arm64 mt8183 )
> > my logs [KernelSU_bugreport_2024-04-29_11_43.tar.gz](https://github.com/tiann/KernelSU/files/15144971/KernelSU_bugreport_2024-04-29_11_43.tar.gz)
> 
> It seems that your Android version is 12. It's different from mine (Android 11). So maybe only Android 12 can boot with this `vmlinux`.

my android version is 11, this image(kernel version is 5.10.209-android12-9) was taken after use KernelSU vmlinux imagel, maybe KernelSU only work on Android 12 arcvm : )

**Comment by tiann** [comment]
The concept of GKI only applies to devices such as smartphones, other devices like simulators, watches, and virtual machines do not follow KMI.

**Comment by tiann** [comment]
So, what's the issue now?

**Comment by YsLtr** [comment]
> So, what's the issue now?

The origin. No more progress.

**Comment by tiann** [comment]
But i did't see any logs related with KernelSU.

**Comment by YsLtr** [comment]
> But i did't see any logs related with KernelSU.

It's exactlly a serious problem. So we need more difference devices to break the deadlock.

**Comment by tiann** [comment]
closed since inactive
