### ISSUE TITLE
[Feature]能否提供通过刷机包和addon.d进行lkm刷入。

### ISSUE THREAD

**Issue by fsxitutu** [tiann/KernelSU#1659]
### Is your feature request related to a problem? Please describe.

因为现有的官方kernelsu提供的刷机包只有通过ak3脚本刷入gki内核的刷机包。没有刷入lkm的刷机包。且不支持addon.d脚本在ota后自动刷入，需要手动在管理器里手动刷入，ota后容易遗漏此步骤。

### Describe the solution you'd like.

提供一个刷机包，可以通过在recovery刷入的方式刷入lkm内核模块获得root。

### Describe alternatives you've considered.

这里有一个我随手做的刷入kernelsu内核模块(lkm)的刷机包。经测试在google pixel 7 pro上能够使用。
https://fileserver.lanzouo.com/iYEXQ1wbs7gb

### Additional context

既然能够通过刷机包刷入lkm，能否通过addon.d脚本自动在ota后自动重新刷入？
现有难题是kernelsu并没有把修补boot所需要的所有二进制文件(busybox , ksud , magiskboot , ksuinit , *-kernelsu.ko)释放到一个稳定的地方(比如/data/adb/ksu/bin)，由第三方提供addon.d脚本容易因版本升级等原因造成兼容性问题。

**Comment by tiann** [comment]
没有这个计划。
