### ISSUE TITLE
Failed to `fastboot boot` to the temp system with boot.img provided by KernelSU under Color OS 14

### ISSUE THREAD

**Issue by jackyzy823** [tiann/KernelSU#1661]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Failed to `fastboot boot` to the temp system with boot.img provided by KernelSU under Color OS 14
在ColorOS 14下，使用KernelSU提供的boot.img， fastboot boot至临时系统失败

### To Reproduce

1. 一开始在ColorOS_PJA110_13.1.1.552(CN01)_A.2下，使用 android13-5.15.144_2024-02-boot.img ， fastboot boot 进入系统，后直接安装成功
2. 更新系统 至 ColorOS PJA110_14.0.0.500(CN01) C.18，忘记在重启前将KSU安装至另外的Slot （应该说没想到点立即安装就重启了）
3. 进入系统后第二次更新系统 至 ColorOS PJA110_14.0.0.600(CN01) C.19 ，
4. 使用对应的 android13-5.15.148_2024-04-boot.img fastboot boot 失败，应该是直接进入原系统。
5. 使用 修补的方式（修补通过系统安装包提取的init_boot.img 后 fastboot flash init_boot ）能够成功root

----------------
1. Under ColorOS_PJA110_13.1.1.552(CN01)_A.2 , `fastboot boot` with  android13-5.15.144_2024-02-boot.img successfully and root successfully.
2. OTA the system to  ColorOS PJA110_14.0.0.500(CN01) C.18 and reboot without install KernelSU to another slot.
3. OTA the system to ColorOS PJA110_14.0.0.600(CN01) C.19 
4. `fastboot boot` with   android13-5.15.148_2024-04-boot.img failed, the device is booted to the original system.
5. Patch the init_boot.img from the OTA pacakge, and the fastboot flash init_boot the_patched_init_boot.img , the device is booted successfully and is rooted successfully.

### Logs

我不知道如何提取临时boot的日志，如果有需要请告诉我如何操作，我将上传日志。
I don't know how to fetch the device log of temp boot. If you could instruct me how to get the log , i will happy to upload the log. Thanks

### Device info

- Device: OnePlus Ace2Pro
- OS Version: ColorOS PJA110_14.0.0.600(CN01) C.19 
- KernelSU Version: 1187
- Kernel Version: 5.15.123-android13-8-00753-g58cccd9b6704

### Additional context

Thanks for your project!

**Comment by tiann** [comment]
#1051 可能是一个原因
