### ISSUE TITLE
[Feature] Add logs export to local storage

### ISSUE THREAD

**Issue by Fede2782** [tiann/KernelSU#1664]
### Is your feature request related to a problem? Please describe.

I'm always frustrated when I need to get KernelSU logs because when I click the Logs button in Settings it opens the Share menu, this means that if I have to get the logs file on the device it has been captured on, I need to share it to another device first or upload to some cloud service. 

### Describe the solution you'd like.

It should open a popup which asks if the user wants to share or save on device. In case the user wants to save on device a DocumentsUI screen or similar should allow the user to save the logs where he desires on by default in some Download folders

### Describe alternatives you've considered.

Instead of sharing it and then deleting it at least give the user the path where the log is saved

**Comment by powellnorma** [comment]
Workarounds:

https://f-droid.org/en/packages/xyz.myachin.saveto/

https://android.stackexchange.com/questions/195062/share-as-file-on-filesystem

**Comment by LHC12580** [comment]
到底是什么情况啊？



---Original---
From: ***@***.***&gt;
Date: Tue, May 7, 2024 20:41 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [tiann/KernelSU] [Feature] Add logs export to local storage(Issue #1664)




  
韦树哥为什么不更新了，腾讯和阿里又威胁你们了是吗？
  
又是哪个自媒体在那乱说不更新了，能不能先提升自己的英语水平，把公告看懂；再不济，Google 翻译都不会用吗？

**Comment by klxiaoniu** [comment]
How to design this interaction? Simply replacing sending logs with save logs, like LSPosed, or add a dialog that allows to choose save or share?

**Comment by tiann** [comment]
I think save log is OK, if he wants to share, he can share it in file
manager later.

快乐小牛 ***@***.***> 于 2024年5月9日周四 下午4:37写道：

**Comment by Fede2782** [comment]
> Or we can add an Intent to ourselves, and when we share to this intent, it will be saved locally.

I think the best way could be to click on Capture logs -> Let the user chose if he wants to save locally or wants to share. In the first case a DocumentsUI page could be opened to let user save where he wants. In the second case the share menu could open

**Comment by tiann** [comment]
#1741

**Comment by yousefboutrad** [comment]
Kernel samsonj m 53 !!

**Comment by nasryhsyb00-jpg** [comment]
> #3629 )
