### ISSUE TITLE
[Custom]11807升级了apk，但核心没升级到位只有11804，LSPosed图标丢失了

### ISSUE THREAD

**Issue by maston2** [tiann/KernelSU#1665]
### 目前升级完成后的界面（用的最新的image，只有11804，管理器是ksu自动下载的11807，两者的小版本号不一致）：
![8ab047ab90e989cf9f2390707564fadf](https://github.com/tiann/KernelSU/assets/124343921/f431a09a-7065-452c-b1fe-0c795d14b0fc)

### 也安装了LSPosed和zgisk next模块，原来使用的也很正常。
![99bb86bb46bdb7c2f32b2249ab9c09bd](https://github.com/tiann/KernelSU/assets/124343921/761a7fd8-65c6-479b-9646-e4144acaa979)

### 但现在lsposed模块在桌面不显示图标了，但之前的lsposed插件也都全部有效运行，只是没有Lsposed界面不好设置了。

请问，这是我升级操作错误了吗？

PS，上传的图好大啊，这个无法控制……

**Comment by tiann** [comment]
只有 LKM 模式可以在管理中安装，GKI 模式只能自己刷写；建议先看文档。

**Comment by maston2** [comment]
我就是自己刷的啊，不然怎么能到11804，只是刷不到11807啊。

**Comment by tiann** [comment]
App 11087，因为 App 有 bug，新增了3个commit 修复，内核没有变化，所以版本比内核高，这个是正常现象。
