### ISSUE TITLE
KernelSU Manager does not launch on Android 15

### ISSUE THREAD

**Issue by scarlettekk** [tiann/KernelSU#1666]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

On the latest beta of Android 15, KernelSU manager does not launch, it just sits on the splash screen forever. It is unknown whether this is because of Android 15 or not.

### To Reproduce

1. (Possibly) Install android 15 beta on emulator or pixel
2. Install KernelSU manager
3. Open KernelSU manager
4. Observe behavior

### Expected behavior

The app opens

### Screenshots

The app hangs on the splash screen
![Screenshot_20240425-164935](https://github.com/tiann/KernelSU/assets/42524580/4f87ae0e-c681-46a9-9fec-e19b448c4e2f)

### Logs

Unable to export logs since the app does not open. However:
`adb logcat | grep kernelsu`: 
[log.txt](https://github.com/tiann/KernelSU/files/15121855/log.txt)

### Device info

- Device: Pixel 8 Pro
- OS Version: Android 15 beta 1.1
- KernelSU Version: 0.9.3
- Kernel Version: 5.15.137-android14-11

**Comment by tiann** [comment]
> 04-25 16:48:13.487  2024  2389 I LSPosed-Bridge: [ INFO] 04-25 16:48:13 (ZygoteArgsHook) @startViaZygote force mount data: 10540 me.weishu.kernelsu

Nothing to do with KernelSU, LSPosed doesn't support Android 15 now.
