### ISSUE TITLE
apk版本11807，但img是11804

### ISSUE THREAD

**Issue by maston2** [tiann/KernelSU#1669]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

![image](https://github.com/tiann/KernelSU/assets/124343921/98b8df5e-1e74-4d3b-a6e9-bb5146c43b60)

我用的是红米k50，别的img是不是11804不知道，但android12-5.10.168_2023-05-boot-gz.img.gz这个是11804.

另外，LSPosed的桌面快捷方式没有了，不知道是否与这个有关。

### Device info

- Device: 红米k50
- OS Version: 澎湃
- KernelSU Version: 11804
- Kernel Version: 11807

**Comment by tiann** [comment]
正常现象，bug 与此无关。
