### ISSUE TITLE
[Feature] Provide legacy_lz4 GKI

### ISSUE THREAD

**Issue by onokatio** [tiann/KernelSU#1674]
### Is your feature request related to a problem? Please describe.

Now lz4_legacy KMI (like Pixel ROM) is not provided on Github Release.

### Describe the solution you'd like.

Please provide the file at CI.

### Describe alternatives you've considered.

I'm considering to create PR myself.

**Comment by hobby1999** [comment]
use this is  enough

**Comment by hobby1999** [comment]
use this is enough

**Comment by hobby1999** [comment]
use this,https://kernelsu.org/guide/installation.html#patch-boot-image

**Comment by onokatio** [comment]
> use this,https://kernelsu.org/guide/installation.html#patch-boot-image

Yes, I know and am using it. But I want prebuilt images.

**Comment by apprehensions** [comment]
What is wrong with LMK?

**Comment by onokatio** [comment]
LMK is good for daily use.
But installation LKM by `fastboot flash` doesn't make stock image backup on kernelsu app, so I can't use `restore stock` feature in app.

**Comment by onokatio** [comment]
I'm trying to inspect, but I found that repacking boot.img with `magiskboot` and provided android?-boot-lz4.img from kernelsu are almost same and I couldn't find about "compression format" diffirence.

**Comment by onokatio** [comment]
And also I found that two file are diffirence only about avb header. I think this means true reason that kernelsu gki doesn't boot pixel is not relating compression format.

**Comment by onokatio** [comment]
umm, It seems bootloop is from just vbmeta mismatch.
