### ISSUE TITLE
[Custom]能否将magiskboot二进制文件释放到kernelsu工作目录

### ISSUE THREAD

**Issue by fsxitutu** [tiann/KernelSU#1676]
### Describe your problem.

因为目前的ksu管理器不会把内置的magiskboot二进制文件释放到ksu的工作目录中(比如/data/adb或/data/adb/ksu/bin)。导致如果需要在命令行环境下刷入gki或lkm时需要依赖于从现有的ksu管理器中提取所需的magiskboot二进制文件。这种方式并不可靠，因为用户有可能出于隐藏root等目的卸载ksu管理器，导致无法获取magiskboot二进制文件给ksud用于修补boot/init_boot镜像。且对于自动化工具/脚本等不太友好。

下面这里有一个我自己编写的用于OTA后重新刷入kernelsu lkm的addon.d脚本。用于展示命令行环境下刷入lkm的过程。
[99-kernelsu.txt](https://github.com/tiann/KernelSU/files/15145769/99-kernelsu.txt)

希望后面可以把magiskboot二进制文件释放到ksu工作目录(最好是和busybox及ksud同一目录)，以便其他工具或脚本可以较为稳定和方便的进行boot/init_boot修补操作。

**Comment by tiann** [comment]
PRs welcome
