### ISSUE TITLE
Although 0.9 series code compiles and works on 4.x kernels, the manager does not

### ISSUE THREAD

**Issue by dunsolicited** [tiann/KernelSU#1682]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

The 0.9 series is advertised as "LKM does not support non-GKI kernels, and will not support them in the future;"

The 4.x series of kernels does not use LKM, and obviously are not GKI. These are explicitly excluded in the manager apk source, but the kernel code will still work just fine at 0.9.3.

The latest 0.8 manager will work fine with the latest 0.9.3 kernel code on a 4.x series kernel. Is this intended?

### Device info

- Device:
- OS Version:
- KernelSU Version:
- Kernel Version:

**Comment by tiann** [comment]
what's the issue here？

**Comment by dunsolicited** [comment]
![image](https://github.com/tiann/KernelSU/assets/168475429/e928cd61-0131-4c21-ab11-35f6a5b2c0b4)

This is with the 0.9.3 KernelSU incorporated in the kernel source.

**Comment by dunsolicited** [comment]
The 0.8.1 manager app works fine by the way

**Comment by goodname3** [comment]
我出现了同样的问题，尽管自定义的带有kernelsu的4.4.302 Anykernel包被成功刷入，但管理器不识别它
