### ISSUE TITLE
[Custom] Provide builds for kernel 5.15.123-android13

### ISSUE THREAD

**Issue by Drugoy** [tiann/KernelSU#1698]
### Describe your problem.

OxygenOS (stock ROM for OnePlus 11 devices) last year received a ROM update that now bases on Android 14.
The device shows that it uses kernel of version 5.15.123-android13-8-007520-gbd7d926d6df1.
Your project's releases page seems to lack files named like android14-5.15.123_*-boot*.img.gz suitable for that device+firmware.
Please, add such builds.

**Comment by tiann** [comment]
read the docs, please.

**Comment by Drugoy** [comment]
I've read the docs...

I wanted to try the GKI mode installation.
There are [4 '[mainstream](https://kernelsu.org/guide/installation.html#gki-mode-installation)' + 2 '[other](https://kernelsu.org/guide/installation.html#other-methods)'](https://kernelsu.org/guide/installation.html#gki-mode-installation) methods to do that.
2nd 'other' method
> Use some flashing toolkit on PCs to flash in the kernel provided KernelSU.

is too non-specific to be applicable in my case (I don't have any flashing toolkits and I doubt they'd run on Linux).
So I was left with the just 1 [method](https://kernelsu.org/guide/installation.html#install-with-boot-img-provided-by-kernelsu) that starts with 'Find proper boot.img'. Since there's no matching build - I've opened this ticket.

I guess I'll go with LKM method then.
I had already patched `init_boot` partition via Magisk and KernelSU now throws an error that it can't flash that partition again since Magisk had already got tampered with it, so I guess, I'll have to take clean init_boot.img, patch it via KernelSU and then flash it via fastboot.

**Comment by tiann** [comment]
so, you just don't know what is KMI at all.

**Comment by Drugoy** [comment]
I know only what was mentioned about it in the docs:
> Kernel Module Interface (KMI), kernel versions with the same KMI are compatible. This is what "general" means in GKI; conversely, if the KMI is different, then these kernels are not compatible with each other, and flashing a kernel image with a different KMI than your device may cause a bootloop.

**Comment by Drugoy** [comment]
Damn, so I got lost in the versions...
Thank you, @HuskyDG
