### ISSUE TITLE
adb shell not apply su

### ISSUE THREAD

**Issue by pinkwave** [tiann/KernelSU#1700]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

adb shell cannot apply su. if set the profile for the terminal app or any app and try to use su (works), but not for the adb shell.

### Screenshots

![Screenshot from 2024-05-06 09-42-27](https://github.com/tiann/KernelSU/assets/167660873/787a7801-06a8-462e-859a-81d9fa905667)
![photo_2024-05-06_09-45-09 (2)](https://github.com/tiann/KernelSU/assets/167660873/91e27843-12ba-4dee-92a0-e3c3e7019dd0)
![photo_2024-05-06_09-45-09](https://github.com/tiann/KernelSU/assets/167660873/527f693a-b433-4c1c-a218-b2abfb836c52)

### Device info

- Device: Pixel 4
- OS Version: 10
- KernelSU Version: 11804
- Kernel Version: 4.14.111

### Additional context

[KernelSU_bugreport_2024-05-06_09_49.tar.gz](https://github.com/tiann/KernelSU/files/15217623/KernelSU_bugreport_2024-05-06_09_49.tar.gz)

**Comment by pinkwave** [comment]
close. 
solved manual integration.

similar to [https://github.com/tiann/KernelSU/issues/502](url)

**Comment by Pulsero** [comment]
> close. solved
> 
> similar to [#502](https://github.com/tiann/KernelSU/issues/502)

Hi! How did you solve it?

**Comment by noseccomp** [comment]
> > close. solved
> > similar to [#502](https://github.com/tiann/KernelSU/issues/502)
> 
> Hi! How did you solve it?

manual integration without KPROBE
