### ISSUE TITLE
i don't know name issue 

### ISSUE THREAD

**Issue by NyaruToru** [tiann/KernelSU#1702]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

first i install module modify system/vendor dir like thermal disable

But after i reboot my system/vendor dir have only file module(thermal disable)
system/vendor/bin/(2 file)

other file is lost, causing the device to malfunction.

But after i remove module all file in system/vendor is back

I don't know name issue 

### To Reproduce

1. Open kernelsu manager (4.14.117)
2. install thermal disable 2.0 
3. Reboot
4. 4 view system/vendor dir
5. other file like build.prop is lose

### Device info

- Device:Poco x3 nfc
- OS Version: Andoroid 11
- KernelSU Version: 11833
- Kernel Version: 4.14.117

**Comment by tiann** [comment]
upload the module installation logs

**Comment by tiann** [comment]
KernelSU does not support self-extracting /vendor files. You should place the vendor in the system directory, and KernelSU will automatically extract and process symbolic links during installation.

**Comment by tiann** [comment]
No, you should modify the module.
