### ISSUE TITLE
Announcement

### ISSUE THREAD

**Issue by tiann** [tiann/KernelSU#1705]
### Describe your problem.

KernelSU has been around for nearly two years and has stabilized, and we plan to move to 1.0 in the future; here are some adjustments:

1. In principle, we only accept Bug Reports and do not accept external Feature Requests; if you want new features, you are welcome to submit a Pull Request. We will still develop new features that we think are interesting/cool, such as sulog, ksufs, webui, etc.
2. Since non-GKI kernels are full of weird things, it is very time-consuming to deal with this kind of problem; from now on, we will only deal with issues related to GKI kernels. For problems with old kernels, please search for issues by yourself; we will give up supporting non-GKI kernels in version 1.0. Since non-GKI kernels are no longer updated, you can continue to use KernelSU version 0.9.3; in fact, starting from 0.7.0, we have not added any features to non-GKI kernels.

Our energy is limited, but the rewards are even more limited, so please understand our choice, thank you!

**Comment by tiann** [comment]
For non GKI kernel, please refer: #943

**Comment by Fede2782** [comment]
Will support code for pre-GKI remain in the main source or not? @tiann

**Comment by tiann** [comment]
> Will support code for pre-GKI remain in the main source or not after v1? @tiann 

It will be removed.

**Comment by 0xSoul24** [comment]
Add support for android15-6.6 kernel

**Comment by JingMatrix** [comment]
**Feature request**
Add API to close the WebView page.
I would like to run some commands, and then close the WebView so that uses don't need to manually use return to exit the WebView.

**Comment by diabl0w** [comment]
If pre-GKI code is being removed from 1.0+ please remove all references to being compatible with non-gki kernels. The README and the website both claim compatability. No one wants to install EOL program. Wasted a lot of my time.

**Comment by Valz8887** [comment]
Quiero componer mi software

**Comment by jeffpeng3** [comment]
> > 1. if you want new features, you are welcome to submit a Pull Request.
> 
> Sorry for such a manner – not skilled enough to submit a Pull Request:
> 
> **[FEATURE REQUEST] Add predefined selection for the kernel version.**
> 
> Currently, user must re-enter the kernel version (KMI) with every OTA update. Such a behavior increases the potential risks if he/she missteps for whatever reason. However, KMI is fairly constant and rarely changes within the same device (especially if it is not an emulator). Therefore, it would be beneficial to provide user with the option to select KMI just one time via settings, similar to the "Umount modules by default" toggle.

Typically, applying LKM before an OTA reboot will still automatically grab the KMI in the partition, and you only need to specify it manually if kernelSU can't find it, so you should first identify what your kernel can't indicate KMI.

**Comment by kingmk323** [comment]
Hello,
thank you in advance for all your help. I need to install kernelSU on my daily driver, a Samsung Galaxy F13 (Exynos) with original rom, and I want to ask a couple of questions before I proceed.

First of all, I'm currently rooted with Magisk Canary, but a banking app that I really need detects it even if it's hidden and I pass strong integrity. I've read that people got it working with kernelSU instead, hence the switch that I want to do. Here are my questions:

Is kernelSU installable on my phone configuration without building a custom kernel? I've installed the app on the phone and it looks like it should be possible, but I would like some reassurance on this regard.

All your guides say that I should patch boot.img and then flash it, but Samsung original firmwares work a bit differently afaik. I don't have a boot.img file, but I have an AP tar containing the whole system and the boot.img file in some form instead. I can feed Magisk this AP tar and Magisk Manager is capable of patching it - can the kernelSU app do the same?

I'm currently with an about 1 year old firmware installed on the phone (I never had the time to update it), but I was going to update to the latest firmware in all this change process. Can I safely use the latest firmware or is kernelSU going to have issues with it? Which version should I use in case?

As I said, I need to install kernelSU and remove Magisk from the system. I have a feeling that installing kernelSU with Magisk installed might be easier as I can get root for it and possibly patch the system in place without needing to patch and flash any files. Is it safe to do it this way, and then remove Magisk via its manager after installing kernelSU? Also re question 2, how would future updates work? Samsung disables OTAs when the bootloader is unlocked, so my only way to update the firmware is to flash it via Odin. Will I be able to patch the files in the future and then flash them with Odin?

**Comment by mojibksa** [comment]
https://github.com/tiann/KernelSU/issues/1705

**Comment by ghost** [comment]
Kernel su da bootloop no Galaxy a36 Kernel 6.6.46

**Comment by ghost** [comment]
Bootloop no Galaxy A36 5G kernel 6.6.46

**Comment by Qiong-yu131** [comment]
> ### 描述您的问题。
> KernelSU 已经存在了将近两年，并且已经稳定下来，我们计划在未来迁移到 1.0;以下是一些调整：
> 
> 1. 原则上，我们只接受 Bug 报告，不接受外部功能请求;如果您想要新功能，欢迎您提交 Pull Request。我们仍然会开发我们认为有趣/很酷的新功能，例如 sulog、ksufs、webui 等。
> 2. 由于非 GKI 内核充满了奇怪的东西，处理这种问题非常耗时;从现在开始，我们将只处理与 GKI 内核相关的问题。老内核的问题，请自行搜索 issue;我们将在 1.0 版本中放弃对非 GKI 内核的支持。由于非 GKI 内核不再更新，因此您可以继续使用 KernelSU 版本 0.9.5;事实上，从 0.7.0 开始，我们没有为非 GKI 内核添加任何功能。
> 
> 我们的能量是有限的，但奖励更是有限，所以请理解我们的选择，谢谢！

一个简单的提问，你是如何看待sukisu，ksu-next，和susfs4ksu，如果susfs没有出现，这几个ksu分支是不是就不会出现，他们只会关心好不好，而忽略其中原理，就像现在的新中国和就历史，这只是我个人观点

**Comment by nicollas27** [comment]
Hello developers,

I own a Samsung Galaxy M53 5G (SM-M536B) running Android 15.
Currently, there is no public custom kernel for this device on kernel 6.6, so I’m kindly requesting if someone could help with a recompiled kernel (preferably with KernelSU/KernelSU-Next support).

Device details

Model: SM-M536B (Galaxy M53 5G)

Chipset: MediaTek Dimensity 900 (MT6877)

Android version: 15

Kernel version (from uname -a): Linux version 6.6.x … (please replace with your exact output from Settings > About phone > Kernel version)

Firmware build: (replace with your current build, e.g. M536BXXUxxx…)


Source code

Samsung has already released the Android 15 kernel source for the M53:
👉 Samsung OSRC - SM-M536B_CIS_15_Opensource.zip

Request

A custom/recompiled kernel based on Android 15 kernel 6.6 for the M53.

Please include support for KernelSU or KernelSU-Next.

The kernel should provide a boot.img flashable with Odin or Heimdall (⚠️ no custom recovery required).


Motivation

At the moment, there’s no custom kernel available for this device on Android 15, and having one would make KernelSU possible and open the door for further development.

Thanks in advance to anyone who can help

**Comment by alexandre723299** [comment]
Seria muito bom adicionar uma função pra esconder ou máscarar o aplicativo do kernelsu, com uma reinstalação do pacote apk com nome diferente.

**Comment by GoRhanHee** [comment]
> Hello developers,
> 
> I own a Samsung Galaxy M53 5G (SM-M536B) running Android 15. Currently, there is no public custom kernel for this device on kernel 6.6, so I’m kindly requesting if someone could help with a recompiled kernel (preferably with KernelSU/KernelSU-Next support).
> 
> Device details
> 
> Model: SM-M536B (Galaxy M53 5G)
> 
> Chipset: MediaTek Dimensity 900 (MT6877)
> 
> Android version: 15
> 
> Kernel version (from uname -a): Linux version 6.6.x … (please replace with your exact output from Settings > About phone > Kernel version)
> 
> Firmware build: (replace with your current build, e.g. M536BXXUxxx…)
> 
> Source code
> 
> Samsung has already released the Android 15 kernel source for the M53: 👉 Samsung OSRC - SM-M536B_CIS_15_Opensource.zip
> 
> Request
> 
> A custom/recompiled kernel based on Android 15 kernel 6.6 for the M53.
> 
> Please include support for KernelSU or KernelSU-Next.
> 
> The kernel should provide a boot.img flashable with Odin or Heimdall (⚠️ no custom recovery required).
> 
> Motivation
> 
> At the moment, there’s no custom kernel available for this device on Android 15, and having one would make KernelSU possible and open the door for further development.
> 
> Thanks in advance to anyone who can help

Just import ksu driver and hook ksu codes in ur kernel source and compile… its simple

**Comment by BomSloth40** [comment]
1231@Bomsloth40
