### ISSUE TITLE
ADB not working after flashing a simple module

### ISSUE THREAD

**Issue by powellnorma** [tiann/KernelSU#1710]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

After flashing a simple module that just overwrites `/system/etc/hosts` and rebooting, adb is not working anymore. The device simply does not show up anymore, no matter what I try.

Deleting `/data/adb/ksu/modules.img` via termux and rebooting fixes the issue.
In termux I can also see that `/system/etc/hosts` does get correctly replaced / over-mounted.

One thing that looks suspicious to me:

```
[   18.812591] [pid:1,cpu0,init]init: Service 'exec 5 (/data/adb/ksud)' (pid 701) exited with status 0 waiting took 0.150053 seconds
[   18.812652] [pid:1,cpu0,init]init: Wait for exec took 0.150207 seconds
[   18.814117] [pid:1,cpu0,init]init: processing action (sys.usb.config=hisuite,mtp,mass_storage,adb && sys.usb.configfs=1)
[   18.814331] [pid:1,cpu0,init]init: write_file: Unable to write to '/config/usb_gadget/g1/UDC': No such device
[   18.814727] [pid:1,cpu0,init]init: Service 'macaddr' (pid 693) exited with status 0
[   18.815124] [pid:1,cpu0,init]init: cannot find '/sbin/adbd', disabling 'adbd': No such file or directory
```

In dmesg.log.old, `cannot find '/sbin/adbd', disabling 'adbd'` does not appear.

I know this kernel is quite old, and it could be a weird kernel bug. So I don't expect anyone to spend much time with this. Just wanted to ask in case someone as an idea. Thank you!

[KernelSU_bugreport_2024-05-08_10_23.tar.gz](https://github.com/tiann/KernelSU/files/15245969/KernelSU_bugreport_2024-05-08_10_23.tar.gz)

### Device info

- Device: HUAWEI P8 lite 2017
- OS Version: Android 8
- KernelSU Version: 11823
- Kernel Version: 4.4.23 (am using https://github.com/riarumoda/KernelSU-4.4)

**Comment by tiann** [comment]
Your android version is too low, try change this: https://github.com/tiann/KernelSU/blob/e0267a22f81650f222e275d6383d36e805cf5da1/userspace/ksud/src/defs.rs#L32
