### ISSUE TITLE
i want help remove samsung security for s9+ kernel

### ISSUE THREAD

**Issue by egydoctor2010** [tiann/KernelSU#1715]
hi all,
i want to disable security for my samsung s9+in order to compile ksu for my device.
i tried many times with another instructions for other samsung devices but kernel always panic
so i need help please to disable security.
i uploaded my kernel source from samsung open source site and here is the link (or you can search at samsung open source site direcly by SM-G965F and download the one for this version G965FXXUHFVB4).
https://www.mediafire.com/file/m0rtxngw7i63xx5/SM-G965F_QQ_Opensource.zip/file
thanks.

**Comment by weisuofayubc** [comment]
1000$ at least

**Comment by tiann** [comment]
https://github.com/tiann/KernelSU/issues/1705#issue-2282958944
