### ISSUE TITLE
Custom build KernelSU-debug.apk not working, official apk does

### ISSUE THREAD

**Issue by powellnorma** [tiann/KernelSU#1716]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Maybe this is some safety mechanism such that only the official KernelSU Manager is recognized/allowed by the kernel?
What steps are needed to make a "custom build" KernelSU.apk work?

Official one says "Working", while my custom build one says "Not supported"

### Device info

- Device: HUAWEI P8 lite 2017
- OS Version: Android 8
- KernelSU Version: 11823
- Kernel Version: 4.4.23 (am using https://github.com/riarumoda/KernelSU-4.4)

**Comment by tiann** [comment]
#739

**Comment by powellnorma** [comment]
Can you please give some more hints on how to find the EXPECTED_SIZE and EXPECTED_HASH when building myself?
I see that I can set them in the Makefile, but how do I find the correct values for my build?

Probably I have to create a key with which I sign the .apk - But how to derive the HASH and SIZE of that key I created?
Thank you for any hints.

**Comment by tiann** [comment]
`ksud debug get-sign`
