### ISSUE TITLE
Injected app through module is in place, but doesn't work ...

### ISSUE THREAD

**Issue by Huexxx** [tiann/KernelSU#1718]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

I'm using a module to inject an app to /system.

"Same" module was working fine on the past... over Android 13 and that old KernelSU. I say "Same" because I've updated some files to a newer version of the app, tunned some permissions, etc.

Module installs fine, it does what is expected to do. Using MiXplorer or shell you can locate the files on place, but for "System  : ClassLoader" the path doesn't exist...

### Logs

Looking at the logs, files are in place... but not for "System  : ClassLoader"

- Module is properly loaded and overlay mounted. Note that fsopen() fails because it's 4.4

07-24 23:32:56.197   925   925 I KernelSU: ksud::cli: command: PostFsData
07-24 23:32:56.206   925   925 I KernelSU: ksud::utils: safemode: false
07-24 23:32:56.206   925   925 I KernelSU: ksud::utils: kernel_safemode: false
07-24 23:32:56.206   925   925 I KernelSU: ksud::module: /data/adb/post-fs-data.d not exists, skip
07-24 23:32:56.206   925   925 D KernelSU: ksud::utils: ensure_clean_dir: /data/adb/modules/
07-24 23:32:56.206   925   925 D KernelSU: ksud::utils: ensure_clean_dir: /data/adb/modules/ exists, remove it
07-24 23:32:56.291   925   925 I KernelSU: ksud::init_event: mount module image: /data/adb/ksu/modules_update.img to /data/adb/modules/
07-24 23:32:56.349   925   925 I KernelSU: ksud::mount: AutoMountExt4 drop: /data/adb/modules/, auto_umount: false
07-24 23:32:56.357   925   925 I KernelSU: ksud::profile: profile sepolicy dir not exists.
07-24 23:32:56.357   925   925 I KernelSU: ksud::mount: mount tmpfs on /debug_ramdisk
07-24 23:32:56.358   925   925 I KernelSU: ksud::module: load /data/adb/modules/lawnchair.app.unofficial system.prop
07-24 23:32:56.367   925   925 I KernelSU: ksud::mount: mount overlay for /system
07-24 23:32:56.369   925   925 I KernelSU: ksud::mount: mount overlayfs on "/system", lowerdir=/data/adb/modules/lawnchair.app.unofficial/system:/system, upperdir=None, workdir=None
07-24 23:32:56.369   925   925 W KernelSU: ksud::mount: fsopen mount failed: Function not implemented (os error 38), fallback to mount
07-24 23:32:56.370   925   925 W KernelSU: ksud::init_event: partition: system_ext lowerdir is empty
07-24 23:32:56.370   925   925 W KernelSU: ksud::init_event: partition: odm lowerdir is empty
07-24 23:32:56.370   925   925 W KernelSU: ksud::init_event: partition: oem lowerdir is empty
07-24 23:32:56.370   925   925 W KernelSU: ksud::init_event: partition: product lowerdir is empty
07-24 23:32:56.370   925   925 W KernelSU: ksud::init_event: partition: vendor lowerdir is empty
07-24 23:32:56.370   925   925 I KernelSU: ksud::utils: safemode: false
07-24 23:32:56.370   925   925 I KernelSU: ksud::utils: kernel_safemode: false
07-24 23:32:56.370   925   925 I KernelSU: ksud::module: /data/adb/post-mount.d not exists, skip

- SystemConfig and others are able to read the injected files...

05-09 15:41:15.562  1911  1985 I SystemConfig: Reading permissions from /product/etc/sysconfig/app.lawnchair-hiddenapi-package-whitelist.xml
05-09 15:41:15.671  1911  1985 I SystemConfig: Reading permissions from /product/etc/permissions/privapp-permissions-app.lawnchair.xml
05-09 15:41:15.712  1911  1911 I PackageWatchdog: Updated health check state for package app.lawnchair: INACTIVE -> PASSED
05-09 15:41:16.974  1911  1911 I PackageManager: /system/product/overlay/LawnchairOverlay.apk changed; collecting certs
05-09 15:41:17.246  1911  1911 I PackageManager: /system/product/priv-app/Lawnchair changed; collecting certs
05-09 15:41:20.160  1911  1998 W PinnerService: Could not find pinlist.meta for "/system/product/priv-app/Lawnchair/Lawnchair.apk": pinning as blob
05-09 15:41:21.166  1911  2279 D SystemServerTimingAsync: InitThreadPoolExec:Update app-ops uidState in case package app.lawnchair changed
05-09 15:41:21.166  1911  1985 D SystemServerTimingAsync: InitThreadPoolExec:Update app-ops uidState in case package app.lawnchair.overlay changed
05-09 15:41:23.233  2907  2907 I app.lawnchair: Using CollectorTypeCC GC.
05-09 15:41:23.239  2907  2907 E app.lawnchair: Not starting debugger since process cannot load the jdwp agent.
05-09 15:41:23.241  1911  2000 I ActivityManager: Start proc 2907:app.lawnchair/u0a447 for service {app.lawnchair/com.android.quickstep.TouchInteractionService}

- ... but System  : ClassLoader doesn't 'see' them:

05-09 15:41:23.326  2907  2907 W System  : ClassLoader referenced unknown path: /system/product/priv-app/Lawnchair/Lawnchair.apk
05-09 15:41:23.327  2907  2907 D nativeloader: Configuring product-clns-4 for unbundled product apk /system/product/priv-app/Lawnchair/Lawnchair.apk. target_sdk_version=34, uses_libraries=, library_path=/system/product/priv-app/Lawnchair/lib/arm64:/system/product/priv-app/Lawnchair/Lawnchair.apk!/lib/arm64-v8a:/product/lib64:/system/product/lib64, permitted_path=/data:/mnt/expand:/data/user/0/app.lawnchair:/product/lib64:/system/product/lib64
05-09 15:41:23.327  2907  2907 W linker  : Warning: unable to resolve "/system/product/priv-app/Lawnchair/Lawnchair.apk": No such file or directory (ignoring)
05-09 15:41:23.333  2907  2907 E LoadedApk: Unable to instantiate appComponentFactory
05-09 15:41:23.333  2907  2907 E LoadedApk: java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[],nativeLibraryDirectories=[/system/product/priv-app/Lawnchair/lib/arm64, /system/product/priv-app/Lawnchair/Lawnchair.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]
05-09 15:41:23.333  2907  2907 E LoadedApk: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
05-09 15:41:23.333  2907  2907 E LoadedApk: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:637)
05-09 15:41:23.333  2907  2907 E LoadedApk: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:573)
05-09 15:41:23.333  2907  2907 E LoadedApk: 	at android.app.LoadedApk.createAppFactory(LoadedApk.java:272)
05-09 15:41:23.333  2907  2907 E LoadedApk: 	at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:1043)
05-09 15:41:23.333  2907  2907 E LoadedApk: 	at android.app.LoadedApk.getClassLoader(LoadedApk.java:1130)
05-09 15:41:23.333  2907  2907 E LoadedApk: 	at android.app.LoadedApk.getResources(LoadedApk.java:1378)
05-09 15:41:23.333  2907  2907 E LoadedApk: 	at android.app.ContextImpl.createAppContext(ContextImpl.java:3330)
05-09 15:41:23.333  2907  2907 E LoadedApk: 	at android.app.ContextImpl.createAppContext(ContextImpl.java:3322)
05-09 15:41:23.333  2907  2907 E LoadedApk: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7180)
05-09 15:41:23.333  2907  2907 E LoadedApk: 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
05-09 15:41:23.333  2907  2907 E LoadedApk: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2337)
05-09 15:41:23.333  2907  2907 E LoadedApk: 	at android.os.Handler.dispatchMessage(Handler.java:107)
05-09 15:41:23.333  2907  2907 E LoadedApk: 	at android.os.Looper.loopOnce(Looper.java:232)
05-09 15:41:23.333  2907  2907 E LoadedApk: 	at android.os.Looper.loop(Looper.java:317)
05-09 15:41:23.333  2907  2907 E LoadedApk: 	at android.app.ActivityThread.main(ActivityThread.java:8490)
05-09 15:41:23.333  2907  2907 E LoadedApk: 	at java.lang.reflect.Method.invoke(Native Method)
05-09 15:41:23.333  2907  2907 E LoadedApk: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
05-09 15:41:23.333  2907  2907 E LoadedApk: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
05-09 15:41:23.333  2907  2907 W app.lawnchair: Unable to open '/system/product/priv-app/Lawnchair/Lawnchair.apk' : No such file or directory
05-09 15:41:23.333  2907  2907 W ziparchive: Unable to open '/system/product/priv-app/Lawnchair/Lawnchair.apk': No such file or directory
05-09 15:41:23.333  2907  2907 E app.lawnchair: Failed to open APK '/system/product/priv-app/Lawnchair/Lawnchair.apk': I/O error
05-09 15:41:23.334  2907  2907 W ResourcesManager: failed to preload asset path '/system/product/priv-app/Lawnchair/Lawnchair.apk'
05-09 15:41:23.334  2907  2907 W ResourcesManager: java.io.IOException: Failed to load asset path /system/product/priv-app/Lawnchair/Lawnchair.apk
05-09 15:41:23.334  2907  2907 W ResourcesManager: 	at android.content.res.ApkAssets.nativeLoad(Native Method)
05-09 15:41:23.334  2907  2907 W ResourcesManager: 	at android.content.res.ApkAssets.<init>(ApkAssets.java:303)
05-09 15:41:23.334  2907  2907 W ResourcesManager: 	at android.content.res.ApkAssets.loadFromPath(ApkAssets.java:152)
05-09 15:41:23.334  2907  2907 W ResourcesManager: 	at android.app.ResourcesManager.loadApkAssets(ResourcesManager.java:481)
05-09 15:41:23.334  2907  2907 W ResourcesManager: 	at android.app.ResourcesManager.-$$Nest$mloadApkAssets(Unknown Source:0)
05-09 15:41:23.334  2907  2907 W ResourcesManager: 	at android.app.ResourcesManager$ApkAssetsSupplier.load(ResourcesManager.java:174)
05-09 15:41:23.334  2907  2907 W ResourcesManager: 	at android.app.ResourcesManager.createApkAssetsSupplierNotLocked(ResourcesManager.java:1014)
05-09 15:41:23.334  2907  2907 W ResourcesManager: 	at android.app.ResourcesManager.getResources(ResourcesManager.java:1135)
05-09 15:41:23.334  2907  2907 W ResourcesManager: 	at android.app.LoadedApk.getResources(LoadedApk.java:1375)
05-09 15:41:23.334  2907  2907 W ResourcesManager: 	at android.app.ContextImpl.createAppContext(ContextImpl.java:3330)
05-09 15:41:23.334  2907  2907 W ResourcesManager: 	at android.app.ContextImpl.createAppContext(ContextImpl.java:3322)
05-09 15:41:23.334  2907  2907 W ResourcesManager: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7180)
05-09 15:41:23.334  2907  2907 W ResourcesManager: 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
05-09 15:41:23.334  2907  2907 W ResourcesManager: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2337)
05-09 15:41:23.334  2907  2907 W ResourcesManager: 	at android.os.Handler.dispatchMessage(Handler.java:107)
05-09 15:41:23.334  2907  2907 W ResourcesManager: 	at android.os.Looper.loopOnce(Looper.java:232)
05-09 15:41:23.334  2907  2907 W ResourcesManager: 	at android.os.Looper.loop(Looper.java:317)
05-09 15:41:23.334  2907  2907 W ResourcesManager: 	at android.app.ActivityThread.main(ActivityThread.java:8490)
05-09 15:41:23.334  2907  2907 W ResourcesManager: 	at java.lang.reflect.Method.invoke(Native Method)
05-09 15:41:23.334  2907  2907 W ResourcesManager: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
05-09 15:41:23.334  2907  2907 W ResourcesManager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
05-09 15:41:23.341  2907  2907 W ziparchive: Unable to open '/system/product/priv-app/Lawnchair/Lawnchair.apk': No such file or directory
05-09 15:41:23.342  2907  2907 E app.lawnchair: Failed to open APK '/system/product/priv-app/Lawnchair/Lawnchair.apk': I/O error
05-09 15:41:23.342  2907  2907 E ResourcesManager: failed to add asset path '/system/product/priv-app/Lawnchair/Lawnchair.apk'
05-09 15:41:23.342  2907  2907 E ResourcesManager: java.io.IOException: Failed to load asset path /system/product/priv-app/Lawnchair/Lawnchair.apk
05-09 15:41:23.342  2907  2907 E ResourcesManager: 	at android.content.res.ApkAssets.nativeLoad(Native Method)
05-09 15:41:23.342  2907  2907 E ResourcesManager: 	at android.content.res.ApkAssets.<init>(ApkAssets.java:303)
05-09 15:41:23.342  2907  2907 E ResourcesManager: 	at android.content.res.ApkAssets.loadFromPath(ApkAssets.java:152)
05-09 15:41:23.342  2907  2907 E ResourcesManager: 	at android.app.ResourcesManager.loadApkAssets(ResourcesManager.java:481)
05-09 15:41:23.342  2907  2907 E ResourcesManager: 	at android.app.ResourcesManager.-$$Nest$mloadApkAssets(Unknown Source:0)
05-09 15:41:23.342  2907  2907 E ResourcesManager: 	at android.app.ResourcesManager$ApkAssetsSupplier.load(ResourcesManager.java:174)
05-09 15:41:23.342  2907  2907 E ResourcesManager: 	at android.app.ResourcesManager.createAssetManager(ResourcesManager.java:560)
05-09 15:41:23.342  2907  2907 E ResourcesManager: 	at android.app.ResourcesManager.createResourcesImpl(ResourcesManager.java:647)
05-09 15:41:23.342  2907  2907 E ResourcesManager: 	at android.app.ResourcesManager.findOrCreateResourcesImplForKeyLocked(ResourcesManager.java:699)
05-09 15:41:23.342  2907  2907 E ResourcesManager: 	at android.app.ResourcesManager.createResources(ResourcesManager.java:1045)
05-09 15:41:23.342  2907  2907 E ResourcesManager: 	at android.app.ResourcesManager.getResources(ResourcesManager.java:1148)
05-09 15:41:23.342  2907  2907 E ResourcesManager: 	at android.app.LoadedApk.getResources(LoadedApk.java:1375)
05-09 15:41:23.342  2907  2907 E ResourcesManager: 	at android.app.ContextImpl.createAppContext(ContextImpl.java:3330)
05-09 15:41:23.342  2907  2907 E ResourcesManager: 	at android.app.ContextImpl.createAppContext(ContextImpl.java:3322)
05-09 15:41:23.342  2907  2907 E ResourcesManager: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7180)
05-09 15:41:23.342  2907  2907 E ResourcesManager: 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
05-09 15:41:23.342  2907  2907 E ResourcesManager: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2337)
05-09 15:41:23.342  2907  2907 E ResourcesManager: 	at android.os.Handler.dispatchMessage(Handler.java:107)
05-09 15:41:23.342  2907  2907 E ResourcesManager: 	at android.os.Looper.loopOnce(Looper.java:232)
05-09 15:41:23.342  2907  2907 E ResourcesManager: 	at android.os.Looper.loop(Looper.java:317)
05-09 15:41:23.342  2907  2907 E ResourcesManager: 	at android.app.ActivityThread.main(ActivityThread.java:8490)
05-09 15:41:23.342  2907  2907 E ResourcesManager: 	at java.lang.reflect.Method.invoke(Native Method)
05-09 15:41:23.342  2907  2907 E ResourcesManager: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
05-09 15:41:23.342  2907  2907 E ResourcesManager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
--------- beginning of crash
05-09 15:41:23.347  2907  2907 E AndroidRuntime: FATAL EXCEPTION: main
05-09 15:41:23.347  2907  2907 E AndroidRuntime: Process: app.lawnchair, PID: 2907
05-09 15:41:23.347  2907  2907 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Configuration android.content.res.Resources.getConfiguration()' on a null object reference
05-09 15:41:23.347  2907  2907 E AndroidRuntime: 	at android.app.ConfigurationController.updateLocaleListFromAppContext(ConfigurationController.java:273)
05-09 15:41:23.347  2907  2907 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7181)
05-09 15:41:23.347  2907  2907 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
05-09 15:41:23.347  2907  2907 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2337)
05-09 15:41:23.347  2907  2907 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
05-09 15:41:23.347  2907  2907 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:232)
05-09 15:41:23.347  2907  2907 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:317)
05-09 15:41:23.347  2907  2907 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8490)
05-09 15:41:23.347  2907  2907 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-09 15:41:23.347  2907  2907 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
05-09 15:41:23.347  2907  2907 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
05-09 15:41:23.390  1911  1927 I ActivityManager: Process app.lawnchair (pid 2907) has died: fg  CEM 
05-09 15:41:23.390  1911  1978 D DisplayManagerService: Drop pending events for gone uid 10447
05-09 15:41:23.391  1911  2005 I libprocessgroup: Successfully killed process cgroup uid 10447 pid 2907 in 0ms
05-09 15:41:23.391   941   941 I Zygote  : Process 2907 exited due to signal 9 (Killed)

### Device info

- Device: Xiaomi Mi Mix 2 (chiron)
- OS Version: CherishOS 5.5 (sec.patch 240505)
- KernelSU Version: 11838
- Kernel Version: 4.4.302

### Additional context

- KernelSU is manually integrated (I've dropped KPROBES integration after latter commits)
- Su works fine, other modules work fine
- After that error, simply updating the app (installing it from Mixplorer) solves the problem
- KernelSU bugreport attached...
[KernelSU_bugreport_2024-05-09_18_30.tar.gz](https://github.com/tiann/KernelSU/files/15265019/KernelSU_bugreport_2024-05-09_18_30.tar.gz)

**Comment by tiann** [comment]
turn off "umount by default" in settings.

Javier Vazquez ***@***.***> 于 2024年5月10日周五 上午12:44写道：
