### ISSUE TITLE
v0.9.4 causes frida spawn to crash directly

### ISSUE THREAD

**Issue by Imzpy** [tiann/KernelSU#1719]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

First, rewrite img to the phone!
On the [android12-5.10-2023-02_r1] version of the kernel using KernelSU v0.9.4 source code and compiled,
Flush to boot partition successfully, install KernelSU v0.9.4 apk, and grant adb Su permission successfully.
All of this is normal. No additional plugins installed!

When I started the spawn process with frida16.2.1, app it crashed directly, but everything was fine until then.

First, rewrite img to the phone again!
After changing to [Magisk] to get adb Su, everything is back to normal.

### Device info

- Device:Pixel 6
- OS Version:source android-12.0.0_r32
- KernelSU Version:v0.9.4
- Kernel Version:android12-5.10-2023-02_r1

**Comment by tiann** [comment]
log

**Comment by Imzpy** [comment]
> log
Sorry, when I used KernelSu BootImg to flash my phone again, everything went back to normal... I'm an idiot. I must have done something wrong

**Comment by Imzpy** [comment]
pls close issue
