### ISSUE TITLE
non root app running as root

### ISSUE THREAD

**Issue by xxjoe2** [tiann/KernelSU#1723]
i am having problems running some apps, actually those 2 play integrity checkers

when i run the either of the above mentioned apps it shows this error
![Screenshot_20240510_172927_Simple Play Integrity Checker](https://github.com/tiann/KernelSU/assets/83495134/f58c0dfc-5ae7-4dd9-88bc-edc63c4e558f)

i have seen this b4 when i had incorrectly granted root access to them. then when i read the logcat, i found the errors below

from logcat:
05-10 19:09:10.628: W/FontLog(3041): java.lang.SecurityException: Package gr.nikolasspyr.integritycheck does not belong to 10352
05-10 19:09:10.808: D/SGM:GameManager(1265): identifyForegroundApp. gr.nikolasspyr.integritycheck, mCurrentUserId: 0, callerUserId: 0
05-10 19:09:12.877: W/Finsky(18713): [1559] tjh.c(400): Different UID from the calling app: gr.nikolasspyr.integritycheck.
05-10 19:09:12.879: E/Finsky(18713): [1559] tjh.b(9): requestIntegrityToken() failed for gr.nikolasspyr.integritycheck.
05-10 19:09:12.879: E/Finsky(18713): com.google.android.finsky.integrityservice.IntegrityException: Different UID from the calling app.

the app gr.nikolasspyr.integritycheck with pid 10352 (checked) was executed as user 0, ie root. and this resulted as the last exception says, "Different UID from the calling app"

i have removed the .allowlist and reinstalled ksu managed but no luck, they still run as root automatically

any idea pls?

**Comment by tiann** [comment]
you should reboot.

**Comment by xxjoe2** [comment]
of coz i did, its stil the same, both of them

**Comment by bphd** [comment]
```logs
E/keystore2(): system/security/keystore2/src/gc.rs:139 - Error trying to delete blob entry. system/security/keystore2/src/gc.rs:129: Trying to invalidate key.
E/Finsky  (): Caused by: DisplayErrorMessage[Error retrieving information from server. DF-DFERH-01]
E/keymaster_tee(): [ [31mERR [0m]Unexpected title ignore.. title: TEE
E/Finsky  (): [94] oao.c(60): Unexpected android-id = 0
E/Volley  (): [94] kfs.a: Unexpected response code 400 for https://play-fe.googleapis.com/fdfe/integrity
E/Finsky  (): com.google.android.finsky.integrityservice.IntegrityException
```
