### ISSUE TITLE
Weird behaviour of sepolicy patcher (for modules)

### ISSUE THREAD

**Issue by MDNSSKNGHT** [tiann/KernelSU#1724]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

I made a module for Magisk that makes use of the sepolicy rules patcher to hijack camera process without needing a permissive kernel. Now I'm using KernelSU and my module completely breaks the camera server (which is why the sepolicy patches were needed). The module works if I set kernel to permissive. (using setenforce 0)

Weirdly enough ksud did not complain when applying the custom sepolicy rules.

### Expected behavior

The module should work fine without setting the kernel selinux state to permissive.

### Device info

- Device: Samsung Galaxy S21FE (SM-G990E)
- OS Version: Android 14
- KernelSU Version: commit 1f42bbac5ef3fbaf2a5497f631c5b2a57421db6d
- Kernel Version: 5.4.242

**Comment by tiann** [comment]
why not use this: https://kernelsu.org/guide/module.html#sepolicy-rule

**Comment by tiann** [comment]
And also, we only accept kernel 5.10+ issues now. https://github.com/tiann/KernelSU/issues/1705

**Comment by MDNSSKNGHT** [comment]
@tiann Hello. Thanks for responding, yes I'm using sepolicy.rule file. And is there a way for anyone to assist me on this?

**Comment by tiann** [comment]
I don't know, we developers haven't any non gki devices now.

**Comment by MDNSSKNGHT** [comment]
I see. No problem, thanks. The problem was just a matter of file permissions and ownership.
