### ISSUE TITLE
模块卸载失败，也不能手动删除

### ISSUE THREAD

**Issue by o0HalfLife0o** [tiann/KernelSU#1725]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

安装[这个模块](https://github.com/Kolass2004/Unlimited-GooglePhotosBackupMod/releases)后，模块没有生效，既不能卸载，也不能暂停，手动删除/data/adb里的模块文件夹后，手机重启又冒出来

### Screenshots

![Screenshot_2024-05-12-03-39-43-27_baaa51257c82a8b3f281ce09e6f2493f](https://github.com/tiann/KernelSU/assets/6436073/0767a596-04be-4c04-b4e7-dc5597f50275)
![Screenshot_2024-05-12-03-39-46-26_baaa51257c82a8b3f281ce09e6f2493f](https://github.com/tiann/KernelSU/assets/6436073/e6c57bef-d4b3-467f-8dc7-10e2d0568e61)

### Logs

[log](https://drive.google.com/file/d/1BBzBcHvn_ICmvJj5BqzMYI6NB2o6b7Jz/view?usp=drive_link)

### Device info

- Device: 一加ace3
- OS Version: coloros 14
- KernelSU Version: 0.9.4 11838
- Kernel Version: 5.15

**Comment by tiann** [comment]
删掉 `/data/adb/ksu/modules.img` 即可。
