### ISSUE TITLE
一加12更新11838之后termux安装包的时候报错

### ISSUE THREAD

**Issue by geniucker-dev** [tiann/KernelSU#1727]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

安装软件包的时候出现
```
E: Can not write log (Is /dev/pts mounted?) - open (13: Permission denied)
```

### To Reproduce

用termux安装软件包

### Expected behavior

不报错

### Screenshots

手里的设备只有一加12出现这个情况
![Screenshot_2024-05-12-10-22-49-90_84d3000e3f4017145260f7618db1d683](https://github.com/tiann/KernelSU/assets/165345526/73595720-7ab1-4b17-bd6f-6f35ed66e831)

![Screenshot_2024-05-12-10-49-20-82_84d3000e3f4017145260f7618db1d683](https://github.com/tiann/KernelSU/assets/165345526/1d0dc4a0-e100-4fc5-aff6-528e3890c9a5)
`/dev/pts/0`的所有者貌似和其他设备不一样，其他设备都是termux的id

### Logs

[KernelSU_bugreport_2024-05-12_11_28.tar.gz](https://github.com/tiann/KernelSU/files/15284979/KernelSU_bugreport_2024-05-12_11_28.tar.gz)

### Device info

- Device: OnePlus 12
- OS Version: 14
- KernelSU Version: 11838 LKM
- Kernel Version: 6.1.57

**Comment by abbuaus** [comment]
我遇到了相同的问题
![屏幕截图 2024-05-15 080759](https://github.com/tiann/KernelSU/assets/22835510/24ae5cbc-8fe9-47bb-b594-8aa2327fbc3c)
我遇到了相同的问题

**Comment by trialman** [comment]
相同问题, 红米 12t pro , ksu 0.9.4  

![image](https://github.com/tiann/KernelSU/assets/5611750/a8b11477-2d3c-4cd4-b533-b5cc5abb877a)
termux 
不给root权限的时候, pkg 安装正常, ssh可以正常连接

给了root权限后 , 出现  /dev/pts 权限问题, 以下为 sshd 日志
![image](https://github.com/tiann/KernelSU/assets/5611750/bda89928-2b4d-498c-a705-35b6abe1983a)

**Comment by supechicken** [comment]
同樣的情況在11854上還存在，關掉selinux就行了

```shell
~ $ su -c 'ls -laZ /dev/pts/0'
crw------- 1 u0_a560 u0_a560 u:object_r:devpts:s0 136, 0 2024-05-26 19:48 /dev/pts/0
~ $ echo 1 > /dev/pts/0
bash: /dev/pts/0: Permission denied
~ $ su -c 'setenforce 0'; echo 1 > /dev/pts/0
1
```

[KernelSU_bugreport_2024-05-26_19_45.tar.gz](https://github.com/tiann/KernelSU/files/15447310/KernelSU_bugreport_2024-05-26_19_45.tar.gz)

**Comment by BailPlus** [comment]
> 同樣的情況在11854上還存在，關掉selinux就行了
> 
> ```shell
> ~ $ su -c 'ls -laZ /dev/pts/0'
> crw------- 1 u0_a560 u0_a560 u:object_r:devpts:s0 136, 0 2024-05-26 19:48 /dev/pts/0
> ~ $ echo 1 > /dev/pts/0
> bash: /dev/pts/0: Permission denied
> ~ $ su -c 'setenforce 0'; echo 1 > /dev/pts/0
> 1
> ```
> 
> [KernelSU_bugreport_2024-05-26_19_45.tar.gz](https://github.com/tiann/KernelSU/files/15447310/KernelSU_bugreport_2024-05-26_19_45.tar.gz)
> 

关掉selinux太不安全了，有些程序压根无法启动

**Comment by DataEraserC** [comment]
LineageOS 21  (Android 14)
KernelSU version 11872 (kernel build with `tag v0.9.5` `hash b766b98513b5a7eb33bc1c4a76b5702bf1288f07`)
still has this problem

**Comment by DataEraserC** [comment]
> LineageOS 21 (Android 14) KernelSU version 11872 (kernel build with `tag v0.9.5` `hash b766b98513b5a7eb33bc1c4a76b5702bf1288f07`) still has this problem

oh maybe config conflict happened I'm wrong

**Comment by LittleChest** [comment]
这个问题在0.9.5中仍然存在

**Comment by ArvinLi163** [comment]
在安装的时候出现了同样的问题
