### ISSUE TITLE
chcon: Permission denied

### ISSUE THREAD

**Issue by Zenlua** [tiann/KernelSU#1731]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

```shell
chcon u:object_r:rootfs:s0 init.miui.rc
```

>> chcon: 'init.miui.rc' to u:object_r:rootfs:s0: Permission denied

Ksu cannot grant context "u:object_r:rootfs:s0" to file

### Device info

- Device: K20PRO
- OS Version: A14
- KernelSU Version: Latest
- Kernel Version: Latest

**Comment by tiann** [comment]
It is because `/system` is read-only.

**Comment by Zenlua** [comment]
Even when granting permissions to the file in data, it doesn't work
