### ISSUE TITLE
Can't patch boot img 

### ISSUE THREAD

**Issue by msalah-kw** [tiann/KernelSU#1739]
[KernelSU_install_log_2024-05-17-19-50-08.log](https://github.com/tiann/KernelSU/files/15354578/KernelSU_install_log_2024-05-17-19-50-08.log)

Kernel version
5.10.198-android12-9-28575149-abS908EXXU8E XE1

Android 14
OneUi 6.1
SM-S908E

**Comment by tiann** [comment]
you should uncompress the `lz4` image first.
