### ISSUE TITLE
安卓6.1内核编译

### ISSUE THREAD

**Issue by JiuGeFaCai** [tiann/KernelSU#1740]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

术哥，请问一下我编译6.1的内核为什么始终不能开机，编译命令是tools/bazel build --config=fast//common:kernel_aarch64_dist，我把编译后生成的Image镜像文件替换你官网的ak3工具进行刷入还是不能开机，内核源码我一定没有动过，安装谷歌官网教程来的，我怀疑是我用的编译后的产物用错了，具体用的是
/root/android-kernel/6.1/bazel-out/k8-fastbuild/bin/common/kernel_aarch64/Image
这个路径下的
![{143F93D7-67E9-4840-B0EC-508BFBD37B4B}](https://github.com/tiann/KernelSU/assets/99115192/66ee2bb1-828b-4edb-96c6-ff330c8ec636)

### Device info

- Device:
- OS Version:
- KernelSU Version:
- Kernel Version:

**Comment by tiann** [comment]
先搜 issue。

**Comment by JiuGeFaCai** [comment]
> 先搜问题。

搜了，编译命令用tools/bazel run --config=fast --config=stamp --lto=thin //common:kernel_aarch64_dist -- --dist_dir=dist这个也不能开机
