### ISSUE TITLE
[Feature] Support Image Lz4

### ISSUE THREAD

**Issue by ItsMadruga** [tiann/KernelSU#1743]
### Is your feature request related to a problem? Please describe.

I use a Samsung Galaxy A54, and its boot image, or init_boot, is compressed as lz4, and it is not possible to patch the image through the application because of this, it keeps giving a decompression error.

### Describe the solution you'd like.

I strongly ask you to add patch support in images compressed like lz4, I don't understand much, so I apologize for any stupidity

### Describe alternatives you've considered.

I've already tried using programs like lz4 to decompress the image and then patch it through the application, but as I can't flash an .img but only .lz4, I have to compress it again, and that way it gets corrupted.

**Comment by rsuntk** [comment]
Unpack the lz4 archive and patch it. Also, if you use ODIN to flash your phone, then repack it to tarball file (without compress it to lz4 again) and it should work.

**Comment by tiann** [comment]
As far as i know, odin and heimdall both support boot.img without lz4.
