### ISSUE TITLE
version release bug

### ISSUE THREAD

**Issue by Hussein995** [tiann/KernelSU#1759]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

after updating to latest release it keeps giving errors while compiling

### Logs

Run export PATH=$HOME/:$PWD/toolchain/bin:$PATH
ln: failed to create symbolic link '/home/runner/python': File exists
mkdir: cannot create directory ‘out’: File exists

[i] Building KernelSU...

build_kernel.sh: line 190: replace_config_option: command not found

[+] Compiling KernelSU + Enforcing..

make: ./scripts/clang-android.sh: No such file or directory
#
# configuration written to .config
#
make: ./scripts/clang-android.sh: No such file or directory
make[1]: ./scripts/clang-android.sh: No such file or directory
scripts/kconfig/conf  --silentoldconfig Kconfig
make: ./scripts/clang-android.sh: No such file or directory
  CHK     include/config/kernel.release
  CHK     include/generated/uapi/linux/version.h
-- KernelSU version: 10201
-- KernelSU Manager signature size: 0x033b
-- KernelSU Manager signature hash: c3[7](https://github.com/Hussein995/N975F/actions/runs/9201873094/job/25310763660#step:6:8)1061b19d8c7d7d6133c6a9bafe198fa944e50c1b31c9d8daa8d7f1fc2d2d6
  CHK     include/generated/utsrelease.h
  CHK     scripts/mod/devicetable-offsets.h
  CHK     include/generated/timeconst.h
  CHK     include/generated/bounds.h
  CHK     include/generated/asm-offsets.h
  CALL    scripts/checksyscalls.sh
  CHK     include/generated/compile.h
  CC      fs/open.o
  CC      fs/read_write.o
  CC      fs/stat.o
  CHK     kernel/config_data.h
  CC      fs/exec.o
  CC      security/selinux/hooks.o
  CC      security/selinux/selinuxfs.o
  CC      security/selinux/ss/services.o
  AR      fs/built-in.o
  CC      security/selinux/ss/status.o
  AR      security/selinux/selinux.o
  AR      security/selinux/built-in.o
  AR      security/built-in.o
  CC      drivers/input/input.o
-- KernelSU version: 10201
-- KernelSU Manager signature size: 0x033b
-- KernelSU Manager signature hash: c371061b19d[8](https://github.com/Hussein995/N975F/actions/runs/9201873094/job/25310763660#step:6:9)c7d7d6133c6a9bafe198fa944e50c1b31c9d8daa8d7f1fc2d2d6
  CC      drivers/kernelsu/ksu.o
drivers/kernelsu/ksu.c:[9](https://github.com/Hussein995/N975F/actions/runs/9201873094/job/25310763660#step:6:10)7:18: error: a parameter list without types is only allowed in a function definition
MODULE_IMPORT_NS(VFS_internal_I_am_really_a_filesystem_and_am_NOT_a_driver);
                 ^
1 error generated.
make[2]: *** [scripts/Makefile.build:356: drivers/kernelsu/ksu.o] Error 1
make[1]: *** [scripts/Makefile.build:671: drivers/kernelsu] Error 2
make[1]: *** Waiting for unfinished jobs....
  AR      drivers/input/input-core.o
  AR      drivers/input/built-in.o
make: *** [Makefile:[12](https://github.com/Hussein995/N975F/actions/runs/9201873094/job/25310763660#step:6:13)97: drivers] Error 2
make: *** Waiting for unfinished jobs....
Error: Process completed with exit code 1.

### Device info

- Device: N975F
- OS Version: 14
- KernelSU Version: LATEST
- Kernel Version:  4.14.114

**Comment by tiann** [comment]
There is a guard here, so why your 4.14 kernel will hit this?

https://github.com/tiann/KernelSU/blob/main/kernel/ksu.c#L98

check your source first.

**Comment by wu17481748** [comment]
> 这里有一个守卫，那么为什么你的 4.14 内核会击中这个呢？
> 
> https://github.com/tiann/KernelSU/blob/main/kernel/ksu.c#L98
> 
> 首先检查您的来源。


KernelSU 版本：最新
内核版本：4.14.186

也出现这个问题

../drivers/kernelsu/ksu.c:97:18: error: a parameter list without types is only allowed in a function definition
MODULE_IMPORT_NS(VFS_internal_I_am_really_a_filesystem_and_am_NOT_a_driver);                      ^

**Comment by strec007** [comment]
I'm also getting similar error:
```
-- KernelSU version: 11895
-- KernelSU Manager signature size: 0x033b
-- KernelSU Manager signature hash: c371061b19d8c7d7d6133c6a9bafe198fa944e50c1b31c9d8daa8d7f1fc2d2d6

...

../../../../../../kernel/fairphone/sm7225/KernelSU/kernel/ksu.c:97:1: error: type specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
MODULE_IMPORT_NS(VFS_internal_I_am_really_a_filesystem_and_am_NOT_a_driver);
^
int
../../../../../../kernel/fairphone/sm7225/KernelSU/kernel/ksu.c:97:18: error: a parameter list without types is only allowed in a function definition
MODULE_IMPORT_NS(VFS_internal_I_am_really_a_filesystem_and_am_NOT_a_driver);
                 ^
2 errors generated.
make[3]: *** [/srv/src/LINEAGE_21_0/kernel/fairphone/sm7225/scripts/Makefile.build:338: drivers/kernelsu/ksu.o] Error 1
make[2]: *** [/srv/src/LINEAGE_21_0/kernel/fairphone/sm7225/scripts/Makefile.build:642: drivers/kernelsu] Error 2
```

Is there any workaround to be able to compile? Thank you.

**Comment by vanshsantoshi** [comment]
@strec007 @wu17481748 

Solution to that written here:
https://github.com/tiann/KernelSU/issues/1972
