### ISSUE TITLE
安卓6.1内核编译

### ISSUE THREAD

**Issue by JiuGeFaCai** [tiann/KernelSU#1768]
### Describe your problem.

术哥，我搜了lssues，根据你的action编译方法，用的 tools/bazel run --config=fast --config=stamp --lto=thin //common:kernel_aarch64_dist -- --dist_dir=dist编译命令，可是刷入手机还是不能开机啊

**Comment by tiann** [comment]
action 代码都是公开的，为什么 ci 编译能开机你自己不能，你得着你自己的原因。
