### ISSUE TITLE
Build error :error: initializer element is not constant

### ISSUE THREAD

**Issue by bsy001** [tiann/KernelSU#1770]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

When I am building my kernel on Android-x86 with kernelsu.The gcc give  me error,it tell:"
`/kernel/drivers/kernelsu/allowlist.c:27:8: error: initializer element is not constant
/kernel/drivers/kernelsu/allowlist.c:27:8: error: (near initialization for 'allowlist_mutex.wait_lock')`
" ,what can I do ,thanks.
tips: I am not good at English , so if I speak not right , I am sorry.  

### Expected behavior

build success

### Logs

android-x86/kernel/drivers/kernelsu/allowlist.c:26:15: error: initializer element is not constant
android-x86/kernel/drivers/kernelsu/allowlist.c:26:15: error: (near initialization for 'allowlist_mutex.wait_lock')
cc1: warning: unrecognized command line option "-Wno-gcc-compat" [enabled by default]
cc1: warning: unrecognized command line option "-Wno-int-conversion" [enabled by default]
make[3]: *** [android-x86/kernel/scripts/Makefile.build:333: drivers/kernelsu/allowlist.o] Error 1
make[2]: *** [android-x86/kernel/scripts/Makefile.build:637: drivers/kernelsu] Error 2
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [android-x86/kernel/Makefile:1171: drivers] Error 2
make[1]: Leaving directory 'android-x86/out/target/product/x86_64/obj/kernel'
make: *** [Makefile:146: sub-make] Error 2
make: Leaving directory 'android-x86/kernel'
ninja: build stopped: subcommand failed.
20:42:19 ninja failed with: exit status 1

### Device info

- Device:android-x86
- OS Version:pie-x86
- KernelSU Version:11838
- Kernel Version:i do not know

**Comment by tiann** [comment]
Nothing to do with KernelSU, maybe you should try another compiler.
