### ISSUE TITLE
throne_tracker.c building error

### ISSUE THREAD

**Issue by Pr0pHesyer** [tiann/KernelSU#1771]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Unofficial kernel building error.
Used kernel:https://github.com/LineageOS/android_kernel_xiaomi_msm8998
Building error:
/home/runner/work/Android-Builder/Android-Builder/Mi6/drivers/kernelsu/throne_tracker.c:173:54: error: too many arguments to function call, expected 2, have 3
                        unsigned int hash = full_name_hash(NULL, dirpath, strlen(dirpath));
                                            ~~~~~~~~~~~~~~                ^~~~~~~~~~~~~~~
/home/runner/work/Android-Builder/Android-Builder/Mi6/include/linux/dcache.h:89:21: note: 'full_name_hash' declared here
extern unsigned int full_name_hash(const unsigned char *, unsigned int);
                    ^
1 error generated.
make[3]: *** [/home/runner/work/Android-Builder/Android-Builder/Mi6/scripts/Makefile.build:292: drivers/kernelsu/throne_tracker.o] Error 1
make[2]: *** [/home/runner/work/Android-Builder/Android-Builder/Mi6/scripts/Makefile.build:527: drivers/kernelsu] Error 2
make[1]: *** [/home/runner/work/Android-Builder/Android-Builder/Mi6/Makefile:1080: drivers] Error 2

Detail in https://github.com/Pr0pHesyer/Android-Builder/actions/runs/9243917807/job/25428620808

### To Reproduce

1. clone kernel source
2. get toolchains
3. start build

### Expected behavior

Finish and output without error.

### Screenshots

_No response_

### Logs

```
/home/runner/work/Android-Builder/Android-Builder/Mi6/drivers/kernelsu/throne_tracker.c:173:54: error: too many arguments to function call, expected 2, have 3
                        unsigned int hash = full_name_hash(NULL, dirpath, strlen(dirpath));
                                            ~~~~~~~~~~~~~~                ^~~~~~~~~~~~~~~
/home/runner/work/Android-Builder/Android-Builder/Mi6/include/linux/dcache.h:89:21: note: 'full_name_hash' declared here
extern unsigned int full_name_hash(const unsigned char *, unsigned int);
                    ^
1 error generated.
make[3]: *** [/home/runner/work/Android-Builder/Android-Builder/Mi6/scripts/Makefile.build:292: drivers/kernelsu/throne_tracker.o] Error 1
make[2]: *** [/home/runner/work/Android-Builder/Android-Builder/Mi6/scripts/Makefile.build:527: drivers/kernelsu] Error 2
make[1]: *** [/home/runner/work/Android-Builder/Android-Builder/Mi6/Makefile:1080: drivers] Error 2
make[1]: *** Waiting for unfinished jobs....
```

### Device info

- Device:sagit
- OS Version:lineage os 21
- KernelSU Version:git latest version
- Kernel Version:4.4.302


### Additional context

Use https://github.com/DogDayAndroid/Android-Builder
Detail in https://github.com/Pr0pHesyer/Android-Builder/actions/runs/9243917807/job/25428620808

**Comment by Pr0pHesyer** [comment]
Another trial:
Local machine,same kernel,but toolchains:https://github.com/kdrag0n/proton-clang,use`curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -`.
Error:
`../drivers/kernelsu/sucompat.c:331:40: error: use of undeclared identifier 'real_regs'
        inode = (struct inode *)PT_REGS_PARM1(real_regs);
                                              ^
1 error generated.
make[3]: *** [../scripts/Makefile.build:292: drivers/kernelsu/sucompat.o] Error 1`

**Comment by rsuntk** [comment]
Use main branch or add this commit [7af4f33](https://github.com/tiann/KernelSU/commit/7af4f338e56cce386ba0dccdc0871b687cd697b1)

**Comment by Pr0pHesyer** [comment]
Received,sucompat.c was fix in main.
#1773 will be tested as soon.

**Comment by Pr0pHesyer** [comment]
Worked after merging #1773.

**Comment by sahidmaulana053-sudo** [comment]
Guwa ga ngrti
