### ISSUE TITLE
编译 6.1 内核，执行提供的命令后WiFi能打开，但移动数据仍然无法打开

### ISSUE THREAD

**Issue by abbuaus** [tiann/KernelSU#1776]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

自己编译的6.1 内核打不开移动数据
本来连wifi都打不开，执行了 rm common/android/abi_gki_protected_exports_*
然后WiFi可以打开了，但是数据依然打不开

### Device info

- Device: 小米14pro
- OS Version:
- KernelSU Version:
- Kernel Version:

**Comment by tiann** [comment]
这跟 KernelSU 有什么关系？
