### ISSUE TITLE
[Feature] QoL features for managing the sparse image.

### ISSUE THREAD

**Issue by RaXorX** [tiann/KernelSU#1777]
### Is your feature request related to a problem? Please describe.

I install a module and then see that the sparse file has blown out of proportion once again. Yes, I'm aware it's a sparse image and does not reflect actual file size, but recovery says so, and since taking a "data" partition is usually a task done being in recovery. It'd be awesome if...

### Describe the solution you'd like.

- [ x ] ~~There's an option to reduce the sparse image file size. (Already there)~~
- [ ] There's an option to automatically reduce the sparse image file after installing a module.
- [ ] There's an option to manually resize the sparse image file through the manager.
- [ ] If it's possible to reverse the resizing. Though this happens if you reinstall a new module or remove one. But if the manager could trigger this automatically, that's another thing.

### Describe alternatives you've considered.

-

**Comment by tiann** [comment]
https://github.com/tiann/KernelSU/issues/1705#issue-2282958944

**Comment by LeeBinder** [comment]
@RaXorX it would make more sense to add this into the [Discussions section](https://github.com/tiann/KernelSU/discussions)
