### ISSUE TITLE
[Feature] Repositories

### ISSUE THREAD

**Issue by CanerKaraca23** [tiann/KernelSU#1778]
### Is your feature request related to a problem? Please describe.

-

### Describe the solution you'd like.

webui was cool, devs started to add webui support to their modules. Now let's think bigger.

What about bring a section for module repositories like old times? Just like iOS jailbreak managers and LSPosed.

You will add a repository and you can see all of the modules in it, description of module, changelog of module and you will get notification when a module updated. Also i think it will be good for security.

Maybe someone see this idea as foolish or unnecessary. But i think it will be good for community.

### Describe alternatives you've considered.

-

**Comment by tiann** [comment]
https://github.com/tiann/KernelSU/issues/1705#issue-2282958944

**Comment by DerGoogler** [comment]
There serval manager out there, like MRepo or MMRL

**Comment by LeeBinder** [comment]
@CanerKaraca23 it would make more sense to add this into the [Discussions section](https://github.com/tiann/KernelSU/discussions) here

**Comment by DerGoogler** [comment]
@CanerKaraca23, you don't know how hard it is to maintain such a repo.

You'll require:

- Guidelines (follow module format etc)
- Admins, moderators etc
- Approval & Takedown system
- Automation for module updates

This is done my third-party apps like MRepo and MMRL, those are build specifically for this kind of thing. 

Magisk, KernelSU etc should handle the root, nothing more
