### ISSUE TITLE
Running pm from Termux fails

### ISSUE THREAD

**Issue by larena1** [tiann/KernelSU#1784]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

https://github.com/bmax121/APatch/issues/192
https://github.com/topjohnwu/Magisk/commit/488c5a307a813f304b7e28b7d5324e1ead6f09f7

I think it used to work before at some point using KSU but somehow it currently does not. APatch fixed it a while ago and Magisk always worked. Can you fix it too?

### Device info

- Device:
- OS Version: 14
- KernelSU Version: 11838
- Kernel Version: 5.15

**Comment by Hellohi3654** [comment]
Yes have same issue

**Comment by meiser79** [comment]
https://kernelsu.org/guide/how-to-integrate-for-non-gki.html#failed-to-execute-pm-in-terminal

**Comment by aviraxp** [comment]
Should get fixed after https://github.com/tiann/KernelSU/commit/31653b11f13284ca4711b11cdbb2c1e754cd7778

**Comment by trialman** [comment]
![image](https://github.com/tiann/KernelSU/assets/5611750/e9f00771-2578-4a14-b5a3-ff818befa2dd)
![image](https://github.com/tiann/KernelSU/assets/5611750/f7cc3ce1-c5a1-4e41-997d-1b6d9d3e22d1)
latest version still not working

**Comment by privacyguy123** [comment]
Same error on non GKI - the Termux packages install fine but complain about ```/dev/pts``` not mounted.

**Comment by aviraxp** [comment]
@larena1 does it work with GKI？

**Comment by gxFs7** [comment]
I’m using a GKI kernel, and I attempted to apply the modification mentioned in the KernelSU non-GKI integration guide (https://kernelsu.org/guide/how-to-integrate-for-non-gki.html#failed-to-execute-pm-in-terminal) to fix the pm and am command issues. However, the problem still persists.

What concerns me is that this error affects some of my important applications and add-ons, so it’s becoming a real limitation.

Here is my kernel source for reference:
👉 https://github.com/ravindu644/android_kernel_a165f

The issue looks like this in Termux:
~ $ su
:/data/data/com.termux/files/home $ pm
cmd: Failure calling service package: Failed transaction (2147483646)

I would really appreciate any guidance or suggestions to resolve this problem.
