### ISSUE TITLE
Compilation failed msm-4.4 kernel

### ISSUE THREAD

**Issue by GhostMaster69-dev** [tiann/KernelSU#1791]
-- KernelSU version: 11874
-- KernelSU Manager signature size: 0x033b
-- KernelSU Manager signature hash: c371061b19d8c7d7d6133c6a9bafe198fa944e50c1b31c9d8daa8d7f1fc2d2d6
  CC      drivers/kernelsu/kernel/ksu.o
../drivers/kernelsu/kernel/ksu.c:97:1: error: type specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
   97 | MODULE_IMPORT_NS(VFS_internal_I_am_really_a_filesystem_and_am_NOT_a_driver);
      | ^
      | int
../drivers/kernelsu/kernel/ksu.c:97:18: error: a parameter list without types is only allowed in a function definition
   97 | MODULE_IMPORT_NS(VFS_internal_I_am_really_a_filesystem_and_am_NOT_a_driver);
      |                  ^
2 errors generated.

**Comment by strec007** [comment]
I have the same issue. How did you fix it? Thanks.

**Comment by GhostMaster69-dev** [comment]
> I have the same issue. How did you fix it? Thanks.

Non Gki support removed so use previous version or just revert commits to add Non GKI support back.

**Comment by vanshsantoshi** [comment]
Wrote 3 possible solutions to this in short
https://github.com/tiann/KernelSU/issues/1972
