### ISSUE TITLE
开机核心频率吃满

### ISSUE THREAD

**Issue by QiuFenyyds** [tiann/KernelSU#1793]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [x] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

k50pro今天更新1.0.0版本出现的问题

### Expected behavior

修复问题

### Screenshots

![Screenshot_2024-06-02-07-30-39-894_com omarea vtools](https://github.com/tiann/KernelSU/assets/95760988/94433020-8dd0-4a20-bd28-4db5e0d67fb9)

### Logs

[KernelSU_bugreport_2024-06-02_07_38.tar.gz.zip](https://github.com/user-attachments/files/15523663/KernelSU_bugreport_2024-06-02_07_38.tar.gz.zip)

### Device info

- Device: Redmi k50pro
- OS Version: HyperOS1.0.2
- KernelSU Version:11874
- Kernel Version:5.10.168-android12-9-00001-g81e7418c6466-ab10486262

**Comment by tiann** [comment]
模块的问题，请自行排查。
