### ISSUE TITLE
VIVO系列新机器好像都不支持LKM模式

### ISSUE THREAD

**Issue by qianmo-xw** [tiann/KernelSU#1797]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

使用最新的管理器1.0.0去修补init_boot后刷入   依然显示未安装     使用magisk修补就可以获得权限

### Expected behavior

获取权限

### Device info

- Device: VIVO X90
- OS Version: PD2241B_A_13.0.15.10
- KernelSU Version: 1.0.0
- Kernel Version: 5.15.41-android13-8-g55b418225194-dirty

**Comment by qianmo-xw** [comment]
https://wwf.lanzout.com/b0foig5pe
密码:1hc0    这是用到的文件和Log

**Comment by qianmo-xw** [comment]
> https://wwf.lanzout.com/b0foig5pe 密码:1hc0 这是用到的文件和Log

修补的是init_boot  boot不知道有没有用顺便传上来了

**Comment by RinLin-NYA** [comment]
vivo系设备没有办法通过ksu/ap来获得su，它们的seccomp里有额外设置阻止其运行

**Comment by bb33bb** [comment]
> vivo系设备没有办法通过ksu/ap来获得su，它们的seccomp里有额外设置阻止其运行

能提示下在哪里不，我也遇到了相同的问题。望老哥能指点下。

**Comment by tiann** [comment]
#1289

**Comment by NULL204** [comment]
魅族20Pro遇到了相同的问题，不同的是，使用0.9.4版本的LKM可以正常工作，0.9.5以及1.0.0版本的都无法工作。
我可能问了蠢问题，但是希望能有热心的老哥回答一下我的疑惑，谢谢了
