### ISSUE TITLE
kernel su 管理器中显示未激活，但是模块正常使用

### ISSUE THREAD

**Issue by youlvlv** [tiann/KernelSU#1800]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

更新了 1.0 版本的 kernel su 后，重新刷入 kernel su 后重启，kernel su 管理器中提示未激活，但是模块被成功挂载了，root 也正常获取了

### To Reproduce

1.  从 0.94 更新到 1.0 版本管理器
2. 刷入 kernel su
3. 重启提示未激活

### Expected behavior

显示激活

### Screenshots

![S40603-20292763_me weishu kernelsu](https://github.com/tiann/KernelSU/assets/53246349/27626682-823c-4565-902f-5eac81ebe51f)
![S40603-20291989_org lsposed manager](https://github.com/tiann/KernelSU/assets/53246349/6fbcb422-f873-4175-b685-9f27768c52f5)

### Device info

- Device: meizu 20 pro
- OS Version:flyme 10.5.5.1
- KernelSU Version: 1.0
- Kernel Version: 
5.15.94-android13-8-g6701334c485e-ab17001233086

**Comment by aviraxp** [comment]
Need dmesg when boot.

**Comment by youlvlv** [comment]
> Need dmesg when boot.
What should I do?

**Comment by youlvlv** [comment]
> Need dmesg when boot.

What should I do?

**Comment by youlvlv** [comment]
> Need dmesg when boot.

kernel su is already working, but shows no activation in the manager。I can use the module and root permissions normally

**Comment by aviraxp** [comment]
https://t.me/hwrtools/10

**Comment by youlvlv** [comment]
[boot-2024-06-06-09-00-54.log](https://github.com/user-attachments/files/15598369/boot-2024-06-06-09-00-54.log)

**Comment by aviraxp** [comment]
可能需要一下打开管理器时，dmesg的输出

**Comment by youlvlv** [comment]
> 可能需要一下打开管理器时，dmesg的输出

这个要怎么做呢？

**Comment by Kudryavka03** [comment]
应该是所有魅族的设备都出现这个问题了。
退回Ver0.9.4正常，0.9.5起管理器显示未激活了，但Root权限，模块，一切正常工作

**Comment by youlvlv** [comment]
> 应该是所有魅族的设备都出现这个问题了。
> 退回Ver0.9.4正常，0.9.5起管理器显示未激活了，但Root权限，模块，一切正常工作

需要把 boot 也回退至 0.94 嘛？

**Comment by youlvlv** [comment]
> 可能需要一下打开管理器时，dmesg的输出

还需要什么信息嘛？

**Comment by Kudryavka03** [comment]
宽容SELinux后开两次管理器就能正常识别到工作中
![de4fb77e5c5e3a1d0567e54619083017](https://github.com/tiann/KernelSU/assets/23144521/09209543-8d1b-4a75-9cfb-474c8dfd13ef)
再次改为严格后，管理器依然工作
![8ac9297745c57f3429250af2704751e2_720](https://github.com/tiann/KernelSU/assets/23144521/a575992c-f0d9-480a-ac80-372d3b2338c3)

**Comment by HHH3366** [comment]
啊！？😂

**Comment by youlvlv** [comment]
> 宽容SELinux后开两次管理器就能正常识别到工作中 ![de4fb77e5c5e3a1d0567e54619083017](https://private-user-images.githubusercontent.com/23144521/340575861-09209543-8d1b-4a75-9cfb-474c8dfd13ef.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2OTYxMTAsIm5iZiI6MTcxODY5NTgxMCwicGF0aCI6Ii8yMzE0NDUyMS8zNDA1NzU4NjEtMDkyMDk1NDMtOGQxYi00YTc1LTljZmItNDc0YzhkZmQxM2VmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDA3MzAxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyNWEyNmYwYTEwNzc4NGEzMjg5NDI0NjhkMzIxZGY2NzFlZTNlMjI4NTZlZTliZWQ1YmM2MWEzNmRkNDUyYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6OTlGgxFnIZ1n_2HKW_klsFxgI4ETwwV8HzU-uTji1E) 再次改为严格后，管理器依然工作 ![8ac9297745c57f3429250af2704751e2_720](https://private-user-images.githubusercontent.com/23144521/340575941-a575992c-f0d9-480a-ac80-372d3b2338c3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2OTYxMTAsIm5iZiI6MTcxODY5NTgxMCwicGF0aCI6Ii8yMzE0NDUyMS8zNDA1NzU5NDEtYTU3NTk5MmMtZjBkOS00ODBhLWFjODAtMzcyZDNiMjMzOGMzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDA3MzAxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmYmI2YjE5NGUwNjg5YWNlMTA5NWUzODYyYTlmZTJiYTA2YjllYmVlMDVlZmY1MGZlYzlmMTg2ZjY2MWRiMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vbuIBGzqBR5m5ia0rSlfTgxveulhOo_6YTql8vWGT94)

我尝试了一下，还是没有成功，修改后需要重启么？

**Comment by Kudryavka03** [comment]
> > 宽容SELinux后开两次管理器就能正常识别到工作中 ![de4fb77e5c5e3a1d0567e54619083017](https://private-user-images.githubusercontent.com/23144521/340575861-09209543-8d1b-4a75-9cfb-474c8dfd13ef.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2OTYxMTAsIm5iZiI6MTcxODY5NTgxMCwicGF0aCI6Ii8yMzE0NDUyMS8zNDA1NzU4NjEtMDkyMDk1NDMtOGQxYi00YTc1LTljZmItNDc0YzhkZmQxM2VmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDA3MzAxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyNWEyNmYwYTEwNzc4NGEzMjg5NDI0NjhkMzIxZGY2NzFlZTNlMjI4NTZlZTliZWQ1YmM2MWEzNmRkNDUyYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6OTlGgxFnIZ1n_2HKW_klsFxgI4ETwwV8HzU-uTji1E) 再次改为严格后，管理器依然工作 ![8ac9297745c57f3429250af2704751e2_720](https://private-user-images.githubusercontent.com/23144521/340575941-a575992c-f0d9-480a-ac80-372d3b2338c3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2OTYxMTAsIm5iZiI6MTcxODY5NTgxMCwicGF0aCI6Ii8yMzE0NDUyMS8zNDA1NzU5NDEtYTU3NTk5MmMtZjBkOS00ODBhLWFjODAtMzcyZDNiMjMzOGMzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDA3MzAxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmYmI2YjE5NGUwNjg5YWNlMTA5NWUzODYyYTlmZTJiYTA2YjllYmVlMDVlZmY1MGZlYzlmMTg2ZjY2MWRiMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vbuIBGzqBR5m5ia0rSlfTgxveulhOo_6YTql8vWGT94)
> 
> 我尝试了一下，还是没有成功，修改后需要重启么？

不要重启，多开几次也许就好了（）
kmsg中会有KernelSU的日志，提示找到了管理器的
感觉是有不明的SELinux策略阻止了Manager对tmpfs的访问？

**Comment by Kudryavka03** [comment]
魅族在/data/app目录中有一个文件，名叫default_cow，这个文件夹上下文是install_data_file
然后ksu_filp_open_compat打开这个目录的时候，会被SELinux阻止，然后就不再继续搜寻下去了
>avc:  denied  { read } for  comm="PackageManager" name="default_cow" dev="dm-55" ino=276 scontext=u:r:system_server:s0 tcontext=u:object_r:install_data_file:s0 tclass=dir permissive=0

应该就是系统自带的selinux规则阻止了
通过ksud给selinux打补丁 `ksud sepolicy patch "allow system_server install_data_file dir  {read open}"` 后顺利找到manager。
所以search_manager在搜索管理器的时候，遇到错误的时候是不是应该不要返回而是继续搜索下去呢？
@youlvlv 试试看用ksud给SELinux规则打一下补丁

**Comment by HHH3366** [comment]
@Kudryavka03 呃~他应该只能做到发现问题（俺也一样😂）

**Comment by pomelohan** [comment]
可以尝试加到这里：https://github.com/tiann/KernelSU/blob/main/kernel/selinux/rules.c#L124

```
ksu_allow(db, "system_server", "install_data_file", "dir", "open");
ksu_allow(db, "system_server", "install_data_file", "dir", "read");
```
