### ISSUE TITLE
不支持 begonia （kernel 4.14），voltage os Android 14 (qpr2 update)

### ISSUE THREAD

**Issue by kodhh** [tiann/KernelSU#1806]
### Describe your problem.

不支持 begonia （kernel 4.14），voltage os Android 14 (qpr2 update)，而且magisk似乎也有问题。
[Not able to enable zygisk on voltage os Android 14 (qpr2)](https://github.com/topjohnwu/Magisk/issues/8050)
这要怎么解决？

**Comment by natsumerinchan** [comment]
898e9d4f8ca9b2f46b0c6b36b80a872b5b88d899 低于5.10的内核已经不再支持
