### ISSUE TITLE
Build Manager工作流中的ksud-x86_64-pc-windows-gnu无法使用外置LKM模块

### ISSUE THREAD

**Issue by dishuo183** [tiann/KernelSU#1809]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

- Install Error: Unknown KMI, please choose LKM manually
[ERROR ksud::cli] Error: Unknown KMI, please choose LKM manually

    Caused by:
        Unsupported platform
Error: Unknown KMI, please choose LKM manually

Caused by:
    Unsupported platform

### To Reproduce

1. 在Build Manager工作流的[#1595](https://github.com/tiann/KernelSU/actions/runs/9232469762)及以后的所有ksud-x86_64-pc-windows-gnu都无法使用(之前的可以)以下命令修补我的init_boot
  `ksud.exe boot-patch -m android13-5.15_kernelsu.ko -b init_boot.img --magiskboot magiskboot.exe`
2. 无法通过-m选项使用外置LKM模块，提示未知KMI。但可以使用--kmi选项使用内置的KMI版本
3. 经测试使用-m选项修补小米14U的init_boot仍提示未知KMI

### Expected behavior

希望修复无法使用的问题

### Screenshots

![PixPin_2024-06-05_13-54-36](https://github.com/tiann/KernelSU/assets/79615197/cd065175-acff-479c-bb01-70f2bc965103)

### Device info

- Device: Redmi K70
- OS Version: 1.0.16
- KernelSU Version: v1.0.0(11874)
- Kernel Version: 5.15.123-android13-8-00008

**Comment by tiann** [comment]
添加参数 `--kmi <KMI`

**Comment by tiann** [comment]
建议你用 WSL，我不用 Windows。

**Comment by dishuo183** [comment]
好的，谢谢
