### ISSUE TITLE
/system/bin/su: No such file or directory

### ISSUE THREAD

**Issue by shandongtlb** [tiann/KernelSU#1813]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

![Screenshot_20240609_000358_NetHunter Terminal](https://github.com/tiann/KernelSU/assets/40312509/665826f9-4cc7-4422-8539-1d9009f84f81)
之前还好好的，更新了1.0之后就这样了，dmesg没发现异常
其他终端类app均提示无su，使用mt浏览器也未发现有su
内核官网gki模式，自编译gki以及lkm模式均复现

### Device info

- Device: s23u
- OS Version: oneui5.1
- KernelSU Version: 1.0
- Kernel Version: 5.15.78 gki

**Comment by tiann** [comment]
你装的是不是 32 位的应用

**Comment by shandongtlb** [comment]
貌似是system挂载只读导致的，可是刷了读写模块还不行

**Comment by shandongtlb** [comment]
> 你装的是不是 32 位的应用

你指的是ksu的APP32位吗，貌似只有64一个版本
其他终端类都是64的

**Comment by shandongtlb** [comment]
> 你装的是不是 32 位的应用

我专门看了一下，就算模块已经挂载读写，/system/bin/里面也没有su

**Comment by tiann** [comment]
su 文件本来就不存在。你直接运行 /system/bin/su 是什么结果？

**Comment by natsumerinchan** [comment]
v1.0.0发布时还没有 78bf2493bf2b92a12636a4ec64ded21e33644441 这个提交，你试试安装ci版本的

**Comment by shandongtlb** [comment]
> su 文件本来就不存在。你直接运行 /system/bin/su 是什么结果？

![Screenshot_20240609_112707_NetHunter Terminal](https://github.com/tiann/KernelSU/assets/40312509/5171fec6-0b2f-44a4-9f8c-fe13b4440848)

not found

**Comment by shandongtlb** [comment]
换了几个APP，都一样的结果

**Comment by shandongtlb** [comment]
juicessh和termux 都不行
![Screenshot_20240609_113825_Termux](https://github.com/tiann/KernelSU/assets/40312509/d1a535cd-dbbc-47db-ac02-1391009d16db)

**Comment by fsxitutu** [comment]
> juicessh和termux 都不行 ![Screenshot_20240609_113825_Termux](https://private-user-images.githubusercontent.com/40312509/337945166-d1a535cd-dbbc-47db-ac02-1391009d16db.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNzE2NzksIm5iZiI6MTcxODA3MTM3OSwicGF0aCI6Ii80MDMxMjUwOS8zMzc5NDUxNjYtZDFhNTM1Y2QtZGJiYy00N2RiLWFjMDItMTM5MTAwOWQxNmRiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDAyMDI1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0NzcwZjE2MzEwNjExNTQ5MTU1MDk4ZTk3MDhiMmIyMGIxYTIyM2FhMWIxMjFkMDFmNjAzNGE3MzUzODcwOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Tw3Q2gXI86rrDOLeGphxc7t8ssVKUf2bUAzBwPkebXI)

如果你是使用termux的google play版本，请换回f-droid版本。实测google play版本在termux环境内无法识别kernelsu的su命令(failsafe环境可使用su)。

**Comment by shandongtlb** [comment]
> > juicessh和termux 都不行 ![Screenshot_20240609_113825_Termux](https://private-user-images.githubusercontent.com/40312509/337945166-d1a535cd-dbbc-47db-ac02-1391009d16db.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNzE2NzksIm5iZiI6MTcxODA3MTM3OSwicGF0aCI6Ii80MDMxMjUwOS8zMzc5NDUxNjYtZDFhNTM1Y2QtZGJiYy00N2RiLWFjMDItMTM5MTAwOWQxNmRiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDAyMDI1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0NzcwZjE2MzEwNjExNTQ5MTU1MDk4ZTk3MDhiMmIyMGIxYTIyM2FhMWIxMjFkMDFmNjAzNGE3MzUzODcwOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Tw3Q2gXI86rrDOLeGphxc7t8ssVKUf2bUAzBwPkebXI)
> 
> 如果你是使用termux的google play版本，请换回f-droid版本。实测google play版本在termux环境内无法识别kernelsu的su命令(failsafe环境可使用su)。

可是我得用nethunter的终端，不行，现在换回magisk了，先将就着

**Comment by 5ec1cff** [comment]
如果还想在用 ksu 的情况下正常使用 play 版 termux ，可以把你的 su 脚本 (`$PREFIX/bin/su`) 换成下面的代码

```sh
unset LD_PRELOAD LD_LIBRARY_PATH
exec /system/bin/sh -c 'exec /system/bin/su'
```

**Comment by bgaojin** [comment]
我遇到的问题是 设置shell root以后, linux下打开终端 adb shell 输入su  提示/system/bin/su: No such file or directory
用的0.9.5版本，手机内核4.4 自己编译

**Comment by bgaojin** [comment]
我遇到的问题 设置shell root以后，linux下打开终端 adb shell 输入su 提示/system/bin/su: 没有那个文件或目录
用的0.9.5版本，手机内核4.4 自己编译，其他app root正常

**Comment by aviraxp** [comment]
> 如果还想在用 ksu 的情况下正常使用 play 版 termux ，可以把你的 su 脚本 (`$PREFIX/bin/su`) 换成下面的代码
> 
> ```shell
> if [ -n "$LD_PRELOAD" ]; then
>  unset LD_PRELOAD LD_LIBRARY_PATH
>  exec /system/bin/sh $0 "$@"
> fi
> exec /system/bin/su "$@"
> ```

https://github.com/termux-play-store/termux-tools/commit/9187cfa169cc64861a0fc7e98a01b9c78eb1634d

**Comment by kongle233** [comment]
我也遇见了同样的问题，经过我的测试,内核ksu版本大于等于9.4就会出现这个问题，目前尚未解决

**Comment by shandongtlb** [comment]
你才是真大佬

**Comment by a289672082** [comment]
负更新吗,还好我翻了记录,对非gki设备影响很大,因为官方对非gki设备的指导版本是0.95

**Comment by heinhuiz** [comment]
This issue starts on 0.9.3, so 0.9.2 is the latest usable version.
