### ISSUE TITLE
Is 5.10.177 no longer supported?

### ISSUE THREAD

**Issue by Criticise** [tiann/KernelSU#1818]
### Describe your problem.

0.9.4 after cancelled serial gki patches, I didn't find the reasons why they were ditched

**Comment by dabao1955** [comment]
#1705

Besides, 5.10.177 is a GKI kernel, which is still maintained.

**Comment by dabao1955** [comment]
> > > > #1705
> > > > Besides, 5.10.177 is a GKI kernel, which is still maintained.
> > > 
> > > 
> > > It's deprecated by Google.
> > 
> > You're right. But ksu still supports the GKI kernel that has ended support, doesn't it?
> 
> No.

Well you can still compile it by yourself whether  it has dropped support.

**Comment by tiann** [comment]
https://kernelsu.org/guide/installation.html#kmi
