### ISSUE TITLE
新增多用户管理权限功能

### ISSUE THREAD

**Issue by AMWss** [tiann/KernelSU#1822]
### Is your feature request related to a problem? Please describe.

在小米等系统自带的系统分身中（多用户）KernelSU缺少权限管理的便利性，最显著且最严重的问题就是，在小米HyperOS，系统分身中，想要KernelSU授权必须得在主空间卸载KernelSU，再重启，再到分身中安装KernelSU才能正常使用KernelSU且不会加载主空间的模块，而且主空间会丢失权限哪怕重新安装KernelSU，只有在分身卸载KernelSU，并重启，在主空间再安装KernelSU才能正常使用，极大的不便利性，且在分身授予应用“爱玩机工具箱”su会显示已授权但爱玩机无法获取权限的问题，猜测这是与KernelSU并不完正的多用户空间授权问题有关系
再次感谢作者的劳动成果，希望KernelSU能更好

### Describe the solution you'd like.

新增多用户相关授权功能

### Describe alternatives you've considered.

Magisk
Kitsune Mask
Magisk Alpha

**Comment by tiann** [comment]
#1705
