### ISSUE TITLE
AirMusic root access denied

### ISSUE THREAD

**Issue by papaalfacharliealfaromeo** [tiann/KernelSU#1825]
![Screenshot_20240615-120811](https://github.com/tiann/KernelSU/assets/137070734/f871d1ec-b1fe-4fad-9792-3c8cda3a1bc0)
![Screenshot_20240615-121237](https://github.com/tiann/KernelSU/assets/137070734/be6434a4-7062-44ea-b2f5-3f1ff7998eb6)
![Screenshot_20240615-121248](https://github.com/tiann/KernelSU/assets/137070734/12014405-6539-4941-b2fb-65828a8d7b5b)

please help me, thanks.

**Comment by tiann** [comment]
Nothing to do with us.

**Comment by papaalfacharliealfaromeo** [comment]
> Nothing to do with us.

If so, what is the problem? I don't understand this problem.
