### ISSUE TITLE
Install in android11 device notify follow “Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]”

### ISSUE THREAD

**Issue by BugTan** [tiann/KernelSU#1826]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

install kernelsu in TCL TV android11 via adb shell give this error Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]
![image](https://github.com/tiann/KernelSU/assets/12221410/3f5eab12-07e5-4581-b248-874a2c714a9b)

### Device info

- Device:TCl 85Q9K 
- OS Version:Android11
- KernelSU Version:1.0.0
- Kernel Version:Linux localhost 5.4.233-g17273fc9edc3-dirty

**Comment by AMWss** [comment]
这个问题不是kernelsu的原因，是你的tcl没有匹配的原生库导致安装失败，比如v8a,v7a这些，是你的电视不支持管理器的原生库导致的

**Comment by AMWss** [comment]
建议adb shell查看CPU架构
我的意思就是你的电视处理器架构不支持KernelSU管理器
如果命令没记错应该是
adb shell getprop ro.product.cpu.abi

**Comment by tiann** [comment]
32 bit devices are not supported.

**Comment by BugTan** [comment]
> 建议adb shell查看CPU架构 我的意思就是你的电视处理器架构不支持KernelSU管理器 如果命令没记错应该是 adb shell getprop ro.product.cpu.abi

架构是armv8l

**Comment by BugTan** [comment]
> 32 bit devices are not supported.

确实是32位架构，这样就没法用了，可以增加打包为32架构么
