### ISSUE TITLE
[Feature] Import/Export Settings

### ISSUE THREAD

**Issue by BlazeFTL** [tiann/KernelSU#1827]
### Is your feature request related to a problem? Please describe.

Whenever i change custom roms i have to allow su access manually everytime

If somehow kernelSu can remember the apps i allowed su would be great(doesn't have to be through import/export) if there are other good ideas for such task

### Describe the solution you'd like.

*

### Describe alternatives you've considered.

*

### Additional context

*

**Comment by tiann** [comment]
#1705
