### ISSUE TITLE
[Feature] Add option to randomize ksu manager package name

### ISSUE THREAD

**Issue by Vantesh** [tiann/KernelSU#1828]
### Describe your problem.

Some banking apps have started flagging the ksu manager app as a root app and don't work until you delete the manager to work, adding an option to randomize it's package name would be very useful like in magisk.

**Comment by lols** [comment]
Ah yes I just experience it was about to create and saw this, my banking app detect root when I have kernelsu app installed and when I uninstall, it works fine again..... Would be great if we can have something like magisk generate random app name
