### ISSUE TITLE
EACCES

### ISSUE THREAD

**Issue by suprohub** [tiann/KernelSU#1833]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

![Screenshot_20240618-201421](https://github.com/tiann/KernelSU/assets/125716028/07256e6f-f6cb-4731-a5aa-f0659f398efe)
Why i not write?

### To Reproduce

Download apk editor
Edit data

### Expected behavior

Editet data

### Logs

No losg 

### Device info

- Device: sweet_k6a (sweet2, sweet_global2...)
- OS Version: 14
- KernelSU Version: last
- Kernel Version: 4.14.340

**Comment by tiann** [comment]
#1705
