### ISSUE TITLE
KernelSU does not ask to allow su access to certain apps with root capabilities

### ISSUE THREAD

**Issue by Dondrejohnson5** [tiann/KernelSU#1838]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

KernelSU does not automatically determine which apps have root capabilities to show a dialog box, like Magisk, that asks the user to allow or deny the root app access to root. Below, I use Greenify as an example. 

### To Reproduce

- Install a root-capable app from the Play Store, such as Greenify
- Open the app, and go through the setup
- At some point during the setup, you will see the app says it is unable to determine root

### Expected behavior

- As the app, during setup, determines whether or not the device is rooted, KernelSU asks with a dialog box to either allow the deny said app access to su.

### Screenshots

![Screenshot_20240623-154055_Greenify](https://github.com/tiann/KernelSU/assets/29732079/f87ff2b9-1c38-4a65-ae62-58f3624ae1b8)

### Logs

[KernelSU_bugreport_2024-06-23_15_41.tar.gz.zip](https://github.com/user-attachments/files/15945781/KernelSU_bugreport_2024-06-23_15_41.tar.gz.zip)

### Device info

- Device: Motorola Edge 40 Pro 
- OS Version: 14
- KernelSU Version: 1.0.0
- Kernel Version: 5.15.149

### Additional context

If there is any reason why this cannot be implemented to KernelSU (probably having something to do with KernelSU actively hiding su from all apps by default), I understand. In which case, I propose a feature request (my apologies in advance, as I have no idea how to create a proper pull request here):

In the SuperUser tab of KernelSU manager app, highlight all installed apps that are capable of utilizing root, so, while the user is determining which apps to allow su before the app asks for such, the user has a better idea or recollection of which apps have root capabilities, therefore which apps to allow and which others to leave alone.

**Comment by tiann** [comment]
KernelSU's `su` is invisible to all applications by default, so you cannot know if a certain app has called `su` unless you make it visible. 

I believe that proactive authorization is a better and safer approach than passive pop-ups, and we will not support this method.

**Comment by Dondrejohnson5** [comment]
I figured so.. Can you at least consider this function instead? 

"In the SuperUser tab of KernelSU manager app, highlight all installed apps that are capable of utilizing root"

It will be on KernelSU to determine and detect which apps can use root, so I can have a better idea of which apps I need to proactively enable su for, and know which ones I don't

**Comment by Dondrejohnson5** [comment]
> KernelSU's `su` is invisible to all applications by default, so you cannot know if a certain app has called `su` unless you make it visible.
> 
> I believe that proactive authorization is a better and safer approach than passive pop-ups, and we will not support this method.

I figured so.. Can you at least consider this function instead?

"In the SuperUser tab of KernelSU manager app, highlight all installed apps that are capable of utilizing root"

It will be on KernelSU to determine and detect which apps can use root, so I can have a better idea of which apps I need to proactively enable su for, and know which ones I don't

**Comment by tiann** [comment]
> all installed apps that are capable of utilizing root

Any app is capable of utilizing root. Which programs do you think really need to use the 'su' command, and how can you get this list? Online configuration? I don't have time to maintain this online configuration. You just need to enter its name in the search box to find it.

**Comment by Dondrejohnson5** [comment]
> Any app is capable of utilizing root. 

How so? I wouldn't think any app can if they never ask for su access

> Which programs do you think really need to use the 'su' command, and how can you get this list? Online configuration? 

I'm not sure you understood me. I meant if the KSU manager can detect on device which apps would use su somehow, through like an apk dive or something (I don't really know), not through an online configuration. I wouldn't think something like that would even require the internet 🤷

**Comment by tiann** [comment]
we can't detect that. Nobody (including ourselves) can detect su unless you authorize it.

**Comment by lvyitian** [comment]
> > Any app is capable of utilizing root.
> 
> How so? I wouldn't think any app can if they never ask for su access anywhere in the app
> 
> > Which programs do you think really need to use the 'su' command, and how can you get this list? Online configuration?
> 
> I'm not sure you understood me. I meant if the KSU manager can detect on device which apps would use su somehow, through like an apk dive or something (I don't really know, just an idea to make my point), not through an online configuration. I wouldn't think something like that would even require the internet 🤷

@Dondrejohnson5 Because applications get root shell access by using Runtime.getRuntime().exec(...).
You can't know whether it is executing su unless you run it.

**Comment by GOTBLZ** [comment]
> > > Any app is capable of utilizing root.
> > 
> > 
> > How so? I wouldn't think any app can if they never ask for su access anywhere in the app
> > > Which programs do you think really need to use the 'su' command, and how can you get this list? Online configuration?
> > 
> > 
> > I'm not sure you understood me. I meant if the KSU manager can detect on device which apps would use su somehow, through like an apk dive or something (I don't really know, just an idea to make my point), not through an online configuration. I wouldn't think something like that would even require the internet 🤷
> 
> [@Dondrejohnson5](https://github.com/Dondrejohnson5) Because applications get root shell access by using Runtime.getRuntime().exec(...). You can't know whether it is executing su unless you run it.

Sorry to bring up an old post, but I feel this feature could be handy - would it not be possible to make it so at the very least KernelSU can display at the top of the list, which apps have requested su, by logging the Runtime.getRuntime().exec(...) command? Then people could use the app and go back to KernelSU to see it at the top of the list and they could also see if an app has been spamming requests for su access
