### ISSUE TITLE
Is it possible to have KSU LKM with locked bootloader?

### ISSUE THREAD

**Issue by xpert0** [tiann/KernelSU#1839]
### Describe your problem.

I am using KSU LKM mode in a device, but I am curious if it's possible to have locked bootloader along with KSU. I found that "Android requires kernel modules to be in the partitions that have dm-verity enabled. This removes the need for signing individual modules for their authenticity."(source: https://source.android.com/docs/core/architecture/kernel/loadable-kernel-modules ).
Please help with this.
![Screenshot_2024-06-24-09-59-59-866_com android chrome](https://github.com/tiann/KernelSU/assets/131262073/4703026b-1f80-43f5-a08b-4187f25df21a)

**Comment by tiann** [comment]
In general, no. Unless you have a vulnerability that can escalate to root.
