### ISSUE TITLE
[2个小疑问]如何比较方便的从GKI模式切换到LKM？

### ISSUE THREAD

**Issue by lshilshi** [tiann/KernelSU#1840]
### Describe your problem.

@tiann 感谢大佬的付出与KSU工具！

Q1：如何简单一些从GKI模式切换到LKM？
看了readme后，说对于手机，还是推荐LKM模式
当前手机运行于GKI模式
我知道可以unroot+卸载KSU后重新安装KSU于LKM模式
但是这是个笨办法吧，我想知道有方便一些的方法吗？
已经尝试在KSU Manager中Direct Install了，但是重启还是在GKI模式

Q2:GKI 5.10.168-12.xxxx 内核的更新问题
提问前看过 #1818 
之前KSU Manager是0.9.3版本，内核与此匹配
今天刚刚将KSU Manager升级到1.0，（未更新内核，因为无了），在Manager中选择Direct Install
reboot后，在Manager中内核信息仍然是5.10.168-12.xxxx，我不知道是不是已经更新到与1.0匹配的内核了？

假如还是需要自己刷入修改后内核更新，5.10.168-12.xxxx 虽然是GKI，但是从release看自0.9.4后就失去适配了
从readme来看，5.10.xxx-12.xxx 的第一个xxx是sublevel，说这个在内核更新时候不是很重要，
那么我可以用还在适配的 5.10.198/205/209-12.xxx 的内核来进行更新吗？
如果可以忽视sublevel来更新的话，那请问提供多个sublevel的更新包有其它意义吗？

抱歉，不是很懂，已经努力看过readme、wiki和issue了
还是只能来issue发问，如果不妥，可以关闭，但请抽时间回复一下，谢谢！

**Comment by tiann** [comment]
1. 使用官方 boot/init_boot 包修补后重新刷机，没有别的更好的办法。
2. 0.9.4 以后，只是不支持 GKI 设备（内核版本 5.10 以下），内核 5.10 以上的设备，GKI 模式还是支持的；另外你需要阅读官网关于 KMI 的说明，KMI 不关心 sublevel。
