### ISSUE TITLE
Compilation error in clang-17 plz help sir

### ISSUE THREAD

**Issue by Devil15071993** [tiann/KernelSU#1845]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

../drivers/ksu/ksu.c:97:1: error: type specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
MODULE_IMPORT_NS(VFS_internal_I_am_really_a_filesystem_and_am_NOT_a_driver);

### Screenshots

![Screenshot_2024-06-29-07-56-58-366_com offsec nhterm](https://github.com/tiann/KernelSU/assets/97546639/862711bb-cae4-49c9-a611-cd665d05d9f3)

### Device info

- Device: Mi 11x (aliothin)
- OS Version: hyperos v1.0.1.0
- KernelSU Version: 11895
- Kernel Version: Realking kernel v- 4.19.314

**Comment by tiann** [comment]
https://github.com/tiann/KernelSU/issues/1705

**Comment by vanshsantoshi** [comment]
Solution here: 
https://github.com/tiann/KernelSU/issues/1972
