### ISSUE TITLE
qgki support 

### ISSUE THREAD

**Issue by mortaza01** [tiann/KernelSU#1854]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

need support for qgki kernel... please support 

### Device info

- Device: mi 11 ultra
- OS Version: Android 14
- KernelSU Version: 
- Kernel Version:5.4.233-qgki-gef02e3e868c2

**Comment by Morrigan-Ship** [comment]
same please reopen it
