### ISSUE TITLE
发送日志中的 “保存日志保存日志”

### ISSUE THREAD

**Issue by wmrasw** [tiann/KernelSU#1855]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

点击设置中的发送日志，弹出菜单中保存日志选项描述文本重复了两遍

### To Reproduce

1.点击设置
2.点击发送日志

### Expected behavior

文本应显示为：保存日志
其他语言无此问题

### Screenshots

![Screenshot_2024-07-05-02-00-47-773_me weishu kernelsu](https://github.com/tiann/KernelSU/assets/134150147/77b5bc8d-1902-493c-813a-eb4f9a26cce9)
![Screenshot_2024-07-05-02-00-17-894_me weishu kernelsu](https://github.com/tiann/KernelSU/assets/134150147/a61220fe-547e-410c-8455-2ec4ff8d54dd)

### Device info

- Device:Redmi
- OS Version:14
- KernelSU Version:1.0.0
- Kernel Version:5.10.168

**Comment by tiann** [comment]
https://github.com/tiann/KernelSU/commit/51337ee7ee73b3449f054a460fa54f4229cc5999
