### ISSUE TITLE
魅族20Pro LKM模式 无法运行在0.9.5以及1.0.0版本下，0.9.4版本正常工作

### ISSUE THREAD

**Issue by NULL204** [tiann/KernelSU#1856]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

魅族20pro解锁BL后，我下载1.0.0版本修补init_boot（来源是官方提供的卡刷包），其中未产生任何报错
在进入 Fastboot 后，执行 fastboot flash init_boot C:\Users\jiayvyv\Desktop\kernelsu_patched_20240705_055144.img
依然无报错
重启进入app，显示未安装

我从高到底测试了一些版本，0.9.4版本成功生效，显示 工作中<LKM>
0.9.4版本成功后，手动将app升级到1.0.0，并执行“直接安装”，重启后依然显示“未安装”

我搜索了一些类似的issues，但是并没有能解决我的疑惑，因为似乎症状不太一样
或许我问了蠢问题，但是我确实被这个困扰了很久，希望有热心的老哥能回答一下我的问题，非常感谢

### Expected behavior

在重启过后一个显示为“工作中”

### Logs

[KernelSU_bugreport_2024-07-05_14_14.tar.gz](https://github.com/user-attachments/files/16105636/KernelSU_bugreport_2024-07-05_14_14.tar.gz)

### Device info

- Device: MEIZU 20 Pro
- OS Version:
    Flyme 10.5.5.1A
    Android 14  安全补丁日期 2024/4/5
- KernelSU Version: 0.9.5~1.0.0
- Kernel Version: 5.15.94-android13-8-g6701334c485e-ab17001233086

**Comment by 940842546** [comment]
MeiZu21Note the same as u

**Comment by lovelyelfpop** [comment]
我红米K70 pro，和你的症状一样。

我的解决办法是：
先装magisk环境root，然后用kernel flasher刷入kernelSU修补过的init_boot，重启后kernelSU就显示工作中了。
然后卸载掉magisk。
但是这时候kernel flasher变得无法正常使用，打开会显示"invalid ramdisk in boot.img"

**Comment by lovelyelfpop** [comment]
> > 我红米K70 pro，和你的症状一样。
> > 我的解决办法是： 先装magisk环境root，然后用kernel flasher刷入kernelSU修补过的init_boot，重启后kernelSU就显示工作中了。 然后卸载掉magisk。 但是这时候kernel flasher变得无法正常使用，打开会显示"invalid ramdisk in boot.img"
> 
> 你可能没有授权kef

给过Root权限了

**Comment by helleon** [comment]
魅族 21 Pro，Flyme 10.5.5.1A，症状一样，0.9.3一切正常，1.0.0就不行
6.1.25-android14-11-maybe-dirty
刷6.1.25的gki不能启动

**Comment by NULL204** [comment]
持续跟进：更新 Flyme 10.5.5.1A  2024-07-10 版本后，更新1.0.1版本，显示工作中<LKM>
更新方法：Flyme 使用完整的卡刷包更新，kernelsu 下载1.0.1版本apk，选直接安装
目前没有发现BUG

**Comment by magojohnji** [comment]
+1 模拟器
Windows 11 Insider Preview version 24H2，WSA_2407.40000.0.0_x64，管理器版本 1.0.0，最后一个可用版本是 0.9.4，再往上就显示未安装了

**Comment by helleon** [comment]
> 魅族 21 Pro，Flyme 11.0.0.0A，症状一样，0.9.3一切正常，1.0.0就不行 6.1.25-android14-11-maybe-dirty 刷6.1.25的gki不能启动

1.0.1在上述环境一切正常

**Comment by yilishazi** [comment]
1.01已经修复这个问题了，重新修补就正常了
