### ISSUE TITLE
[Custom] 未能在官网指向页面找到ksud二进制下载链接

### ISSUE THREAD

**Issue by 13584452567** [tiann/KernelSU#1857]
### Describe your problem.

![图片](https://github.com/tiann/KernelSU/assets/25471437/d20ea440-cc9d-4384-94e4-cf3c6ab85584)
但是在最新1.0的release界面只有各种内核文件，ko模块和apk文件的下载

**Comment by NULL204** [comment]
#1538 
https://github.com/tiann/KernelSU/actions/workflows/build-manager.yml

**Comment by fsxitutu** [comment]
解压管理器apk，提取对应架构的libksud.so改名就是了😀

**Comment by 13584452567** [comment]
> 解压管理器apk，提取对应架构的libksud.so改名就是了😀

![图片](https://github.com/tiann/KernelSU/assets/25471437/b5a33b01-13f9-4867-9112-6edd3b3f59f9)
X86_64的Linux无法运行提取出来的文件

**Comment by 13584452567** [comment]
> #1538 [tiann/KernelSU/actions/workflows/build-manager.yml](https://github.com/tiann/KernelSU/actions/workflows/build-manager.yml)

CI版本可用，十分感谢

**Comment by chenzhu005774** [comment]
> 解压管理器apk，提取对应架构的libksud.so改名就是了😀
你好 请教一下。我是像编译自己的管理器apk。看样子似乎要首先编译libksud.so.请问我如何自己编译libksud.so ，然后编译对应的管理器apk。谢谢
