### ISSUE TITLE
在ROOT权限下无法直接加载kernelsu.ko

### ISSUE THREAD

**Issue by Iamxiaoq** [tiann/KernelSU#1862]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

文档里提到”适用于一些特殊场景；比如使用临时 ROOT 权限也可以加载 LKM“ ，我尝试在magisk root下直接加载kernesu.ko，未能成功。

### To Reproduce

/data/local/tmp # ls -l
-rwxrwxrwx 1 shell shell   155536 2024-07-04 21:35 ksu.ko

/data/local/tmp # insmod ksu.ko
insmod: failed to load ksu.ko: No such file or directory

/data/local/tmp # dmesg
[ 1624.977215] kernelsu: Unknown symbol kallsyms_lookup_name (err -2)
[ 1624.977369] kernelsu: Unknown symbol dentry_path_raw (err -2)
[ 1624.977459] kernelsu: Unknown symbol security_add_hooks (err -2)
[ 1624.977498] kernelsu: Unknown symbol groups_free (err -2)
[ 1624.977530] kernelsu: Unknown symbol groups_alloc (err -2)
[ 1624.977561] kernelsu: Unknown symbol groups_sort (err -2)
[ 1624.977596] kernelsu: Unknown symbol set_groups (err -2)
[ 1624.977634] kernelsu: Unknown symbol path_umount (err -2)
[ 1624.977670] kernelsu: Unknown symbol security_hook_heads (err -2)
[ 1624.977707] kernelsu: Unknown symbol init_nsproxy (err -2)
[ 1624.977750] kernelsu: Unknown symbol kernel_read (err -2)
[ 1624.977782] kernelsu: Unknown symbol kernel_write (err -2)
[ 1624.977817] kernelsu: Unknown symbol strncpy_from_user_nofault (err -2)
[ 1624.977852] kernelsu: Unknown symbol security_secid_to_secctx (err -2)
[ 1624.977881] kernelsu: Unknown symbol security_release_secctx (err -2)
[ 1624.977912] kernelsu: Unknown symbol security_secctx_to_secid (err -2)
[ 1624.977942] kernelsu: Unknown symbol selinux_state (err -2)
[ 1624.977969] kernelsu: Unknown symbol selinux_blob_sizes (err -2)
[ 1624.977999] kernelsu: Unknown symbol symtab_search (err -2)
[ 1624.978029] kernelsu: Unknown symbol symtab_insert (err -2)
[ 1624.978069] kernelsu: Unknown symbol ebitmap_set_bit (err -2)
[ 1624.978098] kernelsu: Unknown symbol ebitmap_get_bit (err -2)
[ 1624.978144] kernelsu: Unknown symbol avtab_search_node (err -2)
[ 1624.978175] kernelsu: Unknown symbol avtab_search_node_next (err -2)
[ 1624.978204] kernelsu: Unknown symbol avtab_insert_nonunique (err -2)
[ 1624.978238] kernelsu: Unknown symbol policydb_filenametr_search (err -2)
[ 1624.978345] kernelsu: Unknown symbol __hashtab_insert (err -2)
[ 1624.978392] kernelsu: Unknown symbol avc_ss_reset (err -2)
[ 1624.978429] kernelsu: Unknown symbol selnl_notify_policyload (err -2)
[ 1624.978458] kernelsu: Unknown symbol selinux_status_update_policyload (err -2)

### Device info

- Device: note11tpro
- OS Version: miui13
- KernelSU Version: 1.0
- Kernel Version:Linux localhost 5.10.66-android12-9-00001-g41ff3fa8fff9-ab8171928 #1 SMP PREEMPT Mon Feb 7 06:19:48 UTC 2022 aarch64

### Additional context

内核报`Unknown symbol kallsyms_lookup_name`看起来是没有找到这个符号，但是相同情况下使用patch boot.img的方式，是可以的激活LKM模式的。由于看不到`ksuinit`的源码没办法仿照着加载，也不知道这insmod是不是需要做什么额外处理。

**Comment by tiann** [comment]
预期行为，KernelSU 现在本来就不支持你这种方式。
