### ISSUE TITLE
请教一下编译出来的内核刷入后正常运行但是不支持kernelsu会是什么原因呢？

### ISSUE THREAD

**Issue by xyychenchen** [tiann/KernelSU#1871]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

先描述一下我的编译过程：
1 拉去设备源码（我用的都是lineageos或者crdroid官方仓库的源码）
2 源码文件夹里拉取kernelsu源码（0.9.5版本）
3 在脚本文件里修改对应的defconfig文件
4 在defconfig文件里添加kprobe的三行代码，或者手动修改那四个地方的源码（按照kernelsu官网操作） 

现在描述一下我遇见的2个问题：
1 第一次编译成功是小米8（dipper）内核4.9 ROM是lineageos-18.1，编译出来的内核打开kernelsu是显示运行中，但是在依次安装zygisk-next，lsp，shamiko的时候，开关按钮不是蓝色的，是浅色的，而且无法点击开启或关闭，可卸载，然后lsp也没有在通知栏弹出，我手动安装了lsp的管理apk也显示lsp并未安装，很自然lsp模块也就都用不了了
2 后续的编译是针对一加5T、6、6T这三个设备（内核4.4），并且ROM是lineageos-18.1和crdroid-8,（android-12.1）的编译，内核源码都是拉官方的仓库，还有小米8 的crdroid-8（android-12.1）的内核编译，无论是kprobe（用make menuconfig检查过kprobe依赖项是开启的）或者手动修改内核源码2种方式，编译出来的内核正常开机，但是kernelsu显示不支持

所以就是把能排查的都排查了一遍，但是不知道为什么编译出来的内核是不支持kernelsu的，作者能否给点提示或者思路呢，谢谢

### Device info

- Device: 小米8
- OS Version: lineageos-18.1
- KernelSU Version: 0.9.5
- Kernel Version: .4.9

**Comment by tiann** [comment]
#1705

**Comment by Coconutat** [comment]
> ### Please check before submitting an issue
> * [x]  I have searched the issues and haven't found anything relevant
> * [x]  I will upload bugreport file in KernelSU Manager - Settings - Report log
> * [ ]  I know how to reproduce the issue which may not be specific to my device
> 
> ### Describe the bug
> 先描述一下我的编译过程： 1 拉去设备源码（我用的都是lineageos或者crdroid官方仓库的源码） 2 源码文件夹里拉取kernelsu源码（0.9.5版本） 3 在脚本文件里修改对应的defconfig文件 4 在defconfig文件里添加kprobe的三行代码，或者手动修改那四个地方的源码（按照kernelsu官网操作）
> 
> 现在描述一下我遇见的2个问题： 1 第一次编译成功是小米8（dipper）内核4.9 ROM是lineageos-18.1，编译出来的内核打开kernelsu是显示运行中，但是在依次安装zygisk-next，lsp，shamiko的时候，开关按钮不是蓝色的，是浅色的，而且无法点击开启或关闭，可卸载，然后lsp也没有在通知栏弹出，我手动安装了lsp的管理apk也显示lsp并未安装，很自然lsp模块也就都用不了了 2 后续的编译是针对一加5T、6、6T这三个设备（内核4.4），并且ROM是lineageos-18.1和crdroid-8,（android-12.1）的编译，内核源码都是拉官方的仓库，还有小米8 的crdroid-8（android-12.1）的内核编译，无论是kprobe（用make menuconfig检查过kprobe依赖项是开启的）或者手动修改内核源码2种方式，编译出来的内核正常开机，但是kernelsu显示不支持
> 
> 所以就是把能排查的都排查了一遍，但是不知道为什么编译出来的内核是不支持kernelsu的，作者能否给点提示或者思路呢，谢谢
> 
> ### To Reproduce
> _No response_
> 
> ### Expected behavior
> _No response_
> 
> ### Screenshots
> _No response_
> 
> ### Logs
> _No response_
> 
> ### Device info
> * Device: 小米8
> * OS Version: lineageos-18.1
> * KernelSU Version: 0.9.5
> * Kernel Version: .4.9
> 
> ### Additional context
> _No response_

模块修复：参考这个[commit](https://github.com/Coconutat/android_kernel_xiaomi_sdm845_lineageos_Exp/commit/aafa042aad0aeb6d02297e891b57f56c3242b8ad)  
  
如果还有问题，降级到v0.9.2的KSU源码，管理器也要降级到v0.9.2。而且不要再更新管理器了。
