### ISSUE TITLE
Manager app not working after kernel flash

### ISSUE THREAD

**Issue by Bartek0x00** [tiann/KernelSU#1874]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

After patching my non-GKI 4.14.113 kernel manually as stated here: https://kernelsu.org/guide/how-to-integrate-for-non-gki.html (CONFIG_KSU enabled, KPROBES disabled, v0.9.5) and flashing successfully, i cannot install the KernelSU manager app (tried multiple versions) as the device reboots while installing (true for packet manager install, adb streamed install and twrp install). My kernel contains kernelsu symbols and was compiled without an error, so i wouldn't expect the fault to be in the build itself. KernelSU manager worked normally on stock kernel, but showed unsupported as my kernel is old and non-GKI.

### To Reproduce

1.Flash custom, manually patched non-GKI kernel for android12 N975F d2s
2.Try to install KernelSU manager

### Expected behavior

Normal installation and access to su binaries

### Logs

While installing the app:

74101 07-12 14:27:23.777 10356 10425 W fb4a.AppInitScheduler|Run:   Finished PreloadFreshFeedRanker in 289ms
74102 07-12 14:27:23.789 10621 10621 I FMain|21706|RootUtil: isDeviceRooted(): false true true
74103 07-12 14:27:23.794  7664  8546 I Icing   : Internal init done: storage state 0
74104 07-12 14:27:23.794 10528 10528 I FSvc|21706|LegalManager: init()
74105 07-12 14:27:23.800 10528 10615 I FSvc|21706|FotaUtil: PDA Version: N975FXXS9HWG9
74106 07-12 14:27:23.800 10528 10615 I FSvc|21706|FotaUtil: CSC Version: N975FOXM9HWG9

then reboot occurs

### Device info

- Device: N975F d2s SM Note 10+
- OS Version: 12
- KernelSU Version: v0.9.5
- Kernel Version: 4.14.113

**Comment by tiann** [comment]
#1705

**Comment by rsuntk** [comment]
Try disable `CONFIG_UH`, `CONFIG_KDP` and `CONFIG_RKP`
