### ISSUE TITLE
umount debug ramdisk failed

### ISSUE THREAD

**Issue by jututt** [tiann/KernelSU#1876]
### Describe your problem.

KSU 11872, Manager 11874
crDroid 10.6 A14 QPR3
Xiaomi Mi9

Got these recurring dmesg errors

```
[   34.951895] KernelSU: umount /data/adb/modules failed: -38
[   34.951904] KernelSU: umount /debug_ramdisk failed: -38
```
No modules installed, tried to disable / enable ZRAM, no luck

Also have a lot of handle ignore non zygote child

**Comment by tiann** [comment]
#1705
