### ISSUE TITLE
非GKI设备在kernelsu管理面板中无法安装模块

### ISSUE THREAD

**Issue by xyychenchen** [tiann/KernelSU#1877]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

![image](https://github.com/user-attachments/assets/0f200f02-a348-4c55-b899-36218f944afa)
![image](https://github.com/user-attachments/assets/9b547cb7-6f05-42e5-a5a0-c0662179820a)

我的两部设备
1 小米8 内核4.9 ROM是lineageos-18.1 kernelsu使用的是0.9.4 面板是1.0.0 源码来自lineageos官方仓库
2 一加5T 内核4.4 ROM是lineageos-18.1 kernelsu使用的是0.9.3 面板是1.0.0 源码来自lineageos官方仓库
两部设备都是在安装模块的时候，模块的开关按钮无法点击，只有卸载是可以点击的，我曾经安装了zygisk next和lsp，然后手动下载了lsp的管理器，显示未安装。这就是我遇见的问题，应该如何解决呢？大佬

### Device info

- Device: dipper
- OS Version: lineageos-18.1
- KernelSU Version: 0.9.4
- Kernel Version: 4.9

**Comment by xyychenchen** [comment]
说的不够准确，是正常安装，安装的流程没报错，但是重启之后，模块的开关是灰色的，无法点击，然后之前安装过lsp，我手动打开lsp管理器显示是未安装的，我曾经按照一个大佬的思路去到data/adb里去找模块的文件，发现里面没有任何可执行文件，空空如也

**Comment by xyychenchen** [comment]
已解决

**Comment by BirdView321** [comment]
请教下 怎么解决的呀。我是lineageos20  xiaomi8 pro  问题跟你一样

**Comment by xyychenchen** [comment]
> 请教下 怎么解决的呀。我是lineageos20 xiaomi8 pro 问题跟你一样

看一下这个 commit [https://github.com/sticpaper/android_kernel_xiaomi_msm8998-ksu/commit/646d0c8](url)
