### ISSUE TITLE
redefinition of static inline u32 current_sid(void)

### ISSUE THREAD

**Issue by TheDeathDragon** [tiann/KernelSU#1917]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Kernel version is 4.19.191

```shell
/alps/kernel-4.19/drivers/kernelsu/selinux/selinux.c:79:19: error: redefinition of 'current_sid'
static inline u32 current_sid(void)
                  ^
/alps/kernel-4.19/security/selinux/include/objsec.h:44:19: note: previous definition is here
static inline u32 current_sid(void)
                  ^
1 error generated.
```

### Device info

- Device: MT6765
- OS Version: Vendor is A12
- KernelSU Version: latest 1.01
- Kernel Version: latest 1.01

**Comment by tiann** [comment]
#1705

**Comment by rifsxd** [comment]
Same issue with realme_C35 5.4.x kernel
