### ISSUE TITLE
Unable to perform OTA updates after restoring the image

### ISSUE THREAD

**Issue by King-Maple** [tiann/KernelSU#1932]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

After restoring the original factory image, the image OTA still cannot update the image. After comparing the restored ramdisk.cpio with the original ramdisk.cpio, it was found that some bytes were missing

### To Reproduce

1. Restore the image
2. OTA update
3. Upon checking the update_degine log, it was found that the boot verification failed

### Expected behavior

The boot after restoring the image should be consistent with the original boot in order to perform OTA updates

### Screenshots

![8F3F7C9B7D52A48BE0AC6C17929D28C6](https://github.com/user-attachments/assets/6663283d-29f6-4fbb-939e-f54ca3bdbe4c)
![E8BB5E5D6098B0B8A6E8E81A9C770ED1](https://github.com/user-attachments/assets/b167d748-952b-40ac-b669-172502d79903)
![8B26D828E1E0DD173900A3A30C0339AF](https://github.com/user-attachments/assets/83a0a1c7-ea4f-409a-99df-45f26fd16b0d)

### Logs

[KernelSU_bugreport_2024-08-01_22_05.tar.gz.zip](https://github.com/user-attachments/files/16457765/KernelSU_bugreport_2024-08-01_22_05.tar.gz.zip)

### Device info

- Device:MI 12
- OS Version:OS 1.0.5.0
- KernelSU Version:0.9.5
- Kernel Version:5.10.177

**Comment by rsp4jack** [comment]
Hi,
How do you solve this problem? I am experiencing the same.
