### ISSUE TITLE
刷入后存储显示异常

### ISSUE THREAD

**Issue by Kalansas** [tiann/KernelSU#1952]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

刷入官方android13-5.15.137_2024-01版本的内核后系统存储显示异常。我的手机是512G存储的，但刷完后显示2T。请问如何解决？
![Screenshot_2024-08-06-23-26-43-671_me weishu kernelsu](https://github.com/user-attachments/assets/8ae3e85b-f26b-4f76-8c95-8894f0b44712)
![Screenshot_2024-08-06-23-26-56-812_com android settings-edit](https://github.com/user-attachments/assets/a1d15383-df92-4807-b1b8-24c01e9cd98f)

### Device info

- Device: 小米13 Ultra
- OS Version: MIUI 14.0.20
- KernelSU Version: v1.0.1 (11928)
- Kernel Version: 5.15.137-android13-8-gf5468ec7ad99

**Comment by Seele-Vollerei32** [comment]
已知问题,不会修复,是稀疏文件系统导致的,真看不惯可以点设置里的最小化稀疏文件,会导致模块失效,自行斟酌使用
