### ISSUE TITLE
5.10-android12 cannot use the keyboard sprite app root permission

### ISSUE THREAD

**Issue by androiddisk** [tiann/KernelSU#1967]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug
The button sprite prompts no root permission when selecting root mode
按键精灵选择root模式 提示无root权限

### To Reproduce
使用联想L71091和摩托G54存在问题   内核版本是5.10-android12 kernelsu app 里面勾选按键精灵app 打开按键精灵选择root模式 提示无root权限
﻿
﻿There is an issue with using Lenovo L71091 and moto g54. The kernel version is 5.10-android 12. In the kernelsu app, check the button sprite app and open it. When selecting root mode, it prompts that there is no root permission

测试小米civi4 pro  内核版本6.1-android14 无此bug
Tested Xiaomi Civi4 Pro kernel version 6.1-android14 without this bug

### Expected behavior

正常使用root权限
Normal use of root privileges
### Screenshots

![image](https://github.com/user-attachments/assets/41969021-e540-4a76-aa32-bdb36a0b8b55)

### Logs
日志是联想L71091的，同样有此问题的G54如果有需要我也可以上传
The log is from Lenovo L71091, and I can also upload G54 with the same issue if needed
[KernelSU_bugreport_2024-08-09_22_54.tar.gz](https://github.com/user-attachments/files/16563461/KernelSU_bugreport_2024-08-09_22_54.tar.gz)
文件过大，无法上传请这里下载按键精灵app  The file is too large to upload. Please download it here Button Elf app
http://download.myanjian.com/
![image](https://github.com/user-attachments/assets/156dd845-4742-428e-a97f-6c6749406319)

### Device info

- Device:Lenovo L71091
- OS Version:12
- KernelSU Version:1.0.1
- Kernel Version:11928
- 
- Device:XT2343-3
- OS Version:14
- KernelSU Version:1.0.1
- Kernel Version:11928

### Additional context

测试小米civi4 pro  内核版本6.1-android14 无此bug
Tested Xiaomi Civi4 Pro kernel version 6.1-android14 without this bug

**Comment by androiddisk** [comment]
不知道是否是联想的问题还是 内核版本5.10-android12 导致的按键精灵root问题   应该不是按键精灵的问题 测试小米civi4 pro内核版本6.1-android14 无此bug

**Comment by tiann** [comment]
We don't support 32bit apps.
