### ISSUE TITLE
Should we cover how to utilize dynamic systems (DSU) to extract boot image as an alternative method for LKM installation?

### ISSUE THREAD

**Issue by roowheel** [tiann/KernelSU#1970]
### Describe your problem.

There are devices that are GKI-compatible but the OEM doesn't officially provide stock ROMs anymore (i.e. 2024 OnePlus).

To use KernelSU on those devices, the user would have to grab stock ROMs from 3rd-party websites.  However, it's not a long-term solution to rely on 3rd-party services to provide stock ROMs.

There's another option that doesn't rely on such websites.  Namely, after unlocking the BL, sideload a userdebug GSI image to DSU and reboot the device to DSU.  There, `adb shell` would be running as root, and it'd be greenlight to dump any partition out to the PC.

Should we cover how to utilize dynamic systems (DSU) to extract boot image as an alternative method for LKM installation?

**Comment by tiann** [comment]
You can use `fastboot boot kernelsu-xxx.img` to boot and install directly: https://kernelsu.org/guide/installation.html#get-the-official-firmware

**Comment by roowheel** [comment]
> You can use `fastboot boot kernelsu-xxx.img` to boot and install directly: https://kernelsu.org/guide/installation.html#get-the-official-firmware

The official KernelSU boot image is great, but the patchset level may not be up-to-date, and if the stock ROM patchset level is newer than KernelSU's (which is just the case for OnePlus after OTA), booting KernelSU image will fail.

Have tested that on my own device.

That's why I believe we might need to cover the usage of DSU as an alternative method.

**Comment by tiann** [comment]
Use `fastboot boot` (not `fastboot flash boot`) to temporarily boot your device, and then use the temporary root to install LKM mode.

**Comment by roowheel** [comment]
> Use `fastboot boot` (not `fastboot flash boot`) to temporarily boot your device, and then use the temporary root to install LKM mode.
> 
> If you need the stock boot image, you can use temporary root to directly `dd` extract, without the need for DSU."

You mentioned the need to `fastboot boot`, but that's not going to happen if the KernelSU boot image has got older patchset level than stock boot (after OTA).

You might want to experiment that on your own device.

Just for your heads up:

As of Aug. 13, the lastest ColorOS 14 release has got their patchset level bumped to Jun. 5, whereas

**Comment by roowheel** [comment]
> I use a Xiaomi device, and it works well. I'm not sure what happened with OnePlus.

Anti-rollback mechanism. Followed the same protocol Google Pixel started.

(So you finally passed the Xiaomi Entrance Exam? Congratulations.)
