### ISSUE TITLE
[Custom]Kernel fails to build on custom build

### ISSUE THREAD

**Issue by Lumince** [tiann/KernelSU#1996]
### Describe your problem.

So I have an interesting issue. I am trying to build a custom kernel with KernelSU for the nintendo switch (via [switchroot)](https://wiki.lineageos.org/devices/nx_tab/build/variant4/) and for some reason, the changes made from the guide on the site result in it failing. I have the kernel building without KernelSU. If anyone could take a look at this and see if I am missing anything? I see a few errors revolving kernelsu, but I have no idea how to go about fixing them. (I am sorry if this is not the right place for posting this)
[output.txt](https://github.com/user-attachments/files/16703732/output.txt)

**Comment by tiann** [comment]
https://kernelsu.org/guide/how-to-integrate-for-non-gki.html#integrate-with-kprobe

> [KernelSU 1.0 and later versions no longer support non-GKI kernels](https://github.com/tiann/KernelSU/issues/1705). The last supported version is v0.9.5, please make sure to use the correct version.

**Comment by vanshsantoshi** [comment]
Solution here:
https://github.com/tiann/KernelSU/issues/1972
