### ISSUE TITLE
LKM 模式下 kernelsu.ko 如何检测内核内的ramdisk 文件 以及提取 。这样才能开发类似面具的overlay.d 功能

### ISSUE THREAD

**Issue by androiddisk** [tiann/KernelSU#2004]
### Describe your problem.

如题，不知道kernelsu.ko如何检测并提取打包进ramdisk的文件。 实在没方向 ，所以发帖请教下

**Comment by tiann** [comment]
https://github.com/tiann/KernelSU/blob/main/userspace/ksud/src/boot_patch.rs

**Comment by androiddisk** [comment]
> https://github.com/tiann/KernelSU/blob/main/userspace/ksud/src/boot_patch.rs

感谢大佬回复 我可能没表达清楚疑问， 我是想说 kernelsu.ko 内核模块代码里面如何去检测释放 ramdisk 的文件 而不是如何将文件封装进init_boot
