### ISSUE TITLE
请教一下大佬为何不将KernelSU设计为一个GKI的独立驱动模块呢

### ISSUE THREAD

**Issue by tuancc-repo** [tiann/KernelSU#202]
请教一下大佬为何不将KernelSU设计为一个GKI的独立驱动模块呢，而是将KernelSU编译进为不同的GKI版本内核呢, 个人感觉编译为不同的GKI内核版本去单独编译一个是工作量会更大吧

**Comment by tiann** [comment]
编译进内核会更简单。

**Comment by tuancc-repo** [comment]
会不会存在有厂商改动GKI内核呢,  哪怕是很细微的一个改动,  如果没有改动后源码的话, 到时候就很难去重新编译适配吧

**Comment by tiann** [comment]
那还是 GKI 吗？

**Comment by tuancc-repo** [comment]
好像也是啊,  估计是我太笨了

**Comment by tuancc-repo** [comment]
想问一下大佬预计目前大概要编译多少个版本的GKI内核文件啊
