### ISSUE TITLE
[Custom] Magisk Modules Converter?

### ISSUE THREAD

**Issue by topaloglu321** [tiann/KernelSU#2037]
All we know some of the modules for Magisk are not working on KernelSU. 
Is it possible to create a converter to adapt modules on KernelSU. 

For example I couldn't manage to make it work this module on my device. 
Any tips to convert it? or Any tools? 

https://www.magiskmodule.com/ios-16-5-system-sounds-magisk-module/

**Comment by jeffpeng3** [comment]
I think what you need is to read the official documents.

https://kernelsu.org/guide/difference-with-magisk.html

**Comment by topaloglu321** [comment]
I read the documents many  times but this is not what I'm asking for? 
I'm not sure about the possibility of creating a "Converter" and trying to learn about that? 

If you can tell what it needs to use the module I sent,  on KernelSU, that would be really helpful?

**Comment by tiann** [comment]
KernelSU has tried its best to be compatible with Magisk modules, but if the module uses Magisk's internal features, there's nothing that can be done. Additionally, as mentioned above, KernelSU will by default unmount modules; you can check this switch.
