### ISSUE TITLE
[Custom]kernel flasher应用无法使用

### ISSUE THREAD

**Issue by dared2007** [tiann/KernelSU#2042]
### Describe your problem.

使用kernelsu后kernel flasher应用无法使用，导致无法更新系统
![Screenshot_2024-09-08-10-37-02-796_com github capntrips kernelflasher](https://github.com/user-attachments/assets/d3cd6175-f8fe-4c29-b2cc-f4d3272c0995)

**Comment by tiann** [comment]
kernel flasher 的 bug。
