### ISSUE TITLE
KernelSU running in LXC environment cannot install module

### ISSUE THREAD

**Issue by eminarcissus** [tiann/KernelSU#2044]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Hi,

Working environment: 

Using KernelSU in together with Snapdragon 865 phone, with Waydroid(a LXC container running inside of linux host, which the path on android system is very different with kernel space file system I believe, likely /data/adb/modules is being mounted from host system on /$HOME/.local/share/waydroid/data/data/adb/modules etc) installed on Sailfish OS. 

Current kernel version is v4.19, i did compiled it without patch fs/namespace.c because it always crash the kernel, which didn't have time to dig out the reason yet,also that's not the topic of this issue.

I've patched the kernel both with v0.9.5 and 0.9.0 (1.0 above have problem compiling so i didn't tried out to fix yet). SU permission works great, but module system is not working.

The module system looks like does have some compatibility problems with LXC container running environment, I don't have a log of KernelSU right now because I'm trying with other solution(APatch) right now, but looks like they both sharing the same module system and reports the same error

09-08 23:16:49.337  9234  9277 I APatchCli: module disable admirepowered result: false
09-08 23:17:01.817  9234  9234 I APatchCli: is global namespace enabled:
09-08 23:17:14.819  9234  9234 I APatchCli: has magisk: false
09-08 23:17:18.232  9234  9234 I APatchCli: is global namespace enabled:
09-08 23:17:26.270  9234  9234 I APatchCli: has magisk: false
09-08 23:18:01.993 12565 12565 I APatchD : apd::cli: command: Module { command: Install { zip: "/data/user/0/me.bmax.apatch/cache/module.zip" } }
09-08 23:18:01.995 12565 12565 I APatchD : apd::module: module prop: {"updateJson": "https://api.nullptr.icu/android/zygisk-next/static/update.json", "id": "zygisksu", "version": "1.1.0 (330-a1b0e69-release)", "versionCode": "330", "description": "Standalone implementation of Zygisk.", "name": "Zygisk Next", "author": "Nullptr, 5ec1cff"}
09-08 23:18:01.996 12565 12565 I APatchD : apd::module: zip uncompressed size: 3.43 MB
09-08 23:18:01.996 12565 12565 I APatchD : apd::module: grow size: 271.87 MB
09-08 23:18:01.996 12565 12565 I APatchD : apd::module: Creating brand new module image
09-08 23:18:02.086 12565 12565 I APatchD : apd::module: e2fsck exit code: 0
09-08 23:18:02.087 12565 12565 E APatchD : apd::cli: Error: No such file or directory (os error 2)

the error is pretty straight forward, preparing image without error, e2fsck exit with 0,  mouting image, cannot find file, os error 2 and nothing more. 

Here are some debug log I did when I was testing kernelsu: 

i checked on /data/adb/ksu folder when I see trying mouting image, there aren't any img file being created after preparing the module in /data/adb/ksu/, if I do create those three images files(modules.img/modules_update.img and tmp one I can't recall the name) manually, it still failed to mount in the following step, which I do believe is Rust's mount loop part. I suspect the userspace code(rust part) are trying to route the file tasks on the host environment(kernel spcae?) without respect the lxc container environment setting in kernel space, but since my host is a linux system, all of those paths doesn't exists at all, so e2fsck exit with 0 is also a weird thing right here). 

Is there any ways I can directly using all of mounts,mkfs etc commands in busybox? I believe those were just normal actions happens in container environment with proper root access, but I'm still not convinced why e2fsck exit with 0 if the img doesn't even exists at all.

Any hints or suggestions will be really appreciated.

### Device info

- Device:
- OS Version:
- KernelSU Version:
- Kernel Version:

**Comment by eminarcissus** [comment]
I just recompiled the userspace part, seems like this is not the case, will close the issue for now. Will investigate more.

**Comment by fabio-87** [comment]
> I just recompiled the userspace part, seems like this is not the case, will close the issue for now. Will investigate more.

Hi eminarcissus, I've a Sony Xperia 10 III with SailfishOS installed and I searched a lot for a root solution for the LXC container. Is your device the same?
If yes, can you share the kernel, so I can flash it?
Thanks a lot!!

**Comment by eminarcissus** [comment]
> > I just recompiled the userspace part, seems like this is not the case, will close the issue for now. Will investigate more.
> 
> Hi eminarcissus, I've a Sony Xperia 10 III with SailfishOS installed and I searched a lot for a root solution for the LXC container. Is your device the same? If yes, can you share the kernel, so I can flash it? Thanks a lot!!

I'm using Xperia 1ii, they share a similar kernel but not exactly the same, probably will brick the boot process if directly used. Compile the kernel just following the sailfish hadk compile instruction is enough, only catcha is to pack the kernel with intramfs, which needs some unpack of the old and replace the kernel file.
Also KernelSU will not work for aliendalvik(i didn't tested very extendly yet, since I run both waydroid and aliendalvik on device, only one rooted is enough for me), but waydroid needs some init.rc modifications, will need some time to get hands dirty to get everything on trail.
