### ISSUE TITLE
[Help] Use KSU without manager app

### ISSUE THREAD

**Issue by alfaonyt** [tiann/KernelSU#2077]
### Describe your problem.

Hey,
I'm using KSU to then install Magisk on a device because I don't have access to the firmware files but there is one issue.
Kernel boots fine but Android is in Armv7 mode which isn't supported by the app.
I am not asking to add 32 bits support because I know there are no plans to do so.
Is there a way to temporarily use KSU without the app to dump init_boot to then patch it with Magisk?
Thanks

PS: The device is a Ticwatch Pro 5 running kernel 5.15.144

**Comment by alfaonyt** [comment]
I found an arm32 app but it's not working and after searching a bit more, it seems like the kernel module has not been loaded.
Is there any solution?

**Comment by tiann** [comment]
Enable `CONFIG_KSU_DEBUG` and compile the kernel. By default, `adb shell` will be granted root access.
We won't add it in non-debug mode because it is dangerous.

**Comment by alfaonyt** [comment]
@tiann I figured it out but it still does not work unfortunately. I think the KSU module might not be loading for some reason (kernel is 64 bits, android is 32 bits).
I have seen that on another device that uses kernel 5.10 once but I wasn't able to fix it.
