### ISSUE TITLE
😱免费开盒查人头😆

### ISSUE THREAD

**Issue by Zaq14rfv** [tiann/KernelSU#2083]
### Describe your problem.

👉 强烈推荐免费人肉社工搜索机器人: 
这个很好用 据说可以免费查大头🌝

😱 精准盒打击, 快来免费体验吧! 点击下方链接跳转使用

https://t.me/TapSGKbot?start=6868087938

**Comment by tiann** [comment]
麻烦你不要到处拉屎。
