### ISSUE TITLE
edited build.prop

### ISSUE THREAD

**Issue by itachiccc** [tiann/KernelSU#2090]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Can edited build.prop,but it doesn't save any change.
eg.i want modify ro.build.display.id, After reboot and nothing has changed.

### Device info

- Device:S23u
- OS Version:Android 14
- KernelSU Version:v1.0.1
- Kernel Version:5.15.148

**Comment by tiann** [comment]
https://kernelsu.org/guide/module.html#system-prop
