### ISSUE TITLE
Hello sir, Version 0.9.5 does not support the 4.4 Android kernel

### ISSUE THREAD

**Issue by mzb98** [tiann/KernelSU#2101]
### Describe your problem.

I tried compiling 0.9.5 kernelsu for the 4.4 version of the kernel. However, I found that when booting, it will show that it is not supported and it only supports GKI. May I ask which version of kernelsu can only be used for the 4.4 kernel?

**Comment by ravindu644** [comment]
> ### Describe your problem.
> I tried compiling 0.9.5 kernelsu for the 4.4 version of the kernel. However, I found that when booting, it will show that it is not supported and it only supports GKI. May I ask which version of kernelsu can only be used for the 4.4 kernel?

Does the compiled Kernel booted ?

Can you see "ksud.o" in build logs ?

Is OverlayFS is enabled in Defconfig ?

Where's the source ?

Did you manually integrated KSU or used KProbe method?

**Comment by ravindu644** [comment]
> ### Describe your problem.
> I tried compiling 0.9.5 kernelsu for the 4.4 version of the kernel. However, I found that when booting, it will show that it is not supported and it only supports GKI. May I ask which version of kernelsu can only be used for the 4.4 kernel?

Did the compiled kernel boot?

Can you see "ksud.o" in the build logs?

Is OverlayFS enabled in the Defconfig?

Where is the source?

Did you manually integrate KSU, or did you use the KProbe method?

**Comment by mzb98** [comment]
> > ### Describe your problem.
> > I tried compiling 0.9.5 kernelsu for the 4.4 version of the kernel. However, I found that when booting, it will show that it is not supported and it only supports GKI. May I ask which version of kernelsu can only be used for the 4.4 kernel?
> 
> Did the compiled kernel boot?
> 
> Can you see "ksud.o" in the build logs?
> 
> Is OverlayFS enabled in the Defconfig?
> 
> Where is the source?
> 
> Did you manually integrate KSU, or did you use the KProbe method?

Yes, Sir. I manually modified kprobe and ksu. In my tests, version 0.6 kernelsu passed the test, but 0.9.5 did not work. this is the kernel source . I did not find ksud.o in the 0.9.5 build file. this is the kernel source: :https://github.com/jagogardiner/kernel_xiaomi_acrux/tree/staging     , i used  acrux_defconfig to build.

**Comment by ravindu644** [comment]
> > > ### Describe your problem.
> > > I tried compiling 0.9.5 kernelsu for the 4.4 version of the kernel. However, I found that when booting, it will show that it is not supported and it only supports GKI. May I ask which version of kernelsu can only be used for the 4.4 kernel?
> > 
> > 
> > Did the compiled kernel boot?
> > Can you see "ksud.o" in the build logs?
> > Is OverlayFS enabled in the Defconfig?
> > Where is the source?
> > Did you manually integrate KSU, or did you use the KProbe method?
> 
> Yes, Sir. I manually modified kprobe and ksu. In my tests, version 0.6 kernelsu passed the test, but 0.9.5 did not work. this is the kernel source . I did not find ksud.o in the 0.9.5 build file. this is the kernel source: :https://github.com/jagogardiner/kernel_xiaomi_acrux/tree/staging , i used acrux_defconfig to build.

if you didn't see "ksud.o" in build logs, that means KernelSU is not even enabled when you compile your kernel.

if you can fork that source, then modify it and commit your changes and upload it to github, I can review what's wrong with your source.

**Comment by mzb98** [comment]
> > > > ### Describe your problem.
> > > > I tried compiling 0.9.5 kernelsu for the 4.4 version of the kernel. However, I found that when booting, it will show that it is not supported and it only supports GKI. May I ask which version of kernelsu can only be used for the 4.4 kernel?
> > > 
> > > 
> > > Did the compiled kernel boot?
> > > Can you see "ksud.o" in the build logs?
> > > Is OverlayFS enabled in the Defconfig?
> > > Where is the source?
> > > Did you manually integrate KSU, or did you use the KProbe method?
> > 
> > 
> > Yes, Sir. I manually modified kprobe and ksu. In my tests, version 0.6 kernelsu passed the test, but 0.9.5 did not work. this is the kernel source . I did not find ksud.o in the 0.9.5 build file. this is the kernel source: :https://github.com/jagogardiner/kernel_xiaomi_acrux/tree/staging , i used acrux_defconfig to build.
> 
> if you didn't see "ksud.o" in build logs, that means KernelSU is not even enabled when you compile your kernel.
> 
> if you can fork that source, then modify it and commit your changes and upload it to github, I can review what's wrong with your source.

Ok,sir. The build project has been post ,the website is  https://github.com/mzb98/acrux2

**Comment by mzb98** [comment]
Strangely, the same changes won't work in version 0.9, but will work in versions 0.6 and 0.5

**Comment by jeffpeng3** [comment]
Do you have any build logs?

**Comment by ravindu644** [comment]
> > > > > ### Describe your problem.
> > > > > I tried compiling 0.9.5 kernelsu for the 4.4 version of the kernel. However, I found that when booting, it will show that it is not supported and it only supports GKI. May I ask which version of kernelsu can only be used for the 4.4 kernel?
> > > > 
> > > > 
> > > > Did the compiled kernel boot?
> > > > Can you see "ksud.o" in the build logs?
> > > > Is OverlayFS enabled in the Defconfig?
> > > > Where is the source?
> > > > Did you manually integrate KSU, or did you use the KProbe method?
> > > 
> > > 
> > > Yes, Sir. I manually modified kprobe and ksu. In my tests, version 0.6 kernelsu passed the test, but 0.9.5 did not work. this is the kernel source . I did not find ksud.o in the 0.9.5 build file. this is the kernel source: :https://github.com/jagogardiner/kernel_xiaomi_acrux/tree/staging , i used acrux_defconfig to build.
> > 
> > 
> > if you didn't see "ksud.o" in build logs, that means KernelSU is not even enabled when you compile your kernel.
> > if you can fork that source, then modify it and commit your changes and upload it to github, I can review what's wrong with your source.
> 
> Ok,sir. The build project has been post ,the website is https://github.com/mzb98/acrux2

Okay, let me check

**Comment by mzb98** [comment]
> Do you have any build logs?

Sir,i don't have build log . You mean the command that is prompted at compile time?

**Comment by ravindu644** [comment]
> > Do you have any build logs?
> 
> Sir,i don't have build log . You mean the command that is prompted at compile time?

I created a pull request. your job is editing the build script to add toolchain paths and variables.

**Comment by mzb98** [comment]
> > > Do you have any build logs?
> > 
> > 
> > Sir,i don't have build log . You mean the command that is prompted at compile time?
> 
> I created a pull request. your job is editing the build script to add toolchain paths and variables.

Do I need to upload the compilation tool as well? My compiler tool is  installed by  apt ,so it hard to upload . The compile script is  [0mybuild.sh](https://github.com/mzb98/acrux2/blob/main/0mybuild.sh)

**Comment by ravindu644** [comment]
> > > > Do you have any build logs?
> > > 
> > > 
> > > Sir,i don't have build log . You mean the command that is prompted at compile time?
> > 
> > 
> > I created a pull request. your job is editing the build script to add toolchain paths and variables.
> 
> Do I need to upload the compilation tool as well? My compiler tool is installed by apt ,so it hard to upload . The compile script is [0mybuild.sh](https://github.com/mzb98/acrux2/blob/main/0mybuild.sh)

no. just run "git stash && git pull origin main" in your source (the source which is linked to that github repo)

**Comment by ravindu644** [comment]
> > > > > Do you have any build logs?
> > > > 
> > > > 
> > > > Sir,i don't have build log . You mean the command that is prompted at compile time?
> > > 
> > > 
> > > I created a pull request. your job is editing the build script to add toolchain paths and variables.
> > 
> > 
> > Do I need to upload the compilation tool as well? My compiler tool is installed by apt ,so it hard to upload . The compile script is [0mybuild.sh](https://github.com/mzb98/acrux2/blob/main/0mybuild.sh)
> 
> no. 

First, merge my pull request to your kernel repository in GitHub.

Then, run "git stash && git pull origin main" in your local source (the source which is linked to that github repo)

**Comment by mzb98** [comment]
> > > > > > Do you have any build logs?
> > > > > 
> > > > > 
> > > > > Sir,i don't have build log . You mean the command that is prompted at compile time?
> > > > 
> > > > 
> > > > I created a pull request. your job is editing the build script to add toolchain paths and variables.
> > > 
> > > 
> > > Do I need to upload the compilation tool as well? My compiler tool is installed by apt ,so it hard to upload . The compile script is [0mybuild.sh](https://github.com/mzb98/acrux2/blob/main/0mybuild.sh)
> > 
> > 
> > no.
> 
> First, merge my pull request to your kernel repository in GitHub.
> 
> Then, run "git stash && git pull origin main" in your local source (the source which is linked to that github repo)

Thank you sir , I've merged the code. I'll recompile and test it later.

**Comment by mzb98** [comment]
> > > > > > Do you have any build logs?
> > > > > 
> > > > > 
> > > > > Sir,i don't have build log . You mean the command that is prompted at compile time?
> > > > 
> > > > 
> > > > I created a pull request. your job is editing the build script to add toolchain paths and variables.
> > > 
> > > 
> > > Do I need to upload the compilation tool as well? My compiler tool is installed by apt ,so it hard to upload . The compile script is [0mybuild.sh](https://github.com/mzb98/acrux2/blob/main/0mybuild.sh)
> > 
> > 
> > no.
> 
> First, merge my pull request to your kernel repository in GitHub.
> 
> Then, run "git stash && git pull origin main" in your local source (the source which is linked to that github repo)

Thank you sir ,now it works
