### ISSUE TITLE
Unable to modify /vendor if the phone doesn't have a seperate vendor partition

### ISSUE THREAD

**Issue by theboringkid** [tiann/KernelSU#2108]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

On devices without a seperate vendor partition, `system/vendor` is not a symlink to `/vendor`. Therefore, any changes made in `$MODDIR/system/vendor` will not be in the actual `/vendor` folder, but only in `/system/vendor` which does not affect anything.
This can be worked around by placing the modifications in `$MODDIR/vendor`, but that folder should (according to documentation) be automatically generated and shall not be manually modified.
I think just like for devices that have a seperate vendor partiton, files in `$MODDIR/system/vendor`  should be moved to `$MODDIR/vendor` automatically.

### To Reproduce

1. Install a module that requires modification to /vendor (e.g. V4A) on a device without a seperate vendor partition

### Expected behavior

Files inside `$MODDIR/system/vendor` should be inside `/vendor`

### Logs

Note that while taking this log, I already put the v4a files manually into `$MODDIR/vendor`
[KernelSU_bugreport_2024-10-01_18_35.tar.gz](https://github.com/user-attachments/files/17213821/KernelSU_bugreport_2024-10-01_18_35.tar.gz)

### Device info

- Device: SM-G950F (Galaxy S8 with Exynos 8895)
- OS Version: Android 11 OneUI 3 (FloydR)
- KernelSU Version: 11457
- Kernel Version: 4.4.302 (hadesKernel v3.0.1)

**Comment by tiann** [comment]
You shouldn't put the files manully into `$MODDIR/vendor`, we've handled this case, but if you do it, it will be ignored.

https://github.com/tiann/KernelSU/blob/main/userspace/ksud/src/installer.sh#L307

**Comment by theboringkid** [comment]
> You shouldn't put the files manully into `$MODDIR/vendor`, we've handled this case, but if you do it, it will be ignored.

I don't think you understood my issue.

For my device, `/system/vendor` is _not_ a symlink to `/vendor`. My device does not have a vendor partition. 
Because of the code you've sent me, in my case modules can only modify `/system/vendor`.
However, the actual vendor files are stored in `/vendor` and _not_ in `system/vendor`. Therefore any module that tries to modify vendor files (e.g. adding the v4a library), does just modify files/directories, that are not meaningful.


I know that I shouldn't put files in `$MODDIR/vendor` but it is the only way I'm able to modify vendor files on my device. Thats why I think this is a bug.

**Comment by tiann** [comment]
It is not an independent partition, nor is it a symbolic link pointing to `/system/vendor`, so what is it?

**Comment by theboringkid** [comment]
Okay I dug around a bit. The vendor folder is inside the system partition. However, that doesn't get mounted at `/system`, but at `/` (See the KSU log). Interestingly, the S8 isn't a system-as-root device afaik (launching with Oreo) so I'm actually a bit confused now too.
