### ISSUE TITLE
kind request: please re-enable non-GKI kernel support | "os error 38/ Function not implemented" in the KernelSU Manager app when trying to install any module

### ISSUE THREAD

**Issue by LeeBinder** [tiann/KernelSU#2130]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Error:
```
Mounting image
Error: Function not implemented (os error 38)
Error: exit code = 1.
```

### To Reproduce

This error has been occurring since commit fd09ccf ("Drop some legacy codes", #1981) https://github.com/tiann/KernelSU/commit/fd09ccfc2906ad119f7158f9518810e06a73a919
pushed on 2024-08-15 by yujincheng08 https://github.com/tiann/KernelSU/actions/runs/10401460643

The latest working version I found to be the one from the commit before on the same day, KernelSU_v1.0.1-20-gbbc31bdb_11948-release.apk from https://github.com/tiann/KernelSU/actions/runs/10401046882

### Expected behavior

zip package installations should run all the way through, ending with the prompt to restart

### Logs

[KernelSU_install_logs.zip](https://github.com/user-attachments/files/17356859/KernelSU_install_logs.zip)

### Device info

- Device: Nokia 6.1 ("PL2")
- OS Version: Android 14/ crDroid 10.8 official, by default KernelSU enabled by the ROM's dev
- KernelSU Version: most current Manager app from Actions all the way down to KernelSU_v1.0.1-21-gfd09ccfc_11949-release
- Kernel Version: 4.4.302-perf+ (non-GKI)

### Additional context

@yujincheng08 Is the reason for dropping some legacy codes simply a more or less cosmetic cleanup, or does it offer any real advantage ever since apart from maybe a slightly smaller app? If it's the first, may I kindly you please consider re-adding these legacy codes so even users with devices running on a non-GKI kernel can again run and benefit from your's and the team's current development? That would be awesome :)

Thank you for looking into this.

**Comment by LeeBinder** [comment]
![](https://i.imgflip.com/41r3nw.jpg) 🙋🏻‍♂️

**Comment by Ftayaan** [comment]
I got the same error .I fixed it by changing apk file of ksu .if you install the latest version from official it would fix the issue

**Comment by LeeBinder** [comment]
That wouldn't be a "fix" at all, Ftayaan, but only a work-around by downgrading! Because he latest release is older than the current ones from Actions...

**Comment by JeanxPereira** [comment]
same here

**Comment by LeeBinder** [comment]
Thanks JeanxPereira for reporting, too. In the description for today's [v1.0.2 release](https://github.com/tiann/KernelSU/releases/tag/v1.0.2), it reads:

> WARNING: Non-GKI devices should not upgrade to this version!

Would be really sad if that was final from now on with users of older devices not able to get KernelSU manager updates anymore 🙁

**Comment by JeanxPereira** [comment]
oh what a shame :(
Will the new versions not work even if I am using a GKI kernel?

Device: Mi 10T [Apollo]
OS: PixelOS_apollo-14.0-20241016-2005
Kernel: N0Kernel_apollo-16.0.1

**Comment by angelokimhui** [comment]
Time to move to APatch I guess.

**Comment by LeeBinder** [comment]
What's APatch? Never heard of of it.

**Comment by Ylarod** [comment]
We don't provide official support to non-GKI devices now.

**Comment by LeeBinder** [comment]
[rsuntk/ KernelSU](https://github.com/rsuntk/KernelSU): KernelSU with MagicMount, support GKI **and Non-GKI** !!

- Latest release v1.0.2-40-legacy from Dec. 30, 2024 - get it from https://github.com/rsuntk/KernelSU/releases

- even more recent (nightly/ pre-) releases from his [Actions section](https://github.com/rsuntk/KernelSU/actions?query=is%3Asuccess), also announced on his [Telegram channel](https://t.me/rsukrnlsu) - latest as of now from Jan. 5, 2025.

Not tested yet - just want to let anybody interested know so you folks have a chance to test while I'm still out-and-about

**Comment by billabongbruno** [comment]
> [rsuntk/ KernelSU](https://github.com/rsuntk/KernelSU): KernelSU with MagicMount, support GKI **and Non-GKI** !!
> 
> * Latest release v1.0.2-40-legacy from Dec. 30, 2024 - get it from https://github.com/rsuntk/KernelSU/releases
> * even more recent (nightly/ pre-) releases from his [Actions section](https://github.com/rsuntk/KernelSU/actions?query=is%3Asuccess), also announced on his [Telegram channel](https://t.me/rsukrnlsu) - latest as of now from [Jan. 5, 2025](https://github.com/rsuntk/KernelSU/actions/runs/12619042277#artifacts).
> 
> Not tested yet - just want to let anybody interested know so you folks have a chance to test while I'm still out-and-about

Hey there.
I have been struggling with this issue for a while on some of my devices (the drop of support for non-GKI devices) aswell.

I had learned to live with the 1.0.1 version of KSU rather than having the latest app until I came across your post here, which in turn led me to that GitHub repo, just to find out it didn't work.

However, me being stubborn as I am, I finally found a working repo that's on par with the latest official KSU release and works with non-GKI devices / kernels.

Here it is:
[](https://github.com/backslashxx/KernelSU)

Hope it helps.


Best regards,
Bruno.

**Comment by LeeBinder** [comment]
Thank you, but non of the forks (and not even any of their older releases or nightly builds from Actions) work with my Nokia 6.1's old 4.4.302-perf+ Kernel (crDroid 11/ Android 15) :(

Which Kernel version does your phone have? It's displayed in KernelSU Manager start page.

**Comment by LeeBinder** [comment]
Explanation what's going on see pull request  [Revert "Drop some legacy codes (#1981)" #2153 ](https://github.com/tiann/KernelSU/pull/2153) and below.

In that context, for some users with non-GKi kernel devices, https://github.com/Fede2782/KernelSU/releases might work

**Comment by LeeBinder** [comment]
YES, working - figured it out on my Nokia 6.1 with crDroid 10.11 Official/ Android 14 😉

1. in KernelSU Manager, install LSPosed (I use [JingMatrix/LSPosed](https://github.com/JingMatrix/LSPosed) latest from [Actions](https://github.com/JingMatrix/LSPosed/actions)) as module, reboot
2. install the [Core Patch XPosed App](https://github.com/LSPosed/CorePatch), best latest from [Actions](https://github.com/LSPosed/CorePatch/actions?query=is%3Asuccess). It will allow to install apks with a different signature than the one already installed (in our case KernelSU Manager forks)
3. in LSPosed, enable the Core Patch module then also enable it for both, System Framework AND KernelSU
4. in KernelSU Manager → Superuser: tap onto Core Patch and activate Superuser for it
5. Without reboot, try installing one of two KernelSU Manager forks with both, MagicMount and non-GKI support, either [rsuntk/ KernelSU](https://github.com/rsuntk/KernelSU) (best most recent from [Actions](https://github.com/rsuntk/KernelSU/actions?query=is%3Asuccess)) or [backslashxx/KernelSU](https://github.com/backslashxx/KernelSU)<br><br>If that didn't work right away, reboot and try again<br><br>
6. Open KernelSU Manager and verify that it's working

😎

**Comment by LeeBinder** [comment]
**KernelSU Next** - A kernel-based root solution for Android | Supports kernel 4.4 - 6.6 (Non-GKI & GKI)

https://rifsxd.github.io/KernelSU-Next/
https://github.com/rifsxd/KernelSU-Next

**Comment by Hongshi607** [comment]
你好.
