### ISSUE TITLE
manager: module: refresh after action button action

### ISSUE THREAD

**Issue by backslashxx** [tiann/KernelSU#2171]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

user has to pull down to refresh after action button action
some modules use description ie on module.prop to show status

### To Reproduce

https://github.com/backslashxx/bindhosts/blob/4e7ba03e0576b0e0bceac5c1ba4f1d2f3260814c/action.sh#L98
- this part where description gets updated

### Screenshots

https://github.com/user-attachments/assets/685cfedc-3649-4bab-ae98-9e2126a1744a

### Expected behavior

Module manager refreshes itself

https://github.com/user-attachments/assets/7e76bbc5-dee5-441f-9d60-a99c5e29359e

### Logs

irrelevant

### Device info

- Device: irrelevant
- OS Version: A14 QPR3
- KernelSU Version: 11985 (reverted for < 5.2 )
- Kernel Version: irrelevant
https://github.com/backslashxx/KernelSU

**Comment by rsuntk** [comment]
Maybe creating a refresh function after action button was pressed is a good idea.

**Comment by rsuntk** [comment]
> it gets refreshed on module updates/customize.sh triggers but not on action
ofcourse this is also on downstream, Apatch

Apatch refreshed by default?

**Comment by rsuntk** [comment]
Modify onBack function maybe can fix it
