### ISSUE TITLE
Cant flash module in ksu after uodate some leaks pls fix it

### ISSUE THREAD

**Issue by Gittex77** [tiann/KernelSU#2180]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

I can flash any module but when I go go for older KSU manager I can after update its gone too

### Screenshots

![Screenshot_20241101-160451_KernelSU](https://github.com/user-attachments/assets/0281e922-0a16-4379-8cce-e900290100b3)

### Device info

- Device: Redmi note 9
- OS Version: lineage is 20
- KernelSU Version: latest
- Kernel Version:fearless kernel latest

**Comment by angelokimhui** [comment]
Your device does not meet the GKI requirements and the latest version explicitly said that you should not update KernelSU Manager if using non-GKI devices. Please downgrade KernelSU apk to fix in the meantime and wait for update.

Duplicate: https://github.com/tiann/KernelSU/issues/2179#issuecomment-2451644795

**Comment by Ylarod** [comment]
We don't provide official support to non-GKI devices now.
