### ISSUE TITLE
A large amount of storage capacity is displayed.

### ISSUE THREAD

**Issue by tagjg** [tiann/KernelSU#2185]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

A large amount of storage capacity is displayed.
My device's original storage capacity is 128GB, but it is showing as 2.0TB.
![Screenshot_20241102-193434](https://github.com/user-attachments/assets/9f069f10-a97d-4b19-8837-4bd3fa739ef7)

### To Reproduce

1.Patch boot.img with kernelsu.
2.Flash the boot.img.

### Expected behavior

The correct storage capacity is displayed.

### Device info

- Device:Xperia 5 IV（A204SO）
- OS Version:14
- KernelSU Version:v1.0.2
- Kernel Version:5.10.198-android12-9-00043-g4d382310f0e9-ab12017590
#1 Wed Jun 26 07:57:15 UTC 2024

### Additional context

 This bug did not exist with Magisk, APatch, etc.
I have tried other versions of KernelSU and this bug still occurs.

**Comment by naranyinyun** [comment]
just read the document
https://kernelsu.org/guide/faq.html#why-is-there-a-huge-1-tb-file
