### ISSUE TITLE
OS error 38 while installing modules

### ISSUE THREAD

**Issue by MarekSurek** [tiann/KernelSU#2186]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

While installing any module, in 1.0.2 OS error 38 pops out. On 1.0.1 there's no issue.

### To Reproduce

1. go to install modules
2. try to install one
3. see os error 38

### Expected behavior

Module should be installed

### Screenshots

![Screenshot_20241102-205157_KernelSU](https://github.com/user-attachments/assets/681a466f-a059-465d-ac90-154d38a4f311)

### Logs

[KernelSU_install_log_2024-11-02-20-57-12.log](https://github.com/user-attachments/files/17608179/KernelSU_install_log_2024-11-02-20-57-12.log)

### Device info

- Device: RMX2170
- OS Version: 14
- KernelSU Version: 1.0.2
- Kernel Version: 4.14.336

**Comment by angelokimhui** [comment]
Duplicate : https://github.com/tiann/KernelSU/issues/2180#issuecomment-2451722171

**Comment by MurtazaKolachi** [comment]
I'm also facing this same issue

**Comment by LeCmnGend** [comment]
Me too. Os38 error and the same log

**Comment by Fyg369** [comment]
Isn’t it not supported by non-gki kernels?

**Comment by Fede2782** [comment]
You are using non-GKI. KernelSU dropped non-GKI support in v1.0.0 (kernel space) and v1.0.2 (userspace).

**Comment by msgcg** [comment]
Was same issue, You can install 0.7.6 version, flash modules, than update to latest version

**Comment by Ylarod** [comment]
We don't provide official support to non-GKI devices now.
