### ISSUE TITLE
I wonder whether we could patch vmlinux to support Kernel-SU.

### ISSUE THREAD

**Issue by 1457384613gh** [tiann/KernelSU#22]
I wonder whether we could patch `vmlinux` to support Kernel-SU or not.

For chromeOS, I've seen `vmlinux` `system.raw.img` `vendor.raw.img` into `ROOT-A: /opt/google/vms/android`.

I want to make its Android Container rooted, so could I patch `vmlinux` to support Kernel-SU？

**Comment by tiann** [comment]
What is the version of the kernel? KernelSU only supports Android GKI(general kernel image). 

If it is, you can download the `Image.gz` from [CI](https://github.com/tiann/KernelSU/actions) and uncompress it with gzip, then replace the `vmlinux` with the `Image`(the `Image` is actually a `vmlinux` file).

**Comment by 1457384613gh** [comment]
Several versions of kernel, such as 5.10 and 5.15.

**Comment by tiann** [comment]
ok, just upload it and i will take a look.

**Comment by 1457384613gh** [comment]
[vmlinux + ureadahead.pack.zip](https://github.com/tiann/KernelSU/files/10312085/vmlinux.%2B.ureadahead.pack.zip)

I don't know what `ureadahead.pack` is, so upload, too.

**Comment by tiann** [comment]
This kernel seems not a GKI kernel, maybe you should download the kernel source and compile it by yourself.

**Comment by 1457384613gh** [comment]
Thank you!

**Comment by tiann** [comment]
I will close this, if you have any issue on build kernel source with KernelSU, please file another issue.

**Comment by tiann** [comment]
GKI 目前只存在于 Android 手机和平板，其他的内核版本高于 5.10 的 Android 系统，如 WSL, ChromeOS，甚至 Android Wear, Android Tv 目前都不适用于 GKI。也就是说，如果你想在这些设备上使用 KernelSU，依然需要自行编译内核。
