### ISSUE TITLE
App crashes when there is an update and no browser is installed

### ISSUE THREAD

**Issue by Angxddeep** [tiann/KernelSU#2210]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

So it took me a while to understand what was happening. I was using Pixel OS with no browser installed and when I clicked on the update KernelSU option, it crashed but after installed brave it opened up and downloaded the latest update.

### To Reproduce

1.use an old version of KSU 
2.Click on update 
3. make sure no browser is installed

### Screenshots

![Screenshot_20241113-104944](https://github.com/user-attachments/assets/61b05095-b6e7-4097-9b63-4bfbb827f481)

### Logs

https://bin.mkr.pw/~673436f5632ce757b62662b3

### Device info

- Device:xaga(Redmi K50i)
- OS Version:A15

**Comment by tiann** [comment]
Who would use a device without a browser? If that’s the case, you can update it manually.

**Comment by Angxddeep** [comment]
> Who would use a device without a browser? If that’s the case, you can update it manually.

I am just letting you know as I said.
