### ISSUE TITLE
action.sh按钮触发的执行页面while命令卡死

### ISSUE THREAD

**Issue by log-D** [tiann/KernelSU#2214]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

我写了一个shell脚本，内容是通过捕音量键下将a值循环递增范围是1-3循环，通过捕获音量键上条件判断选择并执行1-3的功能，但是在我通过手机终端执行能够正常显示，但是放入模块内重命名为action.sh，通过KSU模块按钮执行该功能时，循环体内的内容没有显示出来并且卡死无响应。

### To Reproduce

#shell 代码
key_click() {
    while true; do sleep 0.5
    keyInfo=$(getevent -qlc 1 | grep KEY_VOLUME)
    #echo $keyInfo
    if [ "$keyInfo" == "" ]; then
    continue
    else
    UpKey=$(echo $keyInfo | grep KEY_VOLUMEUP)
    #echo $UpKey
    [ "$UpKey" != "" ] && return 1 || return 0
    break
fi
done
}
key_click1() {
    kc=""
    while [ "$kc" = "" ]; do
        kc="$(getevent -qlc 1 | awk '{ print $3 }' | grep 'KEY_')"
        #echo $kc
        sleep 0.5
    done
}
funcshow(){
    if [ $a -eq 1 ]; then
        #clear
        echo "功能$a 请按压音量键上确认选择"
        key_click1
    elif [ $a -eq 2 ]; then
        #clear
        echo "功能$a 请按压音量键上确认选择"
        key_click1
    elif [ $a -eq 3 ]; then
        #clear
        echo "功能$a: 恢复关闭的温控  请按压音量键上确认选择"
        key_click1
    elif [ $a -gt 4 ];then
        a=0
    fi
}
funcrun(){
    if [ $a -eq 1 ]; then
           echo "你选择了功能$a"
    elif [ $a -eq 2 ]; then
        echo "你选择了功能$a"
    elif [ $a -eq 3 ]; then
        echo "你选择了功能$a"
    fi
}
while true; do
    if [[ $kc == *"UP"* ]]; then
        echo "您确认了运行了功能$a"
        funcrun
        echo "点击音量键上或下结束或退出😘"
        key_click
        break
    else
        ((a++))
        funcshow
    fi
done

### Logs

[KernelSU_bugreport_2024-11-14_20_54.tar.gz](https://github.com/user-attachments/files/17749079/KernelSU_bugreport_2024-11-14_20_54.tar.gz)

### Device info

- Device: Redmi K60U
- OS Version:Hyper OS 1.0.22.0.UMLCNXM
- KernelSU Version: 11986
- Kernel Version: v1.0.2(11986)

**Comment by pilotayy** [comment]
自己的问题啊,反馈啥啊反馈👎
