### ISSUE TITLE
[Feacture request] add gki 5.4 with Novembre pach

### ISSUE THREAD

**Issue by Usernamamama** [tiann/KernelSU#2221]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Is feacture request 

### To Reproduce

K

### Expected behavior

Have 5.4 gki

### Screenshots

E

### Logs

Nope

### Device info

- Device:a52sxq
- OS Version:14
- KernelSU Version:1.0.2
- Kernel Version:5.4

### Additional context

No

**Comment by tiann** [comment]
5.4 is not GKI 2.0.
