### ISSUE TITLE
一加13 init_boot刷入成功、临时内核启动、boot.img repack,均显示未安装.

### ISSUE THREAD

**Issue by acvlwe** [tiann/KernelSU#2235]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

按照guide几种方法都试了,都能成功启动但是管理器中就是显示未安装.头大

### Screenshots

![Screenshot_2024-01-01-02-30-11-15_baaa51257c82a8b3f281ce09e6f2493f](https://github.com/user-attachments/assets/f9630d18-5e8b-4ee0-ae06-f6fc8ea3ffd1)
![Screenshot_2024-01-01-02-30-39-72_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/user-attachments/assets/217db378-016a-423a-b6e1-60b33df75dbf)

### Logs

[KernelSU_bugreport_2024-01-01_02_23.tar.gz](https://github.com/user-attachments/files/17874182/KernelSU_bugreport_2024-01-01_02_23.tar.gz)

### Device info

- Device: oneplus 13
- OS Version:  ColorOS PJD110_15.0.0.204(CN01)
- KernelSU Version: 1.0.2
- Kernel Version: 6.6.30-android15-8

**Comment by acvlwe** [comment]
需要重新把管理器安装一次解决.........

**Comment by xiaooloong** [comment]
11986 同版本的管理器，使用 patch init_boot 的方法。houji os2.0.6.0 6.1.75-android14-11 也遇到同样的问题，每次开机后管理器均显示未安装，需要重新安装一次管理器。

**Comment by 96368a** [comment]
同样的问题，mi13 os2.0.3.0 6.1.148 android15，11986 版本管理器，使用所有方式刷入均显示未安装，并且重新安装一次管理器之后还是显示未安装
