### ISSUE TITLE
ksud sepolicy apply file doesn't work

### ISSUE THREAD

**Issue by sekaiacg** [tiann/KernelSU#227]
**Describe the bug**
command: `ksud sepolicy apply file`
1.Execution succeed and doesn't work.

**To Reproduce**
1. exec: `/data/adb/ksud sepolicy apply /cache/l.rule`
2. result: `NormalPerm(NormalPerm { op: "allow", source: ["platform_app"], target: ["default_prop"], class: ["property_service"], perm: ["set"] })`
3. ` [ 1125.629091] type=1107 audit(1676100930.295:2015): uid=0 auid=4294967295 ses=4294967295 subj=u:r:init:s0 msg='avc: denied { set } for property=persist.mi.current_action pid=13647 uid=10062 gid=10062 scontext=u:r:platform_app:s0:c512,c768 tcontext=u:object_r:default_prop:s0 tclass=property_service permissive=0'`

**Expected behavior**
Execute successfully and take effect

**Screenshots**
![0001](https://user-images.githubusercontent.com/33929605/218246336-ec19fb43-bf65-4032-b129-447b10390a3a.png)

**Smartphone (please complete the following information):**
 - Device: [xiaomi 10 pro]
 - OS: [android 12]
 - Version [miui dev 22.7.19]
 - KernelSU/Manager  [10582/3.7]

**Additional context**
`allow platform_app default_prop property_service set`

**Comment by sekaiacg** [comment]
Try using magiskpolicy:
```
cmi:/ # magiskpolicy --live "allow platform_app default_prop property_service set"
fopen /sys/fs/selinux/policy failed with 22: Invalid argument
```

**Comment by tiann** [comment]
Does magiskpolicy work without KernelSU?

**Comment by sekaiacg** [comment]
> Does magiskpolicy work without KernelSU?

Yes, magiskpolicy works fine without kernel su enabled.
Is it necessary to notify to take effect after modifying avc_table?
`avc_ss_reset - Flush the cache and revalidate migrated permissions. : policy sequence number`
https://elixir.bootlin.com/linux/v4.19.272/source/security/selinux/avc.c#L970

**Comment by tiann** [comment]
You can try add this policy before anyone can do (maybe post-fs-data), if the policy is denied before, it won't query the avc table.

**Comment by tiann** [comment]
But the magiskpolicy open failed seems meaning we break something of SELinux

**Comment by sekaiacg** [comment]
> 

翻译太麻烦了…
我执行过：
setenforce 0
setenforce 1
之后ksud添加的规则生效了
同时magisk或ksud模块sepolicy.rule开机时是生效的
只是进系统后：
1.magiakpolicy报错
2.ksud没某效果
所以我觉得是不是需要刷新缓存
setenforce是有这些步骤的，当然，我不了解具体原因

**Comment by tiann** [comment]
有这个可能。如果 SELinux 曾经拒绝过某个策略，那就会直接命中缓存里的拒绝策略，不会再去查 avc table 了。如果开机的时候添加生效，但后续不生效，大概率是这个原因。

**Comment by sekaiacg** [comment]
> 有这个可能。如果 SELinux 曾经拒绝过某个策略，那就会直接命中缓存里的拒绝策略，不会再去查 avc table 了。如果开机的时候添加生效，但后续不生效，大概率是这个原因。

https://github.com/tiann/KernelSU/blob/d9aecbcbca79d730f6f4aec2cff269c18ee7ad02/kernel/core_hook.c#L236-L244
成功调用handle_sepolicy后尝试增加`avc_ss_reset(state->avc, 0);` ？

我使用的内核是其他作者编译的，没办法测试......

**Comment by sekaiacg** [comment]
我也发现涉及一些其他的地方，复杂...
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/blob/cmi-r-oss/security/selinux/selinuxfs.c#L178-L181

**Comment by tiann** [comment]
我试过，直接调用 `avc_ss_reset` 会卡死

**Comment by sekaiacg** [comment]
> 我试过，直接调用 `avc_ss_reset` 会卡死

我相信大佬，一定有办法

**Comment by tiann** [comment]
更新到这个 commit 看下是否可以：https://github.com/tiann/KernelSU/commit/f6967d2cfba7557185f3d14444711c1a32ca37ff

**Comment by sekaiacg** [comment]
> 更新到这个 commit 看下是否可以：[f6967d2](https://github.com/tiann/KernelSU/commit/f6967d2cfba7557185f3d14444711c1a32ca37ff)

大佬厉害
测试可能会晚一点......

**Comment by sekaiacg** [comment]
> 更新到这个 commit 看下是否可以：[f6967d2](https://github.com/tiann/KernelSU/commit/f6967d2cfba7557185f3d14444711c1a32ca37ff)

这个提交没有效果

然后我发现还有地方要加上：
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/blob/64b40409431988d060f7484369c8c2d7deca1bb3/security/selinux/ss/services.c#L2936-L2941
这样就可以了，以下是修改后的代码：
```
#include "xfrm.h"
......
static void reset_avc_cache() {
#if LINUX_VERSION_CODE < KERNEL_VERSION(4, 14, 163)
	avc_ss_reset(0);
	selnl_notify_policyload(0);
	selinux_status_update_policyload(0);
#else
	struct selinux_avc *avc = selinux_state.avc;
	avc_ss_reset(avc, 0);
	selnl_notify_policyload(0);
	selinux_status_update_policyload(&selinux_state, 0);
#endif
	selinux_xfrm_notify_policyload();
}
```
最后magiskpolicy出错时只有：                                                            
`fopen /sys/fs/selinux/policy failed with 22: Invalid argument`
没有更多的信息了

**Comment by tiann** [comment]
是只要内核是 KernelSU，不做任何操作（比如你上面的 allow） magiskpolicy 就无法工作？

**Comment by tiann** [comment]
https://github.com/tiann/KernelSU/commit/20ff53096285f706f22200fc7fd720d7285c7bca 加上去了

**Comment by sekaiacg** [comment]
> 是只要内核是 KernelSU，不做任何操作（比如你上面的 allow） magiskpolicy 就无法工作？

启用了KernelSU magiskpolicy就无法工作。但是magisk 模块中的sepolicy.rule生效。
是不是ksu启动到某个阶段后导致的？

**Comment by tiann** [comment]
> > 是只要内核是 KernelSU，不做任何操作（比如你上面的 allow） magiskpolicy 就无法工作？
> 
> 启用了KernelSU magiskpolicy就无法工作。但是magisk 模块中的sepolicy.rule生效。 是不是ksu启动到某个阶段后导致的？

magisk 加载策略比 ksu 早，很可能是 ksu 加载后就异常了。但是，我这里用 5.10 的内核测试，magiskpolicy 是正常的。可以在 https://elixir.bootlin.com/linux/v4.19.272/source/security/selinux/selinuxfs.c#L374 这里打点日志看看到底是哪里有问题。

**Comment by sekaiacg** [comment]
> > > 是只要内核是 KernelSU，不做任何操作（比如你上面的 allow） magiskpolicy 就无法工作？
> > 
> > 
> > 启用了KernelSU magiskpolicy就无法工作。但是magisk 模块中的sepolicy.rule生效。 是不是ksu启动到某个阶段后导致的？
> 
> magisk 加载策略比 ksu 早，很可能是 ksu 加载后就异常了。但是，我这里用 5.10 的内核测试，magiskpolicy 是正常的。可以在 https://elixir.bootlin.com/linux/v4.19.272/source/security/selinux/selinuxfs.c#L374 这里打点日志看看到底是哪里有问题。

好的，我会尝试

**Comment by tiann** [comment]
https://github.com/tiann/KernelSU/blob/main/kernel/selinux/sepolicy.c#L692
操作这里的只有这一个

**Comment by sekaiacg** [comment]
**fp->len:**
`*len = security_policydb_len(state);`
` [ 4962.048508] skkk8: len=2041758 `
**policy file:** `-r--r--r-- 1 root root 2041758 1970-01-01 08:00 /sys/fs/selinux/policy`

https://elixir.bootlin.com/linux/v4.19.272/source/security/selinux/ss/policydb.h#L359
```
static inline int put_entry(const void *buf, size_t bytes, int num, struct policy_file *fp)
{
	size_t len = bytes * num;

	if (len > fp->len)
		return -EINVAL;
	memcpy(fp->data, buf, len);
	fp->data += len;
	fp->len -= len;

	return 0;
}
```
是文件长度不正确？

**Comment by tiann** [comment]
有可能是这里不对：https://github.com/tiann/KernelSU/blob/main/kernel/selinux/sepolicy.c#L131
这逻辑我确实没在非 GKI 验证过。

**Comment by sekaiacg** [comment]
> 有可能是这里不对：https://github.com/tiann/KernelSU/blob/main/kernel/selinux/sepolicy.c#L131 这逻辑我确实没在非 GKI 验证过。

我有点害怕

**Comment by tiann** [comment]
可以把 ksu 的内置策略用 magiskpolicy 加载一下，然后看看它的 len 是多少

**Comment by sekaiacg** [comment]
```
struct avtab_node {
	struct avtab_key key;
	struct avtab_datum datum;
	struct avtab_node *next;
}
struct avtab_key {
	u16 source_type;	/* source type */
	u16 target_type;	/* target type */
	u16 target_class;	/* target object class */
	u16 specified;	/* what field is specified */
};
struct avtab_datum {
	union {
		u32 data; /* access vector or type value */
		struct avtab_extended_perms *xperms;
	} u;
};
struct avtab_extended_perms {
	/* extension of the avtab_key specified */
	u8 specified; /* ioctl, netfilter, ... */
	/*
	 * if 256 bits is not adequate as is often the case with ioctls, then
	 * multiple extended perms may be used and the driver field
	 * specifies which permissions are included.
	 */
	u8 driver;
	/* 256 bits of permissions */
	struct extended_perms_data perms;
};
struct extended_perms_data {
	u32 p[8];
};
```

没有xperms:
sizeof(u16) * 4 + sizeof(u32);
有xperms:
sizeof(u32) * 4 + sizeof(u32) + sizeof(u8) + sizeof(u8) + sizeof(u32) * ARRAY_SIZE(avdatum.u.xperms->perms.p)


https://github.com/tiann/KernelSU/blob/eeb8cda1755a74b4c61081fa797bfac2f86df266/kernel/selinux/sepolicy.c#L131-L140

是不是少了一个avtab_datum.data
这个`grow_size += sizeof(u32) * 1; `

**Comment by sekaiacg** [comment]
代码修改为：
```
int grow_size = sizeof(u16) * 4; 
grow_size += sizeof(u32);
if (key->specified & AVTAB_XPERMS) { 
 	grow_size += sizeof(u8); 
 	grow_size += sizeof(u8); 
 	grow_size += sizeof(u32) * 
 		     ARRAY_SIZE(avdatum.u.xperms->perms.p); 
 }
```
日志结果：
```
[   85.698102] skkk12: rc=2041770
[   85.698105] skkk5: security_read_policy rc=0
```

看起来正常了，这个计算是对的吗?
我再用magiskpolicy手动加载一下看看结果

**Comment by sekaiacg** [comment]
我还是用magiskpolicy加载后看看结果吧

**Comment by tiann** [comment]
这个 union 在 arm64 上应该是 sizeof void*=u64

**Comment by sekaiacg** [comment]
未启用KSU
开机时为0
```
cmi:/ # ls -al /sys/fs/selinux/policy                                                                
-r--r--r-- 1 root root 0 1970-01-01 08:00 /sys/fs/selinux/policy
```

```
magiskpolicy --live "permissive su"
-r--r--r-- 1 root root 1597212 1970-01-01 08:00 /sys/fs/selinux/policy
```
```
magiskpolicy --live "typeattribute su mlstrustedsubject"
cmi:/ # ls -al /sys/fs/selinux/policy                                                                
-r--r--r-- 1 root root 1597224 1970-01-01 08:00 /sys/fs/selinux/policy
```
......

```
magiskpolicy --live "allow kernel adb_data_file dir *"
-r--r--r-- 1 root root 2373264 1970-01-01 08:00 /sys/fs/selinux/policy
```

超出ksu很多了。好像没办法判断...

**Comment by tiann** [comment]
> 代码修改为：
> 
> ```
> int grow_size = sizeof(u16) * 4; 
> grow_size += sizeof(u32);
> if (key->specified & AVTAB_XPERMS) { 
>  	grow_size += sizeof(u8); 
>  	grow_size += sizeof(u8); 
>  	grow_size += sizeof(u32) * 
>  		     ARRAY_SIZE(avdatum.u.xperms->perms.p); 
>  }
> ```
> 
> 日志结果：
> 
> ```
> [   85.684340] skkk6: enter security_read_policy
> [   85.684345] skkk8: len=2045562
> ```
> 
> 是对的 -r--r--r-- 1 root root 2045562 1970-01-01 08:00 policy

你这样修改之后，magiskboot 能正常工作不？/sys/fs/selinux/policy 是否可以正常读写？

**Comment by sekaiacg** [comment]
> > 代码修改为：
> > ```
> > int grow_size = sizeof(u16) * 4; 
> > grow_size += sizeof(u32);
> > if (key->specified & AVTAB_XPERMS) { 
> >  	grow_size += sizeof(u8); 
> >  	grow_size += sizeof(u8); 
> >  	grow_size += sizeof(u32) * 
> >  		     ARRAY_SIZE(avdatum.u.xperms->perms.p); 
> >  }
> > ```
> >   
> > 日志结果：
> > ```
> > [   85.684340] skkk6: enter security_read_policy
> > [   85.684345] skkk8: len=2045562
> > ```
> >   
> > 是对的 -r--r--r-- 1 root root 2045562 1970-01-01 08:00 policy
> 
> 你这样修改之后，magiskboot 能正常工作不？/sys/fs/selinux/policy 是否可以正常读写？

magiskboot 能正常工作，规则也能生效，/sys/fs/selinux/policy默认权限是只读的
我改成0644后
```
cat /sys/fs/selinux/policy > /cache/p
cat /cache/p > /sys/fs/selinux/policy 
cat: xwrite: Invalid argument
```
无法写入。

**关闭KSU后也无法写入。**

**Comment by sekaiacg** [comment]
不知道写没写错.....不懂这里。

**Comment by tiann** [comment]
`/sys/fs/selinux/load` 不支持 seq_write，必须整个丢进去，用 cat + pipe 应该都会直接失败。

**Comment by tiann** [comment]
试一下这个：https://github.com/tiann/KernelSU/commit/f9b3218dedaf3a5af51c489695d9666ca644902d

如果能使应该就没问题了。

**Comment by sekaiacg** [comment]
> 试一下这个：[f9b3218](https://github.com/tiann/KernelSU/commit/f9b3218dedaf3a5af51c489695d9666ca644902d)
> 
> 如果能使应该就没问题了。

这是在4.19.256中新加入的
selinux: Add boundary check in put_entry()
https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.19.256

**Comment by sekaiacg** [comment]
> 试一下这个：[f9b3218](https://github.com/tiann/KernelSU/commit/f9b3218dedaf3a5af51c489695d9666ca644902d)
> 
> 如果能使应该就没问题了。

可能要晚一点，内核不是我编译的

**Comment by sekaiacg** [comment]
> 

原来是这样

**Comment by sekaiacg** [comment]
> 试一下这个：[f9b3218](https://github.com/tiann/KernelSU/commit/f9b3218dedaf3a5af51c489695d9666ca644902d)
> 
> 如果能使应该就没问题了。

这是之前的，实际2045562，写入2041782，大小不一致
```
cmi:/ # ls -al /sys/fs/selinux/policy                                                                
-r--r--r-- 1 root root 2045562 1970-01-01 08:00 /sys/fs/selinux/policy

cmi:/ # cat /sys/fs/selinux/policy > /cache/p
1|cmi:/ # dd if=/cache/p of=/sys/fs/selinux/load bs=2045562                                          
0+1 records in
0+1 records out
2041782 bytes (1.9 M) copied, 0.032909 s, 59 M/s

cmi:/ # ls -al /sys/fs/selinux/policy
-r--r--r-- 1 root root 2041782 1970-01-01 08:00 /sys/fs/selinux/policy
```

[f9b3218](https://github.com/tiann/KernelSU/commit/f9b3218dedaf3a5af51c489695d9666ca644902d)

```
cmi:/ # ls -al /sys/fs/selinux/policy
-r--r--r-- 1 root root 2184234 1970-01-01 08:00 /sys/fs/selinux/policy

cmi:/ # cat /sys/fs/selinux/policy > /cache/p
cmi:/ # dd if=/cache/p of=/sys/fs/selinux/load bs=2184234
0+1 records in
0+1 records out
2041782 bytes (1.9 M) copied, 0.033362 s, 58 M/s

cmi:/ # ls -al /sys/fs/selinux/policy                                                                
-r--r--r-- 1 root root 2041782 1970-01-01 08:00 /sys/fs/selinux/policy
```

因为误差有点大，我又看了下之前的log

**fp->len:**
`*len = security_policydb_len(state);`
` [ 4962.048508] skkk8: len=2041758 `
**policy file:** `-r--r--r-- 1 root root 2041758 1970-01-01 08:00 /sys/fs/selinux/policy`

发现最开始出错时的大小：2041758
现在写入的大小：2041782
相差24

我在本地编写程序输出了一下struct大小：
```
typedef unsigned char u8;
typedef unsigned short u16;
typedef unsigned int u32;

skkk: extended_perms_data=32
skkk: avtab_extended_perms=36
skkk: avtab_datum=8
skkk: avtab_key=8
skkk: avtab_node=24
skkk: u8=1
skkk: u16=2
skkk: u32=4
```
正好差一个avtab_node？

**Comment by sekaiacg** [comment]
**fp->len:**
`*len = security_policydb_len(state);`
` [ 4962.048508] skkk8: len=2041758 `
**policy file:** `-r--r--r-- 1 root root 2041758 1970-01-01 08:00 /sys/fs/selinux/policy`

发现最开始出错时的大小：2041758
现在写入的大小：2041782
相差24
时在是分析不下去了
https://github.com/tiann/KernelSU/blob/eeb8cda1755a74b4c61081fa797bfac2f86df266/kernel/selinux/sepolicy.c#L131-L140

最原始的代码应该没有问题，不清楚哪里有错误，不排除第三放内核有问题

**Comment by sekaiacg** [comment]
android12-5.10-2022-11的时候还没有加入(5.10.136)
https://android.googlesource.com/kernel/common/+/refs/heads/android12-5.10-2022-11/security/selinux/ss/policydb.h#373

android12-5.10-2022-12加入(5.10.149)
https://android.googlesource.com/kernel/common/+/refs/heads/android12-5.10-2022-12/security/selinux/ss/policydb.h#362

真的只有我这里出了问题吗

**Comment by sekaiacg** [comment]
android12-5.10-2022-11的时候还没有加入(5.10.136)
https://android.googlesource.com/kernel/common/+/refs/heads/android12-5.10-2022-11/security/selinux/ss/policydb.h#373

android12-5.10-2022-12加入(5.10.149)
https://android.googlesource.com/kernel/common/+/refs/heads/android12-5.10-2022-12/security/selinux/ss/policydb.h#362

真的只有我这里出了问题吗

**Comment by tiann** [comment]
我明天刷这个版本试试

**Comment by sekaiacg** [comment]
> 我明天刷这个版本试试

我在`apply_kernelsu_rules`执行后加入一段代码，手动给len加16
```
[    1.837109] KernelSU: skkk: start apply_kernelsu_rules
[    1.837110] KernelSU: skkk: db->len=1597212
[    1.844943] KernelSU: skkk: end apply_kernelsu_rules
[    1.844944] KernelSU: skkk: db->len=2041758
[    1.844946] KernelSU: skkk: added db->len=2041774
```
magiskpolicy 可以正常应用规则。同时文件大小也是 **2041774**
这说明，比 2041782 小也不会出错。
```
cmi:/ # ls -al /sys/fs/selinux/policy
-r--r--r-- 1 root root 2041774 1970-01-01 08:00 /sys/fs/selinux/policy
cmi:/ # cat /sys/fs/selinux/policy > /cache/p
cmi:/ # ls -al /sys/fs/selinux/policy                                                                
-r--r--r-- 1 root root 2041782 1970-01-01 08:00 /sys/fs/selinux/policy
```
在cat后文件大小为 **2041782**
玄学

**Comment by tiann** [comment]
写入或读取过程中可能会 trim，只要工作正常就没问题了

**Comment by sekaiacg** [comment]
> 写入或读取过程中可能会 trim，只要工作正常就没问题了

好的，剩下的就交给大佬了

**Comment by tiann** [comment]
咱们现在纠结的问题是什么来着？我刷到了 5.10.149 并且 policydb.h 的确改了，测试的 magiskpolicy 能正常工作？

**Comment by sekaiacg** [comment]
> 咱们现在纠结的问题是什么来着？我刷到了 5.10.149 并且 policydb.h 的确改了，测试的 magiskpolicy 能正常工作？

https://github.com/tiann/KernelSU/issues/227#issuecomment-1429689863

根据这个，我这应该是卡上了bug....

**Comment by tiann** [comment]
你用现在 main 分支的代码，magiskpolicy 还是会报错？

**Comment by sekaiacg** [comment]
> 你用现在 main 分支的代码，magiskpolicy 还是会报错？ 我用 5.10.149 如果回退到原始代码，是会报错的；但最新的代码已经不会了，虽然 size 对不上。

……新的提交改了len，所以我这里也不会报错，都正常了
原来不是我卡了bug，这就好
那这个问题算解决了吧
