### ISSUE TITLE
Audio modules and web browsers

### ISSUE THREAD

**Issue by dranivil** [tiann/KernelSU#2276]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

When I install an audio module like viper4Android or Audio modification Library, chronium based web browsers like kiwi browser or Vivaldi stop working.They lose access to the internet and the tabs are not displayed. 

### To Reproduce

1- install audio module
2- open browser

### Expected behavior

Errors in browsers

### Logs

[KernelSU_bugreport_2024-12-08_23_06.tar.gz](https://github.com/user-attachments/files/18054162/KernelSU_bugreport_2024-12-08_23_06.tar.gz)

### Device info

- Device: xiaomi 13
- OS Version: Xiaomi eu
- KernelSU Version: 11986
- Kernel Version: 5.15.123-android13

**Comment by backslashxx** [comment]
viper needs to be mounted for most things.
so you either have to modify its post-fs-data to do a global mount OR
you disable umount modules by default on KernelSU

**Comment by dranivil** [comment]
> viper needs to be mounted for most things. so you either have to modify its post-fs-data to do a global mount OR you disable umount modules by default on KernelSU

Works! Thanks

**Comment by dranivil** [comment]
Solved

**Comment by backslashxx** [comment]
yeah close this issue then

**Comment by dranivil** [comment]
Solved
