### ISSUE TITLE
Patching of Samsung Galaxy S22 latest firmware results in bootloop

### ISSUE THREAD

**Issue by iacchi** [tiann/KernelSU#2291]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

(previosuly I used Magisk, this is my first attempt with kernelSU)

As the title says, I get a bootloop when I try to install kernelSU on my Galaxy S22. Here are the steps I followed:

### To Reproduce

1. I did a fresh install of the latest firmware for my Galaxy S22 (S901BXXUDEXK5), installed the kernelSU app without logging in on Google or Samsung account, the app said "Not installed" (so I assume the phone is compatible).
2. I extracted the boot.img file from the stock firmware, loaded it on the phone, opened the kernelSU app and patched the file. I copied the patched .img file back to my pc
3. I untar'd the AP file of the firmware, deleted the original boot.img.lz4 file, replaced it with the patched one, renamed to boot.img, tar'd the AP file again
4. Opened Odin, and flashed the whole firmware fresh again (using CSC file to erase data, not HOME_CSC)

### Expected behavior

Once the firmware flash finishes, the phone goes into a bootloop. In step 3, I also tried to replace the patched boot.img file with one downloaded from your github (specifically,  android12-5.10.218_2024-08-boot.img.gz) but after flashing it also leads to a bootloop. Notice that the kernel of this firmware version is 5.10.223-android12-9-29544049-abS901BXXUDEXK5 and I can't find an android12-5.10.223 in your list of downloadable files.

Am I doing something wrong, or is there something wrong/some incompatibility between kernelSU and my phone. I know of people who managed to install kernelSU on a Galaxy S23 (using one of your kernel images) so I want to say it should work. Is there a way you could provide an android12-5.10.223 kernel image for me to try? Unfortunately I cannot downgrade the firmware due to Samsung shenanigans.

### Device info

- Device: Samsung Galaxy S22
- OS Version: Android 14, firmware version S901BXXUDEXK5
- KernelSU Version: 1.0.2
- Kernel Version: 5.10.223-android12-9-29544049-abS901BXXUDEXK5

**Comment by IgorEisberg** [comment]
Could be related or not, but there's something wrong with the builds released with 1.0.2.
In my case I use AnyKernel3-android12-5.10.209_2024-05.zip flashed via TWRP.
Randomly or when trying to boot to TWRP again, device gets stuck in a bootloop (no ADB at that stage).
Using the same exact version from the 1.0.1 release everything works fine.

**Comment by iacchi** [comment]
I kind of gave up and used Magisk Alpha, which my stupid banking app doesn't recognise for the moment.

**Comment by tiann** [comment]
Samsung's RKP and RDP prohibit load modules in the kernel; you can only use the GKI mode.

**Comment by marcocancarini** [comment]
I'm sorry to reopen this issue. Disabling encryption on Samsung phone and patching vbmeta ([with this for example)](https://xdaforums.com/t/sm-s911b-0-one-ui-6-1-userdata_aio-odin-flashable-to-remove-encryption-make-rom-rw-install-twrp-root-use-on-stock-firmware-unlocked-bootloaders.4610067/) allows me to flash a patched stock kernel?
I tried patching stock kernel (the image boot.img and also iniy_boot.img) with the app kernelsu and flashing it but I got a hash error between the kernel and the vbmeta partition or something 
![IMG_20250101_112905_981](https://github.com/user-attachments/assets/3c7097d3-7050-4223-9ece-ea18ac0df21c)

**Comment by BasedJellyfish11** [comment]
Adding more detailed context since this issue is up high on google search results and the GKI readme leads to a bootloop.

I was able to patch my S22 (SM-S901B) on latest firmware (EUX build `S901BXXUDFYD9` released on 04/28/2025) by following GKI method. 

- Flash the build normally with Odin first. I wanted to delete my data on the update so I flashed CSC over HOME_CSC - not sure if HOME_CSC works at all
    - Phone will boot normally into the new firmware
- Flash uncompressed boot.img from the releases section of the repo. You will need to rename it to boot.img and add it to a tar archive for Odin to pick it up.
    - At this point turning on your phone will bootloop
- Flash an empty vbimage. You can get one following https://wiki.postmarketos.org/wiki/Android_Verified_Boot_(AVB)#Disabling_verified_boot with avbtool. Once you have it, rename to vbimage and add to a tar, just like the boot.img
    - This should let you boot normally

Note that upon boot I was forced to login to a wifi network so my phone could report modifications to google / samsung.

**Comment by sha3rawi33** [comment]
> flash vbmeta_dsiable.tar

tried this but still no luck with patched boot image to boot successfully; only stuck on Samsung logo with knox warning
