### ISSUE TITLE
Reset PC After Click KernelSU

### ISSUE THREAD

**Issue by CapitanArdeshir** [tiann/KernelSU#2326]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

I Download kernelsu 1.0.2 and  install
When click kernelsu icon for opened app
My Phone Restart
How Fix That 

### Device info

Samsung Note 9
Android 13
KernelSU V 1.0.2

### Additional context

I Download kernelsu 1.0.2 and  install
When click kernelsu icon for opened app
My Phone Restart
How Fix That

**Comment by rsuntk** [comment]
Probably your Kernel still have `CONFIG_UH` enabled

**Comment by tiann** [comment]
#1705
