### ISSUE TITLE
vendor overlay breaks stock vendor mount

### ISSUE THREAD

**Issue by natsumerinchan** [tiann/KernelSU#233]
**Describe the bug**
I get stuck on the first screen when I first start up after installed this module.

After successfully entering the system, the module has been disabled.

**To Reproduce**
1. Flash this module [门禁卡.zip](https://github.com/tiann/KernelSU/files/10715416/default.zip)
2. Reboot

**Expected behavior**
This module is created by [cardemulator](https://play.google.com/store/apps/details?id=com.yuanwofei.cardemulator.pro), allows the app to systemless modify /vendor/etc/libnfc-nxp.conf  for the purpose of emulating nfc cards.

**Screenshots**
![After the second time reboot](https://user-images.githubusercontent.com/64072399/218296973-25c19668-fdc4-4612-a1fb-cbdb939e7bbd.png)

**Smartphone (please complete the following information):**
 - Device: [Oneplus 9RT]
 - OS: [PixelOS]
 - Version [33]

**Additional context**
[KernelSU_bugreport_2023-02-12_14_16.tar.gz](https://github.com/tiann/KernelSU/files/10715431/KernelSU_bugreport_2023-02-12_14_16.tar.gz)

**Comment by tiann** [comment]
please execute: `ls -al /system` and give me the output

**Comment by natsumerinchan** [comment]
![截图 2023-02-12 14-48-29](https://user-images.githubusercontent.com/64072399/218297235-a74eecc9-0d26-4660-b7f3-d18402f32394.png)

**Comment by tiann** [comment]
After install the nfc module, execute: `chcon u:object_r:vendor_configs_file:s0 /data/adb/ksu/modules/NFC_Card_Emulator/vendor/etc/libnfc-nxp.conf` and have a try

**Comment by natsumerinchan** [comment]
I flashed the module and no system folder appeared, are they in modules_update.img?I haven't rebooted yet.
![Screenshot_20230212-152859_质感文件](https://user-images.githubusercontent.com/64072399/218298632-54a58846-00b7-47c9-bee6-e5a2c675dabd.png)

So I try to add customize.sh and post-fs-data.sh to set selinux context but it is still error.

[nfc.zip](https://github.com/tiann/KernelSU/files/10715550/nfc.zip)

**Comment by tiann** [comment]
What happened if you rename the `libnfc-nxp.conf` to someone else?

**Comment by natsumerinchan** [comment]
I renamed it to celica.conf and it is still error

**Comment by tiann** [comment]
only an empty /vendor/etc would cause error?

**Comment by natsumerinchan** [comment]
yes

**Comment by tiann** [comment]
Maybe add `chcon u:object_r:vendor_configs_file:s0 /vendor/etc` ?

**Comment by natsumerinchan** [comment]
Failed.
[nfc.zip](https://github.com/tiann/KernelSU/files/10715604/nfc.zip)

**Comment by tiann** [comment]
please execute: `ls -alZ /vendor` and `ls -alZ /vendor/etc`

**Comment by natsumerinchan** [comment]
[vendor.txt](https://github.com/tiann/KernelSU/files/10715609/vendor.txt)
[vendor-etc.txt](https://github.com/tiann/KernelSU/files/10715610/vendor-etc.txt)

**Comment by tiann** [comment]
And what is `mount -t overlay`?

**Comment by natsumerinchan** [comment]
```
[celica@arch ~]$ adb shell
martini:/ $ su
martini:/ # mount -t overlay
overlay on /system type overlay (ro,seclabel,relatime,lowerdir=/data/adb/ksu/modules/lhroot/system:/data/adb/ksu/modules/xmlpak/system:/data/adb/ksu/modules/busybox-ndk/system:/data/adb/ksu/modules/zygisksu/system:/data/adb/ksu/modules/lxgwttftemplatec/system:/data/adb/ksu/modules/zipsigner/system:/data/adb/ksu/modules/magic-flash/system:/data/adb/ksu/modules/go-touch-mapper/system:/data/adb/ksu/modules/com.aurora.services/system:/data/adb/ksu/modules/nano-ndk/system:/system)
overlay on /product type overlay (ro,seclabel,relatime,lowerdir=/data/adb/ksu/modules/lxgwttftemplatec/product:/product)
martini:/ #
```

**Comment by tiann** [comment]
When you install the nfc module(dont reboot), upload the /data/adb/ksu/modules_update.img

**Comment by natsumerinchan** [comment]
https://drive.google.com/file/d/1xyKIO2k7bWatyZnkSw96dVvnwTVf76w4/view?usp=share_link

**Comment by tiann** [comment]
Install the module and before reboot, replace modules_update.img with this one: https://taichi.lanzoum.com/itpkU0nccefc
(unzip it first)

**Comment by natsumerinchan** [comment]
Still error😂

**Comment by tiann** [comment]
What if you put a `setenforce 0` to post-fs-data.sh?

**Comment by natsumerinchan** [comment]
Still the same, maybe the problem is not on selinux?

**Comment by tiann** [comment]
please try this: https://taichi.lanzoum.com/ij6GE0nchlwb

**Comment by natsumerinchan** [comment]
It is booting success now!But the flie have not overlayed to the real /vendor/etc
![Screenshot_20230212-171807_质感文件](https://user-images.githubusercontent.com/64072399/218302791-416e396c-cc58-48bb-9f32-1e459edd87cf.png)
![Screenshot_20230212-171831_质感文件](https://user-images.githubusercontent.com/64072399/218302794-1f05d4a8-fff9-421f-990c-3cf3d7e6c792.png)

**Comment by tiann** [comment]
What is `mount -t overlay`?

**Comment by natsumerinchan** [comment]
```
[celica@arch ~]$ adb shell
martini:/ $ su
martini:/ # mount -t overlay
overlay on /system type overlay (ro,seclabel,relatime,lowerdir=/data/adb/ksu/modules/lhroot/system:/data/adb/ksu/modules/xmlpak/system:/data/adb/ksu/modules/busybox-ndk/system:/data/adb/ksu/modules/zygisksu/system:/data/adb/ksu/modules/lxgwttftemplatec/system:/data/adb/ksu/modules/zipsigner/system:/data/adb/ksu/modules/magic-flash/system:/data/adb/ksu/modules/go-touch-mapper/system:/data/adb/ksu/modules/com.aurora.services/system:/data/adb/ksu/modules/nano-ndk/system:/system)
overlay on /product type overlay (ro,seclabel,relatime,lowerdir=/data/adb/ksu/modules/lxgwttftemplatec/product:/product)
martini:/ #                                                                                                                                                                                                                                   martini:/ #
```

**Comment by tiann** [comment]
vendor overlay is gone? `ls -alZ /data/adb/ksu/modules/NFC_Card_Emulator`?

**Comment by natsumerinchan** [comment]
![截图 2023-02-12 17-51-35](https://user-images.githubusercontent.com/64072399/218304135-b42d9b87-2417-4c17-894b-4aafc52506a6.png)

**Comment by tiann** [comment]
Please send me the log in Settings - Send log

**Comment by natsumerinchan** [comment]
[KernelSU_bugreport_2023-02-12_18_15.tar.gz](https://github.com/tiann/KernelSU/files/10715819/KernelSU_bugreport_2023-02-12_18_15.tar.gz)

**Comment by tiann** [comment]
[Log Catcher-v22.5(27).zip](https://github.com/tiann/KernelSU/files/10715828/Log.Catcher-v22.5.27.zip)

The logcat buffer is gone, please use this module get logcat. 

the log will be `/cache/bootlog` or `/data/local/bootlog`

**Comment by natsumerinchan** [comment]
[boot-2023-02-12-18-22-37.log](https://github.com/tiann/KernelSU/files/10715839/boot-2023-02-12-18-22-37.log)

**Comment by tiann** [comment]
please try this release: https://github.com/tiann/KernelSU/actions/runs/4155889057

**Comment by natsumerinchan** [comment]
Bootloop now，how to enable safety mode

**Comment by tiann** [comment]
Your device would bootloop with only one `/system/vendor` folder?

**Comment by tiann** [comment]
> Bootloop now，how to enable safety mode

I don't have Oneplus device, but for xiaomi devices, you can reboot to recovery, and there is a option "reboot with safe mode"

**Comment by natsumerinchan** [comment]
I will try to flash the offical boot and use magisk to delete nfc module

**Comment by natsumerinchan** [comment]
Maybe kernelsu should add a feature that automatically disables all modules after 3 bootloops?

**Comment by natsumerinchan** [comment]
Start up now

**Comment by natsumerinchan** [comment]
Only install nfc and log catcher

![Screenshot_20230212-191210_KernelSU](https://user-images.githubusercontent.com/64072399/218307588-634e9fff-f09b-4961-b6e3-6abf40f97bc3.png)
[bootlog.tar.gz](https://github.com/tiann/KernelSU/files/10715901/bootlog.tar.gz)
[oldlogbak.tar.gz](https://github.com/tiann/KernelSU/files/10715902/oldlogbak.tar.gz)
[boot-2023-02-12-19-11-33.log](https://github.com/tiann/KernelSU/files/10715900/boot-2023-02-12-19-11-33.log)

**Comment by tiann** [comment]
install the module and upload modules_update.img

**Comment by natsumerinchan** [comment]
[modules_update.img.tar.gz](https://github.com/tiann/KernelSU/files/10715929/modules_update.img.tar.gz)

**Comment by tiann** [comment]
How about this one? 
[modules_update.img.zip](https://github.com/tiann/KernelSU/files/10716062/modules_update.img.zip)

**Comment by natsumerinchan** [comment]
Boot failed.
[bootlog.tar.gz](https://github.com/tiann/KernelSU/files/10716125/bootlog.tar.gz)
[oldlogbak.tar.gz](https://github.com/tiann/KernelSU/files/10716126/oldlogbak.tar.gz)
[boot-2023-02-12-21-15-52.log](https://github.com/tiann/KernelSU/files/10716124/boot-2023-02-12-21-15-52.log)

**Comment by tiann** [comment]
I have no idea why simply overlay vendor would cause bootloop, i test Redmi and pixel, it seems working.

When bootloop, is the system_server or adbd launched?

**Comment by natsumerinchan** [comment]
Vibrate when booting, can not connect to adbd.

**Comment by natsumerinchan** [comment]
I am checking the kernel config [CONFIG_OVERLAY_FS=y](https://github.com/bheatleyyy/kernel_oplus_sm8350/blob/dd23589bd48c42ef0f05ddc4cccc174b22a03a2c/arch/arm64/configs/vendor/lahaina-qgki_defconfig#L5950)

**Comment by tiann** [comment]
> I think KernelSU didn't handle this. ![Screenshot_20230214-181938_Trình chạy Pixel](https://user-images.githubusercontent.com/84650617/218723338-ae8f6827-ab80-4235-a181-0927dbf40b1d.png)

I think so

**Comment by natsumerinchan** [comment]
![截图 2023-02-14 19-59-43](https://user-images.githubusercontent.com/64072399/218732171-82ad1c0a-9cb5-45c7-a152-322b21c7d8ee.png)

**Comment by tiann** [comment]
[KernelSU_v0.3.8-28-g47bcccd-release.apk.zip](https://github.com/tiann/KernelSU/files/10793165/KernelSU_v0.3.8-28-g47bcccd-release.apk.zip)
@natsumerinchan Could you test this package?

**Comment by natsumerinchan** [comment]
> [KernelSU_v0.3.8-28-g47bcccd-release.apk.zip](https://github.com/tiann/KernelSU/files/10793165/KernelSU_v0.3.8-28-g47bcccd-release.apk.zip) @natsumerinchan Could you test this package?


Nice!!!It is working now:

![Screenshot_20230221-201346_质感文件](https://user-images.githubusercontent.com/64072399/220342867-f388a08c-14a3-4536-bd02-b3686c315b33.png)
![Screenshot_20230221-201448_质感文件](https://user-images.githubusercontent.com/64072399/220342879-981541cb-5aab-4877-b489-6751b3f4040c.png)
