### ISSUE TITLE
[Add Device]: 

### ISSUE THREAD

**Issue by z1298808165** [tiann/KernelSU#235]
### Repository URL

https://github.com/z1298808165/kernel_xiaomi_star

### Device

GKI 1.0

### Code of Conduct

- [X] I'm the maintainer of this repository

**Comment by tiann** [comment]
The repo is 404

**Comment by TheVoyager0777** [comment]
> 

Did you test it before?

**Comment by z1298808165** [comment]
> > 
> 
> Did you test it before?

Sorry, this is a wrong operation

**Comment by tiann** [comment]
reverted: https://github.com/tiann/KernelSU/commit/a5dbbf4881178e817bd5b22876f9588a37c3c909
