### ISSUE TITLE
Android12以下应用程序的UI颜色错误

### ISSUE THREAD

**Issue by Jesse205** [tiann/KernelSU#237]
![Screenshot_20230213_003809.jpg](https://user-images.githubusercontent.com/51242302/218324299-b1e84ef1-5921-41a9-8432-2a444bf2d847.jpg)

**Comment by tiann** [comment]
这个颜色预期应该是什么？请清晰地描述你的问题。

**Comment by Jesse205** [comment]
> 这个颜色预期应该是什么？请清晰地描述你的问题。

这个应该为黄色，与整体的颜色保持一致，但是现在呈现出来的却是新工程默认的紫色
![Screenshot_20230213_125815](https://user-images.githubusercontent.com/51242302/218374828-da55e173-b3d5-4e37-b08d-98d1d5c3769a.jpg)

![Screenshot_20230213_125812_com coolapk market](https://user-images.githubusercontent.com/51242302/218374834-745fd04c-500e-4955-bc0d-b07e0a355c85.jpg)

**Comment by Jesse205** [comment]
![Screenshot_20230213_125747](https://user-images.githubusercontent.com/51242302/218374996-fa7b7b3d-5b11-453d-84d8-036748b60649.jpg)
