### ISSUE TITLE
如何手动删除kernelSU模块

### ISSUE THREAD

**Issue by h88782481** [tiann/KernelSU#242]
如题，昨天新增的自动救砖我发现没有效果，导致我现在不能开机，刷回原boot可以开机，但是只要在刷入kernelSU因为有模块就会导致无法开机

**Comment by tiann** [comment]
自动救砖对 GKI 设备自动生效，非 GKI 要集成代码。
两个方法，其一进 twrp 删 /data/adb/ksu
其二想办法启动安卓自带的安全模式。

**Comment by h88782481** [comment]
> 自动救砖对 GKI 设备自动生效，非 GKI 要集成代码。 两个方法，其一进 twrp 删 /data/adb/ksu 其二想办法启动安卓自带的安全模式。

好的，感谢
