### ISSUE TITLE
Version is shown as 12.

### ISSUE THREAD

**Issue by Katsuyuki-Karasawa** [tiann/KernelSU#247]
**Describe the bug**
Version is shown as 12.

**To Reproduce**
1. flash this [image](https://github.com/tiann/KernelSU/releases/download/v0.3.8/ksu-10614-Image-android13-5.10.107_2022-05-boot.img.gz)
2. wipe data(loop)
3. boot and initial setting
![Screenshot_20230216-181532](https://user-images.githubusercontent.com/70247011/219326542-f801a599-1456-4b35-93f6-6e1a6ed4b618.png)

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Pixel 6a(bluejay)
 - OS: TQ1A.230205.002(A13)
 - Version: 5.10.107

**Comment by tiann** [comment]
Please ensure the image is flashed successfully. if you already have KernelSU installed, you can use KernelFlasher to flash AK3 package, follow this instruction: https://kernelsu.org/guide/installation.html

**Comment by Katsuyuki-Karasawa** [comment]
@tiann 
KernelFlasher does not start because there is no magiskboot
FKM will Abort
I can't confirm that there is anything wrong with flash.
The basic functions are working without any problems.

**Comment by Katsuyuki-Karasawa** [comment]
Flash the same way again and you will only get the same result.

**Comment by tiann** [comment]
[KernelFlasher.apk.zip](https://github.com/tiann/KernelSU/files/10754997/KernelFlasher.apk.zip)

Try this one, you can also build it yourself: https://github.com/capntrips/KernelFlasher/commit/3715b6f966e1c183ecb4fd0499174deb61d80bec

**Comment by tiann** [comment]
The installation instruction has said " you cannot flash boot image of CI to pixel directly. please read it carefully.
