### ISSUE TITLE
S22+ bootloop

### ISSUE THREAD

**Issue by BIGFWyyy** [tiann/KernelSU#251]
S22+的内核为5.10.66，当我下载对应的boot.img文件并使用Odin将下载的boot作为AP项刷入手机后，会出现bootloop的情况

**Comment by tiann** [comment]
no log no fix. And you should read the installation instruction carefully.

**Comment by BIGFWyyy** [comment]
内核版本为5.10.66-android12-9-25281636
我下载的文件为ksu-10614-Image-android12-5.10.66_2021-11-boot.img.gz
因为是三星设备的缘故，我用Odin将解压后得到的boot.img作为AP选项刷入手机，并尝试重启。
此外我也尝试过使用magiskboot将原厂boot.img中的kernel文件替换为 AnyKernel3中的image文件，之后再通过Odin刷入，结果也是一样的
我是哪个步骤出现问题了吗？
