### ISSUE TITLE
Sound mods modules

### ISSUE THREAD

**Issue by lsander** [tiann/KernelSU#253]
Installing sound mods modules like Sony audio sound enchantment or Xtreme music module disables network, wifi and fingerprint and doesn't work at all. Modules working fine on magisk. If modules need some changes then will close. If kernelsu then can provide log or something. Most modules working so i don't think it is a device problem.
Poco X3 pro. A13, paranoid android with non gki unofficial build of kernelsu.

**Comment by tiann** [comment]
Setting - Send log and open an issue again.

**Comment by dranivil** [comment]
I have the same problem
