### ISSUE TITLE
KernelSU not working on Samsung S22

### ISSUE THREAD

**Issue by NGC1952-2** [tiann/KernelSU#261]
[last_kmsg.txt](https://github.com/tiann/KernelSU/files/10783049/last_kmsg.txt)
-- Original  --
**Describe the bug**
KernelSU Does Not work on Samsung S22

**To Reproduce**
1.Try the Normal Method (didnt work)
2.Find out that the Ramdisk is lz4-Legacy
3.Try the other way
4. Extract boot.img from Stock Firmware (AP-BlahBlah/Boot.img.lz4 extracted by 7zip-zstd)
5. Patch with MagiskInit or AIK 
6. Flash
7. Get Rebooted
8. Re-Flash
9. Get Rebooted
10. Give Up

**Expected behavior**
Boot and  get root access

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Galaxy S22 (S901N,r0q)
 - OS: Android 13
 - Version android12-9, 5.10.81  (used the AnyKernel 5.10.81)

--- 由谷歌翻译翻译 ----

**描述错误**
KernelSU 不适用于三星 S22

**重现**
重现该行为的步骤：
1.尝试正常方法（没用）
2.查看Ramdisk是lz4-Legacy
3.尝试其他方式
4. 从 Stock Firmware 中提取 boot.img（AP-BlahBlah/Boot.img.lz4 由 7zip-zstd 提取）
5. 用 MagiskInit 或 AIK 打补丁
6.闪光灯
7. 重新启动
8. 重新闪现
9. 重新启动
10.放弃

**预期行为**
启动并获得root访问权限

**截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**智能手机（请填写以下信息）：**
 - 设备：Galaxy S22 (S901N,r0q)
 - 操作系统：Android 13
 - 版本 android12-9、5.10.81（使用 AnyKernel 5.10.81

**Comment by tiann** [comment]
```
[    0.580901] [7:           init:    1] qrtr: Unknown symbol sock_alloc_send_pskb (err -2)
[    0.580907] [7:           init:    1] qrtr: Unknown symbol skb_copy_datagram_from_iter (err -2)
[    0.580931] [7:           init:    1] init: Failed to insmod '/lib/modules/qrtr.ko' with args '': No such file or directory
[    0.580935] [7:           init:    1] init: LoadWithAliases was unable to load qrtr
[    0.581188] [7:           init:    1] init: Failed to load kernel modules
[    0.581342] [7:           init:    1] init: InitFatalReboot: signal 6
```

Samsung's kernel doesn't obey the GKI, init crashed here: http://aospxref.com/android-12.0.0_r3/xref/system/core/init/first_stage_init.cpp#293

Maybe you can try delete `/lib/modules/qrtr.ko` in ramdisk.

**Comment by tiann** [comment]
samsung adds its private symbol to abi list, you should add this file `https://github.com/mohammad92/android_kernel_samsung_sm8450/blob/fe971903450c4d13089e93ec2848e2866f157e12/android/abi_gki_aarch64_galaxy_grey` to kernel source, and modify here: https://github.com/mohammad92/android_kernel_samsung_sm8450/blob/fe971903450c4d13089e93ec2848e2866f157e12/build.config.gki.aarch64#L32
