### ISSUE TITLE
S22+: su can't work

### ISSUE THREAD

**Issue by BIGFWyyy** [tiann/KernelSU#263]
First the phone reboot when start the app, after disable CONFIG_RKP, CONFIG_KDP and CONFIG_UH, the app could run successfully.
![Screenshot_20230221_145308_KernelSU](https://user-images.githubusercontent.com/91934378/220269576-2d2638bc-3858-4412-8c49-e255a2c39aaf.jpg)
when i connect the PC and try to get su, something happen like this 
![image](https://user-images.githubusercontent.com/91934378/220269407-3ed7c9db-01c6-4a48-bf87-a8ddce71777e.png)
besides the moudle can't work either
![Screenshot_20230221_145417_KernelSU](https://user-images.githubusercontent.com/91934378/220269782-0ee9fa96-d416-4841-9486-dbd6378f35a6.jpg)
here is the log:
[KernelSU_bugreport_2023-02-21_14_56.tar.gz](https://github.com/tiann/KernelSU/files/10790525/KernelSU_bugreport_2023-02-21_14_56.tar.gz)

**Comment by BIGFWyyy** [comment]
besides you can find the Kernel source at https://opensource.samsung.com/uploadSearch by search S906BXXU2BVJA 
i didn't edit the code except the three config above

**Comment by tiann** [comment]
the log is 0 size

**Comment by tiann** [comment]
You should disable these by delete them( don't set it to `n` or `m`):

```
CONFIG_UH=y
CONFIG_RKP=y
# CONFIG_RKP_FIMC_CHECK is not set
CONFIG_KDP=y
CONFIG_KDP_CRED=y
CONFIG_KDP_NS=y
CONFIG_RKP_TEST=y
CONFIG_KDP_TEST=y
```

**Comment by BIGFWyyy** [comment]
how about this log[KernelSU_bugreport_2023-02-21_14_56.tar.gz](https://github.com/tiann/KernelSU/files/10790670/KernelSU_bugreport_2023-02-21_14_56.tar.gz)
i'll try to delete them one more time

**Comment by BIGFWyyy** [comment]
after delete these config everything works well right now, thanks for your help
have a good day

**Comment by amantu-qbit** [comment]
> You should disable these by delete them( don't set it to `n` or `m`):
> 
> ```
> CONFIG_UH=y
> CONFIG_RKP=y
> # CONFIG_RKP_FIMC_CHECK is not set
> CONFIG_KDP=y
> CONFIG_KDP_CRED=y
> CONFIG_KDP_NS=y
> CONFIG_RKP_TEST=y
> CONFIG_KDP_TEST=y
> ```

Can you still do it? andd can you tell me how to do it?
