### ISSUE TITLE
Fails to compile 

### ISSUE THREAD

**Issue by kondors1995** [tiann/KernelSU#277]
**Describe the bug**
Fails to compile with clang 17 didn't test with older clang 

**To Reproduce**
  CC      drivers/media/platform/msm/camera/cam_fd/fd_hw_mgr/cam_fd_hw_mgr.o
../drivers/kernelsu/selinux/sepolicy.c:734:43: error: no member named 'total_nr_elements' in 'struct ebitmap'
        for (j = 0; j < db->type_attr_map_array->total_nr_elements; j++) {
                        ~~~~~~~~~~~~~~~~~~~~~~~  ^
../drivers/kernelsu/selinux/sepolicy.c:741:46: error: member reference base type 'struct type_datum *' is not a structure or union
        for (j = 0; j < db->type_val_to_struct_array->total_nr_elements; j++) {
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^ ~~~~~~~~~~~~~~~~~
../drivers/kernelsu/selinux/sepolicy.c:758:9: error: incompatible pointer types assigning to 'struct flex_array *' from 'struct ebitmap *' [-Werror,-Wincompatible-pointer-types]
        old_fa = db->type_attr_map_array;
               ^ ~~~~~~~~~~~~~~~~~~~~~~~
../drivers/kernelsu/selinux/sepolicy.c:759:26: error: incompatible pointer types assigning to 'struct ebitmap *' from 'struct flex_array *' [-Werror,-Wincompatible-pointer-types]
        db->type_attr_map_array = new_type_attr_map_array;
                                ^ ~~~~~~~~~~~~~~~~~~~~~~~
../drivers/kernelsu/selinux/sepolicy.c:768:9: error: incompatible pointer types assigning to 'struct flex_array *' from 'struct type_datum **' [-Werror,-Wincompatible-pointer-types]
        old_fa = db->type_val_to_struct_array;
               ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../drivers/kernelsu/selinux/sepolicy.c:769:31: error: incompatible pointer types assigning to 'struct type_datum **' from 'struct flex_array *' [-Werror,-Wincompatible-pointer-types]
        db->type_val_to_struct_array = new_type_val_to_struct;
                                     ^ ~~~~~~~~~~~~~~~~~~~~~~
../drivers/kernelsu/selinux/sepolicy.c:776:9: error: incompatible pointer types assigning to 'struct flex_array *' from 'char **' [-Werror,-Wincompatible-pointer-types]
        old_fa = db->sym_val_to_name[SYM_TYPES];
               ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../drivers/kernelsu/selinux/sepolicy.c:777:33: error: incompatible pointer types assigning to 'char **' from 'struct flex_array *' [-Werror,-Wincompatible-pointer-types]
        db->sym_val_to_name[SYM_TYPES] = new_val_to_name_types;
                                       ^ ~~~~~~~~~~~~~~~~~~~~~
8 errors generated.
make[4]: *** [../scripts/Makefile.build:355: drivers/kernelsu/selinux/sepolicy.o] Error 1

**Smartphone (please complete the following information):**
- K20 PRO
[ - OS: [e.g. iOS8.1]
 - Version [e.g. 22]](https://github.com/SOVIET-ANDROID/kernel_xiaomi_raphael/tree/dev/KSU)

**Comment by tiann** [comment]
Your code seems cherry-picked newer kernel's commit, so you should read the code and understand it, then modify it yourself. KernelSU official won't help to compile the kernel.

**Comment by AkariOficial** [comment]
> **Describe the bug** Fails to compile with clang 17 didn't test with older clang
> 
> **To Reproduce** Steps to reproduce the behavior: CC drivers/media/platform/msm/camera/cam_fd/fd_hw_mgr/cam_fd_hw_mgr.o ../drivers/kernelsu/selinux/sepolicy.c:734:43: error: no member named 'total_nr_elements' in 'struct ebitmap' for (j = 0; j < db->type_attr_map_array->total_nr_elements; j++) { ~~~~~~~~~~~~~~~~~~~~~~~ ^ ../drivers/kernelsu/selinux/sepolicy.c:741:46: error: member reference base type 'struct type_datum *' is not a structure or union for (j = 0; j < db->type_val_to_struct_array->total_nr_elements; j++) { ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^ ~~~~~~~~~~~~~~~~~ ../drivers/kernelsu/selinux/sepolicy.c:758:9: error: incompatible pointer types assigning to 'struct flex_array *' from 'struct ebitmap *' [-Werror,-Wincompatible-pointer-types] old_fa = db->type_attr_map_array; ^ ~~~~~~~~~~~~~~~~~~~~~~~ ../drivers/kernelsu/selinux/sepolicy.c:759:26: error: incompatible pointer types assigning to 'struct ebitmap *' from 'struct flex_array *' [-Werror,-Wincompatible-pointer-types] db->type_attr_map_array = new_type_attr_map_array; ^ ~~~~~~~~~~~~~~~~~~~~~~~ ../drivers/kernelsu/selinux/sepolicy.c:768:9: error: incompatible pointer types assigning to 'struct flex_array *' from 'struct type_datum **' [-Werror,-Wincompatible-pointer-types] old_fa = db->type_val_to_struct_array; ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ../drivers/kernelsu/selinux/sepolicy.c:769:31: error: incompatible pointer types assigning to 'struct type_datum **' from 'struct flex_array *' [-Werror,-Wincompatible-pointer-types] db->type_val_to_struct_array = new_type_val_to_struct; ^ ~~~~~~~~~~~~~~~~~~~~~~ ../drivers/kernelsu/selinux/sepolicy.c:776:9: error: incompatible pointer types assigning to 'struct flex_array *' from 'char **' [-Werror,-Wincompatible-pointer-types] old_fa = db->sym_val_to_name[SYM_TYPES]; ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ../drivers/kernelsu/selinux/sepolicy.c:777:33: error: incompatible pointer types assigning to 'char **' from 'struct flex_array *' [-Werror,-Wincompatible-pointer-types] db->sym_val_to_name[SYM_TYPES] = new_val_to_name_types; ^ ~~~~~~~~~~~~~~~~~~~~~ 8 errors generated. make[4]: *** [../scripts/Makefile.build:355: drivers/kernelsu/selinux/sepolicy.o] Error 1
> 
> **Smartphone (please complete the following information):**
> 
> * K20 PRO
>   [ - OS: [e.g. iOS8.1]
> * Version [e.g. 22]](https://github.com/SOVIET-ANDROID/kernel_xiaomi_raphael/tree/dev/KSU)

managed to solve? mine gives the same errors. and I don't believe it's a kernel problem, but some incompatibility, I'm using kernel v4.14.x

**Comment by tiann** [comment]
https://github.com/SoDebug/kernel_xiaomi_raphael

**Comment by kondors1995** [comment]
> https://github.com/SoDebug/kernel_xiaomi_raphael

I dont see anything in this repot that would be regarding this selinux issue in KSU

**Comment by tiann** [comment]
Because he didn't cherry pick other version's commit, it should work out of box for 4.14 kernel. You should check your commit, we cannot recognize cherry pick so we cannot help it

**Comment by kondors1995** [comment]
I understand, i would appreciate some pointers since so far all points to KSU selinux code issue

**Comment by tiann** [comment]
I will check your souce later

**Comment by kondors1995** [comment]
Thank you

**Comment by AkariOficial** [comment]
> In your kernel, https://github.com/SOVIET-ANDROID/kernel_xiaomi_raphael/blob/7088630cde372392f46e62f9f03883dede3f9154/security/selinux/ss/policydb.h#L297 `type_attr_map_array` is `struct ebitmap*`, but in official 4.14 release, it is `struct flex_array*`. You can modify the version check in kernelsu: https://github.com/tiann/KernelSU/blob/main/kernel/selinux/sepolicy.c#L654 (there are maybe many other modifications like this) or revert your commit picked from higher linux version.

> which version of clang is recommended?

**Comment by AkariOficial** [comment]
> Thank you

did you manage to solve?

**Comment by kondors1995** [comment]
Yes i reverted selinux patch tiann mentioned

**Comment by AkariOficial** [comment]
> how? freshness to be asking so much, but I had the same problems as you. my kernel is also 4.14
