### ISSUE TITLE
打开clang_lto（thin_lto），不能使用

### ISSUE THREAD

**Issue by kodhh** [tiann/KernelSU#278]
在内核4.14+kprobe模式下，打开clang_lto（thin_lto）编译，不工作。关闭clang_lto，才能使用。

**Comment by tiann** [comment]
什么叫不工作？

**Comment by kodhh** [comment]
显示是工作中，但是root没有，还说内核不支持overlayfs。编译了好几次都不行，后来关了lto再试着编译一下，就正常了。

**Comment by tiann** [comment]
参考手动集成的方式。

**Comment by kodhh** [comment]
好像是开了clang lto就不能用kprobe，手动集成比kprobe好吗？

**Comment by Dreamail** [comment]
lto会更变符号名，所以请自行backport高版本的patch

**Comment by Dreamail** [comment]
https://lore.kernel.org/all/20211004162936.21961-1-ndesaulniers@google.com/
https://lore.kernel.org/all/20210408182843.1754385-8-samitolvanen@google.com/
