### ISSUE TITLE
selinux_state not been back ported to mainline 4.9.212+

### ISSUE THREAD

**Issue by rhjdvsgsgks** [tiann/KernelSU#280]
**Describe the bug**
#245 will use selinux_state after 4.9.212+ . but it only avaliable on android common kernel. and not on mainlane. it will cause issus when using mainline 4.14/4.9 kernel

**To Reproduce**
1. build ksu on top of https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/tag/?h=v4.14.274
2. get some error about selinux_state not found

**Expected behavior**
fallback to alternative method automatically

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: any device using mainline kernel
 - OS: not a matter
 - Version: kernel 4.14.274

**Additional context**
works fine if i turn on the fallback method manually. i suggest add a way to control this manually by ccflags

**Comment by tiann** [comment]
PRs welcome

**Comment by tiann** [comment]
Due to the severe fragmentation of older kernel versions, any modifications made will not be able to satisfy everyone. However, if you have a better solution, welcome to make a PR : )
