### ISSUE TITLE
Please add support for android12-5.10.117

### ISSUE THREAD

**Issue by brijagstu7** [tiann/KernelSU#281]
OnePlus 11r (or Ace 2) has an android12-5.10.117 kernel number

**Comment by tiann** [comment]
you can try 5.10.149, it is same KMI

**Comment by natsumerinchan** [comment]
Copy from website

KMI
Kernel Module Interface (KMI), kernel versions with the same KMI are compatible This is what "genernal" means in GKI; conversely, if the KMI is different, then these kernels are not compatible with each other, and brushing in a kernel image with a different KMI than your device may cause a bootloop.

Specifically, for GKI devices, the kernel version format should be as follows:

```
KernelRelease :=
Version.PatchLevel.SubLevel-AndroidRelease-KmiGeneration-suffix
w      .x         .y       -zzz           -k            -something
```

`w.x-zzz-k` is the KMI version. For example, if a device kernel version is `5.10.101-android12-9-g30979850fc20`, then its KMI is `5.10-android12-9`; theoretically, it can boot up normally with other KMI kernels.


TIP

Note that the SubLevel in the kernel version is not part of the KMI! That means that `5.10.101-android12-9-g30979850fc20` has the same KMI as `5.10.137-android12-9-g30979850fc20`!

**Comment by natsumerinchan** [comment]
> you can try 5.10.149, it is same KMI

His KMI seems to be 5.10-android12-x, actually he should flash android12-5.10.136?

**Comment by brijagstu7** [comment]
> you can try 5.10.149, it is same KMI

What about 5.4.xx? There doesn't seem to be one.

**Comment by tiann** [comment]
Please read the instruction first.

**Comment by LeChenOS** [comment]
oneplus ace2 kernelsu 文件以及lsp
wwnq.lanzoub.com/b022jebod
密码:fizx
