### ISSUE TITLE
frida-service 启动失败, 每次启动frida-service手机便重启.

### ISSUE THREAD

**Issue by General110** [tiann/KernelSU#289]
Kernel: 5.15.41-android13-8-gf8258f375514
BRAND: Xiaomi
MODEL: 2211133C
PRODUCT: fuxi
MANUFACTURER: Xiaomi
SDK: 33
PREVIEW_SDK: 0
FINGERPRINT: Xiaomi/fuxi/fuxi:13/TKQ1.220905.001/V14.0.17.0.TMCCNXM:user/release-keys
DEVICE: fuxi
Manager: v0.4.0 (10672)
KernelRelease: 5.15.41-android13-8-gf8258f375514
KernelVersion: #1 SMP PREEMPT Tue Feb 21 20:19:51 UTC 2023
Mahcine: aarch64
Nodename: localhost
Sysname: Linux
KernelSU: 10663

  已经尝试多个frida版本!,SELinux 也尝试修改过宽容模式 ,结果一样手机重启

**Comment by tiann** [comment]
setting - sendlog

**Comment by General110** [comment]
> setting - sendlog
[https://wwpl.lanzoue.com/ia3ce0ozx8ta](url)
[https://wwpl.lanzoue.com/ipmpt0ozx8yf](url)

**Comment by General110** [comment]
> log

[https://github.com/General110/kernelSU-frida-log](url)

**Comment by tiann** [comment]
复现问题重启后，看下 `/sys/fs/pstore` 和 `/data/vendor/diag` 下是否有内容，如果有的话打包传上来看一下。

**Comment by General110** [comment]
> /data/vendor/diag

[/data/vendor/diag/md_history](https://github.com/General110/kernelSU-frida-log/blob/main/md_history)

**Comment by General110** [comment]
> > /data/vendor/diag
> 
> [/data/vendor/diag/md_history](https://github.com/General110/kernelSU-frida-log/blob/main/md_history)

没什么文件, 文件中好像也没什么内容.
发现一个奇怪的点 ,就是用adb shell 启动frida没什么事,还没开始注入一打开任何一个APP手机就重启!

**Comment by tiann** [comment]
frida 版本是多少？手机是软重启还是整个重启了（adb shell 断开了吗？

**Comment by General110** [comment]
> frida 版本是多少？手机是软重启还是整个重启了（adb shell 断开了吗？

adb shell 没断开,软重启

**Comment by General110** [comment]
> frida 版本是多少？手机是软重启还是整个重启了（adb shell 断开了吗？

最新的 16.0.10

**Comment by tiann** [comment]
软重启不是 KernelSU 的问题。你的错误日志如下：
```
03-02 09:49:03.377 20994 20994 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
03-02 09:49:03.377 20994 20994 F DEBUG   : Build fingerprint: 'Xiaomi/fuxi/fuxi:13/TKQ1.220905.001/V14.0.17.0.TMCCNXM:user/release-keys'
03-02 09:49:03.377 20994 20994 F DEBUG   : Revision: '0'
03-02 09:49:03.377 20994 20994 F DEBUG   : ABI: 'arm64'
03-02 09:49:03.377 20994 20994 F DEBUG   : Timestamp: 2023-03-02 09:49:02.264232667+0800
03-02 09:49:03.377 20994 20994 F DEBUG   : Process uptime: 55s
03-02 09:49:03.377 20994 20994 F DEBUG   : Cmdline: system_server
03-02 09:49:03.377 20994 20994 F DEBUG   : pid: 12648, tid: 20988, name: system_server  >>> system_server <<<
03-02 09:49:03.377 20994 20994 F DEBUG   : uid: 1000
03-02 09:49:03.377 20994 20994 F DEBUG   : tagged_addr_ctrl: 0000000000000001 (PR_TAGGED_ADDR_ENABLE)
03-02 09:49:03.377 20994 20994 F DEBUG   : pac_enabled_keys: 000000000000000f (PR_PAC_APIAKEY, PR_PAC_APIBKEY, PR_PAC_APDAKEY, PR_PAC_APDBKEY)
03-02 09:49:03.377 20994 20994 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0000000000000000
03-02 09:49:03.377 20994 20994 F DEBUG   : Cause: null pointer dereference
03-02 09:49:03.377 20994 20994 F DEBUG   :     x0  00000078fe512360  x1  000000778d57cc10  x2  000000778d57cc18  x3  0000000000000010
03-02 09:49:03.377 20994 20994 F DEBUG   :     x4  0000000000000000  x5  0000000000000000  x6  00000079b737c6cb  x7  67615f6164697266
03-02 09:49:03.377 20994 20994 F DEBUG   :     x8  0000000000000001  x9  00000000000051fc  x10 00000000000051fc  x11 00000079b725697b
03-02 09:49:03.377 20994 20994 F DEBUG   :     x12 00000079b72a0d2c  x13 0000000000000026  x14 00000079b7258f06  x15 000000000000000a
03-02 09:49:03.377 20994 20994 F DEBUG   :     x16 0000000000000001  x17 00000079b7344bc0  x18 0000007721b52000  x19 0000000000000000
03-02 09:49:03.377 20994 20994 F DEBUG   :     x20 00000078fe512000  x21 00000000000001d0  x22 0000000000003168  x23 0000000000003168
03-02 09:49:03.377 20994 20994 F DEBUG   :     x24 000000778d57ccb0  x25 000000778d57ccb0  x26 000000778d57cff8  x27 00000000000fc000
03-02 09:49:03.377 20994 20994 F DEBUG   :     x28 00000000000fe000  x29 000000778d57cc40
03-02 09:49:03.377 20994 20994 F DEBUG   :     lr  00000078fe51110c  sp  000000778d57cc10  pc  0000000000000000  pst 0000000080001800
03-02 09:49:03.377 20994 20994 F DEBUG   : backtrace:
03-02 09:49:03.377 20994 20994 F DEBUG   :       #00 pc 0000000000000000  <unknown>
03-02 09:49:03.377 20994 20994 F DEBUG   :       #01 pc 0000000000000108  <anonymous:78fe511000>
```

而且，我用 Magisk 也成功复现了这个 BUG（未安装 KernelSU）：

![telegram-cloud-photo-size-5-6053058235759440991-y](https://user-images.githubusercontent.com/4233744/222325141-b4631930-c562-4f60-aa21-979dd5845ca2.jpg)

**Comment by duanxiaoyun2003** [comment]
同红米n12t，执行frida -U -f 就会软重启，框架是magisk delat 安卓版本13 frida 和Frida server 16.0.0 fridatools 12.0.4

**Comment by General110** [comment]
> 同红米n12t，执行frida -U -f 就会软重启，框架是magisk delat 安卓版本13 frida 和Frida server 16.0.0 fridatools 12.0.4

这个解决了是frida 的问题 [https://github.com/frida/frida-gum/pull/731](https://github.com/frida/frida-gum/pull/731)

**Comment by simatuzheng** [comment]
> > 同红米n12t，执行frida -U -f 就会软重启，框架是magisk delat 安卓版本13 frida 和Frida server 16.0.0 fridatools 12.0.4
> 
> 这个解决了是frida 的问题 [frida/frida-gum#731](https://github.com/frida/frida-gum/pull/731)

你好，我的小米12spro  也是这个问题，请问如何解决的。

**Comment by General110** [comment]
> > > 同红米n12t，执行frida -U -f 就会软重启，框架是magisk delat 安卓版本13 frida 和Frida server 16.0.0 fridatools 12.0.4
> > 
> > 
> > 这个解决了是frida 的问题 [frida/frida-gum#731](https://github.com/frida/frida-gum/pull/731)
> 
> 你好，我的小米12spro 也是这个问题，请问如何解决的。

你可以试试最新版frida看看，不记得他在那个版本修复了。

**Comment by caijinwei** [comment]
最后解决了么   我pixel5 安卓13 也出现了软重启问题。最新版frida

**Comment by wrxdz** [comment]
无解啊，
16.0.13及以后修正重启，报dlopen failed: library "/proc/self/fd/283" not found
16.0.12启动有个报错
16.0.11及以前开启frida重启问题
老版本12.8.0 12.4.0还报segmentation fault错误
