### ISSUE TITLE
内核4.9.148编译错误

### ISSUE THREAD

**Issue by Coconutat** [tiann/KernelSU#290]
目标设备：Huawei P10 
系统版本：EMUI 9.1.0
内核版本：4.9.148
交叉编译器：gcc-arm-9.2-2019.12-x86_64-aarch64-none-linux-gnu
KernelSU版本：0.3.9/0.4.0
config里添加了KPROBES相关，
`CONFIG_KPROBES=y
CONFIG_HAVE_KPROBES=y
CONFIG_KPROBE_EVENTS=y`
也支持CONFIG_MOUDLES。
`CONFIG_MODULES=y`
不添加KernelSU可以正常编译。
内核源码：[Kirin960内核，9.1分支](https://github.com/maimaiguanfan/android_kernel_huawei_hi3660/tree/9.1)
错误log：
[log.txt](https://github.com/tiann/KernelSU/files/10876713/log.txt)

**Comment by tiann** [comment]
```
../drivers/kernelsu/selinux/sepolicy.c:734:22: error: ‘struct policydb’ has no member named ‘type_attr_map_array’; did you mean ‘type_attr_map’?
  734 |  for (j = 0; j < db->type_attr_map_array->total_nr_elements; j++) {
      |                      ^~~~~~~~~~~~~~~~~~~
      |                      type_attr_map
```

You should understand the source code and modify it yourself, huawei modify its code and if we modify KernelSU, other kernel will not be happy.

**Comment by Coconutat** [comment]
> ```
> ../drivers/kernelsu/selinux/sepolicy.c:734:22: error: ‘struct policydb’ has no member named ‘type_attr_map_array’; did you mean ‘type_attr_map’?
>   734 |  for (j = 0; j < db->type_attr_map_array->total_nr_elements; j++) {
>       |                      ^~~~~~~~~~~~~~~~~~~
>       |                      type_attr_map
> ```
> 
> You should understand the source code and modify it yourself, huawei modify its code and if we modify KernelSU, other kernel will not be happy.

Thank for your help.
