### ISSUE TITLE
使用0.4版本的KSU管理器同时安装ZygiskOnKSU模块会导致Momo显示：找到Magisk

### ISSUE THREAD

**Issue by yhaue** [tiann/KernelSU#293]
**Describe the bug**
使用0.4版本的KSU管理器同时安装ZygiskOnKSU模块会导致Momo显示：找到Magisk

**To Reproduce**
安装0.4版本的KSU管理器后安装ZygiskOnKSU(4-0.6.2)，Momo显示：找到Magisk
此时退回0.3.9版本的KSU管理器并重启，Momo不再显示找到Magisk
再次安装0.4版的KSU，重启，Momo再次显示：找到Magisk

**Smartphone (please complete the following information):**
 - Device: K30SU
 - OS: Lineage19.1

**Comment by tiann** [comment]
不影响使用。

**Comment by natsumerinchan** [comment]
如果app能正常启动则没必要太过关注momo的检测结果

**Comment by Rakau** [comment]
> 不影响使用。

使用欧易APP会提示设备已被ROOT

**Comment by tiann** [comment]
我也用欧易，没遇到这个情况。

**Comment by Rakau** [comment]
> 我也用欧易，没遇到这个情况。

那只有一个可能了，用了挂载/system的模块导致这个情况
