### ISSUE TITLE
gcc isra optimize break kprobe symbol lookup

### ISSUE THREAD

**Issue by rhjdvsgsgks** [tiann/KernelSU#296]
**Describe the bug**
default gcc optimize will add a ".isra.x" postfix after symbol. that will make kprobe failed with -2

**To Reproduce**
1. use gcc to compile kernel

**Expected behavior**
able to handle symbol with postfix

**Screenshots**
no

**Smartphone (please complete the following information):**
 - Device: not relevant
 - OS: not relevant
 - Version 4.14.274

**Additional context**
https://github.com/iovisor/bcc/issues/1754

**Comment by tiann** [comment]
https://kernelsu.org/guide/how-to-integrate-for-non-gki.html#manully-modify-the-kernel-source

**Comment by Dreamail** [comment]
You should patch your kernel source code

**Comment by Dreamail** [comment]
I mean backporting this feature may work:
https://lore.kernel.org/all/20211004162936.21961-1-ndesaulniers@google.com/
https://lore.kernel.org/all/20210408182843.1754385-8-samitolvanen@google.com/
