### ISSUE TITLE
不存在SU

### ISSUE THREAD

**Issue by juanlianyangyang** [tiann/KernelSU#298]
我按照网站上的方法，加入到了我的内核中，我还需要做什么才能使其工作正常，KernelSU的重启到Rec是工作的！

![image](https://user-images.githubusercontent.com/91620957/223386635-c3fb3b9f-7333-4f4c-acb6-7579deb7eac7.png)

![image](https://user-images.githubusercontent.com/91620957/223386797-f2689423-2322-455f-bea6-b250a73cbc24.png)

**Comment by tiann** [comment]
No log no fix.
