### ISSUE TITLE
当我的post-of-data脚本需要先setenforce 0，之后再延时setenforce 1的话，会造成模块失效，手机重启(selinux规则没有apply进去)

### ISSUE THREAD

**Issue by kodhh** [tiann/KernelSU#299]
当我的post-of-data脚本有需要先setenforce 0，之后再延时setenforce 1的话，会造成模块失效，甚至手机重启(selinux规则没有apply进去)，但这在magisk是可以的

**Comment by tiann** [comment]
请清晰地描述你的问题并附上日志。

**Comment by kodhh** [comment]
我把 getenforce() 函数删除就好了，也没看到有什么问题
