### ISSUE TITLE
微软身份认证器启动后导致系统崩溃重启

### ISSUE THREAD

**Issue by fatinghenji** [tiann/KernelSU#304]
**描述 bug**
微软身份认证器启动后导致系统崩溃重启

**复现步骤**
1. 启动微软身份认证器
2. 系统停止响应，重启

**期望行为**
应用正常启动运行

**截屏**
系统崩溃，无法提供截屏

**手机信息 (请填写一下信息):**
 - 手机型号: 一加acePro
 - OS: coloros13
 - Version  0.4.0

**额外信息**
无

**Comment by Rakau** [comment]
没遇到此情况

**Comment by tiann** [comment]
至少提供一下日志，还有你需要确认这是 KernelSU 的问题而不是你装的其他模块或者系统导致。

**Comment by beiweiaran** [comment]
> 回复

我magisk root之后也这样进微软身份验证器直接系统直接崩溃关机了
