### ISSUE TITLE
su -c command don't accept arguments until I use quotes

### ISSUE THREAD

**Issue by frknkrc44** [tiann/KernelSU#305]
**Describe the bug**
Magisk accepts command args for su -c without quotes but KernelSU don't.

**To Reproduce**
~ $ su -c echo arg

~ $ su -c "echo arg"
arg

**Expected behavior**
It have to accept command line arguments without quotes.

**Screenshots**
![Screenshot_20230318-064134_Termux](https://user-images.githubusercontent.com/45714956/226083209-2c786174-8a7d-4240-85a5-36a2bc2dc26a.png)

**Smartphone (please complete the following information):**
 - Device: Oneplus 9
 - OS: Android 13
 - Version 10663

**Additional context**

**Comment by Ylarod** [comment]
Now, `/system/bin/su` is redirected to `/system/bin/sh` in kernel with permission promotion.
The `sh` cannot work without quotes.
In the future, we may provide a userspace `su` to solve this.
