### ISSUE TITLE
Unable to read /data/data

### ISSUE THREAD

**Issue by Rakau** [tiann/KernelSU#306]
**Describe the bug**

Mixplorer and Swift Backup can't read files in /data/data after giving root access

**Smartphone (please complete the following information):**
 - Device: Xiaomi 13
 - OS: Andriod 13
 - Version 10678 & Manager v0.4.0-5-g76b9790 10677

**Comment by tiann** [comment]
https://kernelsu.org/guide/faq.html#is-there-any-mount-master-global-mount-namespace-in-kernelsu

**Comment by KoljaFrahm** [comment]
> https://kernelsu.org/guide/faq.html#is-there-any-mount-master-global-mount-namespace-in-kernelsu

This link is not readable anymore.
How can I access /data/data with a root explorer (like solid explorer)?
