### ISSUE TITLE
Feature request: system r/w; systemless hosts

### ISSUE THREAD

**Issue by simplerick-simplefun** [tiann/KernelSU#307]
**Is your feature request related to a problem? Please describe.**
Hello I was using adaway and tried to edit system host file but it's not supported. In magisk there's an option of "systemless hosts" but there's no module available for it. Moreover it will be useful for backup/restore of system apps with system r/w.

**Describe the solution you'd like**
feature of "system r/w" or "systemless host"

**Comment by tiann** [comment]
https://t.me/KernelSU_group/3249/44669

**Comment by 5wHN28Dg** [comment]
Just tested it and unfortunately it broke playi

**Comment by Lu5ck** [comment]
`mount -bind` breaks safetynet.
`overlay /system/etc` expose root modifications thus get detected by anti root
Did be nice to be able to overlay just one file or somehow only expose that one file.
