### ISSUE TITLE
An error was reported when compiling Android12-5.10 x86_64

### ISSUE THREAD

**Issue by longhuan1999** [tiann/KernelSU#31]
An error was reported when compiling Android12-5.10 x86_64, but the compilation of Android13-5.15 x86_64 passed.
![image](https://user-images.githubusercontent.com/43313501/211148822-bf16334d-e2fe-4b3a-8696-a844c60be585.png)
![image](https://user-images.githubusercontent.com/43313501/211149084-d0bfc387-6c6b-44df-8c9b-43c06183500e.png)

**Comment by tiann** [comment]
please provide the kernel source code

**Comment by longhuan1999** [comment]
I just used my own workflow, kernelSU is the latest without modification.

**Comment by tiann** [comment]
I need the Linux kernel source code

**Comment by hmtheboy154** [comment]
Do you have `CONFIG_GENERIC_ENTRY` defined in your defconfig ?

**Comment by longhuan1999** [comment]
repo from https://android.googlesource.com/kernel/manifest

**Comment by longhuan1999** [comment]
BUILD_BOOT_IMG=1 SKIP_VENDOR_BOOT=1 KERNEL_BINARY=bzImage GKI_RAMDISK_PREBUILT_BINARY=out/ramdisk AVB_SIGN_BOOT_IMG=1 AVB_BOOT_PARTITION_SIZE=$((64*1024*1024)) AVB_BOOT_ALGORITHM=SHA256_RSA2048 AVB_BOOT_KEY=prebuilts/kernel-build-tools/linux-x86/share/avb/testkey_rsa2048.pem BOOT_IMAGE_HEADER_VERSION=4 LTO=thin BUILD_CONFIG=common/build.config.gki.x86_64 build/build.sh

**Comment by longhuan1999** [comment]
https://github.com/longhuan1999/KernelSU/actions/runs/3861583741

**Comment by tiann** [comment]
Please try this version: https://github.com/tiann/KernelSU/commit/94d0d5ac6b18c07ef25eb42c4dffd90bb816e715

**Comment by longhuan1999** [comment]
Ok, thanks. There is no issues any more.
