### ISSUE TITLE
Oppo/Realme kernel restrict su running

### ISSUE THREAD

**Issue by qiurigao** [tiann/KernelSU#321]
Device: Realme GT 5G (RMX2202)
Stock ROM: Color OS 13
Android Version: Android-13-5.4-qgki
Clang Version: r383902b1
DEFCONFIG: vendor/lahaina-qgki_defconfig
Kernel Source: https://github.com/realme-kernel-opensource/realme_gt-AndroidT-kernel-source
Vendor Source: https://github.com/realme-kernel-opensource/realme_gt-AndroidT-vendor-source
Issues:执行su 后并未切换到root https://github.com/LineageOS/android_kernel_oneplus_sm8250/commit/d0a5559729ef796f7c427151ff347558ec4235b8
日志：
[boot_29--1970-01-04-10-26-15.tar.gz](https://github.com/tiann/KernelSU/files/11063841/boot_29--1970-01-04-10-26-15.tar.gz)

<6>  (2)[8953:sh][20230324_13:30:50.845257]@2 KernelSU: newfstatat su->sh!
<6>  (2)[8953:sh][20230324_13:30:50.845462]@2 KernelSU: faccessat su->sh!
<6>  (0)[8974:sh][20230324_13:30:50.848458]@0 KernelSU: do_execveat_common su found
<6>  (0)[8974:sh][20230324_13:30:50.848547]@0 KernelSU: error: 0, sid: 2125

**Comment by natsumerinchan** [comment]
上传一下编译时生成的.config

**Comment by qiurigao** [comment]
[lahaina-qgki_defconfig.zip](https://github.com/tiann/KernelSU/files/11068176/lahaina-qgki_defconfig.zip)

**Comment by natsumerinchan** [comment]
![截图 2023-03-25 15-31-04](https://user-images.githubusercontent.com/64072399/227703765-9876d82b-782e-40b9-9762-4ef8dbf93c9a.png)

**Comment by qiurigao** [comment]
[config.zip](https://github.com/tiann/KernelSU/files/11068309/config.zip)

**Comment by qiurigao** [comment]
> As I recall realme has restrictions on what can run as su or root

are you code view

**Comment by tiann** [comment]
https://github.com/realme-kernel-opensource/realme_gt-AndroidT-kernel-source/blob/master/include/trace/hooks/secureguard.h

**Comment by tiann** [comment]
Maybe you can change this line: https://github.com/realme-kernel-opensource/realme_gt-AndroidT-kernel-source/blob/master/include/trace/hooks/secureguard.h#L14

to `#if 0`?

**Comment by tiann** [comment]
你是否有做类似隐藏 BL 锁的操作？

**Comment by qiurigao** [comment]
> 你是否有做类似隐藏 BL 锁的操作？

没有 而且也没有必要啊

**Comment by qiurigao** [comment]
![Screenshot_2023-04-16-08-44-06-43_9e8df3d0c7c1f50248b6ee043a653d26](https://user-images.githubusercontent.com/22121479/232260213-8fcc5be2-cc14-42ce-a3ee-22b2afc526a9.jpg)
宽容模式可以正常运行

**Comment by qiurigao** [comment]
@tiann 如何在开机后手动修改selinux规则并启用selinux就像magisk一样

**Comment by tiann** [comment]
https://kernelsu.org/guide/module.html#sepolicy-rule

**Comment by tiann** [comment]
I will close this since someone follow the instruction and disable all security guard features of the kernel and it works well.
