### ISSUE TITLE
How do I modify the files in the /system path?

### ISSUE THREAD

**Issue by Imzpy** [tiann/KernelSU#322]
I want to add a file or folder in the path/system/etc,
But when I create a file or folder, will prompt "Read only file system".
I have seen some articles that can use the systemless method to add files or folders,
But I don't know how to do it in kernelsu,
Do I need to install zygisk?
Place the file I want to add in the /data/adb/ksu/modules/zygisksu/system/etc/xxx.conf directory? 
like this?
Is there any other way?
Can I use this method without installing modules?

Please help me.tks!

**Comment by Imzpy** [comment]
Last night, 
I conducted a test ,
created the required files in the path "/data/adb/ksu/modules/", 
such as "/data/adb/ksu/modules/mroot/system/etc/xxx. conf".
When I restart my phone, 
I find that using the command "ls - al/system/etc | grep xxx. conf" ,
can output the existence of this file.

I want to know the files created in this way,
When is the file loaded?
Is it the earliest time?

If you can,please publish some tutorials on the official website,
If it can include the principle and the process and load time ,
That would be perfect.
Thank you.

**Comment by Imzpy** [comment]
One more question,
When the original file already exists,
Will creating a file with the same name overwrite it?
What if I want to delete a file?
What should I do?
Please help me, thank you very much.

**Comment by tiann** [comment]
1. To modify /system, you should use modules, modules in KernelSU works nearly same way as Magisk, check the magisk document first: https://topjohnwu.github.io/Magisk/guides.html#magisk-modules
2. KernelSU use overlayfs to modify system, you can use `mknod filename c 0 0` in the module dir to delete `filename` in the same directory in system.

**Comment by Imzpy** [comment]
Thank you very much for your help,
It is recommended that you annotate the overayfs on the official website,
And attach a module description for magisk,
This is very friendly to newcomers.

**Comment by tiann** [comment]
Thanks for your advice, I am writing a document about module

**Comment by tiann** [comment]
https://kernelsu.org/guide/module.html#system-directory

**Comment by Imzpy** [comment]
Thank you very much. I saw your update yesterday

**Comment by deyloTT** [comment]
Hey, i was reading through the pages about modulea but im yet to understand how do i edit /system/build.prop
what i want is to force dark mode system wide. I usually add a line to build.prop but since this is my first time using kernelsu, i dont know how to get it done. Simply trying to edit the file doesn’t work anymore

**Comment by tiann** [comment]
> Hey, i was reading through the pages about modulea but im yet to understand how do i edit /system/build.prop what i want is to force dark mode system wide. I usually add a line to build.prop but since this is my first time using kernelsu, i dont know how to get it done. Simply trying to edit the file doesn’t work anymore

https://kernelsu.org/guide/module.html#system-prop same as Magisk

**Comment by deyloTT** [comment]
Sorry but im still lost. Downloaded a template module and tried to edit it with my changes but that doesnt work. Also saw a modules named overlayfs, will that work to edit build.prop?
