### ISSUE TITLE
App data cann't read by third-party apps

### ISSUE THREAD

**Issue by trinhloivn** [tiann/KernelSU#328]
With kernelsu on my k50ultra(android12-5.10.101_2022-05.zip)
some backup apps like swift backup,alpha backup,Neo-Backup,...cant load data app to backup and restore

with magisk it work fine.i dont know why,,,

**Comment by TinyHai** [comment]
those apps depend special su file, but kernelsu don't have su file
when some apps exec su file, kernelsu will replace it with sh which has uid 0 and permisive selinux context

**Comment by TinyHai** [comment]
If you want a backup app which works fine on kernelsu, you can try it [Android-DataBackup](https://github.com/XayahSuSuSu/Android-DataBackup)

**Comment by H1mJT** [comment]
[Neo backup 8.3.2 alpha03](https://t.me/neo_applications/305)  does work with kernelsu.

**Comment by trinhloivn** [comment]
> If you want a backup app which works fine on kernelsu, you can try it [Android-DataBackup](https://github.com/XayahSuSuSu/Android-DataBackup)

thanks for infor.i will try...

**Comment by tiann** [comment]
#306
