### ISSUE TITLE
KernelSU doesn't work and show "prctl reply error"

### ISSUE THREAD

**Issue by hmtheboy154** [tiann/KernelSU#33]
![Screenshot_20230108-120223488](https://user-images.githubusercontent.com/39849246/211202845-4c69f530-6195-42d9-9add-4b9daededf67.jpg)
![Screenshot_20230108-121127341](https://user-images.githubusercontent.com/39849246/211202849-8b0d9e77-3fe7-4413-80c2-7a5c35cd8cfc.jpg)

Here is my kernel source :
https://github.com/hmtheboy154/Darkmatter-kernel/tree/umbral

I also have this source which contain KernelSU so I can easily merge them
https://github.com/hmtheboy154/kernel_ksu

**Comment by hmtheboy154** [comment]
revert `kernel: add PT_REGS_PARAM6` works
https://github.com/tiann/KernelSU/commit/36aff66835637cc17e5e4e6a5f491cbcc82fa193

**Comment by tiann** [comment]
oh, no, there is a typo: https://github.com/tiann/KernelSU/commit/36aff66835637cc17e5e4e6a5f491cbcc82fa193#diff-86cf8fa1ed07f8b903b70320ef8f785e5e3d4ddb6cacb1f6a49bc53bc75a7ad1R29

**Comment by tiann** [comment]
https://github.com/tiann/KernelSU/commit/a2ec618c4943d21ceb2e03eecfcc99ea87b724ca
