### ISSUE TITLE
ZArchiver cannot grant root

### ISSUE THREAD

**Issue by bugme2** [tiann/KernelSU#331]
在管理器给ZArchiver授权后，但是ZArchiver没有获取到权限。

复现：
重新安装ZArchiver，管理器授权给ZArchiver。

截图：
![Screenshot_2023-04-01-08-20-43-13_baaa51257c82a8b3f281ce09e6f2493f](https://user-images.githubusercontent.com/40169265/229256186-d9020f1d-b393-409e-b68a-b43110e59eed.jpg)
![Screenshot_2023-04-01-08-19-26-95_83ab3b20d3fba5c9c905d050db1f8de3](https://user-images.githubusercontent.com/40169265/229256194-26937b0a-5ff2-4e6b-97a2-0a618f484ed3.jpg)

设备：一加11
系统：ColorOs13
版本：安卓13

**Comment by Dreamail** [comment]
请强行停止目标应用后再试

**Comment by bugme2** [comment]
> 请强行停止目标应用后再试

无用

**Comment by bugme2** [comment]
> > 请强制停止目标应用后重新测试
> 
> 无用

**Comment by 1582130940** [comment]
或许ZArchiver是只认su二进制路径的应用，参考钛备份？

**Comment by tiann** [comment]
This is a bug of ZArchiver, it use `su -v` to check su version and if i force the KernelSU version to be "25.2:MagiskSU" and it will work, other version longer than this would faile.

**Comment by tiann** [comment]
https://github.com/tiann/KernelSU/commit/effcaf0cde27d936a27df4c9b2a4bdfc513b1edd
