### ISSUE TITLE
Is there KernelSU Manager for Recovery Mode

### ISSUE THREAD

**Issue by huangsijun17** [tiann/KernelSU#34]
like [Magisk Manager for Recovery Mode (mm)](https://github.com/Rikj000/Magisk-Manager-for-Recovery-Mode)

**Comment by tiann** [comment]
No, there isn't. You can adb push `ksud` to TWRP and use the cli to manage module, or just delte `/data/adb/ksu/`.
KernelSU have no plan to support recovery mode now.
