### ISSUE TITLE
"Remove tags with same KMI"

### ISSUE THREAD

**Issue by trinhloivn** [tiann/KernelSU#341]
![Screenshot_2023-04-05-01-33-57-023_com android chrome](https://user-images.githubusercontent.com/72311759/229886503-31780550-06af-455b-94e1-5406ff69e518.jpg)
In new released version no longer for kernel android12-5.10.101_2022
I see it 'same kmi'
so can i use what version on last release ?
or next update it back or drop it
Thank for reading

**Comment by Ylarod** [comment]
https://kernelsu.org/guide/installation.html#necessary-knowledge

**Comment by trinhloivn** [comment]
> https://kernelsu.org/guide/installation.html#necessary-knowledge
thanks for reply,i read it
my kernel is 5.10.101-android12-9 so KMI is 5.10-android12-9
i can use same but in releases on have 5.10-android12-02
                                                              5.10-android12-11
it not same
i try 5.10-android12-11 my phone bootloop....

**Comment by Ylarod** [comment]
`2023-02` is the release date, not kmi version

you should use ksu-10724-Image-android12-5.10.160_2023-02

**Comment by trinhloivn** [comment]
> `2023-02` is the release date, not kmi version
> 
> you should use ksu-10724-Image-android12-5.10.160_2023-02
@Ylarod 
thanks u,my bad
it work now
