### ISSUE TITLE
There isn't the kernelsu for the 5.10.101 kernel in the 5.0 release. 

### ISSUE THREAD

**Issue by JackieCat0418** [tiann/KernelSU#342]
In last version, there is the 5.10.101 in it.But in kernelsu 5.0, there isn't. Is the 5.10.101 not supported?

**Comment by TinyHai** [comment]
[GKI-Versioning](https://source.android.com/docs/core/architecture/kernel/gki-versioning)

**Comment by Ylarod** [comment]
https://kernelsu.org/guide/installation.html#necessary-knowledge
https://github.com/tiann/KernelSU/commit/ddbc71b273ec57af67c710e76fb2a6978f88f308

**Comment by trinhloivn** [comment]
> In last version, there is the 5.10.101 in it.But in kernelsu 5.0, there isn't. Is the 5.10.101 not supported?

same my kernel u can try this https://github.com/tiann/KernelSU/releases/download/v0.5.0/AnyKernel3-android12-5.10.160_2023-02.zip
it work for me

**Comment by JackieCat0418** [comment]
I used to flash https://github.com/tiann/KernelSU/releases/download/v0.5.0/AnyKernel3-android12-5.10.160_2023-02.zip
It can boot and use ksu. However,I can't use the superuser. I can only use the modules

**Comment by tiann** [comment]
> I used to flash https://github.com/tiann/KernelSU/releases/download/v0.5.0/AnyKernel3-android12-5.10.160_2023-02.zip It can boot and use ksu. However,I can't use the superuser. I can only use the modules @Ylarod

Update manager App
