### ISSUE TITLE
System Overlay cant load

### ISSUE THREAD

**Issue by trinhloivn** [tiann/KernelSU#346]
+ In new release system overlay cant load anymore (product/overlay: i make module to install overlay system in this)
+ pre-release it work normal

**Comment by Ylarod** [comment]
Kernel 5.10 and above will by default unmount files mounted by modules for applications without authorized su permissions .

**Comment by trinhloivn** [comment]
> Kernel 5.10 and above will by default unmount files mounted by modules for applications without authorized su permissions .

so i cant change this? i want mount file by modules :((

**Comment by tiann** [comment]
Add the app to superuser list

**Comment by trinhloivn** [comment]
> Add the app to superuser list

i cant do that step by step because module i use have so many  overlay app (95)
hope u can make option to turn on/off this
:((

**Comment by tiann** [comment]
Maybe it will be added in the future

**Comment by trinhloivn** [comment]
> Maybe it will be added in the future

i hope so.....
back to old version :((
thank for work
