### ISSUE TITLE
lost link

### ISSUE THREAD

**Issue by littlehappy666** [tiann/KernelSU#359]
If I create a empty file "/system/product/app/VoiceTrigger" in my module directory, it shows that after reboot the empty directory "/system/product/app" does exist, but actually the directory "/system/product" is expected to be a soft link not a real directory. The files in the True Path "/product/app" are unaffected. It will not take effect unless I create a directory named "/product/app/VoiceTrigger". This problem can cause the incompatibility between magisk module and ksu module. Is there any way to solve this problem?

**Comment by tiann** [comment]
Do you create the file manully in customize.sh？

**Comment by littlehappy666** [comment]
yes. both try, same result

**Comment by littlehappy666** [comment]
> 

yes, both try, same result

**Comment by littlehappy666** [comment]
either
REMOVE="
/system/product/app/VoiceTrigger
"
or
REPLACE="
/system/product/app/VoiceTrigger
"
leads to the same result

**Comment by tiann** [comment]
Try this one https://github.com/tiann/KernelSU/commit/e7881c350c67cabfeb5bb2ec9e70a7126c394221

**Comment by littlehappy666** [comment]
OK, I figure it out. Thank you so much!
