### ISSUE TITLE
Manager caused device restart

### ISSUE THREAD

**Issue by King-Maple** [tiann/KernelSU#361]
**Description error**
On my device, after opening the kernelsu manager and waiting for a few seconds, the device will freeze and restart

**Smartphone:**
-Device: Meizu 20pro
-OS: Android 13
-Version: 0.5.1
**Log:**
[KernelSU_bugreport_2023-04-09_00_01.tar.gz](https://github.com/tiann/KernelSU/files/11183651/KernelSU_bugreport_2023-04-09_00_01.tar.gz)

**Comment by tiann** [comment]
Does it crash when you use adb shell and execute "su"?

**Comment by King-Maple** [comment]
> Does it crash when you use adb shell and execute "su"?

Not really

**Comment by tiann** [comment]
Does it crash every time when opening manager?

**Comment by King-Maple** [comment]
> Does it crash every time when opening manager?

Yes, but as long as you don't switch pages, it won't cause the system to restart

**Comment by tiann** [comment]
Can u execute "ksud debug su" in adb shell with su?

**Comment by King-Maple** [comment]
> Can u execute "ksud debug su" in adb shell with su?

![微信截图_20230411110759](https://user-images.githubusercontent.com/33850335/231046034-0c43c75c-602a-4c88-8ffe-8ba1dfb95283.png)

**Comment by tiann** [comment]
Where is the kernel source? it seems that the kernel is compiled yourself.

**Comment by King-Maple** [comment]
> Where is the kernel source? it seems that the kernel is compiled yourself.

I only changed the version number

**Comment by King-Maple** [comment]
> Where is the kernel source? it seems that the kernel is compiled yourself.

I also used the one you compiled

**Comment by tiann** [comment]
Ok, i know. Can you reboot the device and give me a dmesg ?

**Comment by King-Maple** [comment]
> Ok, i know. Can you reboot the device and give me a dmesg ?
[dmesg.txt](https://github.com/tiann/KernelSU/files/11196035/dmesg.txt)

**Comment by tiann** [comment]
I see many uids are granted root permission, how did you give them root? When you toggle the root switch in "SuperUser" page and kernel will panic?

**Comment by King-Maple** [comment]
> I see many uids are granted root permission, how did you give them root? When you toggle the root switch in "SuperUser" page and kernel will panic?

I granted Root with "SuperUser" page. After switching to the page, I searched and authorized it. However, at this time, you can only kill the manager process directly and cannot return. Switching to other pages will cause you to get stuck

**Comment by King-Maple** [comment]
> I see many uids are granted root permission, how did you give them root? When you toggle the root switch in "SuperUser" page and kernel will panic?

I'll try recording a video for you to see

**Comment by King-Maple** [comment]
> I see many uids are granted root permission, how did you give them root? When you toggle the root switch in "SuperUser" page and kernel will panic?

[video.zip](https://github.com/tiann/KernelSU/files/11196122/video.zip)

**Comment by tiann** [comment]
Can you send me files under `/sys/fs/pstore`?

**Comment by tiann** [comment]
In addition, if you don't do "pull-to-refresh" in "SuperUser" page, would it crash?

**Comment by King-Maple** [comment]
> In addition, if you don't do "pull-to-refresh" in "SuperUser" page, would it crash?

no

**Comment by King-Maple** [comment]
> Can you send me files under `/sys/fs/pstore`?

**Comment by King-Maple** [comment]
> Can you send me files under `/sys/fs/pstore`?

[console-ramoops-0.zip](https://github.com/tiann/KernelSU/files/11196347/console-ramoops-0.zip)

**Comment by tiann** [comment]
[KernelSU_v0.5.1-5-gf2d8f1e-release.apk.zip](https://github.com/tiann/KernelSU/files/11196544/KernelSU_v0.5.1-5-gf2d8f1e-release.apk.zip)
Please try this one

**Comment by King-Maple** [comment]
> [KernelSU_v0.5.1-5-gf2d8f1e-release.apk.zip](https://github.com/tiann/KernelSU/files/11196544/KernelSU_v0.5.1-5-gf2d8f1e-release.apk.zip) Please try this one

This is no problem

**Comment by tiann** [comment]
That is werid, i think this is a kernel optimization of MeiZu which cause the bug, but it is ok for us to do a workaround.
