### ISSUE TITLE
KernelSU 模块挂载失败

### ISSUE THREAD

**Issue by Coconutat** [tiann/KernelSU#364]
**描述错误**  
KernelSU挂载模块失败。
前述：
事件起因是在GSI版本的系统安装ZygiskOnKernelSU模块但是却不生效，然后反馈给模块。经过一番指点，认为可能是KernelSU的错误，@5ec1cff大佬建议我过来反馈下。
上一个反馈：[#16](https://github.com/Dr-TSNG/ZygiskOnKernelSU/issues/16)

**复现**  
1. 刷入一个GSI系统镜像  
2. 在KernelSU管理器里安装ZygiskOnKernelSU 0.6.4 Debug版本 模块

**预期行为**  
模块挂在成功且生效。

**屏幕截图**  

![Screenshot_20230409-180401012](https://user-images.githubusercontent.com/85353552/230770401-ab172f0b-79eb-47f1-bed0-f4b231c31dda.jpg)
![Screenshot_20230409-180413673](https://user-images.githubusercontent.com/85353552/230770405-a60f33b2-82d4-4deb-a2ae-f1b9aa8689aa.jpg)

#**设备信息**  
名称：Huawei P10  
系统：DotOS(GSI)
基础系统：EMUI 9.0.1(Android 9.0)

# 日志

[log3.zip](https://github.com/tiann/KernelSU/files/11185327/log3.zip)
[KernelSU_bugreport_2023-04-09_19_31.tar.gz](https://github.com/tiann/KernelSU/files/11185328/KernelSU_bugreport_2023-04-09_19_31.tar.gz)

**Comment by tiann** [comment]
Android 9？我们没空支持这么老的设备，你有需要可以自己改。

**Comment by Coconutat** [comment]
> Android 9？我们没空支持这么老的设备，你有需要可以自己改。

系统刷的GSI，Android 11.底包是9.0

**Comment by 5ec1cff** [comment]
https://github.com/tiann/KernelSU/blob/main/userspace/ksud/src/event.rs#L40

相关日志：

```
04-09 11:10:23.595   800   800 I KernelSU: ksud::mount: stock overlay: umount all: []
04-09 11:10:23.596   800   800 I KernelSU: ksud::event: partition: system lowerdir: /data/adb/modules/zygisksu/system:/data/adb/modules/Android10_AND_11_GSI_Generic_Fix_For_Huawei_P10/system:/data/adb/modules/riru-core/system:/system
04-09 11:10:23.597   800   800 I KernelSU: ksud::mount: remount stock for /system/ : [MountInfo { source: "none", dest: "/system/system_ext/apex/com.android.vndk.v27/lib/libsoftkeymasterdevice.so", fstype: "tmpfs", options: ["rw", "seclabel", "nodev", "relatime", "mode=755"], dump: 0, pass: 0 }, MountInfo { source: "none", dest: "/system/system_ext/apex/com.android.vndk.v27/lib64/libsoftkeymasterdevice.so", fstype: "tmpfs", options: ["rw", "seclabel", "nodev", "relatime", "mode=755"], dump: 0, pass: 0 }, MountInfo { source: "none", dest: "/system/usr/keylayout", fstype: "tmpfs", options: ["rw", "seclabel", "nodev", "relatime", "mode=755"], dump: 0, pass: 0 }]
04-09 11:10:23.597   800   800 W KernelSU: ksud::event: remount stock failed: No such file or directory (os error 2), umount overlay /system
```

mount：

```
none /system/system_ext/apex/com.android.vndk.v27/lib/libsoftkeymasterdevice.so tmpfs rw,seclabel,nodev,relatime,size=1877868k,nr_inodes=469467,mode=755 0 0
none /system/system_ext/apex/com.android.vndk.v27/lib64/libsoftkeymasterdevice.so tmpfs rw,seclabel,nodev,relatime,size=1877868k,nr_inodes=469467,mode=755 0 0
none /system/usr/keylayout tmpfs rw,seclabel,nodev,relatime,size=1877868k,nr_inodes=469467,mode=755 0 0
```

**Comment by Coconutat** [comment]
我不太理解能在/data/adb/ksu/.mnt/system，就是不挂载system_ext。我看log内显示system_ext lowerdir is empty
`04-11 15:31:03.951   801   801 I KernelSU: ksud::mount: AutoMountExt4 drop: /data/adb/modules/, auto_umount: false
04-11 15:31:03.951   801   801 I KernelSU: ksud::utils: safemode: false
04-11 15:31:03.951   801   801 I KernelSU: ksud::utils: kernel_safemode: false
04-11 15:31:03.951   801   801 I KernelSU: ksud::module: /data/adb/post-fs-data.d not exists, skip
04-11 15:31:03.954   801   801 I KernelSU: ksud::module: load policy: /data/adb/modules/zygisksu/sepolicy.rule
04-11 15:31:03.957   801   801 I KernelSU: ksud::module: load policy: /data/adb/modules/Android10_AND_11_GSI_Generic_Fix_For_Huawei_P10/sepolicy.rule
04-11 15:31:03.957   801   801 I KernelSU: ksud::module: load policy: /data/adb/modules/riru-core/sepolicy.rule
04-11 15:31:03.960   801   801 I KernelSU: ksud::module: exec /data/adb/modules/zygisksu/post-fs-data.sh
04-11 15:31:03.992   801   801 I KernelSU: ksud::module: exec /data/adb/modules/Android10_AND_11_GSI_Generic_Fix_For_Huawei_P10/post-fs-data.sh
04-11 15:31:03.995   801   801 I KernelSU: ksud::module: exec /data/adb/modules/riru-core/post-fs-data.sh
04-11 15:31:04.175   386   386 I auditd  : type=1403 audit(0.0:70): policy loaded auid=4294967295 ses=4294967295
04-11 15:31:04.187   366   366 I ueventd : type=1400 audit(0.0:71): avc: denied { read } for name="image" dev="mmcblk0p59" ino=29 scontext=u:r:ueventd:s0 tcontext=u:object_r:unlabeled:s0 tclass=lnk_file permissive=1
04-11 15:31:04.208   801   801 I KernelSU: ksud::module: exec /data/adb/modules/hwr_logcat/post-fs-data.sh
04-11 15:31:04.329   801   801 I KernelSU: ksud::module: load /data/adb/modules/Android10_AND_11_GSI_Generic_Fix_For_Huawei_P10 system.prop
04-11 15:31:04.338   801   801 I KernelSU: ksud::module: load /data/adb/modules/riru-core system.prop
04-11 15:31:04.353   801   801 I KernelSU: ksud::mount: stock mount root: /data/adb/ksu/.mnt
04-11 15:31:04.354   801   801 I KernelSU: ksud::mount: rootdir: /data/adb/ksu/.mnt/system/, path: /data/adb/ksu/.mnt/system/system/usr/keylayout
04-11 15:31:04.354   801   801 I KernelSU: ksud::mount: bind stock mount: /system/usr/keylayout -> /data/adb/ksu/.mnt/system/system/usr/keylayout
04-11 15:31:04.354   801   801 I KernelSU: ksud::mount: rootdir: /data/adb/ksu/.mnt/system/, path: /data/adb/ksu/.mnt/system/system/system_ext/apex/com.android.vndk.v27/lib/libsoftkeymasterdevice.so
04-11 15:31:04.354   801   801 W KernelSU: ksud::event: mount system failed: get stock mount of partition: system failed
04-11 15:31:04.354   801   801 W KernelSU: ksud::event: partition: system_ext lowerdir is empty
04-11 15:31:04.354   801   801 W KernelSU: ksud::event: partition: odm lowerdir is empty
04-11 15:31:04.354   801   801 W KernelSU: ksud::event: partition: oem lowerdir is empty
04-11 15:31:04.354   801   801 W KernelSU: ksud::event: partition: product lowerdir is empty
04-11 15:31:04.354   801   801 W KernelSU: ksud::event: partition: vendor lowerdir is empty
04-11 15:31:04.354   801   801 I KernelSU: ksud::mount: stock overlay: mount all: []
`

**Comment by tiann** [comment]
[KernelSU_v0.5.1-12-g273a0b0-release.apk.zip](https://github.com/tiann/KernelSU/files/11207307/KernelSU_v0.5.1-12-g273a0b0-release.apk.zip)
用这个，重启手机再抓一下日志

**Comment by Coconutat** [comment]
> [KernelSU_v0.5.1-12-g273a0b0-release.apk.zip](https://github.com/tiann/KernelSU/files/11207307/KernelSU_v0.5.1-12-g273a0b0-release.apk.zip)
> 用这个，重启手机再抓一下日志

好的

**Comment by Coconutat** [comment]
> [KernelSU_v0.5.1-12-g273a0b0-release.apk.zip](https://github.com/tiann/KernelSU/files/11207307/KernelSU_v0.5.1-12-g273a0b0-release.apk.zip) 用这个，重启手机再抓一下日志

[KernelSU_Bugreport#4.zip](https://github.com/tiann/KernelSU/files/11207519/KernelSU_Bugreport.4.zip)

**Comment by tiann** [comment]
[KernelSU_v0.5.1-17-g3c6560a-release.apk.zip](https://github.com/tiann/KernelSU/files/11207600/KernelSU_v0.5.1-17-g3c6560a-release.apk.zip)
再试下这个

**Comment by Coconutat** [comment]
> [KernelSU_v0.5.1-17-g3c6560a-release.apk.zip](https://github.com/tiann/KernelSU/files/11207600/KernelSU_v0.5.1-17-g3c6560a-release.apk.zip)
> 再试下这个

好的，我下班就试试

**Comment by Coconutat** [comment]
> [KernelSU_v0.5.1-17-g3c6560a-release.apk.zip](https://github.com/tiann/KernelSU/files/11207600/KernelSU_v0.5.1-17-g3c6560a-release.apk.zip) 再试下这个

[KernelSU_Bugreport#5.zip](https://github.com/tiann/KernelSU/files/11209093/KernelSU_Bugreport.5.zip)

**Comment by tiann** [comment]
https://github.com/tiann/KernelSU/commit/39b5014add8dec58906cee8c4e4c73a8388fb2a4

**Comment by 5ec1cff** [comment]
你好，方便测试一下重构 mount 的 ksud 吗？

使用方法：用这个 ksud 替换 /data/adb/ksud ，在不打开 manager 的情况下重启

重启后，请提供模块挂载成功状态、/proc/1/mountinfo 、开机日志

如果模块挂载失败，可以打开 manager 再重启

[ksud.zip](https://github.com/tiann/KernelSU/files/11220567/ksud.zip)

**Comment by Coconutat** [comment]
> 你好，方便测试一下重构 mount 的 ksud 吗？
> 
> 使用方法：用这个 ksud 替换 /data/adb/ksud ，在不打开 manager 的情况下重启
> 
> 重启后，请提供模块挂载成功状态、/proc/1/mountinfo 、开机日志
> 
> 如果模块挂载失败，可以打开 manager 再重启
> 
> [ksud.zip](https://github.com/tiann/KernelSU/files/11220567/ksud.zip)

好的

**Comment by 5ec1cff** [comment]
https://t.me/a13e300
