### ISSUE TITLE
红魔8pro安装字体模块后无法进入系统

### ISSUE THREAD

**Issue by laukase** [tiann/KernelSU#371]
**Describe the bug**
红魔8pro在安装完字体模块后重启卡在第三屏。

**To Reproduce**
1. 安装字体模块
2. 重启

**Expected behavior**
安装字体模块后能正常开机并可以正常进入系统。

**Screenshots**

**Smartphone (please complete the following information):**
Kernel: 5.15.78-android13-8-gfe86c885b0db
BRAND: nubia
MODEL: NX729J
PRODUCT: NX729J
MANUFACTURER: nubia
SDK: 33
PREVIEW_SDK: 0
FINGERPRINT: nubia/NX729J/NX729J:13/TKQ1.221013.002/eng.nubia.20230205.014135:user/release-keys
DEVICE: NX729J
Manager: v0.5.1-12-g273a0b0 (10745)
KernelRelease: 5.15.78-android13-8-gfe86c885b0db
KernelVersion: #1 SMP PREEMPT Wed Mar 22 03:21:11 UTC 2023
Mahcine: aarch64
Nodename: localhost
Sysname: Linux
KernelSU: 10746
SafeMode: false

**Additional context**
[log.zip](https://github.com/tiann/KernelSU/files/11207752/log.zip)

**Comment by gcjmail** [comment]
也存在这个问题，刷了字体模块，没有给root权限的app都会闪退！

**Comment by fatinghenji** [comment]
类似问题，刷入字体模块后卡黑屏，长按电源键可呼出重启菜单。一加ace pro

**Comment by tiann** [comment]
0.7.2 版本的 shamiko 应该解决了此问题。

**Comment by fatinghenji** [comment]
> 0.7.2 版本的 shamiko 应该解决了此问题。

问题依旧存在

**Comment by fatinghenji** [comment]
> You can try adding SystemUI and your launcher to whitelist. It should avoid crashing by font modules

How should I switch between blacklist/whitelist mode in kernelsu? How should I create and edit a black/white list?

**Comment by tiann** [comment]
KernelSU now supports App Profile, allowing you to specify whether to uninstall font modules for a particular application.
