### ISSUE TITLE
在未来的版本中是否可以支持安装模块的版本更新提醒？

### ISSUE THREAD

**Issue by fatinghenji** [tiann/KernelSU#383]
**Is your feature request related to a problem? Please describe.**
在使用过程中很难确认安装的模块是否存在更新，很难跟上版本。

**Describe the solution you'd like**
类似于 magisk 中的更新提醒

**Describe alternatives you've considered**
如上

**Additional context**
无

**Comment by tiann** [comment]
未来可能会有
