### ISSUE TITLE
It just reboot to splash and doesn't come out of it.

### ISSUE THREAD

**Issue by TogoFire** [tiann/KernelSU#394]
**Describe the bug**
It just reboots to splash several times and doesn't get to bootanimation.

**To Play**
1. When installing the kernel and trying to turn on the device.

**Expected behavior**
I was hoping that at least it would be possible to get bootanimation to capture log.
If you can help me where I'm going wrong, I'd really appreciate it.

**Screenshots**
Stuck in splash (https://i.pinimg.com/736x/41/d7/ec/41d7eca8e2d5f40b9339ec16377bdab7.jpg)

**Smartphone:**
 - Device: Mi A2 Lite (daisy)
 - OS: Xtended ROM A13 v6
 - Kernel Version: 4.9.337

**Additional context**
Source Kernel: https://github.com/Dev-msm8953/kernel_xiaomi_msm8953/tree/ksu
Build Script: https://github.com/Dev-msm8953/kernel_xiaomi_msm8953/blob/ksu/build.sh

**Comment by tiann** [comment]
https://kernelsu.org/guide/how-to-integrate-for-non-gki.html

**Comment by TogoFire** [comment]
> https://kernelsu.org/guide/how-to-integrate-for-non-gki.html

I comment out ksu_enable_sucompat() and ksu_enable_ksud() in KernelSU/kernel/ksu.c. Device boots normally after that, so kprobe is broken.

Unfortunately kprobe is broken here, I tried their patches:
fs: Add hook kernel hook for kernelsu (exec, open, read_write, stat) |
drivers: input: Add KernelSU SafeMode inpnt_event Kernel Hook |
And
security: selinux: allow init exec (kernelsu:ksud) under nosuid

And to no avail.

Do you have any commits for 4.9 that fix the broken kprobe?

**Comment by tiann** [comment]
the dmesg seems normal?

**Comment by TogoFire** [comment]
> the dmesg seems normal?

I tried again. But still the same thing. Kprobe rip :/

https://github.com/Dev-msm8953/kernel_xiaomi_msm8953/commit/2ea5142690fa4623f776126852f4334664e4097c

Reduced log:
https://katb.in/watufupovoz

"KernelSU: unregister input kprobe: 1!", "KernelSU: load_allow_list open file failed: -2", and "KernelSU: unregister execve kprobe: 1!" suggest that there might be some issues with loading or unregistering some features.

 "load_allow_list open file failed: -2" suggests that there was a failure while attempting to load an allow list file, with an error code of -2. This could potentially indicate an issue with permissions or file access. 

"KernelSU: unregister vfs_read kprobe: 1!" seem to indicate that the app is unregistering some probes related to VFS read operations.

Do you have any ideas?
