### ISSUE TITLE
Use 255 instead of 337

### ISSUE THREAD

**Issue by PaperStrike** [tiann/KernelSU#400]
In #324, the version check starts using `KERNEL_VERSION(4, 9, 337)`, and from the reverts after the PR merge, it seems to break many 4.9 devices, and it did break my 4.9.337 Pixel 3.

My 4.9.337 Pixel 3 `linux/version.h`:
```cpp
#define LINUX_VERSION_CODE 264703
#define KERNEL_VERSION(a,b,c) (((a) << 16) + ((b) << 8) + (c))
```

The subversion number is only 8 bits, so it should only go up to 255. For some reason `LINUX_VERSION_CODE` follows the rule (`264703 == (4 << 16) + (9 << 8) + 255`) while `KERNEL_VERSION` doesn't. The newer `KERNEL_VERSION` is defined as follows, it seems some 4.9 devices haven't (and probably will never) been updated.
```cpp
#define KERNEL_VERSION(a,b,c) (((a) << 16) + ((b) << 8) + ((c) > 255 ? 255 : (c)))
```

On these 4.9 devices, the relevant conditions are never met, and to adapt, we can safely make changes like:
```diff
- #if LINUX_VERSION_CODE >= KERNEL_VERSION(4, 9, 337)
+ #if LINUX_VERSION_CODE >= KERNEL_VERSION(4, 9, 255)
- #if (LINUX_VERSION_CODE >= KERNEL_VERSION(4, 14, 163)) || ((KERNEL_VERSION(4, 10, 0) > LINUX_VERSION_CODE) && (LINUX_VERSION_CODE  >= KERNEL_VERSION(4, 9, 337)))
+ #if (LINUX_VERSION_CODE >= KERNEL_VERSION(4, 14, 163)) || (LINUX_VERSION_CODE == KERNEL_VERSION(4, 9, 255))
```

**Comment by tiann** [comment]
https://github.com/tiann/KernelSU/issues/280#issuecomment-1449223055

**Comment by PaperStrike** [comment]
> [#280 (comment)](https://github.com/tiann/KernelSU/issues/280#issuecomment-1449223055)

This will not break any others, but satisfy more. The "more" I am saying is the one haven't updated their `KERNEL_VERSION` definition. The ones updated has already been using 255 instead of 337.

**Comment by tiann** [comment]
> > [#280 (comment)](https://github.com/tiann/KernelSU/issues/280#issuecomment-1449223055)
> 
> This will not break any others, but satisfy more. The "more" I am saying is the one haven't updated their `KERNEL_VERSION` definition. The ones updated has already been using 255 instead of 337.

Maybe you're right, but i don't have devices to test. if you confirm that, welcome to make a pr :)
