### ISSUE TITLE
"Unlock CN GMS" Module Not working

### ISSUE THREAD

**Issue by Rakau** [tiann/KernelSU#404]
link：https://github.com/fei-ke/unlock-cn-gms

Models：Xiaomi 13、Redmi K50、Xiaomi Civi

**Comment by natsumerinchan** [comment]
You can try [this one](https://github.com/Howard20181/unlock-cn-gms/tree/ksu).

**Comment by Rakau** [comment]
> You can try [this one](https://github.com/Howard20181/unlock-cn-gms/tree/ksu).

Thanks for the advice, it's working fine
