### ISSUE TITLE
apex分区挂载和默认root

### ISSUE THREAD

**Issue by junknet** [tiann/KernelSU#407]
期望的功能:
1. 挂载其余分区文件，重点是 /apex 分区   (做binary patch的需求)
2. adbd默认提权到root（在kernel层阻止adbd init时的降权）  或者在进程运行中 for_task() 改uid提权其他进程？
3. 官方推出kernelsu的防锁，防砖模块，固化到apk内   比如系统1分钟内开机失败，禁用所有模块  

（抱歉有点忙，后续会参与开发）

**Comment by tiann** [comment]
1. 欢迎 PR。
2. 模块能做的功能不要加到内核，而且 adbd 提到 root 相比 su 有何优势？
3. 内置了安全模式。

综上，我们接受第一个特性，第二个特性在没有足够的理由下不会接受，第三个特性有改进空间。另外，我们没有计划开发你需要的功能，但欢迎你参与开发。
