### ISSUE TITLE
Modules (still) not working

### ISSUE THREAD

**Issue by reocat** [tiann/KernelSU#419]
https://github.com/tiann/KernelSU/issues/377
So I recompiled kernel with fresh sources, but it still the same.
Logs:
[KernelSU_bugreport_2023-04-21_23_09.tar.gz](https://github.com/tiann/KernelSU/files/11298960/KernelSU_bugreport_2023-04-21_23_09.tar.gz)

**Comment by zlm324** [comment]
I have compared reports from old version(10704) and new version(10823), I found a mount point "/data/adb/modules -> /dev/block/loop31" in mounts.txt of old version's report, but not found in new version.

**Comment by tiann** [comment]
For 4.9 kernel, you need this patch: https://github.com/F-19-F/android_kernel_oneplus_msm8998/commit/1042d5601a1c0db08c9a9cea89d1895e74576a27

**Comment by TogoFire** [comment]
https://github.com/tiann/KernelSU/issues/910#issuecomment-1780259797
