### ISSUE TITLE
在WSA上无法正常工作

### ISSUE THREAD

**Issue by HKMV** [tiann/KernelSU#424]
> 1.不显示应用列表，并且应用无法获取root
> 2.无法安装模块

![image](https://user-images.githubusercontent.com/26456469/233787644-3789195c-8560-4360-9016-b702acae7eca.png)
![不显示应用列表，并且应用无法获取root](https://user-images.githubusercontent.com/26456469/233787649-055e0d0d-f077-4956-8bae-9b913b98801f.png)
![image](https://user-images.githubusercontent.com/26456469/233787523-a99ed026-d442-411a-878c-11fe6e67c20a.png)
![无法安装模块](https://user-images.githubusercontent.com/26456469/233787534-4ad7e953-ee1e-4a13-8b3f-1706d1b08f86.png)
[KernelSU_bugreport_2023-04-22_21_13.tar.gz](https://github.com/tiann/KernelSU/files/11301446/KernelSU_bugreport_2023-04-22_21_13.tar.gz)

**Comment by tiann** [comment]
#276
