### ISSUE TITLE
重启后掉root授权

### ISSUE THREAD

**Issue by Arlia-Etoile** [tiann/KernelSU#436]
**Describe the bug**
手机重启后，所有授权过root权限的应用都会掉root权限

**To Reproduce**
1. 打开Kernel SU管理器，授权应用root权限
2. 重启手机
3. 再次打开Kernel SU管理器，发现授权过root权限的应用全都掉权限了

**Expected behavior**
重启后不会掉root权限

**Screenshots**
录屏：https://t.me/WangPanBOT?start=filea89468b3faf8223f

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S20 (SM-G981N/x1q)
 - OS: One UI 5.1 G981NKSU3IWCG (Android 13)
 - Version su版本10818

**Additional context**
日志：https://t.me/WangPanBOT?start=file49b4ae1f65130f13

https://t.me/WangPanBOT?start=file49b4ae1f65130f13

**Comment by tiann** [comment]
关闭所有模块，再操作一遍，发送日志。

**Comment by Arlia-Etoile** [comment]
已关闭所有模块重新操作，依旧掉root权限

https://t.me/WangPanBOT?start=file427db05361c7b546

https://t.me/WangPanBOT?start=filef8a1a085f19a1a7b

**Comment by tiann** [comment]
```
save_allow_list creat file failed: -126
```

**Comment by tiann** [comment]
你的内核虽然是 4.19，但看起来少了一些重要的 commit；-126 这个错误，只应该出现在 4.14 以下的内核上，你可以参考这个  PR 修复：https://github.com/tiann/KernelSU/pull/205

**Comment by Sinclair19** [comment]
[重启前](https://github.com/tiann/KernelSU/files/11470238/KernelSU_bugreport_2023-05-13_13_36.tar.gz)
[重启后](https://github.com/tiann/KernelSU/files/11470239/KernelSU_bugreport_2023-05-13_13_39.tar.gz)
是 4.14 内核
请问也是相同的问题吗，能稍详细一点说说应该怎么解决吗，谢谢

**Comment by privacyguy123** [comment]
There is just "no fix" to this? 🤔
