### ISSUE TITLE
android13-5.10自构建Image开机失败

### ISSUE THREAD

**Issue by junknet** [tiann/KernelSU#440]
AnyKernel3-android13-5.10.107_2022-05.zip 解包出来的Image通过magiskboot修补出来可以正常开机。
由于想参与开发，按照如下命令进行构建，机器是 pixel6：
`repo init -u https://mirrors.tuna.tsinghua.edu.cn/git/AOSP/kernel/manifest/ -b common-android13-5.10-2022-05`
`tools/bazel build --config=fast //common:kernel_aarch64_dist`
使用我自己编译出来的IMAGE再通过magiskboot修补 boot 失败

您是修改了什么配置文件吗

**Comment by tiann** [comment]
没改，参考 CI 编译脚本即可。
