### ISSUE TITLE
momo报发现magisk

### ISSUE THREAD

**Issue by rockxsj** [tiann/KernelSU#445]
我刷了kernelsu后会报发现magisk，但是原来的magisk已经卸载了。

![Screenshot_2023-04-29-20-24-05-336_io.github.vvb2060.mahoshojo.jpg](https://user-images.githubusercontent.com/3021207/235302477-b9ccb244-8cac-47e3-8743-5dec9e985077.jpg)

**Comment by tiann** [comment]
过 momo 检测现在以及未来都不是 KernelSU 的目标，请以实际使用的金融银行类 App 能否使用作为标准检测。

**Comment by rockxsj** [comment]
> 过 momo 检测现在以及未来都不是 KernelSU 的目标，请以实际使用的金融银行类 App 能否使用作为标准检测。

金融类app都没问题，但是学习强国助手会触发验证码，所以才做的检测
