### ISSUE TITLE
移植到4.19版本内核后可以正常开机但是显示 “不支持，KernelSU现在只支持GKI内核”

### ISSUE THREAD

**Issue by Kalansas** [tiann/KernelSU#460]
通过B站FlashCorpa大佬的教程，以UtsavBalar1231 的 kernel_xiaomi_sm8250 (https://github.com/UtsavBalar1231/kernel_xiaomi_sm8250) 的内核源码为基础做了移植，手机可以正常开机，但是安装了KernelSU APP后却显示 “不支持，KernelSU现在只支持GKI内核”，请问这种情况是没有移植成功吗还是得下老版本的APP才能正常使用呢？
手机型号：小米 10S （thyme） 8+256GB
MIUI版本：14.0.4 稳定版
Android版本：13
CPU：高通骁龙 870
内核版本：4.19.157-perf-gd54161f94f80

**Comment by tiann** [comment]
没成功
