### ISSUE TITLE
WSA无法正常工作

### ISSUE THREAD

**Issue by ttt5262** [tiann/KernelSU#464]
![屏幕截图 2023-05-05 214833](https://user-images.githubusercontent.com/29058831/236476488-86be41cb-cf97-4f94-a4ee-bcd8a5dd1431.png)
![屏幕截图 2023-05-05 214847](https://user-images.githubusercontent.com/29058831/236476512-1d4ab8d8-21c5-4e01-a5e3-fe2f7a9d4ace.png)
![屏幕截图 2023-05-05 214858](https://user-images.githubusercontent.com/29058831/236476531-c192a011-6439-41f4-9471-b753b19697d2.png)
日志：
[KernelSU_bugreport_2023-05-05_21_42.tar (1).gz](https://github.com/tiann/KernelSU/files/11406865/KernelSU_bugreport_2023-05-05_21_42.tar.1.gz)

**Comment by tiann** [comment]
https://github.com/tiann/KernelSU/commit/72ee14e6bee59452e301be7c4954442b529178c6
