### ISSUE TITLE
4.19内核仍然无法编译出可以让KernelSU识别的镜像

### ISSUE THREAD

**Issue by Kalansas** [tiann/KernelSU#465]
通过B站FlashCorpa大佬的教程，以UtsavBalar1231 的 kernel_xiaomi_sm8250 (https://github.com/UtsavBalar1231/kernel_xiaomi_sm8250) 的内核源码为基础做了移植，手机可以正常开机，但是安装了KernelSU APP后却显示 “不支持，KernelSU现在只支持GKI内核”，请问这种情况是没有移植成功吗还是得下老版本的APP才能正常使用呢？
手机型号：小米 10S （thyme） 8+256GB
MIUI版本：14.0.4 稳定版
Android版本：13
CPU：高通骁龙 870
内核版本：4.19.157-perf-gd54161f94f80

**Update，2023.5.6**

按照KernelSU官网的指引在 make menuconfig 里开启了所有与KPROBES相关的依赖，编译出dtbo.img文件（约440KB），将此文件丢入Anykernel3.zip里并按自己手机的实际情况修改了脚本参数然后刷入，可以正常开机，但还是不成功，KernelSU APP依然不识别，请问是哪里还有问题？
编译平台：WSL2
系统：Ubuntu-22.04（编译时已加上--patch=glibc参数）

**Comment by tiann** [comment]
你要把编译出来的 kernel image 刷进去，不是 dtbo。

**Comment by Kalansas** [comment]
好的谢谢，请问kernel image的路径在哪里，我在/out文件夹里没有找到除了dtbo.img以外的其他img文件了

**Comment by tiann** [comment]
建议你先看下自定义内核相关的教程。

**Comment by Kalansas** [comment]
好的，有什么推荐吗？

**Comment by 837468220** [comment]
请问 现在识别了没 @Kalansas

**Comment by Separatee** [comment]
使用`make help` 
向上翻找看看是否显示了Image-gz的编译选项
![Screenshot_2024-07-17-18-37-22-817_com termux](https://github.com/user-attachments/assets/4132ee6e-00be-4b12-9b64-7bcbd3e2b5f2)

这是我在手机上编译的内核
