### ISSUE TITLE
REPLACE in customize.sh is not replaced

### ISSUE THREAD

**Issue by fei-ke** [tiann/KernelSU#466]
**Describe the bug**
`REPLACE` in customize.sh is not get replaced

Following the documentation example, declare a `REPLACE` in customize.sh 

```sh
REPLACE ="
/system/app/YouTube
/system/app/Bloatware
"
```
After installing and rebooting, these directories were not replaced.

Seem this code did not get the correct path 

https://github.com/tiann/KernelSU/blob/9caf4402007d00215cd14e6515c0751a15837812/userspace/ksud/src/installer.sh#L280-L281

if it ends with a slash, the directory will get replaced.

```sh
REPLACE ="
/system/app/YouTube/
/system/app/Bloatware/
"
```

**Expected behavior**
Each directory in `REPLACE` get replaced

**Screenshots**
<img  width="480" src="https://user-images.githubusercontent.com/2138570/236657814-a3df96d4-c895-4588-9569-2dcb688419f0.png" />

**Smartphone (please complete the following information):**
 - Device: Samsung S23U (SM-S9180)
 - OS:  Android 13, OneUI 5.1 
 - Version KernelSU version: 10847,  Manager version:v0.5.5 (10818)

**Additional context**

**Comment by tiann** [comment]
Does this work?

```
REPLACE ="
/system/app/YouTube
/system/app/Bloatware
"
```

**Comment by Ylarod** [comment]
Try
```
REPLACE="
/system/app/YouTube
/system/app/Bloatware
"
```

the space should not exist between `REPLACE` and `=`
