### ISSUE TITLE
编译错误，5.15内核，clang14.0.0

### ISSUE THREAD

**Issue by iiowoii3389** [tiann/KernelSU#468]
CC      drivers/kernelsu/ksu.o
  CC      drivers/kernelsu/allowlist.o
  CC      drivers/kernelsu/apk_sign.o
  CC      drivers/kernelsu/module_api.o
  CC      drivers/kernelsu/sucompat.o
  CC      drivers/kernelsu/uid_observer.o
  CC      drivers/kernelsu/manager.o
  CC      drivers/kernelsu/core_hook.o
  CC      drivers/kernelsu/ksud.o
../drivers/kernelsu/ksud.c:81:9: error: unknown type name 'compat_uptr_t'
                const compat_uptr_t __user *compat;
                      ^
../drivers/kernelsu/ksud.c:92:3: error: use of undeclared identifier 'compat_uptr_t'
                compat_uptr_t compat;
                ^
../drivers/kernelsu/ksud.c:94:16: error: use of undeclared identifier 'compat'
                if (get_user(compat, argv.ptr.compat + nr))
                             ^
../drivers/kernelsu/ksud.c:97:21: error: use of undeclared identifier 'compat'
                return compat_ptr(compat);
                                  ^
4 errors generated.
make[3]: *** [../scripts/Makefile.build:287：drivers/kernelsu/ksud.o] 错误 1
make[3]: *** 正在等待未完成的任务....
make[2]: *** [../scripts/Makefile.build:549：drivers/kernelsu] 错误 2
make[2]: *** 正在等待未完成的任务....

**Comment by tiann** [comment]
拉一下 KernelSU main分支最新的代码再试下。
