### ISSUE TITLE
Request Feature For module.prop `updateJson`

### ISSUE THREAD

**Issue by Dawnnnnnn** [tiann/KernelSU#469]
**Is your feature request related to a problem? Please describe.**
Modules developed by developers cannot be updated online through the manager

**Describe the solution you'd like**
Like Magisk Manager, it supports defining updateJson field in module.prop, so that users can receive updates pushed by developers based on remote url

**Describe alternatives you've considered**
I think this is a proven official update solution for the module and there is no better alternative

**Additional context**

**Comment by symbuzzer** [comment]
@tiann 
I develop and use daily updated modules. For this reason, the module update feature is very important for me and my user group. I've been using KernelSU for a while and I'm very satisfied. Thank you very much to everyone who contributed. But if the update feature of the modules does not come soon, we will have to reluctantly return to Magisk. So I want to ask; Is this feature planned to be developed in the near future?

**Comment by tiann** [comment]
Maybe this or next weekend.

**Comment by tiann** [comment]
https://github.com/tiann/KernelSU/commit/07273b697181bb2e7d2ab6481b5da6657f018379
