### ISSUE TITLE
你好，我编译成功了，可是新的内核名字，包含KernelSu的字样，如何防检测

### ISSUE THREAD

**Issue by tytnp** [tiann/KernelSU#477]
你好，我编译成功了，可是新的内核名字，包含KernelSu的字样。如下图:

![image](https://github.com/tiann/KernelSU/assets/30230436/a718b64b-0c3b-4b9c-8303-bd995944413f)

这个会有检测特征吧，如何把这个字样去掉。

**Comment by tytnp** [comment]
这个我有办法去掉吗，内核源码在我手里，只是我不熟悉

**Comment by Coconutat** [comment]
> 这个我有办法去掉吗，内核源码在我手里，只是我不熟悉

检查defconfig 里面CONFIG_LOCALVERSION是否填写了内容。如果编译用脚本检查脚本里有没有定义相关内容。或者检查AnyKernel3里的脚本。

**Comment by hyx0329** [comment]
最近也遇到这个问题，发现根源了。以Linux 4.14为例，`scripts/setlocalversion`会查找内核源码文件夹内的所有`.git`文件夹（搜索子项目，具体见`scm_version`这个函数），把所有检测到的子项目文件夹名称以`_$name`形式拼接。

所以要避免出现`KernelSU`字样的话，需要自己稍微修改一下自动脚本做的改动，又或者hack一下setlocalversion。检查当前配置下内核的version string请用`make kernelrelease`。

不过仔细看函数的话，也有一个最简单的方法：`touch .scmversion`，创建一个空文件，这个文件的内容会取代自动检测的内容。
