### ISSUE TITLE
Cchange the kernel source code support device 

### ISSUE THREAD

**Issue by dabao1955** [tiann/KernelSU#478]
I want to change the source code support device I maintain from `OPPO Reno6` to `MediaTek devices in the OPPO Reno series on ColorOS13.x`

**Comment by tiann** [comment]
Just modify yourself and open a PR.

**Comment by dabao1955** [comment]
> Just modify yourself and open a PR.

I'm not a developer, and submitting a PR may only cause me or you trouble.
