### ISSUE TITLE
Crash of the phone

### ISSUE THREAD

**Issue by kilam8900** [tiann/KernelSU#487]
**Describe the bug**
So basically, when I simply launch the app, the phone crash for the reason BUT show a text for a demi second, the same as for when I install [OverlayFS](https://github.com/Magisk-Modules-Alt-Repo/magisk_overlayfs)

**To Reproduce**
1. Install the specific kernel
2. Launch the app
3. Let your phone crash

**Smartphone (please complete the following information):**
 - Device: SM-A325F
 - OS: Android 11
 - Version: 0.5.5

**Additional context**
It's a non GKI device. If you can help me the fix the code, we could add it to unofficial device. Thank you in advance

**Comment by tiann** [comment]
No log no fix

**Comment by kilam8900** [comment]
> No log no fix

Uh, sorry my bad, you want what log? Kernel log?
