### ISSUE TITLE
Crash when opening the app

### ISSUE THREAD

**Issue by kilam8900** [tiann/KernelSU#488]
**Describe the bug**
So basically, when I simply launch the app, the phone crash for the reason BUT show a text for a demi second, the same as for when I install [OverlayFS](https://github.com/Magisk-Modules-Alt-Repo/magisk_overlayfs). On the message is attached the logs (ramoops, logcat while crashing and dmesg, ask me if you need more ofc)

**To Reproduce**
1. Install the specific kernel
2. Launch the app
3. Let your phone crash

**Smartphone (please complete the following information):**
 - Device: SM-A325F
 - OS: Android 11
 - Version: 0.5.5

**Additional context**
It's a non GKI device. If
 you can help me the fix the code, we could add it to unofficial device. Thank you in advance

[logs.tar.gz](https://github.com/tiann/KernelSU/files/11468551/logs.tar.gz)

**Comment by kilam8900** [comment]
![image](https://github.com/tiann/KernelSU/assets/97908231/75d6b1f8-f9cc-4373-949b-c8785c28a566)
If it can help, I noticed that in all the cat logs that I took, it crashes a little close to this point

**Comment by kilam8900** [comment]
Also, here the logs from the app, unfortunately I need the uninstall the patched kernel to access the app but maybe it can help
[KernelSU_bugreport_2023-05-13_03_32.tar.gz](https://github.com/tiann/KernelSU/files/11468606/KernelSU_bugreport_2023-05-13_03_32.tar.gz)

**Comment by tiann** [comment]
Please check this. https://github.com/tiann/KernelSU/issues/260

**Comment by tiann** [comment]
https://github.com/tiann/KernelSU/issues/263

**Comment by kilam8900** [comment]
I'll check

**Comment by kilam8900** [comment]
The app dont make the phone crash, but I cant install module it says that overlayFS is not there and when I do su in thermux, it says that the command su is not found. Do you need logs?

**Comment by kilam8900** [comment]
Its like #263 but i did remove the configs, so here's my logs
[KernelSU_bugreport_2023-05-13_15_06.tar.gz](https://github.com/tiann/KernelSU/files/11469734/KernelSU_bugreport_2023-05-13_15_06.tar.gz)

**Comment by kilam8900** [comment]
I had a bit of a chat with another developer who had also worked on KernelSU and we think that KernelSU would only work with the brand new SM-A325F (A13) kernels. Is that possible?

**Comment by tiann** [comment]
You should check your kernel source and ensure KDP and RKP is not working.
