### ISSUE TITLE
Some apps (e.g. Root Explorer or Advanced Tools Pro) can't list folders of other apps in /data/data or /data/user/0

### ISSUE THREAD

**Issue by Hikari-no-Tenshi** [tiann/KernelSU#492]
**Describe the bug**
Some apps (e.g. Root Explorer or Advanced Tools Pro) can't list folders of other apps in /data/data or /data/user/0.

**To Reproduce**
1. Allow root for Root Explorer.
2. Launch Root Explorer.
3. Go to /data/data or /data/user/0.
4. See that Root Explorer can't list folders of other apps.

**Expected behavior**
Root Explorer should see folders of other apps in /data/data or /data/user/0.

**Screenshots**
I think not needed.

**Smartphone (please complete the following information):**
 - Device: OnePlus 7 (guacamoleb).
 - OS: crDroid based on Android 11.

I know that problem is in namespace and some filemanagers like MiXplorer fixed that issue, but i used to use Root Explorer and would like to see it working, if that can be done from KernelSU side.

**Comment by tiann** [comment]
No log no fix.
