### ISSUE TITLE
Insmod method

### ISSUE THREAD

**Issue by Jin1423** [tiann/KernelSU#496]
Please, make Insmod, or Kmod patch build for magisk.
I have 2 devices, Black Shark 5 pro, Black Shark 5 on 5.10.43, all anykernels breaks my gaming features totally. Triggers, 720hz touch, some also breaks mobile data and black sharks are closed kernel, also the kernel is not default build state. My own kernel GKI2 remake is really far from release.
I saw you closed issue with such request,  i also have Black Shark 4 with 4.19 kernel. My friend, for such good value devices Kmod or Insmod would be decent solution, it shouldn't be hard to make.

**Comment by tiann** [comment]
> it shouldn't be hard to make

So please made it yourself.
