### ISSUE TITLE
小米9 内核4.14通过使用 kprobe 集成，app正常工作，shell 使用su 提示 /system/bin/su: No such file or directory

### ISSUE THREAD

**Issue by wang-weart** [tiann/KernelSU#502]
![Screenshot_20230514-231434_KernelSU](https://github.com/tiann/KernelSU/assets/37867145/95c9b810-8db9-487d-969f-8a1d0fcf29ec)
![Screenshot_20230514-231421_KernelSU](https://github.com/tiann/KernelSU/assets/37867145/05f8c5d4-b091-4d03-a490-22c787da3130)
![Snipaste_2023-05-16_13-45-33](https://github.com/tiann/KernelSU/assets/37867145/20cedf30-2ec9-42ef-b7f8-9a09213d61f0)
内核源码地址 https://github.com/PixelExperience-Devices/kernel_xiaomi_cepheus 分支13
log 文件 中发现一段这个日志
[    0.569519] KernelSU: ksu_lsm_hook_init
[    0.570132] i2c_geni 890000.i2c: i2c error :-107
[    0.570245] i2c_geni 890000.i2c: i2c error :-107
[    0.570248] idtp9220 0-003b: vout regulator get vol: 0
[    0.587522] KernelSU: sucompat: execve_kp: -2
[    0.588473] KernelSU: sucompat: newfstatat_kp: 0
[    0.589370] KernelSU: sucompat: faccessat_kp: 0
[    0.606246] KernelSU: : -2
[    0.607015] KernelSU: ksud: vfs_read_kp: 0
[    0.610245] KernelSU: ksud: input_handle_event_kp: 0
是因为kprobe 导致的吗? 
[KernelSU_bugreport_2023-05-14_18_59.tar.gz](https://github.com/tiann/KernelSU/files/11484408/KernelSU_bugreport_2023-05-14_18_59.tar.gz)

**Comment by wang-weart** [comment]
已解决

**Comment by Minxin** [comment]
求教，授权给其他app root权限正常，授权给com.android.shell，执行su时提示[/system/bin/su: No such file or directory]

**Comment by NitroGear504** [comment]
> 已解决

How do you solved it ?

**Comment by wang-weart** [comment]
> > 已解决
> 
> How do you solved it ?

不要使用kprobe 集成，使用修改源码方式集成

**Comment by NitroGear504** [comment]
> > > 已解决
> > 
> > 
> > How do you solved it ?
> 
> 不要使用kprobe 集成，使用修改源码方式集成

Can you explain your steps to solve this
