### ISSUE TITLE
ksu下zram writeback失效

### ISSUE THREAD

**Issue by STTecCEO** [tiann/KernelSU#514]
**Describe the bug**
在ksu下zram writeback失效
同内核使用magisk时正常

**To Reproduce**
已挂载回写块
使用
echo all > /sys/block/zram0/idle
和
echo idle > /sys/block/zram0/writeback 后
不会回写内容
cat /sys/block/zram0/bd_stat 
/内容未变化表示未触发writeback
以上操作在magisk环境下正常运行

(同时发现ksu占用了一个loop36且没有映射 这个是正常情况吗
```
$ su
:/data/data/com.termux/files/home # cat /sys/block/zram0/bd_stat
       1        0        0
:/data/data/com.termux/files/home # echo all > /sys/block/zram0/idle
:/data/data/com.termux/files/home # echo idle > /sys/block/zram0/writeback
1|:/data/data/com.termux/files/home # cat /sys/block/zram0/bd_stat
       1        0        0
:/data/data/com.termux/files/home #
:/data/data/com.termux/files/home #
:/data/data/com.termux/files/home # losetup -a
/dev/block/loop37: [64804]:1464002 (/data/writeback)
/dev/block/loop36: [64804]:1468183 ()
/dev/block/loop35: [64804]:788379 (), offset 4096, sizelimit 3010560
/dev/block/loop34: [64804]:789857 (), offset 8192, sizelimit 3538944
/dev/block/loop33: [64804]:1665325 (), offset 8192, sizelimit 1716224
``` 

**Expected behavior**
zram正常回写

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: sony xperia 1Ⅲ
 - OS: 13
 - ksu-10991

**Comment by Coconutat** [comment]
我的是安卓9的系统但是无法挂载/product

**Comment by Hb199806** [comment]
+1 请问如何调用Kernel自带的overlayFS读写system分区

**Comment by STTecCEO** [comment]
10964已修复
![Screenshot_20230605-130005](https://github.com/tiann/KernelSU/assets/35169436/f036a5ff-a5a3-409d-8030-231a74b2eb00)

**Comment by STTecCEO** [comment]
玄学能用 重新开启一次后再次失效…

**Comment by tiann** [comment]
你说的 “已挂载回写块”步骤是什么

**Comment by STTecCEO** [comment]
> 你说的 “已挂载回写块”步骤是什么
```
#/data下创建一个3g的文件
dd if=/dev/zero of=/data/writeback bs=1M count=3072

#查看可用的loop
losetup -f
回显 /dev/block/loop37

#挂载过去
losetup /dev/block/loop37 /data/writeback

#关闭zram后执行以下命令，再重启zram
echo /dev/block/loop37 > /sys/block/zram0/backing_dev
```

**Comment by tiann** [comment]
你试试在 su -mm 下执行这些呢？

**Comment by STTecCEO** [comment]
> 
还是没有效果
![Screenshot_20230625-231216](https://github.com/tiann/KernelSU/assets/35169436/547c466a-0fc7-4b4f-a7c1-ce67e685b133)

**Comment by tiann** [comment]
挂载回写块 也用 su -mm 呢？

**Comment by STTecCEO** [comment]
> 你试试在 su -mm 下执行这些呢？
依然是没有反应
![Screenshot_20230626-000820](https://github.com/tiann/KernelSU/assets/35169436/1aa669db-9338-4b4a-8717-c2b24e977189)

**Comment by tiann** [comment]
如果你同时安装 KernelSU 和 Magisk，分别用它们各自的 su 试一下会是什么结果？

**Comment by STTecCEO** [comment]
试了一下，二者共存的时候所有模块被禁用，ksu也没有挂载loop
先用ksu的su跑了一遍，没有问题
magisk跑也正常
![Screenshot_20230626-124740](https://github.com/tiann/KernelSU/assets/35169436/69149af9-e13c-4ffe-bd5a-0de1152128ba)

**Comment by tiann** [comment]
那你只刷 KernelSU，并且手动**删掉** `/data/adb/ksu` 目录试试能行么？

**Comment by tiann** [comment]
你试试 `setenforce 0` 后操作呢？

**Comment by tiann** [comment]
`echo idle > /sys/block/zram0/writeback` 这一步报错了
