### ISSUE TITLE
kernelSU 模块页面不显示模块

### ISSUE THREAD

**Issue by echspan** [tiann/KernelSU#525]
![Screenshot_2023-05-17-21-51-47-400_me weishu kernelsu](https://github.com/tiann/KernelSU/assets/88482848/f670f0c8-1451-4b27-be4e-a2c87f9c0ff2)
![mmexport1684331565108](https://github.com/tiann/KernelSU/assets/88482848/325e75da-fb0c-4329-92c2-69ac0fdc9b03)

设备：redmi note 12turbo
（miui14.0.19）

KernelSU版本0.5.7

**Comment by echspan** [comment]
模块正常运行，
模块安装正常，
无法从KernelSU删除模块

KernelSU模块页面不显示模块

**Comment by tiann** [comment]
请提供日志
