### ISSUE TITLE
Mounting issue with Magisk modules

### ISSUE THREAD

**Issue by Theo-user** [tiann/KernelSU#527]
**Describe the bug**
Error installing YouTube Magisk module.

**To Reproduce**
Uninstall all traces of YouTube and flash the module.

**Expected behavior**
Sucesfully install the Module.

**Screenshots**
![Screenshot_20230518-022835_KernelSU](https://github.com/tiann/KernelSU/assets/75871295/a4dfe1fd-020c-42a6-ae9f-e700df937659)

**Smartphone (please complete the following information):**

Poco F3
Crdroid 8.14
KSU 0.5.7
No Gravity Kernel.
No Magisk installed.

https://github.com/cuynu/ytvanced/releases/download/18.02.33/YouTube.Vanced.v18.02.33_Black_MagiskModule.zip

**Comment by tiann** [comment]
Please install version 0.6 and try it again.

**Comment by fengyuecanzhu** [comment]
> Please install version 0.6 and try it again.

The same issue in version 0.6.

![Screenshot_2023-06-14-07-34-14-145_me weishu kernelsu-edit](https://github.com/tiann/KernelSU/assets/61369261/0092c29e-5580-438b-9aac-64172d19c47a)
![Screenshot_2023-06-14-07-33-58-978_me weishu kernelsu-edit](https://github.com/tiann/KernelSU/assets/61369261/07ccd9e9-41c5-4b4b-a7b9-4ba44073f1cd)

**Comment by tiann** [comment]
I think this is a module issue: "warning: Only can run on Android 12"

**Comment by fengyuecanzhu** [comment]
> I think this is a module issue: "warning: Only can run on Android 12"

The warning is unrelated. It is only meant to indicate that the Monet theme installation package can only be used for Android 12 and above (my device is Android 13). 

Even if I use the normal theme package, the same issue occurs.

![Screenshot_2023-06-14-11-12-34-420_me weishu kernelsu-edit](https://github.com/tiann/KernelSU/assets/61369261/5107b69c-a166-41ae-a4ff-436412406071)

**Comment by tiann** [comment]
It is a module issue, `ln -f` failed and it just ignore it.

**Comment by tiann** [comment]
Modify `ln -f` to `ln -sf` and it should work.

**Comment by fengyuecanzhu** [comment]
> Modify `ln -f` to `ln -sf` and it should work.

Oh, thank you very much for taking your time, it works now.

**Comment by Theo-user** [comment]
Same issue with the very latest version.

![Screenshot_20230625-093749_KernelSU](https://github.com/tiann/KernelSU/assets/75871295/55c1ea9c-175f-4ff1-b10f-365d6527ac58)

**Comment by Theo-user** [comment]
> Modify `ln -f` to `ln -sf` and it should work.

This worked for me but when I reboot youtube is back to base.

**Comment by fengyuecanzhu** [comment]
> > Modify `ln -f` to `ln -sf` and it should work.
> 
> This worked for me but when I reboot youtube is back to base.

Just modify the same line in the service.sh file.

**Comment by Theo-user** [comment]
Thanks. All good now.
