### ISSUE TITLE
New userspace su have argument parse problem

### ISSUE THREAD

**Issue by frknkrc44** [tiann/KernelSU#530]
**Describe the bug**
The new userspace su solution continues to parse arguments after -c

**To Reproduce**
1. Compile a kernel with latest KernelSU
2. Open any terminal
3. type `su -c logcat -v long`

**Expected behavior**
The userspace su shouldn't parse arguments after -c

**Screenshots**
![Screenshot_20230519-150048_Termux](https://github.com/tiann/KernelSU/assets/45714956/fc9b9919-f94e-402d-a4d0-280d6e947208)

**Smartphone (please complete the following information):**
 - Device: Oneplus 9
 - OS: Android 13 QPR2, LineageOS 20
 - Version: Kernel 10889, ksud 0.5.7

**Additional context**

**Comment by ascorbic-acid** [comment]
hello any updates on this, i got the same problem, for example
works: **su -c ls** 
not work: **su -c ls -ahl**

**Comment by tiann** [comment]
It is a known issue, we will fix it soon.
