### ISSUE TITLE
Remove the code for detecting the KSU git version

### ISSUE THREAD

**Issue by dabao1955** [tiann/KernelSU#544]
As asked, when I was removing the git folder under the kernelSU folder, it encountered an error while compiling. It compiles normally when not removed.

In file included from /home/synaptic/android_kernel_oppo_sdm660/drivers/
/home/synaptic/android_kernel_oppo_sdm660/drivers/kernelsu/uid_observer.c:12:0:
/drivers/kernelsu/ksu.h:7:2: warning: #warning "KSU_GIT_VERSION not defined! It is better to make KernelSU a git submodule!" [-Wcpp]
error, forbidden warning: ksu.h:7
make[3]: *** [/home/synaptic/android_kernel_oppo_sdm660/scripts/Makefile.build:282: drivers/kernelsu/uid_observer.o] Error 1

**Comment by tiann** [comment]
Expected behavior.

**Comment by dabao1955** [comment]
> Expected behavior.

**Comment by dabao1955** [comment]
> Expected behavior.

Why do you want to do this?

**Comment by tiann** [comment]
Kernel version code is derived from git.
