### ISSUE TITLE
[提问] 手机已经安装好kernelSU，如何在adb环境下获取root权限？

### ISSUE THREAD

**Issue by dupc23** [tiann/KernelSU#547]
![image](https://github.com/tiann/KernelSU/assets/42033765/a054fd3e-9f4d-4192-b808-d580623ce9c6)
手机上kernelSU设置完好，root可以正常使用，在pc上用adb连接手机，执行su，无法提权。
有知道的老哥吗？这个该怎么弄

**Comment by tiann** [comment]
超级用户授权中，允许 “com.android.shell"

**Comment by dupc23** [comment]
> 超级用户授权中，允许“com.android.shell”

感谢老哥

**Comment by CleMooling** [comment]
> 超级用户授权中，允许 “com.android.shell"

允许后有命令仍然无法正常使用：
[mooling@mooling-laptop ~]$ adb pull /system/build.prop
adb: error: failed to copy '/system/build.prop' to './build.prop': remote open failed: Permission denied

**Comment by androiddisk** [comment]
> > 超级用户授权中，允许 “com.android.shell"
> 
> 允许后有命令仍然无法正常使用： [mooling@mooling-laptop ~]$ adb pull /system/build.prop adb: error: failed to copy '/system/build.prop' to './build.prop': remote open failed: Permission denied

adb shell    然后 su -c cp /system/build.prop /sdcard/build.prop 然后 adb pull /sdcard/build.prop
