### ISSUE TITLE
低版本内核kernelsu编译失败

### ISSUE THREAD

**Issue by bsy1** [tiann/KernelSU#554]
我希望在nova2plus中编译kernelsu，但编译器返回如下error：
`BAC-AL00-TL00_NG_EMUI5.1_opensource/kernel/include/linux/lsm_hook_defs.h:312:3: error: unknown type name 'sockptr_t'
   sockptr_t optval, sockptr_t optlen, unsigned int len)
   ^`
`BAC-AL00-TL00_NG_EMUI5.1_opensource/kernel/include/linux/lsm_hooks.h:53:3: error: conflicting types for '__randomize_layout'
 } __randomize_layout;
   ^`
怎么处理？

**Comment by bsy1** [comment]
我保证我没有打开除kernelsu的任何功能。

**Comment by tiann** [comment]
#555
