### ISSUE TITLE
Kernel su compilation failed in the lower kernel

### ISSUE THREAD

**Issue by bsy1** [tiann/KernelSU#555]
I want to compile kernelsu in nova2plus, but the compiler returns an error like this:
`BAC-AL00-TL00_NG_EMUI5.1_opensource/kernel/include/linux/lsm_hook_defs.h:312:3: error: unknown type name 'sockptr_t' sockptr_t optval, sockptr_t optlen, unsigned int len) ^
BAC-AL00-TL00_NG_EMUI5.1_opensource/kernel/include/linux/lsm_hooks.h:53:3: error: conflicting types for '__randomize_layout' } __randomize_layout; ^`
How to deal with it?
I guarantee I didn't turn on any features other than kernelsu.

**Comment by tiann** [comment]
It is nothing to do with KernelSU.
