### ISSUE TITLE
安装System false encryption模块后丢失所有app数据

### ISSUE THREAD

**Issue by Xuefeng-H** [tiann/KernelSU#566]
**Describe the bug**
通过kernelSU管理器安装System false encryption模块后，重启手机后会丢失所有软件的数据，包括各种app的登录状态、桌面壁纸及图标排布、相册的照片和图片等。

**To Reproduce**
1. 在kernelSU管理器中安装System false encryption模块；
2. 重启手机，输入锁屏密码；
3. 出现一个转圈的加载图标，几秒后手机自动重启至recovery模式；
4. 再次重启后，手机正常开机，但所有app数据已被清除。

**Expected behavior**
用magisk安装此模块则不会触发此bug。

**Screenshots**
![S30531-08222483_me weishu kernelsu](https://github.com/tiann/KernelSU/assets/57562438/5492f952-7b09-4e1a-be56-f3df84894f2e)

**Smartphone (please complete the following information):**
 - Device: [Redmi Note 12 Turbo]
 - OS: [Flyme 10.23.5.8 daily]
 - Version [Android 13]

**Additional context**

**Comment by tiann** [comment]
no log no fix.
