### ISSUE TITLE
如何安装系统根证书

### ISSUE THREAD

**Issue by kingz40o** [tiann/KernelSU#568]
当我向/system/etc/security/cacerts/写入根证书时，'KSU' is read-only，有什么方法或者插件吗

**Comment by neoshui** [comment]
> 当我向/system/etc/security/cacerts/写入根证书时，'KSU' is read-only，有什么方法或者插件吗

你好，写入系统证书可以正常工作吗？我遇到一个问题，请你帮我解答一下，我做好模块，写入证书后，在设置内的加密与凭证中看不到添加的证书。

**Comment by ahmad24shargh** [comment]
Create very simple module:

Create a file called module.prop with contents similar to the following:

```
id=MyCertMod
name=MyCertMod
author=JohnSmith
version=v0.0.0
versionCode=00000
description=Add Adguard Ca Certificate to System Cert at boot stage systemlessly!
```

Now create the required directory structure:

system>etc>security>cacerts

and put the certificate file in it.
Zip the created folder and text file and install it in kernelsu manager.
