### ISSUE TITLE
Some games not working (at least pubgm and standoff 2)

### ISSUE THREAD

**Issue by kitelqmaf** [tiann/KernelSU#571]
Android 13. Ive tried to run pubg mobile and standoff 2 on AlphaDroid and on NusantaraRom both roms was clear and in both roms i got exactly same error. 
Pubg says that it needs storage permission, but after giving it nothing changes.
![Screenshot_20230601-065014_PUBG_MOBILE 1](https://github.com/tiann/KernelSU/assets/81971965/d78aa8ea-1cf6-4981-8286-78312cc69853). Standoff 2 is starts for a second and then instantly blacks out.
I had nusantara rom before and everything worked just fine.

**Comment by tiann** [comment]
It is nothing to do with KernelSU.

**Comment by kitelqmaf** [comment]
nah, as only i installed other kernel it started working just fine.
