### ISSUE TITLE
修完了旧bug又来了新bug：非零用户和主用户同一应用root不能共存

### ISSUE THREAD

**Issue by chen2021-web** [tiann/KernelSU#583]
**Describe the bug**
如题
**To Reproduce**
1. 给主用户的一个应用root，此时主用户的应用的root可以正常调用
2. 给同一应用但不同用户的应用root
3. 然后你就可以发现主用户的应用无法调用root，但你授予的另一个用户的应用就可以了
4. 此操作反过来成立

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [redmi note 9/redmi note 9T]
 - OS: [lineage20]
 - Version [管理器和内核皆为10942]

**Additional context**

**Comment by chen2021-web** [comment]
这是log：
[KernelSU_bugreport_2023-06-04_11_46.tar.gz](https://github.com/tiann/KernelSU/files/11644848/KernelSU_bugreport_2023-06-04_11_46.tar.gz)

**Comment by tiann** [comment]
try this: https://github.com/tiann/KernelSU/commit/8af5a9038bfff4dc99506a897699e7f79add027b

**Comment by chen2021-web** [comment]
ok了

**Comment by chen2021-web** [comment]
旧bug解决了但新bug又来了

**Comment by chen2021-web** [comment]
非零用户应用重启后丢失root

**Comment by chen2021-web** [comment]
这是日志：
[KernelSU_bugreport_2023-06-04_15_39.tar.gz](https://github.com/tiann/KernelSU/files/11645111/KernelSU_bugreport_2023-06-04_15_39.tar.gz)
