### ISSUE TITLE
非零用户应用重启后丢失root

### ISSUE THREAD

**Issue by chen2021-web** [tiann/KernelSU#587]
**Describe the bug**
如题
**To Reproduce**
1. 给一个非零应用root
2. 重启
3. 然后你就会发现这个非零应用的授权没了

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [redmi note 9/redmi note 9T]
 - OS: [lineage20]
 - Version [管理器和内核都是10948]

**Additional context**
日志：
[KernelSU_bugreport_2023-06-04_17_25.tar.gz](https://github.com/tiann/KernelSU/files/11645267/KernelSU_bugreport_2023-06-04_17_25.tar.gz)

**Comment by wu17481748** [comment]
联想手机也遇到过这情况换了app和ksu版本依旧如此
