### ISSUE TITLE
AnyKernel3 zips fixes

### ISSUE THREAD

**Issue by osm0sis** [tiann/KernelSU#588]
Hey! I was just checked out the AK3 zips you bundle in your Releases (woo!), and noticed they're technically broken for init_boot right now, since you set `block=boot`, but init_boot is now separate (as of ~November).

Simple fix though! Simply change it to `block=auto` in your setup in anykernel.sh, which makes it look for init_boot then fall back to boot, and then you could also use the $block value instead of the later if-then logic, e.g.

```
case $block in
  *init_boot*) ;;
  *) ;;
esac
```

I recommend updating to the latest AK3 backend as well since there were some importance fixes and a newer, better busybox last month.

Feel free to use my SELinux busybox instead of Magisk's elsewhere in the main project too: https://github.com/Magisk-Modules-Repo/busybox-ndk

Anyway keep up the great work! 😁👍

**Comment by tiann** [comment]
1. KernelSU will only modify the boot partition as the kernel resides there. Would setting it to boot cause any other issues?
2. Thank you for the reminder. I will update AK3 to the latest version.
3. Using Magisk's Busybox is to maintain compatibility with it. Would there be any issues after switching?

Also, thank you for creating AK3. It is very useful!

**Comment by osm0sis** [comment]
Ahhh of course, okay you were right to leave it as `block=boot`

The SELinux busybox should be relatively the same, just mine updates more quickly, as both are made with my patches using the ndk-box-kitchen.
