### ISSUE TITLE
Custom profile bugs

### ISSUE THREAD

**Issue by Hikari-no-Tenshi** [tiann/KernelSU#592]
**Describe the bug**
Bug 1: Switching to custom profile breaks root access.
Bug 2: Changing groups and capabilities will add every antry again and again on every change submit.

**To Reproduce**
Steps to reproduce the behavior of bug 1:
1. Go to Superusers
2. Click on any app with enabled root access
3. Enable custom profile
4. Run app and see no root access

Steps to reproduce the behavior of bug 2:
1. Go to Superusers
2. Click on any app with enabled root access
3. Enable custom profile
4. Change groups or capabilities few times
5. See same entries added more than once

**Expected behavior**
Expected to have root access with custom profile and one entry of each group and capability,

**Screenshots**
![photo_2023-06-04_20-43-47](https://github.com/tiann/KernelSU/assets/16803494/c2ff18b6-96dc-4b3e-b117-3d7a898a181c)

**Smartphone (please complete the following information):**
 - Device: OnePlus 7
 - OS: Android 11
 - Version: manager 10957, kernel 10951

**Logs**
[KernelSU_bugreport_2023-06-04_20_29.tar.gz](https://github.com/tiann/KernelSU/files/11646301/KernelSU_bugreport_2023-06-04_20_29.tar.gz)

**Comment by tiann** [comment]
You should add enough capabilities to make su work.

**Comment by tiann** [comment]
https://github.com/tiann/KernelSU/commit/9ae0126be5f5968f96c15a8e7fe8a9e0e17bfbc7 Add minimal capabilities for `su`
