### ISSUE TITLE
Manager 0.6版本，无法识别到为旧linux内核手工移植的KernelSU

### ISSUE THREAD

**Issue by zlm324** [tiann/KernelSU#606]
描述：
Manager 0.6版本，无法识别到手工移植的KernelSU。

复现：
在Manager 0.5.7+KernelSU 10964正常工作的情况下，
1. 卸载Manager 0.5.7
2. 安装Manager 0.6，并打开，看到提示“当前仅支持GKI内核”，即Manager认为没有KernelSU。
3. 重启到Recovery，安装KernelSU 10981，重启，Manager依旧找不到KerneSU。
4. 安装Manager 0.5.7+KernelSU 10981，可以识别到KernelSU，但授予ROOT不正常，提示“为<某应用>设置app profile失败”。

手机：
小米6，LineageOS 20，Kernel 4.4.302

**Comment by tiann** [comment]
版本要匹配。
