### ISSUE TITLE
更新v0.6.0后LSPosed安装不成功

### ISSUE THREAD

**Issue by kingz40o** [tiann/KernelSU#607]
更新v0.6.0后，kernelsu正常，正常安装刷入以下模块，LSPosed显示未安装：
[v4-0.7.0] https://github.com/Dr-TSNG/ZygiskOnKernelSU/releases/tag/v4-0.7.0
[1.8.6] https://github.com/LSPosed/LSPosed/releases/tag/v1.8.6
![image](https://github.com/tiann/KernelSU/assets/19370924/3b5683eb-e101-47ad-8b32-07c28ff47a77)

**Comment by tiann** [comment]
ZygiskOnKernelSU 用 debug 版。
