### ISSUE TITLE
保留root升级掉授权

### ISSUE THREAD

**Issue by bugme2** [tiann/KernelSU#612]
保留root升级系统，原本有20个应用授权，开机后剩下9个应用授权而已了。

 - 设备: 一加11
 - 系统: ColorOS13.1
 - KSU版本: 10981

**Comment by tiann** [comment]
no log no fix

**Comment by bugme2** [comment]
[KernelSU_bugreport_2023-07-13_22_56.tar.gz](https://github.com/tiann/KernelSU/files/12040817/KernelSU_bugreport_2023-07-13_22_56.tar.gz)

**Comment by bugme2** [comment]
> 没有日志没有修复
[KernelSU_bugreport_2023-07-13_22_56.tar.gz](https://github.com/tiann/KernelSU/files/12040830/KernelSU_bugreport_2023-07-13_22_56.tar.gz)
