### ISSUE TITLE
Module update feature like Magisk App

### ISSUE THREAD

**Issue by symbuzzer** [tiann/KernelSU#619]
Hi. I am the developer of the Turkish Ad Hosts Magisk Module, which is used very actively in Turkey. At the same time, I have a Magisk Module template that I developed myself and is used quite a lot.
Due to the working logic of the Turkish Ad Hosts module, it is updated almost daily. However, the option to update the module does not appear in the module management tab of KernelSU. I'm wondering if any improvements will be made regarding this.

**Comment by tiann** [comment]
#469

**Comment by symbuzzer** [comment]
Duplicate
