### ISSUE TITLE
SM-S908E (S22 Ultra snapdragon)

### ISSUE THREAD

**Issue by russel5** [tiann/KernelSU#620]
**Describe the bug**
After compiling the kernel from the official sources with KernelSU integrated, the phone boot and works fine, but as soon as I run the program, the phone freezes and reboots

**To Reproduce**
1. Compiling kernel from official sources with KernelSU
2. Run kernelsu apk
3. See error

**Expected behavior**
Can you provide a fix or look at this issue? If i take your kernel images from release section, phone work and app is working, but i'm have battery drain and screen issue.

**Smartphone (please complete the following information):**
 - Device: [Samsung-S22 Ultra SM-S908E]
 - OS: [OneUI 5.1]
 - Version [Android 13]
 - Kenel [5.10.136-Android12-9]

**Comment by rushiranpise** [comment]
Try these
https://github.com/tiann/KernelSU/issues/263#issuecomment-1437963812

More Info: https://github.com/tiann/KernelSU/issues/263

**Comment by russel5** [comment]
@rushiranpise thank you, all works right now
@tiann may be add this info in build guide for samsung phone?
issue closed

**Comment by sha3rawi33** [comment]
Hi, can you help me choose a kernel SU boot.img from the list? 

I have S22U (SM-S908E) with oneui 6 and android 14, security patch is dec 2023. is this the reason?

if not, which kernel boot image are you using now? and how are you flashing it to your phone?

**Comment by russel5** [comment]
https://xdaforums.com/t/sm-s908e-stock-boot-with-kernelsu.4648320/
I'm build stock kernel with kernelsu, just use it
