### ISSUE TITLE
Not working after updating to the latest 10981.

### ISSUE THREAD

**Issue by 3255867418** [tiann/KernelSU#621]
**Describe the bug**
Unable to use superuser or module after updating to the latest 10981.

**To Reproduce**
My device is polaris, which doesn't support GKI, so I compiled a kernel to flash. After flashing, all superusers I granted and modules I installed are gone. And I found I can't use su anymore even if I granted in manger, nor do the modules, they become grey after rebooting.

**Expected behavior**

**Screenshots**
![Screenshot_20230611-154015_KernelSU](https://github.com/tiann/KernelSU/assets/70674246/6709ae5b-eeef-44d7-ac57-65704d58bda8)
![Screenshot_20230611-154019_KernelSU](https://github.com/tiann/KernelSU/assets/70674246/580c557d-8442-4bb6-a498-30e94c052bfa)

**Smartphone (please complete the following information):**
 - Device: Xiaomi MIX2S 
 - OS: Pixelexperience
 - Version 13plus

I will upload log later.

**Comment by 3255867418** [comment]
[KernelSU_bugreport_2023-06-11_16_17.tar.gz](https://github.com/tiann/KernelSU/files/11714212/KernelSU_bugreport_2023-06-11_16_17.tar.gz)

**Comment by netPokey** [comment]
n你好 你的mix2s 成功了吗  可以分享一下吗

**Comment by 3255867418** [comment]
> n你好 你的mix2s 成功了吗 可以分享一下吗

链接: https://pan.baidu.com/s/1YytruftDYXGBtSohaAbscA 提取码: 2bqv ，试试这个10868被删了找不到

**Comment by netPokey** [comment]
> > 你好你的mix2s成功了吗可以分享一下吗
> 
> 链接：https://pan.baidu.com/s/1YytruftDYXGBtSohaAbscA提取码：2bqv，试试这个10868被删除了找不到

你好我刷人开不起机直接进去fastboot
