### ISSUE TITLE
xiaomi12,android12

### ISSUE THREAD

**Issue by crazyxw** [tiann/KernelSU#624]
hello, my phone is xiaomi12,system version is android 12, gki version is 5.10.43, and the bootloader has been unlocked.I downloaded android12-5.10.168_2023-04-boot.img.gz,execute the following command:
1. fastboot flash boot android12-5.10.168_2023-04-boot.img
2. fastboot reboot
But the phone won't turn on.
Please help me, thank you very much.

**Comment by crazyxw** [comment]
Or not. I even tried patching with magiskboot, don't know where the problem is? But I use [https://github.com/tiann/KernelSU/releases/download/v0.5.1/ksu-10733-Image-android12-5.10 .66_2021-11-boot.img.gz](https://github.com/tiann/KernelSU/releases/download/v0.5.1/ksu-10733-Image-android12-5.10.66_2021-11-boot.img.gz) and it works fine.

**Comment by tiann** [comment]
Please upgrade your phone's system first, then try using KernelSU, version 5.10.66 has been deprecated by Google.
