### ISSUE TITLE
内核不支持overlayfs，模块功能无法运作!

### ISSUE THREAD

**Issue by Star-Seven** [tiann/KernelSU#625]
机型：三星SM-N976N
Android版本 ：12 （oneUI4.1）

1. 已成功构建kernelsu内核，提示不支持overlayfs
2. 确认以成功开启overlayfs,但是扔提示不支持overlayfs
如图
![1](https://github.com/tiann/KernelSU/assets/72426083/440bc173-a059-4456-a7a8-1820729e02ec)
![2](https://github.com/tiann/KernelSU/assets/72426083/3b177baf-224f-4b2a-b702-d2e965d54f2b)
相关日志
[KernelSU_bugreport_2023-06-13_07_55.tar.gz](https://github.com/tiann/KernelSU/files/11730013/KernelSU_bugreport_2023-06-13_07_55.tar.gz)

请问是否仍需要修改哪里，谢谢！

**Comment by tiann** [comment]
Search the issues first and you will find the solution.

**Comment by Star-Seven** [comment]
> Search the issues first and you will find the solution.

The kernel configuration was removed as mentioned in issues (263), but still prompted that the kernel does not support overlayfs, which is why I raised this issue
