### ISSUE TITLE
Changing package name

### ISSUE THREAD

**Issue by symbuzzer** [tiann/KernelSU#628]
Some apps (eg banking apps) will check to see if the device is rooted by checking its package name (me.weishu.kernelsu) as the KernelSU project becomes popular. We've already seen this on Magisk before. For this reason, is it possible to work on the feature of re-installing the package name, or another method, as in Magisk?

**Comment by tiann** [comment]
At KernelSU, we recommend uninstalling the manager when not in use.

**Comment by symbuzzer** [comment]
> At KernelSU, we recommend uninstalling the manager when not in use.

So will modules and apps need root perm. still keep work when uninstalled?

**Comment by tiann** [comment]
> > At KernelSU, we recommend uninstalling the manager when not in use.
> 
> So will modules and apps need root perm. still keep work when uninstalled?

Of course, Manager is just a management interface; all the core functions of KernelSU (including root, modules) can work without a manager.

**Comment by mindingulove** [comment]
I did this, biut app is still detected b y my banking app.

**Comment by vpx23** [comment]
> I did this, biut app is still detected b y my banking app.

Try to use Applist Detector to find the culprit: https://github.com/Dr-TSNG/ApplistDetector/releases

**Comment by kiber-io** [comment]
You can make a clone yourself, just do not change the signature, because there is a check for it. This can be achieved using CorePatch, for example.
Plus, there is a mention of the original package in libksud.so, for completeness, you can replace it there (observing the rule that the new line should not be longer than the old one). And it seems to work :)

**Comment by becks90** [comment]
> You can make a clone yourself, just do not change the signature, because there is a check for it. This can be achieved using CorePatch, for example.
> Plus, there is a mention of the original package in libksud.so, for completeness, you can replace it there (observing the rule that the new line should not be longer than the old one). And it seems to work :)

I tried making a clone using APK Explorer & Editor, while having CorePatcher installed.
The Manager App starts, but will show an error: KSU only Supports GKI kernel.
With the original KSU Manager 1.0 it works.

**Comment by SaeedDev94** [comment]
@tiann But it's not easy to install, uninstall it each time!  
It would be great if KernelSU supports changing package name like magisk (Magisk hide) 🙏🏻

**Comment by NCLnclNCL** [comment]
> You can make a clone yourself, just do not change the signature, because there is a check for it. This can be achieved using CorePatch, for example. Plus, there is a mention of the original package in libksud.so, for completeness, you can replace it there (observing the rule that the new line should not be longer than the old one). And it seems to work :)

How to ?
