### ISSUE TITLE
Pixel Experience for Xiaomi Redmi K40S / Xiaomi Poco F4 (munch)

### ISSUE THREAD

**Issue by CN-Scars** [tiann/KernelSU#632]
### Repository URL

https://github.com/CN-Scars/pixel_experience_kernel_xiaomi_sm8250_kernelSU

### Device

Pixel Experience Kernel 4.19.282 for Xiaomi Redmi K40S / Xiaomi Poco F4 (munch)

### Code of Conduct

- [X] I'm the maintainer of this repository

**Comment by tiann** [comment]
#633
