### ISSUE TITLE
[Add Device]: Pixel Experience for Xiaomi Redmi K40S / Xiaomi Poco F4 (munch)

### ISSUE THREAD

**Issue by CN-Scars** [tiann/KernelSU#633]
### Repository URL

https://github.com/CN-Scars/pixel_experience_kernel_xiaomi_sm8250_kernelSU

### Device

Pixel Experience Kernel 4.19.282 for Xiaomi Redmi K40S / Xiaomi Poco F4 (munch)

### Code of Conduct

- [X] I'm the maintainer of this repository

**Comment by tiann** [comment]
Is the robot seems to be broken? @Ylarod

**Comment by Ylarod** [comment]
https://github.com/tiann/KernelSU/actions/runs/5266147684/jobs/9567841948#step:2:68

**Comment by tiann** [comment]
Sorry, due to the robot temporarily malfunctioning, please open a new issue. We apologize for the inconvenience!
