### ISSUE TITLE
[Feature request] Config Backup and Recovery Feature. 配置备份和恢复功能。

### ISSUE THREAD

**Issue by Jialin0502** [tiann/KernelSU#635]
When the system needs to be reset or replaced. KernelSU's config cannot be transferred directly.
需要系统重置或更换时，KernelSU的配置无法直接转移。

The config file is saved as a zip or js file and contains the ROOT control config, module switch status, kernel version, KernelSU version, manager version, and so on.
文件以压缩包或js形式保存，包含ROOT授权配置，模块开关状态，内核版本、KernelSU版本和管理器版本等

**Comment by tiann** [comment]
我没有这个需求，你需要的话欢迎 pr
