### ISSUE TITLE
chromeOS 显示【未安装】，很可能是内核支持，但 vmlinux 不太一样，不知道怎么操作。

### ISSUE THREAD

**Issue by 1457384613gh** [tiann/KernelSU#636]
![Screenshot 2023-06-15 20 41 55](https://github.com/tiann/KernelSU/assets/69227436/03f7e755-7554-4fb1-9bfd-16d8fa3e8abd)
![image](https://github.com/tiann/KernelSU/assets/69227436/f9774367-27f4-4e81-ae9d-462c3f96cab3)
![image](https://github.com/tiann/KernelSU/assets/69227436/a751dd56-876f-4c7e-8321-d896bacbc885)

`vmlinux` 好像是 `FAT12` 的，能被 Diskgenius 挂载，但不能被访问。

**Comment by supechicken** [comment]
我也正在Chrome OS上面折騰著這個，kernel需要自己編譯，因為沒有官方支持。（詳情看首頁教程，用`common-android12-5.10-arcvm-gki-base`的branch）

**Comment by tiann** [comment]
#637
