### ISSUE TITLE
Running in ChromeOS

### ISSUE THREAD

**Issue by supechicken** [tiann/KernelSU#637]
**Describe the bug**
The `kernelsu/ksud.c:111:12: error: unused function 'count'` error appeared when running `build/build.sh`, tried `export CFLAGS='-Wno-error -Wno-unused-function'` but with no luck

*Kernel compiled successfully without KernelSU patch

**To Reproduce**
```shell
repo init -u https://android.googlesource.com/kernel/manifest -b common-android12-5.10-arcvm-gki-base
repo sync
curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -

sed -i "s/check_defconfig//" common/build.config.gki
sed -i "s/DEFCONFIG=gki_defconfig/DEFCONFIG=x86_64_arcvm_defconfig/" common/build.config.gki
cp common/arch/x86/configs/x86_64_arcvm_defconfig common/arch/x86/configs/x86_64_defconfig

LTO=thin CFLAGS='-Wno-error -Wno-unused-function' CXXFLAGS='-Wno-error -Wno-unused-function' BUILD_CONFIG=common/build.config.gki.x86_64 build/build.sh
```

**Smartphone (please complete the following information):**
 - OS: Chrome OS ARCVM kernel
 - Version: `android12-5.10`

### EDIT: This error shows after commenting out `static int count`:
```
/home/supechicken/android-kernel/common/drivers/kernelsu/ksud.c:87:27: error: unused function 'get_user_arg_ptr' [-Werror,-Wunused-function]
static const char __user *get_user_arg_ptr(struct user_arg_ptr argv, int nr)
```

**Comment by supechicken** [comment]
For those who are looking for a workaround:
```shell
# remove -Werror from all Makefiles
makefiles="$(find . -type f -name Makefile | tr "\n" ' ') $(find . -type f -name Kbuild | tr "\n" ' ')"

for i in $makefiles; do
  sed -i 's/-Werror=/-Wno-error=/g' "$i"
  sed -i 's/-Werror/-w/g' "$i"
  sed -i 's/-Wall/-w/g' "$i"
done
```

**Comment by natsumerinchan** [comment]
```
static int count(struct user_arg_ptr argv, int max) __attribute__ ((unused))
```

**Comment by natsumerinchan** [comment]
Compile with x86_64_arcvm_defconfig

[bzImage.zip](https://github.com/tiann/KernelSU/files/11765578/bzImage.zip)

**Comment by supechicken** [comment]
按一下notification就行了

**Comment by supechicken** [comment]
> 😭😭😭😭😭😭 就像手机卡开机Logo一样，进不去。 变成 虚拟砖 了，刚刚 救砖，救 虚拟砖 成功。 @supechicken 你的机子能进去吗？

![RDT_20230616_1235022011108248184961609](https://github.com/tiann/KernelSU/assets/73414985/022304cf-d34c-462d-924e-d49e49d3ad2b)

**Comment by tiann** [comment]
如果你们感兴趣的话，非常欢迎加一个 ChromeOS 的 CI！

**Comment by supechicken** [comment]
> 如果你们感兴趣的话，非常欢迎加一个 ChromeOS 的 CI！

好的，等我先研究一下github action再開pr

**Comment by supechicken** [comment]
先看看ARCVM的kernel log，或許裡面有失敗原因

**Comment by natsumerinchan** [comment]
> Dex 优化器 不支持，挂载失败，这个是不是要去 LSPosed 那边 issue 一下啊？ ![image](https://user-images.githubusercontent.com/69227436/246317211-020f3f1b-c7e2-44cc-8eb7-1d79a216293b.png)

用CI版本的LSPosed https://t.me/LSPosedArchives

**Comment by natsumerinchan** [comment]
> 支持 Dex了，但不支持快捷方式 ![image](https://user-images.githubusercontent.com/69227436/246323480-a635614c-a309-4520-82fe-c343210cedfd.png)

可能是ChromeOS本身不支持创建快捷方式？

**Comment by natsumerinchan** [comment]
> 太棒了，成功啦。 @natsumerinchan 但是啊，chromeOS 没有【拨号】，启动器也没有【LSPosed】的图标，怎么打开 【LSPosed】呢？？？ termux 能输入命令打开【LSPosed】吗？
> 
> ![image](https://user-images.githubusercontent.com/69227436/246316236-a8b8d533-7113-4649-a64a-68a4365ef3e9.png)![image](https://user-images.githubusercontent.com/69227436/246316278-00a1c033-be8d-41e1-8aac-db0bf5cd4fed.png)

```
am start -a android.intent.action.MAIN -c org.lsposed.manager.LAUNCH_MANAGER com.android.shell/.BugreportWarningActivity
```

来自https://github.com/ya0211/MRepo/issues/19#issuecomment-1537081000

**Comment by natsumerinchan** [comment]
> 现在好了，chromeOS 有
> 
> * 安卓的超级用户权限；
> * 支持安装模块；
> * 官方支持的稳定的桌面端的 chrome 浏览器；
> * 未来版本自带 AI；
> 
> 感觉，可玩性可以跟 Android x86 媲美了，稳定性也比 Android x86 强。 分享你们个 grub2，比 Win2Grub要强多了，专门用来 双启动 或 多启动 chromeOS 的。 用起来超级方便的。 https://github.com/M-L-P/brunch-grub2

特别是ChromeOS的SELinux能强制执行

**Comment by natsumerinchan** [comment]
> 虽然安卓版本不是特别高，但毕竟是谷歌的亲儿子，未来肯定会升级安卓版本的。 感觉性能比 WSA 强多了。

话说ChromeOS上allowlist能不能正常保存，会不会像WSA那样重启就丢权限

**Comment by natsumerinchan** [comment]
> 总结下步骤。 下载并解压 zip，把 `bzImage` 重命名为 `vmlinux`， 然后，进入 crosh，输入以下命令。 `shell` `cd /opt/google/vms/android` `ls -l` `sudo mv vmlinux vmlinux_real` `ls -l` `cd ~/Downloads` `ls -l` `sudo cp vmlinux /opt/google/vms/android` `cd /opt/google/vms/android` `ls -l` 然后重启。
> 
> 感觉可以整理成一个【一键KernelSU.sh】的脚本。 `curl -s http://...../...../...../一键KernelSU.sh | sudo bash`

把这个脚本整进压缩包里
`./ksu_arcvm.sh install`: 安装KernelSU并备份原kernel
`./ksu_arcvm.sh uninstall`: 卸载并还原
`./ksu_arcvm.sh -h/--help`: 显示帮助
```
#!/bin/sh
set -eu
ANDROID_ROOT=/opt/google/vms/android

ksu_help() {
    printf "Usage: $0 [options]\n"
    printf "\nOptions:\n"
    printf "  install                       Install KernelSU and backup original\n"
    printf "                                kernel for ChromeOS ARCVM\n"
    printf "  uninstall                     Remove KernelSU and restore original\n" 
    printf "                                kernel for ChromeOS ARCVM\n"
    printf "  -h, --help                    Display this help message and exit\n"
}

ksu_install() {
    if [ -d $ANDROID_ROOT ]; then
        ls -l $ANDROID_ROOT
        if [ ! -e $ANDROID_ROOT/vmlinux_bak ]; then
            sudo mv $ANDROID_ROOT/vmlinux $ANDROID_ROOT/vmlinux_bak
        else
            sudo rm $ANDROID_ROOT/vmlinux
        fi
        if [ -e ./bzImage ]; then
            sudo cp ./bzImage $ANDROID_ROOT/vmlinux
            sudo ls -l $ANDROID_ROOT
        else
            echo "[ERROR] bzImage is not exist."
            exit 127
        fi
    else
        echo "[ERROR] $ANDROID_ROOT is not exist."
        exit 127
    fi
}

ksu_uninstall() {
    if [ -d $ANDROID_ROOT ]; then
        if [ ! -d $ANDROID_ROOT/vmlinux_bak ]; then
            echo "$ANDROID_ROOT/vmlinux_bak is not found."
            echo "Maybe you have uninstall or you have not install KernelSU."
            exit 0
        fi
        sudo rm $ANDROID_ROOT/vmlinux
        sudo mv $ANDROID_ROOT/vmlinux_bak $ANDROID_ROOT/vmlinux
    else
        echo "[ERROR] $ANDROID_ROOT is not exist."
        exit 127
    fi
}

if [ -z "${1-}" ] || [ "${1-}" == "-h" ] || [ "${1-}" == "--help" ]; then
    ksu_help
elif [ "${1-}" == "install" ]; then
    ksu_install
elif [ "${1-}" == "uninstall" ]; then
    ksu_uninstall
else
    echo "[ERROR] No such option."
    exit 1
fi
```

**Comment by supechicken** [comment]
> 总结下步骤...

補充：真正的 Chromebook 要先關閉rootFS verification，然後再 remount as r/w 才能對系統動手腳:
```
/usr/share/vboot/bin/make_dev_ssd.sh --remove_rootfs_verification
sudo reboot
sudo mount -o remount,rw /
```

**Comment by supechicken** [comment]
單單Android重啟是沒用的，一定要整個`crosvm`進程重啟才行（這樣它才會去重新讀取kernel文件）

**Comment by supechicken** [comment]
就算行的通的話那個 KernelSU 管理應用也需要先提權才能用啊，這不就成死循環了😀

**Comment by natsumerinchan** [comment]
还是简单粗暴直接重启ChromeOS好了，我加了个选择是否重启的选项

**Comment by supechicken** [comment]
有喔，剛試了一下能行

**Comment by supechicken** [comment]
不用，剛看了一下 bash shell 下面也有 `vmc`, 所以可以直接在腳本裡面做

**Comment by supechicken** [comment]
和普通Chromebook不同，Brunch 只用 ROOT-A（4號分區，更新的時候將本應只寫往`ROOT-B`的映像也寫往`ROOT-A`,然後強制從`ROOT-A`啟動）

這造成了另一個問題，就是原本的kernel備份也會因為更新而被刪除，這我們還要想想要怎麼解決

**Comment by supechicken** [comment]
```
$ sudo fdisk -l -o Device,Size,Type,Name /dev/sdz
Disk /dev/sdz: 128 GiB, 137438953472 bytes, 268435456 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 5DBAA591-A253-E845-8B2B-299DCB9B971D

Device       Size Type              Name
/dev/sdz1  118.8G Linux filesystem  
/dev/sdz2     32M ChromeOS kernel   KERN-A
/dev/sdz3      4G ChromeOS root fs  ROOT-A
/dev/sdz4     32M ChromeOS kernel   KERN-B
/dev/sdz5      4G ChromeOS root fs  ROOT-B
/dev/sdz6    512B ChromeOS kernel   KERN-C
/dev/sdz7      1G ChromeOS root fs  ROOT-C
/dev/sdz8     16M Linux filesystem  OEM
/dev/sdz9    512B ChromeOS reserved reserved
/dev/sdz10   512B ChromeOS reserved reserved
/dev/sdz11     8M unknown           RWFW
/dev/sdz12    32M EFI System        EFI-SYSTEM

Partition table entries are not in disk order.
```

**Comment by supechicken** [comment]
> > kernel備份也會因為更新而被刪除，
> 
> 直接变成 官方的 vmlinux了。
> 
> Brunch 框架 更换 内核，或者更改其他内核选项，也会造成，vmlinux 自动恢复成官方版的。

可以這麼說。

**Comment by supechicken** [comment]
這也要看 ChromeOS 本身支持才行，不然連系統都進不了

**Comment by djfaizp** [comment]
> 

how to apply it ?

**Comment by supechicken** [comment]
這個看上去很難, 其實原理很簡單：
- PWA 並不能直接訪問 shell, Brunch PWA 是透過 Websocket 聯繫已經在系統運行的`websocketd`後台監聽腳本，叫它幹活
- 要想在 PWA 上面訪問 shell, 我們需要一個自己的監聽腳本，而安裝它還是要進`crosh`，所以網站一鍵 root 是不可能的
- 假設現在腳本裝好了，我們可以透過`init.d`來讓腳本開機自啟，這樣 PWA 才連得上去

我寫過 Websocket server，但不是基於`websocketd`而是從底層`socket`寫起，還是挺容易的

**Comment by supechicken** [comment]
> how to apply it ?

Just paste it into bash shell inside the kernel source directory

**Comment by djfaizp** [comment]
![Screenshot 2023-06-17 2 28 38 PM](https://github.com/tiann/KernelSU/assets/20996246/023c4524-6582-4f00-9872-6c4f68d63096)
how to activate this

**Comment by supechicken** [comment]
> 那 brunch-pwa 是怎么做到 下载好了 brunch.tar.gz 或 rammus.bin 还能够安装的呢？
> 
> PWA 是怎么 修改 系统文件的呢？

不是 PWA 修改的，是 PWA 叫本地後台進程下載並修改的，PWA 只負責把進度顯示出來：

關鍵不在 PWA 本身，是在那個後台腳本: https://github.com/sebanc/brunch/blob/r113/brunch-patches/99-pwa.sh

**Comment by supechicken** [comment]
> how to activate this i have tried manually but the activation script do not work

Did you enable root for this app (in KernelSU app)?

**Comment by supechicken** [comment]
你可以試試

對了，那個`vmc stop arcvm`其實也不太穩定，一換 kernel 就大概率 bootloop，還是老老實實 reboot 算了

**Comment by djfaizp** [comment]
> > how to activate this i have tried manually but the activation script do not work
> 
> @djfaizp Did you enable root for this app (in KernelSU app)?

yes i tried

**Comment by djfaizp** [comment]
@1457384613gh @natsumerinchan @supechicken  i have read reddit and found that this issue is due to arcvm as Google is planing to move to fuschia os so they have introduced arcvm for flew less migration. But arc++ support is great and it uses chrome os kernel. Can some one compile chrome os kernel i think r90 (or android 9) had arc++ kernel architecture.

**Comment by djfaizp** [comment]
i'm currently trying to compile, i will share results here, I <3 Chrome os

**Comment by supechicken** [comment]
> is this correct to implement it

No need to add to Makefile, and this will not work as the syntax of Makefile is different to bash.

Also this patch is no longer needed as https://github.com/tiann/KernelSU/commit/c697398893612a882df8f22ac1fb63bae2e79d79 fixed it

**Comment by supechicken** [comment]
> how to activate this i have tried manually but the activation script do not work

It seems that this app does not support KernelSU yet.

**Comment by djfaizp** [comment]
> > how to activate this i have tried manually but the activation script do not work

you mean termux ? termux gain su access

**Comment by supechicken** [comment]
I mean the script itself

**Comment by natsumerinchan** [comment]
> ![Screenshot 2023-06-17 2 28 38 PM](https://user-images.githubusercontent.com/20996246/246597771-023c4524-6582-4f00-9872-6c4f68d63096.png) how to activate this i have tried manually but the activation script do not work

Try this one? https://github.com/Xtr126/XtMapper.git

**Comment by djfaizp** [comment]
> 他那个，好像是个什么鼠标外设的。 不知道 ARCVM 能不能调用 宿主系统 的 USB 设备。

you can connect it there is no issue at all

**Comment by supechicken** [comment]
> 编译的 vmlinux 不是有两份吗？ 一份是 bootloop 的，体积翻倍； 另一份 是 成功的，体积增一点点。
> 
> 会不会是换错了？

不可能，我用原來的和打了補丁的試了試，一換 kernel log 就報錯（我記得好像是說`vsock`端口被佔了）。兩個 kernel 重啟後都能用

**Comment by hmtheboy154** [comment]
> > how to activate this i have tried manually but the activation script do not work
> 
> It seems that this app does not support KernelSU yet.

Panda keymapper (or Octopus) comes with ARM libraries only, when being injected into the system it will immediately reject it because of different CPU arch. Even if ChromeOS's arcvm has native bridge it does not help at all. The only solution now is to modify bionic libc.

Speaking of ARM, please remember that arcvm has ARM version for ARM Chromebooks too

**Comment by djfaizp** [comment]
> > is this correct to implement it
> 
> No need to add to Makefile, and this will not work as the syntax of Makefile is different to bash.
> 
> Also this patch is no longer needed as [c697398](https://github.com/tiann/KernelSU/commit/c697398893612a882df8f22ac1fb63bae2e79d79) fixed it

![image](https://github.com/tiann/KernelSU/assets/20996246/5383ac4f-2db3-4bcc-8786-73b4c7514bcf)
 i'm still getting this error

**Comment by djfaizp** [comment]
> However, if waydroid can support KernelSU, that of ARC++ can study it.

waydroid is to much laggy i have tried it

**Comment by hmtheboy154** [comment]
> ARC++ has no its own `vmlinux`, at least I don't know how to make it support KernelSU.

Old ARC is a container nearlt like WayDroid like you said, so instead of trying to find the `guest` kernel (arcvm is literally a VM), you directly build KernelSU into your ChromeOS kernel

> ARC++ is like waydroid. However, if waydroid can support KernelSU, that of ARC++ can study it. So what you should do is to ask @hmtheboy154 how to make waydroid support KernelSU.

WayDroid did the same. In fact, I'm not the first one that brought KernelSU into WayDroid, someone else in China already did.

> He will tell you that waydroid supports Magisk Delta. So why don't you try waydroid+MagiskΔ?

I won't tell because I don't know.
 
> However, you can still ask @hmtheboy154 whether there is a way to make waydroid support KernelSU or not.

again, build the kernel with KernelSU, WayDroid will immediately recognize it

**Comment by djfaizp** [comment]
@hmtheboy154  I have tried to compile it but core_hook.c :70 :9: module is still producing the same error which was in ksud.c :87:27:

**Comment by hmtheboy154** [comment]
what's this kernel source ?

**Comment by djfaizp** [comment]
It's [here](https://github.com/djfaizp/brunch/blob/91ba8924e28739ab445b7654bbd77e4d9396e110/prepare_kernels.sh)

**Comment by supechicken** [comment]
> again, build the kernel with KernelSU, WayDroid will immediately recognize it

I don't think it will work as the UID/GID is remapped in containers, which might break the approve/deny algorithm in KernelSU.

**Comment by supechicken** [comment]
Never mind, just found that the source code can handle it by checking the current namespace.

But will the `init` hook work when running in a container?

**Comment by djfaizp** [comment]
why I'm getting this error any idea?

`depmod: WARNING: /home/alex/brunch/chroot/tmp/kernel/out/../../../home/chronos/kernel/lib/modules/4.19.282-brunch-sebanc/kernel/drivers/staging/rtlwifi/r8822be.ko needs unknown symbol rate_control_send_low
modinfo: ERROR: Module alias mac80211 not found.
depmod will prefer updates/ over kernel/ -- OK!
depmod: ERROR: could not open directory /lib/modules/5.15.90.1-microsoft-standard-WSL2: No such file or directory
depmod: FATAL: could not search modules: No such file or directory
make[1]: *** [Makefile.real:108: install] Error 1
make: *** [Makefile:43: install] Error 2
root@Alex:/home/alex/brunch/chroot/tmp/backport-iwlwifi# `

**Comment by natsumerinchan** [comment]
> @natsumerinchan 帮忙看下 那个 5.4.217 的，能不能 kernelsu 修补。
> 
> 我正好有个酷睿一代的设备安装了 fydeOS，是 5.4.217 的内核，可以用来测试。
> 
> 我还制作了给 fydeOS 使用的 grub 主题，需要复制到 `/boot/grub/themes` 目录下，正好在复制主题的时候，顺便把 `vmlinuz-ksu-5.4` 复制到 `/boot`，然后，我还可以 编辑 `grub.cfg`，添加支持 kernelsu 的启动项。
> 
> https://github.com/openFyde/project-openfyde-patches/tree/main/sys-kernel/chromeos-kernel-5_4

OK,等我恰完饭

**Comment by supechicken** [comment]
> @supechicken 这有个 shutdown arcvm，但不知道能不能在 crosh shell 里用上。 https://chromium.googlesource.com/chromiumos/platform2/+/master/vm_tools/concierge/arc_vm.cc

應該不能，因為它沒有可以操作的`dbus`介面

**Comment by djfaizp** [comment]
I noticed brayo arcvm kernel work better in chrome os

**Comment by djfaizp** [comment]
I noticed brayo arcvm kernel work better in chrome os

**Comment by natsumerinchan** [comment]
Root临时修复方法

[arcvm_kernelsu_fix.zip](https://github.com/tiann/KernelSU/files/11859760/arcvm_kernelsu_fix.zip)

```
#!/data/adb/ksu/bin/busybox sh

/system/bin/su "$@"

```

**Comment by supechicken** [comment]
> su临时修复方法

如果加`exec`的話能用嗎？像這樣：
```shell
#!/data/adb/ksu/bin/busybox sh
exec /system/bin/su "$@"
```

**Comment by natsumerinchan** [comment]
> @natsumerinchan 帮忙看下 那个 5.4.217 的，能不能 kernelsu 修补。
> 
> 我正好有个酷睿一代的设备安装了 fydeOS，是 5.4.217 的内核，可以用来测试。
> 
> 我还制作了给 fydeOS 使用的 grub 主题，需要复制到 `/boot/grub/themes` 目录下，正好在复制主题的时候，顺便把 `vmlinuz-ksu-5.4` 复制到 `/boot`，然后，我还可以 编辑 `grub.cfg`，添加支持 kernelsu 的启动项。
> 
> https://github.com/openFyde/project-openfyde-patches/tree/main/sys-kernel/chromeos-kernel-5_4

你试试能不能用，能用我就提pr了 https://github.com/natsumerinchan/KernelSU/actions/runs/5369969915

**Comment by natsumerinchan** [comment]
> > su临时修复方法
> 
> 如果加`exec`的話能用嗎？像這樣：
> 
> ```shell
> #!/data/adb/ksu/bin/busybox sh
> exec /system/bin/su "$@"
> ```

我去试试

**Comment by supechicken** [comment]
> ~我去试试~ 能用

好的謝謝

**Comment by supechicken** [comment]
> 把 /dev/dm-0 当作一块磁盘，进行全盘安装

但`dm-verify`不是唯讀的嗎？居然能寫進去

> 要试试能不能成功挂载子卷上的若干分区，万一能，说不定可以启动。

聽起來能行，不過不知道 Brunch 的 `grub` 有沒有編譯 `lvm` 支持，可能要換一個 `grub` 才行

**Comment by natsumerinchan** [comment]
> > 可能要換一個 grub 才行
> 
> 大不了 `insmod lvm.mod`

FydeOS能开机不

**Comment by tiann** [comment]
> @tiann 给我一个 KernelSU 的 LOGO 的 PNG 文件； 正方形，512px的，我要拿来给 grub 主题用。

[KernelSU_512x512.png.zip](https://github.com/tiann/KernelSU/files/11862835/KernelSU_512x512.png.zip)
我这个不专业，可以先用着。需要找个人做个 svg 的图

**Comment by natsumerinchan** [comment]
> @natsumerinchan 如果 修补宿主系统的内核 实在是很复杂的话，就算了，反正主题也只动了一点点而已，丢了也不可惜。 虽然 安卓容器 比 ARCVM 虚拟机快，可毕竟那是 安卓9 啊，版本偏低了。 太复杂，做不来，不想动的话，就算了。 本来就 有些 鸡肋，食之无味，弃之可惜。 ![image](https://user-images.githubusercontent.com/69227436/248642350-026f375f-7e75-4a2d-8b3b-f668dde1af2a.png)

所以是应该直接编译[x86_64_defconfig](https://chromium.googlesource.com/chromiumos/third_party/kernel.git/+/refs/heads/chromeos-5.4/arch/x86/configs/x86_64_defconfig)吗

**Comment by natsumerinchan** [comment]
> @natsumerinchan 试下这个，这个好像是打过补丁的。 https://github.com/openFyde/kernel

这个的内核版本是177，没问题吗

**Comment by Misakei** [comment]
> 现在好了，chromeOS 有
> 
> * 安卓的超级用户权限；
> * 支持安装模块；
> * 官方支持的稳定的桌面端的 chrome 浏览器；
> * 未来版本自带 AI；
> 
> 感觉，可玩性可以跟 Android x86 媲美了，稳定性也比 Android x86 强。 分享你们个 grub2，比 Win2Grub要强多了，专门用来 双启动 或 多启动 chromeOS 的。 用起来超级方便的。 https://github.com/M-L-P/grub2-brunch

@1457384613gh 老哥，chromeos装上kernelsu成功root后，能不能刷安卓的蝰蛇音效？蝰蛇音效那个lib驱动文件在chromeos里能不能正常驱动呀？能不能麻烦老哥测试一下？

**Comment by Misakei** [comment]
> > @1457384613gh 老哥，chromeos装上kernelsu成功root后，能不能刷安卓的蝰蛇音效？蝰蛇音效那个lib驱动文件在chromeos里能不能正常驱动呀？能不能麻烦老哥测试一下？
> 
> 你不如使用一个自带调音器的音乐播放器。 即便 ARCVM 有音效，不代表宿主系统就能够……

感谢老哥的回复，我可以把ARCVM当虚拟机理解吧？即使生效了，也是虚拟机里面有效果，外面主系统啥样还不一定呢。😂

**Comment by Misakei** [comment]
> > @1457384613gh 老哥，chromeos装上kernelsu成功root后，能不能刷安卓的蝰蛇音效？蝰蛇音效那个lib驱动文件在chromeos里能不能正常驱动呀？能不能麻烦老哥测试一下？
> 
> 你不如使用一个自带调音器的音乐播放器。 即便 ARCVM 有音效，不代表宿主系统就能够……

曾经折腾过一段时间Androidx86，Androidx86是可以完美使用v4a的。😂

**Comment by wxt1221** [comment]
您自己试试不行吗？




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "tiann/KernelSU"                                                                                    ***@***.***&gt;;
Date:&nbsp;Fri, Dec 29, 2023 11:11 AM
***@***.***&gt;;
***@***.***&gt;;
Subject:&nbsp;Re: [tiann/KernelSU] Running in ChromeOS (Issue #637)





   
@1457384613gh 老哥，chromeos装上kernelsu成功root后，能不能刷安卓的蝰蛇音效？蝰蛇音效那个lib驱动文件在chromeos里能不能正常驱动呀？能不能麻烦老哥测试一下？
  
你不如使用一个自带调音器的音乐播放器。 即便 ARCVM 有音效，不代表宿主系统就能够……
  
感谢老哥的回复，我可以把ARCVM当虚拟机理解吧？即使生效了，也是虚拟机里面有效果，外面主系统啥样还不一定呢。😂

**Comment by Misakei** [comment]
> 您自己试试不行吗？
> […](#)
> ------------------&nbsp;Original&nbsp;------------------ From: "tiann/KernelSU" ***@***.***&gt;; Date:&nbsp;Fri, Dec 29, 2023 11:11 AM ***@***.***&gt;; ***@***.***&gt;; Subject:&nbsp;Re: [tiann/KernelSU] Running in ChromeOS (Issue #637) @1457384613gh 老哥，chromeos装上kernelsu成功root后，能不能刷安卓的蝰蛇音效？蝰蛇音效那个lib驱动文件在chromeos里能不能正常驱动呀？能不能麻烦老哥测试一下？ 你不如使用一个自带调音器的音乐播放器。 即便 ARCVM 有音效，不代表宿主系统就能够…… 感谢老哥的回复，我可以把ARCVM当虚拟机理解吧？即使生效了，也是虚拟机里面有效果，外面主系统啥样还不一定呢。😂 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

手头有现成设备直接能跑chromeos,我就不用问了.

**Comment by zanjie1999** [comment]
现在的最新版本v0.9.3 使用 kernel-ARCVM-arm64-5.10.209.zip 中的Image替换vmlinux 可以正常启动，但是kernelsu管理器提示未安装，看内核版本确实已经替换成功了（我的是arm64 mt8183） 

the latest version `v0.9.3` use  `Image` in `kernel-ARCVM-arm64-5.10.209.zip`  to replacement `vmlinux` is working normally, but the kernelsu manager show not install , and the kernel version has been successfully updated (use arm64 mt8183 )
