### ISSUE TITLE
Overlayfs mounted system partition readable and writable problem

### ISSUE THREAD

**Issue by benladengtd** [tiann/KernelSU#638]
Hello, how does KernelSU use overlayfs to make the system partition readable and writable?

**Comment by tiann** [comment]
Use modules.

**Comment by benladengtd** [comment]
Magisk Overlayfs Is it this module? it will cause dropped baseband

**Comment by tiann** [comment]
If you just want to modify the system, you can use the module functions provided by KernelSU to modify it yourself; if you want to directly read and write the /system partition, you can use the magisk overlayfs module; however, there is a trade-off.

**Comment by benladengtd** [comment]
Can you guide how to use the module functions provided by KernelSU? Thanks

**Comment by tiann** [comment]
Read the docs: https://kernelsu.org/guide/module.html

**Comment by benladengtd** [comment]
It would be great if it could be made to enable or disable the function of mounting the system partition with one click.
![110](https://github.com/tiann/KernelSU/assets/12277040/61ed526b-2bca-4ca3-88ab-7fc759dc5916)
