### ISSUE TITLE
manual workflow approval before pr actions running

### ISSUE THREAD

**Issue by Ylarod** [tiann/KernelSU#64]
https://github.com/marketplace/actions/manual-workflow-approval

**Comment by Scirese** [comment]
Yep, it's really necessary for newbie contributors ~~like me~~.

**Comment by tiann** [comment]
How about this option?
<img width="811" alt="image" src="https://user-images.githubusercontent.com/4233744/212473583-2b52f8a5-eeac-42c3-905f-bf8de2e0d191.png">

**Comment by Ylarod** [comment]
I think only kernel CI should be restricted, cause it cost a lot of time

**Comment by Ylarod** [comment]
https://docs.github.com/zh/actions/managing-workflow-runs/skipping-workflow-runs

this works

**Comment by tiann** [comment]
I'll change the CI option to "require approval for all outside collaborators", it is the simplest way
