### ISSUE TITLE
error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode

### ISSUE THREAD

**Issue by djfaizp** [tiann/KernelSU#642]
Please find Log Below 

../scripts/atomic/check-atomics.sh
  CALL    ../scripts/checksyscalls.sh
  CHK     include/generated/compile.h
  CC      drivers/leds/trigger/ledtrig-disk.o
  CC      drivers/kernelsu/core_hook.o
  CC      drivers/leds/trigger/ledtrig-cpu.o
../drivers/kernelsu/core_hook.c: In function ‘setup_groups’:
../drivers/kernelsu/core_hook.c:70:9: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
   70 |         for (int i = 0; i < ngroups; i++) {
      |         ^~~
../drivers/kernelsu/core_hook.c:70:9: note: use option ‘-std=c99’, ‘-std=gnu99’, ‘-std=c11’ or ‘-std=gnu11’ to compile your code
In file included from ../include/linux/printk.h:7,
                 from ../include/linux/kernel.h:15,
                 from ../include/linux/list.h:9,
                 from ../include/linux/key.h:14,
                 from ../include/linux/cred.h:13,
                 from ../drivers/kernelsu/core_hook.c:2:
../drivers/kernelsu/core_hook.c: In function ‘ksu_handle_prctl’:
../include/linux/kern_levels.h:5:25: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘kuid_t’ [-Wformat=]
    5 | #define KERN_SOH        "\001"          /* ASCII Start Of Header */
      |                         ^~~~~~
../include/linux/kern_levels.h:14:25: note: in expansion of macro ‘KERN_SOH’
   14 | #define KERN_INFO       KERN_SOH "6"    /* informational */
      |                         ^~~~~~~~
../include/linux/printk.h:306:16: note: in expansion of macro ‘KERN_INFO’
  306 |         printk(KERN_INFO pr_fmt(fmt), ##__VA_ARGS__)
      |                ^~~~~~~~~
../drivers/kernelsu/core_hook.c:274:25: note: in expansion of macro ‘pr_info’
  274 |                         pr_info("allow root for: %d\n", current_uid());
      |                         ^~~~~~~
../include/linux/kern_levels.h:5:25: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘long unsigned int’ [-Wformat=]
    5 | #define KERN_SOH        "\001"          /* ASCII Start Of Header */
      |                         ^~~~~~
../include/linux/kern_levels.h:11:25: note: in expansion of macro ‘KERN_SOH’
   11 | #define KERN_ERR        KERN_SOH "3"    /* error conditions */
      |                         ^~~~~~~~
../include/linux/printk.h:299:16: note: in expansion of macro ‘KERN_ERR’
  299 |         printk(KERN_ERR pr_fmt(fmt), ##__VA_ARGS__)
      |                ^~~~~~~~
../drivers/kernelsu/core_hook.c:288:33: note: in expansion of macro ‘pr_err’
  288 |                                 pr_err("prctl reply error, cmd: %d\n", arg2);
      |                                 ^~~~~~
../include/linux/kern_levels.h:5:25: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘long unsigned int’ [-Wformat=]
    5 | #define KERN_SOH        "\001"          /* ASCII Start Of Header */
      |                         ^~~~~~
../include/linux/kern_levels.h:11:25: note: in expansion of macro ‘KERN_SOH’
   11 | #define KERN_ERR        KERN_SOH "3"    /* error conditions */
      |                         ^~~~~~~~
../include/linux/printk.h:299:16: note: in expansion of macro ‘KERN_ERR’
  299 |         printk(KERN_ERR pr_fmt(fmt), ##__VA_ARGS__)
      |                ^~~~~~~~
../drivers/kernelsu/core_hook.c:362:49: note: in expansion of macro ‘pr_err’
  362 |                                                 pr_err("prctl reply error, cmd: %d\n",
      |                                                 ^~~~~~
../include/linux/kern_levels.h:5:25: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘long unsigned int’ [-Wformat=]
    5 | #define KERN_SOH        "\001"          /* ASCII Start Of Header */
      |                         ^~~~~~
../include/linux/kern_levels.h:11:25: note: in expansion of macro ‘KERN_SOH’
   11 | #define KERN_ERR        KERN_SOH "3"    /* error conditions */
      |                         ^~~~~~~~
../include/linux/printk.h:299:16: note: in expansion of macro ‘KERN_ERR’
  299 |         printk(KERN_ERR pr_fmt(fmt), ##__VA_ARGS__)
      |                ^~~~~~~~
../drivers/kernelsu/core_hook.c:382:33: note: in expansion of macro ‘pr_err’
  382 |                                 pr_err("unknown cmd: %d\n", arg2);
      |                                 ^~~~~~
../include/linux/kern_levels.h:5:25: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘long unsigned int’ [-Wformat=]
    5 | #define KERN_SOH        "\001"          /* ASCII Start Of Header */
      |                         ^~~~~~
../include/linux/kern_levels.h:11:25: note: in expansion of macro ‘KERN_SOH’
   11 | #define KERN_ERR        KERN_SOH "3"    /* error conditions */
      |                         ^~~~~~~~
../include/linux/printk.h:299:16: note: in expansion of macro ‘KERN_ERR’
  299 |         printk(KERN_ERR pr_fmt(fmt), ##__VA_ARGS__)
      |                ^~~~~~~~
../drivers/kernelsu/core_hook.c:387:41: note: in expansion of macro ‘pr_err’
  387 |                                         pr_err("prctl reply error, cmd: %d\n",
      |                                         ^~~~~~
../include/linux/kern_levels.h:5:25: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘long unsigned int’ [-Wformat=]
    5 | #define KERN_SOH        "\001"          /* ASCII Start Of Header */
      |                         ^~~~~~
../include/linux/kern_levels.h:11:25: note: in expansion of macro ‘KERN_SOH’
   11 | #define KERN_ERR        KERN_SOH "3"    /* error conditions */
      |                         ^~~~~~~~
../include/linux/printk.h:299:16: note: in expansion of macro ‘KERN_ERR’
  299 |         printk(KERN_ERR pr_fmt(fmt), ##__VA_ARGS__)
      |                ^~~~~~~~
../drivers/kernelsu/core_hook.c:391:33: note: in expansion of macro ‘pr_err’
  391 |                                 pr_err("prctl copy err, cmd: %d\n", arg2);
      |                                 ^~~~~~
../include/linux/kern_levels.h:5:25: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘long unsigned int’ [-Wformat=]
    5 | #define KERN_SOH        "\001"          /* ASCII Start Of Header */
      |                         ^~~~~~
../include/linux/kern_levels.h:11:25: note: in expansion of macro ‘KERN_SOH’
   11 | #define KERN_ERR        KERN_SOH "3"    /* error conditions */
      |                         ^~~~~~~~
../include/linux/printk.h:299:16: note: in expansion of macro ‘KERN_ERR’
  299 |         printk(KERN_ERR pr_fmt(fmt), ##__VA_ARGS__)
      |                ^~~~~~~~
../drivers/kernelsu/core_hook.c:418:33: note: in expansion of macro ‘pr_err’
  418 |                                 pr_err("prctl reply error, cmd: %d\n", arg2);
      |                                 ^~~~~~
../include/linux/kern_levels.h:5:25: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘long unsigned int’ [-Wformat=]
    5 | #define KERN_SOH        "\001"          /* ASCII Start Of Header */
      |                         ^~~~~~
../include/linux/kern_levels.h:11:25: note: in expansion of macro ‘KERN_SOH’
   11 | #define KERN_ERR        KERN_SOH "3"    /* error conditions */
      |                         ^~~~~~~~
../include/linux/printk.h:299:16: note: in expansion of macro ‘KERN_ERR’
  299 |         printk(KERN_ERR pr_fmt(fmt), ##__VA_ARGS__)
      |                ^~~~~~~~
../drivers/kernelsu/core_hook.c:434:33: note: in expansion of macro ‘pr_err’
  434 |                                 pr_err("prctl reply error, cmd: %d\n", arg2);
      |                                 ^~~~~~
../drivers/kernelsu/core_hook.c: At top level:
cc1: note: unrecognized command-line option ‘-Wno-gcc-compat’ may have been intended to silence earlier diagnostics
make[3]: *** [../scripts/Makefile.build:262: drivers/kernelsu/core_hook.o] Error 1
make[2]: *** [../scripts/Makefile.build:497: drivers/kernelsu] Error 2
make[2]: *** Waiting for unfinished jobs....
  CC      drivers/leds/led-core.o
  CC      drivers/leds/trigger/ledtrig-panic.o
  CC      drivers/leds/led-class.o
  CC [M]  drivers/leds/trigger/ledtrig-timer.o
  CC      drivers/leds/led-triggers.o
  CC [M]  drivers/leds/led-class-flash.o
  CC [M]  drivers/leds/trigger/ledtrig-oneshot.o
  CC [M]  drivers/leds/leds-88pm860x.o
  CC [M]  drivers/leds/leds-apu.o
  CC [M]  drivers/leds/trigger/ledtrig-heartbeat.o
  CC [M]  drivers/leds/leds-as3645a.o
  CC [M]  drivers/leds/leds-bd2802.o
  CC [M]  drivers/leds/trigger/ledtrig-backlight.o
  CC [M]  drivers/leds/leds-lm3530.o
  CC [M]  drivers/leds/trigger/ledtrig-gpio.o
  CC [M]  drivers/leds/leds-lm3532.o
  CC [M]  drivers/leds/leds-lm3533.o
  CC [M]  drivers/leds/trigger/ledtrig-activity.o
  CC [M]  drivers/leds/leds-lm3642.o
  CC [M]  drivers/leds/leds-pca9532.o
  CC [M]  drivers/leds/trigger/ledtrig-default-on.o
  CC [M]  drivers/leds/leds-gpio.o
  CC [M]  drivers/leds/trigger/ledtrig-transient.o
  CC [M]  drivers/leds/leds-lp3944.o
  CC [M]  drivers/leds/trigger/ledtrig-camera.o
  CC [M]  drivers/leds/leds-lp3952.o
  CC [M]  drivers/leds/leds-lp55xx-common.o
  CC [M]  drivers/leds/trigger/ledtrig-netdev.o
  CC [M]  drivers/leds/trigger/ledtrig-pattern.o
  CC [M]  drivers/leds/leds-lp5521.o
  CC [M]  drivers/leds/trigger/ledtrig-audio.o
  CC [M]  drivers/leds/leds-lp5523.o
  CC [M]  drivers/leds/leds-lp5562.o
  AR      drivers/leds/trigger/built-in.a
  CC [M]  drivers/leds/leds-lp8501.o
  CC [M]  drivers/leds/leds-lp8788.o
  CC [M]  drivers/leds/leds-tca6507.o
  CC [M]  drivers/leds/leds-tlc591xx.o
  CC [M]  drivers/leds/leds-clevo-mail.o
  CC [M]  drivers/leds/leds-pca955x.o
  CC [M]  drivers/leds/leds-pca963x.o
  CC [M]  drivers/leds/leds-da903x.o
  CC [M]  drivers/leds/leds-da9052.o
  CC [M]  drivers/leds/leds-wm831x-status.o
  CC [M]  drivers/leds/leds-wm8350.o
  CC [M]  drivers/leds/leds-pwm.o
  CC [M]  drivers/leds/leds-regulator.o
  CC [M]  drivers/leds/leds-ss4200.o
  CC [M]  drivers/leds/leds-adp5520.o
  CC [M]  drivers/leds/leds-mc13783.o
  CC [M]  drivers/leds/leds-max8997.o
  CC [M]  drivers/leds/leds-lm355x.o
  CC [M]  drivers/leds/leds-blinkm.o
  CC [M]  drivers/leds/leds-menf21bmc.o
  CC [M]  drivers/leds/leds-mlxcpld.o
  CC [M]  drivers/leds/leds-mlxreg.o
  CC [M]  drivers/leds/leds-nic78bx.o
  CC [M]  drivers/leds/leds-mt6323.o
  CC [M]  drivers/leds/leds-lm3601x.o
  CC [M]  drivers/leds/leds-ti-lmu-common.o
  CC [M]  drivers/leds/leds-lm36274.o
  CC [M]  drivers/leds/leds-dac124s085.o
  CC [M]  drivers/leds/uleds.o
  AR      drivers/leds/built-in.a
make[1]: *** [/home/alex/Downloads/brunch/kernels/5.4/Makefile:1750: drivers] Error 2
make[1]: Leaving directory '/home/alex/Downloads/brunch/kernels/5.4/out'
make: *** [Makefile:186: sub-make] Error 2
make: Leaving directory '/home/alex/Downloads/brunch/kernels/5.4'
Kernel build failed

**Comment by djfaizp** [comment]
i was compiling chrome os main kernel while i need arcvm kernel issue closed

**Comment by wu17481748** [comment]
How to solve it! I also have this problem.
