### ISSUE TITLE
No root for system apps

### ISSUE THREAD

**Issue by Hikari-no-Tenshi** [tiann/KernelSU#645]
Latest update https://github.com/tiann/KernelSU/pull/563/commits/bad72baac2ac63a97aca03cb555d695e95d83aac breaks root for system apps.
Reverting just this change fixes root, but introduces other bug that all system apps will have root when you enable root for one of them.

**Comment by tiann** [comment]
1. 什么情况下会让系统应用获取 root 权限？
2. 目前 KernelSU 是通过 uid 授权的，系统应用 uid 都是 1000，所以授予后所有系统应用都会获取 root 权限。

**Comment by Hikari-no-Tenshi** [comment]
I have QS tile that is built-in to system app to quickly save logcat or dmesg to internal storage. Don't want install third-party party apps for logs, so made such system tile.
This tile needs root.
