### ISSUE TITLE
warning: passing argument 1 of 'ERR_PTR' makes integer from pointer without a cast

### ISSUE THREAD

**Issue by wxt1221** [tiann/KernelSU#647]
I'm using aarch64-linux-android-gcc 4.9.x 

../drivers/kernelsu/uid_observer.c: In function 'do_update_uid':
../drivers/kernelsu/uid_observer.c:47:18: warning: passing argument 1 of 'ERR_PTR' makes integer from pointer without a cast
error, forbidden warning: uid_observer.c:47

**Comment by forkill0** [comment]
改成PTR_ERR 函数即可
