### ISSUE TITLE
App profile namespace config not working

### ISSUE THREAD

**Issue by Hikari-no-Tenshi** [tiann/KernelSU#652]
**Describe the bug**
Changing namespace mode doesn't change enything.

**To Reproduce**
1. Start Root Explorer and go to /data/data folder
2. See that Root Explorer lists only own folder
3. Go to Superusers of KernelSU
4. Change namespace mode of Root Explorer to Global
5. Kill Root Explorer for changes to take effect
6. Start Root Explorer and go to /data/data folder
7. See that Root Explorer still lists only own folder

**Expected behavior**
Changing namespace mode should really change namespace for selected app.

**Smartphone:**
 - Device: OnePlus 7
 - OS: Android 11
 - Version: kernel 11012, manager 11007

**Logs**
[KernelSU_bugreport_2023-06-18_10_48.tar.gz](https://github.com/tiann/KernelSU/files/11780871/KernelSU_bugreport_2023-06-18_10_48.tar.gz)

**Comment by Hikari-no-Tenshi** [comment]
Was checking on every update of kernel and manager code since that option was added, but it never worked for me on Root Explorer or on in-built file manager of Advanced Tools Pro.
I'm switched back to Magisk as i can't get same root experience on KernelSU, so closing this issue.

**Comment by ElDavoo** [comment]
same problem :(

**Comment by tiann** [comment]
I know this but i don't know how to reproduce it and how to verify it.
If you guys don't tell how to verify it step by step, i dont know how to fix it.

**Comment by ElDavoo** [comment]
> If you guys don't tell how to verify it step by step, i dont know how to fix it.

Of course, but that doesn't mean the problem doesn't exist.  
 
Anyway, you're right: The version you installed (4.10.3) actually works. Upgrading it (4.11.5) breaks it, so I guess it's an app bug.

**Comment by tiann** [comment]
I did not deny the existence of the problem. But he didn't even tell me what version it was using. I don't have time to go into the details of every issue, and if nobody provides enough information, I will never fix it.

**Comment by ElDavoo** [comment]
It's ok, we just didn't think the version was important (and obviously it was)

**Comment by tiann** [comment]
If you find a way to reproduce and verity it, welcome to open a new issue.
