### ISSUE TITLE
File managers can't remount system as R/W

### ISSUE THREAD

**Issue by Hikari-no-Tenshi** [tiann/KernelSU#655]
**Describe the bug**
File managers can't remount system as R/W,

**To Reproduce**
1. Go to file manager with root support (tried Root Explorer and MiXplorer)
2. Try to remount system R/W and change/add system files
3. See that file manager can't access system with R/W rights

**Expected behavior**
Root file mangers should be able to remount system as R/W

**Smartphone (please complete the following information):**
 - Device: OnePlus 7
 - OS: Android 11
 - Version: kernel 11012, manager 11007

**Additional context**
[KernelSU_bugreport_2023-06-18_11_04.tar.gz](https://github.com/tiann/KernelSU/files/11780886/KernelSU_bugreport_2023-06-18_11_04.tar.gz)

**Comment by tiann** [comment]
Mounting /system as read-write is a legacy of history, KernelSU will not support it; But if you have a suitable method, feel free to submit a PR.
