### ISSUE TITLE
ChromeOS arcvm中调用/system/bin/sh的应用无法正常使用root权限

### ISSUE THREAD

**Issue by natsumerinchan** [tiann/KernelSU#668]
**阐述bug**
ChromeOS上部分应用授权后实际上无法使用root权限，adb shell无法获取root权限
**复现步骤**
1.在ChromeOS安装KernelSU https://www.reddit.com/r/chromeos/comments/14bwi9r/tutorial_root_your_chromeos_android_subsystem/

2.为应用授权，但发现部分应用授权后实际上没有root权限

**预期行为**
所有应用都能正常授权

**截图**

![photo_2023-06-20_17-39-55](https://github.com/tiann/KernelSU/assets/64072399/e49a1de8-4f84-4239-8450-3b7baf567a0a)

**设备信息 :**
 - Device: x86_64 Desktop
 - OS: ChromeOS(brunch)
 - Version: chromeos_15393.58.0_volteer|brunch_r113_stable_20230603
 - KernelSU Version: https://github.com/tiann/KernelSU/commit/9b2f907a4848786b10cb37bf592c7905e3d87e02
 https://github.com/tiann/KernelSU/actions/runs/5318075425

**日志**

[KernelSU_bugreport_2023-06-20_17_34.tar.gz](https://github.com/tiann/KernelSU/files/11798785/KernelSU_bugreport_2023-06-20_17_34.tar.gz)

**Comment by tiann** [comment]
哪些包名是没有授权的？

**Comment by tiann** [comment]
`sucompat: newfstatat_kp: -2`

**Comment by tiann** [comment]
提供一下 kernel 的源码

**Comment by natsumerinchan** [comment]
> 提供一下 kernel 的源码

https://chromium.googlesource.com/chromiumos/third_party/kernel.git/+/refs/heads/chromeos-5.10-arcvm

**Comment by natsumerinchan** [comment]
> 哪些包名是没有授权的？

只授权了截图里的

**Comment by tiann** [comment]
我不知道你截图的应用对应的包名是什么

**Comment by tiann** [comment]
`/cat /proc/kallsyms > /sdcard/sym.txt` 然后把这个文件传上来

**Comment by natsumerinchan** [comment]
> `/cat /proc/kallsyms > /sdcard/sym.txt` 然后把这个文件传上来

[sym.txt](https://github.com/tiann/KernelSU/files/11798997/sym.txt)

**Comment by natsumerinchan** [comment]
> 我不知道你截图的应用对应的包名是什么

```
me.zhanghai.android.files
yarolegovich.materialterminal
com.sanmer.mrepo
com.yxer.packageinstalles
com.android.shell
```

**Comment by tiann** [comment]
等这个 CI 编译完后再试一下：https://github.com/tiann/KernelSU/commit/cd3e29248979fb41b6edc34395033726716c5cf5

**Comment by natsumerinchan** [comment]
> 等这个 CI 编译完后再试一下：[cd3e292](https://github.com/tiann/KernelSU/commit/cd3e29248979fb41b6edc34395033726716c5cf5)

更新后问题依旧

Manager(11023) + Kernel(11022)

[KernelSU_bugreport_2023-06-20_19_33.tar.gz](https://github.com/tiann/KernelSU/files/11799930/KernelSU_bugreport_2023-06-20_19_33.tar.gz)

**Comment by tiann** [comment]
日志中只看到一个 App 申请 su，你在更新 kernel 后，是否有对这些 App 进行操作？

**Comment by natsumerinchan** [comment]
> 日志中只看到一个 App 申请 su，你在更新 kernel 后，是否有对这些 App 进行操作？

有，我更新后删掉allowlist重新授权了

**Comment by natsumerinchan** [comment]
```
[   30.621027] KernelSU: set root profile, key: me.zhanghai.android.files, uid: 10082, gid: 0, context: u:r:su:s0
[   30.621474] KernelSU: save allow list, name: $ uid :9999, allow: 0
[   30.621488] KernelSU: save allow list, name: me.zhanghai.android.files uid :10082, allow: 1
[   31.684674] init: Untracked pid 216 exited with status 137
[   32.831236] binder: undelivered transaction 91844, process died.
[   32.835406] binder: undelivered transaction 91845, process died.
[   38.252822] KernelSU: set root profile, key: yarolegovich.materialterminal, uid: 10072, gid: 0, context: u:r:su:s0
[   38.253176] KernelSU: save allow list, name: $ uid :9999, allow: 0
[   38.253186] KernelSU: save allow list, name: me.zhanghai.android.files uid :10082, allow: 1
[   38.253192] KernelSU: save allow list, name: yarolegovich.materialterminal uid :10072, allow: 1
[   40.409235] KernelSU: prctl reply error, cmd: 12
[   40.409255] KernelSU: prctl reply error, cmd: 13
[   40.421670] KernelSU: handle umount for uid: 10049
[   40.610209] init: Untracked pid 3415 received signal 9
[   41.276237] KernelSU: set root profile, key: com.sanmer.mrepo, uid: 10087, gid: 0, context: u:r:su:s0
[   41.276631] KernelSU: save allow list, name: $ uid :9999, allow: 0
[   41.276658] KernelSU: save allow list, name: me.zhanghai.android.files uid :10082, allow: 1
[   41.276665] KernelSU: save allow list, name: yarolegovich.materialterminal uid :10072, allow: 1
[   41.276671] KernelSU: save allow list, name: com.sanmer.mrepo uid :10087, allow: 1
[   45.348095] KernelSU: set root profile, key: com.yxer.packageinstalles, uid: 10085, gid: 0, context: u:r:su:s0
[   45.348604] KernelSU: save allow list, name: $ uid :9999, allow: 0
[   45.348617] KernelSU: save allow list, name: me.zhanghai.android.files uid :10082, allow: 1
[   45.348626] KernelSU: save allow list, name: yarolegovich.materialterminal uid :10072, allow: 1
[   45.348635] KernelSU: save allow list, name: com.sanmer.mrepo uid :10087, allow: 1
[   45.348663] KernelSU: save allow list, name: com.yxer.packageinstalles uid :10085, allow: 1
[   47.907893] KernelSU: set root profile, key: com.android.shell, uid: 2000, gid: 0, context: u:r:su:s0
[   47.908297] KernelSU: save allow list, name: $ uid :9999, allow: 0
[   47.908310] KernelSU: save allow list, name: me.zhanghai.android.files uid :10082, allow: 1
[   47.908319] KernelSU: save allow list, name: yarolegovich.materialterminal uid :10072, allow: 1
[   47.908327] KernelSU: save allow list, name: com.sanmer.mrepo uid :10087, allow: 1
[   47.908337] KernelSU: save allow list, name: com.yxer.packageinstalles uid :10085, allow: 1
[   47.908391] KernelSU: save allow list, name: com.android.shell uid :2000, allow: 1
```

**Comment by tiann** [comment]
授权以后有没有操作那些 App？

**Comment by natsumerinchan** [comment]
> 授权以后有没有操作那些 App？

试过在adb shell执行su，依旧提示su不存在

唯一一个能正常使用root权限的shell应用是Termux

[KernelSU_bugreport_2023-06-21_11_49.tar.gz.gz](https://github.com/tiann/KernelSU/files/11812041/KernelSU_bugreport_2023-06-21_11_49.tar.gz.gz)

[sym.txt](https://github.com/tiann/KernelSU/files/11812042/sym.txt)

**Comment by natsumerinchan** [comment]
> > 我不知道你截图的应用对应的包名是什么
> 
> ```
> me.zhanghai.android.files #有效
> yarolegovich.materialterminal #无效
> com.sanmer.mrepo #无效
> com.yxer.packageinstalles #有效
> com.android.shell #无效
> ```

追加
```
com.termux #有效
```

**Comment by tiann** [comment]
我加了一些日志，请在这个 CI 编译完后再试一下：https://github.com/tiann/KernelSU/actions/runs/5330045982/jobs/9656333047?pr=670

**Comment by natsumerinchan** [comment]
> 我加了一些日志，请在这个 CI 编译完后再试一下：https://github.com/tiann/KernelSU/actions/runs/5330045982/jobs/9656333047?pr=670

好的👌

**Comment by natsumerinchan** [comment]
[KernelSU_bugreport_2023-06-21_12_54.tar.gz.gz](https://github.com/tiann/KernelSU/files/11812358/KernelSU_bugreport_2023-06-21_12_54.tar.gz.gz)

**Comment by tiann** [comment]
把 `/data/adb/ksu/.allowlist` 删掉重启，然后重新授权，打开无法授权的应用再发一下日志

**Comment by natsumerinchan** [comment]
> 把 `/data/adb/ksu/.allowlist` 删掉重启，然后重新授权，打开无法授权的应用再发一下日志

好的

[KernelSU_bugreport_2023-06-21_13_05.tar.gz.gz](https://github.com/tiann/KernelSU/files/11812934/KernelSU_bugreport_2023-06-21_13_05.tar.gz.gz)

**Comment by tiann** [comment]
setenforce 0 后能使吗？

**Comment by natsumerinchan** [comment]
> setenforce 0 后能使吗？

还是不能

**Comment by tiann** [comment]
从日志看，能否获取 root 似乎是个随即现象，同一个应用反复关闭打开，结果一致吗？

**Comment by natsumerinchan** [comment]
应该是一致的

[KernelSU_bugreport_2023-06-21_13_47.tar.gz.gz](https://github.com/tiann/KernelSU/files/11813910/KernelSU_bugreport_2023-06-21_13_47.tar.gz.gz)

**Comment by tiann** [comment]
确定内核更新了？看不到更新后的日志

**Comment by natsumerinchan** [comment]
> 确定内核更新了？看不到更新后的日志

内核和管理器都是11023

**Comment by tiann** [comment]
用这个再试一下：https://github.com/tiann/KernelSU/actions/runs/5330757236/jobs/9657773305?pr=670

**Comment by natsumerinchan** [comment]
> 用这个再试一下：https://github.com/tiann/KernelSU/actions/runs/5330757236/jobs/9657773305?pr=670

还是无效，但我怀疑是ci直接编译了main分支而不是arcvm分支，新更改压根没编进去

我在本地获取arcvm分支的commit数为825,而ci还是823,我试试本地编译
```
[celica@arch workdir]$ git clone https://github.com/tiann/KernelSU.git -b arcvm
正克隆到 'KernelSU'...
remote: Enumerating objects: 18904, done.
remote: Counting objects: 100% (1915/1915), done.
remote: Compressing objects: 100% (585/585), done.
remote: Total 18904 (delta 1003), reused 1777 (delta 884), pack-reused 16989
接收对象中: 100% (18904/18904), 14.00 MiB | 1.64 MiB/s, 完成.
处理 delta 中: 100% (10483/10483), 完成.
[celica@arch workdir]$ cd KernelSU/
[celica@arch KernelSU]$ git branch
* arcvm
[celica@arch KernelSU]$ git rev-list --count HEAD
825
[celica@arch KernelSU]$ 
```

**Comment by natsumerinchan** [comment]
现在应该有新日志了

[KernelSU_bugreport_2023-06-21_16_05.tar.gz.gz](https://github.com/tiann/KernelSU/files/11815234/KernelSU_bugreport_2023-06-21_16_05.tar.gz.gz)

**Comment by tiann** [comment]
从日志看，mrepo 获取 su 成功了？

**Comment by natsumerinchan** [comment]
> 从日志看，mrepo 获取 su 成功了？

但实际上没有权限
![Screenshot 2023-06-21 18 52 07](https://github.com/tiann/KernelSU/assets/64072399/89beedef-558d-4752-8651-eae7731f6615)

这是11027的log

[KernelSU_bugreport_2023-06-21_18_51.tar.gz.gz](https://github.com/tiann/KernelSU/files/11816666/KernelSU_bugreport_2023-06-21_18_51.tar.gz.gz)

**Comment by natsumerinchan** [comment]
更新后在swift backup截到的图

授权：
![Screenshot 2023-06-21 20 35 09](https://github.com/tiann/KernelSU/assets/64072399/f396921c-439a-494a-9392-890addea00b0)

未授权：
![Screenshot 2023-06-21 20 35 34](https://github.com/tiann/KernelSU/assets/64072399/ec01be4e-1ed8-4f97-99d6-ad62665ad799)

[KernelSU_bugreport_2023-06-21_20_35.tar.gz.gz](https://github.com/tiann/KernelSU/files/11817556/KernelSU_bugreport_2023-06-21_20_35.tar.gz.gz)

swift backup log
[SwiftLogger Logs.txt](https://github.com/tiann/KernelSU/files/11817570/SwiftLogger.Logs.txt)

**Comment by tiann** [comment]
关掉所有模块后还有这个现象吗？

**Comment by natsumerinchan** [comment]
> 关掉所有模块后还有这个现象吗？

依旧有

**Comment by tiann** [comment]
这些有的能授权，有的不能授权的应用，带有 arm 原生库的有多少？这方面有什么共性吗，因为你的设备是 x86_64 的，如果用 arm 的原生库，可能涉及到转译？内核会直接操作寄存器，可能有问题

**Comment by natsumerinchan** [comment]
> 这些有的能授权，有的不能授权的应用，带有 arm 原生库的有多少？这方面有什么共性吗，因为你的设备是 x86_64 的，如果用 arm 的原生库，可能涉及到转译？内核会直接操作寄存器，可能有问题

```
Material Terminal(yarolegovich.materialterminal) x86 #无效
MRepo(com.sanmer.mrepo) 无原生库 #无效
R-安装组件(com.yxer.packageinstalles) arm64 #有效
Swift Backup(org.swiftapps.swiftbackup) x86_64 #知道自己有root但获取KernelSU版本失败
Termux(com.termux) x86_64 #有效
shell(com.android.shell) 无原生库 #无效
质感文件(me.zhanghai.android.files) x86_64 #有效
```

**Comment by natsumerinchan** [comment]
```
:/ $ busybox sh
/ $ su
sh: su: not found
/ $ /system/bin/su
:/ #
```
我在Material Terminal打开busybox的sh再执行/system/bin/su成功获得root权限了

**Comment by tiann** [comment]
在 adb shell 执行 `/system/bin/su` 可以吗？

**Comment by natsumerinchan** [comment]
套层busybox shell就行
![Screenshot 2023-06-21 21 53 29](https://github.com/tiann/KernelSU/assets/64072399/db898ba7-4eb3-4ff5-ada0-af689c2c08b1)

**Comment by natsumerinchan** [comment]
termux能用root是因为它自带shell
![Screenshot 2023-06-21 21 57 01](https://github.com/tiann/KernelSU/assets/64072399/dc33ef2c-849f-4d95-a814-755055d2c75f)

**Comment by natsumerinchan** [comment]
能正常用root权限的基本都自带sh或busybox

![Screenshot 2023-06-21 22 46 10](https://github.com/tiann/KernelSU/assets/64072399/4e14cf91-6296-4b5b-b749-1983d61c7343) 
![Screenshot 2023-06-21 22 46 45](https://github.com/tiann/KernelSU/assets/64072399/6ee29f44-5fa0-4bbf-9f58-5a2318faac2d)

**Comment by tiann** [comment]
`su -V`, `su -h` 这种能执行吗？

**Comment by natsumerinchan** [comment]
> `su -V`, `su -h` 这种能执行吗？

只能在busybox shell用完整路径执行，进入root后反而用不了

![Screenshot 2023-06-21 23 07 13](https://github.com/tiann/KernelSU/assets/64072399/6ad056fb-be59-4cc7-a839-3710a3f7c360)

**Comment by tiann** [comment]
不在 busybox 中能执行 `su -h`, `su -V` 吗？

**Comment by tiann** [comment]
试试手动集成源码的方式还有这个问题吗？

**Comment by natsumerinchan** [comment]
> 试试手动集成源码的方式还有这个问题吗？

用文档的方式手动集成没过编译

**Comment by tiann** [comment]
> > 不在 busybox 中能执行 `su -h`, `su -V` 吗？
> 
> 不能
> 
> ```
> crosh> shell
> chronos@localhost / $ sudo bash
> localhost / # adb shell
> volteer_cheets:/ $ /system/bin/su
> /system/bin/sh: /system/bin/su: inaccessible or not found
> 127|volteer_cheets:/ $ /system/bin/su -v                
> /system/bin/sh: /system/bin/su: inaccessible or not found
> 127|volteer_cheets:/ $ su -v
> /system/bin/sh: su: inaccessible or not found
> 127|volteer_cheets:/ $ 
> ```

这个新发现的问题是昨天的 commit 引起的，已经 revert 了

**Comment by tiann** [comment]
> > 试试手动集成源码的方式还有这个问题吗？
> 
> 用文档的方式手动集成没过编译
> 
> ```
> /home/celica/workdir/ksu_arcvm/common/fs/open.c:404:14: error: ISO C90 forbids mixing declarations and code [-Werror,-Wdeclaration-after-statement]
>         struct path path;
>                     ^
>   CC      drivers/clk/clk-bulk.o
> 1 error generated.
> make[2]: *** [/home/celica/workdir/ksu_arcvm/common/scripts/Makefile.build:273: fs/open.o] Error 1
> ```

把 `ksu_handle_faccessat(&dfd, &filename, &mode, NULL);` 这一句放在 `struct path path` 后。

**Comment by tiann** [comment]
找到 `vfs_statx` 这个函数，改为这个试试。

```
void __attribute__((no_mangle)) vfs_statx(void) { ... }
```

**Comment by natsumerinchan** [comment]
```
/home/celica/workdir/ksu_arcvm/common/fs/stat.c:176:21: error: unknown attribute 'no_mangle' ignored [-Werror,-Wunknown-attributes]
void __attribute__((no_mangle)) vfs_statx(void)
                    ^~~~~~~~~
/home/celica/workdir/ksu_arcvm/common/fs/stat.c:182:19: error: use of undeclared identifier 'dfd'
        ksu_handle_stat(&dfd, &filename, &flags);
                         ^
/home/celica/workdir/ksu_arcvm/common/fs/stat.c:182:25: error: use of undeclared identifier 'filename'
        ksu_handle_stat(&dfd, &filename, &flags);
                               ^
/home/celica/workdir/ksu_arcvm/common/fs/stat.c:182:36: error: use of undeclared identifier 'flags'
        ksu_handle_stat(&dfd, &filename, &flags);
                                          ^
/home/celica/workdir/ksu_arcvm/common/fs/stat.c:183:6: error: use of undeclared identifier 'flags'
        if (flags & ~(AT_SYMLINK_NOFOLLOW | AT_NO_AUTOMOUNT | AT_EMPTY_PATH |
            ^
/home/celica/workdir/ksu_arcvm/common/fs/stat.c:185:3: error: void function 'vfs_statx' should not return a value [-Wreturn-type]
                return -EINVAL;
                ^      ~~~~~~~
/home/celica/workdir/ksu_arcvm/common/fs/stat.c:187:8: error: use of undeclared identifier 'flags'
        if (!(flags & AT_SYMLINK_NOFOLLOW))
              ^
/home/celica/workdir/ksu_arcvm/common/fs/stat.c:189:8: error: use of undeclared identifier 'flags'
        if (!(flags & AT_NO_AUTOMOUNT))
              ^
/home/celica/workdir/ksu_arcvm/common/fs/stat.c:191:6: error: use of undeclared identifier 'flags'
        if (flags & AT_EMPTY_PATH)
            ^
/home/celica/workdir/ksu_arcvm/common/fs/stat.c:195:23: error: use of undeclared identifier 'dfd'
        error = user_path_at(dfd, filename, lookup_flags, &path);
                             ^
/home/celica/workdir/ksu_arcvm/common/fs/stat.c:195:28: error: use of undeclared identifier 'filename'
        error = user_path_at(dfd, filename, lookup_flags, &path);
                                  ^
/home/celica/workdir/ksu_arcvm/common/fs/stat.c:199:29: error: use of undeclared identifier 'stat'
        error = vfs_getattr(&path, stat, request_mask, flags);
                                   ^
/home/celica/workdir/ksu_arcvm/common/fs/stat.c:199:35: error: use of undeclared identifier 'request_mask'
        error = vfs_getattr(&path, stat, request_mask, flags);
                                         ^
/home/celica/workdir/ksu_arcvm/common/fs/stat.c:199:49: error: use of undeclared identifier 'flags'
        error = vfs_getattr(&path, stat, request_mask, flags);
                                                       ^
/home/celica/workdir/ksu_arcvm/common/fs/stat.c:200:2: error: must use 'struct' tag to refer to type 'stat'
        stat->mnt_id = real_mount(path.mnt)->mnt_id;
        ^
        struct 
/home/celica/workdir/ksu_arcvm/common/fs/stat.c:200:6: error: expected identifier or '('
        stat->mnt_id = real_mount(path.mnt)->mnt_id;
            ^
/home/celica/workdir/ksu_arcvm/common/fs/stat.c:201:2: error: must use 'struct' tag to refer to type 'stat'
        stat->result_mask |= STATX_MNT_ID;
        ^
        struct 
/home/celica/workdir/ksu_arcvm/common/fs/stat.c:201:6: error: expected identifier or '('
        stat->result_mask |= STATX_MNT_ID;
            ^
/home/celica/workdir/ksu_arcvm/common/fs/stat.c:203:3: error: must use 'struct' tag to refer to type 'stat'
                stat->attributes |= STATX_ATTR_MOUNT_ROOT;
                ^
                struct 
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [/home/celica/workdir/ksu_arcvm/common/scripts/Makefile.build:273: fs/stat.o] Error 1
make[1]: *** [/home/celica/workdir/ksu_arcvm/common/Makefile:1917: fs] Error 2
make[1]: *** 正在等待未完成的任务....
```

**Comment by tiann** [comment]
把 static 去掉应该也可以

**Comment by natsumerinchan** [comment]
手动集成+去掉static=所有应用都用不了root了，模块倒是正常工作

**Comment by tiann** [comment]
手动集成的时候，`ksu_handle_stat` 你是加在哪里？

**Comment by natsumerinchan** [comment]
![截图 2023-06-22 17-43-43](https://github.com/tiann/KernelSU/assets/64072399/68d3636f-95b5-46f5-9365-23bfb2a0ecb4)

**Comment by bags432** [comment]
遇到和楼主差不多的情况，adb获取不到root权限，但是MT管理器这些app正常，切换0.5.7版本管理器无法为任何app授予root权限

**Comment by natsumerinchan** [comment]
> 听说更新到 0.6.1 了。 但是 Releases 这里没看到 ARCVM 的。 ![image](https://user-images.githubusercontent.com/69227436/248465045-324f7106-e1dd-4089-89c5-bf1705170f34.png)

因为还没修改release.yml

**Comment by natsumerinchan** [comment]
找到了个临时的解决方法，装好busybox模块后把kernelsu源码中所有的/system/bin/sh替换为/system/bin/ash，再写个模块模拟su文件

```
#!/system/bin/ash

/system/bin/su "$@"
```

![Screenshot 2023-06-25 19 45 36](https://github.com/tiann/KernelSU/assets/64072399/c9be19ab-217e-470c-84ad-15881e23d6ab)

**Comment by tiann** [comment]
这个问题的原因是 kprobe stat 失败了。之所以你会看到 busybox 能使系统 sh 不行是因为系统 sh 用的是 statx 而 busybox 用的是 stat。stat 这个东西在 x86_64 和 arm64 上有细微区别，不过我没时间也没机子去测试。
我很奇怪为什么手动集成也有问题，很可能是 stat hook 的地方漏掉了什么，你可以在 fa/stat.c 那几个系统调用那里加点日志，看看系统 sh 走的哪里。

**Comment by supechicken** [comment]
我現在是在 `115.0.5790.94` beta, 能用沒有問題

**Comment by supechicken** [comment]
```
$ file vmlinux.ksu
vmlinux.ksu: Linux kernel x86 boot executable bzImage, version 5.10.184-android12-9-gf525b45859c7 (runner@fv-az96-395) #1 SMP PREEMPT Fri Jul 7 17:24:45 UTC 2023, RO-rootFS, swap_dev 0X9, Normal VGA
$ file vmlinux.orig
vmlinux.orig: Linux kernel x86 boot executable bzImage, version 5.10.176-988157-g288f0650f5bc (chrome-bot@chromeos-release-builder-us-central1-b-x32-7-5wha) #1 SMP PREEMPT Tue Jul 11 19:02:36, RO-rootFS, swap_dev 0X9, Normal VGA
$ ls -la vmlinux
lrwxrwxrwx. 1 root root 11 Jul 19 18:54 vmlinux -> vmlinux.ksu
```

**Comment by supechicken** [comment]
![Screenshot 2023-07-24 18 29 14](https://github.com/tiann/KernelSU/assets/73414985/b1094052-cba5-4718-9eea-a87c7ed94379)

**Comment by supechicken** [comment]
@1457384613gh 不要用`defconfig`, 那是 Linux mainline 的預設最小配置（很多驅動都沒有啟用，開不了機很正常）

試試看用`chromeos/config/chromeos/x86_64`裡面的 config（裡面有幾個config, 看心情隨便選一個）, 那些才是 ChromeOS 用的。

簡單點來說就是跳過`make defconfig`, 把 `chromeos/config/chromeos/x86_64/chromiumos-x86_64.flavour.config` 拷到源碼主目錄的 `.config` 就行了。

**Comment by supechicken** [comment]
等我一下，我幫你整理一下

**Comment by supechicken** [comment]
> 大佬，你可不可以帮我写这个部分？

自己寫吧，其實理解了的話真的很簡單，~~編譯真正的 Android 手機內核才叫噁心~~。

### 以下都是基於 [`chromeos-5.4`](https://chromium.googlesource.com/chromiumos/third_party/kernel/+/refs/heads/chromeos-5.4) 分支中的位置
---
## 1. 生成 config
合併以下文件以獲得一個完整的 kernel config
- `chromeos/config/chromeos/x86_64/chromiumos-x86_64.flavour.config` (x86 ChromiumOS 專用)
- `chromeos/config/chromeos/x86_64/common.config` (x86 專用)
- `chromeos/config/chromeos/base.config` (通用)

```shell
# 合併
./scripts/kconfig/merge_config.sh -m chromeos/config/... chromeos/config/... chromeos/config/...
# 此時 .config 應該出現在源碼根目錄上面了
```

### Brunch 大致上也是這麼做的，不過在此之上關了模塊壓縮還有除錯支持
https://github.com/sebanc/brunch/blob/abb5566b696e83ba0d1ec490ff2743bd93dd25d1/prepare_kernels.sh#L34-L38

## 2. 打補丁
就按你上面的 CI workflow 那樣做就好了 (Apply FydeOS patches + Setup KernelSU)

## 3. 關掉警告自動報錯
不然編譯器可能會因為一些小事報錯
```shell
make menuconfig # 進 config ui
# 進 general setup > 關掉 Compile the kernel with warnings as errors
# 儲存推出

```

## 3. 開始構建
這裡沒什麼好說的，報錯的話看看是不是裝漏了什麼包
```shell
make -j$(nproc) bzImage modules
```

**Comment by supechicken** [comment]
@1457384613gh 先試試，報錯的話請先google, 不行的話再問。我當初也是這樣摸索出來的

**Comment by supechicken** [comment]
`vim` 是交互性的（有鍵盤才能用），在腳本中請用 `sed`

**Comment by supechicken** [comment]
對，不過 github ci 在公開 repo 上是無限任用的，不用太擔心

**Comment by tiann** [comment]
我开启了 `Discussion`，请移步这里讨论：https://github.com/tiann/KernelSU/discussions；不要在 issue 下讨论 off-topic 的问题。

**Comment by tiann** [comment]
这个 issue 我会 lock，如果依然有兴趣并希望解决 ChromeOS 里面的这个问题，欢迎另开 issue。
