### ISSUE TITLE
Show undefined reference to `ksu_vfs_read_hook'

### ISSUE THREAD

**Issue by anuragpindoriya** [tiann/KernelSU#669]
while compiling 

fs/read_write.o: In function `vfs_read':
/home/anurag/Desktop/android_kernal_SM-A107F/out/../fs/read_write.c:451: undefined reference to `ksu_vfs_read_hook'
/home/anurag/Desktop/android_kernal_SM-A107F/toolchains/aarch64-linux-android-4.9/bin/aarch64-linux-android-ld: fs/read_write.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against external symbol `ksu_vfs_read_hook' can not be used when making a shared object; recompile with -fPIC
/home/anurag/Desktop/android_kernal_SM-A107F/out/../fs/read_write.c:451: undefined reference to `ksu_vfs_read_hook'
fs/exec.o: In function `do_execveat_common':
/home/anurag/Desktop/android_kernal_SM-A107F/out/../fs/exec.c:1879: undefined reference to `ksu_execveat_hook'
/home/anurag/Desktop/android_kernal_SM-A107F/toolchains/aarch64-linux-android-4.9/bin/aarch64-linux-android-ld: fs/exec.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against external symbol `ksu_execveat_hook' can not be used when making a shared object; recompile with -fPIC
/home/anurag/Desktop/android_kernal_SM-A107F/out/../fs/exec.c:1879: undefined reference to `ksu_execveat_hook'
drivers/tty/tty_io.o: In function `tty_line_name':
/home/anurag/Desktop/android_kernal_SM-A107F/out/../drivers/tty/tty_io.c:1137: undefined reference to `stpcpy'
drivers/usb/class/usblp.o: In function `ieee1284_id_show':
/home/anurag/Desktop/android_kernal_SM-A107F/out/../drivers/usb/class/usblp.c:1083: undefined reference to `stpcpy'
drivers/usb/gadget/meta.o: In function `iManufacturer_show':
/home/anurag/Desktop/android_kernal_SM-A107F/out/../drivers/usb/gadget/meta.c:938: undefined reference to `stpcpy'
drivers/usb/gadget/meta.o: In function `iProduct_show':
/home/anurag/Desktop/android_kernal_SM-A107F/out/../drivers/usb/gadget/meta.c:939: undefined reference to `stpcpy'
drivers/usb/gadget/meta.o: In function `iSerial_show':
/home/anurag/Desktop/android_kernal_SM-A107F/out/../drivers/usb/gadget/meta.c:940: undefined reference to `stpcpy'
drivers/input/input.o: In function `input_handle_event':
/home/anurag/Desktop/android_kernal_SM-A107F/out/../drivers/input/input.c:380: undefined reference to `ksu_input_hook'
/home/anurag/Desktop/android_kernal_SM-A107F/toolchains/aarch64-linux-android-4.9/bin/aarch64-linux-android-ld: drivers/input/input.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against external symbol `ksu_input_hook' can not be used when making a shared object; recompile with -fPIC
/home/anurag/Desktop/android_kernal_SM-A107F/out/../drivers/input/input.c:380: undefined reference to `ksu_input_hook'
drivers/input/touchscreen/mediatek/ipio_touch_driver/core/parser.o: In function `core_parser_get_int_data':
/home/anurag/Desktop/android_kernal_SM-A107F/out/../drivers/input/touchscreen/mediatek/ipio_touch_driver/core/parser.c:492: undefined reference to `stpcpy'
make[1]: *** [/home/anurag/Desktop/android_kernal_SM-A107F/Makefile:1137: vmlinux] Error 1
make[1]: Leaving directory '/home/anurag/Desktop/android_kernal_SM-A107F/out'
make: *** [Makefile:146: sub-make] Error 2
make: Leaving directory '/home/anurag/Desktop/android_kernal_SM-A107F' 

show this error how i fix this error
KernelVersion is 4.19.127
Phone :- Samsung a10s

**Comment by Coconutat** [comment]
If you use Manual integration of KernelSU,You need Disable KPROBES.

**Comment by anuragpindoriya** [comment]
> If you use Manual integration of KernelSU,You need Disable KPROBES.

how i do this can you help me to do this

**Comment by Coconutat** [comment]
> > If you use Manual integration of KernelSU,You need Disable KPROBES.
> 
> how i do this can you help me to do this

Well,Find your defconfig,then find:
`
CONFIG_KPROBES=y
CONFIG_HAVE_KPROBES=y
CONFIG_KPROBE_EVENTS=y
`
Then do this:
`
# CONFIG_KPROBES is not set
# CONFIG_HAVE_KPROBES is not set
# CONFIG_KPROBE_EVENTS is not set
`
Then read this:[guide](https://kernelsu.org/guide/how-to-integrate-for-non-gki.html)
JUST REMEMBER!Look directly at this section :Manully modify the kernel source.

**Comment by anuragpindoriya** [comment]
I send a my repo link can anybody verify it 
https://github.com/anuragpindoriya/android_kernel_SM-A107F/tree/kernel-su

**Comment by Coconutat** [comment]
> I send a my repo link can anybody verify it https://github.com/anuragpindoriya/android_kernel_SM-A107F/tree/kernel-su

The compiler demonstrated a possible solution by adding a compilation parameter, - fPIC. 
Like: make -jxx -fPIC

I'm not sure if your compiler was chosen correctly. I usually use [Proton Clang](https://github.com/kdrag0n/proton-clang).

**Comment by anuragpindoriya** [comment]
> > I send a my repo link can anybody verify it https://github.com/anuragpindoriya/android_kernel_SM-A107F/tree/kernel-su
> 
> The compiler demonstrated a possible solution by adding a compilation parameter, - fPIC. Like: make -jxx -fPIC
> 
> I'm not sure if your compiler was chosen correctly. I usually use [Proton Clang](https://github.com/kdrag0n/proton-clang).

#!/bin/bash

export CROSS_COMPILE=$(pwd)/toolchains/aarch64-linux-android-4.9/bin/aarch64-linux-android-
export CC=$(pwd)/toolchains/clang-r428724/bin/clang
export CLANG_TRIPLE=aarch64-linux-gnu-
export ARCH=arm64
export ANDROID_MAJOR_VERSION=r

export KCFLAGS=-w
export CONFIG_SECTION_MISMATCH_WARN_ONLY=y

make -C $(pwd) O=$(pwd)/out KCFLAGS=-w CONFIG_SECTION_MISMATCH_WARN_ONLY=y a10s_defconfig
make -C $(pwd) O=$(pwd)/out KCFLAGS=-w CONFIG_SECTION_MISMATCH_WARN_ONLY=y -j8

cp out/arch/arm64/boot/Image $(pwd)/arch/arm64/boot/Image

this is my build script

**Comment by anuragpindoriya** [comment]
#THIS IS MY BUILD SCRIPT

#!/bin/bash

export CROSS_COMPILE=$(pwd)/toolchains/aarch64-linux-android-4.9/bin/aarch64-linux-android-
export CC=$(pwd)/toolchains/clang-r428724/bin/clang
export CLANG_TRIPLE=aarch64-linux-gnu-
export ARCH=arm64
export ANDROID_MAJOR_VERSION=r

export KCFLAGS=-w
export CONFIG_SECTION_MISMATCH_WARN_ONLY=y

make -C $(pwd) O=$(pwd)/out KCFLAGS=-w CONFIG_SECTION_MISMATCH_WARN_ONLY=y a10s_defconfig

# YOU CAN SEE HERE I ADDED FLAG----------------------------------------------------------------------------->
make -C $(pwd) O=$(pwd)/out KCFLAGS=-w CONFIG_SECTION_MISMATCH_WARN_ONLY=y -j8 -fPIC

# cp out/arch/arm64/boot/Image $(pwd)/arch/arm64/boot/Image


And After Getting This 

make: Entering directory '/home/anurag/Desktop/android_kernel_SM-A107F'
make[1]: Entering directory '/home/anurag/Desktop/android_kernel_SM-A107F/out'
  HOSTCC  scripts/basic/fixdep
  GEN     ./Makefile
  HOSTCC  scripts/kconfig/conf.o
  YACC    scripts/kconfig/zconf.tab.c
  LEX     scripts/kconfig/zconf.lex.c
  HOSTCC  scripts/kconfig/zconf.tab.o
  HOSTLD  scripts/kconfig/conf
drivers/muic/Kconfig:346: warning: 'MUIC_TEST_FUNC' defined with more than one help text -- only the last one will be used
#
# configuration written to .config
#
make[1]: Leaving directory '/home/anurag/Desktop/android_kernel_SM-A107F/out'
make: Leaving directory '/home/anurag/Desktop/android_kernel_SM-A107F'
make: Entering directory '/home/anurag/Desktop/android_kernel_SM-A107F'
make: PIC: No such file or directory
make: *** No rule to make target 'PIC'.  Stop.
make: Leaving directory '/home/anurag/Desktop/android_kernel_SM-A107F'

**Comment by tiann** [comment]
`cd KernelSU && git pull`

**Comment by Coconutat** [comment]
> #THIS IS MY BUILD SCRIPT
> 
> #!/bin/bash
> 
> export CROSS_COMPILE=$(pwd)/toolchains/aarch64-linux-android-4.9/bin/aarch64-linux-android- export CC=$(pwd)/toolchains/clang-r428724/bin/clang export CLANG_TRIPLE=aarch64-linux-gnu- export ARCH=arm64 export ANDROID_MAJOR_VERSION=r
> 
> export KCFLAGS=-w export CONFIG_SECTION_MISMATCH_WARN_ONLY=y
> 
> make -C (pwd)O=(pwd)/out KCFLAGS=-w CONFIG_SECTION_MISMATCH_WARN_ONLY=y a10s_defconfig
> 
> # YOU CAN SEE HERE I ADDED FLAG----------------------------------------------------------------------------->
> make -C (pwd)O=(pwd)/out KCFLAGS=-w CONFIG_SECTION_MISMATCH_WARN_ONLY=y -j8 -fPIC
> 
> # cp out/arch/arm64/boot/Image $(pwd)/arch/arm64/boot/Image
> And After Getting This
> 
> make: Entering directory '/home/anurag/Desktop/android_kernel_SM-A107F' make[1]: Entering directory '/home/anurag/Desktop/android_kernel_SM-A107F/out' HOSTCC scripts/basic/fixdep GEN ./Makefile HOSTCC scripts/kconfig/conf.o YACC scripts/kconfig/zconf.tab.c LEX scripts/kconfig/zconf.lex.c HOSTCC scripts/kconfig/zconf.tab.o HOSTLD scripts/kconfig/conf drivers/muic/Kconfig:346: warning: 'MUIC_TEST_FUNC' defined with more than one help text -- only the last one will be used
> 
> # configuration written to .config
> make[1]: Leaving directory '/home/anurag/Desktop/android_kernel_SM-A107F/out' make: Leaving directory '/home/anurag/Desktop/android_kernel_SM-A107F' make: Entering directory '/home/anurag/Desktop/android_kernel_SM-A107F' make: PIC: No such file or directory make: *** No rule to make target 'PIC'. Stop. make: Leaving directory '/home/anurag/Desktop/android_kernel_SM-A107F'

I am not sure.But,I always add this  export CC=Clang.
Like this:
export PATH=$PATH:/home/coconutat/github/proton-clang-master/bin
export CC=clang
export CLANG_TRIPLE=aarch64-linux-gnu-
export CROSS_COMPILE=aarch64-linux-gnu-
export CROSS_COMPILE_ARM32=arm-linux-gnueabi-

export ARCH=arm64
export SUBARCH=arm64

make ARCH=arm64 O=out CC=clang radioactive_ksu_defconfig

make ARCH=arm64 O=out CC=clang -j24 2>&1 | tee kernel_log-${date}.txt

**Comment by tiann** [comment]
Why do you completely ignore compiler errors when compiling the kernel? The error messages here are already very clear:

> fs/read_write.o: In function vfs_read': /home/anurag/Desktop/android_kernal_SM-A107F/out/../fs/read_write.c:451: undefined reference to ksu_vfs_read_hook'

**Comment by anuragpindoriya** [comment]
> Why do you completely ignore compiler errors when compiling the kernel? The error messages here are already very clear:
> 
> > fs/read_write.o: In function vfs_read': /home/anurag/Desktop/android_kernal_SM-A107F/out/../fs/read_write.c:451: undefined reference to ksu_vfs_read_hook'

How do i fix this

**Comment by tiann** [comment]
Check your KernelSU, make sure it is up to date with the latest commit, and that the variable `ksu_vfs_read_hook` exists in the code.

**Comment by anuragpindoriya** [comment]
CC      drivers/usb/storage/sddr09.o
  CC      drivers/usb/storage/sddr55.o
  CC      drivers/usb/storage/shuttle_usbat.o
  AR      drivers/usb/storage/built-in.a
  AR      drivers/usb/built-in.a
  AR      drivers/built-in.a
make[1]: Leaving directory '/home/runner/work/kernel_builder/kernel_builder/out'
make: *** [Makefile:146: sub-make] Error 2
Error: Process completed with exit code 2.

can anybody help me to solve this

**Comment by Coconutat** [comment]
> CC drivers/usb/storage/sddr09.o CC drivers/usb/storage/sddr55.o CC drivers/usb/storage/shuttle_usbat.o AR drivers/usb/storage/built-in.a AR drivers/usb/built-in.a AR drivers/built-in.a make[1]: Leaving directory '/home/runner/work/kernel_builder/kernel_builder/out' make: *** [Makefile:146: sub-make] Error 2 Error: Process completed with exit code 2.
> 
> can anybody help me to solve this

Hello,I give you a PR,but you not answer me.Please Check it.

**Comment by Coconutat** [comment]
> CC drivers/usb/storage/sddr09.o CC drivers/usb/storage/sddr55.o CC drivers/usb/storage/shuttle_usbat.o AR drivers/usb/storage/built-in.a AR drivers/usb/built-in.a AR drivers/built-in.a make[1]: Leaving directory '/home/runner/work/kernel_builder/kernel_builder/out' make: *** [Makefile:146: sub-make] Error 2 Error: Process completed with exit code 2.
> 
> can anybody help me to solve this

Check this,Please.
https://github.com/anuragpindoriya/android_kernel_SM-A107F/pull/1

**Comment by Hargriv** [comment]
Hi all I'm trying to build the kernel for my Samsung Note 20Ultra SM-N986B OneUI5.1 Android 13 N986BXXU6HWCC kernel base(4.19.87)  downloaded from official Samsung sources The error occurs when I add a driver for kernelSU to the kernel source code taken from https://github.com/tiann/KernelSU/releases

console output

AR drivers/built-in.a
GEN .version
CHK include/generated/compile.h
AR built-in.a
MODPOST vmlinux.o
WARNING: vmlinux: 'fpsensor_goto_suspend' exported twice. Previous export was in vmlinux
WARNING: vmlinux: 'fpsensor_goto_suspend' exported twice. Previous export was in vmlinux
WARNING: modpost: Found 2 section mismatch(es).
To see full details build your kernel with:
'make CONFIG_DEBUG_SECTION_MISMATCH=y'
fs/open.o: In function `do_faccessat':
/home/hargriv/Note-20/kernel-986b/fs/open.c:374: undefined reference to `ksu_handle_faccessat'
fs/read_write.o: In function `vfs_read':
/home/hargriv/Note-20/kernel-986b/fs/read_write.c:453: undefined reference to `ksu_handle_vfs_read'
fs/stat.o: In function `vfs_statx':
/home/hargriv/Note-20/kernel-986b/fs/stat.c:176: undefined reference to `ksu_handle_stat'
fs/exec.o: In function `__do_execve_file':
/home/hargriv/Note-20/kernel-986b/fs/exec.c:1894: undefined reference to `ksu_handle_execveat'
make: *** [Makefile:1128: vmlinux] Error 1

Please help me understand and fix this problem
