### ISSUE TITLE
关于kernelsu的检测

### ISSUE THREAD

**Issue by a2504028411** [tiann/KernelSU#671]
kernlesu在version中留下字符串信息是否会导致成为检查点

bool kernelsuCheck() {
    struct utsname systemInfo;

    if (uname(&systemInfo) < 0) {
        return false;
    }
    return strstr(systemInfo.release, "KernelSU") != NULL;
}

**Comment by tiann** [comment]
KernelSU 官方没有改这个东西，应该是你的内核维护者改的。
