### ISSUE TITLE
Error: no space left on device

### ISSUE THREAD

**Issue by rushiranpise** [tiann/KernelSU#672]
**Describe the bug**
Strange bug Randomly occurs
Can't install modules with small/big size 
For eg : YouTube revanced by j-hc, Pixelify etc

Currently I got it while installing ZygiskforKSU

I have Pixelify and Yt revanced installed and other few modules

**To Reproduce**
1. Install Module
2. See error

**Screenshots**
![Screenshot_20230622-014421_KernelSU](https://github.com/tiann/KernelSU/assets/37355997/55104f23-f6eb-4373-b616-550fa4c48c1b)

[KernelSU_install_log_2023-06-22-01-44-10.log](https://github.com/tiann/KernelSU/files/11825687/KernelSU_install_log_2023-06-22-01-44-10.log)

[KernelSU_bugreport_2023-06-22_01_44.tar.gz](https://github.com/tiann/KernelSU/files/11825847/KernelSU_bugreport_2023-06-22_01_44.tar.gz)

**Smartphone
/:**
 - Device: Samsung Galaxy A50
 - OS: Android OneUi 4
 - Version: 12

**Additional context**
Have seen similar issue in tg group discussion

For now if want to install any modules with big size then,
Have to first remove all modules 
then install the bigger module than install rest 

Also if there is any limit of size of module for ksu?

**Comment by tiann** [comment]
Please upload the module

**Comment by rushiranpise** [comment]
> Please upload the module

I was updating the zygiskforksu module when I got this error,

https://github.com/Dr-TSNG/ZygiskOnKernelSU/releases/download/v4-0.7.1/Zygisk-on-KernelSU-v4-0.7.1-89-release.zip

YouTube RV:
https://github.com/j-hc/revanced-magisk-module/releases/download/20220872/youtube-revanced-magisk-v18.19.35-all.zip

Pixelify: ( have to use [no volume key method](https://github.com/Kingsman44/Pixelify#installation-without-volume-keys) )
https://www.pling.com/p/1794976/

**Comment by tiann** [comment]
try this one: https://github.com/tiann/KernelSU/actions/runs/5343503289

**Comment by rushiranpise** [comment]
> try this one: [tiann/KernelSU/actions/runs/5343503289](https://github.com/tiann/KernelSU/actions/runs/5343503289)

Thanks for the quick fix!! 🫡
It works now..
I was able to install other modules too that are larger in size!!
