### ISSUE TITLE
Complie Error

### ISSUE THREAD

**Issue by wxt1221** [tiann/KernelSU#673]
../drivers/kernelsu/core_hook.c:70:2: error: 'for' loop initial declarations are only allowed in C99 or C11 mode
  for (int i = 0; i < ngroups; i++) {
  ^
../drivers/kernelsu/core_hook.c:224:29: warning: passing argument 2 of 'copy_from_user' makes pointer from integer without a cast
../drivers/kernelsu/ksud.c:301:2: warning: format '%d' expects argument of type 'int', but argument 4 has type 'size_t' [-Wformat=]

g++4.9.x

**Comment by tiann** [comment]
READ the logs, it is clear.
