### ISSUE TITLE
redmi k40g 内核4.1.4.186 使用手动修改内核源码的方式  更新到0.6.1后屏幕闪烁的问题

### ISSUE THREAD

**Issue by fuguiKz** [tiann/KernelSU#683]
**Describe the bug**
redmi k40g 天玑处理器 D1200 ,内核版本  4.14.186 ，在v0.6.0时第一次尝试使用 kprobe 集成无法开机，后使用手动修改内核源码的方式在v0.6.0 10981版本上 成功开机并运行良好。但更新到v 0.6.1 11041后进行编译后刷入则会2秒闪屏一次，管理器与模块均运行良好，只有屏幕会闪烁这个bug，十分影响使用。
**To Reproduce**
1.使用此机型的安卓11 内核源码https://github.com/Tkpointz/android_kernel_aresin
我按照教程进行手动修改内核代码。
<img width="781" alt="image" src="https://github.com/tiann/KernelSU/assets/74097723/b9fa317b-8c72-458f-98c2-3084f0843abd">
2.修改后使用以下脚本进行编译前预处理并打开menuconfig进行检查。
```shell
#!/bin/bash
make clean && rm -rf out
ccache -M 10G
export ARCH=arm64
export SUBARCH=arm64
export PATH="/home/kz/proton-clang/bin:$PATH"
mkdir out
args="-j$(nproc --all) \
ARCH=arm64 \
SUBARCH=arm64 \
O=out \
CC=clang \
CROSS_COMPILE=aarch64-linux-gnu- \
CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
CLANG_TRIPLE=aarch64-linux-gnu- \
AR=llvm-ar \
NM=llvm-nm \
OBJCOPY=llvm-objcopy \
OBJDUMP=llvm-objdump \
STRIP=llvm-strip "
make ${args} mrproper
make ${args} aresin_defconfig
make ${args} menuconfig
make ${args} prepare
``` 
[defconfig使用源码中arch/arm64/configs中自带的aresin_defconfig，未做任何修改。](https://github.com/Tkpointz/android_kernel_aresin/blob/lxr/arch/arm64/configs/aresin_defconfig)

<img width="1280" alt="image" src="https://github.com/tiann/KernelSU/assets/74097723/e245e614-1480-4392-b1b1-20193796056c">
<img width="1280" alt="Snipaste_2023-06-24_08-11-54" src="https://github.com/tiann/KernelSU/assets/74097723/da253c69-18b3-4c23-9f16-0877be7253fa">
redmi k40g 使用v0.6.0  10981 进行编译前修改配置module support中这三个配置中的任何一个后编译出内核刷入都会导致闪屏，有时甚至在twrp中都会闪屏。不进行修改则在10981版本上运行良好，不会闪屏。

但在最新的v0.6.1   11041 版本上编译，哪怕module support 保持原样，编译后仍会闪屏。闪屏频率大概在2秒闪一次。

3.使用以下脚本进行编译。

```shell
#!/bin/bash
export ARCH=arm64
export SUBARCH=arm64
export PATH="/home/kz/proton-clang/bin:$PATH"
mkdir out
args="-j$(nproc --all) \
ARCH=arm64 \
SUBARCH=arm64 \
O=out \
CC=clang \
CROSS_COMPILE=aarch64-linux-gnu- \
CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
CLANG_TRIPLE=aarch64-linux-gnu- \
AR=llvm-ar \
NM=llvm-nm \
OBJCOPY=llvm-objcopy \
OBJDUMP=llvm-objdump \
STRIP=llvm-strip "
make ${args} savedefconfig
make ${args} 2>&1 | tee kernel.log
make ${args} INSTALL_MOD_PATH="." INSTALL_MOD_STRIP=1 modules_install
``` 

4.升级步骤
我在内核根目录重新运行了以下命令
```shell
curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s v0.6.1
``` 
我认为这应该成功将代码更新到了v0.6.1，然后重新执行2到3的步骤进行编译，后续编译开机后内核版本确实显示了11041并且运行良好。但出现了闪屏问题。

**Expected behavior**
希望任何知晓这个问题原因的开发者能帮助我解决这个闪屏bug.

**Smartphone:**
 - Device: [redmi k40g ]
 - OS: [miui 12.5.12]
 -Android Version [android 11]
 - Kernel Version [v4.14.186]
 - Kernelsu Version [v0.6.1 11041]
 -  [Original Kernel Code](https://github.com/Tkpointz/android_kernel_aresin)

**Comment by tiann** [comment]
几个建议：

1. 不要寄希望于开发者能够把你的内核源码编译一遍亲自试一下，我们没有跟你一样的设备，所以说再多也不如一份日志实在。
2. 如果你确定是由于 KernelSU 0.6.0 -> 0.6.1 升级引起的，你可以逐步 revert，看看是哪个 commit 导致的。由于 kernel 修改的代码不多，如果真的有问题，我觉得只可能与这个 https://github.com/tiann/KernelSU/commit/79bb9813efbb8e56bdf9fc2a64088f40f2425faf commit 有关。
3. 编译之前 clean 一下，不要让之前的代码有干扰。

**Comment by fuguiKz** [comment]
> 几个建议：
> 
> 1. 不要寄希望于开发者能够把你的内核源码编译一遍亲自试一下，我们没有跟你一样的设备，所以说再多也不如一份日志实在。
> 2. 如果你确定是由于 KernelSU 0.6.0 -> 0.6.1 升级引起的，你可以逐步 revert，看看是哪个 commit 导致的。由于 kernel 修改的代码不多，如果真的有问题，我觉得只可能与这个 [79bb981](https://github.com/tiann/KernelSU/commit/79bb9813efbb8e56bdf9fc2a64088f40f2425faf) commit 有关。
> 3. 编译之前 clean 一下，不要让之前的代码有干扰。

经过多次尝试，发现在 [bd8434f](https://github.com/tiann/KernelSU/commit/bd8434f4f4f3e631f66d36ad8afdf7a4201c4851) commit之后（包括此commit）均会闪屏，在此之前的commit不会闪屏。
<img width="1258" alt="image" src="https://github.com/tiann/KernelSU/assets/74097723/d5eb7200-b48d-426a-bb3f-d7fe877cc10c">
附带bd8434f 编译后开机的日志，不知道能不能看到啥原因导致的闪屏。
[KernelSU_bugreport_2023-06-24_16_08.tar.gz](https://github.com/tiann/KernelSU/files/11855976/KernelSU_bugreport_2023-06-24_16_08.tar.gz)

**Comment by tiann** [comment]
如果你是手动集成的话，从这个 commit 后，手动集成的代码更新了，文档也更新了，你需要用新的方式去集成。

**Comment by tiann** [comment]
还有，你最好先排除模块的影响。
