### ISSUE TITLE
加密shell脚本无法被sh执行

### ISSUE THREAD

**Issue by woshigenm** [tiann/KernelSU#685]
**Describe the bug**
模块内安装shell脚本被加密成可执行文件，无法被sh执行

**To Reproduce**
1. 使用kernelsu管理器安装模块
2. 安装失败

**Expected behavior**
安装成功
**Screenshots**
![Screenshot_2023-06-24-16-26-39-888_me weishu #kernelsu](https://github.com/tiann/KernelSU/assets/99122353/6b498e01-2b65-47f5-bd65-148c4aea89fa)

**Smartphone (please complete the following information):**
 - RedMi K50
 - Android 13
 - 5.10.101-android12

**Additional context**
安装模块
[miui-monet-v10.0.0-anniversary_release.zip](https://github.com/tiann/KernelSU/files/11855975/miui-monet-v10.0.0-anniversary_release.zip)
在Magisk上安装成功

**Comment by tiann** [comment]
修不了，鬼知道它加密了什么，说不定它在里面用了 Magisk 独有的环境变量呢，什么日志也没有。
