### ISSUE TITLE
selinux 的部分规则设置问题

### ISSUE THREAD

**Issue by Debug-boy** [tiann/KernelSU#688]
**设备内核源码仓库地址 https://github.com/izsdeaman97/NX659J_R_kernel.git**
- 内核版本:[4.19.113]
- 内核已经成功编译正常开机
- 问题是内核的的kprobe好像没有正常,然后我对照官网 https://kernelsu.org/zh_CN/guide/how-to-integrate-for-non-gki.html#using-kprobes 手动修补了内核源码的 do_faccessat   do_execveat_common  vfs_read vfs_statx  这四个函数的 ksu所实现的ksu_handle_xxx一类的函数,
在被修补的do_execveat_common当中会被调用 ksu_handle_execveat_ksud , 紧接着会 apply_kernelsu_rules();
在apply_kernelsu_rules();里我注释掉的这些规则条目如果开启都会开机卡死

	  rcu_read_lock();
	  struct policydb *db = get_policydb();
  
	  ksu_permissive(db, KERNEL_SU_DOMAIN);
	  ksu_typeattribute(db, KERNEL_SU_DOMAIN, "mlstrustedsubject");
	  ksu_typeattribute(db, KERNEL_SU_DOMAIN, "netdomain");
	  ksu_typeattribute(db, KERNEL_SU_DOMAIN, "bluetoothdomain");
  
	  
	  // Create unconstrained file type
	  //ksu_type(db, KERNEL_SU_FILE, "file_type"); //error !!
	  
	  
	  ksu_typeattribute(db, KERNEL_SU_FILE, "mlstrustedobject");
  
	  
	  ksu_allow(db, ALL, KERNEL_SU_FILE, ALL, ALL);
  
	  
	  // allow all!
	  //ksu_allow(db, KERNEL_SU_DOMAIN, ALL, ALL, ALL); //error !!
  
	  
	  // allow us do any ioctl
	  if (db->policyvers >= POLICYDB_VERSION_XPERMS_IOCTL) {
		  //ksu_allowxperm(db, KERNEL_SU_DOMAIN, ALL, "blk_file", ALL);
		  //ksu_allowxperm(db, KERNEL_SU_DOMAIN, ALL, "fifo_file", ALL);
		  //ksu_allowxperm(db, KERNEL_SU_DOMAIN, ALL, "chr_file", ALL);
	  }
  
	  
	  // we need to save allowlist in /data/adb/ksu
	  //ksu_allow(db, "kernel", "adb_data_file", "dir", ALL); //error!!
	  // ksu_allow(db, "kernel", "adb_data_file", "file", ALL);
  
	  // // we may need to do mount on shell
	  //ksu_allow(db, "kernel", "shell_data_file", "file", ALL); //error!!
  
	  // // we need to read /data/system/packages.list
	  ksu_allow(db, "kernel", "kernel", "capability", "dac_override");
  
	  // // Android 10+:
	  // // http://aospxref.com/android-12.0.0_r3/xref/system/sepolicy/private/file_contexts#512
	  // ksu_allow(db, "kernel", "packages_list_file", "file", ALL); //error!!
  
	  // // Kernel 4.4
	  //ksu_allow(db, "kernel", "packages_list_file", "dir", ALL); //error!!
  
	  // // Android 9-:
	  // // http://aospxref.com/android-9.0.0_r61/xref/system/sepolicy/private/file_contexts#360
	  ksu_allow(db, "kernel", "system_data_file", "file", ALL);
	  ksu_allow(db, "kernel", "system_data_file", "dir", ALL);
  
	  // // our ksud triggered by init
	  ksu_allow(db, "init", "adb_data_file", "file", ALL);
	  //ksu_allow(db, "init", KERNEL_SU_DOMAIN, ALL, ALL);//error!!
	  
  
	  // copied from Magisk rules    all error!!!
	  // suRights
	  //ksu_allow(db, "servicemanager", KERNEL_SU_DOMAIN, "dir", "search");//error!!
	  //ksu_allow(db, "servicemanager", KERNEL_SU_DOMAIN, "dir", "read");//error!!
	  //ksu_allow(db, "servicemanager", KERNEL_SU_DOMAIN, "file", "open");//error!!
	  //ksu_allow(db, "servicemanager", KERNEL_SU_DOMAIN, "file", "read");//error!!
	  //ksu_allow(db, "servicemanager", KERNEL_SU_DOMAIN, "process", "getattr");//error!!
	  //ksu_allow(db, ALL, KERNEL_SU_DOMAIN, "process", "sigchld");//error!!
  
	  
	  // allowLog  all error!!!
	  // ksu_allow(db, "logd", KERNEL_SU_DOMAIN, "dir", "search");
	  // ksu_allow(db, "logd", KERNEL_SU_DOMAIN, "file", "read");
	  // ksu_allow(db, "logd", KERNEL_SU_DOMAIN, "file", "open");
	  // ksu_allow(db, "logd", KERNEL_SU_DOMAIN, "file", "getattr");
  
	  // dumpsys  all error!!!
	  // ksu_allow(db, ALL, KERNEL_SU_DOMAIN, "fd", "use");
	  // ksu_allow(db, ALL, KERNEL_SU_DOMAIN, "fifo_file", "write");
	  // ksu_allow(db, ALL, KERNEL_SU_DOMAIN, "fifo_file", "read");
	  // ksu_allow(db, ALL, KERNEL_SU_DOMAIN, "fifo_file", "open");
	  // ksu_allow(db, ALL, KERNEL_SU_DOMAIN, "fifo_file", "getattr");
  
	  // bootctl  all error!!!
	  // ksu_allow(db, "hwservicemanager", KERNEL_SU_DOMAIN, "dir", "search");
	  // ksu_allow(db, "hwservicemanager", KERNEL_SU_DOMAIN, "file", "read");
	  // ksu_allow(db, "hwservicemanager", KERNEL_SU_DOMAIN, "file", "open");
	  // ksu_allow(db, "hwservicemanager", KERNEL_SU_DOMAIN, "process","getattr");
  
	  // Allow all binder transactions
	  //ksu_allow(db, ALL, KERNEL_SU_DOMAIN, "binder", ALL);//error!
	  
  
	  
	  // Allow system server devpts     all error!!!
	  //ksu_allow(db, "system_server", "untrusted_app_all_devpts", "chr_file","read"); //error!!
	  //ksu_allow(db, "system_server", "untrusted_app_all_devpts", "chr_file","write"); //error!!
	  
  
	  rcu_read_unlock();

**Comment by Coconutat** [comment]
一样，我的编译完了也是不能进入系统了。0.6.0的老版本倒是可以。

**Comment by tiann** [comment]
没有看到你在内核中关于 KernelSU 的修改，另外 [这个文档](https://kernelsu.org/zh_CN/guide/how-to-integrate-for-non-gki.html#using-kprobes) 已经更新过了，你要重新改一下。

**Comment by Coconutat** [comment]
> 没有看到你在内核中关于 KernelSU 的修改，另外 [这个文档](https://kernelsu.org/zh_CN/guide/how-to-integrate-for-non-gki.html#using-kprobes) 已经更新过了，你要重新改一下。

您好，我和上面那位朋友不是同一位，不过也遇到相同的问题，新版本Ksu卡开机。能编译，但是卡开机。
这是我的仓库：https://github.com/Coconutat/android_kernel_huawei_kirin970_EMUI9.1.0_KernelSU/tree/Github-Action

**Comment by tiann** [comment]
你是 0.6.0 版本的时候能开机，还是现在回退到 0.6.0 版本能开机？这是两码事

**Comment by Coconutat** [comment]
> 你是 0.6.0 版本的时候能开机，还是现在回退到 0.6.0 版本能开机？这是两码事

0.6.0版本能开机，回退到0.6.0也能开机（新标准的集成方式出来之前的版本）。

**Comment by tiann** [comment]
那你需要提供一下 pstore 日志，另外你可以一个个 revert 看看是哪个 commit 引起的

**Comment by Coconutat** [comment]
> 那你需要提供一下 pstore 日志，另外你可以一个个 revert 看看是哪个 commit 引起的

好的，我尽力。

**Comment by Coconutat** [comment]
> 那你需要提供一下 pstore 日志，另外你可以一个个 revert 看看是哪个 commit 引起的

我用PC编译后倒是没问题了。Github Action的会卡开机，可能是我yml写的有问题。

**Comment by luckyzyx** [comment]
我也是类似的问题，一加 9RT Android13 5.4.210-qgki
https://github.com/luckyzyx/android_kernel_oneplus_sm8350

https://github.com/tiann/KernelSU/commit/54d2962a0d901b8ef997cab229a2644171437068
我把这个commit加回去就可以开机了，KSU功能基本正常，但是LSP数据保存不了，selinux宽容才可以
