### ISSUE TITLE
Patcing boot.img directly?

### ISSUE THREAD

**Issue by symbuzzer** [tiann/KernelSU#690]
The kernel source code of many Mediatek processor devices is not available. Therefore, KernelSU does not work on these devices and they have to use Magisk as a root solution.

I wonder if there is a solution like patching the boot.img directly like in Magisk?

**Comment by tiann** [comment]
GKI Kernel does not require manufacturer's source code.

**Comment by symbuzzer** [comment]
@tiann So how can we patch boot.img files?

**Comment by tiann** [comment]
For GKI kernel, no need.
For non-GKI kernel, not possible.

**Comment by symbuzzer** [comment]
So any solution in future for non-GKI kernels?

**Comment by tiann** [comment]
KernelSU is designed for GKI devices, for non-GKI kernel without source code, use Magisk please.
