### ISSUE TITLE
app su授权和模块页面

### ISSUE THREAD

**Issue by netPokey** [tiann/KernelSU#693]
超级用户授权页面一直转圈圈
![微信截图_20230627152333](https://github.com/tiann/KernelSU/assets/39108418/dd8d6f00-2556-4123-a788-9a1001a8d4dd)

模块页面 内核不支持Overlayfs。。。。。
![微信截图_2](https://github.com/tiann/KernelSU/assets/39108418/3f4ae0cd-6e32-4cac-a7ad-eb7b4536f1f9)
日志
[Uploading KernelSU_bugreport_2023-06-27_15_15.tar.gz…]()

**Comment by netPokey** [comment]
[KernelSU_bugreport_2023-06-27_15_15.tar.gz](https://github.com/tiann/KernelSU/files/11878887/KernelSU_bugreport_2023-06-27_15_15.tar.gz)

**Comment by netPokey** [comment]
130|polaris:/ $ logcat -e "su failed: "
--------- beginning of system
--------- beginning of crash
--------- beginning of main
06-27 15:54:53.692  4294  4294 E KsuCli  : su failed:
06-27 15:54:53.692  4294  4294 E KsuCli  : o4.a: Unable to create a shell!
06-27 15:54:53.692  4294  4294 E KsuCli  :      at p6.i.p(Unknown Source:44)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at d6.d.<clinit>(Unknown Source:27)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at p4.l0.V(Unknown Source:0)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at j.p.c(Unknown Source:1144)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at j.p.V(Unknown Source:545)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at l0.b.a(Unknown Source:50)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at l0.b.V(Unknown Source:8)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at q.h0.a(Unknown Source:376)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at q.h0.X(Unknown Source:40)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at l0.b.X(Unknown Source:58)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at x.m.a(Unknown Source:481)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at x.m.X(Unknown Source:28)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at l0.b.X(Unknown Source:58)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at u.j1.o(Unknown Source:182)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at androidx.compose.material3.p6.a(Unknown Source:153)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at u.j1.m(Unknown Source:637)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at u.j1.u(Unknown Source:338)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at p4.l0.q(Unknown Source:137)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at androidx.compose.material3.b3.c(Unknown Source:345)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at androidx.compose.material3.b3.V(Unknown Source:248)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at l0.b.a(Unknown Source:50)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at l0.b.V(Unknown Source:8)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at androidx.compose.material3.o0.a(Unknown Source:194)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at androidx.compose.material3.o0.X(Unknown Source:40)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at l0.b.X(Unknown Source:58)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at m.f0.a(Unknown Source:488)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at m.f0.X(Unknown Source:97)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at l0.b.X(Unknown Source:58)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at l.v1.b(Unknown Source:579)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at l.v1.w(Unknown Source:56)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at u.j1.h1(Unknown Source:43)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at e0.y.q(Unknown Source:128)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at e0.y.j(Unknown Source:13)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at e0.d0.m(Unknown Source:17)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at e0.d2.a(Unknown Source:53)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at e0.k.a(Unknown Source:9)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at e0.k.a(Unknown Source:9)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at e0.d0.d(Unknown Source:10)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at g1.b0.c(Unknown Source:111)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at g1.x.a(Unknown Source:134)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at androidx.compose.material3.e5.d0(Unknown Source:789)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at g1.g0.d(Unknown Source:32)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at g1.y.d(Unknown Source:8)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at l.v1.b(Unknown Source:352)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at l.v1.w(Unknown Source:48)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at d3.a.G(Unknown Source:63)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at l.x.b(Unknown Source:222)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at l.x.w(Unknown Source:62)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at u.j1.h1(Unknown Source:43)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at n0.z.c(Unknown Source:117)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at i1.k1.a(Unknown Source:12)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at i1.j0.h(Unknown Source:114)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at i1.r.p0(Unknown Source:126)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at g1.t0.c(Unknown Source:32)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at i1.h0.w(Unknown Source:14)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at d3.a.G(Unknown Source:63)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at l.x.b(Unknown Source:222)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at l.x.w(Unknown Source:62)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at u.j1.h1(Unknown Source:43)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at n0.z.c(Unknown Source:117)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at i1.k1.a(Unknown Source:12)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at i1.j0.v0(Unknown Source:60)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at i1.j0.p0(Unknown Source:43)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at g1.t0.c(Unknown Source:32)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at o.q.b(Unknown Source:44)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at o.n.d0(Unknown Source:24)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at g1.g0.d(Unknown Source:32)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at l.v1.b(Unknown Source:352)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at l.v1.w(Unknown Source:48)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at d3.a.G(Unknown Source:63)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at l.x.b(Unknown Source:222)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at l.x.w(Unknown Source:62)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at u.j1.h1(Unknown Source:43)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at n0.z.c(Unknown Source:117)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at i1.k1.a(Unknown Source:12)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at i1.j0.h(Unknown Source:114)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at i1.r.p0(Unknown Source:126)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at g1.t0.f(Unknown Source:52)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at j.o.b(Unknown Source:80)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at j.o.d0(Unknown Source:415)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at g1.g0.d(Unknown Source:32)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at i1.w.p0(Unknown Source:37)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at g1.t0.c(Unknown Source:32)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at i1.h0.w(Unknown Source:14)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at d3.a.G(Unknown Source:63)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at l.x.b(Unknown Source:222)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at l.x.w(Unknown Source:62)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at u.j1.h1(Unknown Source:43)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at n0.z.c(Unknown Source:117)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at i1.k1.a(Unknown Source:12)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at i1.j0.v0(Unknown Source:60)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at i1.j0.p0(Unknown Source:43)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at g1.t0.c(Unknown Source:32)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at o.q.b(Unknown Source:44)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at o.n.d0(Unknown Source:24)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at g1.g0.d(Unknown Source:32)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at l.v1.b(Unknown Source:352)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at l.v1.w(Unknown Source:48)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at d3.a.G(Unknown Source:63)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at l.x.b(Unknown Source:222)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at l.x.w(Unknown Source:62)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at u.j1.h1(Unknown Source:43)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at n0.z.c(Unknown Source:117)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at i1.k1.a(Unknown Source:12)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at i1.j0.h(Unknown Source:114)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at i1.r.p0(Unknown Source:126)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at g1.t0.f(Unknown Source:52)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at j.o.b(Unknown Source:26)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at j.o.d0(Unknown Source:423)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at g1.g0.d(Unknown Source:32)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at i1.w.p0(Unknown Source:37)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at g1.t0.c(Unknown Source:32)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at i1.h0.w(Unknown Source:14)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at d3.a.G(Unknown Source:63)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at l.x.b(Unknown Source:222)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at l.x.w(Unknown Source:62)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at u.j1.h1(Unknown Source:43)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at n0.z.c(Unknown Source:117)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at i1.k1.a(Unknown Source:12)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at i1.j0.v0(Unknown Source:60)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at i1.j0.p0(Unknown Source:43)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at g1.t0.c(Unknown Source:32)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at o.q.b(Unknown Source:44)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at o.n.d0(Unknown Source:24)
06-27 15:54:53.692  4294  4294 E KsuCli  :      at g1.g0.d(Unknown Source:32)

**Comment by tiann** [comment]
先搜索 issues.

**Comment by netPokey** [comment]
我搜过了 有一个263 然后我对不我并没有哪些配置 才来发的bug

**Comment by zl521368789** [comment]
这个问题解决了吗？我使用小米6开源代码内核版本4.4.153进行编译，遇到了同样的问题，经过排查，0.5.2版本的管理器可以app列表可以加载，再更新的管理器就不行了。尝试使用指定tag0.5.2版本进行编译，发现kernelsu并未参与编译

**Comment by Coconutat** [comment]
> 这个问题解决了吗？我使用小米6开源代码内核版本4.4.153进行编译，遇到了同样的问题，经过排查，0.5.2版本的管理器可以app列表可以加载，再更新的管理器就不行了。尝试使用指定tag0.5.2版本进行编译，发现kernelsu并未参与编译

你在defeconfig里写`CONFG_KSU=y`了么？

**Comment by zl521368789** [comment]
> 你在defconfig里写`CONFG_KSU=y`了么？
已经尝试添加，kernelsu并未参与编译

**Comment by Coconutat** [comment]
> > 你在defconfig里写`CONFG_KSU=y`了么？
> > 已经尝试添加，kernelsu并未参与编译

那就去drivers/Makefile里看看，KernelSU的添加规则是不是obj-$(CONFIG_KSU)= kernelsu/

**Comment by zl521368789** [comment]
> > > 你在defconfig里写`CONFG_KSU=y`了么？
> > > 已经尝试添加，kernelsu并未参与编译
> 
> 那就去drivers/Makefile里看看，KernelSU的添加规则是不是obj-$(CONFIG_KSU)= kernelsu/

是的，drivers文件夹下Makefile和Kconfig都已经正确添加，这步是把kernelsu添加到内核源码树时自动添加的

**Comment by netPokey** [comment]
看看编译日志有木有编译

**Comment by netPokey** [comment]
我是后来安装代码patch的

**Comment by zl521368789** [comment]
> 我是后来安装代码补丁的

就是看编译日志没有参与编译，才敢发的。
