### ISSUE TITLE
MicroSD does not work

### ISSUE THREAD

**Issue by Gabriel2392** [tiann/KernelSU#697]
**Describe the bug**
MicroSD does not work with prebuilt KernelSU Images

**To Reproduce**
1. Download appropriate boot image from releases (android12-5.10.136_2022-11-boot.img for ref)
2. Install it

**Expected behavior**
It should work just like stock kernel.

**Screenshots**
![Screenshot_20230629_194943_KernelSU](https://github.com/tiann/KernelSU/assets/88463214/6d1b6aae-548c-41c1-93a0-b81725735d65)
![Screenshot_20230629_195049_My Files](https://github.com/tiann/KernelSU/assets/88463214/b0ddfcd0-33a5-4ca4-ae78-4626717dde37)

**Smartphone:**
 - Device: Samsung Galaxy A33
 - OS: OneUI 5.1
 - Version: 13

**Additional context**
I don't know why this even happens, but the microSD card just stops working when I flash the prebuilt KernelSU image from releases. (Kernel 5.10)
[KernelSU_bugreport_2023-06-29_19_58.tar.gz](https://github.com/tiann/KernelSU/files/11911030/KernelSU_bugreport_2023-06-29_19_58.tar.gz)

**Comment by FlorinelulX** [comment]
Same issue here

**Comment by BlackMesa123** [comment]
Samsung has it's own proprietary drivers to handle the FAT file system (sdFAT), that's probably the reason external SD is not working, Google kernel common does not have these drivers. I'm quite surprised a GKI kernel actually booted in a Samsung device considering the amount of stuff they put in their shipped kernels.

**Comment by Gabriel2392** [comment]
@BlackMesa123 Ah, Sad... I will have to build the kernel on my own for every release, I guess lol...

**Comment by blurrr-000** [comment]
> Samsung has it's own proprietary drivers to handle the FAT file system (sdFAT), that's probably the reason external SD is not working, Google's common kernel tree does not have these drivers. I'm quite surprised a GKI kernel actually booted in a Samsung device considering the amount of stuff they put in their shipped kernels.

Sir, i also encounter this kind of problem my device is samsung a54 running android 14,,, does it have a solution in the future sir? I cant use my memory card.. pls help

**Comment by blurrr-000** [comment]
> Samsung has it's own proprietary drivers to handle the FAT file system (sdFAT), that's probably the reason external SD is not working, Google's common kernel tree does not have these drivers. I'm quite surprised a GKI kernel actually booted in a Samsung device considering the amount of stuff they put in their shipped kernels.

Is there a module to fix this kind of problem?
