### ISSUE TITLE
Requires adding armeabi-v7a support in KernelSU.apk

### ISSUE THREAD

**Issue by VThang51** [tiann/KernelSU#701]
- Q: hey, KernelSU only support `arm64` and `x86_64`, why need `armeabi-v7a`?
- A: I know, but my device is `arm32-binder64` aka `a64`
- Q: Yeah, what does it have to do with each other?
- A: My kernel is arm64 so I want to use KernelSU
- Q: @tiann , can you add `armeabi-v7a` to `KernelSU.apk`?
- A: Would you do it for me? 😄

**Comment by tiann** [comment]
No, i won't. `armeabi-v7a` is already a thing of the past, please convince Google Play first.

**Comment by mickeymgk** [comment]
Actually, `armeabi-v7a` is still a widely used architecture, especially for devices that do not support newer architectures. Many apps on Google Play continue to support armeabi-v7a to ensure compatibility with a broad range of devices. It's not a thing of the past but rather a crucial component. Stop making baseless claims.
