### ISSUE TITLE
update bug_report issue temple

### ISSUE THREAD

**Issue by dabao1955** [tiann/KernelSU#705]
![Screenshot_2023-07-01-20-21-07-36_a252b927494330cdc2c8ba3b3f952e5e](https://github.com/tiann/KernelSU/assets/79307765/efd056ce-b8ca-4641-96c7-70d3e0ea0ab1)
I don't think it's a breaking commit. If you don't mind, I will initiate a pr immediately.

**Comment by tiann** [comment]
the bugreport file generate by manager has all the information we need.

**Comment by tiann** [comment]
Can you make an upload button to upload bugreport?

**Comment by tiann** [comment]
For bug-related issues, the most important thing is to provide a bugreport.zip; if this cannot be done simply from the input box, consider using an issue bot to automatically close invalid issues.

**Comment by tiann** [comment]
I think this is enough
