### ISSUE TITLE
overlay.d support

### ISSUE THREAD

**Issue by Pierre2324** [tiann/KernelSU#713]
**Issue**
Hi, I'm a custom android kernel developer and I've been using Magisk in the past with its MAGISKTMP functionality. 
With magisk, when kernel is flashed the content of ramdisk/overlay.d gets extracted to MAGISKTMP (/sbin on older android and a randomly named folder in /dev for newer android versions).
Every .rc files in there is also appended to ROM's init to run on boot.

**Feature Request**
Would it be possible to mimic Magisk's overlay.d with kernelsu?

**Alternatives**
I've tried pushing files in anykernel/modules to /data/adb/modules with do.systemless=1 and do.modules=1 and removing the magisk check in update-binary so that ak3-helper gets created but that didn't work

I've also tried pushing files manually using terminal commands like cp to copy files from the anykernel to /data/adb/modules manually but that didn't work neither

**Comment by tiann** [comment]
I'm not very familiar with Magisk's overlay.d mechanism, nor do I know its use cases; KernelSU only modifies the kernel and does not touch the ramdisk, so I think it would be quite troublesome to support this feature.

However, I will keep this issue open, in case someone is willing to provide a PR for it.

Also, I wanted to ask, can't the module's `post-fs-data` satisfy the requirements?

**Comment by tiann** [comment]
What things can be done in init.rc but not in post-fs-data?

**Comment by osm0sis** [comment]
Kernel modules loading, and other things that can require on init and early init.

**Comment by Pierre2324** [comment]
> I'm not very familiar with Magisk's overlay.d mechanism, nor do I know its use cases; KernelSU only modifies the kernel and does not touch the ramdisk, so I think it would be quite troublesome to support this feature.
> 
> However, I will keep this issue open, in case someone is willing to provide a PR for it.
> 
> Also, I wanted to ask, can't the module's `post-fs-data` satisfy the requirements?

I actually wanted to push files from my anykernel zip to /data/adb/modules (doesn't have to be ramdisk). 

That would prevent users to having to flash a separate module after flashing my kernel and on my side doing a separate module for every device I maintain since those files are already in anykernel so I thought it would be better to be able to push them to /data/adb/modules directly.

Things like spectrum profiles, bootup tweaks (init.xxx.rc) and .sh scripts so they are ran on boot and available there when I change profiles in my app using /data/adb/modules when the user is using kernelsu instead of magisktmp path. 

I guess post-fs-data would work for that part, but having the possibility from anykernel to push files to a place like /data/adb/modules directly without having magisk requirements would be beneficial. 

But if the use of flashing a separate module.zip in kernelsu app is required to push the same files that are already used in my kernel.zip when magisk is there, then I'll make one.

Sorry if I'm not clear on what I need, hope it's not too bad.

**Comment by osm0sis** [comment]
I'll look into expanding the checks for AK3 to allow KernelSU, but it sounded like you were saying the module wasn't created for KernelSU when you push those files manually.

**Comment by Pierre2324** [comment]
> I'll look into expanding the checks in AK3 to allow KernelSU for the helper module, but it sounded like you were saying the module wasn't created for KernelSU when you push those files manually. And if that's the case then I'm not sure what's missing, since it works fine with Magisk.

What I did:
-Add files to a folder named modules in anykernel
-Made sure do.systemless and do.modules were set to 1 in anykernel.sh
-Commented out the check for magisk (because magisk isn't there) in update-binary do_modules() function so it can create a kernel helper module in /data/adb/modules anyway. 

But nothing was created.

**Comment by osm0sis** [comment]
> > I'll look into expanding the checks in AK3 to allow KernelSU for the helper module, but it sounded like you were saying the module wasn't created for KernelSU when you push those files manually. And if that's the case then I'm not sure what's missing, since it works fine with Magisk.
> 
> What I did: -Add files to a folder named modules in anykernel -Made sure do.systemless and do.modules were set to 1 in anykernel.sh -Commented out the check for magisk (because magisk isn't there) in update-binary do_modules() function so it can create a kernel helper module in /data/adb/modules anyway.
> 
> But nothing was created.

Okay, well that's an AK3 thing. Without a log I can't be sure, but if you correctly commented out the check then the files should get created.

Let's address that in the AK3 xda thread so we don't derail this overlay.d feature request thread (which is still a good request for feature parity, if possible) any further.

**Comment by tiann** [comment]
> Commented out the check for magisk (because magisk isn't there) in update-binary do_modules() function so it can create a kernel helper module in /data/adb/modules anyway.

In KernelSU, `/data/adb/modules` is a mount point, where an ext4 image will be mounted after the Android system starts up, and the original content of this directory will be covered (overlayfs cannot directly use the /data partition). Therefore, if you are operating this directory in recovery, you will not be able to see it after entering the Android system. You can try to use `/data/adb/ksu module install <ZIP>` to install the module; but please note: KernelSU has never supported installing modules in Recovery, and this behavior may change in the future.

**Comment by osm0sis** [comment]
Ahah! So there is something different.. Pierre didn't have any other modules installed so the mount point thing wasn't obvious.

I used to support Magisk in the magisk.img days, so I'll take a look at something similar so KernelSU can have recovery support too once I update the checks.

Then that'll just leave overlay.d as the difference support-wise. 👍

**Comment by nad0vs** [comment]
> post

Actually, init mechanism of android is a great way to launch your own services with "right" users and selinux contexts and perform watchdog monitoring on them.

Avbroot allows for a mechanism to "cook" such init modifications using Magisk's init injection mechanisms and it is very comfy 

https://github.com/chenxiaolong/avbroot/issues/90

I've just used the above described methodology to add an automatically monitored dnscrypt and Cloak services to my magisk-rooted phone, it is much more comfortable than alternatives for launching persistent services and relaunching them when they crash (dnscrypt tends to misbehave for me occasionally)

I do love the idea of kernelsu very much though (especially the root profile / app profile approach) and would love to see init.rc injection implemented in kernelsu

**Comment by nad0vs** [comment]
hey @Pierre2324 would this kind of thing https://kernelsu.org/guide/hidden-features.html allow to do what you want to do by using a custom initrc ? https://kernelsu.org/guide/hidden-features.html

**Comment by Pierre2324** [comment]
> hey @Pierre2324 would this kind of thing https://kernelsu.org/guide/hidden-features.html allow to do what you want to do by using a custom initrc ? 
> 
> (I have not tested this and the wording is slightly ambiguous as to whether it is supposed to load ksurc as a custom android init.rc and also whether it appends records to the init.rc or replaces it wholesale)

Hmm interesting, ambiguous but seems like it 🤔

**Comment by osm0sis** [comment]
The fact that /data/adb/ksu/.ksurc is in /data means it is run at least after post-fs-data, whereas overlay.d can be whole init.rc files with triggers running O believe by at least early-boot.

**Comment by osm0sis** [comment]
Presumably the kernel has access to rootfs pre-init and should be able to do all the overlay.d stuff, so no ramdisk hacking necessary.

**Comment by nad0vs** [comment]
well, yeah @osm0sis is right the thing does not look like it is injecting into init.rc a-la what magisk overlay is doing.
Is there any hope to see init.rc injection in a future version of kernelsu, @tiann ?

I'm growing addicted to how nice things are going with custom services for me, but otherwise want too migrate to kernelsu

**Comment by nad0vs** [comment]
Upon some barely literate prodding and searching on my part, it would appear that KernelSU already does an .rc file injection through atrace.rc 

https://github.com/tiann/KernelSU/blob/978178afc0928cac179e8f23a3407f9d27ab1f01/kernel/ksud.c#L255

So only a mechanism for a user to provide additional user.rc to concatenate to the injected stuff would need to be invented and implemented to make it happen

**Comment by tiann** [comment]
KernelSU does inject init.rc at the kernel level, but that's just a small piece of code (less than 1024 in length), and there's a lot more work to be done if you want to inject an arbitrary rc:
1. where to put this rc file? `/data` is definitely not an option, maybe directly in the `/boot` partition? I'm not sure.
2. we need to intercept a series of system calls to make init think that the rc file exists; this is a lot of work in different kernel versions.

Personally, I wouldn't add this feature because it's more complicated to implement than you think, and I don't have a need for it.

I think @HuskyDG 's approach is more pragmatic and feasible. There is no need to implement everything in the kernel, and it can be implemented as simple as possible.

**Comment by osm0sis** [comment]
Probably somewhere that could be mounted pre-init that doesn't require decryption would be the other option to hold the files, similar to Magisk's PREINITDEVICE location for sepolicy rules files, etc. So like /metadata, /persist or /cache.

**Comment by nad0vs** [comment]
> For `overlay.d`, reading custom `.rc` script and appending to `init.rc` could be easy in kernel, but we also need to mount tmpfs on random directory inside `/dev` to store files from `overlay.d/sbin` which is used for custom `init.rc`.

why can't that be implemented (when necessary, e.g. I don't even need the overlay.d/sbin part, just custom init services ;-) I only need init's feature as a "built in unstoppable watchdog" ) in a custom service itself?

e.g. 

kernelsu would implement two features 

1) init.rc injector (which could be basically an option during install specifying path to custom .rc file the contents of which would be appended to the init injection Kernelsu already does) 
and 
2) "folder to ramdisk" which is basically an option to take a specified folder and add it wholesale to ramdisk, available to root and init via appropriate selinux context/labels and not much anyone else.

If these files need to be moved/mounted to some path inside /dev or something like that, a service with proper powers can be specified in the injected init.rc  and triggered to run via appropriately early init trigger. But it's up to the person making the custom early service to write that service / script etc.

Am I significantly underestimating the gnarliness of android early filesystem / service manipulation?

**Comment by nad0vs** [comment]
> * where to put this rc file? `/data` is definitely not an option, maybe directly in the `/boot` partition? I'm not sure.

@tiann is there something about android boot process and/or  AVB and/or  some later consideration (tricking SafetyNet?) that precludes one from placing the "user.rc to be injected" and additional tooling (overlay.d folder with a handful of binaries) into generic ramdisk (the one that got moved to init_boot separate image in 13-native devices if memory serves)?

**Comment by tiann** [comment]
> > * where to put this rc file? `/data` is definitely not an option, maybe directly in the `/boot` partition? I'm not sure.
> 
> @tiann is there something about android boot process and/or AVB and/or some later consideration (tricking SafetyNet?) that precludes one from placing the "user.rc to be injected" and additional tooling (overlay.d folder with a handful of binaries) into generic ramdisk (the one that got moved to init_boot separate image in 13-native devices if memory serves)?

AVB will verify boot / init_boot, whether you change it to kernel or ramdisk, but this is not a problem for us.

**Comment by tiann** [comment]
I think using init service is a bad idea, because any app can find out all running or stopped services by `getprop | grep init.svc`, random name is also useless, because only one reboot of the device will do it Find the service whose name has changed.

KernelSU deliberately did not use service but directly used exec. Magisk's former daemon used service as a daemon to run, but it also [adopted this method later](https://github.com/topjohnwu/Magisk/commit/dba5020e4f8b1e4a6fc1e964670c6085a49d7a76).

If you just want a watchdog, there are many other options, such as: https://github.com/ochinchina/supervisord

**Comment by tiann** [comment]
closed since no developers are willing to add support, if anyone sees this issue, please feel free to PR

**Comment by anasfanani** [comment]
Just looking here and it seems no developers are willing to add support ( I have small knowledge so I can't ).

With Magisk I can inject init.rc file

```
on charger
  reboot
```

Is it possible to do like this while in KernelSU ?

Thankyou.
