### ISSUE TITLE
KernelSU with exynos kernel 4.19 which function needs to be enabled?

### ISSUE THREAD

**Issue by switch-gott** [tiann/KernelSU#714]
Hi, 
i tried all to get the kernelsu working with galaxy s20 kernel 4.19 and android 13.
No way. Kernel does not boot.
KProbe is enabled.
But, which kernel configs i need too? Debug etc?
Do you can provide a list, which kernel configs we need, to get kernelsu working?
Realy thanks
Bye

**Comment by tiann** [comment]
Can you boot it without KernelSU ？

**Comment by switch-gott** [comment]
Hi,
big thanks for your answer.
Yes i can boot my compiled kernel without kernelsu code.

**Comment by tiann** [comment]
https://kernelsu.org/guide/how-to-integrate-for-non-gki.html

Don't use kprobe and try again

**Comment by switch-gott** [comment]
Thanks.
Realy interessting. 
Why are some samsung kernels only with different hardware, qualcomn chips, are working out of the box with kprobes and exynos not?
I have to disable kprobes if i use the backport Methode?

**Comment by tiann** [comment]
> I have to disable kprobes if i use the backport Methode?

Yes. For other questions, you should ask Samsung.
