### ISSUE TITLE
Symlink bug

### ISSUE THREAD

**Issue by Zackptg5** [tiann/KernelSU#726]
**Describe the bug**
Vendor partition (and possibly others) are moved to root of module and it's path in system is symlinked to full mounted directory.
In screenshot below, actual module vendor files are in <modulename>/vendor while the <modulename>/system/vendor is a symlink to /vendor partition itself

**To Reproduce**
1. Flash module
2. Reboot

**Expected behavior**
Actual folder for non-system partition should be inside the system folder with symlink to it in root of module

**Screenshots**
```
redfin:/data/adb/modules/ainur_jamesdsp # ls -l
total 1445
-rw-r--r-- 1 root root 1458625 2023-07-06 18:26 JamesDSPManager.apk
-rw-r--r-- 1 root root    8173 2023-07-06 18:26 changelog.md
-rw-r--r-- 1 root root     437 2023-07-06 18:26 module.prop
drwxr-xr-x 3 root root    1024 2023-07-06 18:26 system
-rw-r--r-- 1 root root     528 2023-07-06 18:26 uninstall.sh
-rw-r--r-- 1 root root     234 2023-07-06 18:26 update.json
drwxr-xr-x 4 root root    1024 2023-07-06 18:26 vendor
```
```
redfin:/data/adb/modules/ainur_jamesdsp # ls -l system/
total 3
drwxr-xr-x 2 root root 1024 2023-07-06 18:26 etc
lrwxrwxrwx 1 root root    7 2023-07-06 18:26 vendor -> /vendor
```

**Smartphone (please complete the following information):**
 - Device: WSA

**Additional Context:**
I have logs of the module flash and files were copied to <modulename>/system/vendor and when examining the modules.img, it's already changed to the listed bug so I'm thinking the problem happens during the img creation/packing
[ainur_jamesdsp-debug.log](https://github.com/tiann/KernelSU/files/11973071/ainur_jamesdsp-debug.log)

Mounts below:
```
KSU on /system type overlay (ro,seclabel,relatime,lowerdir=/data/adb/modules/ainur_jamesdsp/system:/system)
KSU on /vendor type overlay (ro,seclabel,relatime,lowerdir=/data/adb/modules/ainur_jamesdsp/vendor:/vendor)

```

**Comment by Zackptg5** [comment]
> This is expected, due to overlayfs, if `/vendor` is a seperate partition, installer will move `MODDIR/system/vendor` to `MODDIR/vendor`

So is it the same for all other partitions (such as odm) then? 
Can the documentation be updated to reflect the actual location then? This leads to problems with boot scripts and some mods that affect others (like aml) expecting files in certain locations when they're actually in others

**Comment by tiann** [comment]
Because KernelSU uses overlayfs, if `vendor` is a separate partition, `/system/vendor` is a symbolic link pointing to `/vendor`; In this case, if the directory structure of `$MODPATH/system/vendor` is still maintained in the module directory, the symbolic link `/system/vendor` will be overlaid by the module's `$MODPATH/system/vendor`, and this directory does not have all the contents of `/vendor`; Therefore, in this case we will move the module's `$MODPATH/system/vendor` to `$MODPATH/vendor`.

Also, I'm not sure what the structure of `my_*` partitions is, and I think if necessary, you can also add the corresponding overlay in KernelSU without having to bind mount yourself.

**Comment by Zackptg5** [comment]
> Btw i thinks `$MODPATH/system/vendor` symlink should link to `../vendor` relative path instead of `/vendor` absolute path so Magisk design-compliant modules like yours will still work under KernelSU while the mounted overlay will still point to partition properly.

That would be perfect. Much less headache dealing with partitions in boot scripts like with aml where the install happens on the fly each boot rather than initial flashing

> Because KernelSU uses overlayfs, if `vendor` is a separate partition, `/system/vendor` is a symbolic link pointing to `/vendor`; In this case, if the directory structure of `$MODPATH/system/vendor` is still maintained in the module directory, the symbolic link `/system/vendor` will be overlaid by the module's `$MODPATH/system/vendor`, and this directory does not have all the contents of `/vendor`; Therefore, in this case we will move the module's `$MODPATH/system/vendor` to `$MODPATH/vendor`.
> 
> Also, I'm not sure what the structure of `my_*` partitions is, and I think if necessary, you can also add the corresponding overlay in KernelSU without having to bind mount yourself.

Gotcha, I remember other root solutions doing something similar a couple years ago. I forget if it was magisk or systemless su. Could you update the documentation to make that more clear on the difference with magisk page?
