### ISSUE TITLE
App Detects Root Even with Modules Unmounted

### ISSUE THREAD

**Issue by RecursiveRegistrations** [tiann/KernelSU#727]
I am not sure if this issue is more appropriate to report to the KernelSU team or the Zygisk on KernelSU team, so I figured I would bring it up here. I have an app that detects root even when modules are set to not be mounted for it.

I have reported this issue in more detail to the team that maintains Zygisk on KernelSU as well. Please see that issue for more details.

https://github.com/Dr-TSNG/ZygiskOnKernelSU/issues/37

**Comment by RecursiveRegistrations** [comment]
@Ylarod Why was this closed without explanation?

**Comment by Ylarod** [comment]
1. Unable to reproduce.
2. Unmount is not omnipotent.
3. This is a module issue, not KernelSU's issue.

**Comment by RecursiveRegistrations** [comment]
Alright. I will try to follow up with the team behind Zygisk on KernelSU again.
