### ISSUE TITLE
管理器v0.6.2提示内核版本不够

### ISSUE THREAD

**Issue by HatsuneMikuZero** [tiann/KernelSU#730]
![Screenshot_2023-07-08-12-12-44-187_me weishu kernelsu](https://github.com/tiann/KernelSU/assets/67409983/c48440f5-fdf1-4c12-b831-9de8170769c7)
那五位数是什么的版本？我k60ProMIUI14开发版最新。

**Comment by HatsuneMikuZero** [comment]
或者说是我管理器更新了，头上工作中的东西没更新。

**Comment by tiann** [comment]
不认识字吗？
