### ISSUE TITLE
指定tag(比如v0.5.2)脚本问题，无法参与编译

### ISSUE THREAD

**Issue by zl521368789** [tiann/KernelSU#735]
kernelsu并未参与编译！
把kernelsu添加到我的内核源码树使用curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s v0.5.2。
以下是输出内容：
++ pwd
+ GKI_ROOT=/home/yang/mi6/12mi6ksu52kebokes_gcc/sagit-p-oss
+ echo '[+] GKI_ROOT: /home/yang/mi6/12mi6ksu52kebokes_gcc/sagit-p-oss'
[+] GKI_ROOT: /home/yang/mi6/12mi6ksu52kebokes_gcc/sagit-p-oss
+ test -d /home/yang/mi6/12mi6ksu52kebokes_gcc/sagit-p-oss/common/drivers
+ test -d /home/yang/mi6/12mi6ksu52kebokes_gcc/sagit-p-oss/drivers
+ DRIVER_DIR=/home/yang/mi6/12mi6ksu52kebokes_gcc/sagit-p-oss/drivers
+ test -d /home/yang/mi6/12mi6ksu52kebokes_gcc/sagit-p-oss/KernelSU
+ git clone https://github.com/tiann/KernelSU
Cloning into 'KernelSU'...
remote: Enumerating objects: 20401, done.
remote: Counting objects: 100% (624/624), done.
remote: Compressing objects: 100% (242/242), done.
remote: Total 20401 (delta 363), reused 554 (delta 306), pack-reused 19777
Receiving objects: 100% (20401/20401), 14.98 MiB | 5.21 MiB/s, done.
Resolving deltas: 100% (11416/11416), done.
+ cd /home/yang/mi6/12mi6ksu52kebokes_gcc/sagit-p-oss/KernelSU
+ git stash
No local changes to save
++ git status
++ head -n1
++ grep -Po 'v\d+(\.\d+)*'
+ '[' '' ']'
+ git pull
Already up to date.
+ '[' -z v0.5.2 ']'
+ git checkout v0.5.2
Note: switching to 'v0.5.2'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 0bda101d ci: fix WSA upload path (#372)
+ cd /home/yang/mi6/12mi6ksu52kebokes_gcc/sagit-p-oss
+ echo '[+] GKI_ROOT: /home/yang/mi6/12mi6ksu52kebokes_gcc/sagit-p-oss'
[+] GKI_ROOT: /home/yang/mi6/12mi6ksu52kebokes_gcc/sagit-p-oss
+ echo '[+] Copy kernel su driver to /home/yang/mi6/12mi6ksu52kebokes_gcc/sagit-p-oss/drivers'
[+] Copy kernel su driver to /home/yang/mi6/12mi6ksu52kebokes_gcc/sagit-p-oss/drivers
+ cd /home/yang/mi6/12mi6ksu52kebokes_gcc/sagit-p-oss/drivers
+ test -d /home/yang/mi6/12mi6ksu52kebokes_gcc/sagit-p-oss/common/drivers
+ test -d /home/yang/mi6/12mi6ksu52kebokes_gcc/sagit-p-oss/drivers
+ ln -sf ../KernelSU/kernel kernelsu
+ cd /home/yang/mi6/12mi6ksu52kebokes_gcc/sagit-p-oss
+ echo '[+] Add kernel su driver to Makefile'
[+] Add kernel su driver to Makefile
+ DRIVER_MAKEFILE=/home/yang/mi6/12mi6ksu52kebokes_gcc/sagit-p-oss/drivers/Makefile
+ DRIVER_KCONFIG=/home/yang/mi6/12mi6ksu52kebokes_gcc/sagit-p-oss/drivers/Kconfig
+ grep -q kernelsu /home/yang/mi6/12mi6ksu52kebokes_gcc/sagit-p-oss/drivers/Makefile
+ printf 'obj-$(CONFIG_KSU) += kernelsu/\n'
+ grep -q kernelsu /home/yang/mi6/12mi6ksu52kebokes_gcc/sagit-p-oss/drivers/Kconfig
+ sed -i '/endmenu/i\source "drivers/kernelsu/Kconfig"' /home/yang/mi6/12mi6ksu52kebokes_gcc/sagit-p-oss/drivers/Kconfig
+ echo '[+] Done.'
[+] Done.

**Comment by tiann** [comment]
与我们无关。
