### ISSUE TITLE
Hello, sir , when i completed to build a custom ksumanager ,i found a problem that i can't use my custom ksumanager to manager ksu, it say  signature is not right

### ISSUE THREAD

**Issue by mzb98** [tiann/KernelSU#739]
Hello, sir , when i completed to build a custom ksumanager.apk,i found a problem that i can't use my custom ksumanager to manage 
 ksu root After i installed the ksumanager.apk to my phone  ,  it say  "signature is not right...". And i can build the kernel boot by myself . How can i add my  custom apk signature to the boot.img or boot build file  ?

**Comment by tiann** [comment]
https://github.com/tiann/KernelSU/blob/main/kernel/Makefile#L35

**Comment by mzb98** [comment]
Thank you sir,let me check <+ _ +>
