### ISSUE TITLE
Please Uplad New WSA Kernel

### ISSUE THREAD

**Issue by s1204IT** [tiann/KernelSU#744]
Please Upload WSA Kernel of 5.15.104.1 to v0.6.2 release.

@tiann

**Comment by s1204IT** [comment]
The kernel itself is unchanged.
Just a new WSA kernel for v0.6.2.

https://github.com/tiann/KernelSU/compare/v0.6.2...5d07e1d

**Comment by s1204IT** [comment]
https://github.com/tiann/KernelSU/actions/runs/5492616328#artifacts

This artifact will serve as the kernel for `v0.6.2`.

**Comment by s1204IT** [comment]
And now that [2306 WSA or released](//github.com/microsoft/WSA/discussions/359), we need it in [MagiskOnWSALocal](//github.com/LSPosed/MagiskOnWSALocal) and [WSA-Script](//github.com/YT-Advanced/WSA-Script).

**Comment by tiann** [comment]
> https://github.com/tiann/KernelSU/actions/runs/5492616328#artifacts
> 
> This artifact will serve as the kernel for `v0.6.2`.

Download it here and upload to v0.6.2?

**Comment by tiann** [comment]
uploaded

**Comment by s1204IT** [comment]
Yes!
Thanks!
