### ISSUE TITLE
Function REPLACE

### ISSUE THREAD

**Issue by Yervant7** [tiann/KernelSU#751]
I'm trying to make a module made for magisk work in kernelsu, it has the .replace file in a folder with other files along with the .replace, like in kernelsu the .replace doesn't work, I used the function REPLACE in customize.sh And when I install and restart, the other files inside the module that were together the .replace file does not appear in the target folder, Is this a bug or my stupidity? I don't know very well how to create modules. Thanks

**Comment by tiann** [comment]
KernelSU will never create .replace file, this is expected behavior

**Comment by Yervant7** [comment]
> KernelSU will never create .replace file, this is expected behavior 

Ok, I thought the replace function was a similar alternative

**Comment by tiann** [comment]
The function is same, but it doesn't mean that the implementation is identical.
