### ISSUE TITLE
Hello, sir, I compiled a kernelsu manager, which caused a bug "overlayfs ..."

### ISSUE THREAD

**Issue by mzb98** [tiann/KernelSU#752]
Sir, please read what I said, thank you. ( I have tried all previous github issue solutions )
    I have already set the signature id before, and then installed the software I compiled, but still reported an error (overlayfs  is not available).
Then, I decompressed the apk package and found that the manager I compiled lacked a "libksud.so" file compared to the official manager, but it did not prompt me that this file was missing during compilation.

（I have tried many times, and I think there is a problem with the compiled manager.apk source file）

my logcat:
https://github.com/mzb98/ksulog

(id already changed)
![page5](https://github.com/tiann/KernelSU/assets/77035976/a3967f69-0c05-4d80-87e8-b2ca6b71cbfa)

(overlayfs  is not available).

![page3](https://github.com/tiann/KernelSU/assets/77035976/389677e1-1ecb-4051-aa3c-12152f0154cd)

**Comment by tiann** [comment]
Read the CI script to see how to build manager

**Comment by mzb98** [comment]
Thank your sir .
