### ISSUE TITLE
Headphone not working on Samsung S23 Ultra (Snapdragon)

### ISSUE THREAD

**Issue by DrKetan** [tiann/KernelSU#756]
**Headsphone not working**

**To Reproduce**
1. Simply using Headphone, no sound at all
**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [Samsung S23 Ultra]
 - OS: [OneUI 5.1]
 - Version [A13]

**Additional context**
Let me know whch log will be helpful so I grab it accordingly.
[Logs_placeholder.txt](https://github.com/tiann/KernelSU/files/12025611/Logs_placeholder.txt)
[KernelSU_bugreport_2023-07-13_01_41.tar.gz](https://github.com/tiann/KernelSU/files/12032579/KernelSU_bugreport_2023-07-13_01_41.tar.gz)

**Comment by tiann** [comment]
send bugreport in KernelSU manager

**Comment by DrKetan** [comment]
> send bugreport in KernelSU manager

Thank you. Edited main post with adding bug report.

**Comment by Mdajombishwas7393** [comment]
Same problem with me..
When I rooted with kernelsu android 13.5.15.......
Samsung galaxy s23
Everything is ok but type c headphone not working.
I can volium up down with headphone button. But no sound
Plz solved it..
