### ISSUE TITLE
[Feature] Support Unmounting Modules on a Per-Module Basis

### ISSUE THREAD

**Issue by RecursiveRegistrations** [tiann/KernelSU#759]
### Is your feature request related to a problem? Please describe.

Currently, KernelSU's feature for unmounting modules for apps uses an all or nothing approach. An app is either configured to have all modules mounted or none of them mounted. This is a wonderful feature for hiding modules from apps that may not like them, but I think this feature could be made even more useful if support was added for allowing specific modules to be unmounted for an app while allowing others to remain mounted.

For example, suppose I have an app that doesn't work when a specific module is mounted, but I don't want to unmount all of the modules from the app. With this feature, I could simply configure KernelSU to unmount the problematic module for the app while allowing all of the other modules to remain active.

### Describe the solution you'd like.

Ideally, an option could be added to the KernelSU Manager UI that would allow for users to unmount specific modules rather than using the all or nothing approach that KernelSU currently provides.

### Describe alternatives you've considered.

I can't think of any alternative to this feature other than simply not implementing it an leaving the all or nothing approach as the only option.

**Comment by tiann** [comment]
Umount is mainly used for hiding, hiding or not hiding, no half hiding.

**Comment by RecursiveRegistrations** [comment]
@tiann I know that is what it's used for, but I think it could still be useful to implement selective hiding.

**Comment by tiann** [comment]
PRs welcome

**Comment by RecursiveRegistrations** [comment]
@tiann Time-permitting, I will certainly look in to it.
