### ISSUE TITLE
[Feature] Add Zygisk-Compatible API for Injecting Code in the Zygote Process

### ISSUE THREAD

**Issue by RecursiveRegistrations** [tiann/KernelSU#760]
### Is your feature request related to a problem? Please describe.

Currently, in order to run a module with KernelSU that uses Zygisk, users must install the [Zygisk on KernelSU](https://github.com/Dr-TSNG/ZygiskOnKernelSU) module. While this module is wonderful, it unfortunately has the side effect of increasing the footprint that apps can use for detecting if a device is rooted. A good example of this is issue https://github.com/tiann/KernelSU/issues/727.

I think it would be great if KernelSU had a Zygisk-compatible API built directly into it. As far as I understand, this would make it possible to reduce the footprint that is left by the current implementation of Zygisk since it would be implemented at a kernel level.

### Describe the solution you'd like.

Rather than relying on the Zygisk module, which leaves a detectable footprint even if Shamiko is used to hide it, implementing it in the kernel could allow for better hiding of its presence similar to how KernelSU already hides `su` visibility.

### Describe alternatives you've considered.

The current alternative is to use the Zygisk on KernelSU module in conjunction with Shamiko, but this approach is not always advanced enough to prevent root detection from triggering in apps.

**Comment by RecursiveRegistrations** [comment]
@tiann I'm curious what the closure reason was? I'm not protesting it, but I would like to know. Is what I said about hiding being better if this is done just not true?

**Comment by tiann** [comment]
Not planned
