### ISSUE TITLE
Unable to enable root for apps with android13-5.15.74_2023-02-boot, android13-5.15.74_2022-05-boot is working

### ISSUE THREAD

**Issue by asheroto** [tiann/KernelSU#764]
**Describe the bug**
When trying to boot to the latest version of android13-5.15.74, the [android13-5.15.74_2023-02-boot](https://github.com/tiann/KernelSU/releases/download/v0.6.1/android13-5.15.74_2023-02-boot.img.gz) file, although the phone boots successfully, enabling root on any apps fails.

Error message at bottom after enabling:
```
Failed to grant root for 10422
```

But it _does work with the older version_, [android13-5.15.74_2022-05-boot.img.gz](https://github.com/tiann/KernelSU/releases/download/v0.6.0/android13-5.15.74_2022-05-boot.img.gz). I am able to enable Superuser for any app.

**To Reproduce**
1. Boot with [android13-5.15.74_2023-02-boot.img.gz](https://github.com/tiann/KernelSU/releases/download/v0.6.1/android13-5.15.74_2023-02-boot.img.gz) on CPH2449
2. Tap on Superuser
3. Enable root for any app

**Expected behavior**
Root to be enabled without error message.

**Screenshots**

10866 - android13-5 15 74_2022-05-boot.img (working):
<details><summary>Details</summary>
<p>
<img src="https://github.com/tiann/KernelSU/assets/49938263/9fb9bd99-8e25-4764-a250-8223862afb93">
</p>
</details> 

11041 - android13-5 15 74_2023-02-boot.img (not working):
<details><summary>Details</summary>
<p>
<img src="https://github.com/tiann/KernelSU/assets/49938263/0126d5bf-3c6e-4b23-9a07-9ec02d5e35e9">
</p>
</details> 

**Smartphone (please complete the following information):**
 - Device: OnePlus 11 5G (CPH2449)
 - OS: OxygenOS
 - Version 13.1.0.580 (EX01)

**Additional context**
Since the old version works, there is no urgent need to fix.

**Comment by tiann** [comment]
Update manager

**Comment by asheroto** [comment]
Oh weird, I thought I had it updated. Will try that and report back if it doesn't work.

Thanks!
