### ISSUE TITLE
[Feature]建议新增备份原厂镜像

### ISSUE THREAD

**Issue by Datch666** [tiann/KernelSU#766]
### Is your feature request related to a problem? Please describe.

在magisk中有一个功能“恢复原厂镜像”，原理：首次系统进行全量更新后，会自动备份内核镜像，下次可以在更新的时候恢复原厂镜像，这样就可以使系统实现正常增量更新，而不是每次更新系统都需要全量更新，对于MIUI开发版一周一更新的情况还是比较友好的（全量一次更新就6+GB 徒增闪存消耗和流量消耗....）

### Describe the solution you'd like.

新增此功能（magisk的备份好像有一点小问题，他每次全量更新后都会进行一次备份 不会删掉旧备份 导致会占用内存空间，建议术哥可以加一个备份镜像管理功能，让用户管理(删除)已备份的镜像  并且每次全量更新后都会把旧的备份覆盖）

### Describe alternatives you've considered.

目前我已知的可以增量更新系统的办法只有这一个，而且也是开发成本较低的一个

**Comment by Datch666** [comment]
kernelflasher工具 可以通过备份另一分区boot 刷入到当前分区然后进行增量更新，最后更新完成刷入ak3更新包即可

**Comment by tiann** [comment]
如果你知道原理也知道如何去做，建议提 pr 而非 issue。系统更新频率很低，我个人没有这个需求。
