### ISSUE TITLE
Error executing /proc/mounts & mounting /prism partiton to rw

### ISSUE THREAD

**Issue by DrKetan** [tiann/KernelSU#768]
**Describe the bug**
Error executing /proc/mounts (su permission granted to shell)
Also /prism partition can't get mount as rw with mount -o remount,rw /prism (which is ext4 rw)

**To Reproduce**
1. adb shell su
/proc/mounts

Error : permission not granted
**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [Samsung S23U]
 - OS: [OneUi 5.1]
 - Version [A13]

**Additional context**
[KernelSU_bugreport_2023-07-16_14_34.tar.gz](https://github.com/tiann/KernelSU/files/12063625/KernelSU_bugreport_2023-07-16_14_34.tar.gz)

**Comment by tiann** [comment]
Nothing to do with KernelSU.
