### ISSUE TITLE
Cannot execute "su" in adb shell but can execute on Termux App on mobile

### ISSUE THREAD

**Issue by macaujack** [tiann/KernelSU#769]
When executing `adb shell`, and then `su`, it said `inaccessible or not found`:
```
127|r0q:/ $ su
/system/bin/sh: su: inaccessible or not found
```

But when executing `su` on the mobile APP "Termux", everything works fine (I grant root permission to it in KernelSU APP).

Sorry for asking a noob question. Thanks in advance :)

**Comment by japiotr123** [comment]
You need to add com.android.shell as granted app in kernelsu manager
