### ISSUE TITLE
when i build android common kernel with kernelsu,  get this err_info:Differences between ksymtab and symbol list detected

### ISSUE THREAD

**Issue by angrykub** [tiann/KernelSU#770]
ERROR: Differences between ksymtab and symbol list detected! 
these are two syms:
Symbols missing from ksymtab:  - __cfi_slowpath  - kasan_flag_enabled Symbols missing from symbol list

**Comment by tiann** [comment]
Nothing to do with KernelSU. If you don't know how to build kernel, check CI please.

**Comment by ItsLynix** [comment]
> Nothing to do with KernelSU. If you don't know how to build kernel, check CI please.

if it has nothing to do with kernelsu, then how come same kernel builds 100% fine before KernelSU is applied with the exact same commands?

**Comment by tiann** [comment]
Dont let me repeat. If you don't know how to build kernel, check CI please.
