### ISSUE TITLE
add /data/adb/ksu/bin to PATH

### ISSUE THREAD

**Issue by AzukiAtsui** [tiann/KernelSU#775]
- BINARY_DIR 的值为 `/data/adb/ksu/bin/`

- KernelSU/userspace/ksud/src
/ksu.rs 添加到 PATH 的是 BINARY_DIR

- `/system/bin/which busybox` 得到 ` /data/adb/ksu/bin//busybox` 。多了一个 `/` 字符

所以 `/data/adb/ksu/bin` 没有被正确添加到 PATH

**Comment by tiann** [comment]
多个 `/` 会影响什么？

**Comment by AzukiAtsui** [comment]
> 多个 `/` 会影响什么？

诚然，不影响它工作。但是作字符串对比时： `[ "$(which busybox)" == "/data/adb/ksu/bin/busybox" ]` 结果为 false，尽管用字符串来对比路径就不明智。在理想中，`which` 能得到规范的路径。
