### ISSUE TITLE
Licensing NC vs GPLv3

### ISSUE THREAD

**Issue by comradekingu** [tiann/KernelSU#776]
Noticed the translation license was specifically GPLv3-only, and looked to see if it should be GPLv3-or-later.

However, https://github.com/brevent/genuine/ is (CC) NC, and that isn't compatible with GPLv3-anything.

**To Reproduce**
At the bottom of https://github.com/brevent/genuine/
vs
https://github.com/tiann/KernelSU/blob/main/LICENSE

**Expected behavior**
Maybe it should say an exception was made (sublicensing) if that is the case?

**Comment by tiann** [comment]
https://creativecommons.org/share-your-work/licensing-considerations/compatible-licenses

> The [GNU General Public License version 3 ](https://www.gnu.org/copyleft/gpl.html)was declared a “BY-SA–Compatible License” for version 4.0 on 8 October 2015. Note that compatibility with the GPLv3 is one-way only, which means you may license your contributions to adaptations of BY-SA 4.0 materials under GPLv3, but you may not license your contributions to adaptations of GPLv3 projects under BY-SA 4.0

**Comment by comradekingu** [comment]
@tiann 
Unfortunately the CC licenses aren't compatible with each-other, as **NC** is a non-free license.
This is the 
CC BY-**NC**-SA 4.0
vs
CC CC-BY-SA 4.0

**NC** means non-commercial, which is a restriction on use.

**Comment by tiann** [comment]
I am not a lawer, if you know how to fix it, make a pr please.
