### ISSUE TITLE
Drivedroid can't get root directory from external sd card

### ISSUE THREAD

**Issue by mylove90** [tiann/KernelSU#781]
Hello,

I tried using drivedroid app with both KSU and Magisk.

What i noticed that, if i tried to add an image directory located on External SD card the app just fails to link that.

This behavior doesn't happen with Magisk but i don't want to use Magisk for lots of reasons.

Device: Redmi note 8 (Ginkgo)
KSU version: 0.6.1 (11041)
Drivedroid version: 0.10.50

**Comment by tiann** [comment]
Please use the latest KernelSU and send bugreport. We won't accept legacy version issues.

**Comment by mylove90** [comment]
Hello Sir,

Now i am building my own KernelSU kernel and using latest 0.7 ksu and latest manager app and issue still persistent.

What logs do you need ?

**Comment by UangGaming** [comment]
[KernelSU_bugreport_2024-04-09_23_04.tar.gz](https://github.com/tiann/KernelSU/files/14921165/KernelSU_bugreport_2024-04-09_23_04.tar.gz)

I Have Logs Cant Get SD Card DriveDroid On KSU

**Comment by mylove90** [comment]
> [KernelSU_bugreport_2024-04-09_23_04.tar.gz](https://github.com/tiann/KernelSU/files/14921165/KernelSU_bugreport_2024-04-09_23_04.tar.gz)
> 
> I Have Logs Cant Get SD Card DriveDroid On KSU But My Device Phone Samsung Galaxy A21s Kawa Kernel

As you can see...you won't get any help...same issue still exist in latest version and now you can't even use a directory from internal sd card anymore

I am seriously thinking to try A-Patch right now
