### ISSUE TITLE
[Feature] Custom PATH exposure support

### ISSUE THREAD

**Issue by electrikjesus** [tiann/KernelSU#782]
### Is your feature request related to a problem? Please describe.

I am working on updating Gearlock, and since it loads before the /system/bin folder has been mounted on /, I am having to workaround a bit more than I think we should for it to be able to see KernelSU's su binary. 

### Describe the solution you'd like.

Is there any way we could add a way to expand the path variable KernelSU has hard set to /system/bin/su to also be exposed to custom paths, like /gearlock/bin/su?

### Describe alternatives you've considered.

I have already considered mounting system at / in order to make this possible, but since the plan is to use gearlock as a recovery solution, that defeats the point.

**Comment by tiann** [comment]
I don't want to add this feature, because it will make the vast majority of ordinary users bear additional overhead for this edge case.

You are in recovery, there are many ways to root. For example,  you can  put a `su` to`/gearlock/bin/su`, and use SUID to grant root directly.
