### ISSUE TITLE
刷入模块小概率报错后会清空所有模块的严重问题

### ISSUE THREAD

**Issue by STTecCEO** [tiann/KernelSU#784]
**Describe the bug**
  刷入模块时有概率报错error  16 ，此时若重启所有模块都会消失
![Screenshot_20230719-135634](https://github.com/tiann/KernelSU/assets/35169436/190bf996-32e5-4a5d-b7ee-00f752fda3ad)

**To Reproduce**
  本次偶然出现的操作是刷入shamiko时出现本错误(可能与模块无关，之前是刷入调度模块时出现过一次此问题)，再次刷入模块后提示成功，重启发现除了刚刚刷的shamiko外其他模块全部消失。
  首次刷入后data/adb/ksu下的文件内容如图左侧区域，重启后是右侧区域，modules.img变小，此时内部只有shamiko一个模块
![Screenshot_20230719-200801](https://github.com/tiann/KernelSU/assets/35169436/2a10c044-b32c-4c5f-932f-6efa2b329b0a)

**Smartphone (please complete the following information):**
 - Device:Sony Xperia1Ⅲ
 - OS: 13
 - Version ksu 11090

**Comment by Xuoos** [comment]
> 我也出现了同样的bug，安装第一次失败报错和你一样，再安装就成功，重启模块全没了

**Comment by SherlockChiang** [comment]
但是，用了kernelsu为什么还要用shamiko呢（

**Comment by STTecCEO** [comment]
> 但是，用了kernelsu为什么还要用shamiko呢（

隐藏zygisk

**Comment by tiann** [comment]
需要复现然后上传一份 bugreport

**Comment by tiann** [comment]
由于我这没法复现并且没有相关日志，我将关闭此问题；如果有人复现此问题并提供日志，欢迎 reopen 它。

**Comment by trialman** [comment]
三星note10 , 4.9的内核 ,  kernelsu为最新11210版, 今天反复重启后, 所有模块突然消失了
