### ISSUE TITLE
Issue compiling KernelSU for Mi 10 Ultra (board name "cas")

### ISSUE THREAD

**Issue by starraiderx** [tiann/KernelSU#787]
Hello,

together with @zingrx i am trying to compile KernelSU for the Mi 10 Ultra (board name "cas") but I am encountering an issue with the latest version of KernelSU Manager. The error message I receive is: "The current Kernel Version 10704 is too low please upgrade to version 11701 or higher".

I am using the following kernel as source: [android_kernel_xiaomi_cas](https://github.com/AcmeUI-Devices/android_kernel_xiaomi_cas) by @asuka-mio.

Interestingly, KernelSU Manager Version 0.5.7 works without any problems.

I am unsure if this is a problem on the Kernel source side or if Kernel version 4.19 is no longer supported.

![photo_2023-07-20_15-50-20](https://github.com/tiann/KernelSU/assets/33199500/7c4e8952-fc9e-4260-9019-eb0ab82c3fc4)

![photo_2023-07-20_15-50-25](https://github.com/tiann/KernelSU/assets/33199500/4c7f4c3b-6c4f-4d84-b857-02b055fb1195)

**Comment by tiann** [comment]
> The current Kernel Version 10704 is too low please upgrade to version 11701 or higher

You should update KernelSU source code.

**Comment by asuka-mio** [comment]
Done. @starraiderx
