### ISSUE TITLE
Manager Android 9 无法读取应用列表

### ISSUE THREAD

**Issue by wackejohn** [tiann/KernelSU#796]
**Describe the bug**
Android 9 无法读取应用列表

**Screens
![Screenshot_20230721-080013](https://github.com/tiann/KernelSU/assets/24863513/f20a9a94-5b22-417e-9e27-65f31b0593f5)
hots**
![Screenshot_20190910-111712](https://github.com/tiann/KernelSU/assets/24863513/5e347d85-f69e-4e6b-9d7a-34a68a2531d3)

**Smartphone (please complete the following information):**
 - Device: HTC U12+
 - OS: Android 9.0

**Additional context**
 如图所示，自编译内核，app显示工作中，但应用列表刷新不出来。

**Comment by Coconutat** [comment]
> **Describe the bug** Android 9 无法读取应用列表
> 
> **Screens ![Screenshot_20230721-080013](https://user-images.githubusercontent.com/24863513/255112516-f20a9a94-5b22-417e-9e27-65f31b0593f5.png) hots** ![Screenshot_20190910-111712](https://user-images.githubusercontent.com/24863513/255112534-5e347d85-f69e-4e6b-9d7a-34a68a2531d3.png)
> 
> **Smartphone (please complete the following information):**
> 
> * Device: HTC U12+
> * OS: Android 9.0
> 
> **Additional context** 如图所示，自编译内核，app显示工作中，但应用列表刷新不出来。

尝试让设备开机的时候SELinux为宽容模式，如果宽容后可以用，那就证明ksu可以工作。把剩下就是你适配安卓9了。ksu安卓最低支持到安卓10。

**Comment by Coconutat** [comment]
> > 尝试让设备开机的时候SELinux为宽容模式，如果宽容后可以用，那就证明ksu可以工作。把剩下就是你适配安卓9了。ksu安卓最低支持到安卓10。
> 
> 呃，KernelSU有办法通过编辑配置文件的方法实现控制app的列表吗？

你需要自己实现此功能。

**Comment by wackejohn** [comment]
>你需要自己实现此功能。

刚用magisk模块，关闭了SElinux，app列表可以加载出来。。。适配安卓9这个真难倒我了。。。大佬方便适配不，我可以捐赠

**Comment by Coconutat** [comment]
> > 你需要自己实现此功能。
> 
> 刚用magisk模块，关闭了SElinux，app列表可以加载出来。。。适配安卓9这个真难倒我了。。。大佬方便适配不，我可以捐赠

我自己P10安卓9都没搞好QAQ
