### ISSUE TITLE
TIF_SECCOMP is removed from x86's thread_info.h

### ISSUE THREAD

**Issue by hmtheboy154** [tiann/KernelSU#8]
https://github.com/tiann/KernelSU/blob/96139986b39d0c3e915689ed3f57e5393cdf824e/kernel/ksu.c#L60

https://lore.kernel.org/all/20201116174206.2639648-11-krisman@collabora.com/

**Comment by hmtheboy154** [comment]
It use x86/x86_64 use `syscall_work` instead

https://elixir.bootlin.com/linux/v5.15.78/source/kernel/entry/common.c#L67
https://elixir.bootlin.com/linux/v5.15.78/source/arch/x86/include/asm/thread_info.h#L58

**Comment by hmtheboy154** [comment]
I replace `TIF_SECCOMP` with `SYSCALL_WORK_SECCOMP` and it works, so we need make a condition for this

**Comment by tiann** [comment]
It seems that this is not a problem of x86/x86_64, kernel above 5.11 migrate the TIF_flags to syscall_work flags: https://www.mail-archive.com/linux-kernel@vger.kernel.org/msg2382193.html

**Comment by hmtheboy154** [comment]
but arm/arm64 still got TIF_flags though

**Comment by hmtheboy154** [comment]
oh we can make a condition using `CONFIG_GENERIC_ENTRY` then

**Comment by tiann** [comment]
I think it is this config that makes the difference

**Comment by hmtheboy154** [comment]
fixed
