### ISSUE TITLE
Bluetooth was not working after Root with kernelSu on A33 5G Samsung.

### ISSUE THREAD

**Issue by MRGREENBD** [tiann/KernelSU#800]
**Describe the bug**

**To Reproduce**
![Screenshot_20230722_215423_Settings](https://github.com/tiann/KernelSU/assets/83047650/dfafedfd-2469-41fa-bb82-1325fa7332ba)
![Screenshot_20230722_215416_Settings](https://github.com/tiann/KernelSU/assets/83047650/dd6af3cd-e696-407d-9e68-b33c931f1e15)

1. Go to Bluetooth and turn on and connect with bluetooth device.
2. And make call someone call is connected but can't listen any word through Bluetooth music sound also not working.

**Smartphone (please complete the following information):**
 - Device: [Samsung A33 5G]
 - OS: [ONE UI 5.1]
 - Version [Android 13]

**Comment by tiann** [comment]
https://github.com/tiann/KernelSU/issues/697#issuecomment-1626898826
