### ISSUE TITLE
Problems on RMX3363/60 devices

### ISSUE THREAD

**Issue by cyberdroid1111** [tiann/KernelSU#801]
**Describe the bug**
KernelSU successfully installed from tree side, I used this tree [LINK](https://github.com/aospa-beet/android_kernel_oneplus_sm8350), But the superuser page is just buffering and in the modules section, it's written "overlayfs is not available, module cannot work!"

**To Reproduce**
1. Just open the app

**Screenshots**
Here are some screenshots:- 
![photo_6192539648044152470_w](https://github.com/tiann/KernelSU/assets/112175447/2596c03a-1aea-4869-a5c8-3ccfec8c9559)
![photo_6192539648044152469_w](https://github.com/tiann/KernelSU/assets/112175447/b9d8b1fb-9ea9-44b9-9502-13bbfe68efc0)
![photo_6192539648044152468_w](https://github.com/tiann/KernelSU/assets/112175447/3bfe8413-b18d-49e8-b51e-b07ee46d7c05)

**Smartphone (please complete the following information):**
 - Device: RMX3363
 - OS: Custom ROM

**Additional context**
Here is the log from the KernelSU.apk
* 
[KernelSU_bugreport_2023-07-24_19_45.tar.gz](https://github.com/tiann/KernelSU/files/12146951/KernelSU_bugreport_2023-07-24_19_45.tar.gz)

**Comment by cyberdroid1111** [comment]
Here is the full output of the script.sh, just for full pov of the problem
[kernelsu_script_output.txt](https://github.com/tiann/KernelSU/files/12147011/kernelsu_script_output.txt)

**Comment by tiann** [comment]
Search the issues and you will find the solution.

**Comment by cyberdroid1111** [comment]
But no issue has this problem of buffering aka:
`07-25 20:47:41.749  1645  4508 W InputManager-JNI: Input channel object '3450c91 Splash Screen me.weishu.kernelsu (client)' was disposed without first being removed with the input manager!
07-25 20:47:44.450 15224 15224 W me.weishu.kernelsu:root:0: ART APEX data files are untrusted.
07-25 20:47:44.572 15224 15224 D me.weishu.kernelsu:root:0: Time zone APEX ICU file found: /apex/com.android.tzdata/etc/icu/icu_tzdata.dat
07-25 20:47:44.573 15224 15224 D me.weishu.kernelsu:root:0: I18n APEX ICU file found: /apex/com.android.i18n/etc/icu/icudt70l.dat
07-25 20:47:44.591 15224 15224 W ziparchive: Unable to open '/data/user_de/0/me.weishu.kernelsu/cache/main.dm': No such file or directory
07-25 20:47:44.661 15224 15224 W me.weishu.kernelsu:root:0: unable to execute idmap2: Permission denied
07-25 20:47:44.680  1645  1958 W BroadcastQueue: Permission Denial: broadcasting Intent { act=com.topjohnwu.superuser.RECEIVER_BROADCAST flg=0x10 pkg=me.weishu.kernelsu (has extras) } from null (pid=15224, uid=10196) requires android.permission.BROADCAST_PACKAGE_REMOVED due to registered receiver BroadcastFilter{72364db 10196/u0 ReceiverList{74679ea 15172 me.weishu.kernelsu/10196/u0 remote:3498dd5}}
07-25 20:47:46.395 15172 15241 D ProfileInstaller: Skipping profile installation for me.weishu.kernelsu
07-25 20:47:54.693 15224 15224 I me.weishu.kernelsu:root:0: System.exit called, status: 0
`
