### ISSUE TITLE
BUG REPORT . When i use my custom Ksu manager ,I can't read or write  /data/data by  root cmd.

### ISSUE THREAD

**Issue by mzb98** [tiann/KernelSU#804]
BUG REPORT , When i use my custom Kernelsu manager ,I can't read or write  /data/data . Even i use su cmd .But  if  i grant the  root  to other app, it works fine.

**Comment by dabao1955** [comment]
Even if I am just a common person，I want to know:
- Why not use the official manager?
- Is there a log file? What is the kernel version?

**Comment by mzb98** [comment]
> Even if I am just a common person，I want to know:
> 
> * Why not use the official manager?
> * Is there a log file? What is the kernel version？

I just want to know how it work, And find a best way to use root.

**Comment by mzb98** [comment]
The kernel version is v0.6.1，the log file is normal . When i use "ls /data/data" ,it only show my custom ksu manager's package name.

**Comment by dabao1955** [comment]
> 

You can browse the source code to understand how KernelSU works.

**Comment by natsumerinchan** [comment]
I guess you forgot to compile ksud.
https://github.com/tiann/KernelSU/blob/main/.github/workflows/build-manager.yml#L87-L88
