### ISSUE TITLE
Root profile doesn't persist after a reboot

### ISSUE THREAD

**Issue by RenanLazarotto** [tiann/KernelSU#806]
I'm trying to keep the selected as superuser between reboots. So far, everytime the device restarts, I have to manually enable them.

**To Reproduce**
1. Select an app from the list
2. Enable superuser
3. Reboot
4. At the next boot, the superuser isn't enabled anymore

**Expected behavior**
If this is the expected behaviour, it would be nice to have as an option to keep superuser enabled between reboots. If it's not, keeping the superuser enabled is what I expected.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S10+
 - OS: Android 13 (PixelOS)
 - Version 11155

![Screenshot_20230725-204913_KernelSU](https://github.com/tiann/KernelSU/assets/1446403/4410d872-7c2f-4557-8742-9d5f6989ad41)

**Comment by tiann** [comment]
Search the issues and you will find the solution.

**Comment by RenanLazarotto** [comment]
Sorry to bother again, but searching was the first thing I did. I just searched through all the issues but I still can't figure out what I have missed.

I got some things though: should I set the UID to non-zero? I mean, all I need is that two or three apps always have access to root capabilities. What I'm looking for is to have full access to system files and to give GameGuardian enough access to work.

If I'm not asking too much, can you please point me what is the issue that can help me to achieve that?

I tried looking into ksu docs and I honestly didn't find anything that would help me - or I am completely missing something.

**Comment by tiann** [comment]
https://github.com/tiann/KernelSU/issues/436
https://github.com/tiann/KernelSU/issues/419
https://github.com/tiann/KernelSU/issues/276
