### ISSUE TITLE
请教一下kernelsu如何缓存编译呢

### ISSUE THREAD

**Issue by junknet** [tiann/KernelSU#807]
我在尝试参与kernelsu过程中，每次改动一下就全量编译 
`LTO=thin BUILD_CONFIG=common/build.config.gki.aarch64 build/build.sh` 
然后刷入重启
 有什么办法进行增量编译，加速开发过程吗

**Comment by natsumerinchan** [comment]
打上对应内核版本的patch https://github.com/tiann/KernelSU/tree/main/.github/patches

然后`CCACHE="/usr/bin/ccache" LTO=thin BUILD_CONFIG=common/build.config.gki.aarch64 build/build.sh`

**Comment by junknet** [comment]
感谢
