### ISSUE TITLE
Help fix save_allow_list create file failed: -126

### ISSUE THREAD

**Issue by baooab2** [tiann/KernelSU#810]
**Describe the bug**
i build kernel with latest kernelsu, but have a error save_allow_list create file failed: -126 error i found few solutions, it's built into source but not working, i tested on pixel 4 xl and pixel 3a, they both share the same error. my kernel pixel 4 xl is 4.14.170 but in the code is compare with 4.10.0, i have intentionally set it to 4.14.180 but still not working

#if LINUX_VERSION_CODE < KERNEL_VERSION(4, 14, 180)
	static bool keyring_installed = false;
	if (init_session_keyring != NULL && !keyring_installed &&
	    (current->flags & PF_WQ_WORKER)) {
		pr_info("installing init session keyring for older kernel\n");
		install_session_keyring(init_session_keyring);
		keyring_installed = true;
	}
#endif

Is there any solution to deal with it?

**Screenshots**
![Screenshot 2023-07-27 083710](https://github.com/tiann/KernelSU/assets/84269509/10494a8a-83d5-40c9-beb0-19d1d9f83773)

**Smartphone (please complete the following information):**
 - Device: [Pixel 4 xl, pixel 3a]
 - OS: [anndroid 10]
 - Version [4.14.170, 4.9.200]

**Comment by tiann** [comment]
https://github.com/tiann/KernelSU/issues/436
