### ISSUE TITLE
SELinux Current IAB Capabilities full restrictive

### ISSUE THREAD

**Issue by Kadalis** [tiann/KernelSU#813]
**Describe the bug**
dbus daemon in chroot can't start due to capabilities drop not permitted, though app capabilities in KernelSU all permitted.
`capsh --print` prints "Current IAB" with all negated capabilities.

**To Reproduce**
1. Mount NetHunter chroot
2. Run `dbus-daemon --nofork --system`
3. Get "Failed to drop capabilities: Operation not permitted" fatal error
4. `capsh --print` prints "Current IAB" with all negated capabilities.

**Expected behavior**
Expected no Current IAB defined, or Current IAB defined as all capabilities permitted, so dbus daemon will work

**Screenshots**
There is an error screenshot:
![dbus-error](https://github.com/tiann/KernelSU/assets/65240890/b080a0eb-2dc9-466a-9b50-55ec27eeba21)

**Smartphone (please complete the following information):**
 - Device: Huawei P20 Lite
 - OS: Android 13 (LeaOS 20) + NetHunter
 - Kernel: Self-Built from https://github.com/Kadalis/android_kernel_huawei_hi6250_nethunter 
 - SELinux state: Permissive

**Additional context**
I can blank IAB using capsh
![Termux-capsh-noIAB](https://github.com/tiann/KernelSU/assets/65240890/d01302bc-23c1-4e55-8254-b75016a044bd)

So I can get rid of it using `sudo -E capsh --iab="" -- /data/data/com.offsec.nethunter/files/scripts/bootkali`, it load kali shell without IAB defined and then I can start dbus easily:
![Termux-Kali-noIAB cleaned](https://github.com/tiann/KernelSU/assets/65240890/5b8baec0-5599-4446-936d-384927c6dd4e)

Question is must it be so, or there must be no restrictive IAB Capabilities defined at all and then this is a bug.

Seems there is can be two issues: one about IAB Capabilities, and other about "not permitted" error with SELinux Permissive
Correct me if Im wrong

**Comment by tiann** [comment]
I don't know what you're talking about, nor how this has anything to do with KernelSU.

**Comment by Kadalis** [comment]
Correction of mistakes

First of all, there is very foolish thing. I thought that capabilities is part of SELinux. Im was actually wrong, im understanding it now, and sorry for this
Second, it has too many details, and it is short version

There is an error "operation not permitted" when dbus trying to drop capabilities with KernelSU provided root, but there is no such error when using ADB-provided root.

This is capabilities from /proc/self/status of adb root shell:
```
CapInh: 0000000000000000
CapPrm: 0000007fffffffff
CapEff: 0000007fffffffff
CapBnd: 0000007fffffffff
CapAmb: 0000000000000000
```

And KernelSU root capabilities:
```
CapInh: ffffffffffffffff
CapPrm: ffffffffffffffff
CapEff: ffffffffffffffff
CapBnd: ffffffffffffffff
CapAmb: ffffffffffffffff
```

So, to fix it for me, i'm just zeroing ambient capabilities. There is [patch](https://gist.github.com/Kadalis/07cc708c7fb66c12f2af2eae05d0d6ea) if somebody will experience this problem too.
