### ISSUE TITLE
[BUG] Unlabeled files cause reboot and .img deletion

### ISSUE THREAD

**Issue by osm0sis** [tiann/KernelSU#817]
**Describe the bug:**

Any unlabeled SELinux context files/folders in modules.img or modules_update.img will cause KernelSU to suddenly reboot around post-fs-data and then delete the offending .img file, losing the module(s) there.

**Expected behavior:**

Ideally any SELinux context unlabeled files could be changed to u:object_r:system_file:s0 on the fly during boot if found, as this is what Magisk does.

**Smartphone information:**
 - Device: OnePlus 7T
 - OS: Lineage 20
 - KernelSU Version: 11087

**Comment by tiann** [comment]
How to reproduce it?

**Comment by osm0sis** [comment]
> How to reproduce it?

Create a modules_update.img which contains unlabeled files. I'll work out a bit of test script tomorrow if you need it.

**Comment by tiann** [comment]
I installed a new module and then mounted module_update.img to modules_update and then created the unlabeled file manually, but it didn't reproduce; we're currently getting several reports of disappearing modules, so if you can help reproduce that, I'd appreciate it!

**Comment by osm0sis** [comment]
Okay so here's basically what I've been doing to replicate, and I tried it from no modules (completely fresh KernelSU install) and from an existing modules.img with similar results, if I recall correctly from my earlier testing:

```
dump_moduleinfo() {
cat <<EOF > $1;
id=ksu-test
name=KernelSU Test
version=1
versionCode=1
author=Test
description=Test
EOF
}

moddir=/data/adb/modules/ksu-test
umask 077
if [ ! -d /data/adb/modules ]; then
  mkdir -p /data/adb/modules
  chmod 777 /data/adb/modules
fi
[ -d /data/adb/modules_update ] || mkdir -p /data/adb/modules_update
[ -d /data/adb/ksu ] || mkdir -p /data/adb/ksu
[ -f /data/adb/ksu/modules.img ] && cp -f /data/adb/ksu/modules.img /data/adb/ksu/modules_update.img
if [ ! -f /data/adb/ksu/modules_update.img ]; then
  make_ext4fs -b 1024 -l 256M /data/adb/ksu/modules_update.img 2>/dev/null \
    || mke2fs -b 1024 -t ext4 /data/adb/ksu/modules_update.img 256M
fi
mount -t ext4 -o rw /data/adb/ksu/modules_update.img /data/adb/modules_update
touch /data/adb/ksu/update;
umask 022
rm -rf $moddir
mkdir -p $moddir
dump_moduleinfo $moddir/module.prop
touch $moddir/update

moddir=/data/adb/modules_update/ksu-test
rm -rf $moddir
mkdir -p $moddir/system/etc
echo "test" > $moddir/system/etc/ksu
dump_moduleinfo $moddir/module.prop
touch $moddir/update
#chcon -hR "u:object_r:system_file:s0" $moddir
umount /data/adb/modules_update
```

If the chcon line is uncommented then it all works and boots, but commented the reboot and .img deletion occurs.

**Comment by tiann** [comment]
Here is the English translation:

I don't find this situation surprising. If you install modules manually, you have to deal with all the unexpected cases. When installing with a manager or ksud module install, the SELinux context will be set automatically. Unlike Magisk, our modules in ext4 image don't need context reset on every boot.

**Comment by tiann** [comment]
The module removal phenomenon is actually caused by triggering the protection mechanism. After /system/etc is overlaid as an unlabeled directory, the system is unable to boot normally. Triggering the rollback mechanism on reboot again.

**Comment by osm0sis** [comment]
Magisk just switches any unlabeled to system_file if found during boot, as far as I know.

**Comment by osm0sis** [comment]
Thanks so much! 🙂
