### ISSUE TITLE
内核5.10.157刷入AnyKernel3-android13-5.10.157_2023-03，管理器无法正常工作

### ISSUE THREAD

**Issue by wooyunvip** [tiann/KernelSU#820]
手机是pixel 6 ,内核版本为5.10.157
Linux localhost 5.10.157-android13-4-g3d63f48dc819 #1 SMP PREEMPT Tue Jun 13 15:36:31 UTC 2023 aarch64 Toybox

使用官方安装方法，使用AnyKernel3-android13-5.10.157_2023-03 img和pixel 6原boot.img修改新的new_boot.img刷入，重启后管理器提示内核太低，需要更新内核到11071或以上：
![pic](https://github.com/tiann/KernelSU/assets/24996837/1a6f9dc7-dd36-4d4b-8437-85f27102baeb)

**Comment by natsumerinchan** [comment]
就是字面意思，去更新内核

**Comment by lc0a** [comment]
手持 Redmi Note 9 Pro (代号`gauguin`)。在刷入自行编译的内核后也遇到了类似的问题（如图）。

![Screenshot_20230827-125617_KernelSU](https://github.com/tiann/KernelSU/assets/79348810/09e9f51a-501e-4b9f-9d11-f069b7e3cffa)

内核版本`4.19.113`，源码在[此处](https://gitlab.com/lc0a/android_kernel_xiaomi_gauguin/-/tree/lineage-20-lc-ksu)。
内核中包含的KernelSU确实为最新稳定版（[内核源码提交记录](https://gitlab.com/lc0a/android_kernel_xiaomi_gauguin/-/commit/64f3e59af3ada46959c7ef478a4251a8ffcb62da)，对应 KernelSU [`d394fd2e`](https://github.com/tiann/KernelSU/commit/d394fd2e014056f2b8bf8b9ec0fe64c045d5340b)）。

### 系统信息

* 设备: Redmi Note 9 Pro 5G (代号`gauguin`)
* 系统: LineageOS 20, Android 13
* KernelSU 管理器版本: v0.6.7 (11210)

### 日志文件
[KernelSU_bugreport_2023-08-27_12_55.tar_125540.gz](https://github.com/tiann/KernelSU/files/12447376/KernelSU_bugreport_2023-08-27_12_55.tar_125540.gz)
