### ISSUE TITLE
模块无法激活，且无法使用mtp和adb功能

### ISSUE THREAD

**Issue by Asgore-Dreemur** [tiann/KernelSU#824]
**Describe the bug/问题描述**
自己编译内核尝试支持KernelSU，内核版本4.9，设备为红米5p,代号vince  
系统为crDroid 7.17 android版本11  
SELinux为严格模式  
内核仓库地址:https://github.com/Blacksuan19/kernel_dark_ages_vince 默认分支  
KernelSU刷入模块后，在模块界面启用开关为灰色，无法禁用或启用，重启后模块也并未生效，仍然是灰色按钮  
使用稳定版0.6.2和开发版main均无法解决该问题  
su获取root权限正常  
查看了/data/adb/modules_update下的模块目录为空，/data/adb/modules下的模块目录只有module.prop和update,remove两个空文件  
且adb和mtp电脑不识别设备，但可以正常充电，手机上也没有提示usb调试  
日志:  

**To Reproduce/问题复现**
刷入任意模块后在模块界面查看

**Screenshots/截图**
![B9285C193A3D9347AE386EA368323B26](https://github.com/tiann/KernelSU/assets/81003019/10228413-23a7-4685-89b8-a5f993bb17f0)  
![68ADFF42366D97C8ED5E1E0DB21D5D49](https://github.com/tiann/KernelSU/assets/81003019/d7b26c83-47a0-42e7-8cef-54312d41cfd2)

**Comment by Asgore-Dreemur** [comment]
我的日志在github上无法上传，所以我将其上传到了蓝奏云，抱歉  
链接:https://wwoy.lanzouk.com/ivhLd146pg3g  
无密码

**Comment by Asgore-Dreemur** [comment]
使用的是KProbe集成，自己根据patch修改内核代码在最后链接阶段报错undefined refence

**Comment by Coconutat** [comment]
> 使用的是KProbe集成，自己根据patch修改内核代码在最后链接阶段报错undefined refence
@Aquarius223的方案是正解。

**Comment by Asgore-Dreemur** [comment]
> 模块问题 给kernel 打patch: [sticpaper/android_kernel_xiaomi_msm8998-ksu@646d0c8](https://github.com/sticpaper/android_kernel_xiaomi_msm8998-ksu/commit/646d0c836053ffa8743519c39fcabaecb258f00b) 或 https://github.com/sticpaper/android_kernel_xiaomi_msm8998-ksu/commits/dev 分支 `b7baedf9` 和 `c331c454`


我使用了[sticpaper/android_kernel_xiaomi_msm8998-ksu@646d0c8] (https://github.com/sticpaper/android_kernel_xiaomi_msm8998-ksu/commit/646d0c836053ffa8743519c39fcabaecb258f00b)  
问题并未解决，仍然是不能激活模块  
关于https://github.com/sticpaper/android_kernel_xiaomi_msm8998-ksu/commits/dev 分支 `b7baedf9` 和 `c331c454`,我无法找到`b7baedf9`和`c331c454`提交  
但是有`c331c454e486b3bfe423cc776b1cfbeb85e9467a`和`b7baedf92a16ae49f904e076f0ce08302326cdc5`这两个提交，是这两个提交吗

**Comment by Asgore-Dreemur** [comment]
看了，https://github.com/sticpaper/android_kernel_xiaomi_msm8998-ksu/commits/dev `b7baedf9` 和 `c331c454`这两个上边的东西我这里内核都修改好了
