### ISSUE TITLE
save allow_list failed 

### ISSUE THREAD

**Issue by ebenezerk846** [tiann/KernelSU#828]
**Describe the bug**

**To Reproduce**
1.In every restart the granted root permissions gets reset.modules seems fine.
Kprobes is disabled..
Attaching logs
[KernelSU_bugreport_2023-08-03_23_05.tar.gz](https://github.com/tiann/KernelSU/files/12253544/KernelSU_bugreport_2023-08-03_23_05.tar.gz)

**
**Smartphone (please complete the following information):**
 - Device: Redmi k20 pro
 - OS: Havoc os
 - Android 11

Thanks

**Comment by tiann** [comment]
Search issue first
