### ISSUE TITLE
无法启用overlayfs解锁system

### ISSUE THREAD

**Issue by weizili25830** [tiann/KernelSU#83]
开启后只要换个页面再回去就自己关了
就算不关页面直接重启开机还是关的

【超级会员V5】通过百度网盘分享的文件：000000
链接:https://pan.baidu.com/s/1DxWN8aSDsIb_7lbEGuZPCQ?pwd=9685 
提取码:9685
复制这段内容打开「百度网盘APP 即可获取」
系统环境
安卓13
miui14.0.23.1.9dev 开发版
小米12s ultra

**Comment by natsumerinchan** [comment]
It is still a fake button.

**Comment by Ylarod** [comment]
目前该按钮无实际作用
