### ISSUE TITLE
Partitions become read only

### ISSUE THREAD

**Issue by BobFrantic1** [tiann/KernelSU#830]
**Describe the bug**
When this module is installed, my partitions of my phone become read only.

**To Reproduce**
1. install the kernelSU v 0.6.2
2. check to see if root is read/write
3. install module ZygiskOnKernelSU
4. check to see if partions are still read/write and they aren't.  just read only.

**Expected behavior**
I expected to have read/write partions still

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A52S 5G
 - OS: Android 
 - Version 13
**Additional context**
Unsure if issue is with this module of if it triggers something in the kernel. Be interested if this has happened to anyone else...

**Comment by BobFrantic1** [comment]
don't understand why my issue was closed

**Comment by tiann** [comment]
Won't fix

**Comment by weskerty** [comment]
Google antiwrite protection.
