### ISSUE TITLE
[Feature]android14-5.15 support

### ISSUE THREAD

**Issue by fakerqu** [tiann/KernelSU#839]
### Is your feature request related to a problem? Please describe.

some manufactor has released their android 14 based ROM, but there is no gki for android14-5.15 in github release 

### Describe the solution you'd like.

google has release their new gki code, please add a github build action for android14-5.15

### Describe alternatives you've considered.

none

**Comment by naicfeng** [comment]
https://kernelsu.org/guide/installation.html#kernel-version-vs-android-version

> Kernel version vs. Android version
> Please note: Kernel version and Android version are not necessarily the same!

> If you find that your kernel version is android12-5.10.101, but your Android system version is Android 13 or other; please don't be surprised, because the version number of the Android system is not necessarily the same as the version number of the Linux kernel; The version number of the Linux kernel is generally consistent with the version of the Android system that comes with the device when it is shipped. If the Android system is upgraded later, the kernel version will generally not change. If you need to flash, please always refer to the kernel version!!

**Comment by archandanime** [comment]
@naicfeng From my understanding, if my device is `Pixel 7a`  which launched with `android13-5.10`, I can continue using this kernel `android13-5.10` with new Android 14 release, is that correct?

**Comment by tiann** [comment]
> @naicfeng From my understanding, if my device is `Pixel 7a` which launched with `android13-5.10`, I can continue using this kernel `android13-5.10` with new Android 14 release, is that correct? Edit: I have found this string in Android 14 Beta 5.2 OTA(in `system_ext.img`), I think Google uses the same kernel on Android 14 as on Android 13.
> 
> ```
> Linux version 5.10.107-android13-4-00006-g19424168db55-ab9177961 (build-user@build-host) (Android (8508608, based on r450784e) clang version 14.0.7 (https://android.googlesource.com/toolchain/llvm-project 4c603efb0cca074e9238af8b4106c30add4418f6), LLD 14.0.7) #1 SMP PREEMPT Fri Oct 14 18:30:15 UTC 2022
> ```

Exactly! There is no device launched with `android14-*` kernels now, all devices with Android 14 ROM are actually use `android12-*` or `android13-*` kernels.

**Comment by amteza** [comment]
@tiann The new `Pixel 8/8 Pro` comes with an android14-5.15 kernel. And we have already GKI released for these devices [GKI android14-5.15](https://source.android.com/docs/core/architecture/kernel/gki-android14-5_15-release-builds).

It will be great to have the github actions for this to be built with KernelSU.

**Comment by tiann** [comment]
It is time to add it!

**Comment by amteza** [comment]
BTW, I think that line `BUILD_CONFIG=common/build.config.gki.aarch64 build/build.sh` in `gki-kernel.yml` will require to be updated to `tools/bazel build //common:kernel_aarch64_dist` for `android14-5.15`, I'm testing it right now in a fork of your repo.

**Comment by amteza** [comment]
@tiann, this is driving me crazy. QQ, where is `Image` left after using `bazel` to compile the kernel? I tried `bazel-out` and `bazel-bin/common/kernel_aarch64`

**Comment by li-yifei** [comment]
@amteza They should be in `bazel-bin/common/kernel_aarch64`
I tried building them on my forked repo's [action](https://github.com/li-yifei/KernelSU/actions/runs/6490252240) and local, but the output images cannot work properly on my Pixel 8

**Comment by amteza** [comment]
@li-yifei yeah, did the same but with `$GITHUB_WORKSPACE/android-kernel/bazel-out/k8-fastbuild/bin/common/kernel_aarch64`. My Pixel 8 Pro boots but network (WiFi and 5G) don't work.

**Comment by Kcw1423** [comment]
trying to find kernel version android14-5.15.148, for oneplus 11 latest android 14 NA: CPH2451_14.0.0.501(EX01)
please can anyone help
