### ISSUE TITLE
Why is `v0.6.5` (`11182`)  removed?

### ISSUE THREAD

**Issue by th1nhhdk** [tiann/KernelSU#840]
I just build it for my phone (`pdx203`) , it doesn't work, app keeps complaining that my phone doesn't support GKI, but `v0.6.5` app with `v0.6.2` kernel works fine.

**Comment by Eudximoniia** [comment]
I built the kernel and applied it to the machine, the same thing happened

**Comment by tiann** [comment]
Because it has a fatal issue on 4.x kernel, we fixed it and release 0.6.6
