### ISSUE TITLE
[Feature]提权成功时能否弹出一个toasts以通知用户。

### ISSUE THREAD

**Issue by huangsijun17** [tiann/KernelSU#846]
便于在应用自动提权时通知用户提权成功。若每个APP可以单独选择是否显示就最好了。

**Comment by SoDebug** [comment]
但是没有什么意义，KernelSU的授权需要用户主动授权，如果应用程序提权成功，目标应用功能上能直接体现

**Comment by tiann** [comment]
Closed since no developer is willing to add it.

**Comment by lingsixuan** [comment]
我愿意尝试添加这个功能
