### ISSUE TITLE
can't modify any files requiring root perms when modules are installed

### ISSUE THREAD

**Issue by imapancake22** [tiann/KernelSU#851]
**Describe the bug**
Currently I have zygisk, lsposed, and universal safetynet fixer installed. Whenever I try to modify files using x-plore, turn on or pause adaway it doesn't work. It worked before I installed any modules

**To Reproduce**
Steps to reproduce the behaviour:
1. Install the modules listed above
2. Do something requiring root
3. Watch it not work

**Expected behaviour**
I am able to use applications requiring root normally

**Smartphone (please complete the following information):**
 - Device: Google Pixel 7 pro
 - OS: android 13
 - Version 20-20230805-NIGHTLY-cheetah

**Additional context**

**Comment by tiann** [comment]
KernelSU doesn't support `/system` rw, it is recommended to modify it by modules.
