### ISSUE TITLE
无法安装或卸载模块

### ISSUE THREAD

**Issue by a1623382** [tiann/KernelSU#852]
**Describe the bug**
安装模块时显示“mount failed”
卸载模块后，重启模块依然未被卸载

**Screenshots**
![Screenshot_20230810-142746](https://github.com/tiann/KernelSU/assets/34230652/209aa744-e5c2-40f9-bb77-e5dc06f7c436)

**Smartphone (please complete the following information):**
![Screenshot_20230810-142750](https://github.com/tiann/KernelSU/assets/34230652/8d27d585-d1af-4d14-aa15-8eef6d45710b)

**Additional context**
                           _ __       
  /\ /\___ _ __ _ __   ___| / _\/\ /\ 
 / //_/ _ \ '__| '_ \ / _ \ \ \/ / \ \
/ __ \  __/ |  | | | |  __/ |\ \ \_/ /
\/  \/\___|_|  |_| |_|\___|_\__/\___/

- Preparing image
- Module size: 193.37 MB
- Estimated minimum size of the filesystem: 253231
- Target image size: 721.12 MB
resize2fs 1.46.2 (28-Feb-2021)
The filesystem is already 705240 (1k) blocks long.  Nothing to do!

- Mounting image
- Mount failed: Device or resource busy (os error 16), retry with system mount
losetup: /data/adb/ksu/update_tmp.img: Too many open files
mount: losetup failed 1
- Current boot slot: _a
- Device is system-as-root
Archive:  /data/user/0/me.weishu.kernelsu/cache/module.zip
  inflating: module.prop
******************
 YouTube ReVanced 
 by j-hc 
******************
*********************
 Powered by KernelSU 
*********************
Archive:  /data/user/0/me.weishu.kernelsu/cache/module.zip
  inflating: customize.sh
- Extracting module files
Archive:  /data/user/0/me.weishu.kernelsu/cache/module.zip
  inflating: customize.sh
   creating: bin/
   creating: bin/arm64/
  inflating: bin/arm64/cmpr
   creating: bin/arm/
  inflating: bin/arm/cmpr
  inflating: base.apk
  inflating: uninstall.sh
  inflating: service.sh
  inflating: com.google.android.youtube.apk
  inflating: module.prop

* com.google.android.youtube is up-to-date
* Setting Permissions
* Mounting com.google.android.youtube
* Optimizing com.google.android.youtube
* Cleanup
* Done
  by j-hc (github.com/j-hc)
 
- Done
umount: /data/adb/modules_update: Invalid argument

**Comment by tiann** [comment]
你的问题是什么？显示“mount failed” 并不就代表失败了。

**Comment by a1623382** [comment]
目前模块不能安装或卸载，重启后模块数量和版本不会有任何变化，安装的新模块不会安装成功，更新和卸载也一样

**Comment by tiann** [comment]
没有权限访问日志

**Comment by a1623382** [comment]
> 没有权限访问日志

现在应该好了
https://drive.google.com/file/d/1uwiVDteeNL2xAZqtYCBeyBYr_lELOgfR/view?usp=drivesdk

**Comment by tiann** [comment]
日志显示 `youtube-jhc` 这个模块是安装成功了的

**Comment by a1623382** [comment]
> 日志显示 `youtube-jhc` 这个模块是安装成功了的

实际上是更新失败的，还有‘adguardcert’这个模块是新安装的，但是重启后ksu里面找不到

**Comment by tiann** [comment]
你需要这样做：
1. 复现此问题。
2. 在模块安装界面右上角有保存日志的按钮，点击保存。
3. 上传模块安装日志文件，和设置里面的 bugreport 文件。

**Comment by a1623382** [comment]
`这是安装完adguardcert后，重启前的日志：`[KernelSU_bugreport_2023-08-10_15_43.tar.gz](https://drive.google.com/file/d/1vA80WHYaHPzfPM9ylyc6l6lbM5qvKQNP/view?usp=drivesdk) ``
这是重启后的日志：[KernelSU_bugreport_2023-08-10_15_47.tar.gz](https://drive.google.com/file/d/1vCdfj5Nm3Ip34_mGGgULg7fPX09DXDDp/view?usp=drivesdk)

**Comment by a1623382** [comment]
这是重启后的系统错误报告：[bugreport-rtwo_g-T1TR33.43-48-21-2023-08-10-15-52-21.zip](https://drive.google.com/file/d/1vEAgRCm7QP5JhZ9wnW20mV69jKBG_o_y/view?usp=drivesdk)

**Comment by tiann** [comment]
KernelSU: 11089，请先更新你的内核到 0.6.6 再试；另外，模块安装界面右上角有个保存按钮，那里的日志也需要发一下

**Comment by a1623382** [comment]
emm，0.7.6又遇到了这个问题，这是点击保存按钮之后的log
[KernelSU_install_log_2024-01-19-12-01-09.log](https://github.com/tiann/KernelSU/files/13984043/KernelSU_install_log_2024-01-19-12-01-09.log)
