### ISSUE TITLE
[Feature] Root permissions carry over reboots

### ISSUE THREAD

**Issue by Insomniac05** [tiann/KernelSU#854]
It would be really cool if there was a way that root permissions granted to apps didn't get removed after every reboot, it's troublesome especially when using modules cause everytime a module is installed a restart is needed and that wipes all the root access granted to apps

### Describe the solution you'd like.

It would be really helpful if there is a toggle which can be turned on if the permission is to be a permanent one or a one boot thing

### Describe alternatives you've considered.

NA

**Comment by tiann** [comment]
This is a bug, search the issues and you will find the solution.
