### ISSUE TITLE
更新模块时未将老版本模块大小减去

### ISSUE THREAD

**Issue by misaka19465** [tiann/KernelSU#855]
**Describe the bug**
在更新模块时，kernelsu不会考虑老版本模块的空间占用，而是直接把原镜像大小加上新版本模块大小，在剩余空间较小的手机上更新一些空间占用较大的模块（例如Gapps模块）时可能会爆储存
**To Reproduce**
Steps to reproduce the behaviour:
1. 更新一个模块

**Expected behaviour**
先减去老版本模块大小再加上新版本模块大小

**Additional context**
建议在安装模块时记录给该模块扩大的镜像大小，并在更新时减去该大小

**Comment by tiann** [comment]
resizefs 的时候会 trim，会占用一些额外空间，但应该不是无限增长的
