### ISSUE TITLE
custom gki kernel 

### ISSUE THREAD

**Issue by Hamood111** [tiann/KernelSU#862]
### Is your feature request related to a problem? Please describe.

mi 11 ultra doesn't come with gki kernel 

### Describe the solution you'd like.

i hope in the future u make gki kernel for mi 11 ultra so we can use kernelsu as everybody else 

### Describe alternatives you've considered.

maybe in the future kernelsu work with qgki kernels

### Additional context

![Screenshot_2023-08-12-18-59-37-748_com android settings](https://github.com/tiann/KernelSU/assets/116981650/4aa5a89d-e16d-411f-b84e-14bb38fb4026)
![Screenshot_2023-08-12-19-00-53-858_me weishu kernelsu](https://github.com/tiann/KernelSU/assets/116981650/a0b51380-8888-46bc-9067-1adb69dfe46c)

**Comment by tiann** [comment]
Read docs first.
