### ISSUE TITLE
开机无法执行模块中的service.sh

### ISSUE THREAD

**Issue by Wcoom** [tiann/KernelSU#868]
#!/system/bin/sh
echo 105000 > /sys/class/thermal/thermal_zone32/trip_point_0_temp
echo 105000 > /sys/class/thermal/thermal_zone33/trip_point_0_temp
类似这种service.sh脚本开机无法执行，只能手动进模块目录执行

**Comment by Wcoom** [comment]
http://www.wuduixiaotouming.love/d/%E9%98%BF%E9%87%8C%E4%BA%91/%E4%BF%AE%E6%94%B9GPU%E6%B8%A9%E5%BA%A6%E5%A2%99%E9%80%82%E7%94%A8%E4%BA%8EMIUI13%2014.zip
这是模块的链接

**Comment by Wcoom** [comment]
#!/sbin/sh

#################
# Initialization
#################

umask 022

# echo before loading util_functions
ui_print() { echo "$1"; }

require_new_magisk() {
  ui_print "*******************************"
  ui_print " Please install Magisk v20.4+! "
  ui_print "*******************************"
  exit 1
}

#########################
# Load util_functions.sh
#########################

OUTFD=$2
ZIPFILE=$3

mount /data 2>/dev/null

[ -f /data/adb/magisk/util_functions.sh ] || require_new_magisk
. /data/adb/magisk/util_functions.sh
[ $MAGISK_VER_CODE -lt 20400 ] && require_new_magisk

install_module
exit 0
模块的写入脚本

**Comment by Wcoom** [comment]
内核版本∶11192
管理器版本∶11194

**Comment by tiann** [comment]
传 bugreport

**Comment by Wcoom** [comment]
http://38.6.181.105:5244/d/%E9%98%BF%E9%87%8C%E4%BA%91/KernelSU_bugreport_2023-08-15_15_52.tar.gz

**Comment by tiann** [comment]
模块名字叫什么？

**Comment by tiann** [comment]
```
08-15 11:33:25.303  2172  2172 I KernelSU: ksud::module: exec /data/adb/modules/Feasenabler/service.sh
08-15 11:33:25.314  2172  2172 I KernelSU: ksud::module: exec /data/adb/modules/zygisk_shamiko/service.sh
08-15 11:33:25.316  2172  2172 I KernelSU: ksud::module: exec /data/adb/modules/power_limiter/service.sh
08-15 11:33:25.323  2172  2172 I KernelSU: ksud::module: exec /data/adb/modules/swap_controller/service.sh
08-15 11:33:25.325  2172  2172 I KernelSU: ksud::module: exec /data/adb/modules/zygisksu/service.sh
08-15 11:33:25.333  2172  2172 I KernelSU: ksud::module: exec /data/adb/modules/zygisk_lsposed/service.sh
08-15 11:33:25.338  2172  2172 I KernelSU: ksud::module: exec /data/adb/modules/VKFEATURES_CONTROLLER/service.sh
08-15 11:33:25.346  2172  2172 I KernelSU: ksud::module: exec /data/adb/modules/xgGPUwdq/service.sh
```

日志显示 service.sh 执行了，如果没有效果；你需要自己检查是不是有别的问题，比如配置被覆盖等。

**Comment by Wcoom** [comment]
> 模块名字叫什么？
修改GPU温控墙的，原理是修改路径为/sys/class/thermal/thermal_zone32/trip_point_0_temp，把trip_point_0_temp里的内容修改为105000，开始时候我也以为开机有一段时间会修改不了，所以延迟了一分钟执行但是结果依旧修改不了，包括这种echo 200 > /proc/sys/vm/swappiness也是自动执行不了，只能手动执行。

**Comment by tiann** [comment]
日志显示这个脚本执行了

**Comment by Wcoom** [comment]
> 日志显示这个脚本执行了

好的，谢谢作者。找到原因了，内核接口问题只能用户层手改。
