### ISSUE TITLE
Turn off the machine on reboot

### ISSUE THREAD

**Issue by vGreatDragon** [tiann/KernelSU#869]
**Describe the bug**
After installing any first module, the reboot is successful, all subsequent reboots are forced, or the device simply turns off. At the same time, the installed modules work properly. One more feature, this is observed only on Treble firmware, on EMUI all reboots are working properly.
[dmesg.log](https://github.com/tiann/KernelSU/files/12342577/dmesg.log)
[kernel1_log.txt](https://github.com/tiann/KernelSU/files/12342844/kernel1_log.txt)

**To Reproduce**
Steps to reproduce the behaviour:
4. See the error

**Expected behaviour**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Huawei Nova 2s hi3660
 - OS: EMUI-9.0, Treble Generic A13
 - Version kernel 4.9.113 KSU

**Additional context**
Pangu_V9_KSU-GSI 
https://github.com/Coconutat/android_kernel_huawei_vtr_emui9_KernelSU/releases/

**Comment by tiann** [comment]
I am sorry, i cannot understand what you say.
