### ISSUE TITLE
KernelSU breaks Huawei 4.9 kernel when integrated

### ISSUE THREAD

**Issue by Bakoubak** [tiann/KernelSU#872]
This bug happens when i try to compile this kernel: Linux-4.9.148 for EMUI 9.1, when i compile without KSu, everything goes flawlessly but when i integrate it, it errors out on __GFP_ZERO being undefined in include/linux/pmalloc.h. Defining it using its value causes a kernel panic at boot and including gfp.h causes a panic too.

**To Reproduce**
Steps to reproduce the behaviour:
1. Download this kernel: https://download-c1.huawei.com/download/downloadCenter?downloadId=1EB9D1137670776B87F2B4C5FCC03F93&version=466A3453D362162DC886C26075911925&siteCode=worldwide
2. Integrate + patch for KSu
3. Start build
4. Errors out on pmalloc.h/undefined __GFP_ZERO

**Expected behaviour**
Kernel should compile like stock kernel

**Screenshots**
![image](https://github.com/tiann/KernelSU/assets/60509176/9b1230de-69bf-4bad-b08c-ed5fc858cf25)

**Smartphone**
 - Device: Huawei P Smart 2019/POT-LX1
 - OS: Android 13 (custom) installed ontop of Android 9.1 (stock)
 - Version : 4.9.148

**Additional context**
rebooting to fastboot shows this reboot reason:
AP_S_PANIC 96
HI_APPANIC_RESERVED
...

**Comment by Coconutat** [comment]
In fact,You need morify code by yourself.You need disable it in defconfig.    
I write a tutorial for Huawei Kernel.     
Link in here:[Wiki](https://github.com/Coconutat/HuaweiP10-GSI-And-Modify-Or-Support-KernelSU-Tutorial/wiki/7.KernelSU适配EMUI9或9.1.0系统的内核).   
Notice: Wiki write by Chinese.

**Comment by Bakoubak** [comment]
> 

Thanks for your help but it didn't fix my issue unfortunately

**Comment by Coconutat** [comment]
> > 
> 
> Thanks for your help but it didn't fix my issue unfortunately

I know how to fix it.Watch this:[fix _GFP_ZERO](https://github.com/Abdelhay-Ali/android_kernel_huawei_kirin710_KernelSU/commit/5067cb46ba79c54b043fe25e6cea5094b5f417cf)

**Comment by Coconutat** [comment]
> > 
> 
> Thanks for your help but it didn't fix my issue unfortunately

However, please remember that you still need to turn off other interfering feature options.Other options will always interfere with compiling KernelSU into the kernel and affect its effectiveness.

**Comment by Bakoubak** [comment]
I was already using your fix but it panicks on my device, also are your builds of kernelsu working on P Smart 2019 ? I couldnt get any Kirin 710 build to work on my device unfortunately

**Comment by Coconutat** [comment]
> 

Well, my device is P10 and I use the Kirin 960. But I made some kernel for other Huawei Kirin 710 devices. The work is fine.

**Comment by Coconutat** [comment]
> I was already using your fix but it panicks on my device, also are your builds of kernelsu working on P Smart 2019 ? I couldnt get any Kirin 710 build to work on my device unfortunately

Well, my device is P10 and I use the Kirin 960. But I made some kernel for other Huawei Kirin 710 devices. The work is fine.

**Comment by Coconutat** [comment]
> I was already using your fix but it panicks on my device, also are your builds of kernelsu working on P Smart 2019 ? I couldnt get any Kirin 710 build to work on my device unfortunately

I hope you haven't used the debug section of my wiki. Where is it just for testing. May cause kernel painc
