### ISSUE TITLE
[Feature] customizable default_reserve_size

### ISSUE THREAD

**Issue by rhjdvsgsgks** [tiann/KernelSU#875]
### Is your feature request related to a problem? Please describe.

when installing modules more than once. it will use at least 3 times of the space of modules.img. one for modules.img, one for modules_update.img. the last for update_tmp.img. in this case, big default_reserve_size will significantly increase this storage requirement

### Describe the solution you'd like.

make default_reserve_size adjustable. and add a button to trim the size of modules.img

### Describe alternatives you've considered.

suggest user to run `resize2fs -M /data/adb/ksu/modules_update.img` manually

### Additional context

#855 aggravated this

**Comment by tiann** [comment]
1. This adds an extra complexity that is difficult for the normal user to understand.
2. The files you mentioned are temporary and will be deleted eventually.

**Comment by tiann** [comment]
If you shrink the image, this will cause any files created or modified in the /data/adb/modules directory to fail, which will make many modules not work.
16G devices have not been produced for many years, KernelSU is not born for these devices, let alone sacrifice the experience on new devices for these devices.

**Comment by tiann** [comment]
We are doing an engineering application rather than a theoretical research. If you look at it with a magnifying glass, you can find many problems, but as long as you can solve the problems in 99% of the cases, it is enough for us.
