### ISSUE TITLE
PlayStation Controller, paired, connected, no input.

### ISSUE THREAD

**Issue by fr-jason-fr** [tiann/KernelSU#878]
**Describe the bug**
PlayStation DualShock 4 controllers can be paired, connected but no input is registered.

**To Reproduce**
Steps to reproduce the behaviour:
1. Ensure PS4 is off (not on standby) and the controller is not registered in its list of devices.
2. Turn on Bluetooth on Android device that has a KernelSU enabled kernel.
3. Put controller in pairing mode.
4. Pair the controller as indicated on the Android device that has a KernelSU enabled kernel.
5. Controller show white light on the light bar, no input is registered.
6. The issue repeats itself on another KSU enabled device, but not on 3 pre-KSU devices/kernels.

**Expected behaviour**
Controller input is registered, light bar turns blue, touchpad moves cursor, shows up in gamepad testers, games etc.

**Smartphone (please complete the following information):**
Devices on which the issue appears;
POCO F2 Pro, Various Android 13 ROMs, kernel; [Perf LMI Kernel v290](https://github.com/raystef66/kernel_xiaomi_sm8250/releases/tag/v290_A13)

Redmi Note 4, Various Android 13 ROMs, kernel; https://t.me/mi11screenshots/43187

Devices on which the issue does not appear;
Same as above with stock ROMs, stock kernels, or non-KSU enabled kernels

**Additional context**
The same 3 controllers connect as normal without issue on android devices that are non-KernelSU enabled kernels, Ubuntu 22.04.2 LTS on a Surface Pro 4 i5 tablet/laptop with the linux surface custom kernel, and with the stock kernel as well as Fedora 38 and Windows 11 on a ThinkPad L14 Gen3 Ryzen 5 laptop.

**Comment by tiann** [comment]
Please ensure the issue is caused by KernelSU.

**Comment by fr-jason-fr** [comment]
I have.

**Comment by jason-stream** [comment]
Update; Issue not related to KernelSU

https://github.com/crdroidandroid/issue_tracker/issues/229
