### ISSUE TITLE
Can't install modules 

### ISSUE THREAD

**Issue by msalah-kw** [tiann/KernelSU#879]
Recently I'm not able to install any module, sometimes I can install only one module after restart, then I get the same error 

 - Device: Samsung S22 ultra SM-S908E
 - OS: Android 13 OneUi 5.1

![Screenshot_20230817_104747_KernelSU.jpg](https://github.com/tiann/KernelSU/assets/132661669/a1f55683-66bd-4eb2-a70d-687c7a4dd6b3)

```
 ![Screenshot_20230817_105558_KernelSU.jpg](https://github.com/tiann/KernelSU/assets/132661669/7dd715c0-7f97-4c21-89d9-eb0da5365287)

``
![Screenshot_20230817_105622_KernelSU.jpg](https://github.com/tiann/KernelSU/assets/132661669/167f062d-3d49-4f61-9a6d-adbc860cd50a)

```
![Screenshot_20230817_105655_KernelSU.jpg](https://github.com/tiann/KernelSU/assets/132661669/5a4f70ea-28bc-495f-a1d5-dead280ee7a5)

```

**Comment by tiann** [comment]
update KernelSU to v0.6.6 and send the bugreport.

**Comment by tiann** [comment]
https://github.com/tiann/KernelSU/commit/5f2566e4789b710cb8e92931beeb834a4a9245a4

**Comment by msalah-kw** [comment]
You have helped me in the telegram official group till the problem is fixed 
I appreciate your patience a lot 🌹🙏

**Comment by tiann** [comment]
Thank you for your cooperation, this is also very important to fix the issue.
