### ISSUE TITLE
Got this error when compile

### ISSUE THREAD

**Issue by Fabuxo** [tiann/KernelSU#881]
/drivers/kernelsu/selinux/sepolicy.c:802:43: error: no member named 'total_nr_elements' in 'struct ebitmap'
  802 |         for (j = 0; j < db->type_attr_map_array->total_nr_elements; j++) {
      |                         ~~~~~~~~~~~~~~~~~~~~~~~  ^
../drivers/kernelsu/selinux/sepolicy.c:809:46: error: member reference base type 'struct type_datum *' is not a structure or union
  809 |         for (j = 0; j < db->type_val_to_struct_array->total_nr_elements; j++) {
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^ ~~~~~~~~~~~~~~~~~
../drivers/kernelsu/selinux/sepolicy.c:828:9: error: incompatible pointer types assigning to 'struct flex_array *' from 'struct ebitmap *' [-Werror,-Wincompatible-pointer-types]
  828 |         old_fa = db->type_attr_map_array;
      |                ^ ~~~~~~~~~~~~~~~~~~~~~~~
../drivers/kernelsu/selinux/sepolicy.c:829:26: error: incompatible pointer types assigning to 'struct ebitmap *' from 'struct flex_array *' [-Werror,-Wincompatible-pointer-types]
  829 |         db->type_attr_map_array = new_type_attr_map_array;
      |                                 ^ ~~~~~~~~~~~~~~~~~~~~~~~
../drivers/kernelsu/selinux/sepolicy.c:838:9: error: incompatible pointer types assigning to 'struct flex_array *' from 'struct type_datum **' [-Werror,-Wincompatible-pointer-types]
  838 |         old_fa = db->type_val_to_struct_array;
      |                ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../drivers/kernelsu/selinux/sepolicy.c:839:31: error: incompatible pointer types assigning to 'struct type_datum **' from 'struct flex_array *' [-Werror,-Wincompatible-pointer-types]
  839 |         db->type_val_to_struct_array = new_type_val_to_struct;
      |                                      ^ ~~~~~~~~~~~~~~~~~~~~~~
../drivers/kernelsu/selinux/sepolicy.c:846:9: error: incompatible pointer types assigning to 'struct flex_array *' from 'char **' [-Werror,-Wincompatible-pointer-types]
  846 |         old_fa = db->sym_val_to_name[SYM_TYPES];
      |                ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../drivers/kernelsu/selinux/sepolicy.c:847:33: error: incompatible pointer types assigning to 'char **' from 'struct flex_array *' [-Werror,-Wincompatible-pointer-types]
  847 |         db->sym_val_to_name[SYM_TYPES] = new_val_to_name_types;
      |                                        ^ ~~~~~~~~~~~~~~~~~~~~~
8 errors generated.
make[4]: *** [../scripts/Makefile.build:354: drivers/kernelsu/selinux/sepolicy.o] Erro 1
make[3]: *** [../scripts/Makefile.build:667: drivers/kernelsu/selinux] Erro 2
make[2]: *** [../scripts/Makefile.build:667: drivers/kernelsu] Erro 2
make[2]: *** A aguardar por trabalhos não terminados....

**Comment by Fabuxo** [comment]
Any help please...

**Comment by tiann** [comment]
Search the issues and you will find the solution.
