### ISSUE TITLE
使用kernel后小米13的指纹解锁会有延迟。

### ISSUE THREAD

**Issue by yyzx2016lht** [tiann/KernelSU#883]
设备是小米13，系统是miui14.0.31，刷入android13-5.15.104_2023-06-boot-gz后设备在息屏后重新解锁需要手指在指纹识别处停留超过1秒才会进行识别。经常复现在从口袋拿出手机以及长时间的息屏后

**Comment by tiann** [comment]
换一个其他的版本试一下，有报告说 Google 6 月的有问题。
