### ISSUE TITLE
ColorOS 13.1 182更新后打开支付宝闪退，信号异常

### ISSUE THREAD

**Issue by Lord2333** [tiann/KernelSU#885]
设备是一加Ace2 原神定制版，刷了官版ColorOS，现在的系统是PHK110_13.1.0.182，刷入的内核是android12-5.10.149_2023-01-boot-gz.img。具体表现为：无法打开支付宝，打开五秒就会软重启；SIM卡随机失联，WiFi正常。
之前181系统的时候一切正常，估计是ColorOS的锅。

**Comment by tiann** [comment]
先确认是 KernelSU 的问题。
