### ISSUE TITLE
KernelSU Manager app not working

### ISSUE THREAD

**Issue by BlackMesa123** [tiann/KernelSU#886]
**Describe the bug**
I'm currently trying to include the KernelSU Manager app in my custom ROM via Samsung's Preloaded apps feature. However when I open the manager app, it prints KernelSU is not installed. This doesn't happens when manually installing the app

**To Reproduce**
Flash the ROM, pass the setup wizard and open the app.

**Expected behaviour**
The app should show the currently installed KernelSU version.

**Screenshots**
<img width="30%" src="https://github.com/tiann/KernelSU/assets/13062958/9c15e050-81d5-4ee0-88f6-3ef01ff445a7"> <img width="30%" src="https://github.com/tiann/KernelSU/assets/13062958/02a5d8fb-b11f-4817-b25d-c0e190b659ed">

**Smartphone (please complete the following information):**
 - Device: Galaxy A52s, running S23 Ultra firmware
 - OS: Android 14
 - Version: One UI 6 Beta1

**Additional context**
I did take a look at the code in the driver and I saw it actually expects the package to start with "/data/app/" and end with "/base.apk":
https://github.com/tiann/KernelSU/blob/fb103472c631caf7feae97634dba071ae5ab3ce4/kernel/manager.c#L50-L51

Instead the app is installed at:
```
dm3q:/ $ pm list packages -f | grep kernelsu                                                                                                              
package:/data/app/KernelSU/KernelSU.apk=me.weishu.kernelsu
```

Here's some additional logs from dmesg:
```
dm3q:/ $ dmesg | grep kernelsu
[ 1431.394866] [7:weishu.kernelsu:16351]  KernelSU: become_manager: param pkg: /me.weishu.kernelsu
[ 1431.477858] [7:weishu.kernelsu:16351]  KernelSU: become_manager: param pkg: /me.weishu.kernelsu
[ 1437.861908] [0:            iod:  657]  !@ Read_top(KB): weishu.kernelsu(16351) 4 kworker/u16:5(320) 4 system_server(1327) 4
```

**Comment by tiann** [comment]
#559

**Comment by bemerguy** [comment]
I have the same problem, and it was working before... where's the fix?
