### ISSUE TITLE
[Feature]构建的KernelSU管理器无法正确识别内核

### ISSUE THREAD

**Issue by lingsixuan** [tiann/KernelSU#888]
### Is your feature request related to a problem? Please describe.

我使用这个仓库中的manager源代码构建得到了一个KernelSU管理器的apk文件，将它替换掉系统上已经安装的管理器之后，它显示我没有安装KernelSU，但是实际上我已经安装了它。
这可能是因为KernelSU在内核中限制了能够管理它的APP签名，但是这样使得我难以学习管理器的通信细节。

### Describe the solution you'd like.

我希望我构建的KernelSU管理器能够像预编译的管理器一样完整的工作。

### Describe alternatives you've considered.

为了保证用户不受到假冒的KernelSU欺诈，发布页面中提供的boot镜像应该保留此限制，只允许预编译的管理器获得控制权。但是在通过源代码构建KernelSU Boot时，我希望能够通过一些方法使得构建得到的管理器能获得此Boot的控制权。

**Comment by tiann** [comment]
提问之前先搜 issue.
