### ISSUE TITLE
repo list for non-GKI devices

### ISSUE THREAD

**Issue by Ylarod** [tiann/KernelSU#89]
KernelSU unofficially supports non-GKI devices, maybe we can create a repo list for non-GKI devices maintained by other developers. This makes it easier for user to find proper boot.img to use KernelSU.

**Comment by tiann** [comment]
Is there any repo we can put it to the list now?

**Comment by Ylarod** [comment]
https://github.com/lateautumn233/android_kernel_oneplus_sm8250
for oneplus 8 serials

**Comment by tiann** [comment]
Maybe we should get the kernel author's consent?

**Comment by Ylarod** [comment]
I think so.
@lateautumn233

**Comment by hmtheboy154** [comment]
How about a `Project that use KernelSU` list  instead of just saying `non-GKI devices list` ?

**Comment by Ylarod** [comment]
> How about a `Project that use KernelSU` list instead of just saying `non-GKI devices list` ?

This may include other projects, such as modules.

I think `Unofficially Supported Devices` list would be better.

**Comment by SpectreDev-007** [comment]
https://github.com/XperiaBrickers/kernel_sony_sm8250

Uses KernelSU

I am the kernel author

**Comment by akash07k** [comment]
https://github.com/akash07k/nexus_kernel_xiaomi_sm8250/tree/lychee
It also uses KernelSU (Poco F4: munch)

**Comment by xiaoleGun** [comment]
https://github.com/Diva-Room/Miku_kernel_xiaomi_wayne

branch: TDA

device: wayne

Download from action: https://github.com/xiaoleGun/KernelSU_Action/actions/runs/4031864220

**Comment by YamazakuraH** [comment]
https://github.com/169163-Network/kernel_xiaomi_cepheus

for cepheus
for pixel experience

**Comment by RooGhz720** [comment]
https://github.com/RooGhz720/Aghisna_Sweet_Kernel

kernelSu on branch Aghisna-13
for Redmi Note 10 Pro (Sweet/in)

**Comment by SlackerState** [comment]
https://github.com/SlackerState/android_kernel_xiaomi_sm6150

for Redmi K30 4G (phoenix)

**Comment by tiann** [comment]
If you want to add it to repo list, please make a PR, and modify: 

https://github.com/tiann/KernelSU/blob/main/website/docs/repos.js

I will close and lock this issue now.
