### ISSUE TITLE
The module does not appear in the kernelsu module list

### ISSUE THREAD

**Issue by Yahya2n** [tiann/KernelSU#890]
![Screenshot_20230820-195850_KernelSU](https://github.com/tiann/KernelSU/assets/92499890/b330a0e1-8b22-4bd6-9edd-e277e9ac6f4f)
![Screenshot_20230820-200755_KernelSU](https://github.com/tiann/KernelSU/assets/92499890/dd7e1358-3f05-46ae-aafd-0a6a75ce5eb6)

 #889 The module works in kernelsu, but the module doesn't appear in the module list, please how to fix it?

Previously, I installed a module, because it didn't match my cellphone, I uninstalled it again, and a bootloop occurred, finally I deleted all module data in kernelsu via TWRP, after that a bug occurred

 - Device: [Redmi Note 8]
 - OS: [Evolution X]
 - Version [7.9.7]

[KernelSU_bugreport_2023-08-20_21_49.tar.gz](https://github.com/tiann/KernelSU/files/12388402/KernelSU_bugreport_2023-08-20_21_49.tar.gz)

**Comment by tiann** [comment]
it seems that you disable the logcat, please re-enable it, enter module screen and send the bugreport again.
