### ISSUE TITLE
模块安装后应释放的文件不存在，也无法卸载

### ISSUE THREAD

**Issue by hustler-not-chatty** [tiann/KernelSU#897]
**Describe the bug**
模块在安装并重启之后，释放的文件不存在。

且模块也无法卸载，点击卸载并重启后管理器中仍存在对应条目。

**To Reproduce**
Steps to reproduce the behaviour:
1. 安装 [此模块](https://github.com/AndroidAudioMods/ViPER4Android/releases/tag/v0.5.0) 并重启
2. 重启后模块目录（`/data/adb/modules/Viper4Android-RE`）没有释放出来的文件
3. 进入管理器，选择删除该模块，并重启
4. 重启之后进入管理器，发现条目还在，被画了删除线。

**Expected behaviour**
模块可正常安装 / 卸载

**Screenshots**
![image](https://github.com/tiann/KernelSU/assets/99131470/4583a4af-b8a4-4465-a06d-e42e838aa76e)

**Smartphone (please complete the following information):**
 - Device: OnePlus 6
 - OS: LineageOS 20
 - Version 20

**Additional context**
模块安装日志：[KernelSU_install_log_2023-08-23-18-53-10.log](https://github.com/tiann/KernelSU/files/12421904/KernelSU_install_log_2023-08-23-18-53-10.log)

最后一次重启后的日志：[KernelSU_bugreport_2023-08-24_01_33.tar.gz](https://github.com/tiann/KernelSU/files/12421840/KernelSU_bugreport_2023-08-24_01_33.tar.gz)

内核版本是 4.9，没有开启 KPROBE，根据[教程](https://kernelsu.org/guide/how-to-integrate-for-non-gki.html)手动修改的内核源代码并随 LineageOS 源代码一同编译。

机器的 bootloader 已刷入自己的公钥并锁定。

**Comment by wxt1221** [comment]
感觉不是模块的问题，所有模块都有同样问题，一加6T

**Comment by wxt1221** [comment]
> **Describe the bug** 模块在安装并重启之后，释放的文件不存在。
> 
> 且模块也无法卸载，点击卸载并重启后管理器中仍存在对应条目。
> 
> **To Reproduce** Steps to reproduce the behaviour:
> 
> 1. 安装 [此模块](https://github.com/AndroidAudioMods/ViPER4Android/releases/tag/v0.5.0) 并重启
> 2. 重启后模块目录（`/data/adb/modules/Viper4Android-RE`）没有释放出来的文件
> 3. 进入管理器，选择删除该模块，并重启
> 4. 重启之后进入管理器，发现条目还在，被画了删除线。
> 
> **Expected behaviour** 模块可正常安装 / 卸载
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/99131470/262752968-4583a4af-b8a4-4465-a06d-e42e838aa76e.png)
> 
> **Smartphone (please complete the following information):**
> 
> * Device: OnePlus 6
> * OS: LineageOS 20
> * Version 20
> 
> **Additional context** 模块安装日志：[KernelSU_install_log_2023-08-23-18-53-10.log](https://github.com/tiann/KernelSU/files/12421904/KernelSU_install_log_2023-08-23-18-53-10.log)
> 
> 最后一次重启后的日志：[KernelSU_bugreport_2023-08-24_01_33.tar.gz](https://github.com/tiann/KernelSU/files/12421840/KernelSU_bugreport_2023-08-24_01_33.tar.gz)
> 
> 内核版本是 4.9，没有开启 KPROBE，根据[教程](https://kernelsu.org/guide/how-to-integrate-for-non-gki.html)手动修改的内核源代码并随 LineageOS 源代码一同编译。
> 
> 机器的 bootloader 已刷入自己的公钥并锁定。

已知可能为4.9内核原因，可以根据这个commit来修改内核

> **Describe the bug** 模块在安装并重启之后，释放的文件不存在。
> 
> 且模块也无法卸载，点击卸载并重启后管理器中仍存在对应条目。
> 
> **To Reproduce** Steps to reproduce the behaviour:
> 
> 1. 安装 [此模块](https://github.com/AndroidAudioMods/ViPER4Android/releases/tag/v0.5.0) 并重启
> 2. 重启后模块目录（`/data/adb/modules/Viper4Android-RE`）没有释放出来的文件
> 3. 进入管理器，选择删除该模块，并重启
> 4. 重启之后进入管理器，发现条目还在，被画了删除线。
> 
> **Expected behaviour** 模块可正常安装 / 卸载
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/99131470/262752968-4583a4af-b8a4-4465-a06d-e42e838aa76e.png)
> 
> **Smartphone (please complete the following information):**
> 
> * Device: OnePlus 6
> * OS: LineageOS 20
> * Version 20
> 
> **Additional context** 模块安装日志：[KernelSU_install_log_2023-08-23-18-53-10.log](https://github.com/tiann/KernelSU/files/12421904/KernelSU_install_log_2023-08-23-18-53-10.log)
> 
> 最后一次重启后的日志：[KernelSU_bugreport_2023-08-24_01_33.tar.gz](https://github.com/tiann/KernelSU/files/12421840/KernelSU_bugreport_2023-08-24_01_33.tar.gz)
> 
> 内核版本是 4.9，没有开启 KPROBE，根据[教程](https://kernelsu.org/guide/how-to-integrate-for-non-gki.html)手动修改的内核源代码并随 LineageOS 源代码一同编译。
> 
> 机器的 bootloader 已刷入自己的公钥并锁定。

已知可能是4.9内核原因，可以尝试跟着这个commit修改内核[https://github.com/sticpaper/android_kernel_xiaomi_msm8998-ksu/commit/646d0c8](https://github.com/sticpaper/android_kernel_xiaomi_msm8998-ksu/commit/646d0c8) 

看看这个issue，原因应该一样

[https://github.com/tiann/KernelSU/issues/824](https://github.com/tiann/KernelSU/issues/824)

**Comment by tiann** [comment]
你内核有问题，所有 ksud 相关都没有得到执行；请搜索 issue 寻找解决方案。

**Comment by hustler-not-chatty** [comment]
在应用了[这个 commit](https://github.com/sticpaper/android_kernel_xiaomi_msm8998-ksu/commit/646d0c8) 之后功能就正常了。

感谢提供帮助。 @wxt1221
