### ISSUE TITLE
[Feature] can we add in kernel version 3.18.138

### ISSUE THREAD

**Issue by anuragpindoriya** [tiann/KernelSU#901]
### Is your feature request related to a problem? Please describe.

Can we add kernel-su in kernel version 3.18.138 and no then any way to do this 

### Describe the solution you'd like.

Can add support for it 

### Describe alternatives you've considered.

Add support for 3.18.138 kernel

**Comment by tiann** [comment]
In theory, yes.

**Comment by anuragpindoriya** [comment]
> In theory, yes.

So, how  we do this in practically 😂

**Comment by tiann** [comment]
Read the source code, fix compile error, test.
