### ISSUE TITLE
KernelSU构建失败

### ISSUE THREAD

**Issue by DZ-IO** [tiann/KernelSU#904]
**Describe the bug**
标准内核构建正常，加入KernelSU后构建失败

**To Reproduce**
Steps to reproduce the behaviour:
1. 正常构建内核
2. 内核构建目录下执行`curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -`
3. 重新构建内核
4. See the error

**Expected behaviour**
没有错误，内核构建成功

**Screenshots**
```
root@7798cd414100:~/kbuild# tools/bazel run //common:kernel_aarch64_dist -- --dist_dir=$(pwd)/kout
INFO: Build options --//build/kernel/kleaf:config_fast, --//build/kernel/kleaf:config_local, and --//build/kernel/kleaf:lto have changed, discarding analysis cache.
INFO: Analyzed target //common:kernel_aarch64_dist (0 packages loaded, 85937 targets configured).
INFO: Found 1 target...
ERROR: /root/kbuild/common/BUILD.bazel:47:22: Creating kernel config kernel_aarch64_config failed: (Exit 1): bash failed: error executing command (from target //common:kernel_aarch64_config) /bin/bash -c ... (remaining 1 argument skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
--- common/arch/arm64/configs/gki_defconfig     2023-08-26 15:10:34.113277402 +0000
+++ /root/kbuild/out/bazel/output_user_root/91d2da69fc50ccf8a24cebdd0d91e1f4/sandbox/processwrapper-sandbox/24/execroot/__main__/out__common_kernel_aarch64/android13-5.15/common/defconfig  2023-08-27 00:23:40.754459549 +0000
@@ -586,7 +586,6 @@
 CONFIG_FUSE_FS=y
 CONFIG_VIRTIO_FS=y
 CONFIG_FUSE_BPF=y
-CONFIG_OVERLAY_FS=y
 CONFIG_INCREMENTAL_FS=y
 CONFIG_MSDOS_FS=y
 CONFIG_VFAT_FS=y
ERROR: savedefconfig does not match common/arch/arm64/configs/gki_defconfig
Target //common:kernel_aarch64_dist failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /root/kbuild/common/BUILD.bazel:47:22 Middleman _middlemen/common_Skernel_Uaarch64_Udist-runfiles failed: (Exit 1): bash failed: error executing command (from target //common:kernel_aarch64_config) /bin/bash -c ... (remaining 1 argument skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
INFO: Elapsed time: 7.330s, Critical Path: 3.53s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
root@7798cd414100:~/kbuild# 
```

**Smartphone (please complete the following information):**
 - Device: Xiaomi 13 Ultra
 - OS: MIUI 14 (Android 13)

**Additional context**
移除`common/drivers/Kconfig`中的`source "drivers/kernelsu/Kconfig"`后编译通过

**Comment by tiann** [comment]
https://github.com/tiann/KernelSU/commit/5e893e3d04a3fbe377925d00b1d83c19d875b33a

**Comment by JiuGeFaCai** [comment]
你6.1内核用的哪一条编译命令，我用tools/bazel build --config=fast //common:kernel_aarch64_dist不能开机

**Comment by JanMi-X** [comment]
> 你6.1内核用的哪一条编译命令，我用工具/bazel build --config=fast //common：kernel_aarch64_dist不能开机

大哥你解决了吗 我也是这个问题

**Comment by JiuGeFaCai** [comment]
> > 你6.1内核用的哪一条编译命令，我用工具/bazel build --config=fast //common：kernel_aarch64_dist不能开机
> 
> 大哥你解决了吗 我也是这个问题

解决了已经

**Comment by JanMi-X** [comment]
> > > 你6.1内核用的哪一条编译命令，我用工具/bazel build --config=fast //common：kernel_aarch64_dist不能开机
> > 
> > 
> > 大哥你解决了吗 我也是这个问题
> 
> 解决了已经

咋解决的 能加个联系方式吗我目前被这个困扰

**Comment by JiuGeFaCai** [comment]
> > > > 你6.1内核用的哪一条编译命令，我用工具/bazel build --config=fast //common：kernel_aarch64_dist不能开机
> > > 
> > > 
> > > 大哥你解决了吗 我也是这个问题
> > 
> > 
> > 解决了已经
> 
> 咋解决的 能加个联系方式吗我目前被这个困扰

你发你的qq就行

**Comment by JanMi-X** [comment]
> > > > > 你6.1内核用的哪一条编译命令，我用工具/bazel build --config=fast //common：kernel_aarch64_dist不能开机
> > > > 
> > > > 
> > > > 大哥你解决了吗 我也是这个问题
> > > 
> > > 
> > > 解决了已经
> > 
> > 
> > 咋解决的 能加个联系方式吗我目前被这个困扰
> 
> 你发你的qq就行

745941155

**Comment by jiovf** [comment]
如何解决的,我目前也被这个问题困扰
