### ISSUE TITLE
Manager don't work on stock EMUI 9.1

### ISSUE THREAD

**Issue by Kadalis** [tiann/KernelSU#909]
**Describe the bug**
P20 Lite, stock EMUI
KernelSU Manager don't show any apps, just stuck at load animation. Also, in modules tab it say that overlayfs is not available, but overlayfs turned on in kernel config. On custom GSI it works as should.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open KSU app
2. Go to Superuser tab
3. See infinite loading animation
4. Go to Module tab
5. In Module tab, see "overlayfs is not available, module cannot work!"

**Expected behaviour**
KernelSU should work correctly

**Screenshots**
<img src="https://github.com/tiann/KernelSU/assets/65240890/d4d899af-9fb6-4353-8fdf-2ec7148fb775" data-canonical-src="https://gyazo.com/eb5c5741b6a9a16c692170a41a49c858.png" width="50%" height="50%" alt="Home tab"/>

<img src="https://github.com/tiann/KernelSU/assets/65240890/28d4463a-177b-4323-be77-3588f3943590" data-canonical-src="https://gyazo.com/eb5c5741b6a9a16c692170a41a49c858.png" width="50%" height="50%" alt="Superuser tab"/>

**Smartphone (please complete the following information):**
 - Device: Huawei P20 Lite
 - OS: EMUI 9.1
 - KSU Version 11214
 - Manager version v0.6.7 (11210)

**Additional context**
There is a kmsg grepped to kernelsu only [kmsg-kernelsu.txt](https://github.com/tiann/KernelSU/files/12455717/kmsg-kernelsu.txt)

**Comment by wutaijieing** [comment]
https://github.com/wutaijieing/android_kernel_Glk_kirin710/commits/main

**Comment by Coconutat** [comment]
> **Describe the bug**
> P20 Lite, stock EMUI
> KernelSU Manager don't show any apps, just stuck at load animation. Also, in modules tab it say that overlayfs is not available, but overlayfs turned on in kernel config. On custom GSI it works as should.
> 
> **To Reproduce**
> Steps to reproduce the behaviour:
> 1. Open KSU app
> 2. Go to Superuser tab
> 3. See infinite loading animation
> 4. Go to Module tab
> 5. In Module tab, see "overlayfs is not available, module cannot work!"
> 
> **Expected behaviour**
> KernelSU should work correctly
> 
> **Screenshots**
> <img src="https://github.com/tiann/KernelSU/assets/65240890/d4d899af-9fb6-4353-8fdf-2ec7148fb775" data-canonical-src="https://gyazo.com/eb5c5741b6a9a16c692170a41a49c858.png" width="50%" height="50%" alt="Home tab"/>
> 
> <img src="https://github.com/tiann/KernelSU/assets/65240890/28d4463a-177b-4323-be77-3588f3943590" data-canonical-src="https://gyazo.com/eb5c5741b6a9a16c692170a41a49c858.png" width="50%" height="50%" alt="Superuser tab"/>
> 
> **Smartphone (please complete the following information):**
>  - Device: Huawei P20 Lite
>  - OS: EMUI 9.1
>  - KSU Version 11214
>  - Manager version v0.6.7 (11210)
> 
> **Additional context**
> There is a kmsg grepped to kernelsu only [kmsg-kernelsu.txt](https://github.com/tiann/KernelSU/files/12455717/kmsg-kernelsu.txt)
> 
> 

See this:[Support KernelSU For Huawei EMUI9](https://github.com/Coconutat/HuaweiP10-GSI-And-Modify-Or-Support-KernelSU-Tutorial/wiki/7.KernelSU适配EMUI9或9.1.0系统的内核)

**Comment by Kadalis** [comment]
>See this:[Support KernelSU For Huawei EMUI9](https://github.com/Coconutat/HuaweiP10-GSI-And-Modify-Or-Support-KernelSU-Tutorial/wiki/7.KernelSU%E9%80%82%E9%85%8DEMUI9%E6%88%969.1.0%E7%B3%BB%E7%BB%9F%E7%9A%84%E5%86%85%E6%A0%B8)

Thank you
[Using this commit](https://github.com/Coconutat/android_kernel_huawei_ravel_KernelSU/commit/f67307c967280d9b863058e47bae7611c8bc3db9) (line 166), set SELinux to always permissive. It's resolved an issue, closing.
