### ISSUE TITLE
当前KernelSU版本16过低

### ISSUE THREAD

**Issue by DZ-IO** [tiann/KernelSU#912]
**Describe the bug**
官方命令自编译KSU显示版本过低

**To Reproduce**
1. 按照官方教程编译KernelSU
2. 从编译好的镜像启动
3. 打开KernelSU APP
4. See the error

**Expected behaviour**
kernelSU管理器正常工作

**Screenshots**
![Screenshot_2023-08-29-14-57-11-369_me weishu kernelsu](https://github.com/tiann/KernelSU/assets/54630782/6e17f826-8e96-4506-9c53-0b221699ff5a)

**Smartphone (please complete the following information):**
 - Device: Xiaomi 13 Ultra
 - OS: MIUI 14 (Android 13)

**Additional context**
使用的是官方main分支

**Comment by wxt1221** [comment]
@DZ-IO 麻烦发一下编译时的日志

**Comment by wxt1221** [comment]
主要是这一段：
```
-- KernelSU version: 11214
-- KernelSU Manager signature size: 0x033b
-- KernelSU Manager signature hash: 0xb0b91415
```

**Comment by DZ-IO** [comment]
> @DZ-IO 麻烦发一下编译时的日志，集成ksu时采用的命令行就是有 curl 那段

日志:
```log
/root/kbuild/out/bazel/output_user_root/91d2da69fc50ccf8a24cebdd0d91e1f4/sandbox/processwrapper-sandbox/11/execroot/__main__/common/drivers/kernelsu/Makefile:23: "KSU_GIT_VERSION not defined! It is better to make KernelSU a git submodule!"
-- KernelSU Manager signature size: 0x033b
-- KernelSU Manager signature hash: 0xb0b91415
```
命令行:
```sh
curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main
```

**Comment by wxt1221** [comment]
删除KernelSU文件夹然后重新执行一下命令行

**Comment by wxt1221** [comment]
观察一下是否还有"KSU_GIT_VERSION not defined!之类的报错

**Comment by wxt1221** [comment]
ksu的版本依赖于git的commit数量

**Comment by DZ-IO** [comment]
> 观察一下是否还有"KSU_GIT_VERSION not defined!之类的报错

试过了，还是有报错

**Comment by DZ-IO** [comment]
试了一下，还是有报错

然后顺着这个思路去找了一下Makefile，感觉是这里判断不出来是否在git仓库里导致的（Makefile写的不多，这块只是个人理解，如果有误见谅）

```makefile
# .git is a text file while the module is imported by 'git submodule add'.
ifeq ($(shell test -e $(srctree)/$(src)/../.git; echo $$?),0)
KSU_GIT_VERSION := $(shell cd $(srctree)/$(src); /usr/bin/env PATH="$$PATH":/usr/bin:/usr/local/bin git rev-list --count HEAD)
# ksu_version: major * 10000 + git version + 200 for historical reasons
$(eval KSU_VERSION=$(shell expr 10000 + $(KSU_GIT_VERSION) + 200))
$(info -- KernelSU version: $(KSU_VERSION))
ccflags-y += -DKSU_VERSION=$(KSU_VERSION)
else # If there is no .git file, the default version will be passed.
$(warning "KSU_GIT_VERSION not defined! It is better to make KernelSU a git submodule!")
ccflags-y += -DKSU_VERSION=16
endif
```

**Comment by wxt1221** [comment]
你的KernelSU目录下是否有.git 文件夹
检查一下你的系统的git在哪里，是否在PATH里面

**Comment by wxt1221** [comment]
看得出来调用了git是从系统的PATH里去找的

**Comment by wxt1221** [comment]
跑一下:
```bash
whereis git
cat $PATH
```
看一下

**Comment by DZ-IO** [comment]
> 你的KernelSU目录下是否有.git 文件夹 检查一下你的系统的git在哪里，是否在PATH里面

有.git文件夹，git也在$PATH里
但是它找的那个目录下没有.git

**Comment by wxt1221** [comment]
他在读/drivers/kernelsu的内容，我看了一下这个目录也是个单独的git仓库，你看一下呢

**Comment by wxt1221** [comment]
应该是软连接过去的

**Comment by wxt1221** [comment]
![image](https://github.com/tiann/KernelSU/assets/74451279/069d484f-63be-48df-970b-a0698b7efaea)

**Comment by DZ-IO** [comment]
> 他在读/drivers/kernelsu的内容，我看了一下这个目录也是个单独的git仓库，你看一下呢

那个drivers不是git仓库，所以问题出在这了

**Comment by wxt1221** [comment]
你把/drivers/kernelsu/Makefile改成这样算了，估计是make版本的问题，回头提个PR：
```Makefile
obj-y += ksu.o
obj-y += allowlist.o
kernelsu-objs := apk_sign.o
obj-y += kernelsu.o
obj-y += module_api.o
obj-y += sucompat.o
obj-y += uid_observer.o
obj-y += manager.o
obj-y += core_hook.o
obj-y += ksud.o
obj-y += embed_ksud.o
obj-y += kernel_compat.o

obj-y += selinux/
# .git is a text file while the module is imported by 'git submodule add'.
$(info "$(srctree)")
$(info "$(src)")
ifeq ($(shell test -e $(srctree)/KernelSU/.git; echo $$?),0)
KSU_GIT_VERSION := $(shell cd $(srctree)/$(src); /usr/bin/env PATH="$$PATH":/usr/bin:/usr/local/bin git rev-list --count HEAD)
# ksu_version: major * 10000 + git version + 200 for historical reasons
$(eval KSU_VERSION=$(shell expr 10000 + $(KSU_GIT_VERSION) + 200))
$(info -- KernelSU version: $(KSU_VERSION))
ccflags-y += -DKSU_VERSION=$(KSU_VERSION)
else # If there is no .git file, the default version will be passed.
$(warning "KSU_GIT_VERSION not defined! It is better to make KernelSU a git submodule!")
ccflags-y += -DKSU_VERSION=16
endif

ifndef KSU_EXPECTED_SIZE
KSU_EXPECTED_SIZE := 0x033b
endif

ifndef KSU_EXPECTED_HASH
KSU_EXPECTED_HASH := 0xb0b91415
endif

$(info -- KernelSU Manager signature size: $(KSU_EXPECTED_SIZE))
$(info -- KernelSU Manager signature hash: $(KSU_EXPECTED_HASH))

ccflags-y += -DEXPECTED_SIZE=$(KSU_EXPECTED_SIZE)
ccflags-y += -DEXPECTED_HASH=$(KSU_EXPECTED_HASH)
ccflags-y += -Wno-implicit-function-declaration -Wno-strict-prototypes -Wno-int-conversion -Wno-gcc-compat
ccflags-y += -Wno-declaration-after-statement

```

如果还不行请附上KernelSU那段编译日志，KernelSU Version前面有两行一起复制上来。
并且在`/drivers/kernelsu`目录下执行
```bash
git rev-list --count HEAD
```
把输出复制出来

**Comment by tiann** [comment]
`$(warning "KSU_GIT_VERSION not defined! It is better to make KernelSU a git submodule!")`

需要确保，在 kernel 源码树的 KernelSU 目录中，执行 git 命令可以正常输出 KernelSU 仓库的相关信息，请你自行检查一下。

**Comment by General110** [comment]
gen@gen-virtual-machine:~/android-kernel$ tools/bazel run //common:kernel_aarch64_dist
INFO: Analyzed target //common:kernel_aarch64_dist (1 packages loaded, 79028 targets configured).
INFO: Found 1 target...
INFO: From Building kernel kernel_aarch64:
usr/include/linux/fuse.h:944: found __[us]{8,16,32,64} type without #include <linux/types.h>
/home/gen/android-kernel/out/bazel/output_user_root/afb98f0d0a4c7b3532b63956a6a1dd5a/sandbox/linux-sandbox/31/execroot/__main__/common/drivers/kernelsu/Makefile:23: "KSU_GIT_VERSION not defined! It is better to make KernelSU a git submodule!"
-- KernelSU Manager signature size: 0x033b
-- KernelSU Manager signature hash: 0xb0b91415
INFO: From Building GKI artifacts //common:kernel_aarch64_gki_artifacts:
Creating boot-img.tar.gz for gki-info.txt boot.img boot-gz.img boot-lz4.img
INFO: From Building system_dlkm //common:kernel_aarch64_images_system_dlkm_image:
========================================================
 Creating system_dlkm image
Target //common:kernel_aarch64_dist up-to-date:
  bazel-bin/common/kernel_aarch64_dist
INFO: Elapsed time: 1616.751s, Critical Path: 1601.51s
INFO: 8 processes: 1 internal, 7 linux-sandbox.
INFO: Build completed successfully, 8 total actions
INFO: Build completed successfully, 8 total actions
[dist] INFO: Copying to /home/gen/android-kernel/out/android13-5.15/dist
  
gen@gen-virtual-machine:~/android-kernel$ cd common
gen@gen-virtual-machine:~/android-kernel/common$ git submodule status
 1f42bbac5ef3fbaf2a5497f631c5b2a57421db6d KernelSU (v0.6.8)
gen@gen-virtual-machine:~/android-kernel/common/KernelSU$ git rev-list --count HEAD
1038
gen@gen-virtual-machine:~/android-kernel/common/KernelSU$ make -v
GNU Make 4.3
为 x86_64-pc-linux-gnu 编译
Copyright (C) 1988-2020 Free Software Foundation, Inc.
许可证：GPLv3+：GNU 通用公共许可证第 3 版或更新版本<http://gnu.org/licenses/gpl.html>。
本软件是自由软件：您可以自由修改和重新发布它。
在法律允许的范围内没有其他保证。
gen@gen-virtual-machine:~/android-kernel/common/KernelSU$ git --version
git version 2.34.1


解决不了放弃了......太难了

**Comment by General110** [comment]
**gen@gen-virtual-machine:~/android-kernel$ tools/bazel run //common:kernel_aarch64_dist
INFO: Analyzed target //common:kernel_aarch64_dist (1 packages loaded, 79028 targets configured).
INFO: Found 1 target...
INFO: From Building kernel kernel_aarch64:
usr/include/linux/fuse.h:944: found __[us]{8,16,32,64} type without #include <linux/types.h>
/home/gen/android-kernel/out/bazel/output_user_root/afb98f0d0a4c7b3532b63956a6a1dd5a/sandbox/linux-sandbox/31/execroot/__main__/common/drivers/kernelsu/Makefile:23: "KSU_GIT_VERSION not defined! It is better to make KernelSU a git submodule!"
-- KernelSU Manager signature size: 0x033b
-- KernelSU Manager signature hash: 0xb0b91415
INFO: From Building GKI artifacts //common:kernel_aarch64_gki_artifacts:
Creating boot-img.tar.gz for gki-info.txt boot.img boot-gz.img boot-lz4.img
INFO: From Building system_dlkm //common:kernel_aarch64_images_system_dlkm_image:
========================================================
 Creating system_dlkm image
Target //common:kernel_aarch64_dist up-to-date:
  bazel-bin/common/kernel_aarch64_dist
INFO: Elapsed time: 1616.751s, Critical Path: 1601.51s
INFO: 8 processes: 1 internal, 7 linux-sandbox.
INFO: Build completed successfully, 8 total actions
INFO: Build completed successfully, 8 total actions
[dist] INFO: Copying to /home/gen/android-kernel/out/android13-5.15/dist
  
gen@gen-virtual-machine:~/android-kernel$ cd common
gen@gen-virtual-machine:~/android-kernel/common$ git submodule status
 1f42bbac5ef3fbaf2a5497f631c5b2a57421db6d KernelSU (v0.6.8)
gen@gen-virtual-machine:~/android-kernel/common/KernelSU$ git rev-list --count HEAD
1038
gen@gen-virtual-machine:~/android-kernel/common/KernelSU$ make -v
GNU Make 4.3
为 x86_64-pc-linux-gnu 编译
Copyright (C) 1988-2020 Free Software Foundation, Inc.
许可证：GPLv3+：GNU 通用公共许可证第 3 版或更新版本<http://gnu.org/licenses/gpl.html>。
本软件是自由软件：您可以自由修改和重新发布它。
在法律允许的范围内没有其他保证。
gen@gen-virtual-machine:~/android-kernel/common/KernelSU$ git --version
git version 2.34.1**

**Comment by General110** [comment]
`gen@gen-virtual-machine:~/android-kernel$ tools/bazel run //common:kernel_aarch64_dist
INFO: Analyzed target //common:kernel_aarch64_dist (1 packages loaded, 79028 targets configured).
INFO: Found 1 target...
INFO: From Building kernel kernel_aarch64:
usr/include/linux/fuse.h:944: found __[us]{8,16,32,64} type without #include <linux/types.h>
/home/gen/android-kernel/out/bazel/output_user_root/afb98f0d0a4c7b3532b63956a6a1dd5a/sandbox/linux-sandbox/31/execroot/__main__/common/drivers/kernelsu/Makefile:23: "KSU_GIT_VERSION not defined! It is better to make KernelSU a git submodule!"
-- KernelSU Manager signature size: 0x033b
-- KernelSU Manager signature hash: 0xb0b91415
INFO: From Building GKI artifacts //common:kernel_aarch64_gki_artifacts:
Creating boot-img.tar.gz for gki-info.txt boot.img boot-gz.img boot-lz4.img
INFO: From Building system_dlkm //common:kernel_aarch64_images_system_dlkm_image:
========================================================
 Creating system_dlkm image
Target //common:kernel_aarch64_dist up-to-date:
  bazel-bin/common/kernel_aarch64_dist
INFO: Elapsed time: 1616.751s, Critical Path: 1601.51s
INFO: 8 processes: 1 internal, 7 linux-sandbox.
INFO: Build completed successfully, 8 total actions
INFO: Build completed successfully, 8 total actions
[dist] INFO: Copying to /home/gen/android-kernel/out/android13-5.15/dist
  
gen@gen-virtual-machine:~/android-kernel$ cd common
gen@gen-virtual-machine:~/android-kernel/common$ git submodule status
 1f42bbac5ef3fbaf2a5497f631c5b2a57421db6d KernelSU (v0.6.8)
gen@gen-virtual-machine:~/android-kernel/common/KernelSU$ git rev-list --count HEAD
1038
gen@gen-virtual-machine:~/android-kernel/common/KernelSU$ make -v
GNU Make 4.3
为 x86_64-pc-linux-gnu 编译
Copyright (C) 1988-2020 Free Software Foundation, Inc.
许可证：GPLv3+：GNU 通用公共许可证第 3 版或更新版本<http://gnu.org/licenses/gpl.html>。
本软件是自由软件：您可以自由修改和重新发布它。
在法律允许的范围内没有其他保证。
gen@gen-virtual-machine:~/android-kernel/common/KernelSU$ git --version
git version 2.34.1`

**Comment by General110** [comment]
gen@gen-virtual-machine:~/android-kernel$ tools/bazel run //common:kernel_aarch64_dist
INFO: Analyzed target //common:kernel_aarch64_dist (1 packages loaded, 79028 targets configured).
INFO: Found 1 target...
INFO: From Building kernel kernel_aarch64:
usr/include/linux/fuse.h:944: found __[us]{8,16,32,64} type without #include <linux/types.h>
/home/gen/android-kernel/out/bazel/output_user_root/afb98f0d0a4c7b3532b63956a6a1dd5a/sandbox/linux-sandbox/31/execroot/__main__/common/drivers/kernelsu/Makefile:23: "KSU_GIT_VERSION not defined! It is better to make KernelSU a git submodule!"
-- KernelSU Manager signature size: 0x033b
-- KernelSU Manager signature hash: 0xb0b91415
INFO: From Building GKI artifacts //common:kernel_aarch64_gki_artifacts:
Creating boot-img.tar.gz for gki-info.txt boot.img boot-gz.img boot-lz4.img
INFO: From Building system_dlkm //common:kernel_aarch64_images_system_dlkm_image:

 Creating system_dlkm image
Target //common:kernel_aarch64_dist up-to-date:
  bazel-bin/common/kernel_aarch64_dist
INFO: Elapsed time: 1616.751s, Critical Path: 1601.51s
INFO: 8 processes: 1 internal, 7 linux-sandbox.
INFO: Build completed successfully, 8 total actions
INFO: Build completed successfully, 8 total actions
[dist] INFO: Copying to /home/gen/android-kernel/out/android13-5.15/dist
  
gen@gen-virtual-machine:~/android-kernel$ cd common
gen@gen-virtual-machine:~/android-kernel/common$ git submodule status
 1f42bbac5ef3fbaf2a5497f631c5b2a57421db6d KernelSU (v0.6.8)
gen@gen-virtual-machine:~/android-kernel/common/KernelSU$ git rev-list --count HEAD
1038
gen@gen-virtual-machine:~/android-kernel/common/KernelSU$ make -v
GNU Make 4.3
为 x86_64-pc-linux-gnu 编译
Copyright (C) 1988-2020 Free Software Foundation, Inc.
许可证：GPLv3+：GNU 通用公共许可证第 3 版或更新版本<http://gnu.org/licenses/gpl.html>。
本软件是自由软件：您可以自由修改和重新发布它。
在法律允许的范围内没有其他保证。
gen@gen-virtual-machine:~/android-kernel/common/KernelSU$ git --version
git version 2.34.1

搞不定....放弃了

**Comment by General110** [comment]
用bazel 构建就KSU_GIT_VERSION not defined! It is better to make KernelSU a git submodule!。用build/build.sh
