### ISSUE TITLE
kernelsu exam 

### ISSUE THREAD

**Issue by Hamood111** [tiann/KernelSU#913]
### Is your feature request related to a problem? Please describe.

I just wanna enjoy to  kernelsu group what's up with the exam where are we high school I'm not speaking English very well also I'm not smart so would u please remove this exam I let people enjoy to the group 

### Describe the solution you'd like.

remove the exam

### Describe alternatives you've considered.

remove the exam 

### Additional context

remove the exam

**Comment by Dreamail** [comment]
If you have finished high school, you won't ask stupid question like this. 🤣

**Comment by Hamood111** [comment]
> If you have finished high school, you won't ask stupid question like this. 🤣

I did not finish the high school is that a crime but I'm leaving and working and everything is fine just please let me enjoy the group I'm kernelsu user

**Comment by Hamood111** [comment]
> Just read the introduction and you can finish it easily

I'm using Google translate my English is not good anyway sorry for the inconvenience, I will be satisfied with the kernelsu channel, thanks
