### ISSUE TITLE
[Feature]能否给更新按钮加个弹窗?

### ISSUE THREAD

**Issue by setcurl** [tiann/KernelSU#916]
### Is your feature request related to a problem? Please describe.

就像magisk那样，点击更新能看到changelog.md链接的更新日志，弹窗有两个按钮，一个更新，一个取消，先KernelSU点击更新直接下载刷入看不到日志.....

### Describe the solution you'd like.

这似乎不用写了...

### Describe alternatives you've considered.

也是一样...

**Comment by tiann** [comment]
我认为这是一个好的建议，但我没有时间去完成它；任何人如果有兴趣，欢迎 PR。

**Comment by getcurl** [comment]
> 我认为这是一个好的建议，但我没有时间去完成它；任何人如果有兴趣，欢迎 PR。

我没那能力，只能看着了🙃

**Comment by tiann** [comment]
https://github.com/tiann/KernelSU/commit/81bbb31098b82bbf3f8ef7d1eaea7d01ea544a21

**Comment by setcurl** [comment]
> 我认为这是一个好的建议，但我没有时间去完成它；任何人如果有兴趣，欢迎 PR。

还需要修改下，因为对话框没有高度限制，md过长就会....
![Screenshot_2023-10-01-05-32-14-128_me weishu kernelsu](https://github.com/tiann/KernelSU/assets/78637344/c236555f-b15c-4f75-891f-ba95f3e6c4ae)
