### ISSUE TITLE
手动修改源码后还是不支持

### ISSUE THREAD

**Issue by inuyasha-660** [tiann/KernelSU#922]
用kprobe集成后无法开机，注释掉ksu_enable_sucompat()和ksu_enable_ksud()这两行后能正常开机。于是我尝试修改源码，并关闭kprobe，但刷入后仍然显示不支持，我看到源码和文档有一些差异
文档是`EXPORT_SYMBOL(kernel_read);` 下面是我的
![截图 2023-09-01 09-31-08](https://github.com/tiann/KernelSU/assets/103230572/21aa167f-001f-40db-a40f-9b83ee60cb29)

这是源码：https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S3RXC32.33-8-7

**Comment by tiann** [comment]
请你确认 `CONFIG_KPROBES` 已经关闭。看你现象似乎还是 KPROBE 导致的。

**Comment by inuyasha-660** [comment]
您好，我已经设置了`# CONFIG_KPROBES is not set`是否需要设置其他选项

**Comment by tiann** [comment]
请提供 bugreport。

**Comment by inuyasha-660** [comment]
请问该怎么抓取日志

**Comment by Coconutat** [comment]
> 请问该怎么抓取日志

KernelSU管理器 ->  设置 -> 发送日志

**Comment by inuyasha-660** [comment]
好的，感谢

**Comment by inuyasha-660** [comment]
**Describe the bug**
手动集成仍然不工作

**To Reproduce**
1. 添加KernelSU到设备数
2. 手动修改源码
3. 设置`# CONFIG_KPROBES is not set`
4. 编译后刷入显示不支持

**Expected behaviour**
刷入后正常工作

**Screenshots**
![ba75315d035e00cc215d6123d4e7078a](https://github.com/tiann/KernelSU/assets/103230572/2d859403-38f9-4c03-9d60-7c7e93092bbd)


**Smartphone (please complete the following information):**
 - Device: [mote edge s30 ]
 - OS: [myui]
 - Version [S3RXC32.33-8-7]

**Additional context**
[KernelSU_bugreport_2023-09-01_17_07 (1).gz](https://github.com/tiann/KernelSU/files/12496465/KernelSU_bugreport_2023-09-01_17_07.1.gz)

源码：https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S3RXC32.33-8-7

**Comment by inuyasha-660** [comment]
> 请提供 bugreport。

已经上传了，能帮忙看下吗

**Comment by tiann** [comment]
看起来 KernelSU 的代码压根没有参与编译；应该是你手动集成的时候哪里搞错了。请你提供一下你改过的代码，否则我将直接关闭此 issue。

**Comment by inuyasha-660** [comment]
好的，稍等

**Comment by inuyasha-660** [comment]
> 看起来 KernelSU 的代码压根没有参与编译；应该是你手动集成的时候哪里搞错了。请你提供一下你改过的代码，否则我将直接关闭此 issue。

https://github.com/inuyasha-660/moto-kernelsu 包括编译脚本都在这里了

**Comment by tiann** [comment]
请提供一下内核编译过程的日志输出

**Comment by inuyasha-660** [comment]
好，稍等

**Comment by inuyasha-660** [comment]
使用 `2>&1|tee make.log`打印日志，但是make文件是空的，没有日志怎么办

**Comment by inuyasha-660** [comment]
> 请提供一下内核编译过程的日志输出

请问使用 2>&1|tee make.log打印日志，但是make文件是空的，没有日志怎么办

**Comment by inuyasha-660** [comment]
> 请提供一下内核编译过程的日志输出

您看这个行不行
[make.log](https://github.com/tiann/KernelSU/files/12497595/make.log)

**Comment by tiann** [comment]
看着好像没有毛病，你编译的 Image 传上来看看

**Comment by tiann** [comment]
你的管理器是自己编译的还是官方的？

**Comment by inuyasha-660** [comment]
> 你的管理器是自己编译的还是官方的？

帮别人编的，应该是从酷安下的

**Comment by tiann** [comment]
我是说你用的管理器 apk 是官方的还是自行编译的？

**Comment by tiann** [comment]
给个确定的答复，所有非官方管理器都会提升不支持，除非特别修改源码。

**Comment by inuyasha-660** [comment]
> 给个确定的答复，所有非官方管理器都会提升不支持，除非特别修改源码。

官方的

**Comment by inuyasha-660** [comment]
> 因为管理器不工作，因此基本抓不到有效信息；需要你提供一下打开管理器后的 logcat 日志以及 dmesg 日志；logcat 日志要用电脑抓；dmesg 日志可以尝试执行 `adb bugreport`

好的，因为是帮别人编的，所以可能不能及时回复

**Comment by tiann** [comment]
closed since no feedback
