### ISSUE TITLE
[FR] Better navigation bar

### ISSUE THREAD

**Issue by asuka-mio** [tiann/KernelSU#93]
Now
![Screenshot_20230121-142245~2](https://user-images.githubusercontent.com/43900799/213846706-5a82fed1-68df-43cd-8651-e8ee283e3a4f.png)

Libchecker version
![Screenshot_20230121-142230~2](https://user-images.githubusercontent.com/43900799/213846760-8ad7d102-8ea1-492e-93c6-099fc292146f.png)

**Comment by tiann** [comment]
What is the difference?

**Comment by tiann** [comment]
we have no UI designer, if you think it should be improved, please make a PR.
