### ISSUE TITLE
Minor bug with the text when flashing a module

### ISSUE THREAD

**Issue by kilam9900** [tiann/KernelSU#930]
The "KernelSU"? Text is bugged.

Steps to reproduce the bug:
1. Flash a module
2. Watch

**Expected behaviour**
Clean text I think

**Screenshots**
![Screenshot_20230903_221753_KernelSU](https://github.com/tiann/KernelSU/assets/97908231/ec6d69b6-9ca0-482f-95ff-d91de26831c5)

**Smartphone :**
 - Device: [SM-A325F]
 - OS: [One UI 5.1 Android 13]
 - Version [v0.6.7]

**Additional context**
It also do it in MRepo app

**Comment by osm0sis** [comment]
Looks like an issue with it not preserving leading whitespace?

**Comment by tiann** [comment]
I think it is a font issue, it is normal on my devices.

**Comment by osm0sis** [comment]
Interesting, doesn't look right on my OP7T on Lineage.

**Comment by EricZhang1092** [comment]
mono fonts change? try copy and paste on other apps?
art bug LOL

**Comment by weiwei-cool** [comment]
What？You mean those "*" ?
Isn't that normal?
![Screenshot_2023-09-15-19-19-33-24_baaa51257c82a8b3f281ce09e6f2493f](https://github.com/tiann/KernelSU/assets/79672724/fda1de13-8a1c-4381-9930-b45c0348548e)

**Comment by osm0sis** [comment]
... No, the KernelSU ASCII art logo ...

**Comment by weiwei-cool** [comment]
Could it be because a third party's AOSP customized the font?

**Comment by weiwei-cool** [comment]
i use the original font, but i reproduce the bug :(

**Comment by osm0sis** [comment]
Pretty sure Lineage is the standard AOSP (Google) fonts. That said, the KernelSU app should be able to specify the font for its own output.

I still think it looks kinda like the leading whitespace is being ignored... Kernel Flasher and FKM can display ASCII logos for AK3 flashes on my devices, so I think the KernelSU app would be able to ensure the built in logo works too. 🤷‍♂️
