### ISSUE TITLE
Hide Kernel Su Feature need [Feature]

### ISSUE THREAD

**Issue by sali9043** [tiann/KernelSU#933]
### Is your feature request related to a problem? Please describe.

Now days many app can detect kernel SU manager apk like Winzo,Paytm, phone pe,Banking Apps,other etc .

### Describe the solution you'd like.

No major issue because either hide my app list app or uninstall kernel su manager apk work but still inbuilt features like hide magisk in Kernel Su Manager will great feature.

### Describe alternatives you've considered.

So I think Uninstall and installing again Is wasting time.

**Comment by tiann** [comment]
Uninstalling is the most perfect way to hide manager.

**Comment by sali9043** [comment]
But then when needed need to install it again

**Comment by sali9043** [comment]
If I can even the package name does kernel SU manager still Work.

**Comment by tiann** [comment]
I uninstalled the manager two months ago, after i set it up, i never install it again. If you want this feature, please add it yourself, I don't need it.

**Comment by foxjaw** [comment]
So, all modules & superuser profile configs still continue to exist after app uninstallation right ?
