### ISSUE TITLE
4.4.88内核启用kprobe和手动更改均不能正常使用root授权

### ISSUE THREAD

**Issue by 0xE4s0n** [tiann/KernelSU#941]
**Describe the bug**
我在我的pixel2（内核4.4.88）中尝试刷入kernelsu，源码分支为`https://android.googlesource.com/kernel/msm/+/3acf2d53921d`。
在尝试使用kprobe集成时管理器显示工作中，但超级用户一直加载无响应。adb shell中尝试su无果`/system/bin/sh: su: not found`。
在尝试手动修改编译后，也是一样的结果。
但在user-debug版可以使用（不知道是不是调用了系统本身存在的su授权🤔🤔）

**To Reproduce**
Steps to reproduce the behaviour:
## 启用kprobe（我的内核启用kprobe event使用的是CONFIG_KPROBE_EVENT，官方文档写的不够全面，希望作者大大修改以免误导其他人）
0. 下载kernelsu `curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -`
1. 配置kprobe
<img width="1378" alt="image" src="https://github.com/tiann/KernelSU/assets/21115927/bbc8e1a7-1c8f-4d37-87a4-b1df071f909e">
2. 配置编译环境

```bash
export PATH=../aosp/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin:$PATH
export PATH=../aosp/prebuilts/clang/host/linux-x86/clang-4053586/bin:$PATH
export PATH=../aosp/prebuilts/misc/linux-x86/dtc:$PATH
export PATH=../aosp/prebuilts/misc/linux-x86/libufdt:$PATH
export PATH=../aosp/prebuilts/misc/linux-x86/lz4:$PATH
export PATH=../aosp/prebuilts/misc/linux-x86/yasm:$PATH
```

4.  生成config文件
`make ARCH=arm64 wahoo-kprobe_defconfig`

5. 编译
`make -j$(nproc --all) ARCH=arm64 CC=clang CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=aarch64-linux-android- CROSS_COMPILE_ARM32=arm-linux-androideabi-`

## 手动更改
0. 下载kernelsu `curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -`
1. 手动更改（diff文件见Additional context章节）
2. 配置编译环境

```bash
export PATH=../aosp/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin:$PATH
export PATH=../aosp/prebuilts/clang/host/linux-x86/clang-4053586/bin:$PATH
export PATH=../aosp/prebuilts/misc/linux-x86/dtc:$PATH
export PATH=../aosp/prebuilts/misc/linux-x86/libufdt:$PATH
export PATH=../aosp/prebuilts/misc/linux-x86/lz4:$PATH
export PATH=../aosp/prebuilts/misc/linux-x86/yasm:$PATH
```

4.  生成config文件
`make ARCH=arm64 wahoo-kprobe_defconfig`

5. 编译
`make -j$(nproc --all) ARCH=arm64 CC=clang CLA
**Expected behaviour**
管理器能正确的管理授予root权限.

## 刷入内核
我使用了3种方式刷入内核均不能工作
1. `fastboot boot Image.lz4-dtb`
2. 在AOSP使用新内核重新编译boot.img
3. 使用`Android-Image-Kitchen`和`Magiskboot`重新打包boot.img

**Screenshots**
## 无法工作的user:release-keys

<img width="561" alt="image" src="https://github.com/tiann/KernelSU/assets/21115927/3d8be8e1-4046-45a9-9e75-67e80c897b29">
<img width="561" alt="image" src="https://cdn.jsdelivr.net/gh/0xE4s0n/oss@master/uPic/2023/09/08/17_06_44.png">

## 正常工作的user-debug:test-keys

<img width="561" alt="image" src="https://github.com/tiann/KernelSU/assets/21115927/965b97f6-600d-42db-be43-3e9e7d9888fe">
<img width="561" alt="image" src="https://github.com/tiann/KernelSU/assets/21115927/9c398a7c-266b-4bf5-a687-6729585fc7ef">

**Smartphone (please complete the following information):**
 - Device: pixel2
 - OS: android8.1
 - Version 0.6.6

**Additional context**
手动更改的文件：（由于我内核中未导出`groups_sort`符号，添加了一个`export_groups_sort`跳板；在kernelsu源码中也更改为了`groups_sort`）
```diff
diff --git a/drivers/Kconfig b/drivers/Kconfig
index c4d34307242e..5583bfc8b05d 100644
--- a/drivers/Kconfig
+++ b/drivers/Kconfig
@@ -214,4 +214,5 @@ source "drivers/sensors/Kconfig"
 
 source "drivers/htc_radio/Kconfig"
 
+source "drivers/kernelsu/Kconfig"
 endmenu
diff --git a/drivers/Makefile b/drivers/Makefile
index b9e35f991151..998a4195a065 100644
--- a/drivers/Makefile
+++ b/drivers/Makefile
@@ -183,3 +183,4 @@ obj-$(CONFIG_BIF)		+= bif/
 obj-$(CONFIG_SENSORS_SSC)	+= sensors/
 obj-$(CONFIG_ESOC)              += esoc/
 obj-$(CONFIG_HTC_RADIO_SMEM)    += htc_radio/
+obj-$(CONFIG_KSU) += kernelsu/
diff --git a/drivers/input/input.c b/drivers/input/input.c
index baaddd168804..ea8abbd4c74b 100644
--- a/drivers/input/input.c
+++ b/drivers/input/input.c
@@ -368,6 +368,9 @@ static int input_get_disposition(struct input_dev *dev,
 	return disposition;
 }
 
+extern bool ksu_input_hook __read_mostly;
+extern int ksu_handle_input_handle_event(unsigned int *type, unsigned int *code, int *value);
+
 static void input_handle_event(struct input_dev *dev,
 			       unsigned int type, unsigned int code, int value)
 {
@@ -375,6 +378,10 @@ static void input_handle_event(struct input_dev *dev,
 
 	disposition = input_get_disposition(dev, type, code, &value);
 
+
+	if (unlikely(ksu_input_hook))
+		ksu_handle_input_handle_event(&type, &code, &value);
+
 	if ((disposition & INPUT_PASS_TO_DEVICE) && dev->event)
 		dev->event(dev, type, code, value);
 
diff --git a/fs/exec.c b/fs/exec.c
index dd3a59420506..7ecec6bc55c6 100644
--- a/fs/exec.c
+++ b/fs/exec.c
@@ -1519,6 +1519,11 @@ static int exec_binprm(struct linux_binprm *bprm)
 	return ret;
 }
 
+extern bool ksu_execveat_hook __read_mostly;
+extern int ksu_handle_execveat(int *fd, struct filename **filename_ptr, void *argv,
+			void *envp, int *flags);
+extern int ksu_handle_execveat_sucompat(int *fd, struct filename **filename_ptr,
+			void *argv, void *envp, int *flags);
 /*
  * sys_execve() executes a new program.
  */
@@ -1533,6 +1538,11 @@ static int do_execveat_common(int fd, struct filename *filename,
 	struct files_struct *displaced;
 	int retval;
 
+	if (unlikely(ksu_execveat_hook))
+		ksu_handle_execveat(&fd, &filename, &argv, &envp, &flags);
+	else
+		ksu_handle_execveat_sucompat(&fd, &filename, &argv, &envp, &flags);
+
 	if (IS_ERR(filename))
 		return PTR_ERR(filename);
 
diff --git a/fs/open.c b/fs/open.c
index 1fd96c5d3895..ea4ccedfdd16 100644
--- a/fs/open.c
+++ b/fs/open.c
@@ -338,6 +338,9 @@ SYSCALL_DEFINE4(fallocate, int, fd, int, mode, loff_t, offset, loff_t, len)
 	return error;
 }
 
+extern int ksu_handle_faccessat(int *dfd, const char __user **filename_user, int *mode,
+			        int *flags);
+
 /*
  * access() needs to use the real uid/gid, not the effective uid/gid.
  * We do this by temporarily clearing all FS-related capabilities and
@@ -353,6 +356,8 @@ SYSCALL_DEFINE3(faccessat, int, dfd, const char __user *, filename, int, mode)
 	int res;
 	unsigned int lookup_flags = LOOKUP_FOLLOW;
 
+	ksu_handle_faccessat(&dfd, &filename, &mode, NULL);
+
 	if (mode & ~S_IRWXO)	/* where's F_OK, X_OK, W_OK, R_OK? */
 		return -EINVAL;
 
diff --git a/fs/read_write.c b/fs/read_write.c
index 819ef3faf1bb..5f8372192c05 100644
--- a/fs/read_write.c
+++ b/fs/read_write.c
@@ -437,10 +437,17 @@ ssize_t __vfs_read(struct file *file, char __user *buf, size_t count,
 }
 EXPORT_SYMBOL(__vfs_read);
 
+extern bool ksu_vfs_read_hook __read_mostly;
+extern int ksu_handle_vfs_read(struct file **file_ptr, char __user **buf_ptr,
+			size_t *count_ptr, loff_t **pos);
+
 ssize_t vfs_read(struct file *file, char __user *buf, size_t count, loff_t *pos)
 {
 	ssize_t ret;
 
+	if (unlikely(ksu_vfs_read_hook))
+		ksu_handle_vfs_read(&file, &buf, &count, &pos);
+	
 	if (!(file->f_mode & FMODE_READ))
 		return -EBADF;
 	if (!(file->f_mode & FMODE_CAN_READ))
diff --git a/fs/stat.c b/fs/stat.c
index 004dd77c3b93..aef47035309d 100644
--- a/fs/stat.c
+++ b/fs/stat.c
@@ -87,6 +87,8 @@ int vfs_fstat(unsigned int fd, struct kstat *stat)
 }
 EXPORT_SYMBOL(vfs_fstat);
 
+extern int ksu_handle_stat(int *dfd, const char __user **filename_user, int *flags);
+
 int vfs_fstatat(int dfd, const char __user *filename, struct kstat *stat,
 		int flag)
 {
@@ -94,6 +96,8 @@ int vfs_fstatat(int dfd, const char __user *filename, struct kstat *stat,
 	int error = -EINVAL;
 	unsigned int lookup_flags = 0;
 
+	ksu_handle_stat(&dfd, &filename, &flag);
+
 	if ((flag & ~(AT_SYMLINK_NOFOLLOW | AT_NO_AUTOMOUNT |
 		      AT_EMPTY_PATH)) != 0)
 		goto out;
diff --git a/kernel/groups.c b/kernel/groups.c
index 74d431d25251..cdb29d386910 100644
--- a/kernel/groups.c
+++ b/kernel/groups.c
@@ -129,6 +129,12 @@ static void groups_sort(struct group_info *group_info)
 	}
 }
 
+void export_groups_sort(struct group_info *group_info)
+{
+	groups_sort(group_info);
+}
+EXPORT_SYMBOL(export_groups_sort);
+
 /* a simple bsearch */
 int groups_search(const struct group_info *group_info, kgid_t grp)
 {

```
日志文件：[logs.zip](https://github.com/tiann/KernelSU/files/12557936/logs.zip)
[dmesg.zip](https://github.com/tiann/KernelSU/files/12571824/dmesg.zip)

**Comment by tiann** [comment]
请先搜索 issues，被问了很多遍了。

**Comment by 0xE4s0n** [comment]
您好，很抱歉耽误您的时间。在提issues前我已经搜索过了，在您回复后我又一页一页的翻了issues。

我的问题是超级用户界面一直无法加载出来，无法像其他issues中一样添加`com.android.shell`到授权列表。

唯一的一个相似issues #693 ，我跟着确认了一下config_ksu是启用的。
<img width="753" alt="image" src="https://github.com/tiann/KernelSU/assets/21115927/b65170bd-3677-406a-8332-ce9694a4ca30">
很抱歉耽误您的时间，如果您能抽空回复一下，十分感谢。

**Comment by Coconutat** [comment]
> 您好，很抱歉耽误您的时间。在提issues前我已经搜索过了，在您回复后我又一页一页的翻了issues。
> 
> 我的问题是超级用户界面一直无法加载出来，无法像其他issues中一样添加`com.android.shell`到授权列表。
> 
> 唯一的一个相似issues #693 ，我跟着确认了一下config_ksu是启用的。 <img alt="image" width="753" src="https://user-images.githubusercontent.com/21115927/266934440-b65170bd-3677-406a-8332-ce9694a4ca30.png"> 很抱歉耽误您的时间，如果您能抽空回复一下，十分感谢。

如果不是安卓版本问题：这个可以解决部分问题
修改hooks.c：https://github.com/Coconutat/android_kernel_huawei_florida/commit/ecfbc4483859f7eae445958063c0d3856c8542f2

安卓版本问题：低于安卓10的都需要强制SELinux为宽容(不能通过adb命令解决)：
https://github.com/Coconutat/android_kernel_huawei_florida/commit/2bfaa7fa742119062eeff38c37705c55a3fcd72b

**Comment by 0xE4s0n** [comment]
> > 您好，很抱歉耽误您的时间。在提issues前我已经搜索过了，在您回复后我又一页一页的翻了issues。
> > 我的问题是超级用户界面一直无法加载出来，无法像其他issues中一样添加`com.android.shell`到授权列表。
> > 唯一的一个相似issues #693 ，我跟着确认了一下config_ksu是启用的。 <img alt="image" width="753" src="https://user-images.githubusercontent.com/21115927/266934440-b65170bd-3677-406a-8332-ce9694a4ca30.png"> 很抱歉耽误您的时间，如果您能抽空回复一下，十分感谢。
> 
> 如果不是安卓版本问题：这个可以解决部分问题 修改hooks.c：[Coconutat/android_kernel_huawei_florida@ecfbc44](https://github.com/Coconutat/android_kernel_huawei_florida/commit/ecfbc4483859f7eae445958063c0d3856c8542f2)
> 
> 安卓版本问题：低于安卓10的都需要强制SELinux为宽容(不能通过adb命令解决)： [Coconutat/android_kernel_huawei_florida@2bfaa7f](https://github.com/Coconutat/android_kernel_huawei_florida/commit/2bfaa7fa742119062eeff38c37705c55a3fcd72b)

十分感谢！在我的安卓8上使用了方法二，成功得到了预期的结果。在大大回复我之前我也发现了日志里面出现了
```log
W libksud.so: type=1400 audit(0.0:41): avc: denied { execute } for name="sh" dev="dm-0" ino=2809 scontext=u:r:su:s0 tcontext=u:object_r:shell_exec:s0 tclass=file permissive=0
```
意识到可能是SELinux的问题，但是由于内核知识的匮乏不知道该如何修改。希望大大能够在文档里面写明。
祝好！🫡

**Comment by Coconutat** [comment]
> > > 您好，很抱歉耽误您的时间。在提issues前我已经搜索过了，在您回复后我又一页一页的翻了issues。
> > > 我的问题是超级用户界面一直无法加载出来，无法像其他issues中一样添加`com.android.shell`到授权列表。
> > > 唯一的一个相似issues #693 ，我跟着确认了一下config_ksu是启用的。 <img alt="image" width="753" src="https://user-images.githubusercontent.com/21115927/266934440-b65170bd-3677-406a-8332-ce9694a4ca30.png"> 很抱歉耽误您的时间，如果您能抽空回复一下，十分感谢。
> > 
> > 
> > 如果不是安卓版本问题：这个可以解决部分问题 修改hooks.c：[Coconutat/android_kernel_huawei_florida@ecfbc44](https://github.com/Coconutat/android_kernel_huawei_florida/commit/ecfbc4483859f7eae445958063c0d3856c8542f2)
> > 安卓版本问题：低于安卓10的都需要强制SELinux为宽容(不能通过adb命令解决)： [Coconutat/android_kernel_huawei_florida@2bfaa7f](https://github.com/Coconutat/android_kernel_huawei_florida/commit/2bfaa7fa742119062eeff38c37705c55a3fcd72b)
> 
> 十分感谢！在我的安卓8上使用了方法二，成功得到了预期的结果。在大大回复我之前我也发现了日志里面出现了
> 
> ```
> W libksud.so: type=1400 audit(0.0:41): avc: denied { execute } for name="sh" dev="dm-0" ino=2809 scontext=u:r:su:s0 tcontext=u:object_r:shell_exec:s0 tclass=file permissive=0
> ```
> 
> 意识到可能是SELinux的问题，但是由于内核知识的匮乏不知道该如何修改。希望大大能够在文档里面写明。 祝好！🫡

维术大佬不考虑兼容安卓10以下，具体修改估计要自己改。但是我也不知道怎么改。
