### ISSUE TITLE
安装完成并开启超级用户后依旧提示找不到su

### ISSUE THREAD

**Issue by notcbw** [tiann/KernelSU#942]
**Describe the bug**

4.14内核。打了security/selinux/hooks.c和强制permissive的补丁后，使用kprobe安装kernelsu。app处显示工作中
在com.android.shell处开启超级用户后，adb依旧提示找不到su。使用终端模拟器app也同样。
（试了几个非zygisk的magisk模块，也会在启动时卡死，不知有没有关系。）

**To Reproduce**
Steps to reproduce the behaviour:

1. 打开KernelSU App, 在超级用户中选择com.android.shell启用超级用户
2. 连接设备到PC, 进入adb shell
3. 执行`su -`

**Expected behaviour**

adb进入root shell

**Screenshots**

![Screenshot_20230910-231713](https://github.com/tiann/KernelSU/assets/59708428/54308acf-2b99-4f64-afc4-3b837737838b)
![Screenshot_20230910-231625](https://github.com/tiann/KernelSU/assets/59708428/b5b88657-9ad1-4b16-b05c-207d19e92d11)
![Screenshot_20230910-231605](https://github.com/tiann/KernelSU/assets/59708428/3a7f5d99-8c5b-4179-87ae-ef7aac8d40c9)

**Smartphone (please complete the following information):**
 - Device: Sony Walkman NW-ZX507
 - OS: Android 9.0.0, Kernel 4.14.78
 - Version v0.6.7(11210)

**Additional context**

[KernelSU_bugreport_2023-09-10_23_19.tar.gz](https://github.com/tiann/KernelSU/files/12571918/KernelSU_bugreport_2023-09-10_23_19.tar.gz)

**Comment by tiann** [comment]
请先阅读官方文档。

**Comment by notcbw** [comment]
@tiann 不好意思再打扰你一下，我在dmesg里看到这里execve_kp返回-2，请问这正常吗？

<img width="424" alt="Screenshot 2023-09-11 at 02 01 47" src="https://github.com/tiann/KernelSU/assets/59708428/86b6cf1a-2b3c-4b64-bd3d-deabb0579aca">
