### ISSUE TITLE
Incorrect syscall results on filenames that begins with /system/bin/su

### ISSUE THREAD

**Issue by kxxt** [tiann/KernelSU#957]
**Describe the bug**

Incorrect results are given to userland when kernelsu handles filenames that begins with `/system/bin/su`

**To Reproduce**
Steps to reproduce the behaviour:
1. Run `adb shell` (Super user is granted to shell)
2. In adb shell, run `suadfadg`. 
3. I got `/system/bin/sh: /system/bin/suadfadg: No such file or directory` 

**Expected behaviour**

```
/system/bin/sh: fdsfsf: inaccessible or not found
```

**Smartphone (please complete the following information):**
Not relevant. All devices are affected.

**Additional context**

This is because kernelsu rewrites `su->sh` because the prefix of `/system/bin/suadfadg` matches `/system/bin/su`.

I will open a PR to fix it.

**Comment by osm0sis** [comment]
I think what you saw was expected actually...

Any command that doesn't exist shows sh, unrooted, and even with Magisk:
```
:/ $ su
:/ # exit
:/ $ balhd
/system/bin/sh: balhd: inaccessible or not found
127|:/ $ su
:/ # balhgl
/system/bin/sh: balhgl: inaccessible or not found
127|:/ #
```

**Comment by osm0sis** [comment]
Oh wait, I see the issue in your error message now...

Your expected should actually be the following though:
```
/system/bin/sh: sufdsfsf: inaccessible or not found
```
