### ISSUE TITLE
modpost: Found 3 section mismatch(es).

### ISSUE THREAD

**Issue by anuragpindoriya** [tiann/KernelSU#959]
**Describe the bug**
modpost: Found 3 section mismatch(es).

**To Reproduce**
Steps to reproduce the behaviour:
4. See the error

**Expected behaviour**

**Screenshots**
![image](https://github.com/tiann/KernelSU/assets/77160230/1e8f9cdc-3d79-4c16-a667-4a93a785b292)

**Smartphone (please complete the following information):**
 - Device: [Samsung-m51]
 - OS: [One-ui-5.1-android-12]
 - Version [5.1]

**Additional context**
MODPOST vmlinux.o
WARNING: modpost: Found 3 section mismatch(es).
To see full details build your kernel with:
'make CONFIG_DEBUG_SECTION_MISMATCH=y'
aarch64-linux-gnu-ld: warning: .tmp_vmlinux1 has a LOAD segment with RWX permissions
aarch64-linux-gnu-ld: fs/open.o: in function `SyS_faccessat':
/home/runner/work/android_kernel_samsung_sm6150/android_kernel_samsung_sm6150/out/../fs/open.c:383:(.text+0x6dc): undefined reference to `ksu_handle_faccessat'
aarch64-linux-gnu-ld: fs/read_write.o: in function `vfs_read':
/home/runner/work/android_kernel_samsung_sm6150/android_kernel_samsung_sm6150/out/../fs/read_write.c:455:(.text+0x804): undefined reference to `ksu_vfs_read_hook'
aarch64-linux-gnu-ld: fs/read_write.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `ksu_vfs_read_hook' which may bind externally can not be used when making a shared object; recompile with -fPIC
/home/runner/work/android_kernel_samsung_sm6150/android_kernel_samsung_sm6150/out/../fs/read_write.c:455:(.text+0x804): dangerous relocation: unsupported relocation
aarch64-linux-gnu-ld: /home/runner/work/android_kernel_samsung_sm6150/android_kernel_samsung_sm6150/out/../fs/read_write.c:455:(.text+0x808): undefined reference to `ksu_vfs_read_hook'
aarch64-linux-gnu-ld: /home/runner/work/android_kernel_samsung_sm6150/android_kernel_samsung_sm6150/out/../fs/read_write.c:456:(.text+0x83c): undefined reference to `ksu_handle_vfs_read'
aarch64-linux-gnu-ld: fs/stat.o: in function `vfs_statx':
/home/runner/work/android_kernel_samsung_sm6150/android_kernel_samsung_sm6150/out/../fs/stat.c:189:(.text+0x3cc): undefined reference to `ksu_handle_stat'
aarch64-linux-gnu-ld: fs/exec.o: in function `do_execveat_common':
/home/runner/work/android_kernel_samsung_sm6150/android_kernel_samsung_sm6150/out/../fs/exec.c:1868:(.text+0x1edc): undefined reference to `ksu_execveat_hook'
aarch64-linux-gnu-ld: fs/exec.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `ksu_execveat_hook' which may bind externally can not be used when making a shared object; recompile with -fPIC
/home/runner/work/android_kernel_samsung_sm6150/android_kernel_samsung_sm6150/out/../fs/exec.c:1868:(.text+0x1edc): dangerous relocation: unsupported relocation
aarch64-linux-gnu-ld: /home/runner/work/android_kernel_samsung_sm6150/android_kernel_samsung_sm6150/out/../fs/exec.c:1868:(.text+0x1ee0): undefined reference to `ksu_execveat_hook'
aarch64-linux-gnu-ld: /home/runner/work/android_kernel_samsung_sm6150/android_kernel_samsung_sm6150/out/../fs/exec.c:1871:(.text+0x1efc): undefined reference to `ksu_handle_execveat_sucompat'
aarch64-linux-gnu-ld: /home/runner/work/android_kernel_samsung_sm6150/android_kernel_samsung_sm6150/out/../fs/exec.c:1869:(.text+0x22d4): undefined reference to `ksu_handle_execveat'
aarch64-linux-gnu-ld: drivers/input/input.o: in function `input_handle_event':
/home/runner/work/android_kernel_samsung_sm6150/android_kernel_samsung_sm6150/out/../drivers/input/input.c:385:(.text+0x8564): undefined reference to `ksu_input_hook'
aarch64-linux-gnu-ld: drivers/input/input.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `ksu_input_hook' which may bind externally can not be used when making a shared object; recompile with -fPIC
/home/runner/work/android_kernel_samsung_sm6150/android_kernel_samsung_sm6150/out/../drivers/input/input.c:385:(.text+0x8564): dangerous relocation: unsupported relocation
aarch64-linux-gnu-ld: /home/runner/work/android_kernel_samsung_sm6150/android_kernel_samsung_sm6150/out/../drivers/input/input.c:385:(.text+0x856c): undefined reference to `ksu_input_hook'
aarch64-linux-gnu-ld: /home/runner/work/android_kernel_samsung_sm6150/android_kernel_samsung_sm6150/out/../drivers/input/input.c:386:(.text+0x8820): undefined reference to `ksu_handle_input_handle_event'
make[1]: *** [/home/runner/work/android_kernel_samsung_sm6150/android_kernel_samsung_sm6150/Makefile:1216: vmlinux] Error 1
make[1]: Leaving directory '/home/runner/work/android_kernel_samsung_sm6150/android_kernel_samsung_sm6150/out'
make: *** [Makefile:146: sub-make] Error 2
Error: Process completed with exit code 2.

**Comment by tiann** [comment]
https://github.com/tiann/KernelSU/issues/943#issuecomment-1716881151
