### ISSUE TITLE
更新完11238版本，出现NFC丢失，附日志

### ISSUE THREAD

**Issue by mozixuanqaq** [tiann/KernelSU#962]
**Smartphone:**
 - Device: Redmi K50
 - OS: MIUI14 
 - Version 14.0.23.6.5

**Additional context**

[KernelSU_bugreport_2023-09-16_22_38.tar.gz](https://github.com/tiann/KernelSU/files/12640921/KernelSU_bugreport_2023-09-16_22_38.tar.gz)

**Comment by tiann** [comment]
没有改过模块相关的东西，你需要检查一下是不是其他模块导致或者系统本身升级导致。

**Comment by mozixuanqaq** [comment]
已经解决，清除cache重启就可以了，十分感谢
