### ISSUE TITLE
KernelSu not write .allowlist

### ISSUE THREAD

**Issue by NyaruToru** [tiann/KernelSU#963]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Manager
2. Add apps to root permission
3. Check .allowlist
4. Empty

**Expected behaviour**
.allowlist is normal

**Smartphone (please complete the following information):**
 - Device: x3 nfc
 - OS: Android 11 4.14
 - Version 11

**Comment by tiann** [comment]
#943
