### ISSUE TITLE
keenelsu detection issues 

### ISSUE THREAD

**Issue by Hamood111** [tiann/KernelSU#964]
close the issue open I don't care just want u to know kernelsu app become a discoverer by TB Checker and there's no option to change package name also there's something new in native test 14 result (Evil Service (0x2) I have no idea what's that it's look like you start falling down before you start flying right by the way I just check magisk delta last version it's not discovered by TB Checker u should ask HuskyDG how he did it

**Comment by tiann** [comment]
Uninstall the manager.

**Comment by tiann** [comment]
You can't blame the earth for not having gravity because you can't poop.

**Comment by Hamood111** [comment]
Whatever mrs nasty American arrogance

**Comment by tiann** [comment]
How you treat others is how others will treat you. Since you are not polite, I will not be polite either.
