### ISSUE TITLE
[Feature] Kernel Command Line Parameter for Disabling KSU completely

### ISSUE THREAD

**Issue by Aryanxfa** [tiann/KernelSU#981]
### Is your feature request related to a problem? Please describe.

I'm always frustrated when I need to disable the Kernel SU, but there's no straightforward way to do it without requiring to chnage the kernel atleast for my non GKI device. I want this feature to be present so we can disable KSU by simply changing a kernel command line parameter at will and use magisk alongside it without conflicts.

### Describe the solution you'd like.

I'd like to request a feature in the KSU that allows users to disable Kernel SU by providing a command-line parameter to the kernel during boot. This would make it much more convenient and safer to enable or disable Kernel SU as needed without having to tinker with the actual kernel and would reduce compile time as their will no longer be a special variant for KSU. I am more than open to suggestions if someone has a even better way of doing this.

### Describe alternatives you've considered.

Manual Configuration: Currently, we have to make two separate kernel for KSU and non-KSU by manually modify changing files to disable Kernel SU, but this process is error-prone and can have unintended consequences. I believe Automating this through a command-line parameter is a safer and more user-friendly alternative.

**Comment by tiann** [comment]
You can try this commit: https://github.com/tiann/KernelSU/commit/2d9aebf64b30946ecb98c81bba1ebffdd64a8f2f

Since kernel cmdline has been migrated to bootconfig, i won't add it though.
