### ISSUE TITLE
Permission denied (os error 13) module fails to install

### ISSUE THREAD

**Issue by Franseven** [tiann/KernelSU#982]
**bug description**
Modules fail to install within the KernelSU latest app
Failing in the mounting fase of boot partition with permission denied (os error 13)

**To reproduce**
Select a module zip to install

**Expected behaviour**
The module should finish installation

**Screenshots**
![Screenshot_20230924_090534_KernelSU](https://github.com/tiann/KernelSU/assets/20824989/edfe426e-70df-414f-9647-446c84af665f)

**Smartphone:**
 - Samsung S9+
 - Android 13 Noble Rom 3.7.1 (One Ui 5.1.1)

**Additional context**
Root is present and works fine but modules can't be installed, installing magisk for example modules are able to be installed easily with no issue mounting the boot partition.

**Comment by tiann** [comment]
#943
