### ISSUE TITLE
not support on Android14 with colors OS

### ISSUE THREAD

**Issue by yangshuDBA** [tiann/KernelSU#985]
**can not boot on AndroidVersion14 
with colors13.1**
devices: PHB110  oneplus11 
osversion: colors 13.1
androidVersion: 14

**how do it**
1. download the  ' A13_5.15.94 kernel'
2. flush the boot with commond 'flash boot A13_5.15.94'
3. after reboot,  reboot every 120 Sec forever。

**Comment by tiann** [comment]
no log no fix

**Comment by snipking** [comment]
> no log no fix

same here. how to obtain logs ?
