### ISSUE TITLE
[Feature] Extract the "toggle permission" usage the use of "R.string.superuser" to a new string

### ISSUE THREAD

**Issue by xabolcs** [tiann/KernelSU#986]
### Is your feature request related to a problem? Please describe.

Lately I tried to improve the Hungarian translation (landed as da662133ae2d645310ac0c28d594f4f35d3e114b), but I failed to see that the ["superuser" string](https://github.com/search?q=repo%3Atiann%2FKernelSU+R.string.superuser&type=code) is used for both UI element ([bottom bar page](https://github.com/tiann/KernelSU/blob/afb04126f669379607b6b4087b392428c292132c/manager/app/src/main/java/me/weishu/kernelsu/ui/screen/BottomBarDestination.kt#L22C9-L22C9) and [the title of that page](https://github.com/tiann/KernelSU/blob/afb04126f669379607b6b4087b392428c292132c/manager/app/src/main/java/me/weishu/kernelsu/ui/screen/SuperUser.kt#L54)) and for a toggle (does the specific app have root permission).

As I went for "Applications"  to translate the former, the root permission toggle looks awful now. :see_no_evil: 

### Describe the solution you'd like.

It would be nice to split the string into two:
* one for the first two meaning: ([here](https://github.com/tiann/KernelSU/blob/afb04126f669379607b6b4087b392428c292132c/manager/app/src/main/java/me/weishu/kernelsu/ui/screen/BottomBarDestination.kt#L22C9-L22C9) and [there](https://github.com/tiann/KernelSU/blob/afb04126f669379607b6b4087b392428c292132c/manager/app/src/main/java/me/weishu/kernelsu/ui/screen/SuperUser.kt#L54))
* one for the root permission itself for using for that toggle [here](https://github.com/tiann/KernelSU/blob/afb04126f669379607b6b4087b392428c292132c/manager/app/src/main/java/me/weishu/kernelsu/ui/screen/AppProfile.kt#L164)

### Describe alternatives you've considered.

Sure, it's OK to me to use the same string for the two, but then please improve Weblate description to mention all the usages and meaning to help translators avoid such a mistake! :sweat_smile:

**Comment by tiann** [comment]
I won't split it because the second string need to be re-translated again for all other languages.
Maybe i can add some screenshot for that string in weblate.

**Comment by xabolcs** [comment]
> I won't split it because the second string need to be re-translated again for all other languages.

It's sad to hear that, but sure. :confused: 

> Maybe i can add some screenshot for that string in weblate.

That would be super helpful! :pray:
