### ISSUE TITLE
[bugs] userspace fstack-protector

### ISSUE THREAD

**Issue by bmax121** [tiann/KernelSU#990]
https://github.com/tiann/KernelSU/blob/0b8359a2e2b7a80bb40cd468c1bff5ebe9aafcdc/kernel/sucompat.c#L30
我在借鉴这个思路的时候发现，如果用户空间开启了 -fstack-protector ，会导致堆栈校验失败，指针的位置再往下移动点就好

**Comment by tiann** [comment]
KernelSU 的使用场景里面，要么使用 Java 层的 Runtime.exec 要么是在 adbd fork，基本不会遇到你说的那个问题。

**Comment by bmax121** [comment]
ksu 确实是稳定的，struct pt_regs 里的 sp 好像比用户的 sp 小一点，但是也碰到了例外，很奇怪。issue 先关了
