### ISSUE TITLE
Singpass 19.2 detected KSU

### ISSUE THREAD

**Issue by Lu5ck** [tiann/KernelSU#991]
**Describe the bug**
Singpass 19.2 detected KSU

**To Reproduce**
1. https://play.google.com/store/apps/details?id=sg.ndi.sp
2. Run the app
3. Got detected

**Expected behavior**
Not detected

**Smartphone (please complete the following information):**
 - Device: Poco X3 Pro
 - OS: CrDroid
 - Version: 9.8
 - Kernel self-compiled: https://github.com/Lu5ck/android_kernelsu_xiaomi_sm8150

**Additional context**
- I have no other module installed, just KSU and it got detected.
- Uninstalling KSU manager and Lucky Patcher doesn't help so I assume is not detecting app list.
- Uninstall KSU aka flashing back to stock kernel will allow the app to launch. I have manager installed at this point so I assume is not about app list.

PS: I cannot join the KernelSU telegram group too! The bot does not respond to `/start`!! Please fix.

**Comment by tiann** [comment]
How about flash a custom kernel without KernelSU?

**Comment by Lu5ck** [comment]
I flash this [NetHunter Kernel](https://forum.xda-developers.com/t/updated-13-0-kernel-nethunter-for-poco-x3-pro-vayu-2023-09-13.4627191/) which does not have KernelSU, can run singpass 19.2

I flash this [No Gravity Kernel](https://forum.xda-developers.com/t/kernel-overclocked-no-gravity-2023-08-28-protonclang.4328217/) which has Kernel SU 11210, singpass 19.2 detected root.

**Comment by Ardjlon** [comment]
Any screenshot? I already have my kernel with KSU, and when open the app I can login, but i dont have account, idk if happen after login...

**Comment by Lu5ck** [comment]
> Any screenshot? I already have my kernel with KSU, and when open the app I can login, but i dont have account, idk if happen after login...

No, no need for an account, just tired it by clearing data and cache.

> ![Screenshot_20230928-014148_crDroid Home.png](https://github.com/tiann/KernelSU/assets/6626980/8fde5098-bfbd-48aa-ab1c-9c9fa799e06b)

Are you running any modules? I tried with zero modules.

I am using non-gki, integrated manually with hooks, following the instructions at [here](https://kernelsu.org/guide/how-to-integrate-for-non-gki.html). Maybe missing some hooks?

**Comment by Ardjlon** [comment]
> > Any screenshot? I already have my kernel with KSU, and when open the app I can login, but i dont have account, idk if happen after login...
> 
> No, no need for an account, just tried it by clearing data and cache.
> 
> > ![Screenshot_20230928-014148_crDroid Home.png](https://user-images.githubusercontent.com/6626980/271070332-8fde5098-bfbd-48aa-ab1c-9c9fa799e06b.png)
> 
> Are you running any modules? I tried with zero modules.
> 
> I am using non-gki, integrated manually with hooks, following the instructions at [here](https://kernelsu.org/guide/how-to-integrate-for-non-gki.html). Maybe missing some hooks?
> 
> ![Screenshot_20230928-021406_crDroid Home.png](https://user-images.githubusercontent.com/6626980/271075772-96d10ce6-ebda-4e55-b82d-2dcb4ece2e0a.png)

Not here, I dont use modules, I can see the login options and I have not had any blocks, maybe an app on your list? I have problems with a banking app that closes when it detects MT explorer or ApkMod, among others.

Although I don't understand how it detected root for you from the browser

**Comment by Lu5ck** [comment]
The app opens a website for the deny page while the app closes, that's how it works.

I have tried uninstall root related apps but still detected root.
When I uninstall KSU by flashing back to stock kernel, even with those root apps installed, singpass will run so I doubt is app related.

Are you using kprobe ksu or manual ksu? And what version?

**Comment by belinux** [comment]
I can confirm, I tested the app on a Pixel 7 Pro and it's detecting root..

**Comment by Ardjlon** [comment]
Right now I getting warning...
![photo_2023-09-27_16-43-59](https://github.com/tiann/KernelSU/assets/18650083/ad23deca-9ce9-4797-9c33-8b68c98e2a99)

But

![photo_2023-09-27_16-44-00](https://github.com/tiann/KernelSU/assets/18650083/3171fb4e-a6ea-43d9-8f20-4251f72783b5)

**Comment by tiann** [comment]
I have identified the cause. Before I commit the fix, you can temporarily solve it like this: 

```
rm /data/adb/ksu/modules*.img
```

And then reboot.

**Comment by Lu5ck** [comment]
> I have identified the cause. Before I commit the fix, you can temporarily solve it like this:
> 
> ```
> rm /data/adb/ksu/modules*.img
> ```
> 
> And then reboot.


Can confirm that works. Thank you!

**Comment by ljlVink** [comment]
works!!

**Comment by ljlVink** [comment]
Emmm,I think it's not a good solution.If I delete modules*.img ,the modules installed on KSU wouldn't work.

假如我把modules.img删掉，那么模块全掉了，就是所说的无模块挂载状态下：

假如：
```sh
$ df -h /system
Filesystem       Size Used Avail Use% Mounted on
/dev/block/dm-11 744M 744M     0 100% /
```

假如安装了模块

```sh
$ df -h /system
Filesystem      Size Used Avail Use% Mounted on
KSU             242M 1.7M  233M   1% /system
```

**Comment by backslashxx** [comment]
> It detects the mountpoint of `/data/adb/modules` because kernelsu will not unmount it for kernel lower than 5.10

So what youre saying is that we can unmount it after boot? so, doable with a module? @HuskyDG

**Comment by wxt1221** [comment]
I try to run zygisk for kernelsu and shamiko. It works![Screenshot_20231001-082748_Termux.png](https://github.com/tiann/KernelSU/assets/74451279/ad226587-304c-4084-9552-1e384d1a58e4)

**Comment by Lu5ck** [comment]
> Could you show us the output of the following files in an app with no detections?
> 
> * `/proc/self/mounts`
> * `/proc/self/mountinfo`
> * `/proc/self/mountstats`

KSU kernel, with `/data/adb/modules.img` not deleted
[ksu_mounts.txt](https://github.com/tiann/KernelSU/files/12792430/ksu_mounts.txt)
[ksu_mountstats.txt](https://github.com/tiann/KernelSU/files/12792431/ksu_mountstats.txt)
[ksu_mountinfo.txt](https://github.com/tiann/KernelSU/files/12792432/ksu_mountinfo.txt)

Stock kernel
[stock_mounts.txt](https://github.com/tiann/KernelSU/files/12792433/stock_mounts.txt)
[stock_mountstats.txt](https://github.com/tiann/KernelSU/files/12792434/stock_mountstats.txt)
[stock_mountinfo.txt](https://github.com/tiann/KernelSU/files/12792435/stock_mountinfo.txt)

**Comment by belinux** [comment]
> I have identified the cause. Before I commit the fix, you can temporarily solve it like this:
> 
> ```
> rm /data/adb/ksu/modules*.img
> ```
> 
> And then reboot.

I've tried this, but after rebooting my revanced modules stopped working.. :(

**Comment by Ardjlon** [comment]
> > I have identified the cause. Before I commit the fix, you can temporarily solve it like this:
> > ```
> > rm /data/adb/ksu/modules*.img
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And then reboot.
> 
> I've tried this, but after rebooting my revanced modules stopped working.. :(

It's because the modules are there.
