### ISSUE TITLE
Nethunter Issues

### ISSUE THREAD

**Issue by nexstreamuser** [tiann/KernelSU#993]
I am using Kernelsu for sometimes now but i just installed kali nethunter and facing some issues with some tools in it such as DBUS not turning ON and many More Tools Arent Turing ON but When Shift To Magisk It works , I am Really looking Forward to DEVs to Fix It I am BIG fan of KERNELSU and Really Want DEV to LOOK into THIS PROBLEM . THANK YOU >>>>>>

**Comment by tiann** [comment]
Nothing to do with KernelSU.
