### ISSUE TITLE
HDFC BANK AND IMOBILE(ICICI Bank) both the apps are detecting root now

### ISSUE THREAD

**Issue by sandirickyroy** [tiann/KernelSU#997]
Smartphone that I'm using is: 
 - Device: POCO F4 (MUNCH)
 - OS: EVOLUTION X
 - Version: 7.9.5

Latest IMOBILE AND HDFC BANK both the apps are now detecting root. I tried deleting all the modules and checked but nothing happens.

![Screenshot_20231001-103624_KernelSU](https://github.com/tiann/KernelSU/assets/11662005/1e303a71-3490-4d6c-a25a-ab1cee54ec8c)
![Screenshot_20231001-103646_Kiwi Browser](https://github.com/tiann/KernelSU/assets/11662005/6a58c221-a4ae-498c-a920-1e851eefccfc)
![Screenshot_20231001-103653_Kiwi Browser](https://github.com/tiann/KernelSU/assets/11662005/79959f21-f2fd-4eda-9b09-8e7ee75739a4)

**Comment by tiann** [comment]
https://github.com/tiann/KernelSU/issues/991#issuecomment-1738858519

**Comment by justiriser** [comment]
> [#991 (comment)](https://github.com/tiann/KernelSU/issues/991#issuecomment-1738858519)

any fix coming?
after following this, all modules stopped working 😒

**Comment by Coconutat** [comment]
> > [#991 (comment)](https://github.com/tiann/KernelSU/issues/991#issuecomment-1738858519)
> 
> any fix coming? after following this, all modules stopped working 😒

Of course it will stop working.  Because deleting the module.img cancels the module mount point.

**Comment by sandirickyroy** [comment]
Nothing works.
Now Axis Mobile app has started detecting root.

**Comment by lovwanshichetan** [comment]
> Nothing works.
> Now Axis Mobile app has started detecting root.

It's working fine here 🙂

**Comment by vsnthdev** [comment]
Just updated to the latest iMobile app for ICICI Bank and again it's broken 😔

**Comment by lovwanshichetan** [comment]
> Just updated to the latest iMobile app for ICICI Bank and again it's broken 😔

Use zygisk next & shamiko in kernel su. It should work fine.
