### ISSUE TITLE
The current KernelSU version 10990 is too low for the manager to function properly, Please upgrade to 11071 or higher!

### ISSUE THREAD

**Issue by zackgreen16** [tiann/KernelSU#998]
**Describe the bug**
KernelSU says that version 10990 is too low after updating to the latest version and stops functioning

**To Reproduce**
Steps to reproduce the behaviour:
1. Update KernelSU
2. Open KernelSU
3. See the error

**Expected behaviour**
KernelSU should work as normal, allowing you to set SuperUser permissions, Install modules and etc

**Screenshots**
![Screenshot_20231001-071936_KernelSU](https://github.com/tiann/KernelSU/assets/66157074/cc09d4b7-5693-47ce-b098-d7d719e67051)

**Smartphone (please complete the following information):**
 - Device: C3W6_AP108_4GB
 - OS: Android
 - Version 12L

**Additional context**
KernelSU not working and telling me to update yet I have already updated to the highest version

**Comment by tiann** [comment]
you should flash latest kernel, its version is too low, not only the manager app

**Comment by zackgreen16** [comment]
Oh sorry... I searched everywhere online and I never saw that...
Idk how to update since my system came preinstalled with KernelSU so I'll
try and find out
Thank you!!!! xoxo
